line/armeria

src/site/sphinx/server-basics.rst

I couldn't compile original sample code in documentation due to some trivial errors. (missing semicolon, undefined class)

Fix sample code

---

src/main/java/com/linecorp/armeria/client/ClientOption.java
src/main/java/com/linecorp/armeria/client/ClientOptions.java
src/main/java/com/linecorp/armeria/client/HttpConfigurator.java
src/main/java/com/linecorp/armeria/client/HttpRemoteInvoker.java
src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java
src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
src/main/java/com/linecorp/armeria/client/http/SimpleHttpRequestBuilder.java
src/main/java/com/linecorp/armeria/client/logging/KeyedChannelPoolLoggingHandler.java
src/main/java/com/linecorp/armeria/client/logging/LoggingClientCodec.java
src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java
src/main/java/com/linecorp/armeria/client/pool/KeyedChannelPool.java
src/main/java/com/linecorp/armeria/client/pool/SafeKeyedChannelPoolHandler.java
src/main/java/com/linecorp/armeria/server/RequestTimeoutException.java
src/main/java/com/linecorp/armeria/server/ServiceCallbackInvoker.java
src/main/java/com/linecorp/armeria/server/http/HttpService.java
src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
src/test/java/com/linecorp/armeria/client/thrift/ThriftClientCodecTest.java
src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java

Hi, this is a greetings PR which contains only fixes without impact. I hope you like it~
See each commit for details.

Minor fixes (mostly spelling)

---

src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
src/test/java/com/linecorp/armeria/server/ServerTest.java

Motivation:
When a ServiceInvocationHandler.invoke() raises an exception,
HttpServerHandler logs the exception in exceptionCaught() and closes the
connection immediately. Because it could be said that it's an
application-level failure, we could recover from the exception and
continue handling the next response.
Modifications:
- Modify HttpServerHandler so that it catches an exception raised by
ServiceInvocationHandler.invoke() and continues serving next requests
- Add a test case to ServerTest
- Miscellaneous style/indentation fixes in ServerTest
Result:
No more surprising disconnection

More robust exception handling in HttpServerHandler

---

src/main/java/com/linecorp/armeria/client/DecoratingClientCodec.java
src/main/java/com/linecorp/armeria/client/DecoratingInvocationHandler.java
src/main/java/com/linecorp/armeria/client/DecoratingRemoteInvoker.java

- Add DecoratingClientCodec
- Add DecoratingRemoteInvoker
- Add DecoratingInvocationHandler
/cc @synk

Add cient-side decorator classes

---

pom.xml
src/site/sphinx/_static/overrides.css
src/site/sphinx/conf.py

- Use a forked sphinx-maven-plugin instead of the outdated original
- Retrieve the project information from pom.xml in Sphinx conf.py

Upgrade to the latest Sphinx version

---

src/main/java/com/linecorp/armeria/client/HttpConfigurator.java
src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
src/test/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandlerTest.java
src/test/thrift/hbase.thrift

just fix some typos errors in comments :)

fix typos in comments

---

pom.xml

.. which includes the latest Pygments with the Thrift lexer

Upgrade sphinx-maven-plugin to 1.2.0.Final

---

src/main/java/com/linecorp/armeria/server/HttpServerHandler.java

Related: #51
Motivation:
Most web servers send a redirect when a client sends a non-existent path
that doesn't end with '/' and the path + '/' exists. We should do the
same in our HttpServerHandler
Modifications:
- Add handleNonExistentMapping() method to handle the case where
findServiceConfig(path) returns an empty mapping properly
- Add redirect() to send a redirect response
- Split channelRead() into smaller methods for readability
- handleHttp2Settings()
- handleRequest()
- handleNonExistentMapping()
- handleInvocationPromise()
- handleDecodeFailure()
- Reordered methods so that related methods are grouped together
Result:
You don't need to be careful anymore when you enter a URL that ends with
'/'. e.g. /docs

Redirect from /path to /path/ instead of 404

---

pom.xml
src/main/java/com/linecorp/armeria/server/tracing/TracingServiceInvocationHandler.java
src/test/java/com/linecorp/armeria/client/tracing/TracingRemoteInvokerTest.java
src/test/java/com/linecorp/armeria/server/tracing/TracingServiceInvocationHandlerTest.java

Also fixed the compilation errors caused by Brave API breakage

Upgrade dependencies to their latest stable versions

---

pom.xml

See https://github.com/netty/netty/pull/5064 for more information.

Upgrade to Netty 4.1.0.CR6 to fix DNS resolver issues

---

pom.xml
src/main/java/com/linecorp/armeria/client/HttpConfigurator.java
src/main/java/com/linecorp/armeria/server/ServerInitializer.java

- Netty 4.1.0.CR7
- Removed the workarounds that's not needed anymore
- https://github.com/netty/netty/pull/5077
- https://github.com/netty/netty/pull/5096
- SLF4J 1.7.21
- Tomcat 8.0.33
- jetty-alpn-agent 2.0.1

Upgrade dependencies

---

src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java

.. because it's protocol negotiation failure after all even if it's timeout.

Use SessionProtocolNegotiationException when protocol upgrade fails due to timeout

---

NOTICE.txt
licenses/LICENSE.brave.al20.txt
licenses/LICENSE.guava.al20.txt
licenses/LICENSE.jsonunit.al20.txt
licenses/LICENSE.jsr305.al20.txt
licenses/LICENSE.metrics.al20.txt
licenses/LICENSE.reflections.wtfpl.txt

.. for the dependencies added since last update

Add missing license files and notices

---

src/main/java/com/linecorp/armeria/client/ClientBuilder.java
src/main/java/com/linecorp/armeria/client/routing/DefaultWeightedEndpoint.java
src/main/java/com/linecorp/armeria/client/routing/Endpoint.java
src/main/java/com/linecorp/armeria/client/routing/EndpointGroup.java
src/main/java/com/linecorp/armeria/client/routing/EndpointGroupException.java
src/main/java/com/linecorp/armeria/client/routing/EndpointGroupInvoker.java
src/main/java/com/linecorp/armeria/client/routing/EndpointGroupRegistry.java
src/main/java/com/linecorp/armeria/client/routing/EndpointGroupUtil.java
src/main/java/com/linecorp/armeria/client/routing/EndpointSelectionStrategy.java
src/main/java/com/linecorp/armeria/client/routing/EndpointSelector.java
src/main/java/com/linecorp/armeria/client/routing/StaticEndpointGroup.java
src/main/java/com/linecorp/armeria/client/routing/WeightedEndpoint.java
src/main/java/com/linecorp/armeria/client/routing/WeightedRoundRobinStrategy.java
src/test/java/com/linecorp/armeria/client/routing/EndpointGroupUtilTest.java
src/test/java/com/linecorp/armeria/client/routing/StaticEndpointGroupTest.java

Client side load balancer

---

src/site/sphinx/server-basics.rst

I added space into the sample code since I found it while reading Armeria tutorial.

Add space to fix code format

---

pom.xml
settings/checkstyle/checkstyle-suppressions.xml
settings/checkstyle/checkstyle.xml
settings/intellij_idea/code_style.xml
settings/intellij_idea/inspection.xml

- Also add maven-checkstyle-plugin

Add tool settings for external contributors

---

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java

Motivation:
Recent TomcatService changes introduced the reference to
URLEncoder.DEFAULT, which is only available since Tomcat 8.5. Trying to
use pre-8.5 Tomcat will fail with a NoSuchFieldError.
Modifications:
- Do not use URLEncoder.DEFAULT but create one by ourselves.
Result:
Works with Tomcat 7.5 and 8.0 again

Make TomcatService compatible with pre-8.5 again

---

src/main/java/com/linecorp/armeria/common/http/FilteredHttpResponse.java
src/main/java/com/linecorp/armeria/common/logging/LogLevel.java
src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
src/main/java/com/linecorp/armeria/server/http/encoding/HttpEncodedResponse.java

- Extend FilteredHttpResponse instead of FilteredStreamMessage in
HttpEncodedResponse
- Add FilteredStreamMessage.beforeSubscribe()
- Add LogLevel.log(Logger, String)

Add FilteredHttpResponse

---

src/site/sphinx/_static/overrides.css
src/site/sphinx/_templates/versions.html

- Maven central
- Travis CI
- codecov.io

Add project badges to the web site

---

pom.xml
src/test/java/com/linecorp/armeria/server/docs/ServiceInfoTest.java

Use jsonunit for more robust assertion

Fix JSON comparison in ServiceInfoTest

---

src/main/java/com/linecorp/armeria/client/ClientOptions.java
src/main/java/com/linecorp/armeria/client/http/HttpClientDelegate.java
src/test/java/com/linecorp/armeria/client/http/HttpClientIntegrationTest.java

Change user-agent header to be overridable by request

---

pom.xml

- Brave 3.11.0
- Jackson 2.7.7
- Tomcat 8.5.5
- Netty TCNative BoringSSL (static) 1.1.33.Fork22
- Mockito 2.1.0-RC.1
- Checkstyle 7.1.1
- Sphinx Maven plugin 1.4.0.Final

Update the dependencies

---

grpc/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java

Motivation:
InsecureTrustManagerFactory from Netty creates an X509TrustManager which
accepts all certificates.
However, when server mandates the authentication of a client
certificate, JDK internally wraps a TrustManager with
AbstractTrustManagerWrapper unless it extends X509ExtendedTrustManager.
AbstractTrustManagerWrapper performs an additional check (DN
comparison), making InsecureTrustManager not insecure enough.
Modifications:
Temporarily fork Netty's InsecureTrustManagerFactory and make its
TrustManager implementation extend X509ExtendedTrustManager instead of
X509TrustManager.
Result:
ArmeriaGrpcServerInteropTest now passes even if OpenSSL is not
available.

Fix failing ArmeriaGrpcServerInteropTest

---

core/src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java

Motivation:
ClientRequestContext.path() includes a query string while
ServiceRequestContext.path() does not. We have a consistency problem
here.
Modifications:
- Include a query string into ServiceRequestContext.path()
Result:
Consistency

Include query string in ServiceRequestContext.path()

---

core/src/main/java/com/linecorp/armeria/client/http/HttpRequestSubscriber.java

Found the following stack trace:
java.lang.NullPointerException: sessionProtocol
at java.util.Objects.requireNonNull(Objects.java:228)
at com.linecorp.armeria.common.logging.DefaultRequestLog.start(DefaultRequestLog.java:48)
at com.linecorp.armeria.client.http.HttpRequestSubscriber.writeFirstHeader(HttpRequestSubscriber.java:143)
at com.linecorp.armeria.client.http.HttpRequestSubscriber$$Lambda$47/1162177271.run(Unknown Source)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
at …

Fix NPE in HttpRequestSubscriber

---

core/src/main/java/com/linecorp/armeria/server/Server.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerConfig.java

Make the number of boss I/O threads configurable

---

core/src/main/java/com/linecorp/armeria/internal/Types.java
core/src/main/java/com/linecorp/armeria/internal/thrift/ThriftServiceMetadata.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Converter.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Converters.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Delete.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Deserializers.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunction.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctionEntry.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctionImpl.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctions.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpService.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpServiceBuilder.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicPath.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Get.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Head.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/MappedDynamicFunction.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Methods.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Options.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/ParameterEntry.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Patch.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Path.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/PathParam.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Post.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Put.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/ResponseConverter.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/Trace.java
core/src/main/java/com/linecorp/armeria/server/http/dynamic/package-info.java
core/src/test/java/com/linecorp/armeria/server/http/HttpServiceTest.java
core/src/test/java/com/linecorp/armeria/server/http/TestConverters.java

This pull request resolves #150

Implement advanced request mapping

---

core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistryTest.java

.. which removes a wrong endpoint group.

Fix incorrect cleanup in EndpointGroupRegistryTest

---

tomcat/src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java

tomcat version logging was doing on TomcatVersion.java already.

Remove duplicated code for tomcat version logging (#394)

---

core/src/main/java/com/linecorp/armeria/client/http/HttpClientFactory.java

Remove unused delegate field at HttpClientFactory

---

tomcat/src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java
tomcat/src/test/java-shared/com/linecorp/armeria/test/webapp/WebAppContainerTest.java
tomcat/src/test/resources-shared/tomcat_service/echo_post.jsp

ref: https://github.com/line/armeria/issues/410
Please let me know if anything is missing. 😄

Fix issue of NPE that occur when request body is empty.

---

dependencies.yml
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaGrpcServerStream.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ServerCallImpl.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaGrpcServerStreamTest.java
it/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServer.java
it/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerBuilder.java
it/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java

Update grpc to 1.1.2

---

thrift/src/test/java/com/linecorp/armeria/it/metrics/DropwizardMetricsIntegrationTest.java

Motivation:
A metric-collecting client relies on the availability of RequestLog. A
RequestLog may not be available immediately after an invocation is
finished.
Modifications:
- Use a CountDownLatch to wait until all RequestLogs are collected
before the assertions
Result:
- Fixes #404
- No more flaky test

Fix flaky DropwizardMetricsIntegrationTest

---

core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java

Fix NPE in DefaultServiceRequestContext.toString()

---

build.gradle
thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServiceTest.java

- Work around the bug in the shadow plugin
- https://github.com/johnrengelman/shadow/issues/283
- Use the right line separator for Thrift DocService examples

Make Armeria build fine again on Windows

---

core/src/test/java/com/linecorp/armeria/server/ServiceTest.java

.. for more consistent test coverage value

Add more test case to ServiceTest

---

core/src/main/java/com/linecorp/armeria/server/http/dynamic/Deserializers.java
core/src/test/java/com/linecorp/armeria/server/http/HttpServiceTest.java

Apply this change will make Deserializers support Boolean type.

Make dynamic http service's path variable support Boolean

---

core/src/main/java/com/linecorp/armeria/client/http/HttpClientPipelineConfigurator.java
core/src/test/java/com/linecorp/armeria/client/http/HttpClientSniTest.java
core/src/test/java/com/linecorp/armeria/server/SniServerTest.java

Motivation:
Client-side SNI does not work.
Modifications:
- Specify hostname and port when creating an SslHandler
- Improve SniServerTest and HttpClientSniTest so that SNI support is
tested thoroughly
Result:
- Client-side SNI works.

Fix client-side SNI support

---

core/src/main/java/com/linecorp/armeria/internal/http/Http1ObjectEncoder.java
thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java

HTTP1 splits the response when it goes over the size of a TLS frame, so it needs to be aware of pooled objects to not memory leak.

Handle ByteBufHttpData in Http1ObjectEncoder.

---

thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java

Ignore a flaky test until it's fixed

---

thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java

- Retry the test up to 10 times until it does not get
ClosedSessionException.
- Add FIXMEs so that we can fix this better later
Not an ideal fix but I think it's better than just ignoring it completely.

Work around the test failures in ThriftOverHttpClientTServletIntegrationTest

---

retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactory.java
retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaRetrofitBuilder.java
site/src/sphinx/client-retrofit.rst

.. also remove unused fields and parameters from ArmeriaRetrofitBuilder
and ArmeriaCallFactory

Fix outdated client-retrofit.rst

---

site/src/sphinx/client-grpc.rst
site/src/sphinx/client.rst
site/src/sphinx/server-grpc.rst

- client
- gRPC-web
- Unframed
- Blocking logic

Update gRPC docs.

---

core/src/main/java/com/linecorp/armeria/internal/metric/PrometheusMetricRequestDecorator.java

Motivation:
PrometheusMetricRequestDecorator.MetricAdapter is actually a Facade now that I have considered it.
Modifications:
- PrometheusMetricRequestDecorator.MetricAdapter renamed to PrometheusMetricRequestDecorator.MetricFacade

Correct the design pattern usage

---

grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
grpc/src/test/java/com/linecorp/armeria/internal/grpc/HttpStreamReaderTest.java

I had misunderstood that the subscription demand is only needed between data frames, but on the client-side it's also needed after the initial headers. Without correctly requesting a frame, the stream hangs.
Currently, if onSubscribe happens to be run before request, than two frames are requested at subscription time which allows this error to be hidden, but this is not guaranteed order, and in the opposite order, only one frame is correctly requested (for some reason I reliably trigger the latter behavior on a server I am developing, not sure yet why I'd see such different behavior than the unit tests). Anyways, I have tweaked the initial request semantics to not allow this dual-behavior for clarity.

Ensure an HTTP object is requested after reading headers in a gRPC stream.

---

core/src/main/java/com/linecorp/armeria/server/http/healthcheck/ManagedHttpHealthCheckService.java
core/src/test/java/com/linecorp/armeria/server/http/healthcheck/ManagedHttpHealthCheckServiceTest.java

-Add SettableHttpHealthCheckService implementation
#511

Implement SettableHttpHealthCheckService

---

core/src/main/java/com/linecorp/armeria/client/SessionOption.java
core/src/main/java/com/linecorp/armeria/client/SessionOptions.java
core/src/main/java/com/linecorp/armeria/client/http/HttpClientPipelineConfigurator.java
core/src/test/java/com/linecorp/armeria/client/SessionOptionsTest.java
core/src/test/java/com/linecorp/armeria/client/http/HttpClientSniTest.java
core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java
testing/src/main/java/com/linecorp/armeria/testing/server/webapp/WebAppContainerTest.java
thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java

Allow arbitrary customization of client SslContext.

---

core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java

Motivation:
Need to fix flaky tests.
Modifications:
- Relax the assertions a little bit, like in #636
- Increase the timing tolerance of responseTimeout and reduce backoff delay so
when unexpected exception happens which adds 3200 milliseconds to test, still pass the test
Result:
- Fix #666

Fix flaky tests in RetryingHttpClientTest

---

core/build.gradle

- Sort the dependencies of core/build.gradle
- Fix the incorrect comment related with ProGuarding Caffeine

Clean up the build script

---

core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java

- Correct some typos in the javadoc comment of com.linecorp.armeria.common.util.Exceptions methods

Correct typo

---

core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java

#delegate() and #subscribe() may call from different thread, and there is a timing issue that both method won't call subscribeToDelegate method. Apply this change will fix the problem and solve leaking subscriber issue too.

Fix DeferredStreamMessage may not call subscribeToDelegate method.

---

core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java

Fix factory method to not cause infinite recursion.

---

site/src/sphinx/_static/overrides.css

- Change the text alignment of list items to 'justify'
- Adjust bottom margin and padding of list items

Improve the site stylesheet

---

core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java

.. until the efficienty issues with WindowSketchQuantiles are resolved
See https://github.com/micrometer-metrics/micrometer/issues/139

Switch from WindowSketchQuantiles to CKMSQuantiles

---

spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring-boot/autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java

Use global MeterRegistry if MeterRegistry bean is not present

---

core/src/main/java/com/linecorp/armeria/internal/DefaultValues.java
core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java
core/src/main/java/com/linecorp/armeria/server/annotation/Default.java
core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceBuilderTest.java
core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java

Modifications:
- Change '@Optional' to '@Default' to avoid conflicting with java.util.Optional<T>
- Support 'Optional<T>' as a type of arguments

Support Optional<T> type for annotated services

---

core/src/main/java/com/linecorp/armeria/server/Service.java
core/src/main/java/com/linecorp/armeria/server/file/HttpFileService.java

Related to https://github.com/line/armeria/issues/440
TODOs:
* Use AsyncLoadingCache instead of LoadingCache
* ~~Expose cache stats~~

Replace HttpVfs entry cache to Caffeine cache

---

core/src/test/java/com/linecorp/armeria/client/Http2ClientSettingsTest.java
core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java

Fix buffer leaks in unit tests

---

core/src/main/java/com/linecorp/armeria/client/Endpoint.java
core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistry.java
core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointSelector.java
core/src/main/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java

Make EndpointSelector.select() aware of current request

---

core/src/test/java/com/linecorp/armeria/common/metric/MoreMetersTest.java

It is possible that a summary or a timer is registered already before
running MoreMetersTest. If that's the case, `armeria.hdrHistogram.count`
will not be 0 unlike the assumptions in `MoreMetersTest`.

Fix incorrect assertions in MoreMetersTest

---

core/src/main/java/com/linecorp/armeria/common/metric/RollingHdrQuantiles.java
core/src/test/java/com/linecorp/armeria/common/metric/RollingHdrQuantilesTest.java

Motivation:
DoubleRecorder from HdrHistogram can throw
ArrayIndexOutOfBoundsException even if auto-resize is enabled for its
DoubleHistograms when the range of values is too wide. For example, when
a histogram contains 0.000000001 (1 nanosecond), it can only contain up
to 16, which is way too small for our use case.
Modifications:
- Limit the minimum value to 0.001 (1 millisecond)
- Limit the maximum value to the extent that does not trigger
ArrayIndexOutOfBoundsException
- Fix an overflow bug in rotate() method due to incorrect cast order
Result:
ArrayIndexOutOfBoundsException should not be raised even if too small or
big value is recorded.

Fix ArrayIndexOutOfBoundsException from HdrHistogram

---

core/src/main/java/com/linecorp/armeria/client/Clients.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/UserClient.java

Customize ClientRequestContext when creating requests

---

core/src/main/java/com/linecorp/armeria/common/metric/RollingHdrQuantiles.java

To be honest, I'm not sure why Recorder throws an
IndexOutOfBoundsException which is not specified in the API
specification, but we have to deal with it.
Note that this is just a stopgap solution until we upgrade to Micrometer
1.0.0-rc.4.
Fixes #827

Fix IndexOutOfBoundsException in RollingHdrQuantiles

---

zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/ZooKeeperConnector.java

Motivation:
KeeperException.NoNodeException may be thrown when iterating over the
children of a node if they were removed by other party during iteration.
Modifications:
- Handle NoNodeException in ZooKeeperConnector.notifyChange()
Result:
- Robustness

Fix KeeperException.NoNodeException in ZooKeeperConnector

---

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerConfig.java

add netty option related to HTTP/1.

Make the parameters related with HTTP header decoding configurable (#829)

---

core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java

PublisherBasedStreamMessage may not invoke Subscriber.onSubscribe() on a
given situation:
1. Publisher invokes AbortableSubscriber.onSubscribe().
2. AbortableSubscriber.onSubscribe() sets 'subscription'.
3. AbortableSubscriber.onSubscribe() schedules onSubscribe0() that
invokes user's Subscriber.onSubscribe() to run on an EventLoop.
4. abort() is requested from the EventLoop in step 3 before user's
Subscriber.onSubscribe() is invoked by onSubscribe0(). The abortion
(cancelOrAbort0(boolean)) is performed before onSubscribe0() of
the step 3 is executed because abort() will be invoked directly.
5. The Subscriber is not notified because cancelOrAbort0() replaced
the 'subscriber' field before onSubscribe0() is run.
This commit also contains the following changes:
- Fix a bug where …

Fix a race condition in PublisherBasedStreamMessage

---

core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java

Motivation:
If we are sure there will be neither content nor trailing headers in a
request, we do not need to send a streaming request to a Service but
just a closed one. This has the following advantages:
- We can use FixedStreamMessage-based HttpRequest implementations later.
- AbortedStreamException will never be instantiated when handling the
request.
Modifications:
- Close the decoded HttpRequest if it is sure there will neither content
nor trailing headers.
Result:
- Reduced instantiation of AbortedStreamException

Close decoded HttpRequest sooner if possible

---

zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java

Ignore ZooKeeperRegistrationTest.testConnectionRecovery()

---

core/src/main/java/com/linecorp/armeria/common/HttpData.java

* HttpData  charset of.. -> charset to use..

Rephrased documentation related to charset

---

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java

Motivation:
`AbstractStreamMessageDuplicator` was desgined initially to be used in the situation where
a lot of threads are competing for the resourses.
However, the `Duplicator` is created and used during retrying mostly, which is conducted by
an event loop.
So, I thought it would be better if we remove the volatile fields as possible and use the event loop to
syncronize the access using `doSomeMethod` as we do in `EventLoopStreamMessage`.
Modifications:
- `StreamMessageProcessor` in `AbstractStreamMessageDuplicator` has an `EventExecutor`
- Use the `EventExecutor` where syncronization is needed
Result:
- Better dupplicator less bugs

Change AbstractStreamMessageDuplicator to have an EventExecutor

---

site/build.gradle

.. by updating sphinx-gradle-plugin to 1.0.6

Update Sphinx to 1.6.5

---

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java
core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceExceptionHandlerTest.java

Modifications:
- Ensure that the result of calling `invoke()` method is casted to CompletionStage<?> for the case of request aggregation.

Fix a bug in AnnotatedHttpServiceMethod

---

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java

Modifications:
- Do not ignore an exception from RequestConverterFunction#convert.
- Do not allow returning `null` from RequestConverterFunction#convert.

Throw an exception raised while converting a request to a `@RequestObject` instance

---

site/src/sphinx/_static/overrides.css
site/src/sphinx/server-access-log.rst

- Fix table overflow problem
- Fix syntax highlighting issue in server-access-log.rst

Improve the look of the site

---

dependencies.yml
gradle/wrapper/gradle-wrapper.properties

* netty: 4.1.17.Final -> 4.1.19.Final
* reactive-streams: 1.0.1 -> 1.0.2
* spring-boot: 1.5.8.RELEASE -> 1.5.9.RELEASE
* tomcat: 8.5.23 -> 8.5.24
* hibernate-validator: 6.0.5.Fina -> 6.0.7.Final
* json-unit: 1.25.1 -> 1.27.0
* mockito: 2.12.0 -> 2.13.0
* gradle: 4.3.1 -> 4.4.1

Dependency update

---

build.gradle
tomcat8.0/build.gradle

- shadow plugin 2.0.1 -> 2.0.2
- snakeyaml 1.18 -> 1.19
- protoc 3.4.0 -> 3.5.1
- tomcat 8.0.47 -> 8.0.48

Update more dependencies

---

core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java

Motivation:
The pull request #929 introduced the violation of RFC 7540 section
8.1.2.5:
> If there are multiple Cookie header fields after decompression, these
> MUST be concatenated into a single octet string ..
Modifications:
- Merge and split cookies in a correct and robust way using StringJoiner
and Splitter
- Inline Http2ToHttpHeaderTranslator which is used only in a single place
Result:
- Fixes #930

Fix incorrect cookie split

---

site/build.gradle
site/src/sphinx/conf.py

- Add sphinxcontrib.httpdomain
- Add sphinxcontrib.inlinesyntaxhighlight
- Update sphinx-gradle-plugin to 1.1.0

Add HTTP domain extension to Sphinx configuration

---

site/src/sphinx/_static/overrides.css

- Fix a problem where a table has small width
- Fix a problem where unnecessary scrollbars are shown

Fix poor table rendering in Chrome

---

testing-internal/src/main/resources/logback-test.xml

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/TrafficLoggingHandler.java#L34

Fix logback setting for TrafficLoggingHandler

---

grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java

Implement ServiceWithPathMappings in UnframedGrpcService too.

---

site/src/sphinx/advanced-zookeeper.rst
zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroup.java
zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java

Resolves #1005, with a typo fix.

Remove ZooKeeperEndpointGroup#Mode

---

core/src/main/java/com/linecorp/armeria/server/ServerListenerBuilder.java
core/src/test/java/com/linecorp/armeria/server/ServerListenerTest.java

Implement ServerListenerBuilder

---

zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanContextUtil.java
zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java

Trivial fix, it will save a very small memory usage per HttpTracingService

Make closeSpan method static

---

core/src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java

Motivation:
DefaultKeyedChannelPool.doClose() can trigger
ConcurrentModificationException while iterating over allChannels.
Modifications:
- Do not trigger Channel.close() operation while iterating over
allChannels. Call Channel.close() later.
Result:
- Fixes #1022

Fix ConcurrentModificationException in DefaultKeyedChannelPool.doClose()

---

site/src/sphinx/server-basics.rst

Not to use `respond` method.
Use lambda if it can.
~~Use `:name` style instead of `{name}` style.~~
Use `:name` style to indicate that Armeria allows it.
Fix the lack of braces.
https://github.com/line/armeria/issues/1041
Including some of https://github.com/line/armeria/pull/999
Should I include `import`?

Do not use deprecated methods in documentation

---

grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java

Motivation:
On CI, it seems relatively common for the socket to get killed during
some of the test cases in GrpcClientTest.
Modifications:
- Just log the error instead of failing it.
Result:

Ignore flaky test (GrpcClientTest.halfDuplexCallShouldSucceed) in CI

---

site/src/sphinx/advanced-retry.rst

- Remove the use of `Optional` in the API
- Mention that `onServerErrorStatus()` retries on an exception as well
- Fix indentation

Fix automatic retry documentation

---

jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java

[TRIVIAL] Remove unused JettyService#PATH_SPLITTER

---

settings/checkstyle/checkstyle.xml

Related to https://github.com/line/centraldogma/pull/176

Allow empty lambdas in the check style

---

site/src/sphinx/server-annotated-service.rst

related issue: https://github.com/line/armeria/issues/1106

Add documentation for BeanRequestConverterFunction

---

dependencies.yml

Update protobuf-jackson dependency

---

core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java

Motivation:
Currently there is no way to get rpc method name from access log.
Modifications:
- Write rpc method name to request line log.

Write rpc method name to access log

---

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java
core/src/main/java/com/linecorp/armeria/server/annotation/DecoratorFactory.java
core/src/main/java/com/linecorp/armeria/server/annotation/DecoratorFactoryFunction.java
core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorator.java
core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecoratorFactoryFunction.java
core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecorators.java
core/src/main/java/com/linecorp/armeria/server/annotation/decorator/RateLimitingDecorator.java
core/src/main/java/com/linecorp/armeria/server/annotation/decorator/RateLimitingDecoratorFactoryFunction.java
core/src/main/java/com/linecorp/armeria/server/annotation/decorator/RateLimitingDecorators.java
core/src/main/java/com/linecorp/armeria/server/annotation/decorator/package-info.java
core/src/main/java/com/linecorp/armeria/server/throttling/RateLimitingThrottlingStrategy.java
core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceDecorationTest.java
core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServicesTest.java
site/src/sphinx/server-annotated-service.rst

Modifications:
- Add `@DecoratorFactory` annotation and `DecoratorFactoryFunction` interface.
- Add `@LoggingDecorator` annotation and `LoggingDecoratorFactoryFunction` in order to prove concept.
Result:
- Closes #1010

Add user-defined decorator for annotated HTTP services

---

site/src/sphinx/_static/overrides.css
site/src/sphinx/client-service-discovery.rst
site/src/sphinx/client.rst

Modifications:
- Add client-service-discovery.rst which explains client-side load
balancing and service discovery
- Update `overrides.css` so that the menu items look better, especially
monospaced ones

Add documentation about client-side load balancing and service discovery

---

site/src/sphinx/server-docservice.rst

Motivation:
It is not clear from `server-docservice.rst` that `DocService` supports
gRPC services or not.
Modifications:
- Update the code examples so that it is clear that both Thrift and gRPC
services are supported
Result:
- gRPC users are happy.

Add gRPC example to DocService documentation

---

spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java

Fixes https://github.com/line/armeria/issues/1141

Provides a way to specify exception/request/response handlers in AnnotatedServiceRegitrationBean

---

spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractServiceRegistrationBean.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/HttpServiceRegistrationBean.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceRegistrationBean.java
spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java

Fixes https://github.com/line/armeria/issues/1080

Register multiple decorators in service registration beans

---

thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java

Fix flakiness in DropwizardMetricsIntegrationTest

---

core/src/main/java/com/linecorp/armeria/server/Server.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
core/src/test/java/com/linecorp/armeria/server/ServerTest.java

solve https://github.com/line/armeria/issues/1009

Provide a way to specify Netty ChannelOptions for Server

---

core/src/test/java/com/linecorp/armeria/internal/metric/MicrometerUtilTest.java
settings/checkstyle/checkstyle.xml

Patche from https://github.com/line/line-bot-sdk-java/pull/241

Remove Java6Assertions (use org.assertj.core.api.Assertions instead)

---

core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java

Motivation:
On TLS handshake failure, we see at least two log messages - one from
the handshake failure event and another from `exceptionCaught()`.
There's no point of logging about TLS-related exceptions after TLS
handshake failure, since the connection is irrecoverable and will be
closed automatically by Netty.
Modifications:
- Do not log TLS-related exceptions after TLS handshake failure, while
logging non-TLS exceptions properly.
Result:
Less noisy log

Clean up logging related with TLS handshake failures

---

core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
dependencies.yml
examples/README.md
examples/spring-boot-tomcat/build.gradle
examples/spring-boot-tomcat/src/main/java/example/springframework/boot/tomcat/HelloConfiguration.java
examples/spring-boot-tomcat/src/main/java/example/springframework/boot/tomcat/HelloController.java
examples/spring-boot-tomcat/src/main/java/example/springframework/boot/tomcat/Main.java
examples/spring-boot-tomcat/src/main/resources/config/application.yml
examples/spring-boot-tomcat/src/test/java/example/springframework/boot/tomcat/HelloControllerTest.java
examples/spring-boot-tomcat/src/test/java/example/springframework/boot/tomcat/HelloIntegrationTest.java
examples/spring-boot-tomcat/src/test/resources/application-testbed.yml
settings.gradle
settings/checkstyle/checkstyle-suppressions.xml
settings/checkstyle/checkstyle.xml

- Added the first example `spring-boot-tomcat` as requested by many people
- Updated Checkstyle rules and suppressions to make sure the examples do not have a copyright header because they belong to the public domain.
- Added the constructor that accepts `Iterable<? extends HealthChecker>` to `HttpHealthCheckService`

Add the first example project

---

examples/README.md
examples/annotated-http-service/build.gradle
examples/annotated-http-service/src/main/java/example/armeria/server/annotated/ExceptionHandlerService.java
examples/annotated-http-service/src/main/java/example/armeria/server/annotated/InjectionService.java
examples/annotated-http-service/src/main/java/example/armeria/server/annotated/MessageConverterService.java
examples/annotated-http-service/src/main/java/example/armeria/server/annotated/PathPatternService.java
examples/annotated-http-service/src/main/java/example/armeria/server/annotated/ServerFactory.java
examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedHttpServiceTest.java
settings.gradle

Motivation:
We provide official document for annotated HTTP service, but it is not ready-to-use on IDE. So, it would be useful to beginners if we provide working examples.
Modifications:
- Add `example.armeria.server` package

Add examples of annotated HTTP service

---

.post-release-msg

Motivation:
Because we have armeria-examples in a different repository, we need to include the instruction which copies the examples.

Update post release msg

---

zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java

This uses Brave's remote endpoint api.
See openzipkin/brave#747
Depends on #1328

Drops main compile dependency on io.zipkin.zipkin2:zipkin 

---

core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java

Motivation:
An `AssertionError` can be triggered when a user calls `StartStopSupport.start()`
or `stop()` because we do not switch the state into `STARTING` or `STOPPING`
in a single transaction.
Modifications:
- Enter `STARTING` or `STOPPING` before submitting a start/stop task.
- Roll back to `STOPPED` or `STARTED` if the task submission failed.
Result:
- Fixes #1351

Fix an assertion error caused by simultaneous `StartStopSupport.start()` or `stop()`

---

.appveyor.yml
.travis.yml
gradle.properties

- Add `-Xmx1280m` JVM option
- Enable on-demand project configuration

Add JVM and Gradle options to gradle.properties

---

grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframer.java

Actually, `firstFrame` was never set because I forgot to remove line 197 >< I guess the optimization previously in #1167 was just from the removal of `nextFrame`.
I tried finishing the `firstFrame` optimization but there was no difference so just getting rid of it.

Remove unnecessary firstFrame optimization.

---

grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java

I noticed gRPC upstream has this optimization so figured we should too. Unfortunately, it didn't change the result of the `empty` benchmark but probably still worth doing.
https://github.com/grpc/grpc-java/blob/master/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java#L200
After
```
Benchmark                                           (clientType)   Mode  Cnt      Score      Error  Units
c.l.a.g.downstream.DownstreamSimpleBenchmark.empty        OKHTTP  thrpt    5  29995.439 ±  263.738  ops/s
c.l.a.g.upstream.UpstreamSimpleBenchmark.empty            OKHTTP  thrpt    5  74463.286 ± 4337.546  ops/s
```
Before
```
Benchmark                                           (clientType)   Mode  Cnt      Score       Error  Units
c.l.a.g.downstream.DownstreamSimpleBenchmark.empty …
```

Special-case marshalling of empty protos.

---

core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java

Motivation:
f5251f1b83adf4fa9229927d8ac3134a13ed231f introduced the failure of
`HttpFileServiceTest.testFileSystemGet_modifiedFile()` on Windows.
Modifications:
- Update the last write time of the file explicitly so that there is no
chance of having the same last write time.
Result:

Fix failures in HttpFileServiceTest

---

dependencies.yml

Also upgrades micrometer to 1.1.0

Upgrade spring-boot dependency to 2.1.0

---

benchmarks/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java
core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClient.java
core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java
core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/main/java/com/linecorp/armeria/common/RpcResponse.java
core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java
core/src/main/java/com/linecorp/armeria/server/Server.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
thrift/src/main/java/com/linecorp/armeria/common/thrift/AsyncMethodCallbacks.java

Even less usage of CompletableFuture.whenComplete()

---

thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftCallService.java
thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java

Related: #1368 #1372
Motivation:
When a Thrift client sends a one-way call, it expects that the server
sends its response even before the call is actually handled.
Our current implementation sends a response after the call is handled,
which is not an expected behavior comparing to the official Thrift
implementation.
Modifications:
- Completed `RpcResponse` as soon as possible.
- Logged at WARN level when a one-way call fails instead of failing
`RpcResponse` because it's done already.
Result:
- Fixes #1368

Make one-way Thrift call responses sent early

---

dependencies.yml

See: https://github.com/trustin/sphinx-gradle-plugin/releases/tag/sphinx-gradle-plugin-2.3.1

Update sphinx-gradle-plugin to 2.3.1

---

core/src/main/java/com/linecorp/armeria/server/AnnotatedValueResolver.java

Modifications:
- Do not write a log message if the actual type is not one of the following types:
- `RequestContext` / `ServiceRequestContext`
- `Request` / `HttpRequest`
- `AggregatedHttpMessage`
- `HttpParameters`
- `Cookies`
Result:
- Closes #1485

Do not write a false log message from AnnotatedValueResolver

---

site/src/sphinx/server-annotated-service.rst

Fix invalid annotations

---

site/src/sphinx/server-basics.rst

Modifications:
- Add `Getting an IP address of a client who initiated a request` section to `server-basics.rst`.

Add docs about getting an IP address of a client who initiated a request

---

core/src/main/java/com/linecorp/armeria/internal/logging/CountingSampler.java

Currently `CountingSampler` synchronizes threads to manipulate an integer counter such that it doesn't go over `100`. An `AtomicInteger` and `mod` can do the same with much less overhead.
See https://github.com/openzipkin/brave/pull/857

Don't synchronize CountingSampler.

---

grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
site/src/sphinx/server-grpc.rst

Add option to run gRPC callbacks in blocking executor.

---

site/src/sphinx/server-cors-service.rst
site/src/sphinx/server-cors.rst
site/src/sphinx/server-grpc.rst
site/src/sphinx/server.rst

Added a document about CORS Service.

---

grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java

This test case exercises grpc-web with a top-level error. I don't see anything wrong with the server behavior at least for this case.
For #1586

Add test for grpc-web error case.

---

site/src/sphinx/server-annotated-service.rst

Modifications:
- Add `Using a composite annotation` section to `server-annotated-service.rst`.
Result:
- Documentation
- Closes #1608

Add docs about a composite annotation

---

core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
saml/src/main/java/com/linecorp/armeria/server/saml/SamlService.java

Motivation:
A user has no way to know why a `SamlService` is returning a 400 Bad
Request response.
Modifications:
- Add logging.
- Add more test cases for `DeferredStreamMessage` which is used by
`SamlService`, just in case the exception is not propagated.
Result:
- More information when something goes wrong with `SamlService`.

Add more loggings to `SamlService`

---

examples/README.md
examples/proxy-server/README.md
examples/proxy-server/build.gradle
examples/proxy-server/src/main/java/example/armeria/proxy/AnimationService.java
examples/proxy-server/src/main/java/example/armeria/proxy/Main.java
examples/proxy-server/src/main/java/example/armeria/proxy/ProxyService.java
examples/proxy-server/src/main/resources/index.html
settings.gradle

Motivation:
The more, the better.
Modification:
- Add a proxy server example.
Result:
- More examples.

Add a proxy server example

---

core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategyWithContent.java
site/src/sphinx/client-retry.rst

- Updated the Javadoc of `RetryStrategy` and `RetryStrategyWithContent`
so that it is more user-centric.

Clean up RetryStrategy and RetryStrategyWithContent Javadoc

---

grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocServicePlugin.java

Motivation:
While `GrpcDocServicePlugin` scans the gRPC services to retrieve their
`ServiceDescriptor`s, a `NullPointerException` can occur in some
services.
Modifications:
- Skip the service whose `getServiceDescriptor()` and
`getSchemaDesciptor()` return `null`.
- Skip the service whose `getSchemaDescriptor()` returns a descriptor
that's not a `ProtoFileDescriptorSupplier`.
Result:
- No more NPE
- Fixes #1705

Fix NPE while DocService scans gRPC services

---

spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/Ssl.java

Support disabling OpenSSL in Spring

---

grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientFactory.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcJsonUtil.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcTestUtil.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java

…RPC service / client.
Fixes #1696

Add options to customize the JSON marshalling behavior of gRPC service/client

---

core/src/main/java/com/linecorp/armeria/common/util/SystemInfo.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java

Fail fast when configuring a server for TLS but HTTP/2 is not available.

---

site/src/sphinx/index.rst

.. which contains more up-to-date and prettier content.

Update the introductory slides to the latest version

---

dependencies.yml

https://github.com/curioswitch/curiostack/releases/tag/protobuf-jackson-0.4.0
Fixes #1784

Update protobuf-jackson dependency.

---

core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
site/src/sphinx/server-basics.rst

Add document about per service configuration

---

docs-client/build.gradle

- Node.js 10.16.0
- Yarn 1.16.0

Update Yarn and Node.js

---

.github/CODEOWNERS

Add @ikhoon to the team

---

.github/CODEOWNERS

Remove @hyangtack from CODEOWNERS

---

core/src/main/java/com/linecorp/armeria/server/ServerConfig.java

Export blocking task executor metrics

---

dependencies.yml
site/src/sphinx/conf.py

This release includes [sphinxemoji](https://sphinxemojicodes.readthedocs.io/),
which will help us make our web site look more friendly in the future. :smile:

Update sphinx-gradle-plugin from 2.5.0 to 2.6.0

---

core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java

Realized I accidentally deleted this method in #1940

Restore deleted method.

---

site/src/sphinx/_templates/footer.html
site/src/sphinx/_templates/layout.html

.. so we have better picture of our users.

Add Google Analytics tracker to the web site

---

benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
core/src/main/java/com/linecorp/armeria/server/Server.java
core/src/test/java/com/linecorp/armeria/server/ServerTest.java
core/src/test/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckServiceTest.java
examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedHttpServiceTest.java
examples/grpc-service/src/test/java/example/armeria/grpc/HelloServiceTest.java
examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
examples/spring-boot-minimal/src/test/java/example/springframework/boot/minimal/HelloApplicationIntegrationTest.java
examples/spring-boot-tomcat/src/test/java/example/springframework/boot/tomcat/HelloIntegrationTest.java
examples/static-files/src/test/java/example/armeria/server/files/MainTest.java
spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java

Adds shortcut methods and changed codes in test.
Result:
- Fix #1956

Add a shortcut methods for Server::activeLocalPort()

---

examples/README.md
examples/annotated-http-service/build.gradle
examples/grpc-service/build.gradle
examples/saml-service-provider/build.gradle
examples/server-sent-events/build.gradle
examples/spring-boot-minimal/build.gradle
examples/static-files/build.gradle

Related: #1987 
Motivation:
I didn't know could start projects from IDE. Because when i get started with examples, i was not familiar with IDE. So i wanted to add and explain way to run examples easy.
Modification:
- Update `README.md`
- Update `build.gradle`, (Followed on existing code conventions)
Results:
- Easy way to start examples in CLI environment.
- It might be help for beginners like me.😄

 Add guide for how to run examples

---

site/src/sphinx/_static/center_page.js
site/src/sphinx/_static/overrides.css
site/src/sphinx/_templates/layout.html

GitHub Corners look better. See http://tholman.com/github-corners/

Switch from GitHub ribbons to corners

---

core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java

Motivation:
When an Armeria server is serving multiple protocols on the same port,
the last `ChannelHandler` in a `ChannelPipeline` is a `ProtocolDetectionHandler`,
which does not implement `exceptionCaught()` handler method properly.
As a result, a user will see the following warning message when the
connection is closed before the current session protocol is detected.
An exceptionCaught() event was fired, and it reached at the tail of
the pipeline. It usually means the last handler in the pipeline did
not handle the exception.
Modifications:
- Implement `ProtocolDetectionHandler.exceptionCaught()` properly.
- Make sure the connection is closed when protocol detection is not
finished in time.
Result:
- No more confusing warning log message on premature disconnection.
- Timeout is now …

Implement `ProtocolDetectionHandler.exceptionCaught()`

---

dependencies.yml
saml/src/test/java/com/linecorp/armeria/server/saml/SamlRequestIdManagerTest.java

As described in https://github.com/awaitility/awaitility/issues/140

Update Awaitility to 4.0.1

---

CONTRIBUTING.md

Inserted a section about test into CONTRIBUTING.md as following:
"We support both JUnit 4 and JUnit 5 for testing, but we recommend to use JUnit 5."
Also changed the protocol of all links to 'https' instead of 'http'.

Insert test section into CONTRIBUTING.md

---

gradle.properties
site/build.gradle

Motivation:
- We need to know better about our traffic.
Modifications:
- Inject Google Analytics tracker to Javadoc and Xref.
- Note that we injected the tracker to the web site already.
Result:
- Better knowledge about our customers.

Inject Google Analytics tracker to Javadoc and Xref

---

core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java

.. to avoid confusion with Armeria `Server`.
Also:
- made the nested test non-static
- renamed `JettyInterop` to `JettyInteropTest` to avoid test naming
warning

Use FQCN for Jetty `Server`

---

.appveyor.yml
.travis.install_jdk.sh
.travis.yml
CONTRIBUTING.md
README.md
build.gradle

Switch default build JDK to Java 12.

---

docs-client/src/containers/App/index.tsx
docs-client/src/containers/HomePage/index.tsx
docs-client/src/containers/MethodPage/DebugPage.tsx
docs-client/src/containers/MethodPage/EndpointPath.tsx
docs-client/src/containers/MethodPage/HttpHeaders.tsx
docs-client/src/containers/MethodPage/HttpQueryString.tsx
docs-client/src/containers/MethodPage/RequestBody.tsx
docs-client/src/lib/transports/grpc-unframed.ts

It'd be nice if you can check out the debug page in this branch locally to make sure it works ok - I tried various operations and think it's fine but there are a lot of possible variations.
Also fixes long-time pet peeve by prettifying gRPC unframed JSON.
Fixes #1949

Migrate debug page to hooks.

---

brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.java
brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextBuilder.java
brave/src/main/java/com/linecorp/armeria/internal/brave/TraceContextUtil.java
brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
brave/src/test/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextTest.java
brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java

Allow configuring a thread name pattern to treat as non-request threads.

---

site/src/sphinx/server-annotated-service.rst

I reflected this change in the document.
https://github.com/line/armeria/pull/2060

Fix document

---

site/src/sphinx/advanced-production-checklist.rst

Fix a wrong usage in documentation

---

build.gradle
dependencies.yml

Add hamcrest 2.2 dependency and upgrade json-unit 2.8.1 to 2.10.0

---

brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/UserClient.java
core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
core/src/main/java/com/linecorp/armeria/common/RequestContext.java
core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java
core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequest.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequestTest.java

Fix #2001 
Add UUID From RequestContext

Add UUID From RequestContext

---

spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/DocServiceConfigurator.java

Hi I'd like to solve this issue #2185 , I made some changes but I don't know if what I'm doing is the right choice, could you help me?

Allow customizing DocService when integrating with Spring Boot

---

core/src/main/java/com/linecorp/armeria/common/HttpHeadersJsonDeserializer.java
core/src/main/java/com/linecorp/armeria/common/HttpHeadersJsonSerializer.java
core/src/main/java/com/linecorp/armeria/common/MediaTypeJsonDeserializer.java
core/src/main/java/com/linecorp/armeria/common/MediaTypeJsonSerializer.java
core/src/main/java/com/linecorp/armeria/common/RequestHeadersJsonDeserializer.java
core/src/main/java/com/linecorp/armeria/common/ResponseHeadersJsonDeserializer.java
core/src/main/java/com/linecorp/armeria/server/docs/TypeSignatureJsonSerializer.java

Hide all Jackson Ser/deserializers from public API

---

core/src/main/java/com/linecorp/armeria/common/HttpStatus.java
core/src/test/java/com/linecorp/armeria/common/HttpStatusTest.java

This changeset added shortcut methods to HttpStatus class

Add HttpStatus.isSuccess() and other boolean getters

---

core/src/main/java/com/linecorp/armeria/common/HttpStatus.java
core/src/test/java/com/linecorp/armeria/common/HttpStatusTest.java

This changeset is a follow-up of #2435

Clean up `HttpStatus.is*()` and their tests

---

core/src/main/java/com/linecorp/armeria/server/GracefulShutdownSupport.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/test/java/com/linecorp/armeria/server/GracefulShutdownSupportTest.java

... when graceful shutdown is disabled.
Motivation:
When graceful shutdown is disabled, `pendingResponses` meter stays at
`0`, because `DisabledGracefulShutdownSupport.pendingResponses()` always
returns `0`.
Modifications:
- Use `LongAdder` to keep track of the number of pending responses.
- Minor optimizations:
- Do not add unnecessary callbacks when handling a request.
- Remove the `boolean` flags at the cost of losing 1-nanosecond
precision, which is OK because we check if quiet period is over
every 100 ms.
Result:
- `pendingResponses` meter yields a correct value even when graceful
shutdown is disabled.
- Potentially less contention under load, thanks to `LongAdder`.
- Tad bit less garbage due to less number of callbacks.

Fix a bug where `pendingResponses` meter is not updated

---

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriter.java
core/src/main/java/com/linecorp/armeria/common/stream/ClosedStreamException.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java

.. and deprecate `ClosedPublisherException`
Closes #2447

Replace `ClosedPublisherException` with `ClosedStreamException`

---

site/src/sphinx/server-docservice.rst

Added protobuf-maven-plugin configuration needed to expose services documentation to DocService.

Added maven configuration for DocService

---

core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
core/src/test/java/com/linecorp/armeria/common/HttpRequestTest.java

Motivation:
We forgot to release an empty buffer in `HttpRequest.of()`.
Modifications:
- Release an empty buffer in `HttpRequest.of()`.
- Simplify `if-else` blocks.
Result:
- Memory leaks be gone!

Fix buffer leak in `HttpRequest.of()`

---

site/src/sphinx/advanced-dropwizard-integration.rst

Fix: Dropwizard example reference

---

brave/src/main/java/com/linecorp/armeria/client/brave/ArmeriaHttpClientParser.java
brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
brave/src/main/java/com/linecorp/armeria/client/brave/ClientRequestContextAdapter.java
brave/src/main/java/com/linecorp/armeria/server/brave/ArmeriaHttpServerParser.java
brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
brave/src/main/java/com/linecorp/armeria/server/brave/ServiceRequestContextAdapter.java
brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientTest.java
brave/src/test/java/com/linecorp/armeria/client/brave/ClientRequestContextAdapterTest.java
brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceTest.java
brave/src/test/java/com/linecorp/armeria/server/brave/ServerRequestContextAdapterTest.java
dependencies.yml

there will be a brave 5.10.1 shortly, just raising for feedback as there is at least one question area.

Update Brave from 5.9.5 to 5.10.1

---

dependencies.yml

Release notes: https://github.com/dropwizard/dropwizard/releases/tag/v1.3.20

Upgrade to Dropwizard 1.3.20

---

CONTRIBUTING.md

Related discussion: https://github.com/line/armeria/pull/2566#discussion_r390072695

Require using Assert4J for test case assertions

---

core/src/main/java/com/linecorp/armeria/client/ClientDecoration.java
core/src/main/java/com/linecorp/armeria/client/ClientDecorationBuilder.java
core/src/test/java/com/linecorp/armeria/common/logging/ContentPreviewerTest.java
site/src/sphinx/advanced-structured-logging.rst
site/src/sphinx/client-decorator.rst

Related: #1117
To-do:
Add documentation for server side

Add documentation for the order of client decoration

---

core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java

Motivation:
`RetryingClient` and `RetryingRpcClient` currently stops working
completely when `RetryStrategy.shouldRetry()` or
`RetryStrategyWithContent.shouldRetry()` throws an exception.
Modifications:
- Catch the exceptions raised by the strategy implementation and fail
the upstream request with it.
Result:
- Faulty `RetryStrategy` does not make `RetryingClient` stop working
anymore.

Handle the exception raised by `RetryStrategy`

---

spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java

Motivation:
Received a report of the following stack trace:
java.lang.IllegalStateException: :status header does not exist.
at com.linecorp.armeria.common.DefaultResponseHeadersBuilder.build(DefaultResponseHeadersBuilder.java:50)
at com.linecorp.armeria.spring.web.reactive.ArmeriaServerHttpResponse.lambda$write$3(ArmeriaServerHttpResponse.java:186)
Modifications:
- Always set the default status when `:status` header is missing.
Result:
- No more `IllegalStateException` while building a WebFlux response.

Fix `IllegalStateException` while building a WebFlux response

---

site/src/sphinx/client-grpc.rst

Add documentation for gRPC-web for clients

Add gRPC-web to client documentation

---

core/src/main/java/com/linecorp/armeria/server/Server.java
core/src/test/java/com/linecorp/armeria/server/ServerTest.java

Hello, I tried to solve this easy issue, any comments are  welcome.

Add `Server.blockUntilShutdown()`

---

site/src/layouts/mdx.module.less

Remove excessive margin between a paragraph and sublist

---

brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
dependencies.yml

Updates to Brave 5.12.1

---

dependencies.yml

Should fix test flake in ITHttpServer

Updates to Brave 5.12.3

---

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java

just trivial PR for better error message for unexpected error

Improve the exception message for the case of unexpected type

---

brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
build.gradle
core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
core/src/main/java/com/linecorp/armeria/common/HttpResponseWriter.java
core/src/main/java/com/linecorp/armeria/common/logging/ContentPreviewerFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java
core/src/test/java/com/linecorp/armeria/common/stream/SubscriptionOptionTest.java
core/src/test/java/com/linecorp/armeria/server/TestConverters.java
core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
dependencies.yml
docs-client/package-lock.json
examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitClassAwareMeterIdPrefixFunction.java
rxjava/src/test/java/com/linecorp/armeria/common/rxjava/RequestContextAssemblyTest.java
rxjava2/src/test/java/com/linecorp/armeria/common/rxjava2/RequestContextAssemblyTest.java

https://errorprone.info/
It will be nice if we apply errorprone to avoid mistakes.

Apply errorprone

---

core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java

Sorry 😅 
https://ci.appveyor.com/project/line/armeria/builds/33592680
https://ci.appveyor.com/project/line/armeria/builds/33592680/job/96insdl7hd8ugk6c
https://ci.appveyor.com/project/line/armeria/builds/33592680/job/66hilw04qeib4fsa
https://ci.appveyor.com/project/line/armeria/builds/33592680/job/k8i184iv70qck9a1

Fix flaky test in ProxyClientIntegrationTest.testProxyWithH2C

---

site/src/pages/docs/client-service-discovery.mdx

Add missing parentheses in client-service-discovery.mdx

---

core/src/main/java/com/linecorp/armeria/common/HttpStatus.java

I matched the indent with other comments.

Fix indent in HttpStatus.java

---

core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java

Motivation:
A user sometimes creates a large number of `ClientFactory`s and forgets
to close them. This causes leaking resources such as:
- `DatagramChannel`s for DNS resolution
- `EventLoop`s if a user specified a new `EventLoopGroup`
Modifications:
- Use Netty's `ResourceLeakDetector` to keep track of
`DefaultClientFactory`, so that an `ERROR`-level message is logged
when it leaks.
Result:
- Easier to find a common user mistake.

Add leak detection to `DefaultClientFactory`

---

core/src/main/java/com/linecorp/armeria/common/unsafe/PooledHttpData.java

Thanks, @adriancole, for pinging us.

Fix an example in `PooledHttpData` Javadoc

---

site/src/components/article-list.module.less
site/src/pages/community/articles.json
site/src/pages/news/20200703-newsletter-1.mdx

- Add the newsletter vol. 1
- Update the article list
- Add @ikhoon's Reactive Streams articles
- Add @carlsagan21's LINE Bot API slides
- Update the article list stylesheet so that the table does not
overflow in a wide screen.

Add the newsletter vol. 1 / Update the article list

---

site/src/pages/docs/advanced-custom-attributes.mdx
site/src/pages/docs/advanced-dropwizard-integration.mdx
site/src/pages/docs/advanced-logging.mdx
site/src/pages/docs/advanced-unit-testing.mdx
site/src/pages/docs/client-circuit-breaker.mdx
site/src/pages/docs/client-custom-http-headers.mdx
site/src/pages/docs/client-retry.mdx
site/src/pages/docs/client-service-discovery.mdx
site/src/pages/docs/client-thrift.mdx
site/src/pages/docs/server-access-log.mdx
site/src/pages/docs/server-annotated-service.mdx
site/src/pages/docs/server-basics.mdx
site/src/pages/docs/server-cors.mdx
site/src/pages/docs/server-decorator.mdx
site/src/pages/docs/server-grpc.mdx
site/src/pages/docs/server-http-file.mdx

- Use Junit5 for `advanced-unit-testing.mdx`
- Use `<type://class#method()>` where possible

Use JUnit 5 in documentation

---

thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientBuilderTest.java

Motivation:
If an HTTP decorator such as `CircuitBreakerClient` throw an exception when Thrift client calls,
the `HttpRequest` is not aborted which lead to a buffer leak.
Modification:
- Abort `HttpRequest` in `THttpClientDelegate` if an HTTP decorator throw an exception.
Result:
- You no longer see the buffer leak when Thrift client is used with `ClientBreakerClient`.

Fix a buffer leak in Thrift client

---

site/src/pages/community/articles.json

https://medium.com/dev-genius/effective-grpc-9152bea2cf50

Add 'Effective gRPC' by @viktortnk

---

spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtilTest.java
spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java

…ettings.enableMetrics is true

Decorate all services with MetricCollectingService when integrates with Spring Boot

---

site/src/pages/community/articles.mdx

Thanks to @okue for the description.

Add a new community video from @okue

---

site/src/components/article.tsx
site/src/pages/community/articles.mdx

- Added a new article with slides: 'Spring BootユーザのためのArmeria入門'.
- Updated the `<Article />` component to allow specifying more than one type.
- Updated some articles to take advantage of this feature.
- Updated the `<Article />` component to allow specifying HTML in a description.

Add the new slides by @matsumana

---

examples/README.md
examples/context-propagation/dagger/src/main/java/example/armeria/contextpropagation/dagger/MainGraph.java
examples/context-propagation/manual/src/main/java/example/armeria/contextpropagation/manual/MainService.java
examples/context-propagation/reactor/build.gradle
examples/context-propagation/reactor/src/main/java/example/armeria/contextpropagation/reactor/Main.java
examples/context-propagation/reactor/src/main/java/example/armeria/contextpropagation/reactor/MainService.java
examples/context-propagation/rxjava/src/main/java/example/armeria/contextpropagation/rxjava/MainService.java
kotlin/src/test/kotlin/com/linecorp/armeria/server/SuspendingAnnotatedServiceTest.kt
settings.gradle

It would be nice if we have the Reactor context-propagation example as we have one for Rxjava.

Add Reactor context-propagation example

---

examples/README.md
examples/thrift/build.gradle
examples/thrift/src/main/java/example/armeria/thrift/HelloServiceImpl.java
examples/thrift/src/main/java/example/armeria/thrift/Main.java
examples/thrift/src/main/thrift/hello.thrift
examples/thrift/src/test/java/example.armeria.thrift/HelloServiceTest.java
examples/thrift/src/test/java/example/armeria/thrift/HelloServiceTest.java
settings.gradle

Motivation:
A Thrift example with `armeria-thrift*` is not offered officially.
Modifications:
- Add Thrift example
Result:
Close #2978

Add Thrift example

---

examples/README.md
examples/annotated-http-service-kotlin/build.gradle.kts
examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/ContextAwareService.kt
site/src/pages/docs/server-annotated-service.mdx
site/src/pages/docs/setup.mdx

Add documentation for the Kotlin Coroutines Section.
---

Add documentation for Kotlin coroutines

---

site/src/pages/community/articles.mdx

@aanrii Thanks a lot for writing an article that involves Armeria! Please feel free to let us know if you'd like to change the description of your article. (I just adapted one from the summary section of your post.)

Add a new community article by @aanrii

---

dependencies.yml
licenses/web-licenses.txt

There's a missing localEndpoint.ip bug this fixes.
Note: the build seemed to effect the licenses file, so I'm leaving that part

Updates to the latest Brave version

---

spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java

Motivation:
- The test sometimes fails. So I change to a simpler test.
Modifications:
- Fix `ArmeriaAutoConfigurationWithoutMeterTest`
Result:
- Close #3077

Test failure: com.linecorp.armeria.spring.ArmeriaAutoConfigurationWithoutMeterTest

---

core/src/main/java/com/linecorp/armeria/common/SerializationFormat.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcSerializationFormatProvider.java
grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePlugin.java
rxjava2/src/main/java/com/linecorp/armeria/internal/server/rxjava2/ObservableResponseConverterFunctionProvider.java
rxjava3/src/main/java/com/linecorp/armeria/internal/server/rxjava3/ObservableResponseConverterFunctionProvider.java
thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftSerializationFormatProvider.java
thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePlugin.java

Related https://github.com/openzipkin/zipkin/pull/3232
It could be DEBUG level instead of INFO because it might not be basic information to understand as @adriancole suggested.

Lower the log level for SPI implementations found

---

site/src/components/api-link.tsx
site/src/pages/release-notes/1.2.0.mdx
site/src/plugins/gatsby-remark-api-links.js

This PR also includes a way of displaying full parameter information in a method by appending `?full`.
```java
<type://Foo#bar(String, Integer)?full>
```

Add a release note for 1.2.0

---

core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtilTest.java
site/src/pages/docs/server-annotated-service.mdx

This is the documentation for
Add arbitrary param parsers #3143

Add documentation for annotated arbitrary types

---

core/src/main/java/com/linecorp/armeria/client/IgnoreHostsTrustManager.java
core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
core/src/main/java/com/linecorp/armeria/internal/common/HttpHeadersUtil.java
core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java
core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientAdditionalHeadersTest.java
core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerAdditionalHeadersTest.java
javadoc/build.gradle

Motivation:
Related #3159
Modifications:
- Use `disallowedList` instead of `blacklist`
- Use `allowedList` instead of `whitelist`
Result:
Closed #3159

Use disallowed list instead of blacklist and allow list instead of whitelist

---

core/src/main/java/com/linecorp/armeria/common/util/UnmodifiableFuture.java

nit: {@code

---

core/src/main/java/com/linecorp/armeria/common/util/AbstractOption.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactoryRegistry.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java

Use `ClassValue` for the map whose key is `Class`

---

site/src/pages/docs/server-service-registration.mdx

fix  EurekaUpdatingListenerBuilder  sample code.

Fix examples in server-service-registration.mdx

---

tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceDestroyedConnectorTest.java

Fix flaky test in TomcatServiceDestroyedConnectorTest

---

site/src/pages/community/articles.mdx

Add 'A Bootiful Podcast: Netty and Armeria founder Trustin Lee'

---

site/src/pages/community/articles.mdx

Added two articles:
- "Writing a Java library with better experience" at JPoint 2020
- "You are done with the asynchronous server if you know what request scoping is" at Naver Deview 2020

Add the articles of Request Scoping and Writing a Java library with better experience

---

eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java

If instance  no longer registered with Eureka,  try to re-registration.

Attempt re-registration when Eureka heart beat fails with 404 Not Found

---

site/src/pages/release-notes/1.4.0.mdx

Based on #3316 - please ignore the dependency updates.

Add release notes for 1.4.0

---

site/src/pages/docs/client-service-discovery.mdx
site/src/pages/docs/server-service-registration.mdx

Add documentation for Consul

---

it/grpc/kotlin/src/test/kotlin/com/linecorp/armeria/grpc/kotlin/HelloServiceImpl.kt
it/grpc/kotlin/src/test/kotlin/com/linecorp/armeria/grpc/kotlin/HelloServiceTest.kt

Fix typo of package name

---

site/src/pages/docs/client-factory.mdx

- Motivation: https://github.com/line/armeria/pull/3289#issuecomment-786480501
- Testing: N/A
- Open Issues : N/A

Remove final keyword from doc for simplicity

---

jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java

Motivation:
Jetty raises an `EofException` when a user attempted to write to a
closed output stream. Our `HttpTransport` implementation raises a
`ClosedStreamException` which is translated into `IOException:
ClosedStreamException` by Jetty. If we raised an `EofException`, Jetty
would have just rethrow it.
Modifications:
- Throw an `EofException` when failed to write to an `HttpResponse`
instead of throwing a `ClosedStreamException`.
Result:
- Compatibility

Raise `EofException` instead of `ClosedStreamException` in `JettyService`

---

site/src/pages/news/20200703-newsletter-1.mdx
site/src/pages/news/20210202-newsletter-2.mdx
site/src/pages/release-notes/0.84.0.mdx
site/src/pages/release-notes/0.85.0.mdx
site/src/pages/release-notes/0.86.0.mdx
site/src/pages/release-notes/0.88.0.mdx
site/src/pages/release-notes/0.89.0.mdx
site/src/pages/release-notes/0.90.0.mdx
site/src/pages/release-notes/0.90.3.mdx
site/src/pages/release-notes/0.91.0.mdx
site/src/pages/release-notes/0.92.0.mdx
site/src/pages/release-notes/0.93.0.mdx
site/src/pages/release-notes/0.94.0.mdx
site/src/pages/release-notes/0.95.0.mdx
site/src/pages/release-notes/0.98.0.mdx
site/src/pages/release-notes/0.98.5.mdx
site/src/pages/release-notes/0.99.0.mdx
site/src/pages/release-notes/0.99.3.mdx
site/src/pages/release-notes/0.99.6.mdx
site/src/pages/release-notes/0.99.9.mdx
site/src/pages/release-notes/1.1.0.mdx
site/src/pages/release-notes/1.2.0.mdx
site/src/pages/release-notes/1.3.0.mdx
site/src/pages/release-notes/1.4.0.mdx

.. so that users are informed better when they upgrade.
- Fixed a broken GitHub username

Make it clear that we introduced a breaking change in 1.3.0

---

core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java

Motivation:
When a request is timed out even before `HttpResponseSubscriber`
subscribes, a user will see the following log message:
```
Unexpected exception from a service or a response publisher:
com.linecorp.armeria.server.RequestTimeoutException
```
We should not log this because it's not expected.
Modifications:
- Do not log when a response stream fails due to cancellation or
timeout.
Result:
- Less noisy and less scary logging

Do not log `RequestTimeoutException` when timed out too early

---

core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
core/src/test/java/com/linecorp/armeria/common/DefaultHttpResponseDuplicatorTest.java

…sageDuplicator`
Motivation:
If the size of input object is larger than `maxSingalLength`,
`DefaultMessageDuplicator` rejects the message and aborts the upstream.
However it does not release the given input data.
https://github.com/line/armeria/blob/c60f7a317094be5ecbf3ade68ef55d15e40df938/core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java#L246-L248
Modifications:
- Release the input object if it is not passed to the downstream.
Result:
You no longer see leak objects when `DefaultStreamMessageDuplicator` raises `ContentTooLargeException`.

Fix a leak when `ContentTooLargeException` is raised by a `DefaultMessageDuplicator`

---

thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java

Motivation:
```
GracefulShutdownIntegrationTest > testBaseline() FAILED
Expecting:
<3587462600L>
to be between:
[2638880000L, 3438880000L]
at com.linecorp.armeria.it.server.GracefulShutdownIntegrationTest.testBaseline(GracefulShutdownIntegrationTest.java:156)
```
Modifications:
- Add an additional iteration to measure an accurate baseline
Result:
- Fixes #3554

Fix flaky GracefulShutdownIntegrationTest

---

core/src/main/java/com/linecorp/armeria/common/HttpHeaderGetters.java
core/src/main/java/com/linecorp/armeria/common/QueryParamGetters.java
core/src/main/java/com/linecorp/armeria/common/StringMultimap.java
core/src/main/java/com/linecorp/armeria/common/StringMultimapBuilder.java
core/src/main/java/com/linecorp/armeria/common/StringMultimapGetters.java
core/src/test/java/com/linecorp/armeria/common/HttpHeadersBaseTest.java
core/src/test/java/com/linecorp/armeria/common/QueryParamsBaseTest.java

Motivation: Close https://github.com/line/armeria/issues/3438
Modifications:
* Add getLastXxx for all getXxx

Add get last method for HttpHeaders and QueryParams

---

.github/workflows/actions_build.yml

Cancel duplicated GitHub Action workflows

---

core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java

Add `ServerBuilder.localPort` shortcuts

---

core/build.gradle
core/src/main/java/com/linecorp/armeria/internal/common/JavaVersionSpecific.java
core/src/main/java12/com/linecorp/armeria/internal/common/CurrentJavaVersionSpecific.java
core/src/main/java12/com/linecorp/armeria/internal/common/Java12ContextAwareFuture.java
core/src/main/java12/com/linecorp/armeria/internal/common/Java12ContextAwareMinimalStage.java
core/src/main/java12/com/linecorp/armeria/internal/common/Java12VersionSpecific.java
core/src/test/java/com/linecorp/armeria/internal/common/ContextAwareFutureTest.java
core/src/test/java/com/linecorp/armeria/internal/common/ContextFutureCallbackArgumentsProvider.java
core/src/test/java12/com/linecorp/armeria/internal/common/Java12ContextAwareFutureTest.java
core/src/test/java9/com/linecorp/armeria/internal/common/Java9ContextAwareFutureTest.java

Override new `CompletableFuture` methods in Java 12 for `ContextAwareFuture`

---

build.gradle
dependencies.yml
site/src/pages/release-notes/1.9.2.mdx

- Micrometer 1.7.0 -> 1.7.1
- ScalaPb 0.11.3 -> 0.11.4
- Spring Boot 2.5.1 -> 2.5.2
- Build
- finagle-serversets_2.13 21.5.0 -> 21.6.0
- graphql-dgs-client 4.2.0 -> 4.3.1
- kotlin-allopen 1.5.10 -> 1.5.20
- Proguard 7.1.0-beta1 -> 7.1.0

Add the release note for 1.9.2 and update dependencies

---

site/src/pages/docs/client-decorator.mdx

Add section describing how to modify/react to responses going through the Client decorators.

Extend doc for Client decorators

---

NOTICE.txt
dependencies.yml
examples/graphql-kotlin/build.gradle.kts
examples/graphql-kotlin/src/main/kotlin/example/armeria/server/graphql/kotlin/Main.kt
examples/graphql-kotlin/src/main/resources/schema.graphqls
examples/graphql-kotlin/src/test/kotlin/example/armeria/server/graphql/kotlin/GraphqlArmeriaClient.kt
examples/graphql-kotlin/src/test/kotlin/example/armeria/server/graphql/kotlin/GraphqlServiceTest.kt
licenses/LICENSE.graphql-kotlin.al20.txt
settings.gradle

Motivation:
This is to show the example to he/she using `Armeria` and `graphql-kotlin`.
Modifications:
- Add `graphql-kotlin`
- Add example
Result:
- Closes #3667

Add example for `graphql-kotlin`

---

examples/grpc/src/main/java/example/armeria/grpc/Main.java

Motivation:
This is my first contribution!
This PR contains only re-indent :)
Modifications:
- Re-indent some codes
Result:
- The behavior of the code is not affected

Re-indent gRPC example

---

core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java

Motivation:
```
Caused by:java.lang.NullPointerException: Cannot invoke "com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(java.lang.Throwable)" because "res" is null(Cannot invoke "com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(java.lang.Throwable)" because "res" is null)
at com.linecorp.armeria.client.HttpResponseDecoder.failUnfinishedResponses(HttpResponseDecoder.java:131)
at com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:415)
```
`HttpResponseDecoder` MUST be executed in an event loop. The NPE might be
caused by recursive calls of `failUnfinishedResponses()`.
Even though we use `Iterator`, a null reference could be returned.
Modifications:
- Add `closing` flag to ensure serialized executions …

Fix `NullPointerException` in `HttpResponseDecoder`

---

core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java

Motivation:
Address flaky test KeepAliveHandlerTest.testIdle
Modifications:
- Wait for meters to be recorded before performing assertions on them.
Result:
- Feel free to close this PR if you had a better idea in mind @ikhoon 🙏 🙇

Address flaky test KeepAliveHandlerTest.testIdle

---

site/src/pages/docs/advanced-streaming-backpressure.mdx

Source: https://github.com/line/armeria/pull/3397
Motivation:
To provide better reading experience to Armeria users.
Modifications:
- Paraphrased sentences
- Removed monospace + link styling (`<type:..`) from a section title
Result:
- Hopefully, readers will be able to use streaming response perfectly for their services.

Revise the doc for Streaming Response

---

.github/CODEOWNERS

Recently, @jrhee17 joined Armeria team in LINE.
Welcome, @jrhee17! 🎉

Add @jrhee17 to the team

---

core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupIntegrationTest.java

Fix flaky test in HealthCheckedEndpointGroupIntegrationTest

---

site/src/pages/community/articles.mdx

Recently, I found an awesome podcast in that @AngerM talked about Armeria
as a DoorDash's next-generation framework.
https://mattanger.dev/posts/2021-07-24-talking-kotlin/
Thanks, @AngerM for sharing your experience! ❤️

Add a new community podcast video

---

core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextTest.java

Motivation:
This PR contains only re-indent :)
Modifications:
- Re-indent [ServiceRequestContextTest](https://github.com/line/armeria/blob/master/core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextTest.java)
Result:
- The behavior of existing code is not affected

Re-indent ServiceRequestContextTest

---

core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java

Fix test failures in `KeepAliveHandlerTest`

---

site/src/pages/docs/advanced-metrics.mdx

Correct spelling from cumster to custom

Correct spelling from cumster to custom

---

docs-client/build.gradle
site/build.gradle

- Updated Node.js to 16.14 as a preparatory step for supporting building
on Apple Silicon (minor version bump)
- Updated NPM as well (micro version bump)

Update Node.js and NPM to 16.14.0 and 6.14.16

---

dependencies.yml

Modifications:
Removed unnecessary comment
Result:
- Closes #4188
no effect

Remove unnecessary comment

---

site/src/components/required-dependencies.tsx
site/src/pages/docs/setup.mdx

Motivation:
More users are starting to use Kotlin scripting, add this tab can help them copy-paste codes
Modifications:
- Add Gradle(Kotlin) tab to RequiredDependencies component
Result:
- Closes #4106 
- Test result:
| | Screenshot|
|---|---|
| Gradle |<img width="768" alt="image" src="https://user-images.githubusercontent.com/15963765/161285176-8e15843e-8b8b-4685-b60c-1b85cdd408ac.png"> |
| Kotlin| <img width="806" alt="image" src="https://user-images.githubusercontent.com/15963765/161010069-236b9cce-695f-46f5-b778-515de1c4e090.png">|
| Gradle| <img width="776" alt="image" src="https://user-images.githubusercontent.com/15963765/161285024-e6700f26-37e6-4f64-92bf-f2281d6b6450.png">|
| Kotlin| <img width="776" alt="image" src="https://user-images.githubusercontent.com/15963765/161285049-c15 …

Add Gradle(Kotlin) tab to RequiredDependencies component

---

tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceAccessLogTest.java

Motivation:
As #4182 , Tomcat AccessLog need to use CoyoteRequest's startTime
Modifications:
- Set startTime of CoyoteRequest
Result:
- Closes #4182

Add request start time to CoyoteRequest

---

site/src/pages/community/articles.mdx

Modification:
- Add an article of "Hello Armeria, Bye Spring":
- https://www.slideshare.net/GihwanKim10/hello-armeria-bye-spring
Co-authored by @ks-yim

Add article of Hello Armeria, Bye Spring

---

site/src/pages/community/articles.mdx

Also updated the description of 'Hello Armeria, Bye Spring' so it reads
better.

Add 'Building an Authentication Microservice at LINE' to the community article list

---

site/src/pages/release-notes/1.16.0.mdx

[Preview (PDF)](https://github.com/line/armeria/files/8512848/1.16.0.pdf)

Add the release note for 1.16.0

---

dependencies.yml
dropwizard2/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaServerFactory.java

Motivation:
bump dropwizard version so that we can pickup latest dependency updates
Modifications:
- update gradle dependencies yaml file

Update Dropwizard from 2.0.29 to 2.1.0

---

site/src/pages/docs/advanced-metrics.mdx

Motivation:
This explanation is useful for users who want to collect gRPC metrics with spring-boot-armeria
Result:
- Closes #4197

Add document for gPRC metrics with armeria-spring-boot

---

site/src/pages/release-notes/1.17.1.mdx

Motivation:
Modifications:
Result:

Add release note for 1.17.1

---

site/package-lock.json
site/package.json
site/src/layouts/base.tsx
site/src/layouts/star-begging.module.less
site/src/layouts/star-begging.tsx

Motivation:
If a user stays on Armeria site (https://armeria.dev) for more than 10 seconds, we can assume they might be interested in our project and like to star Armeria on GitHub.
Modifications:
- Add a small banner to the left corner of the Armeria site.
- It will be exposed 10 seconds after a user visits.
Result:
Gentle star marketing

Provide a way to conveniently give star Armeria from the site

---

.github/workflows/actions_build.yml
.github/workflows/publish-site.yml
site/build.gradle

Motivation:
Use `secrets.GITHUB_TOKEN` for fetching contributor list
Modifications:
- Pass `secrets.GITHUB_TOKEN` as `-PgithubToken`
Result:
- Less flakiness

Try specifying the github token when fetching the contributor list

---

site/src/pages/docs/server-grpc.mdx

Motivation:
Update  the document for https://github.com/line/armeria/pull/4585
Modifications:
- Update the document  in the gRPC Blocking service implementation section
Result:
- Let users know  that `@Blocking` annotation is available for gRPC services

Update the document in the gRPC Blocking service implementation section

---

site/src/pages/release-notes/1.22.1.mdx

Add release notes for 1.22.1

---

core/src/test/java/com/linecorp/armeria/server/CustomServerErrorHandlerTest.java

Motivation:
The test service is bound to `/bar` but the client sends a request to `/foo`.
https://github.com/line/armeria/blob/b16bc8d926e3b4ebb07b86b66a09cd1126121574/core/src/test/java/com/linecorp/armeria/server/CustomServerErrorHandlerTest.java#L78-L82 https://github.com/line/armeria/blob/b16bc8d926e3b4ebb07b86b66a09cd1126121574/core/src/test/java/com/linecorp/armeria/server/CustomServerErrorHandlerTest.java#L150-L154 I believe that is a typo. The test ensures an exception raised in a service is handled by an error hander at the virtual host.
The test has passed before #4552 is merged. Because `FallbackService` raised `HttpStatusException` that is recovered to 400 Bad Request.
Modifications:
- Fix `CustomServerErrorHandlerTest.defaultVirtualHost()` to send a request to `/bar`.
- …

Fix a wrong request path in `CustomServerErrorHandlerTest`

---

site/src/pages/docs/client-retrofit.mdx

Motivation:
Improve documentation
Modifications:
- Insert a missing word in a sentence
Result:
- The sentence makes sense!

Typo correction: add missing word

---

site/src/pages/docs/advanced-scala.mdx

Mention the `http4s-armeria` project on the Scala integration page

---

site/src/pages/release-notes/1.24.2.mdx

Add release notes for 1.24.2

---

it/flags-provider/src/test/java/com/linecorp/armeria/common/FlagsProviderTest.java

Reformat `FlagsProviderTest`

---

.github/actions/package-lock.json
.github/actions/package.json
.github/actions/post-release.ts
.github/actions/tsconfig.json
.github/workflows/publish-release.yml
.post-release-msg
core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitWithRetryTest.java

Motivation:
Automate the remaining release process to relieve the effort of the devs.
Modifications:
- Add `post-release.ts` that does some tasks after releasing a new version:
- Close milestone.
- Write release notes.
- Create a pull request to Central Dogma for updating Armeria version.
- Make `post-release.ts` triggered after finishing the `publish` task.
Result:
Enhanced release workflows.

Automate post release process

---

site/src/pages/community/developer-guide.mdx

Add documentation on gradle enterprise integration

---

grpc/src/test/java/com/linecorp/armeria/common/grpc/GoogleGrpcStatusFunctionTest.java

Motivation:
Modifications:
Result:

Fix broken `gRPC` tests

---

settings.gradle

Motivation:
Modifications:
Result:

Upgrade gradle enterprise plugins

---

gradle.properties

Motivation:
Modifications:
Result:

Fix snapshot version to 1.25.1

---

site/src/pages/release-notes/1.25.1.mdx

Release note for 1.25.1

---

site/src/pages/release-notes/1.25.2.mdx

Release notes for 1.25.2

---

site/src/pages/docs/setup.mdx

The page is outdated so we need to update it.

Update "Setting up a project" docs

---

core/src/test/java/com/linecorp/armeria/client/Http2GoAwayTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientPipeliningTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceAnnotationAliasTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceDecorationTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceResponseConverterTest.java
core/src/test/java/com/linecorp/armeria/server/StreamingDecodedHttpRequestTest.java
core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
core/src/test/java/com/linecorp/armeria/server/file/FileServiceAdditionalHeadersTest.java
core/src/test/java/com/linecorp/armeria/server/streaming/JsonTextSequencesTest.java
grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcFlowControlTest.java
grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcStatusCauseTest.java
it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java

- Migrate JUnit4 tests to JUnit 5
(Continuation of #5105)
I'm working on something else, so the next one will be a while.

Migrate more JUnit 4 tests to JUnit 5

---

.github/workflows/public-suffixes.yml

Verified by https://github.com/jrhee17/armeria/actions/runs/6543741701/job/17769115003

Fix failing public suffixes

---

reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareFluxTest.java

Motivation:
`ConnectableFlux` is disposed right after the flux is subscribed with the number of subscribers that is specified when creating. So I didn't have to call dispose from the first.
Result:
- Close #5262

Fix ContextAwareFluxTest flaky test

---

site/src/pages/docs/client-retry.mdx

Motivation:
While reading through the [Automatic retry](https://armeria.dev/docs/client-retry), I noticed a slight discrepancy between one of the examples and its corresponding code. 
Modifications:
- This change corrects that discrepancy.
Result:
no code is changed.

Refine example explanation for RetryRule behavior

---

.github/workflows/gradle-enterprise-postjob.yml
.github/workflows/tag-new-release.yml

Motivation:
If releases are performed through an automated task, mistakes can be reduced and more validation can be added.
Modifications:
- Add `tag-new-release.yml` to tag a new version with GitHub Actions dispatch UI.
Result:
Automated release process

Release a new version with GitHub Actions

---

site/src/pages/release-notes/1.26.3.mdx

Add release notes for 1.26.3

---

logback/logback12/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java

Motivation:
If `Flags` class is initialized before `RequestContextExportingAppender` is registered to the root logger,
the logs produced `Flags` in the initialization of the class are silently ignored.
See #5327 for the details.
Modifications:
- Lazily create `RequestContextExporterBuilder` to not initialize `Flags` while ` RequestContextExportingAppender` is being initialized.
- `RequestContextExporterBuilder` is created when `FlagsLoaded.get()` is true.
Result:
- `Flags` now correctly logs all messages when `RequestContextExportingAppender` is configured.
- Fixes #5327

Fixed a bug where logs produced by `Flags` were not appended to `RequestContextExportingAppender`

---

core/src/main/java/com/linecorp/armeria/client/websocket/DefaultWebSocketClient.java

Motivation:
A leak was detected while a CI build was running.
https://github.com/line/armeria/actions/runs/7665407974/job/20891255893?pr=5167#step:11:4166 It was leaked when a WebSocket client sends a request to an invaild path.
```
08:12:09.002 [armeria-common-worker-epoll-2-11] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) …
```

Fix a leak when WebSocket client receives an invalid response

---

core/src/test/java/com/linecorp/armeria/common/stream/ByteStreamMessageOutputStreamTest.java

Motivation:
`ByteStreamMessageOutputStreamTest.writeAfterStreamClosed()` tests if `ByteStreamMessageOutputStream` raises an IOException after the enclosing `ByteStreamMessage` is aborted.
If a `StreamMessage` has been subscribed by another `Subscriber`, the abortion process may happen in a different thread asynchronously.
Modifications:
- Wait until the abortion of `ByteStreamMessage` completes.
Results:
Closes #4553

Fix flaky `ByteStreamMessageOutputStreamTest.writeAfterStreamClosed()`

---

thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java

Motivation:
We received a report where thrift was leaking pooled byte buffers.
We use pooled byte buffers to create the thrift request in `THttpClientDelegate` assuming
that it will be released when sent on the wire for normal cases.
https://github.com/line/armeria/blob/7f302505a05d24e7704bcffc43fab6337344cb2c/thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java#L134
However, if any requests don't have a chance to reach the wire, they will leak the byte buffer.
I believe it is reasonable to assume that requests not decoded properly should be cleaned up. Hence, I propose we do an extra `req.abort` inside `handlePreDecodeException`.
Modifications:
- Modify `handlePreDecodeException` to accept an additional `HttpRequest` parameter
- Abort the …

Handle a leak when thrift requests are aborted early

---

site/src/pages/docs/client-timeouts.mdx
site/src/pages/tutorials/grpc/blog/index.mdx

Fix typo in document

---

site/src/pages/release-notes/1.28.1.mdx

Add release notes for 1.28.1

---

site/src/pages/tutorials/rest/blog/implement-delete.mdx

If you look at the exception handling part of the official document REST Tutorial Step 7 DELETE Implementation document
`throw new IllegalArgumentException("The blog post does not exist. id: " + id);`
It is written as "id". [link](https://armeria.dev/tutorials/rest/blog/implement-delete#handle-exceptions)
In the error case test section  
`assertThatJson(res.contentUtf8()).isEqualTo("{\"error\":\"The blog post does not exist. ID: 100\"}");`
It is written as "ID". [link](https://armeria.dev/tutorials/rest/blog/implement-delete#5-test-an-error-case)
Document modification is required.
I modified the exception handling part from `throw new IllegalArgumentException("The blog post does not exist. id: " + id);` to `throw new IllegalArgumentException("The blog post does not exist. ID: " + id);` …

REST Tutorial Step 7 Modifying a Document

---

core/src/test/java/com/linecorp/armeria/server/Http1ServerDelayedCloseConnectionTest.java

Fix flaky test in Http1ServerDelayedCloseConnectionTest

---

core/src/test/java/com/linecorp/armeria/common/stream/InputStreamStreamMessageTest.java

Fix flaky test in InputStreamStreamMessageTest

---

site/src/pages/community/articles.mdx

- Added the articles from the following contributors:
- @dogacel
- @dgahn
- @tomatophobia

Add more community articles

---

site/src/pages/release-notes/1.29.3.mdx

New bug fixes are added.
- #5825
- #5824
- #5829
- #5835

Update release notes for 1.29.3

---

thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java

Motivation:
I thought the previous modification #6354 would fix the flakiness, but it turned out it didn't.
The first attempt may not be cancelled by `res.cancel(true)` because of the race between an event loop and the main thread. https://github.com/line/armeria/blob/a0e2225cb7aac6b229b86e25e9b2f34633a9f45b/thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java#L354-L356 Therefore, I propose removing the flaky assertions and adding a new clear assertion that verifies retry occurs only once.
Modifications:
- Remove flaky assertions in `RetryingRpcClientTest.doNotRetryWhenResponseIsCancelled()`
Result:
Make CI stable

Fix flaky `RetryingRpcClientTest.doNotRetryWhenResponseIsCancelled()`
