thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java
thrift/src/main/java/com/linecorp/armeria/internal/thrift/TByteBufTransport.java
thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java

When looking for any places we slice a buffer when creating `HttpData`, I found this one. Switching to using pooled buffers removes this usage while also probably making the client more memory efficient (we switched the server a long time ago but never the client).

Use pooled buffers in thrift client.

---

build.gradle
dependencies.yml
spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java

Motivation:
- `spring-boot-webflux-starter` app does not start when multiple
`MeterRegistry`s are registerted
```
org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is java.lang.IllegalStateException: Too many MeterRegistry beans: [io.micrometer.cloudwatch.CloudWatchMeterRegistry@6dd79214, io.micrometer.prometheus.PrometheusMeterRegistry@2c47a053, io.micrometer.core.instrument.composite.CompositeMeterRegistry@7767bd4e] (expected: 1)
at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:82)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
at …
```

Use BeanFactory's getBean in findBean

---

core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java

While working on other SSL stuff, I noticed that the logic for SSL configuration is in two places and a bit confusing. And it's not too hard to enable TLSv1.3, so figured may as well turn it on since it seems to be getting more widely used now. FWIU, openssl intends users to automatically get it enabled when updating their dependency version, so figure similar for Armeria should be acceptable, but let me know if we should flag this. For reference, https://wiki.openssl.org/index.php/TLS1.3
No rush on this PR :)

Consolidate SSL logic and enable TLSv1.3 by default.

---

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/MetadataUtil.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/TransportStatusListener.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
grpc/src/test/java/com/linecorp/armeria/internal/grpc/TestServiceImpl.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java

Now incoming headers are copied into `Metadata` and outgoing `Metadata` is copied into headers. Since `Metadata` is supported now, I have stopped using `EMPTY_METADATA` which was questionable to begin with, since it's mutable so a singleton shouldn't be used. Tests have replaced some code that used to use armeria for manipulating headers with ones that use `Metadata` (armeria versions are very well tested in `core` already so don't really need them here I guess).
Will leave this WIP until hearing back on https://github.com/grpc/grpc-java/issues/5788

Marshal headers <-> gRPC Metadata.

---

core/src/main/java/com/linecorp/armeria/client/AbstractClientFactory.java
core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
core/src/main/java/com/linecorp/armeria/client/Clients.java
core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
core/src/main/java/com/linecorp/armeria/client/Endpoint.java
core/src/main/java/com/linecorp/armeria/client/HttpClient.java
core/src/main/java/com/linecorp/armeria/client/HttpClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientFactory.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientFactory.java
thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java

Motivation:
- Current HttpClient only allow string or URI object for argument,
but Endpoint is commonly use for handling URI. For convenience,
HttpClient can accept Endpoint as argument.
Modification:
- Add Endpoint argument to HttpClient creation methods.
Result:
- HttpClient can be created with Endpoint instead of string or URI.

Provide a way to create a client with an Endpoint rather than with a URI

---

site/build.gradle
spring/boot1-autoconfigure/build.gradle

Related: https://github.com/line/gradle-scripts/pull/61
Motivation:
When configure-on-demand is enabled, inter-project dependencies are
calculated correctly only when task dependency is specified as a task
path string or `Project.evaluationDependsOn()` must be used. See:
- https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:configuration_on_demand
> The task dependencies declared via task path are supported and cause
> relevant projects to be configured.
> Example: someTask.dependsOn(":someOtherProject:someOtherTask")
Modifications:
- Add `Project.evaluationDependsOn()` calls where necessary
Result:
- Fixes a bug where a certain project is not configured when it has to
be, causing a weird compilation error due to unconfigured dependencies.

Fix project evaluation dependencies

---

core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java
core/src/test/java/com/linecorp/armeria/internal/PathAndQueryTest.java

Motivation:
Currently, percent-encoded characters only for ampersand(`&`), semi-colon(`;`) and equal(`=`) are preserved after parsing URI by `PathAndQuery`. So, if a request has a percent-encoded `#`(`%23`), it is decoded as a raw `#` character. Due to this behavior, `QueryStringDecoder` cannot parse parameters correctly if a query string has a `#`, because `#` is a fragment identifier and the decoder ignores everything after the identifier.
Modifications:
- Every percent-encoded characters for reserved characters are preserved after parsing URI by `PathAndQuery`.
- Reserved characters. (from `https://tools.ietf.org/html/rfc3986#section-2.2`)
- `:` / `/` / `?` / `#` / `[` / `]` / `@`
- `!` / `$` / `&` / `'` / `(` / `)` / `*` / `+` / `,` / `;` / `=`

Preserve percent-encoded character after parsing URI by PathAndQuery

---

build.gradle
core/src/test/java/com/linecorp/armeria/client/Http1EmptyRequestTest.java
dependencies.yml
testing-internal/src/main/java/com/linecorp/armeria/testing/internal/TestUtil.java

…arameterized test to it.
Was curious if junit5 has the same problem as #1601 and it doesn't! So I want to migrate all the parameterized tests to junit5 (or at least the gRPC ones since I use them a lot and it's annoying that I can't use Gradle runner because of them).
I found that the biggest missing piece from junit5 is global timeouts. 5.5 will have it, but that will probably take a while to be released. Also, I don't think they'll support disable-on-debug in their first release either. So wondering if it makes sense to add this utility for running a lambda with a timeout using the current junit5 style.

Add a utility for executing junit5 tests with timeout and convert a parameterized test to it

---

docs-client/package.json
docs-client/src/containers/App/index.tsx
docs-client/src/containers/MethodPage/index.tsx
docs-client/src/index.tsx
docs-client/webpack.config.ts
docs-client/yarn.lock
licenses/web-licenses.txt

- Migrate from `@babel/polyfills` to `core-js` as advised by Babel 7.4
- Fixed TSLint errors

Update frontend dependencies

---

core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClientTest.java
dependencies.yml
grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerTest.java
testing-internal/build.gradle
testing-internal/src/main/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
testing-internal/src/main/resources/junit-platform.properties

We commonly use mockito in tests so it should make sense to always have it enabled for junit5 tests. This change ensures it's always as easy (or easier) to write a junit5 test as junit4 in the codebase.
Migrated one test to demonstrate it works.
This extension defaults to mockito's strict stubs setting - `@MockitoSettings` can be applied to disable this. But Mockito seems to strongly recommend this and is going to default it in mockito 3 because it removes the needs to set stubs, then verify them - verification happens automatically with the strict stubs setting.

Automatically enable MockitoExtension in JUnit 5 tests.

---

core/src/main/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistries.java
core/src/main/java/com/linecorp/armeria/common/metric/PrometheusMeterRegistries.java

Motivation:
`DropwizardMeterRegistries` has `configureRegistry()` while
`PrometheusMeterRegistries` does not.
Modifications:
- Add `PrometheusMeterRegistries.configureRegistry()`
- Allow method chaining for `configureRegistry()`
Result:
- Consistency
- Convenience

Add `PrometheusMeterRegistries.configureRegistry()`

---

docs-client/package.json
docs-client/src/components/GotoSelect/index.tsx
docs-client/src/containers/App/index.tsx
docs-client/yarn.lock
licenses/web-licenses.txt

Fixes #653
Motivation
* In a server which serves a large number of methods, it takes time to go methods in debug page.
Modification
* Add [react-select](https://github.com/JedWatson/react-select)@3.0.4 dependency on docs-client for auto selection
* Convert docs specification into suggestion model
* Put the `go-to` input on the rightmost side of the `AppBar`
Result
* We can access any of the methods, structs, enums, and exceptions quickly
by using auto-complete or up-down key navigation.

Implement the go-to form for DocService debug page

---

grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto

While looking into gRPC context, I noticed the implementation is very similar to Armeria's, using a thread-local. So didn't find any reason not to work, and at least this example seems to be working ok. Let's add the test for now and follow up on what use cases don't work.
/cc @andrewoma

Add unit test that uses gRPC Context.

---

core/src/main/java/com/linecorp/armeria/common/CacheControl.java
core/src/main/java/com/linecorp/armeria/common/CacheControlBuilder.java
core/src/main/java/com/linecorp/armeria/common/ClientCacheControl.java
core/src/main/java/com/linecorp/armeria/common/ClientCacheControlBuilder.java
core/src/main/java/com/linecorp/armeria/common/ServerCacheControl.java
core/src/main/java/com/linecorp/armeria/common/ServerCacheControlBuilder.java
core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
core/src/test/java/com/linecorp/armeria/common/CacheControlTest.java
core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java

Motivation:
We moved `Client/ServerCacheControl*` into the `common` package in #1816.
This means we can make `protected` methods package-local.
Modifications:
- Make `CacheControlBuilder` package-local
- Make all `protected` methods package-local
- Rename `ArmeriaHttpUtil.parseCacheControl()` to `parseDirectives()`
for future reuse
- Rename `ArmeriaHttpUtil.parseCacheControlSeconds()` to
`parseDirectiveValueAsSeconds()` for future reuse.
- Remove type parameter from `CacheControlBuilder` for cleaner Javadoc
generation
Result:
- Leaner public API which hides the stuff which was unnecessarily
visible from users.

Hide `CacheControlBuilder` from the public API

---

dependencies.yml

`protobuf-jackson` has released stable version (same as last version) and published javadoc
https://github.com/curioswitch/curiostack/releases/tag/protobuf-jackson-1.0.0

Update protobuf-jackson to 1.0.0

---

CONTRIBUTING.md
README.md
site/src/sphinx/setup.rst

Related: #1851
Motivation:
Some users misinterpreted our `README.md` and thought our minimum
requirement is Java 11, which is not correct.
Modifications:
- Make it clear that our minimum requirement is Java 8.
Result:
- Hopefully less confusion

Add 'requirements' to README.md and web site

---

spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerLoadBalancerInteropTest.java
spring/boot-webflux-autoconfigure/src/test/resources/config/application-test_loadbalancer.yml

.. while handling a WebFlux response.
Motivation:
When handling a `HEAD` request, Webflux can get the response from a `GET`
request handler and cancel the body subscription immediately. In that
case, `PublisherBasedHttpResponse` will fail its `completionFuture` with
a `CancelledSubscriptionException`, which will be propagated to WebFlux
as an unhandled exception.
Modifications:
- Filter out `CancelledSubscriptionException` and
`AbortedStreamException` so that WebFlux does not write an ERROR log
about an unhandled exception.
- Do not log at DEBUG level about a cancelled stream when the current
request method is `HEAD` because it's expected.
Result:
- Less noisy error handling
- Fixes #1847

Ignore `CancelledSubscriptionException` and `AbortedStreamException`

---

dependencies.yml
grpc/build.gradle
thrift/build.gradle
thrift0.11/build.gradle
thrift0.9/build.gradle

Motivation:
In some configuration, the `java.xml.ws.annotation` module, which
contains `javax.annotation.Generated`, is not added by default. As a
result, a user will get the 'cannot find symbol' compilation error.
Modifications:
- Add an explicit dependency to `jakarta.annotation:jakarta.annotation-api`
- Exclude the `javax.annotation:javax.annotation-api` which has been
superceded by `jakarta.annotation-api`
Result:
- No more compilation errors

Add missing dependency for `javax.annotation.Generated`

---

thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpErrorResponseTest.java
thrift/src/test/java/com/linecorp/armeria/it/thrift/ThrottlingRpcServiceTest.java

Motivation:
When a Thrift service fails with an `HttpStatusException` or an
`HttpResponseException`. `THttpService` wraps it with a
`TApplicationException` and sends a `200 OK` response. Instead, we could
make `THttpService` respect such exceptions and send a proper HTTP error
response.
This can be useful when a service wants to send a timeout response such
as `503 Service Unavailable`, because otherwise a client will have to
handle two different timeouts in two different ways:
- `503 Service Unavailable` (when Thrift service method failed to
produce a response before the request times out.)
- `200 OK` with a Thrift-level timeout exception (when Thrift service
method produces an error response that tells the request has timed out.)
Modifications:
- Make `THttpService` handle …

Handle `HttpStatus/ResponseException` in `THttpService`

---

core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/main/java/com/linecorp/armeria/server/Server.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/logging/AccessLogWriter.java
core/src/test/java/com/linecorp/armeria/server/HttpResponseSubscriberTest.java
core/src/test/java/com/linecorp/armeria/server/ServiceBindingBuilderTest.java
core/src/test/java/com/linecorp/armeria/server/ServiceBindingTest.java
core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
kafka/src/main/java/com/linecorp/armeria/server/logging/kafka/KafkaAccessLogWriter.java
thrift/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java

Motivation:
A user might want to specify `AccessLogWriter` per service when he/she uses `KafkaAccessLogWriter` or similar.
Modification:
- Add a setter for `AccessLogWriter` to `ServerBuilder.route()`.
Result:
- You can now specify `AccessLogWriter` per service.

Provide a way to specify per-service AccessLogWriter

---

core/src/main/java/com/linecorp/armeria/client/DefaultAddressResolverGroupFactory.java

Motivation:
@normanmaurer kindly suggested me to enable TCP fallback for our default
DNS name resolver, and we definitely should to handle a large DNS
response.
Modifications:
- Enable TCP fallback by calling `DnsNameResolverBuilder.socketChannelType()`
Result:
- Can handle a large DNS response

Enable TCP fallback for the default DNS name resolver

---

benchmarks/src/jmh/java/com/linecorp/armeria/grpc/downstream/LargePayloadBenchmark.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/common/RequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceTest.java
core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextTest.java
core/src/test/java/com/linecorp/armeria/server/TestConverters.java
examples/grpc-service/src/main/java/example/armeria/grpc/HelloServiceImpl.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
grpc/src/test/java/com/linecorp/armeria/internal/grpc/TestServiceImpl.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaWebClientTest.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ByteBufLeakTest.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerAutoConfigurationTest.java
thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftCallService.java
thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
thrift/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java
thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpHeaderTest.java
thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java

Motivation:
A user often has to downcast `RequestContext`:
ServiceRequestContext ctx = (ServiceRequestContext) RequestContext.current();
Because of this, the code often gets pretty verbose:
((ServiceRequestContext) RequestContext.current()).routingContext().hostname();
If we have `ServiceRequestContext.current()`, it would have been much nicer:
ServiceRequestContext.current().routingContext().hostname();
If the current context is not a `ServiceRequestContext` (or `ClientRequestContext`), we could simply raise an `IllegalStateException`.
Modifications:
- Add `currentOrNull()` to `RequestContext`
- Add `current()`, `mapCurrent()` and `currentOrNull()` to `Service/ClientRequestContext`
- Use `Service/ClientRequestContext.current/mapCurrent/currentOrNull()` wherever
possible.
Result:
- Closes …

Add `current/mapCurrent/currentOrNull()` to `Service/ClientRequestContext`

---

core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java

Motivation:
Since Netty 4.1.37, `SslHandler` emits an `SslHandshakeCompletionEvent`
when a TLS handshake is complete. It triggers a log message at WARN
level currently.
Modifications:
- Add `SslHandshakeCompletionEvent` to the known user events.
Result:
- Less noise

Ignore `SslHandshakeCompletionEvent`

---

site/src/sphinx/advanced-spring-webflux-integration.rst

Motivation:
Spring Boot sometimes use an old Netty version which is not compatible
with what's used by Armeria.
Modifications:
- Update the WebFlux integration documentation to pin the Netty version
Result:
- No more runtime errors

Pin Netty version when integrating with Spring Boot

---

core/src/main/java/com/linecorp/armeria/server/healthcheck/DefaultHealthCheckUpdateHandler.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckUpdateHandler.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckUpdateResult.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/ListenableHealthChecker.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/ManagedHttpHealthCheckService.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/SettableHealthChecker.java
core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java

Motivation:
- By adding long-polling support to a health check service, an advanced
health check client can get notified immediately when a server becomes
healthy (or unhealthy), rather than polling periodically.
- `ManagedHttpHealthCheckService` provides only a very simple update
mechanism that's hard to customize.
Modifications:
- Deprecate `*HttpHealthCheckService`
- Add `HealthCheckService` and its builder
- Add `ListenableHealthChecker` to implement notification
Result:
- Long-polling support for health checks, which will greatly reduce the
delay between the actual moment when the server got unhealthy and when
the client learns the unhealthiness.

New `HealthCheckService` with long-polling support

---

core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java
core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
core/src/main/java/com/linecorp/armeria/internal/logging/LoggingDecorators.java
core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java

Related: #1810
Motivation:
When writing a header sanitization function, the function must be
written to return an `HttpHeaders`. For some users, it would be simpler
and/or more efficient if we relax the output type constraint of header
sanitizer functions, e.g.
Function<HttpHeaders, Object> f = headers -> "sanitized!";
Modifications:
- Change the output type to `?` for all sanitizer functions.
- Deduplicated sanitization logic in `DefaultRequestLog`.
Result:
- Convenience and efficiency

Relax the output type constraint of sanitizer functions

---

site/src/sphinx/_extensions/api.py
site/src/sphinx/advanced-zipkin.rst
site/src/sphinx/server-grpc.rst

Motivation:
At some point in the past, `:api:` and `:apiplural:` roles stopped to
work.
Modification:
- Do not monkey-patch `HTMLTranslator`.
- Define a node properly.
Result:
- API links are back.

Fix API links in the web site

---

grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java

This matches the default as documented in `ServerCall.setMessageCompression`. I personally don't like the default very much though... I think we would generally want to encourage using stream encoding via `HttpEncodingService` / `HttpDecodingClient` instead of message compression, which will have much better performance.
Fixes #1885

Enable message compression on server by default.

---

site/src/sphinx/server-annotated-service.rst

`ResponseHeadersBuilder` is an interface, so I think this is correct.

Fix server-annotated-service.rst

---

core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java

This allows the upgrade to happen without user business logic having to worry about it.
Fixes #1895

Use OPTIONS instead of HEAD for HTTP/2 upgrade.

---

dependencies.yml

Motivation:
https://github.com/melix/jmh-gradle-plugin says that the minimal plugin version is `0.5.0` when using Gradle `5.5`.

Update jmh-gradle-plugin version to 0.5.0-rc-1

---

spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequest.java
spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequestTest.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java

Motivation:
The uri of `ServerHttpRequest` in Spring Web flux contains the base URL.
Also, a negative value of "max-age" from "set-cookie" means no "max-age" attribute, we shouldn't set it.
Modification:
- Add the base URL when `ArmeriaServerHttpRequest` is created.
- Do not set max-age from set-cookie when the value is negative
Result:
- Spring integration

Fix the uri of ArmeriaServerHttpRequest to contain the base url

---

core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java

I ran into this while debugging why `awaitInitialEndpoints` in https://github.com/openzipkin/zipkin/pull/2653 often takes seconds to resolve `localhost`. I don't think I found the real culprit yet, but it does look like when closing and re-registering a health checked endpoint group, health checks from the closed one will still continue to be sent forever.
Also wondering if we need to redesign it so `EndpointGroupRegistry` is a field of `ClientFactory` instead of `static`.

Cancel health check when closing health checked endpoint

---

brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java

Motivation:
On the client side, it is possible that a request is not sent to the
wire, e.g. when connection error or validation failure occurs.
Modifications:
- Make sure `REQUEST_FIRST_BYTES_TRANSFERRED` is available before
logging wire receive.
Result:
- No more `RequestLogAvailabilityException` in `BraveClient` and
`HttpTracingClient`.
- Fixes #1911

Do not record wire timestamp when no request was transferred

---

core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java

Motivation:
Provide `(ServierBuilder|VirtualHostBuilder).decorator(DecoratingServiceFunction)`
see #1882 
Modification:
- Added `decorator(DecoratingServiceFunction)`  in `ServerBuilder` and `VirtualHostBuilder`

Add `(ServerBuilder|VirtualHostBuilder).decorator(DecoratingServiceFunction)`

---

core/src/main/java/com/linecorp/armeria/server/annotation/ConsumesJson.java

By RFC7158, Json text is encoded in UTF-8 by default.
However @ConsumesJson can consume only "application/json; charset=utf-8"
not "application/json". Update @ConsumesJson can consume both way.
See https://tools.ietf.org/html/rfc7158#section-8.1

Update @ConsumesJson can consume 'appplication/json' by default.

---

core/src/main/java/com/linecorp/armeria/common/HttpData.java
core/src/main/java/com/linecorp/armeria/unsafe/ByteBufHttpData.java
core/src/test/java/com/linecorp/armeria/common/HttpDataTest.java

It's fairly common to convert a `HttpData` to an `InputStream`, e.g. when parsing into Jackson, so it's nice to make sure `ByteBufHttpData.toInputStream` is efficient too.
Fixes #1918

Implement ByteBufHttpData.toInputStream

---

core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java
core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java

Motivation:
In `RequestContext.makeContextAware(future)`, if `pushIfAbsent()` throws the `IllegalStateException` because of pushing
different `RequestContext` to the thread local, it just swallows the exception.
Modification:
- Complete the future with the exception.
Result:
- The exception is propagated to the returned future when calling `makeContextAware()`

Propagate IllegalStateException when calling makeContextAware

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/client/Clients.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/DefaultHttpClient.java
core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
core/src/main/java/com/linecorp/armeria/client/UserClient.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMapping.java
core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistry.java
core/src/main/java/com/linecorp/armeria/client/endpoint/StaticEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
core/src/main/java/com/linecorp/armeria/common/RequestContext.java
core/src/main/java/com/linecorp/armeria/common/StringValueConverter.java
core/src/main/java/com/linecorp/armeria/internal/ClientUtil.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/test/java/com/linecorp/armeria/client/ClientRequestContextInitFailureTest.java
core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMappingTest.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientAuthorityHeaderTest.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcStatus.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientRequestContextInitFailureTest.java
logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporter.java
thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientRequestContextInitFailureTest.java

Motivation:
`ClientRequestContext.endpoint()` currently return an `Endpoint` which
may be 1) a host:port endpoint or 2) a group endpoint. Therefore, a
client decorator does not know which host the request will be sent to
exactly; it is determined after all decorators are evaluated. This makes
it hard for client decorators to do the following:
- Injecting a header value derived from the target host name.
- Accounting for the number of requests sent to each host.
Modifications:
- Split the initialization of `DefaultClientRequestContext` into two:
1) constructor and 2) `init()` method.
- Determine the target host at the context initialization phase.
- Make `ClientRequestContext.endpoint()` nullable, so that the
decorators can handle the case where endpoint selection has failed.
- Add …

Move Endpoint selection to the beginning of client execution

---

brave/src/main/java/com/linecorp/armeria/client/brave/ArmeriaHttpClientParser.java
brave/src/main/java/com/linecorp/armeria/server/brave/ArmeriaHttpServerAdapter.java
brave/src/main/java/com/linecorp/armeria/server/brave/ArmeriaHttpServerParser.java
brave/src/test/java/com/linecorp/armeria/client/brave/ArmeriaHttpClientAdapterTest.java
brave/src/test/java/com/linecorp/armeria/server/brave/ArmeriaHttpServerAdapterTest.java
core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
core/src/main/java/com/linecorp/armeria/server/Route.java
core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
core/src/test/java/com/linecorp/armeria/server/PathWithPrefixTest.java
core/src/test/java/com/linecorp/armeria/server/RouteTest.java

Related: #1906
Motivation:
When a user builds a `Route` with `pathWithPrefix()`, the following
route:
pathWithPrefix("/prefix", "glob:foo")
can be simplified into:
path("glob:/prefix/**/foo")
only except that the `**` must not be captured.
Modifications:
- Simplify a glob path mapping with prefix into a simple glob path
mapping, not into `PrefixPathMapping`.
- Add `numGroupsToSkip` option to `GlobPathMapping` so that we can skip
the `**` group we added implicitly.
- Address the comments which were not addressed in #1906
- Javadoc fixes
- Removal of redundant `public` modifiers
- Do not insert between `prefix` and `regex` when generating a span
name for `PrefixPathMapping`.
Result:
- Much cleaner Brave span names and meter tags for the route with a
prefix and a glob.
- …

Simplify a glob path mapping with prefix into a glob

---

benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/StaticEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java

Also moves logic for waiting for endpoints to `EndpointGroup`. Many of our groups just delegate, so aren't `DynamicEndpointGroup`, but users shouldn't have to know whether a group is dynamic or not to do the initial endpoint wait.
I noticed when writing tests that use a health checked client, they were extremely slow. Investigating, I realized it's almost impossible for a health checked endpoint of a dns endpoint to resolve endpoints without waiting one interval of retry, which defaults to relatively slow 3 seconds, since health checking starts within microseconds - even a fast DNS resolution will take milliseconds. It seems too tedious to require users to await on DNS endpoint groups, before then constructing a health checked one, and waiting on it. 
I'm not so confident that sticking a …

Wait for delegate endpoints before beginning health check.

---

core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java
core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/main/java/com/linecorp/armeria/common/HttpResponseUtil.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java

Motivation:
If a user calls `client.get(...).aggregate()`, it uses the `EventLoop` which is used for writing the elements
to the `HttpResponse` to subscribe. So the logic executed by one `EventLoop` seamlessly. However, if there's
a decorator which uses `DeferredHttpResponse` such as `ConcurrencyLimitingHttpClient` or `RetryingClient`,
it's executed not by one `EventLoop` but two `EventLoop`s which switching situation happens.
Modifications:
- Add `HttpResponse.from(stage, defaultSubscriberExecutor)`.
- Add a constructor which takes an `EventExecutor` to `DeferredHttpResponse`.
- `DeferredHttpResponse` is public but it's deprecated a long time ago, so perhaps don't need to have a class which extends it.
Result:
- Aggregating `HttpResponse` becomes more efficient when …

Enable DeferredHttpResponse to have a defaultSubscriberExecutor

---

core/build.gradle
core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java

During https://github.com/openzipkin/zipkin-aws/pull/135 we found that Armeria will add a second `host` header even if one is already set in the request headers before sending them. This can break behavior and I suppose must break some HTTP spec too.
I wasn't sure whether to respect or ignore the user's setting, but with this change, if a user themselves set an authority and host to different values, we'll leave the host as is. While this is a bad user, I guess we should trust they did it on purpose.
I had to write the unit test in Jetty since during the conversion from HTTP/1 headers to Armeria headers, the duplicate hosts got normalized. 

Don't add a second translated header when it already exists.

---

grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java

Motivation:
According to the [spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests),
gRPC `Request-Headers` has to contain `te` header in order to detect incompatible proxies.
Modification:
- Add `te` header to gRPC request headers
Result:
- Fix #1963

Fix to contain te header in gRPC request

---

core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientLoadBalancingTest.java

Motivation:
`RetryingClient.newDerivedContext()` always selects a new `Endpoint`,
but it should never for the first attempt, because the `Endpoint` for
the first attempt has been already selected by the parent context.
Modifications:
- Add `totalAttempt` parameter to `RetryingClient.newDerivedContext()`
and do not select a new `Endpoint` when it's greater than 1.
- Add a test case
Result:
- Fixes #1973

Make `RetryingClient` respect the `Endpoint` selection order

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClientBuilder.java
core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeServiceBuilder.java
core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeServiceBuilder.java
core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFileBuilder.java
core/src/main/java/com/linecorp/armeria/server/file/HttpFileBuilder.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientTest.java

Motivation:
Self type parameters are useful when you write an abstract builder
with method chaining, but the Javadoc generated from it looks less
intuitive.
Modifications:
- Remove the usage of the self-type parameters from abstract builders.
- Add `CircuitBreakerClientBuilder.mapping()`.
- Deprecate `CircuitBreakerClientBuilder.circuitBreakerMapping()`.
Result:
- Looks prettier to users
- Increased maintanence burden for devs
- Deprecation of `CircuitBreakerClientBuilder.circuitBreakerMapping()` in favor of `mapping()`

Remove the self-type parameters from abstract builders

---

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupLongPollingTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java

Motivation:
`HealthCheckService` provides a way to get notified immediately when a
server becomes healthy or healthy. We should make use of it in
`HealthCheckedEndpointGroup`.
Modifications:
- Make `HttpHealthChecker` respect the `armeria-lphc` header.
- Fix a bug where `RequestLog.responseCause()` is sometimes not
recorded at all.
Result:
- `HealthCheckedEndpointGroup` knows really soon when a server becomes
healthy or unhealthy, except when the server is completely
unreachable, e.g. connection refused.
- `RequestLog.responseCause()` is recorded correctly.

Implement long polling for `HealthCheckedEndpointGroup`

---

core/src/main/java/com/linecorp/armeria/client/DefaultHttpClient.java
core/src/main/java/com/linecorp/armeria/client/HttpClient.java
core/src/main/java/com/linecorp/armeria/client/HttpClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/UserClient.java
core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
core/src/test/java/com/linecorp/armeria/client/HttpClientRequestPathTest.java
core/src/test/java/com/linecorp/armeria/client/SimpleHttpClientTest.java
core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java

Motivation:
Currently, HttpClient executes can only be used by a URI path.
If HttpClient accepts absolute URI and executes with default options, it is easy for the first user to use it.
Modifications:
* Add static method `of()` in `HttpClient` to execute request with
absolute URI
* Add package private `UNDEFINED_URI` in `HttpClientBuilder` to create
`HttpClient#of()` without specifying URI
Result:
A user who wants to use HttpClient with default options can reduce boilerplate code.
Fixes: #1143

Provide a way to request from an absolute URL with HttpClient

---

core/src/main/java/com/linecorp/armeria/client/Endpoint.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckerContext.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupAuthorityTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupLongPollingTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java

Motivation:
- When a server stops, the clients who sent long-polling health check
requests will currently get a GOAWAY frame or an immediate
disconnection.
- The port number specified in `HealthCheckedEndpointGroupBuilder.port()`
is not used when filling the `:authority` header.
- A user sometimes wants to send a `GET` request rather than `HEAD`.
Modifications:
- Modify `HealthCheckService` to send a response even when a server is
stopping, so that the client is given a chance to receive them.
- Update `HttpHealthCheckedEndpointGroupLongPollingTest` to make sure
the client gets the correct 'unhealthy' response with `armeria-lphc: 0`
header when a server stops.
- Made sure the custom port numbers are respected when building URI and
`:authority` header.
- Add `useGet(boolean)` option to the …

Various improvements in health checking code

---

brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.java

This shows how to use `setCurrentThreadNotRequestThread` until we have
a function of Thread instead.

RequestContextCurrentTraceContext.setCurrentThreadNotRequestThread code

---

CONTRIBUTING.md
core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java
core/src/test/java/com/linecorp/armeria/internal/SslContextUtilTest.java

Motivation:
Netty's JdkSslContext does not support TLSv1.3. Armeria should disable TLS v1.3 when using JdkSslContext. 
Result:
Fixes #1984

Disable TLS v1.3 when using JdkSslContext

---

benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/BackoffBenchmark.java
core/src/main/java/com/linecorp/armeria/client/retry/ExponentialBackoff.java
core/src/test/java/com/linecorp/armeria/client/retry/ExponentialBackoffTest.java

This is inspired by discussion in #1979. Since the memory overhead is small enough, it seems nice to not redo the same fixed computation over and over.
After (consistent and fast)
```
Benchmark                     (numAttemptsSoFar)   Mode  Cnt          Score           Error  Units
BackoffBenchmark.exponential                   1  thrpt    5  391031493.454 ▒   6193827.024  ops/s
BackoffBenchmark.exponential                   2  thrpt    5  319670068.844 ▒  10576871.127  ops/s
BackoffBenchmark.exponential                   3  thrpt    5  251773952.326 ▒   5541318.925  ops/s
BackoffBenchmark.exponential                   4  thrpt    5  264484115.245 ▒ 125757992.112  ops/s
BackoffBenchmark.exponential                   5  thrpt    5  322578825.056 ▒   5550847.620  ops/s …
```

Precompute exponential backoff.

---

grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java
grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClientTest.java

It seems stackdriver trace api will wait until trailers to set the
status for certain errors. This seems legit looking at the gRPC spec.
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#errors
Example error:
```
2019-08-16 10:45:30.502  INFO 47885 --- [-worker-nio-2-2] c.l.a.c.l.LoggingClient                  : Response: {startTime=2019-08-16T02:45:30.498Z(1565923530498646), length=0B, duration=3786µs(3786891ns), headers=[:status=200, content-type=application/grpc, date=Fri, 16 Aug 2019 02:45:12 GMT, alt-svc=quic=":443"; ma=2592000; v="46,43,39"], trailers=[EOS, grpc-status=5, grpc-message=Requested entity was not found., google.rpc.resourceinfo-bin=EhNwcm9qZWN0cy96aXBraW4tZGV2, grpc-status-details-bin=CAUSH1JlcXVlc3RlZCBlbnRpdHkgd2FzIG5vdCBmb3VuZC4aRAordHlwZS5nb29nbGVhcGlzLm …
```

Handles gRPC status when deferred to trailers

---

core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayResponseConverterFunction.java
core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java

Motivation:
The following annotated service method will fail because
`ByteArrayResponseConverterFunction` currently does not convert `byte[]`
or `HttpData` with the content type other than
`application/octet-stream` or `application/binary`.
Modifications:
- Convert `byte[]` or `HttpData` even if the content type is neither
`application/octet-stream` nor `application/binary`.
- Also fix the case where `byte[]` or `HttpData` is not converted when a
service method produces text content.
Result:
- Fixes #1999

Fix `byte[]` and `HttpData` conversion

---

site/src/sphinx/conf.py

Motivation:
`site/src/sphinx/conf.py` reads `dependencies.yml` to generate version
properties. `conf.py` currently fails with an error when
`dependencies.yml` contains the `boms` section.
Modifications:
- Handle the `boms` sections propertly.
Result:
- Site generation doesn't fail anymore when the `boms` section is added.

Make Sphinx site generation not fail on `boms` section

---

core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupLongPollingTest.java

This change fixes `RequestLogAvailabilityException` which can happen
when the request is not handled fast enough.
com.linecorp.armeria.client.endpoint.healthcheck.HttpHealthCheckedEndpointGroupLongPollingTest > keepEndpointHealthinessWhenLongPollingTimeout() FAILED
com.linecorp.armeria.common.logging.RequestLogAvailabilityException: RESPONSE_HEADERS
at com.linecorp.armeria.common.logging.RequestLog.ensureAvailability(RequestLog.java:120)
at com.linecorp.armeria.common.logging.DefaultRequestLog.responseHeaders(DefaultRequestLog.java:833)
at com.linecorp.armeria.client.endpoint.healthcheck.HttpHealthCheckedEndpointGroupLongPollingTest.keepEndpointHealthinessWhenLongPollingTimeout(HttpHealthCheckedEndpointGroupLongPollingTest.java:195)

Fix flaky `HttpHealthCheckedEndpointGroupLongPollingTest`

---

dependencies.yml
site/src/sphinx/advanced-spring-webflux-integration.rst
site/src/sphinx/conf.py

This moves brave, jackson and netty versions to use bom. Notably, in jackson this helps because not everything has a uniform version number. Also notably, the netty-bom doesn't claim netty-tcnative-boringssl-static, which could lead to compatability problems iiuc
Note: Sphinx is very upset at me. It prefers versions declared explicitly.
```
Configuration on demand is an incubating feature.
Running Sphinx v2.1.2
Traceback (most recent call last):
File "/Users/travis/build/trustin/sphinx-binary/build/venv/lib/python3.6/site-packages/sphinx/config.py", line 361, in eval_config_file
File "/Users/travis/build/trustin/sphinx-binary/build/venv/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
File "/Users/acole/oss/armeria/site/src/sphinx/conf.py", line 50, in <module> …
```

Moves brave, jackson and netty version management to bom (Bill of Materials)

---

core/src/main/java/com/linecorp/armeria/common/util/Version.java
core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
docs-client/package.json
docs-client/src/containers/App/index.tsx
docs-client/src/containers/HomePage/index.tsx
docs-client/src/lib/versions.tsx
docs-client/webpack.config.ts
docs-client/yarn.lock
licenses/web-licenses.txt

Motivation:
- The current armeria version of the doc service could not be showed in the armeria documentation service, so the version has been added to the title area.
Modification:
- Add armeria version in DocService
Result:
- Show armeria version in Armeria documentation service

Show armeria version in doc service #685

---

retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/metric/RetrofitMeterIdPrefixFunctionTest.java

Related: #1913
Motivation:
By adding a builder method that accepts `ClientOptions` directly instead
of the function that mutates `ClientOptions`, a user can easily reuse
his or her `ClientOptions` instance:
HttpClient myClient = ...;
// Before:
builder.withClientOptions((uri, b) -> b.options(myClient.options()));
// After:
builder.clientOptions(myClient.options());
Modifications:
- Add `clientOptions(ClientOptions)` method to `ArmeriaRetrofitBuilder`.
Result:
- User friendliness.

Add `ArmeriaRetrofitBuilder.clientOptions()`

---

core/src/main/java/com/linecorp/armeria/client/Client.java
core/src/main/java/com/linecorp/armeria/client/DecoratingClient.java
core/src/test/java/com/linecorp/armeria/client/ClientOptionsBuilderTest.java

Motivation:
A user often need to downcast decorated `Client` to certain type of `Client`.
If we have `Client.as()`, it would be possible.
Modifications:
* Add `as()` to `Client`
* Add `as()` to `DecoratingClient`
Result:
* Closes #1883

Add `as()` to `Client`

---

CONTRIBUTING.md

When clicked the contact us link, get a 404 error.
because changed it

because not found page, changed to add mailto

---

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java

Related: #1913
Motivation:
By adding a builder method that accepts `ClientOptions` directly instead
of the function that mutates `ClientOptions`, a user can easily reuse
his or her `ClientOptions` instance:
HttpClient myClient = ...;
// Before:
builder.withClientOptions(b -> b.options(myClient.options()));
// After:
builder.clientOptions(myClient.options());
Modifications:
- Add `clientOptions(ClientOptions)` method to `HealthCheckedEndpointGroupBuilder`.
Result:
- User friendliness.

Add `HealthCheckedEndpointGroupBuilder.clientOptions()`

---

brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java

Looks like some changes fix this problem(Not sure which one). So remove the ignore assumption and add back the test for HTTP/1.1 .
close https://github.com/line/armeria/issues/1914

Remove unnecessary ignore of brave client integration test

---

core/src/main/java/com/linecorp/armeria/client/Client.java
core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
core/src/main/java/com/linecorp/armeria/client/Clients.java
core/src/main/java/com/linecorp/armeria/client/DecoratingClient.java
core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
core/src/main/java/com/linecorp/armeria/client/HttpClient.java
core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
core/src/main/java/com/linecorp/armeria/client/UserClient.java
core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java
core/src/main/java/com/linecorp/armeria/client/retry/BackoffWrapper.java
core/src/main/java/com/linecorp/armeria/common/util/AbstractUnwrappable.java
core/src/main/java/com/linecorp/armeria/common/util/Unwrappable.java
core/src/main/java/com/linecorp/armeria/server/DecoratingService.java
core/src/main/java/com/linecorp/armeria/server/Service.java
core/src/test/java/com/linecorp/armeria/client/HttpClientUnwrapTest.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientFactory.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientUnwrapTest.java
thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClient.java
thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java
thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientInvocationHandler.java
thrift/src/test/java/com/linecorp/armeria/client/thrift/THttpClientUnwrapTest.java

Related: #2018
Motivation:
- `Client.as()` and `Service.as()` have the same logic which can be
deduplicated.
- `Client.as()` is useless when a user tries to unwrap `HttpClient`,
gRPC client or Thrift client, because they do not implement `Client`.
Modifications:
- Add `Unwrappable` and make `Client`, `Service` and `Backoff` extend it.
- Make `HttpClient` implement `Unwrappable`.
- Add `ClientFactory.unwrap(client, type)` so that a user can unwrap a
gRPC or Thrift client.
- `ClientFactory.clientBuilderParam()` now delegates to `unwrap()`.
- Revise the Javadoc of `as()`.
Result:
- A non-`Client` client object can be unwrapped via `ClientFactory.unwrap()`.
- A user can implement his or her `Unwrappable`.

Add `Unwrappable` and `ClientFactory.unwrap()`

---

core/src/main/java/com/linecorp/armeria/client/DefaultHttpClient.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerBuilder.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounter.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientIntegrationTest.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientTest.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClientTest.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounterTest.java

Motivation:
The `HttpRequest` given to `DefaultHttpClient.execute()` must be aborted
or consumed completely at any circumstances. However, it currently does
not. For example, when a circuit is open and `CircuitBreakerClient`
raises an exception, the request will be left open forever.
Modifications:
- Abort the request when request failed unexpectedly.
- Replace Guava `Tickers` with ours.
Result:
- `ByteBufHttpData` does not leak anymore.

Fix resource leak in `DefaultHttpClient.execute()`

---

core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java

We're observing a cryptic warn :
```
Unexpected exception:
```
and the cause has no trace:
```
com.linecorp.armeria.client.ResponseTimeoutException: null
```
This PR aims to give more info
- which host timed out
- after what delay

Explain Response timeout

---

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpService.java
core/src/main/java/com/linecorp/armeria/internal/annotation/DefaultExceptionHandler.java
core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionHandlerFunction.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceAnnotationAliasTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceBuilderTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceExceptionHandlerTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceHandlersOrderTest.java
examples/annotated-http-service/src/main/java/example/armeria/server/annotated/ExceptionHandlerService.java
examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/ValidationExceptionHandler.java
rxjava/src/test/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionProviderTest.java
spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java

Motivation:
`ExceptionHandlerFunction.handleExeption()` accepts `RequestContext`
rather than `ServiceRequestContext` for an unknown reason.
Modifications:
- Change the method signature of `handleException()` so that a user does
not need to downcast `RequestContext` to `ServiceRequestContext`.
Result:
- Breaking change
- A user does not have to downcast `RequestContext` to
`ServiceRequestContext` anymore.

Require `ServiceRequestContext` for `ExceptionHandlerFunction`

---

spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java

All actuator endpoints currently return a media type provided by spring boot except for the top-level directory. Now it uses the correct spring boot content type.
The existing links test covers this change.

Return spring content type for /actuator

---

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java

I had no idea blocking stubs supported querying server streaming endpoints like this. Turns out we need to notify a call's executor when messages are received so a blocking stub can read individual messages, not just the final one as we currently support.
Fixes #2065

Notify blocking stub executor on message.

---

spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithConsumerTest.java

I think it's useful to be able to customize with spring without using custom types, for example to allow creating a plugin module that just configures a server without needing to worry about armeria-spring. It's sort of similar to how Spring supports both custom annotations and `javax.inject` annotaions. 
Idea came up in https://github.com/jeqo/zipkin-storage-kafka/pull/38
/cc @adriancole @jeqo

Recognize Consumer<ServerBuilder> beans for spring autoconfiguration

---

grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcStatus.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerTest.java
grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshallerTest.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java

Largish diff since refactors deframed message to provide type to business logic to be able to handle special types (currently only one in existence is grpc-web trailers)
Fixes #2030

Support gRPC web trailers in client.

---

core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java

Currently if all endpoints start out unhealthy, then the initial endpoints future for a health checked endpoint group never completes. The initial endpoints future should indicate when the endpoints have first been checked, not when they first become healthy - while an `EndpointGroup` with no `Endpoint`s is sort of useless, I think it's still a perfectly good `EndpointGroup` and deserves notifying listeners :)

Make sure listeners are notified after first health check has resolved.

---

core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
core/src/main/java/com/linecorp/armeria/server/docs/EnumValueInfo.java
docs-client/src/containers/EnumPage/index.tsx
docs-client/src/lib/specification.tsx
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocServicePlugin.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServicePluginTest.java
grpc/src/test/proto/com/linecorp/armeria/grpc/testing/messages.proto
thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftDocServicePlugin.java
thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServicePluginTest.java

**Motivation**
#1966
Add literal value field for enum in documentation.
-> Add literal value as member variable to EnumValueInfo, modify following changes.
**Result**
User can see literal value of enum values in doc pages
There's a question I have working on this issue.
I wonder what is the standard to define 'enum' or 'struct',
Because I defined enums in thrift file but they're partially shown.

Add literal value field for enum in internal documentation

---

spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationHttpService.java
spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java

Spring boot has a tedious mechanism for overriding behavior for individual endpoints
https://github.com/spring-projects/spring-boot/blob/2.1.x/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/HealthEndpointWebExtensionConfiguration.java#L71
I think handling all these cases is too much for our project - health is very common and important though so figured it's worth at least implementing it specially.
/cc @adriancole This fixes current zipkin-server returning 200 on all health responses.

Map response code for health check.

---

thrift/src/main/java/com/linecorp/armeria/common/thrift/text/AbstractThriftMessageClassFinder.java
thrift/src/main/java/com/linecorp/armeria/common/thrift/text/DefaultThriftMessageClassFinder.java
thrift/src/main/java/com/linecorp/armeria/common/thrift/text/StackWalkingThriftMessageClassFinder.java
thrift/src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java
thrift/src/test/java/com/linecorp/armeria/common/thrift/text/ThriftMessageClassFinderTest.java

Motivation:
#1686  
Modification:
Use StackWalker for getting a full stack trace in Thrift TEXT serialization format from above java version 9.
Result:
choose stack trace api according to java version.

Use StackWalker for TTEXT serialization format when on Java 9+(#1686)

---

core/src/main/java/com/linecorp/armeria/common/util/EventLoopThreadFactory.java

Motivation :
Sometimes method-level documentation for deprecated method provides
useful information to users.
Modifications :
Add javadoc documentation to deprecated constructors of `EventLoopThreadFactory`
Result :
Better user information.
Related #2067

Add documentation to `EventLoopThreadFactory`

---

spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java

A previous change fixed health status mapping, but in the process made
it required to have health autoconfiguration. This fixes the below
error:
```
Parameter 3 of method actuatorServerConfigurator in com.linecorp.armeria.spring.actuate.ArmeriaSpringActuatorAutoConfiguration required a bean of type 'org.springframework.boot.actuate.health.HealthStatusHttpMapper' that could not be found.
```

Makes health configuration optional

---

core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java
core/src/main/java/com/linecorp/armeria/common/util/CountingSampler.java
core/src/main/java/com/linecorp/armeria/common/util/RateLimitingSampler.java
core/src/main/java/com/linecorp/armeria/common/util/Sampler.java
core/src/main/java/com/linecorp/armeria/common/util/Samplers.java
core/src/test/java/com/linecorp/armeria/common/util/SamplerTest.java

Motivation:
Like we can specify a string to instantiate a `Backoff`, we could also
specify a specification string to instantiate a `Sampler`, which will be
useful when sampling policy must be configurable.
Modifications:
- Add `Sampler.of()`
- Minor documentation clean-up of `Backoff.of()`
Result:
- A user can create a `Sampler` from a specification string, which means
sampling policy settings can be configurable from a configuration
file, a system property or other external sources.
- Can start to work on #2105

Add `Sampler.of(String specification)`

---

core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java

Motivation:
When a long-polling health check request times out, the data structure
that holds a pending response is not cleaned up.
Modifications:
Make sure to clean up the pending response.
Result:
The memory leak is gone.

Fix memory leak in `HealthCheckService`

---

examples/spring-boot-tomcat/src/test/java/example/springframework/boot/tomcat/HelloIntegrationTest.java
spring/boot-autoconfigure/build.gradle
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/DropwizardSupport.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/PrometheusSupport.java
spring/boot-webflux-autoconfigure/build.gradle
spring/boot1-autoconfigure/build.gradle

Motivation:
A user may not want to pull in Dropwizard Metrics or Prometheus at all.
Modifications:
- Access anything related with Dropwizard or Prometheus only when the related classes are available at runtime.
- Make `io.dropwizard.metrics:metrics-json` and `io.micrometer:micrometer-registry-prometheus` optional.
Result:
- Fixes #2106
- A user can exclude `io.dropwizard.metrics:metrics-core` as well as
`metrics-json`.
- A user can exclude `io.micrometer:micrometer-registry-prometheus`

Make Dropwizard Metrics and Prometheus optional for Spring Boot integration

---

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
core/src/main/java/com/linecorp/armeria/server/annotation/PathPrefix.java
core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactoryTest.java

Adding @PathPrefix annotation for a user to declare a prefix path that a service object handles.
Motivation :  https://github.com/line/armeria/issues/2031
This PR allows a user to declare a 
```
ServerBuilder sb = new ServerBuilder();
sb.annotatedService(new ForBarService());
```
and 
```
@PathPrefix("/foo")
public class FooBarService {
@Get("/bar")
public Object barGet() { ... }
}
```
But this PR does **not** allow something like this:
```
@PathPrefix("/foo")
public class FooBarService {
@Get //without path
public Object barGet() { ... }
}
```
Because a path has to be specified either in `@Path` or in a http method annotation(`@Get`) or an exception is thrown. But I think this is nice to have feature. I just want to get feedback on if this is the right direction I'm going and this is …

Adding @PathPrefix annotation

---

site/src/sphinx/_static/overrides.css

Motivation:
On mobile view, the GitHub corner covers the hamburger button when the
menu is open.
Modification:
Move down the GitHub corner so that it never overlaps with the hamburger
button regardless whether the menu is open or not.
Result:
Better mobile web site experience

Move down the GitHub corner on mobile view

---

benchmarks/src/jmh/java/com/linecorp/armeria/common/ExceptionSamplerBenchmark.java
core/src/main/java/com/linecorp/armeria/client/GoAwayReceivedException.java
core/src/main/java/com/linecorp/armeria/client/RefusedStreamException.java
core/src/main/java/com/linecorp/armeria/client/ResponseTimeoutException.java
core/src/main/java/com/linecorp/armeria/client/SessionProtocolNegotiationException.java
core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java
core/src/main/java/com/linecorp/armeria/client/WriteTimeoutException.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/FailFastException.java
core/src/main/java/com/linecorp/armeria/common/ClosedSessionException.java
core/src/main/java/com/linecorp/armeria/common/ContentTooLargeException.java
core/src/main/java/com/linecorp/armeria/common/ExceptionSampler.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/common/ProtocolViolationException.java
core/src/main/java/com/linecorp/armeria/common/TimeoutException.java
core/src/main/java/com/linecorp/armeria/common/stream/AbortedStreamException.java
core/src/main/java/com/linecorp/armeria/common/stream/CancelledSubscriptionException.java
core/src/main/java/com/linecorp/armeria/common/stream/ClosedPublisherException.java
core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java
core/src/main/java/com/linecorp/armeria/server/HttpStatusException.java
core/src/main/java/com/linecorp/armeria/server/RequestTimeoutException.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaStatusException.java
grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcStatusCauseTest.java
saml/src/main/java/com/linecorp/armeria/server/saml/SamlException.java

Motivation:
`Flags.verboseExceptions()` gives a user only two choices - enabling
stacktrace for all exceptions or not. We could let a user take
trade-offs by allowing him or her to specify a `Sampler` specification.
Modifications:
- Accept a `Sampler` specification string as a value of the
`com.linecorp.armeria.verboseExceptions` system property.
- Use the default specification of `rate-limited=10`, which allows 10
traces per second per exception type.
- Note that `true` and `false` are translated into `always` and
`never`.
- Add `ExceptionSampler`
- Replace `Flags.verboseExceptions()` with `verboseExceptionSampler()`
and `verboseExceptionSamplerSpec()`
- The exceptions which never had stack traces can now have stack trace.
- Add a benchmark
Result:
- A user will get the stack trace for …

Use `Sampler` to determine whether to fill stack trace

---

core/src/main/java/com/linecorp/armeria/common/util/CountingSampler.java
core/src/main/java/com/linecorp/armeria/common/util/RateLimitingSampler.java
core/src/main/java/com/linecorp/armeria/common/util/Sampler.java
core/src/main/java/com/linecorp/armeria/common/util/Samplers.java
core/src/test/java/com/linecorp/armeria/common/util/SamplerTest.java

Motivation:
As pointed out by @adrialcole at https://github.com/openzipkin/brave/pull/994#issuecomment-535922533
the name of the parameter of `Sampler.random(double)` has to be
`probability` rather than `rate`.
Modifications:
- Rename `rate` to `probability` for random sampling.
- Make `CountingSampler` and `RateLimitingSampler` have a type
parameter for less compiler warnings.
Result:
- Less confusing terminology

Rename `rate` to `probability` for random sampling

---

core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
core/src/main/java/com/linecorp/armeria/common/HttpRequestDuplicator.java

Motivation:
`HttpHeaders` is immutable from #1731.
When it was mutable the `:authority` header is automatically filled and it's added to the original headers as well.
In `RetryingHttpClient`, there was a logic that checks if there's an `:authority` header or not.
If there's no an `:authority` header, it means that the header is automatically added, so `RetryingHttpClient` removed that for next retry.
However, `HttpHeaders` is immutable and it always has an `:authority` header since #2092. We should remove that logic.
Modification:
- Remove the logic that checks the initial `:authority` header
Result:
- Obsolete code gone

Remove initial authority check in RetryingHttpClient

---

benchmarks/src/jmh/java/com/linecorp/armeria/common/thrift/text/StackTracingBenchmark.java

Motivation:
add benchmarking result in line of PR: #2055 
Modification:
* add benchmarking result about between using Thread.getStackTrace, Stackwalker, and Stackwalker with RETAIN_CLASS_REFERENCE option
Result:
* Throughput of Stackwalker with RETAIN_CLASS_REFERENCE option is better than others 
* but is recoded high error

Add a JMH benchmark for `ThriftMessageClassFinder`

---

core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
core/src/test/java/com/linecorp/armeria/client/HttpResponseWrapperTest.java

Motivation:
- `HttpResponseDecoder` logs a `ResponseTimeoutException` while
notifying it to a user, which is a double notification.
Modifications:
- Do not log a `ResponseTimeoutException` when the response has been
timed out and the `HttpResponse` was closed with the same exception.
Result:
- Fixes #2000

Do not notify `ResponseTimeoutException` twice

---

core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java

Motivation:
In #2134, I forgot to call `HttpRequestDuplicator.abort()` and `HttpResponseDuplicator.abort()` in `RetryingHttpClient`.

Call duplicator.abort() where necessary

---

core/src/main/java/com/linecorp/armeria/common/util/Version.java

Motivation:
Fix sorting defect #2117
Modifications:
Use a TreeMap instead of a HashMap when identifying versions.
Result:
Versions are now sorted by their artifactId, which is the TreeMap key.
DocService displays the modules sorted alphabetically.

Use TreeMap in Version Class to Sort the Versions

---

core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupTest.java

Fix EndpointGroup.of(Iterable) type

---

dependencies.yml

It seems like the Dropwizard team did not publish their Javadoc for
Metrics 4.1.0.

Fix a 404 error while retrieving Dropwizard Metrics Javadoc links

---

benchmarks/src/jmh/java/com/linecorp/armeria/grpc/GrpcServiceBenchmark.java
benchmarks/src/jmh/resources/logback-test.xml
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java

It's actually relatively rare for headers to change across requests in gRPC since most users don't use message compression, and especially armeria users usually use our standard decorators instead of populating `Metadata`. We can optimize this case by always returning the same instance of `ResponseHeaders`.
Added a microbenchmark that only executes service business logic to remove thread-switch / connection overhead.
After
```
Benchmark                    Mode  Cnt      Score      Error  Units
GrpcServiceBenchmark.empty  thrpt    5  44601.768 ▒ 3864.274  ops/s
```
Before
```
Benchmark                    Mode  Cnt      Score      Error  Units
GrpcServiceBenchmark.empty  thrpt    5  33842.070 ▒ 8515.208  ops/s
```

Use singleton headers where possible in gRPC calls.

---

benchmarks/src/jmh/java/com/linecorp/armeria/internal/metric/RequestMetricSupportBenchmark.java
core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefix.java
core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java

This is the smallest solution for helping with the performance of tag addition. Our default logic can at least add tags in order to prevent reordering when sorting (TimSort handles already-sorted arrays well without special logic).
Also removes comparator when sorting since `Tag` is `Comparable` and adds tests for `Equals/HashCode` for use in playing with those functions.
For #2150
After
```
Benchmark                                        Mode  Cnt        Score         Error  Units
RequestMetricSupportBenchmark.registerSameTags  thrpt    5  6816146.723 ▒ 1548641.211  ops/s
```
Before
```
Benchmark                                        Mode  Cnt        Score        Error  Units
RequestMetricSupportBenchmark.registerSameTags  thrpt    5  5813367.536 ▒ 154548.384  ops/s
```

Add default tags in order.

---

CONTRIBUTING.md
README.md
site/src/sphinx/index.rst

Motivation:
It is probably time to start to use StackOverflow for accepting
questions. Asking a question via an issue was not conventional anyway.
Modifications:
- Replace the question links with the StackOverflow links
- Add the Slack invitation link to `CONTRIBUTING.md`
Result:
Everybody, it's time to set up an e-mail notification for `armeria` tag!

Use StackOverflow for accepting questions

---

.appveyor.build.sh
.appveyor.yml
build.gradle
core/build.gradle
docs-client/build.gradle
it/spring/boot-tomcat8.5/build.gradle
spring/boot1-autoconfigure/build.gradle
thrift0.11/build.gradle
thrift0.9/build.gradle

- Our build machines can afford a parallel build.
- Enable parallelism with 4 maximum workers. 
- This makes the build finish in 10 minutes (previously 20+ minutes).
- Run only essential tasks on Windows to reduce the build time.
- No Checkstyle
- No shading
- No docs-client
- Only a few tasks:
- `:core:test`
- `:grpc:test`
- `:thrift:test`
- `:it:server:test`

Enable parallel build in CI jobs / Run only essential tasks on Windows

---

site/src/sphinx/setup.rst

Motivation:
`armeira-zipkin` has been removed since [0.94.0 release](https://github.com/line/armeria/releases/tag/armeria-0.94.0).
Modification:
*  Replace `armeria-zikin` with  `armeria-brave` in documentation.
Result:
A user can set up `armeria-brave` using [`Setting up a project`](https://line.github.io/armeria/setup.html#setting-up-a-project) guide.

Drop `armeria-zipkin` artifact from setup.html

---

core/src/main/java/com/linecorp/armeria/server/Server.java
core/src/test/java/com/linecorp/armeria/server/ServerTest.java

Hello, I've added Armeria version metric.
**Motivation:**
- Want to check Armeria version with Grafana
FYI:
In Prometheus best practices, this kind of metric is described as follows.
https://prometheus.io/docs/practices/naming/
> foobar_build_info (for a pseudo-metric that provides metadata about the running binary)
e.g.
```
node_exporter_build_info{branch="master",goversion="go1.7.5",revision="840ba5dcc71a084a3bc63cb6063003c1f94435a6",version="0.14.0"} 1
```
**Modifications:**
- Add Armeria version metric
**Result:**
It's exported as follows
Labels:
- commit
- version
```
armeria_build_info{commit="74700d402178e00045b1ca23006f7f6131b2a92d",version="0.94.1-SNAPSHOT",} 1.0
```
example dashboard:

Add Armeria version metric

---

core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java
core/src/test/java/com/linecorp/armeria/server/HttpResponseSubscriberTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerDefaultHeadersTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
core/src/test/java/com/linecorp/armeria/server/ProxyProtocolEnabledServerTest.java
core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
core/src/test/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckServiceTest.java
core/src/test/java/com/linecorp/armeria/server/streaming/JsonTextSequencesTest.java
examples/server-sent-events/src/main/java/example/armeria/server/sse/Main.java
spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java

Motivation:
* Issue #2137
Modifications:
* Modify `HttpResponseSubscriber.onNext()` to add `SERVER` and `DATE` header by default
* Add boolean `enableServerHeader` field to `ServerBuilder` and `ServerConfig`
* Add boolean `enableDateHeader` field to `ServerBuilder` and `ServerConfig`
* Add `ServerBuilder.disableSeverHeader()` to disable default `Server` header.
* Add `ServerBuilder.disableDateHeader()` to disable default `Date` header.
* Add test cases
Result:
* Fixes #2137
* HttpResponse will include `Server` header by default with following format
```
server: Armeria/0.94.1
```
* HttpResponse will include `Date` header by default with following format (RFC 1123)
```
date: Wed, 16 Oct 2019 08:26:14 GMT
```

Add `Server` and `Date` header by default

---

benchmarks/src/jmh/java/com/linecorp/armeria/internal/HttpTimestampSupplierBenchmark.java
core/src/main/java/com/linecorp/armeria/internal/HttpTimestampSupplier.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java
core/src/test/java/com/linecorp/armeria/internal/HttpTimestampSupplierTest.java

As TechEmpower suggests, this caches HTTP timestamps for any given second. I can wire this into the `Date` header after that's in if this makes sense :)
```
Benchmark                                  Mode  Cnt         Score         Error  Units
HttpTimestampSupplierBenchmark.cached     thrpt    5  37665728.115 ▒  324874.523  ops/s
HttpTimestampSupplierBenchmark.notCached  thrpt    5   2099035.297 ▒ 1176888.041  ops/s
```

Add optimized supplier of current HTTP timestamp

---

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
core/src/main/java/com/linecorp/armeria/server/annotation/Paths.java
core/src/main/java/com/linecorp/armeria/server/docs/ServiceInfo.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServicePluginTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServiceTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceBuilderTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactoryTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceTest.java
core/src/test/java/com/linecorp/armeria/server/docs/ServiceInfoTest.java
docs-client/src/containers/MethodPage/index.tsx
site/src/sphinx/server-annotated-service.rst
spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtilTest.java

Motivation:
A user might want to specify multiple paths for annotated http services. 
Modification:
- Allow repeatable annotations for `@Path` annotation.
- Different behavior in path declaration (described below)
- One `AnnotatedHttpService` is created for each `(httpMethod, pathMapping)`
- It is difficult to accommodate multiple pathMappings using a single `AnnotatedHttpService` because `AnnotatedValueResolver` may be different
- It may be possible to optimize this by serving multiple  `httpMethod`s that have the same `pathMapping` using a single `AnnotatedHttpService` at the cost of code complexiy
- Merge `MethodInfo` endpoints with same (`httpMethod`, `methodName`)
- Known issue: overloaded methods for `AnnotatedHttpService` are not displayed in docs. I'm thinking this can be tackled …

Support multiple Path annotations

---

spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequest.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerAutoConfigurationTest.java

**Motivation**:
`ArmeriaServerHttpRequest` implements `org.springframework.http.server.reactive.ServerHttpRequest`.
However `ArmeriaServerHttpRequest` does not implement `getRemoteAddress` and relies on default method which returns null.
As a result when using Armeria as an underlying server of Spring WebFlux, we get `Optional.empty` remoteAddress from serverRequest handled by handlerFunction.
For example, suppose there's a routerFunction like below.
```
@Bean
public RouterFunction<ServerResponse> route() {
return RouterFunctions
.route(RequestPredicates.GET("/route")
.and(RequestPredicates.accept(MediaType.TEXT_PLAIN)),
serverRequest -> {
// remoteAddress() returns Optional.empty()
Optional<InetSocketAddress> remoteAddress = serverRequest.remoteAddress();
ServerResponse.ok().build();
}); …
```

Implement ArmeriaServerHttpRequest.getRemoteAddress()

---

docs-client/build.gradle
docs-client/yarn.lock

…h unrelated work and to make sure build fails if lockfile needs to be updated by a new dependency but hasn't been.
Users can update the lockfile by running the `yarn` command directly without Gradle (probably most common) or the new `yarnUpdate` task.

Have yarn task default to frozen lockfile to not update yarn file with unrelated work

---

core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/common/util/OsType.java
core/src/main/java/com/linecorp/armeria/common/util/SystemInfo.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java

Motivation:
Related #1645
`useOpenSsl` in `Flags` is used only when TLS is enabled. However, it takes a lot to instantiate `OpenSsl` class so it adds up a tremendous time to the server startup time. We should fix to instantiate it only when it needs.
Modification:
- Set `useOpenSsl` in `Flags` lazily
- Check whether the OS is Linux before calling `Epoll.isAvailable()`
- Add `OsType`
Result:
- Reduced server startup time to 80 percent (20% decreased)

Set useOpenSsl in Flags lazily to reduce server startup time

---

core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandler.java
core/src/main/java/com/linecorp/armeria/internal/Http1ClientCodec.java
core/src/main/java/com/linecorp/armeria/internal/ReadSuppressingHandler.java
core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java

Currently, HTTP/1 codec is forked from upstream to allow deactivating sessions in it, and HTTP/2 handler has some API machinery to deactivate sessions there too. We can avoid forking and separating logic by having a single handler that takes care of deactivation.

Deactivate HttpSession in separate handler from codecs.

---

dependencies.yml

- www.slf4j.org and logback.qos.ch started to respond with non-200
status.

Update SLF4J and Logback Javadoc URL

---

core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TestDnsServer.java

Motivation:
In Netty, `DnsNameResolver` only caches if the failure was not because of an IO error or timeout, but that was caused by query itself.
So we should follow the behavior.
Modifications:
- Cache only when the raised `UnknownHostException` does not have cause.
Result:
- Do not cache when IO error or timeout happens
To-do:
- Sending a PR to upstream so that we don't rely on this checking cause to figure out the cause is cacheable or not.

Fix not to cache DNS failure when timed out

---

benchmarks/src/jmh/java/com/linecorp/armeria/common/stream/StreamMessageBenchmark.java
benchmarks/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java
benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/BackoffBenchmark.java
benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/RetryingHttpClientBase.java
benchmarks/src/jmh/java/com/linecorp/armeria/grpc/shared/ClientType.java
benchmarks/src/jmh/java/com/linecorp/armeria/grpc/shared/GithubApiService.java
benchmarks/src/jmh/java/com/linecorp/armeria/grpc/shared/SimpleBenchmarkBase.java
benchmarks/src/jmh/java/com/linecorp/armeria/internal/PathParsingBenchmark.java
benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkBase.java
benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkClient.java
settings/checkstyle/checkstyle.xml

For the following classes (in the bechmark module) I don't know what kind of Javadoc I want to write for them. That's why I need some help. 
- com.linecorp.armeria.core.client.retry.WithDuplicator
- com.linecorp.armeria.core.client.retry.WithoutDuplicator
- com.linecorp.armeria.grpc.downstream.DownstreamSimpleBenchmark
- com.linecorp.armeria.grpc.upstream.UpstreamSimpleBenchmark
- com.linecorp.armeria.retrofit2.downstream.DownstreamSimpleBenchmark
- com.linecorp.armeria.retrofit2.upstream.UpstreamSimpleBenchmark
Fixes #2136

Add some missing Javadoc comments

---

core/src/main/java/com/linecorp/armeria/client/Endpoint.java
core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
core/src/test/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroupTest.java

Motivation:
`DynamicEndpointGroup` currently does not accept an update request which
changes only the weight of an existing `Endpoint`.
Modifications:
- Fix `DynamicEndpointGroup` so that it accepts the case where only
weights are changed.
- Improve `Endpoint.hashCode()` so it does not invoke `authority()`
unnecessarily.
Result:
- `DynamicEndpointGroup` always notifies its listeners when meaningful
changes are detected.

Make `DynamicEndpointGroup` respect a weight change

---

core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java

I guess we always use `isInstanceOf` for this sort of check since it's the same as a catch clause and this was probably a typo. I found an environment where the test fails with `SearchDomainUnknownHostException` which doesn't exactly match and the test fails. I guess it happens when DNS search domains are set.
```
2019-11-11T15:32:47.6365221Z com.linecorp.armeria.client.RefreshingAddressResolverTest > removedWhenExceedingBackoffMaxAttempts() FAILED
2019-11-11T15:32:47.6365686Z     java.lang.AssertionError: 
2019-11-11T15:32:47.6366100Z     Expecting:
2019-11-11T15:32:47.6368092Z      <io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'foo.com' failed to resolve …
```

Don't use exact match when checking UnknownHostException in test

---

core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java

I have seen the below sort of flake - I don't see anything particularly wrong with the test so hypothesize that the timeout handler event loop gets slowed down for some reason while a different event loop for the response runs. So I'm hoping setting the event loop would help in this case though not sure until I never see the error again ;)
I also went ahead and changed to use the lambda pattern for the builders - it took me 5 minutes to understand what's going on with the same method being called at same indentation level multiple times. I've never been a fan of the fluent API and I think this is a good example of how it can really encourage poor user code readability.
```
com.linecorp.armeria.server.ServerBuilderTest > serviceConfigurationPriority() FAILED …
```

Set event loop for delayed responses in test.

---

core/src/main/java/com/linecorp/armeria/server/HttpStatusException.java
core/src/test/java/com/linecorp/armeria/server/HttpStatusExceptionTest.java

Motivation:
Users may want to record why they are throwing `HttpStatusException` by
specifying its cause.
Modifications:
- Add the static factory methods that require `Throwable cause` to
`HttpStatusException`
- Fixed a bug where `HttpStatusException.of(int)` always returns a
non-verbose exception.
Result:
- Users can add a cause to an `HttpStatusException`.

Allow `HttpStatusException` to have a cause

---

core/src/test/java/com/linecorp/armeria/server/ServerTest.java
thrift/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java

Motivation:
Found this flaky test:
```
com.linecorp.armeria.server.ServerTest > customStartStopExecutor FAILED
Expecting:
<"Test worker">
to start with:
<"com.linecorp.armeria.server.ServerTest#customStartStopExecutor">
at com.linecorp.armeria.server.ServerTest.lambda$customStartStopExecutor$11(ServerTest.java:386)
at java.base/java.util.concurrent.LinkedTransferQueue.forEachFrom(LinkedTransferQueue.java:1699)
at java.base/java.util.concurrent.LinkedTransferQueue.forEach(LinkedTransferQueue.java:1719)
at com.linecorp.armeria.server.ServerTest.customStartStopExecutor(ServerTest.java:386)
```
It happens because the `startStopExecutor` executes the `server.stop()` task right away before the main thread attach the callback using `thenApply(...)`.
It makes the thread …

Fix flaky test in ServerTest

---

core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java
core/src/test/java/com/linecorp/armeria/server/ServerTest.java

Motivation:
`HttpServerHandler` creates an `EarlyRespondingRequestContext` which
does not implement `ServiceRequestContext` when handling an invalid
request. The default `AccessLogWriter` implementations expects all
`RequestContext`s on the server side are `ServiceRequestContext`. As a
result, an invalid request triggers a `ClassCastException` in
`AccessLogWriter`.
Such an assumption that a service-side context is always
`ServiceRequestContext` is reasonable, so we should always provide a
`ServiceRequestContext` rather than just a `RequestContext`.
Modifications:
- Remove `EarlyRespondingRequestContext`.
- Always use `DefaultServiceRequestContext`, even for invalid requests
and the `OPTIONS *` request.
- Enable access logs for the test cases that tests invalid paths.
- Simplify the …

Always use `ServiceRequestContext` on the server side

---

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
core/src/main/java/com/linecorp/armeria/server/Routed.java
core/src/main/java/com/linecorp/armeria/server/RoutingResult.java
core/src/main/java/com/linecorp/armeria/server/RoutingResultBuilder.java
core/src/main/java/com/linecorp/armeria/server/RoutingResultType.java
core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java

Motivation:
Currently, with the following code:
.route().get("/foo").build(someService);
a CORS preflight request (OPTIONS method) will go to `someService`,
which is not an expected behavior.
It is mainly because of the hack we added some time ago for adding
support for `@CorsDecorator`:
- `DefaultRoute` - https://github.com/line/armeria/blob/armeria-0.95.0/core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java#L88-L99
- `AnnotatedHttpServiceFactory` - https://github.com/line/armeria/blob/armeria-0.95.0/core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java#L368-L378
Modifications:
- Add `RoutingResultType` to represent three routing state:
- `MATCHED`
- `NOT_MATCHED`
- `CORS_PREFLIGHT` (not matched, but need to handle a …

Make sure a CORS preflight request doesn't go to a wrong service

---

site/src/sphinx/_static/add_badges.js

Motivation:
Our Slack shared invite link expires sooner than expected. It may be
because some bots are visiting the invite link following the link.
Modifications:
- Add `rel=nofollow` to the badge links
Result:
- The Slack shared invite link may expire later.

Add `rel=nofollow` to the site badge links

---

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java

Motivation:
Domain name resolution failure was reported on Windows OS. #2243
Before solving the original problem, this workaround enables [`DefaultAddressResolverGroup`](https://netty.io/4.1/api/io/netty/resolver/class-use/DefaultAddressResolverGroup.html) by the flag. This flag is disabled by default.
The `DefaultAddressResolverGroup` uses JDK's built-in domain name lookup mechanism. See [here](https://netty.io/4.1/api/io/netty/resolver/DefaultNameResolver.html) for more information.
Modification:
* Add `useJdkDnsResolver` flag to enable `DefaultAddressResolverGroup`.
* Use `DefaultAddressResolverGroup.INSTANCE` if it is possible.
Result:
A user can now use  `DefaultAddressResolverGroup` by enabling `useJdkDnsResolver` flag.

Allow configuring DefaultAddressResolverGroup by flag

---

dependencies.yml

Motivation:
Armeria Build is failed on macOS Catalina(10.15.1) with `netty-tcnative-boringssl-static-2.0.27.Final`.
```
> Task :examples:grpc-service:test FAILED
#
#
#
#
#
#
```
`Netty 4.1.43.Final` which is used in [Armeria 0.96.0](https://github.com/line/armeria/blob/armeria-0.96.0/dependencies.yml#L11) was release with [tcnative 2.0.26.Final](https://github.com/netty/netty/blob/netty-4.1.43.Final/pom.xml#L318).
Modification:
* Revert netty-tcnative-boringssl-static to `2.0.26`
Result:
A user who uses macOS Catalina can build Armeria project.

Revert netty-tcnative-boringssl-static version to `2.0.26.Final`

---

brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
docs-client/build.gradle

Annotations are displayed in the zipkin UI as a table to be able to see time spent in individual steps of a span. It should be useful to users to be able to see client connection timings in spans.
Interestingly, until #2272 it's likely these annotations will happen before the span start time, which is not how spans are normally recorded. It shouldn't hurt though to have them since they're just numbers in a table. The other issue is actually a lot more work, so in the meantime at least this provides useful numbers.
Misc: I found that there would always be a 30-60s pause between `yarnSetup` and `yarn` on my computer and found it's because `gradle-node-plugin` adds `node_modules` as a task output, causing Gradle to hash every single file in there which takes forever. Without defining it as …

Add connection timing annotations to client spans.

---

benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
core/src/main/java/com/linecorp/armeria/client/encoding/HttpDecodingClient.java
core/src/main/java/com/linecorp/armeria/common/AggregatedHttpRequest.java
core/src/main/java/com/linecorp/armeria/common/AggregatedHttpResponse.java
core/src/main/java/com/linecorp/armeria/common/HeaderOverridingHttpRequest.java
core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/main/java/com/linecorp/armeria/common/RequestContext.java
core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpService.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/ManagedHttpHealthCheckService.java
core/src/test/java/com/linecorp/armeria/client/HttpClientWithRequestLogTest.java
core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpRequestTest.java
core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpResponseTest.java
core/src/test/java/com/linecorp/armeria/common/HttpRequestDuplicatorTest.java
core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
core/src/test/java/com/linecorp/armeria/server/encoding/HttpEncodedResponseTest.java
examples/proxy-server/src/main/java/example/armeria/proxy/ProxyService.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
testing/junit/src/main/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServerExtension.java
testing/junit/src/test/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServiceExtensionTest.java

Motivation:
- The following two methods look confusingly similar to each other and
`HttpRequest` implements `Publisher`:
- `HttpRequest.of(RequestHeaders, Publisher)`
- `HttpRequest.of(HttpRequest, RequestHeaders)`
- Some static factory methods could be just member methods:
- `HttpRequest.of(HttpRequest, RequestHeaders)`
- `HttpRequest.of(AggregatedHttpRequest)`
- `HttpResponse.of(AggregatedHttpResponse)`
Modifications:
- Deprecated `HttpRequest.of(HttpRequest, RequestHeaders)` in favor of
`HttpRequest.of(RequestHeaders, HttpRequest)`
- Improved `HttpRequest.of(RequestHeaders, Publisher)` and
`HttpResponse.of(Publisher)` so that they handle `HttpRequest` and
`HttpResponse` specially.
- Added `HttpRequest.withHeaders(RequestHeaders)`
- Deprecated `HttpRequest.of(AggregatedHttpRequest)` and …

Clean up the factory methods in `Http{Request,Response}`

---

site/src/sphinx/client-custom-http-headers.rst

Hello Armeria fellows,
I found that some custom header example is old-fashion (not working), so I changed the example.
While I am working this job, I found that `ClientOptionsBuilder` example is now deprecated, so it would be better to change another example to utilize `ClientOptionsBuilder`, but all are deprecated. If you have any idea for that, I will update for it also.

Fix outdated documentation in `client-custom-http-headers.rst`

---

core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/common/util/Sampler.java
core/src/main/java/com/linecorp/armeria/common/util/Samplers.java
core/src/test/java/com/linecorp/armeria/common/util/SamplerTest.java

Motivation:
Modifications:
- Add `Sampler.rateLimiting()`.
- Deprecate `Sampler.rateLimited()`.
- Make `Sampler.of(String)` accept `rate-limiting=n` and `rate-limit=n`
as well as `rate-limited=n`.
Result:
- Fixes #2122
- (Deprecation) `Sampler.rateLimites()` has been deprecated in favor of
`rateLimiting()`.

Deprecate `Sampler.rateLimited()` in favor of `rateLimiting()`

---

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java

This adds support for the `deadline` option of a gRPC client stub. Now, if this is provided, for example by one of the gRPC integration tests, it is handled correctly at the client side - previously it only sort of worked because it would often be handled at the server side.
I also added an option, not available in usptream, to ignore a client-specified timeout in the server. I've always felt it unsafe that gRPC server uses a client header to determine timeout, and this flag can be used for situations without trusted clients (and unit tests :) ).
Fixes #2008

Respect gRPC stub deadline.

---

benchmarks/src/jmh/java/com/linecorp/armeria/common/stream/StreamMessageBenchmark.java
benchmarks/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java
benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
core/src/main/java/com/linecorp/armeria/server/DefaultRoutingContext.java
core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java

While looking through routing code, I randomly found that this class doesn't have equals / hashCode. It means it will break any routing cache (not only is it itself never cached but it will pollute the cache with garbage and cause it to be ineffective). Luckily, it seems to only be used in rarer cases of falling back to trailing slash and prefix + regex paths, which are rare, and composite service router, which doesn't use the server's main router so has a limited scope for cache pollution.
In another PR, I'm going to remove `summary()`, it seems like an inefficient way to save just a bit of code and isn't our normal pattern for hashCode / equals in other classes. But want to take it a step at a time if it's ok.
Also fixed JMH compilation that probably stopped working with a version …

Implement RoutingContextWrapper equals / hashCode / toString

---

core/src/main/java/com/linecorp/armeria/server/CompositeRouter.java
core/src/main/java/com/linecorp/armeria/server/RouteCache.java
core/src/main/java/com/linecorp/armeria/server/Router.java
core/src/main/java/com/linecorp/armeria/server/Routers.java
core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java
core/src/main/java/com/linecorp/armeria/server/RoutingTrieBuilder.java
core/src/test/java/com/linecorp/armeria/server/HttpServerAutoRedirectTest.java
core/src/test/java/com/linecorp/armeria/server/RouterTest.java
core/src/test/java/com/linecorp/armeria/server/RoutingTrieTest.java

Motivation:
For example, if a user bound a service at `prefix:/docs`, the service
will get requests only when the request path starts with `/docs/`, which
means `/docs` will not be matched.
This is not a problem when there is no other mappings that match `/docs`
because Armeria will automatically redirect you to `/docs/`.
However, the following code will not work:
// `/docs` will not be redirected to `/docs/` but handled by
// `HttpFileService`.
Server server =
.service("prefix:/docs", new DocService())
.service("prefix:/", HttpFileService.of(...))
.build();
... because the `HttpFileService` will handle the request to `/docs`.
To address this issue, we need to introduce some special casing for the
path without a trailing slash.
However, the redirection should not occur …

Automatic redirection with a trailing slash

---

core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/main/java/com/linecorp/armeria/server/ProxiedAddresses.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
core/src/test/java/com/linecorp/armeria/server/HttpHeaderUtilTest.java
core/src/test/java/com/linecorp/armeria/server/ProxyProtocolEnabledServerTest.java
core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java

Motivation:
It is not easy to log a user's desired IP among multiple proxied IP addresses. See #1631
Modification:
* Add `clientAddressMapper()` to `ServerBuilder` and `ServerRequestContext`
* Revise `ProxiedAddresses` to hold multiple destination addresses
Result:
* A user can now select a client IP address from proxied addresses.
Fixes: #1631

Provide a way to specify client IP from proxied addresses

---

brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java

Related: #2248
Motivation:
When a client disconnects from a server, the `HttpResponse` being
prepared by a service was simply aborted with an `AbortedStreamException`.
However, since 0.96.0, thanks to #2248, an `HttpResponse` is aborted
with more specific exception, such as:
- `ClosedSessionException` on a disconnection
- `Http2Exception.StreamException` on an HTTP/2 RST_STREAM frame
However, `HttpResponseSubscriber` was not updated to handle the above
exceptions, which means they will leave noisy `WARN` level logs.
Modifications:
- Handle the exceptions which may cancel the current stream properly.
- Add `Exceptions.isStreamCancelling()`
- Fix a bug where `HttpResponseSubscriber` records
`responseFirstBytesTransferredTimeNanos` incorrectly.
- Make sure to cancel the health check response …

Fix noisy `WARN` logs on client disconnection

---

docs-client/package.json
docs-client/src/index.html
docs-client/src/index.tsx
docs-client/webpack.config.ts
docs-client/yarn.lock
licenses/web-licenses.txt

The main reason for using favicons-webpack-plugin is to avoid having the same source file in the repo twice, but we don't need to generate a full suite of favicons for a debug page.
We also can avoid bundling in fonts to reduce size further. Worst case is if in a constrainted network fonts don't load, the page will still work fine (and maybe even with correct fonts if the OS contains roboto)
Incidentally, I found out that favicon won't work in most cases since it doesn't support relocation (e.g., mounting at `/docs`) until https://github.com/jantimon/favicons-webpack-plugin/pull/173
Fixes #2299

Slim down docs client

---

core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java

While reading through https://github.com/line/armeria/commit/b597f7a865a527a84ee3d6937075cfbb4470ed20 to understand it, I had to look up what the `~` operator does 😅  I think it's very uncommonly used and better to avoid if it's not necessary to improve readability. I found that because we don't need to presize the `BitSet` (it's a static final) and `BitSet.get` efficiently checks characters outside the range of the `BitSet`, it doesn't seem necessary and we can make the code more readable. What do you think?

Reduce bit operations for header validation

---

benchmarks/src/jmh/java/com/linecorp/armeria/common/HttpHeadersBenchmark.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java

For https://github.com/line/armeria/security/advisories/GHSA-35fr-h7jr-hh86 we have added back header validation to prevent injection attacks. I think there are many many servers that don't have exposure to this issue, most of them because they only use server-server RPC which is always HTTP/2, and others because they don't have any chance of setting headers with untrusted content. In the interest of our recent goal of reducing overhead for RPC-only scenarios (for reference, I don't see such validation in grpc-java, where it shouldn't be needed as they're HTTP/2-only), I propose adding a flag to allow users to disable the validation.
```
Benchmark                                  Mode  Cnt         Score        Error  Units
HttpHeadersBenchmark.create_noValidation  thrpt    5  24338315.495 …
```

Add flag to control header validation.

---

core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
core/src/test/java/com/linecorp/armeria/client/DefaultWebClientTest.java

Bugfix- disappearing query params, during webclient request execution with undefined endpoint, right CLA commit email

Fix a bug where query params disappear when `WebClient` executes

---

core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java

- Wait until all pending responses are flushed.

Fix flaky `HealthCheckServiceTest`

---

NOTICE.txt
dependencies.yml
examples/README.md
examples/grpc-reactor/build.gradle
examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/HelloServiceImpl.java
examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/Main.java
examples/grpc-reactor/src/main/proto/hello.proto
examples/grpc-reactor/src/test/java/example/armeria/grpc/reactor/HelloServiceTest.java
gradle/scripts/lib/java-rpc-proto.gradle
licenses/LICENSE.reactive-grpc.bsd.txt
settings.gradle

This adds an example for gRPC using the [reactive-grpc](https://github.com/salesforce/reactive-grpc) library.
See https://github.com/line/armeria-examples/pull/2
I, @cbornet, hereby release the Git commits in [this pull request](https://github.com/line/armeria-examples/pull/2310) ('The Contribution') under [Creative Commons Zero 1.0](https://creativecommons.org/publicdomain/zero/1.0/), so that anyone can modify and/or redistribute The Contribution without any restriction.

Add grpc-service-reactor example

---

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java
grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocServicePlugin.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java

Just found these random points. One is removing an unused field (after we switched to pre-preparing the response headers)

Small gRPC cleanups

---

core/src/main/java/com/linecorp/armeria/internal/dns/DefaultDnsNameResolver.java
core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java

Motivation:
The `UnknownHostException` created by `DefaultDnsNameResolver` does
not tell a user about the DNS queries it sent.
Modifications:
- Update the messages of the `UnknownHostException`s created by
`DefaultDnsNameResolver`, so they are more user-friendly.
- Improve the coverage of `DnsAddressEndpointGroupTest`.
- Maybe fix the flakiness of `DnsAddressEndpointGroupTest.backoff()` and
`backoffOnEmptyResponse()`.
Result:
- User-friendliness
- Fixes #2315

Improve exception message of `UnknownHostException`

---

core/src/main/java/com/linecorp/armeria/common/QueryStringDecoder.java
core/src/main/java/com/linecorp/armeria/common/QueryStringEncoder.java

Motivation:
As demonstrated by @franz1981, we can bypass JVM's array boundary checks
completely, by using `PlatformDependent.getByte()`.
Modifications:
- Optimize `QueryStringEncoder.isUnsafeOctet()` and
`QueryStringDecoder.decodeHexNibble()` using
`PlatformDependent.getByte()`.
- Fix an off-by-one error in `decodeHexNibble()`
Result:
- Another performance gain
- Fixes an off-by-one error in `decodeHexNibble()`

Improve the performance of query string encoding/decoding

---

core/src/main/java/com/linecorp/armeria/common/QueryStringDecoder.java
core/src/main/java/com/linecorp/armeria/common/QueryStringEncoder.java

Motivation:
@nitsanw and @franz1981 came up with an even faster way to convert a
character into a primitive value:
- Allocate an array as long as 65536.
- Use a character as an index.
- No need for boundary check at all because a `char` never exceeds
65535 by definition.
- Increased cache miss may be a concern, but I guess it will not
matter because most characters will be in ASCII range anyway.
Modifications:
- Use a 65536-byte long lookup table for decoding a hexdecimal nibble
and determining if a character needs to be percent-encoded.
Result:
- Nice performance boost

Make `QueryString{Encoder,Decoder}` even faster

---

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceExtensions.java
core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceExtensions.java
core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceBuilderTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactoryTest.java
core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceHandlersOrderTest.java
core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilderTest.java
core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtilTest.java

Motivation:
Add more ways to add global annotated service extensions
Modifications:
- Add a way set AnnotatedHttpServiceExtensions from `{VirtualHost,Server}Builder`
- Change creation time about `{VirtualHost}AnnotatedServiceBindingBuilder` 
Result:
Closes #1752

Add more ways to add global annotated service extensions

---

benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java
core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java
core/src/main/java/com/linecorp/armeria/common/RequestContext.java
core/src/main/java/com/linecorp/armeria/common/RequestContextAwareLogger.java
core/src/main/java/com/linecorp/armeria/common/logging/LogLevel.java
core/src/main/java/com/linecorp/armeria/internal/logging/LoggingDecorators.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java

Motivation:
- `ServiceConfig.loggerName()` and `ServiceRequestContext.logger()` have
been deprecated since long ago.
- `LoggerFactory.getLogger()` is currently invoked on each request to
create a new `Logger`, which may have performance impact on a certain
logging framework, such as Log4J2, as reported in #2306.
Modifications:
- Remove:
- `Server{Builder,Config}.serviceLoggerPrefix()`
- `ServiceConfig.loggerName()`
- `ServiceRequestContext.logger()`
- The default `Logger` of `LoggingService` is now:
`LoggerFactory.getLogger(LoggingService.class)`
- Add `RequestContext.makeContextAware(Logger)`
- Move `RequestContextAwareLogger` from `server` to `common`
- Make the logging implementations in `LoggingDecorators` log the
current `RequestContext`.
- Remove unnecessary `RequestLogListener` …

Remove per-service loggers

---

core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java
core/src/main/java/com/linecorp/armeria/common/util/Version.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/auth/BasicToken.java
core/src/main/java/com/linecorp/armeria/server/auth/OAuth1aToken.java
core/src/main/java/com/linecorp/armeria/server/auth/OAuth2Token.java
dependencies.yml
dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/ArmeriaHttpConnectorFactory.java
dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/ArmeriaHttpsConnectorFactory.java
dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/proxy/ArmeriaProxyConnectorFactory.java
dropwizard/src/main/java/com/linecorp/armeria/dropwizard/logging/AccessLogWriterFactory.java
dropwizard/src/main/java/com/linecorp/armeria/dropwizard/logging/CustomAccessLogWriterFactory.java
dropwizard/src/test/java/com/linecorp/armeria/dropwizard/ArmeriaConnectorFactoryTest.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/Compressor.java
grpc/src/main/java/com/linecorp/armeria/unsafe/grpc/GrpcUnsafeBufferUtil.java
rxjava/src/main/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionProvider.java
settings/checkstyle/checkstyle-suppressions.xml
settings/checkstyle/checkstyle.xml
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat90ProtocolHandler.java

Motivation:
There are some missing Javadocs due to lack of the following Checkstyle
checks:
- `MissingJavadocPackage`
- `MissingJavadocType`
- `MissingJavadocMethod`
Modifications:
- Update Checkstyle to 8.28 due to a bug in `MissingJavadocPackage`.
- https://github.com/checkstyle/checkstyle/issues/7117
- Enable the forementioned Checkstyle checks and update suppressions.
- Fix all Checkstyle violations.
Result:
- Closes #2136

Add missing Javadocs

---

docs-client/src/containers/MethodPage/DebugPage.tsx

Allow to leave requestBody box empty.
Before request with empty `requestBody` box will fail because of JSON validation
Now request with empty `requestBody` box would be executed

Fix annoying docs issue with empty request body

---

core/src/main/java/com/linecorp/armeria/server/DefaultRoutingContext.java
core/src/test/java/com/linecorp/armeria/server/RoutingContextTest.java

Motivation:
While I was making #2102, I fixed `hashCode()` and `equals()` implementation
of `DefaultRoutingContext` class as using `query()` and `headers()` rather
than `contentType()` and `acceptTypes()`. It seemed okay because I added
the properties `params()` and `headers()` to `RoutingContext`, but it was
a mistake from the `RouteCache`'s view. It would cause cache misses from
`RouteCache` because the variation of cache key becomes wide.
Modifications:
- Use `contentType()` and `acceptTypes()` from `hashCode()` and `equals()`
of `DefaultRoutingContext` class.
Result:
- `RouteCache` can cache routes as the same as before.

Fix a bug where causes cache misses from RouteCache

---

core/src/main/java/com/linecorp/armeria/common/HttpResponseWriter.java
core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriter.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
core/src/test/java/com/linecorp/armeria/internal/DefaultHttpResponseTest.java
jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java

Motivation:
`HttpResponseWriter.close(AggregatedHttpResponse)` and `StreamWriter.close(Object)`
raise an exception when 1) a user gave an invalid input or 2) the stream
is closed already while writing.
Such behavior can lead to a stream left open or a content left
unreleased.
Modifications:
- Deprecate `StreamWriter.close(Object)` which has an ambiguous
contract.
- Always close the stream for `close(AggregatedHttpResponse)` and its
cousins in `HttpResponseWriter`.
- Use `tryWrite()` and `close()` instead of `close(Object)` in our code.
Result:
- Less leak
- Less ambiguity

Make sure to close `HttpResponseWriter` and release content

---

.github/CODEOWNERS
grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/package-info.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaStatusException.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/Decompressor.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/package-info.java
grpc-protocol/src/main/java/com/linecorp/armeria/internal/grpc/protocol/StatusCodes.java
grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnaryGrpcService.java
grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/package-info.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClientTest.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnaryGrpcServiceTest.java

Motivation:
Realized that both client and server classes in `grpc-protocol` are
placed under `common.grpc.protocol`.
Modifications:
- Move the client and server side classes to `client.grpc.protocol` and
`server.grpc.protocol` respectively.
- Add @anuraaga to the owners of `/grpc-protocol/`
Result:
Consistency

Reorganize the classes in `grpc-protocol`

---

core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerMetrics.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/MetricCollectingCircuitBreakerListener.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistries.java
core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
core/src/main/java/com/linecorp/armeria/common/metric/MoreNamingConventions.java
core/src/main/java/com/linecorp/armeria/common/metric/NoopMeterRegistry.java
core/src/main/java/com/linecorp/armeria/common/metric/PrometheusMeterRegistries.java
core/src/main/java/com/linecorp/armeria/internal/metric/CaffeineMetricSupport.java
core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java
core/src/main/java/com/linecorp/armeria/server/Server.java
core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java
core/src/main/java/com/linecorp/armeria/server/file/FileService.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/MetricCollectingCircuitBreakerListenerTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java
core/src/test/java/com/linecorp/armeria/common/metric/MoreNamingConventionsTest.java
core/src/test/java/com/linecorp/armeria/internal/metric/CaffeineMetricSupportTest.java
core/src/test/java/com/linecorp/armeria/internal/metric/MicrometerUtilTest.java
core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
core/src/test/java/com/linecorp/armeria/server/ServerTest.java
core/src/test/java/com/linecorp/armeria/server/composition/CompositeServiceTest.java
grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunctionBuilder.java
retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/metric/RetrofitMeterIdPrefixFunctionTest.java
thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java

Co-authored-by: Per Lundberg <perlun@gmail.com>
Motivation:
The Micrometer naming conventions (http://micrometer.io/docs/concepts#_naming_meters)
suggest that dotted notation (`foo.bar.baz`) should be used when naming
meters and tags. This has the advantage of letting different Micrometer
monitoring implementations be able to convert it to the naming
convention which is native for it (e.g. JMX, Prometheus etc).
Modifications:
- Switch to Micrometer's naming convention everywhere.
- Add a new flag `com.linecorp.armeria.useLegacyMeterNames` which
switches back to the old meter names.
- Deprecate `MoreNamingConventions`
- The `NamingConvention`s returned by `MoreNamingConventions` now return
Micrometer's default `NamingConvention` for corresponding backend.
- …

Follow Micrometer's naming convention

---

grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientFactory.java
testing-internal/src/main/resources/logback-test.xml

Motivation:
`GrpcClientFactory` currently assumes that the stub factory methods
are always one of `newStub()`, `newBlockingStub()` and `newAsyncStub()`.
However, by using a plugin like `grpc-reactor`, the stub factory method
can be `newReactorStub()`
Modifications:
- Generalize the stub factory lookup mechanism in `GrpcClientFactory`.
- Clean-up `logback-test.xml` so that the log messages from Project
Reactor are logged.
Result:
Partial support for the gRPC client stubs generated with `grpc-reactor`.

Generalize gRPC stub factory lookup mechanism

---

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AllHealthCheckStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/PartialHealthCheckStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/PartialHealthCheckStrategyBuilder.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/AllHealthCheckStrategyTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilderTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/PartialHealthCheckStrategyBuilderTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/PartialHealthCheckStrategyTest.java

* https://github.com/line/armeria/issues/1953
* When HealthCheckEndpointGroup has a lot of candidates, it's not efficient.
* Divide `how to select health check candidate' as HealthCheckStrategy.
* Make all check strategy as default.
* Make partial check strategy.
* Add AllHealthCheckStrategy and PartialHealthCheckStrategy.

Limit the number of endpoints in HealthCheckedEndpointGroup

---

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java

Motivation:
When the default ClientFactoryOptions is passed to ClientFactoryBulider via `options(ClientFactoryOptionsptions)`,
ChannelOption.CONNECT_TIMEOUT_MILLIS is set to null.
It causes `NullPointException` in initialization of  `HttpChannelPool`. #2385
https://github.com/line/armeria/blob/f0d870fde1088114070be31b67f7df0a21e835c6/core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java#L109-L110
Modifications:
* Make `ClientFactoryOption.CHANNEL_OPTIONS` immutable.
* Copy new CHANNEL_OPTIONS and preserve the existing one.
Result:
No more `NullPointException` with `ClientFactoryOptions.of()` during client connection.
Fixes #2385
/cc @delegacy @max904-github

Preserve default `CHANNEL_OPTION`s in  `ClientFactoryBuilder`

---

retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitClassAwareMeterIdPrefixFunction.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunction.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunctionBuilder.java
retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/RetrofitClassAwareMeterIdPrefixFunctionTest.java
retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunctionTest.java

Add new meter function class for retrofit clients that provide more information:
- Raw path from the Retrofit annotaiton
- Consistent service name based on class name, by default with `service` tag
- httpMethod and httpStatus
This changes does not replace previous RetrofitMeterIdFunction as it would be breaking changes and maybe some users will prefer other variant :thinking: 
In addition to this Tag names for metric may be adjusted as well to comply with Armeria server format (currently use `path` and `httpMethod` whether Armeria server metrics provide `route` that contains path and http method at the same time)
Closes #2345

Implement class aware retrofit meter function

---

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java

Motivation:
A 4xx health check response usually indicates the client configuration
error such as missing access token.
Modifications:
- Log more friendly message when receiving a 4xx health check response.
- Remove redundant `saturatedMultiply()`
Result:
User-friendliness

Helpful message on a 4xx health check response

---

core/src/main/java/com/linecorp/armeria/client/HttpHeaderUtil.java
core/src/main/java/com/linecorp/armeria/common/util/Version.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/Server.java
core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
core/src/test/java/com/linecorp/armeria/common/util/VersionTest.java
it/server/src/test/java/com/linecorp/armeria/it/hbase/HBaseClientCompatibilityTest.java

I had a report of this stack trace
```
Exception in thread "main" java.lang.NullPointerException
at com.linecorp.armeria.server.Server.setupVersionMetrics(Server.java:319)
at com.linecorp.armeria.server.Server.<init>(Server.java:128)
at com.linecorp.armeria.server.ServerBuilder.build(ServerBuilder.java:1543)
```
Currently we always export version information into the meter registry based on a classpath resource. While the resource should almost always be present, it's conceivable that some scenario will not have the files (old fat jar methods are notorious for only having one copy of service files in the jar) and the server should still start up.
I also modified
- Cache property loading
- Return immutable map

Don't fail to start server when version info can't be found.

---

build.gradle
dependencies.yml
examples/grpc-kotlin/build.gradle.kts
examples/spring-boot-minimal-kotlin/build.gradle.kts

Motivation:
- Fix Kotlin plugin warning from Gradle
Modifications:
- Move `org.jetbrains.kotlin.jvm` to root script
Result:
- Fixes #2397

Fix Kotlin plugin warning from Gradle

---

core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientBuilderParams.java
core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
core/src/main/java/com/linecorp/armeria/client/ClientOption.java
core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
core/src/main/java/com/linecorp/armeria/client/Clients.java
core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientBuilderParams.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/UserClient.java
core/src/main/java/com/linecorp/armeria/client/WebClient.java
core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckerContext.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
core/src/test/java/com/linecorp/armeria/client/DefaultWebClientTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientUnwrapTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupIntegrationTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedServiceTest.java
examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
examples/static-files/src/test/java/example/armeria/server/files/MainTest.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientFactory.java
thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientInvocationHandler.java
thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java

Motivation:
When creating a new client derived from an existing client, a user can
write the following code:
```java
WebClient client = WebClient.builder(...)...build();
WebClient derived =
WebClient.builder(client.scheme().sessionProtocol(),
client.endpointGroup())
.path(client.absolutePathRef())
.factory(client.factory())
.options(client.options())
.build();
```
We could make `ClientFactory` a part of `ClientOptions`, so that a user
doesn't have to specify it manually:
```java
WebClient derived =
WebClient.builder(client.scheme().sessionProtocol(),
client.endpointGroup())
.path(client.absolutePathRef())
.options(client.options())
.build();
```
Modifications:
- Add `ClientOption.FACTORY`.
- Add `AbstractClientOptionsBuilder.factory(ClientFactory)`
- Remove the `factory(ClientFactory)` …

Make `ClientFactory` a part of `ClientOptions`

---

core/src/test/java/com/linecorp/armeria/internal/EventLoopThreadTest.java

Seems good to me. I guess there might be an issue if proguard strips out `NonBlocking` from our jar? ~~Armeria and reactor are in different classloaders? It'd be interesting to hear more details of the deployment setup to add to #2404~~

Add test for #2404 (Reactor non-blocking integration)

---

core/src/main/java/com/linecorp/armeria/client/DecodedHttpResponse.java
core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java
core/src/main/java/com/linecorp/armeria/common/HeaderOverridingHttpRequest.java
core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java
core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java

Motivation:
While I was working on #1409, I found out that `subscribe` and `drainAll` methods in `StreamMessage` have a lot of boilerplate code so I wanted to remove them.
Modifications:
- Add `StreamMessage.defaultSbuscrbierExecutor()`
Result:
- (Breaking)
- Deprecated `StreamMessage.subscribe(..., boolean withPooledObjects)` is now gone.
- Use `StreamMessage.subscribe(..., SubscriptionOption.WITH_POOLED_OBJECTS)`.
- Deprecated `StreamMessage.drainAll(..., boolean withPooledObjects)` is now gone.
- Use `StreamMessage.drainAll(..., SubscriptionOption.WITH_POOLED_OBJECTS)`.

Clean up StreamMessage subscribe methods

---

core/build.gradle

Related: #2404
Motivation:
We allowed Proguard to prune all classes that are not under
`com.linecorp.armeria` (except the internal ones). This can make our own
forked tag interface `reactor.core.scheduler.NonBlocking` to be pruned
by ProGuard, although it is currently kept indirectly and automatically.
It'll be safer if we configure ProGuard explicitly.
Modifications:
- Add ProGuard `keep` for `reactor.core.scheduler.NonBlocking`
Result:
- No chance of regression

Prevent ProGuard from pruning Reactor `NonBlocking`

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
core/src/main/java/com/linecorp/armeria/common/DefaultHttpRequestDuplicator.java
core/src/main/java/com/linecorp/armeria/common/DefaultHttpResponseDuplicator.java
core/src/main/java/com/linecorp/armeria/common/FixedHttpRequest.java
core/src/main/java/com/linecorp/armeria/common/FixedHttpResponse.java
core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
core/src/main/java/com/linecorp/armeria/common/HttpRequestDuplicator.java
core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/main/java/com/linecorp/armeria/common/HttpResponseDuplicator.java
core/src/main/java/com/linecorp/armeria/common/PublisherBasedHttpResponse.java
core/src/main/java/com/linecorp/armeria/common/logging/BinaryContentPreviewer.java
core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageDuplicator.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java
core/src/test/java/com/linecorp/armeria/common/DefaultHttpRequestDuplicatorTest.java
core/src/test/java/com/linecorp/armeria/common/DefaultHttpResponseDuplicatorTest.java
core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorVerification.java
examples/proxy-server/src/main/java/example/armeria/proxy/AnimationService.java

Motivation:
Before I get into #1409, I need to clean up the duplicator so that `FixedStreamMessage` and other `StreamMessage`s can have the same APIs to return the duplicator.
Modifications:
- Add `StreamMessage.toDuplicator()`
- Add `StreamMessageDuplicator`, `HttpRequestDuplicator` and `HttpResponseDuplicator` interfaces
Result:
- (Breaking)
- `HttpRequestDuplicator` and `HttpResponseDuplicator` are now interfaces.
- You should use `HttpRequest.toDuplicator()` and `HttpResponse.toDuplicator()` to use the duplicators.
To-dos:
- Implement a new duplicator that optimizes `FixedStreamMessage` by wrapping it.
- Move `DefaultStreamMessageDuplicator` under the internal package. Related #2360

Add StreamMessage.toDuplicator

---

core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/main/java/com/linecorp/armeria/internal/RequestContextThreadLocal.java
core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java

Motivation:
When we send a data, we don't buffer but flush them to the socket one by one.
However, under heavy load, especially when using HTTP/2, there's a chance that the data is not fully written(partial write) or nor written at all because of the lack of the space in sending buffer. http://man7.org/linux/man-pages/man2/write.2.html
Even though we try to push the data to the socket while spinning (16 times by default), it could fail.
In that case, we just store data to `ChannelOutboundBuffer` and try it next time when writing other data.
This is where the trouble begins. The next write that would be handling a different request, which means different `RequestContext` in the thread-local, completes the writing and executes all callbacks. Some of the callback should not be invoked with …

Fix a bug where callbacks are invoked with the wrong context

---

examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/Main.java
saml/src/main/java/com/linecorp/armeria/server/saml/KeyStoreCredentialResolverBuilder.java

I noticed there is one SAML implementation API exposed in our public API. Given SAML's diligent separation of API and implementation, I guess it's better for us to also make sure to only expose the API.

Don't expose SAML impl in public API.

---

.appveyor.build.sh
.appveyor.yml
build.gradle

Also adds JRE exact version to paths so version can be updated without manually clearing CI cache
I found that JDK12 has this bug when generating javadoc
https://bugs.openjdk.java.net/browse/JDK-8222091
I sort of wonder how we've been releasing so far (do we release on Windows?), but I guess it's a good time to switch to JDK13 for release.

Switch to JDK 13 for releasing and CI build.

---

brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
core/src/test/java/com/linecorp/armeria/client/Http1EmptyRequestTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupAuthorityTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupLongPollingTest.java
core/src/test/java/com/linecorp/armeria/internal/DefaultHttpRequestTest.java
core/src/test/java/com/linecorp/armeria/internal/DefaultHttpResponseTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerHeaderValidationTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
dependencies.yml
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerAutoConfigurationTest.java
testing-internal/src/main/java/com/linecorp/armeria/testing/internal/TestUtil.java
testing-internal/src/main/resources/junit-platform.properties
thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
thrift/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java

Motivation:
JUnit Jupiter provides various properties that controls the timeout
behavior globally, and we could use them instead of manually specifying
`Timeout` annotations with magic numbers.
Modifications:
- Disable timeout on debug by default.
- Set 60-second timeout for all testables and life cycle methods.
- Remove `TestUtil.withTimeout()`
- Update dependencies:
- JUnit Platform 1.5.2 -> 1.6.0
- JUnit 5.5.2 -> 5.6.0, 4.12 -> 4.13
Result:
No need to add `Timeout` annotation

Use JUnit Jupiter's global timeout settings

---

core/src/main/java/com/linecorp/armeria/client/endpoint/CompositeEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java

Motivation:
`EndpointGroup` does not extend `ListenableAsyncCloseable` but only
`AsyncCloseable`, because otherwise we would have to expose the methods
that do not blend well into `Endpoint`. However, it does not stop other
`EndpointGroup` implementations from implementing
`ListenableAsyncCloseable`.
Modifications:
- The following classes now implement `ListenableAsyncCloseable`:
- `DynamicEndpointGroup`
- `CompositeEndpointGroup`
- `OrElseEndpointGroup`
- `HealthCheckedEndpointGroup` now closes itself automatically when its
`ClientFactory` is closed.
Result:
- Easier to inspect the life cycle state of some `EndpointGroup`s.
- `HealthCheckedEndpointGroup` now closes itself automatically when its
`ClientFactory` is closed.
- Closes #1084

Make some `EndpointGroup`s implement `ListenableAsyncCloseable`

---

core/src/main/java/com/linecorp/armeria/server/Route.java

Motivation:
Fix typo "amd" -> "and" in JavaDoc of class `com.linecorp.armeria.server.Route`
Modifications:
Modify "amd" to "and" in class `com.linecorp.armeria.server.Route`
Result:
No typo in JavaDoc of class `com.linecorp.armeria.server.Route`

Fix typo in JavaDoc

---

grpc/build.gradle
grpc/src/main/proto/com/linecorp/armeria/grpc/internal_exception_messages.proto

…adoc.
I found that unfortunately the outer class still has some, uncommonly used, functionality (holds the `Descriptor` of the proto) so couldn't remove it completely. Renamed it to include the word `Internal` (the public apis in the class are useless, just the descriptor specifications stored there are what we still want to keep) and excluded it from javadoc, hope this is ok.

Rename debug.proto to more internal-sounding type

---

core/src/main/java/com/linecorp/armeria/client/circuitbreaker/FailFastException.java

Motication:
User got a trouble on make test code when (s)he tried to do a test on
circuitBreaker and when it raises an exception (FailFastException).
Originally, to reproduce the exception, user needs to use Reflection to
make exception.
Modification:
Make FailFastException consturctor public, add java doc comment for it.
Make parameter checking for nonNull
Result:
public constructor for FailFastException and java doc
Issued by #2440

Make FailFastException public

---

core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerStrategy.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/main/java/com/linecorp/armeria/common/HttpResponseWriter.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupLongPollingPingTest.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpClientResponseSubscriber.java

We can use `HttpStatus.is*()` instead of `HttpStatus.codeClass() == HttpStatusClass.CLASS_NAME`.

Use `HttpStatus.is*()` for brevity

---

gradle.properties
gradle/scripts/README.md
gradle/scripts/lib/common-dependencies.gradle
site/build.gradle
spring/boot1-autoconfigure/build.gradle

…of manually aggregating all dependencies.
Now that we do dependency management using Gradle, `gradle-versions-plugin` can be applied to our dependency management itself rather than aggregating dependencies across projects. This simplifies the configuration a little.
This also removes `configureondemand`. This flag is strongly discouraged by Gradle team since it's too easy to introduce fragility and as Gradle is much faster at configuration than 2.x, it doesn't help much anymore. 
https://github.com/gradle/gradle/issues/2868
It's so fragile that it completely breaks if you have multiple Kotlin build scripts in a hierarchy
https://github.com/gradle/kotlin-dsl-samples/issues/311
The `dependencyManagement` tweak here ends up in this scenario
- For normal builds, all projects need to depend …

Apply gradle-versions-plugin to dependencyManagement project

---

core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
core/src/main/java/com/linecorp/armeria/internal/client/DnsUtil.java

Motivation:
If there's no network interfaces that support IPv6, we must not send a DNS query for that.
Modification:
- Check the network interfaces in `DnsAddressEndpointGourp` not to make IPv6 DNS query.
Result:
- `DnsAddressEndpointGourp` does not send DNS queries for AAAA when IPv6 is not available.

Fix a bug where making IPv6 DnsQuestion when it's not supported

---

docs-client/src/containers/App/index.tsx

This PR fixes an issue with overlapping method type and name in the DocService sidebar.
- The `spacing` parameter is a multiple of 8 pixels. I can adjust if necessary.

Fix overlap in DocService sidebar

---

core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
core/src/test/java/com/linecorp/armeria/server/ServiceRoutingTest.java

Motivation:
Annotated services are lazily bond to `VirtualHost` to apply `AnnotatedServiceExtensions` to them. #2316
It causes a change in the order of original service binding defined by the user.
This is critical if a user uses a global fallback service.
In the following example, the user added the fallback service in the last.
However, the fallback will be added first and annotated services will be added later.
```java
sb.annotatedService("/api/v0/", new Object() {
@Get("regex:/projects/(?<projectName>[^/]+)")
...
});
sb.annotatedService("/api/v0/", new Object() {
@Get("/users/me")
...
});
sb.serviceUnder("/", (ctx, req) -> HttpResponse.of("fallback"));
```
Modifications:
* Make ServiceConfigBuilder implement ServiceConfigSetters
* Remove unused getters in ServiceConfigBuilder
* Merge …

Preserve service binding order when building routers

---

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupCompatibilityTest.java

Motivation:
When `HealthCheckedEndpointGroup` receives the old `armeria-lphc` header
with a single integer value, the health check fails due to
`IndexOutOfBoundsException`.
Modifications:
- Catch all exceptions while reading the `armeria-lphc` header value.
Result:
`HealthCheckedEndpointGroup` does not malfunction anymore when working
with an old server (0.97).

Fix `HealthCheckedEndpointGroup` compatibility with old servers

---

core/src/main/java/com/linecorp/armeria/server/file/CachingHttpFile.java
core/src/main/java/com/linecorp/armeria/server/file/FileService.java

Motivation:
`EventLoopCheckingFuture` logs a warning about any blocking operations
that occur in an event loop, and we do blocking operations in
`FileService` and `CachingHttpFile`.
Modifications:
- Read files via `blockingTaskExecutor` or a user-specified `Executor`.
Result:
- Fixes #2473

Fix blocking operation warnings from `FileService`

---

core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java

Related commit: 2ed97c069c6b7d070a351e60ad9d6afedfad0f1c
Motivation:
`FileServiceTest` sometimes fails with `AccessDeniedException` on Windows.
Modifications:
- Retry up to 10 times to write to a file.
Result:
- Hopefully less flakiness on Windows

Potentially fix flakiness in `FileServiceTest`

---

core/src/test/java/com/linecorp/armeria/internal/common/DefaultTimeoutControllerTest.java

Motivation:
DefaultkresetTimeout_withoutInit() is easy to fail in CI build environment.
Sometimes `resetTimeout(10)` was timed out before returns a value.
Modifications:
* Multiply timeout millis in test code
Result:
Clean up & no more flaky
Fixes #2477

Fix DefaultTimeoutControllerTest.resetTimeout_withoutInit()

---

core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java

Motivation:
`DocStringsExtractor` makes `Reflections` throw a `ReflectionsException`
if a resource folder (e.g. `META-INF/armeria/grpc`) exists but it
contains no files.
Modifications:
- Do not attempt to call `Reflections.getResources()` if the resource
folder does not contain any files.
Result:
- No more `ReflectionsException` while scanning docstrings.
- Fixes #2491

Fix `ReflectionsException` while scanning docstrings

---

core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/test/java/com/linecorp/armeria/common/EmptyReferenceCountedHttpData.java
core/src/test/java/com/linecorp/armeria/common/HttpRequestTest.java
core/src/test/java/com/linecorp/armeria/common/HttpResponseTest.java

Related: d168c5793fae8a15faf3981b3c4ad35a67f19f50
Motivation:
`HttpResponse.of()` does not release an empty `HttpData`.
Modifications:
- Made `HttpResponse.of()` release an empty `HttpData` immediately.
Result:
- Potentially less leak.
- Note that `ByteBufHttpData` ensures an empty `HttpData` is always
unpooled, so there should be no leak unless a user implemented his
or her own `HttpData` implementation like we did in the test case.

Fix a leak in `HttpResponse.of()`

---

core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java

Motivation:
`ClientUtil.failAndGetFallbackResponse()` aborts a request
conditionally, but I don't see a reason to do so. Also,
`DefaultWebClient.execute()` passes a similar logic as a fallback
function, but it doesn't seem necessary anymore.
Modifications:
- Always abort the request and finish logging.
Result:
- Less chance of unsubscribed requests

Always abort a failed client request

---

core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/UserClient.java
core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java

Realized that we already fail the request-side in
`DefaultClientRequestContext.init()` and `failEarly()`, which allowed me
to clean up 5c6ac9a77bc303729dbf640c7a0763571f8395b3 a little bit more.
Also rearranged `DefaultClientRequestContext.failEarly()` so that `abort()`
is called before log completion, like we did in `ClientUtil.fail()`, for
consistency.
Related: #2499

Clean up `ClientUtil`

---

core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java

Motivation:
When an HTTP/2 client resets the current stream, Armeria server's
request will be aborted with Netty `Http2Exception`, leaking
implementation detail.
Modifications:
- Abort with `ClosedStreamException` instead of `Http2Exception`.
Result:

Abort with `ClosedStreamException` on `RST_STREAM`

---

core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java

Handling #2511 
Motivation:
RequestContextExporter did not have export for req.id
Modification:
- Introduce REQ_ID into BuiltInProperty
- Introduce method for REQ_ID
- Update test

Make `RequestContextExporter` capable of exporting request ID

---

core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java
dependencies.yml

.. due to a known regression: https://github.com/ronmamo/reflections/issues/279
Fixes #2518

Downgrade Reflections from 0.9.12 to 0.9.11

---

core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithLoggingTest.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithMetricsTest.java
core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java

Motivation:
With `RetryingClient` involved, a `RequestLog` can have child
`RequestLog`s. Currently, the parent `RequestLog`'s request-side
properties are fetched from the first child, and response-side
properties from the last child. See: https://line.github.io/armeria/advanced-structured-logging.html#nested-log
However, if the first child request fails with an
`UnprocessedRequestException` (e.g. due to a connection refused error),
the first child's `requestCause()`, which is non-null, is propagated to
the parent log. As a result, even if the request eventually succeeded
thanks to retries, the parent log's `requestCause()` will be non-null,
making `MetricCollectingClient` consider the request as a failure.
Modifications:
- Always use `null` as a parent `requestCause()`.
- …

Do not propagate the first child's `requestCause()` for nested logs

---

core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java

Should fix #2505 
**Motivation**
It seems like `exceededMaxStreamsPropagatesFailureCorrectly` is the only test which seems to fail often.
One difference between this test and others, is that some requests are expected to fail.
Although this test waits for all successful requests to register to the server, it doesn't wait for failed responses to complete.
Wait for failed responses to complete before proceeding with assertions

Fix flaky HttpClientMaxConcurrentStreamTest

---

core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
core/src/main/java/com/linecorp/armeria/common/DefaultAttributeMap.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java
core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java

Motivation:
- `RequestContextExporter.state()` does not consider the case where the
current context has a root context. As a result, a `ClientRequestContext`
may reuse the state of its root context.
- `RequestContextExporter` does not take custom attributes into account
when determining if the properties needs to be re-exported. As a
result, custom attributes will not be re-exported even if a user
changes any of their values.
Modifications:
- Use `ClientRequestContext.ownAttr()` to check whether the state object
exists.
- Compare attribute values as well when determining if properties need
to be re-exported.
- Handle the case where attribute or header disappears.
- Implemented `toString()` for:
- `DefaultAttributeMap`
- `FakeChannel` in `AbstractRequestContextBuilder`
- …

Fix a bug where `RequestContextExporter` exports wrong properties

---

core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
core/src/test/java/com/linecorp/armeria/internal/common/logging/LoggingTestUtil.java
core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java

Motivation:
When `Logging{Client,Service}` logs requests and responses via
`LoggingDecorators`, the context must be pushed so that
`RequestContextExportingAppender` picks up the context and export the
properties to the logging framework's MDC.
Modifications:
- Push the current context before logging anything in
`LoggingDecorators`.
- Updated `Logging{Client,Service}Test` to:
- Test if the context is pushed.
- Test without using mocks excessively.
Result:
- `Logging{Client,Service}` now works well with
`RequestContextExportingAppender` or any other logging subsystem that
relies on thread-local variables.

Push the current context when logging requests and responses

---

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptionValue.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
core/src/main/java/com/linecorp/armeria/client/ClientOption.java
core/src/main/java/com/linecorp/armeria/client/ClientOptionValue.java
core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/common/StringMultimapBuilder.java
core/src/main/java/com/linecorp/armeria/common/util/AbstractOption.java
core/src/main/java/com/linecorp/armeria/common/util/AbstractOptionValue.java
core/src/main/java/com/linecorp/armeria/common/util/AbstractOptions.java
core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
core/src/test/java/com/linecorp/armeria/client/ClientFactoryOptionsTest.java
core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcFlowControlTest.java

Motivation:
Currently, the option's default values and the code that validates and
merges an option value is placed in the container classes (`*Options`)
rather than the key classes (`*Option`). This harms the readability and
maintainability of options, because:
- An option and its defalut value are maintained in different places. A
dev can forget to add a default value when adding a new option.
- If a new option is added for a certain client type only such as gRPC,
there's no way for a dev to implement a merge function specific to
that option. A dev must update the container's merge function in the
core, breaking modularity.
Modifications:
- `AbstractOption` now has default value, validator and merge function.
- As a result, type parameters of `AbstractOption`, `AbstractOptions`, …

Revamp the options API

---

core/src/main/java/com/linecorp/armeria/internal/common/util/HttpTimestampSupplier.java
core/src/test/java/com/linecorp/armeria/internal/common/util/HttpTimestampSupplierTest.java

Motivation:
The initial value of `nextUpdateNanos` is `0`, which can make
`HttpTimestampSupplier` generate an empty string if `System.nanoTime()`
returns a negative value.
Modifivations:
- Initialize `nextUpdateNanos` with the current `System.nanoTime()`
value.
- Improve testability of `HttpTimestampSupplier` so that we do not need
to busy-loop while testing.
Result:
- `HttpTimestampSupplier` works even when `System.nanoTime()` returns a
negative value.

Make `HttpTimestampSupplier` work with negative clock value

---

core/src/main/java/com/linecorp/armeria/common/logging/LogLevel.java

Motivation:
- It is sometimes necessary to represent the log level where all log
message is discarded.
- It is currently not possible to write a log message with more than
three arguments with `LogLevel.log()`.
Modifications:
- Added `LogLevel.OFF`
- Added a new variant of `LogLevel.log()` that accepts varargs.
Result:
- Can represent the state where logging is off.
- Can log with more than 3 arguments.

Add `LogLevel.OFF` and `log()` method with varargs

---

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
core/src/main/java/com/linecorp/armeria/common/stream/NeverInvokedSubscriber.java
core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReader.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpClientResponseSubscriber.java

Motivation:
According to https://github.com/reactive-streams/reactive-streams-jvm#2.13,
a subscriber must not throw an exception but just call `Subscription.cancel()`.
Some of our subscribers violated this rule so we should fix them.
Modifications:
- Call `Subscription.cancel()` instead of throwing an exception in `Subscriber`s
Result:
- `Subscriber` does not throw an exception anymore.

Fix Subscriber not to throw an exception

---

core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java

…eout*`
Motivation:
When a timeout is not scheduled for a request, a new timeout set by
`set{Request,Response}Timeout` does not work well.
See #2535
Modifications:
- Make `set{Request,Response}Timeout` call `set{Request,Reponse}TimeoutAfterMillis`
if a timeout is not scheduled yet.
Result:
The `set{Request,Response}Timeout*` properly set the new timeout when no timeout is scheduled.

Fix a bug where `ctx.set*Timeout()` does not schedule a timeout

---

core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/Clients.java
core/src/main/java/com/linecorp/armeria/client/WebClient.java
core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
core/src/test/java/com/linecorp/armeria/client/ClientBuilderTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofit.java
retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientBuilderTest.java
thrift/src/test/java/com/linecorp/armeria/it/client/endpoint/StaticEndpointGroupIntegrationTest.java
thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java

Related: #2525
Motivation:
The behavior of the `path()` method in client builder classes is
confusing. It throws an exception when the builder was created with a
URI while it doesn't when created with an `EndpointGroup`.
Modifications:
- Removed `path()` method from the builder classes.
- Added various factory methods that require a path to the clients and
client builders.
- Added various factory methods that accepts `String` in lieu of
`Scheme` or `SessionProtocol` for convenience.
- Slightly changed the behavior of `ClientBuilder.serializationFormat()`,
so it doesn't throw an exception even when the builder was created
with a URI.
- Added a variant of `ClientBuilder.serializationFormat()` that accept a
`String`.
Result:
- Less confusion.
- More convenience.
- Closes #2525

Require request path when building a client

---

dependencies.yml
spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java

Motivation:
New rawStatusCode methods are introduced in Spring 5.2.4. Spring Boot 2.2.5 has been released with it.
Modifications:
- Upgrade Spring Boot from 2.2.4 to 2.2.5
- Implement `getRawStatusCode` and `setRawStatusCode(statuscode)`
- Simplify `if else` conditions
- Rename `String status` to `String statusCode` for consistency
Result:
- Optimized implementation.
- Fixes: #2431

Implement new rawStatusCode methods in ServerHttpResponse

---

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerHandlerTest.java

Motivation:
Let's see following example:
```java
StreamMessageAndWriter<Object> stream = new DefaultStreamMessage<>();
stream.write(data);
stream.close();
stream.subscribe(mySubscriber);
stream.abort();
```
In this case, `onError()` or `onComplete()`, which `onNext(data)` is called previously, should be called. But, currently, just `onComplete()` is invoked.
Modifications:
- If `StreamMessage.abort()` or `cancel()` is called, the `StreamMessage` handles the subscriber with the event and ignores the `close()` call.
Result:
- You now get `AbortedStreamException` error when the stream is aborted after closed.

Fix StreamMessage to handle abort() correctly

---

core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperties.java
core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilder.java
core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilderTest.java
core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
site/src/sphinx/advanced-logging.rst

Motivation:
A user can export built-in properties and context attributes with predefined key or prefix.
Sometimes, he or she wants to export it with a different key for such as `JSON` structured logging.
Please see #2512 for the detail discussion.
Modifications:
- Add new builder methods to `RequestContextBuilder` for customizing the exporting key.
- Introduce a new alias format for Logback.
- `<alias>=<build-in properties>`
- `<alias>=attr:com.example.Foo#ATTR_BAR`
- XML examples:
```xml
<export>request_id=req.id</export>
<export>my_foo_bar=attr:com.example.Foo#ATTR_BAR</export>
```
- Move exporting logics from `RequestContextExporter` into `BuiltInProperty`.
- Add `req.content` for the RPC params and the content preview of the request
- Add `res.content` for the RPC result and the …

More ways to customize export keys for `RequestContextExporter`

---

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
site/src/sphinx/client-service-discovery.rst

I recently heard that some of our users specified the original endpoint group not the `HealthCheckecEndpointGroup` when building a `WebClient`.
So I thought we need to reinforce the documentation.

Add documentation creating WebClient using HealthCheckedEndpointGroup

---

core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java

Motivation:
When long-polling and periodic ping task are enabled together, which is
so by default, `PingTask` instances are not cleaned up properly, leading
to memory leak.
Modifications:
- Use `handle()` instead of `exceptionally()` to cancel `PingTask` and
`TimeoutTask`.
Result:
- Memory leak is gone.

Do not leak ping tasks in `HealthCheckService`

---

brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java

Motivation:
`BraveClientIntegrationTest` has 5 seconds timeout but it could take longer because of instrumenting test coverage.
We should increase it to 10 seconds.
Modification:
- Increase timeout for `BraveClientIntegrationTest`
Result:
- Close #2534

Increase timeout for BraveClientIntegrationTest

---

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java

- `USE_HTT2_PING_WHEN_NO_ACTIVE_STREAMS` -> `USE_HTTP2_PING_WHEN_NO_ACTIVE_STREAMS`
(Missing `P` in `HTTP2`)
- `Flags.useHttp2PingWhenNoActiveStreams` -> `Flags.defaultUseHttp2PingWhenNoActiveStreams`
(Default value flags must start with `default` like all other default value flags.)
- `OnWhen` -> `When`
/cc @sivaalli

Fix naming mistakes in HTTP/2 ping options

---

core/src/main/java/com/linecorp/armeria/common/QueryParams.java

- Fixed incorrect parameter description for `queryString`.
- Fixed a grammar error in `withMutations()`

Fix Javadoc errors in `QueryParams`

---

NOTICE.txt
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/OneElementFixedStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/RegularFixedStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/TwoElementFixedStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java
core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java
core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
core/src/test/java/com/linecorp/armeria/common/stream/SubscriberThrowingExceptionTest.java
licenses/LICENSE.rxjava.al20.txt
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java

Motivation:
An exception raised by a `Subscriber`'s `onNext()` or other handler methods can cause an unexpected connection drop.
We should handle it.
Modifications:
- Catch the exception thrown by `onSubscribe()` and `onNext()` from `Subscriber`s.
- Aabort the stream or call `onError` with the cause.
- Catch the exception thrown by `onComplete()` and `onError()`, and log it.
- Fork `CompositeException` from RxJava.
Result:
- Close #2475
- The connection is not closed by unhandled exceptions from `Subscriber`s anymore.

Handle exceptions from Subscribers

---

brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/internal/common/RequestTimeoutScheduler.java
core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java

Motivation:
DefaultClientRequestContext and DefaultServiceRequestContext have duplicate code.
It is easy to make mistakes.
Modifications:
* Add RequestTimeoutScheduler and migrate duplicate code
* Remove timedOut flag in DefaultServiceRequestContext and delegate to RequestTimeoutScheduler
* Increase globalTimeout in BraveClientIntegrationTest (still flaky)
Results:
Clean up and deduplicate code

Deduplicate timeout code in RequestContext implementations

---

core/src/main/java/com/linecorp/armeria/common/HttpMethod.java
core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
core/src/main/java/com/linecorp/armeria/server/Route.java
core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
core/src/main/java/com/linecorp/armeria/server/Routers.java
core/src/test/java/com/linecorp/armeria/server/RouterTest.java
core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java

Motivation:
Check out this code:
```java
sb.decorator((delegate, ctx, req) -> {
System.err.println(2);
return delegate.serve(ctx, req);
});
sb.routeDecorator().pathPrefix("/").build((delegate, ctx, req) -> {
System.err.println(1);
return delegate.serve(ctx, req);
});
sb.decoratorUnder("/", (delegate, ctx, req) -> {
System.err.println(3);
return delegate.serve(ctx, req);
});
```
The executed order of decorators are a little messed becuase `routeDecorator()` has all `HttpMethod`s set, but others don't.
If we set `HttpMethods.knownMethods()` when there's no method set for a route, the execution order of decorator will be the order they inserted.
Modifications:
- Add `HttpMethod.knownMethods()` to the `Route` if it's empty.
- However, the logger name and metric don't include it because it's …

Add all HTTP methods to route when the method is empty

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/DefaultExceptionHandler.java
core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionVerbosity.java

Motivation:
An annotated sevice currently logs all exceptions except the following
by default:
- `IllegalArgumentException`
- `HttpStatusException`
- `HttpResponseException`
However, it logs some ignorable socket-related exceptions, such as
`ClosedSessionException`.
Modifications:
- Check the exception with `Exceptions.isExpected()` before logging.
Result:
- Reduced amount of meaningless log messages

Do not warn on unexpected exceptions in annotated services

---

core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/main/java/com/linecorp/armeria/common/ClosedSessionException.java
core/src/main/java/com/linecorp/armeria/common/stream/ClosedStreamException.java
core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriberTest.java

Motivation:
It is sometimes hard to know why a connection or a stream has been
closed or reset.
Modifications:
- Allow a user specify a message or a cause when creating a
`Closed{Session,Stream}Exception`.
- Specify a message or a cause when creating `Closed{Session,Stream}Exception`
when applicable.
- Removed redundant instantiation of `ClosedSessionException`s.
- Fixed a bug where `ClosedSessionException` is raised when
`ClosedStreamException` is expected.
Result:
- More information when diagnosing a `Closed{Session,Stream}Exception`
- Fixed a bug where `ClosedSessionException` is raised when
`ClosedStreamException` is expected.

Specify why on `Closed{Session,Stream}Exception`

---

core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java

Motivation:
`HttpHeaders` is an immutable type, and thus we do not need to make a
copy of `additional{Request,Response}{Headers,Trailers}` when creating
a derived `RequestContext`.
Modifications:
- Do not copy. Just assign.
- Simplify the related test cases
Result:
- Performance

Remove unnecessary header copies when deriving a context

---

core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java

…Client
Motivation:
`System.nanoTime()` can return a negative number. 
So the sum of `System.nanoTime()` and `responseTimeoutMills` can also be zero
even if `responseTimeoutMillis` is positive.
Modifications:
- Add `isTimeoutEnabled` flag for checking whether the timeout was set
or not
Result:
Remove a potential timeout bug

Make `RetryingClient` handle negative nano time properly

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java
site/src/sphinx/server-annotated-service.rst

Motivation:
`UUID` is commonly used to represent a unique ID.
However `UUID` is not included in the supported types by default.
Modifications:
- Add UUID to `supportedElementTypes` in `AnnotatedServiceTypeUtil`
Result:
You can now bind `UUID` to path variables or query parameters.
Fixes #2573

Allow `UUID` to be bound to annotated service parameters

---

core/src/main/java/com/linecorp/armeria/internal/common/AbstractRequestContextAwareFuture.java
core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
core/src/test/java/com/linecorp/armeria/internal/common/RequestContextAwareFutureTest.java
core/src/test/java9/com/linecorp/armeria/internal/common/Java9RequestContextAwareFutureTest.java

Motivation:
If a context if pushed from an unexpected thread of forgetting to close the previous context, we raise an exception.
However, this could happen in a future, which means that the exception might not be propagated to the caller, we should warn to let the user knows.
Modification:
- Warn if a context is pushed illegally.
Result:
- You easily notice if a context is pushed illegally.

Warn if context is pushed illegally

---

core/src/main/java/com/linecorp/armeria/common/RequestContextAwareLogger.java

Motivation:
`RequestContextAwareLogger` currently does not push the context when
logging, which means `RequestContextExporter` will not be able to export
the properties to MDC.
Modifications:
- Push the context every time `RequestContextAwareLogger` logs.
- Use `TemporaryThreadLocals` when building a log message.
Result:
- `RequestContextAwareLogger` pushes the context as expected by
`RequestContextExporter`, and thus the properties are exported to MDC.

Make `RequestContextAwareLogger` push context

---

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java

Motivation:
When an HTTP/2 stream is closed by the other side before sending a request headers, we should call `response.close(cause)` to close the response.
If we don't call that, the request is closed later by the peer's timeout mechanism because the response timeout and idle timeout is not activated.
Modification:
- Call `response.close(cause)` when HTTP/2 stream is closed and fails to send a request header.
Result:
- You no longer see the dangling unfinished responses.
To-do:
- Wrap `ProxyConnectException` with `UnprocessedRequestException`.

Fix a bug where response is not closed with an exception

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/common/util/TextFormatter.java
core/src/main/java/com/linecorp/armeria/internal/common/util/TemporaryThreadLocals.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/test/java/com/linecorp/armeria/common/util/TextFormatterTest.java

- Use `TemporaryThreadLocals` to reduce `StringBuilder` reallocation.
- Add `RequestId`s
- Move the slow path to a separate method so that fast path can be
inlined.
- Add `TextFormatter.socketAddress()` and `inetAddress()`
- Fix method ordering.
- Fix indentation
- Fix for a potential `NPE` on Windows in
`DefaultServiceRequestContext.{local,remote}Address()`

Reimplement `RequestContext.toString()`

---

core/src/main/java/com/linecorp/armeria/common/util/CountingSampler.java
core/src/main/java/com/linecorp/armeria/common/util/Sampler.java
core/src/main/java/com/linecorp/armeria/common/util/Samplers.java
core/src/test/java/com/linecorp/armeria/common/util/CountingSamplerTest.java
core/src/test/java/com/linecorp/armeria/common/util/SamplerTest.java

Motivation:
`CountingSampler` is currently using `double` for probability, while [Brave](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/sampler/CountingSampler.java#L60) (where this class was originally forked from) is using `float`. This causes issues when passing in floats like `0.01f`, which is converted to `double` as `0.009999999776482582`. This causes `percent` to be `0`.
Modification:
- Change `CountingSampler` to accept a `float`.
Result:
When passing in the probability of `0.01f`, the percentage is correctly calculated as `1`.

Change CountingSampler to accept float instead of double

---

benchmarks/src/jmh/java/com/linecorp/armeria/common/HttpRequestHeaderConversionBenchmark.java
benchmarks/src/jmh/java/com/linecorp/armeria/common/HttpResponseHeaderConversionBenchmark.java
core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/main/java/com/linecorp/armeria/internal/client/ClientHttp1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/client/ClientHttp2ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/client/HttpHeaderUtil.java
core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/server/ServerHttp1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/server/ServerHttp2ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java

Motivation:
Currently, user-provided HTTP headers and trailers are consumer by
`HttpRequestSubscriber` and `HttpResponseSubscriber`. The following is
the basic header/trailer validation and conversion process:
1. `Http*Subscriber` merges the `Request/ResponseHeaders` and
`ctx.additional*Headers()` while excluding some prohibited headers.
2. `Http*Subscriber` passs the merged headers to `HttpObjectEncoder`.
3. `HttpObjectEncoder` converts the merged headers while excluding some
more prohibited headers, using `ArmeriaHttpUtil`.
(Pretty much same for trailers)
Instead, we could streamline and optimize this process like the following:
1. `Http*Subscriber` passes `Request/ResponseHeaders` and
`ctx.additional*Headers()`, without any validation or exclusion.
2. `HttpObjectEncoder` converts the …

Streamline HTTP header/trailer validation and conversion

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
core/src/main/java/com/linecorp/armeria/common/util/TimeoutMode.java
core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
core/src/test/java/com/linecorp/armeria/internal/common/DefaultTimeoutControllerTest.java
core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
core/src/test/java/com/linecorp/armeria/server/ServerTest.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java

…ions.
Motivation:
The new timeout API was introduced in Armeria 0.98.0 and `set*Timeout{Millis}` has been deprecated. #2343
However, we got some internal inquiries about how to replace the `setTimeout{Millis}`.
It is hard to implement with the existing API.
On the other hand, some of the users are confused about the new timeout API.
See #2535 for the detail discussion.
I think we need to clean and revamp the timeout API before 1.0
Modifications:
- Undeprecate `set*Timeout{Millis}`
- Deprecate `set*TimeoutAt{Millis}` without a replacement
- Deprecate `set*TimeoutAfter{Millis}` in favor of `setTimeout{Millis}(TimeoutMode.FROM_NOW, ...)`
- Deprecate `extend*Timeout{Millis}` in favor of `setTimeout{Millis}(TimeoutMode.EXTEND, ...)`
- Add TimeoutMode enum
- Migrate deprecated API
- Use …

Revamp `RequestContext.set{Request,Response}Timeout()`

---

core/src/main/java/com/linecorp/armeria/server/auth/AuthFailureHandler.java
core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java
core/src/main/java/com/linecorp/armeria/server/auth/AuthServiceBuilder.java
core/src/main/java/com/linecorp/armeria/server/auth/AuthSuccessHandler.java

Motivation:
Related: #2323
Result:
- (Breaking) `AuthSuccessHandler` and `AuthFailureHandler` now does not have type parameters.

Fix AuthSuccessHandler to use HttpRequest and HttpResponse

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestLogAccess.java
core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java

Motivation:
`RequestId` is used for tracking the request and the response pair.
A request can be executed multiple times by `RetryingClient`.
It is difficult to group and trace all retried requests without the request ID of the original request.
By accessing the parent log from the current request context, we are able to log the parent and current request ID pair.
Modifications:
- Add `parent()` to `RequestLogAccess`
- Include the request ID of parent log to `toString()` in `DefaultClientRequestContext`
Results:
- You can now access a parent log from a child log.
- `DefaultClientRequest.toString()` contains a parent request ID if available.
- Fixes #2588

Provide a way to access a parent log from a child log

---

core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/main/java/com/linecorp/armeria/client/HttpSession.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java

Motivation:
When sending requests asynchronously, the requests might not be sending in order due to DNS resolution and HTTP/2 multiplexing.
If it happens after stream ID is assigned, the request, which tries to create a new stream after a stream whose ID is bigger is created, couldn't be used.
Modifications:
- Assign the stream ID right before writing `RequestHeaders`.
Result:
- You no longer see `ClosedStreamException` due to the stream creation reversal

Assign stream ID right before writing RequestHeaders

---

core/src/test/java/com/linecorp/armeria/common/stream/SubscriberThrowingExceptionTest.java

The test failure was because we cannot specify the executor when `PublisherBasedStreamMessage` subscribes the publisher.

Fix intermittent test failure in SubscriberThrowingExceptionTest

---

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java

Fixes #2601
**Motivation**
Before proxy connection is successfully negotiated, all writes are pending and not sent.
This signifies proxy negotiation failure is safely retry-able.
Ignore `ProxyConnectException`  due to write failure in `HttpRequestSubscriber`.
Wrap `ProxyConnectException` in `HttpSessionHandler. exceptionCaught`

Wrap ProxyConnectException with UnprocessedRequestException

---

grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/CallCredentialsDecoratingClient.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java

Because `CallCredentials` can resolve headers asynchronously, this ended up being more complicated than I expected, but using a decorator means it's not so bad.
Fixes #2619

Add support for gRPC CallCredentials.

---

brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/main/java/com/linecorp/armeria/internal/client/ClientHttp1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/client/ClientHttp2ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/client/ClientHttpObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/common/HttpHeadersUtil.java
core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/server/ServerHttp1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/server/ServerHttp2ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/internal/server/ServerHttpObjectEncoder.java
core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerAdditionalHeadersTest.java

Motivation:
After #2372 merged, the additional headers are not contained to the `ResponseHeaders` of the log.
We should fix it to contain.
Modifications:
- Split `HttpObjectEncoder.writeHeaders()` to `writeHeaders()` and `writeTrailers()`.
- Interface `HttpObjectEncoder`.
- Add `ClientHttpObjectEncoder` and `ServerHttpObjectEncoder`.
- Fix a bug where an exception is not wrapped with `UnprocessedRequestException` when it fails to write a `RequestHeaders`.
- Fix a bug where additional headers is added to informational headers.
- Fix a bug where `ResponseHeaders` log does not contain additional headers.
- Fix a bug where response trailers is not logged
- Refactor `HttpResponseSubscriber` and `HttpObjectEncoder`
Result:
- You now can see the additional headers in `RequestLog`.
To-do:
- …

Fix the ResponseHeaders log to contain additional headers

---

core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/DnsTimeoutException.java
core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java
core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java

Motivation:
DNS resolution could take longer when there's more than one `DnsServerAddressStream`.
Modifications:
- DNS resolution is timed out after `queryTimeoutMillis`.
Result:
- DNS resolution is timed out after `queryTimeoutMillis`.
- Close #2621

Fix a bug where DNS resolution is not timed out

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
rxjava/src/test/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionTest.java
rxjava2/src/test/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunctionTest.java

Movation:
When an annoated service returns `Single<HttpResponse>`, the serialized result is not the content of `HttpResponse`
For example, the following service will not return `"a"`.
```java
@Get("/http-response")
public Single<HttpResponse> httpResponse() {
return Single.just(HttpResponse.of("a"));
}
```
The serialization of `HttResponse` class itself is returned
```json
{
"empty": false,
"open": false,
"complete": false
}
```
Modifications:
- Do not covert result if it is an instance of `HttpResponse` already
Result:
- You can now return `HttpResponse` with `Single` or `Maybe` in an annotated service.

Fix a bug where `Single<HttpResponse>` is not serialized properly in annotated service

---

core/src/main/java/com/linecorp/armeria/common/ClosedSessionException.java
core/src/main/java/com/linecorp/armeria/common/stream/ClosedStreamException.java
core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java

Motivation:
`ClosedSessionException` also means that all sessions are closed.
If `ClosedSessionException` extends `ClosedSessionException`,
a `ClosedSessionException` can be caught by `ClosedSessionException`.
It will be useful when a user wants to make their own retrying strategy.
Modifications:
- Make `ClosedStreamException` extensible
- `ClosedSessionException` extends `ClosedStreamException` instead of `RuntimeException`
Result:
- You can now catch `ClosedSessionException` by `ClosedStreamException`
- Fixes #2596

Make `ClosedSessionException` extend `ClosedStreamException`

---

core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java
core/src/test/java/com/linecorp/armeria/server/HttpResponseSubscriberTest.java
core/src/test/java/com/linecorp/armeria/server/encoding/HttpEncodedResponseTest.java
dependencies.yml

…mpty
Motivation:
`EncodingService` should not try to encode the body when the status indicates that the content it empty.
Modifications:
- Check the status if it indicates the content is empty in `EncodingService`.
- Downgrade Micrometer to 1.3.6 becuase 1.4.0 is Non-LTS.
Result:
- `EncodingService` does not encode the content when the status is 204, 205 and 304

Do not encode response when the status indicates empty content

---

core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java

Motivation:
`HealthCheckService` warns a user when a specified `HealthChecker` does
not implement `ListenableHealthChecker`, but doesn't tell which
`HealthChecker` exactly it is.
Modifications:
- Update the log message so it's easier to understand and to know which
`HealthChecker` is a problem.
Result:

Log which health checkers are not listenable

---

site/src/sphinx/server-basics.rst

Motivation:
The typo "res" is leading to mis-understand as HttpResponse in sample code. It should be HttpRequest.
Modification:
Just change "res" to "req".
Result:
Typo is fixed.

fix typo : res -> req

---

dependencies.yml

Curator 4.3.0 depends on ZooKeeper 3.5.7.
So we should align the version.
Modifications:
- Zookeeper 3.6.0 -> 3.5.7
- Checkstyle 8.30 -> 8.31
- Dropwizard 2.0.2 -> 2.0.5
- gax-grpc 1.54.0 -> 1.55.0
- java-jwt 3.10.1 -> 3.10.2
- json-unit 2.16.0 -> 2.16.2
- Retrofit 2.8.0 -> 2.8.1
- Spring Boot 2.2.5.RELEASE -> 2.2.6.RELEASE

Downgrade ZooKeeper

---

docs-client/src/containers/App/index.tsx
docs-client/src/containers/MethodPage/DebugPage.tsx

Motivation:
When `Use these HTTP headers for all functions.` is clicked, the event clears an HTTP headers form.
Since `stickyHeaders` is a dependent of `useEffect()` in DebugPage.
If `stickHeaders` is updated, it will refresh the form data by the user unintentionally.
Modifications:
- Remove `stickyHeaders` and `addtionalHeaders` from the `useEffect()`
that initializes debug form data.
- Clear url params when navigating to other methods.
Result:
`stickyHeaders` checkbox does not clear form data anymore.

Fix a bug where `useEffect()` has wrong dependencies in DebugPage

---

core/src/main/java/com/linecorp/armeria/common/QueryStringEncoder.java
core/src/test/java/com/linecorp/armeria/common/QueryParamsTest.java

Motivation:
When `toQueryString()` is called with empty `QueryParams`, an exception arisen.
Modifications:
- Modify to return just empty string when `toQueryString()` is called with empty `QueryParams`..
Result:
Does not arise the exception when `toQueryString()` is called with empty `QueryParams`.

Fix a bug where `toQueryString()` with empty `QueryParams`

---

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java

Motivation:
`HealthCheckedEndpointGroup.refreshContexts()` can trigger its
reentrance by calling `DefaultHealthCheckerContext.destroy()` while
iterating over them. `destroy()` can trigger `updateHealth()`, which
triggers `refreshContexts()`.
Modifications:
- Protect `refreshContexts()` from reentrance by setting the thread
local flag as early as possible.
Result:
- No more `ConcurrentModificationException` hopefully.

Fix `ConcurrentModificationException` in `HealthCheckedEndpointGroup`

---

core/src/main/java/com/linecorp/armeria/client/retry/HttpStatusBasedRetryStrategy.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java

Motivation:
A user sometimes needs to retry on any (or certain type of) exceptions.
Modifications:
- Add `RetryStrategy.onException()`
- Relax the type parameter of `onStatus()`
- Clean up the JavaDoc
Result:
A user can retry on any (or certain type of) exceptions more conveniently.

Add `RetryStrategy.onException()`

---

javadoc/build.gradle
settings.gradle

Motivation:
We'd like to move our Javadoc to javadoc.io in the future. In
javadoc.io, each artifact has its own Javadoc, but it'll be more
user-friendly if we publish all-in-one Javadoc as well.
Modifications:
- Add `armeria-javadoc` which provides an all-in-one Javadoc JAR.
Result:
- A user can browse the all-in-one Javadoc at javadoc.io.
- A user can browse different versions of Javadocs in the future.

Publish all-in-one Javadoc JAR to Maven Central

---

thrift/src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java
thrift/src/main/java/com/linecorp/armeria/internal/common/thrift/TByteBufTransport.java
thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftTreeStructureTest.java
thrift/src/test/thrift/TreeStructTest.thrift
thrift0.12/src/test/thrift/TreeStructTest.thrift
thrift0.9/src/test/thrift/TreeStructTest.thrift

Motivation:
If a union has a recursive tree structure, `TTEXT` protocol fails to decode the serialized JSON text
even though `TBINARY` works fine. Our internal user initially reported the problem.
The cause is
1. The generated thrift code does not provide field class in `FieldMetaData`, only a typedef.
```java
// in the genereated Branch.java
tmpMap.put(_Fields.LEAF_TYPES, new FieldMetaData("leafTypes", TFieldRequirementType.DEFAULT,
new ListMetaData(org.apache.thrift.protocol.TType.LIST,
new FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT, "LeafType"))));
```
2. When `TTEXT` protocol fails to get class of the field, it will try to search the current field class in the stack frame.
However, `LeafType` class is hidden by its superclass `TUnion` in the stack frame.
So …

Fix a bug where a recursive union struct failed to decode in TTEXT protocol

---

core/src/main/java/com/linecorp/armeria/common/metric/MoreNamingConventions.java

…gConvention
see https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusNamingConvention.java#L68-L74

Add seconds suffix to LONG_TASK_TIMER for legacy convention

---

docs-client/src/containers/MethodPage/DebugPage.tsx
docs-client/src/lib/transports/annotated-http.ts

Adds a new button in the doc service to allow pretty print of the response.
I've created a test endpoint that creates an object with 100 elements and each element is an object with three values:

Prettify output of REST calls in DocService if JSON

---

site/src/sphinx/advanced-logging.rst

Motivation:
- From Armeria 0.99.2, the prefix for http header of request context is changed  (`req.http_headers` -> `req.headers` (https://github.com/line/armeria/commit/6f21290a3e6e3bb2af22d8a9061d472dcabda545#diff-83d81e6e8b60860f5efe62a993aaee06L42)
Modifications:
- Update Armeria official website manual

Fix incorrect Logback settings in documentation

---

gradle.properties
site/build.gradle

Motivation:
We're going to host our Javadoc in javadoc.io, which means it doesn't
make sense anymore to inject Googla Analytics scripts in our Javadoc
without explicit user consent.
Modifications:
- Do not inject Google Analytics script into Javadoc/Xref.
Result:
- OK to deploy the Javadoc to javadoc.io.

Remove Google Analytics from references

---

core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java

Motivation:
In `ConcurrencyLimitingClient`, we have separate logic when it's unlimited.
We should take the case where the concurrency is `MAX_VALUE` as unlimited.
Modifications:
- Set the `maxConcurrency` as `0` when it's `Integer.MAX_VALUE`.
Result:
- Less overhead

Do not limit ConcurrencyLimitingClient when maxConcurrency is MAX_VALUE

---

core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java

Motivation:
`HttpResponseSubscriber` must cancel the subscription of a response
stream at any case. Unfortunately, when a service sends a response with
content for a `HEAD` request, it calls neither `subscription.request()`
nor `subscription.cancel()`, making the stream lingers until the
connection is closed.
Modifications:
Make sure `Subscription.cancel()` is called whenever response stream
processing is done.
Result:
The leak is gone.

Fix a leak in `HttpResponseSubscriber`

---

core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java

Motivations:
Found this:
```
java.lang.IllegalStateException: complete already: DefaultPromise@7efa5cc1(failure: com.linecorp.armeria.client.SessionProtocolNegotiationException: expected: http, reason: connection established, but session creation timed out: [id: xxxxx)
at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:112)
at com.linecorp.armeria.client.HttpChannelPool.lambda$connect$6(HttpChannelPool.java:424)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
at …
```

Use tryFailure in HttpChannelPool

---

core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java

Motivation:
We use MPSC queue in `DefaultStreamMessage`. If more than one thread consumes the MPSC queue,
the index of the queue is not correctly updated so a thread might spin forever in `peek()` as we've seen in #2683.
This bug was introduced from 0.98.4 #2539 by me. 😢 
Modifications:
- Fix to consume the MPSC queue only by the subscription thread.
Result:
- You no longer see the spinning thread in `StreamMessage`.

Fix a bug where two threads access MPSC queue

---

benchmarks/src/jmh/java/com/linecorp/armeria/internal/common/CacheableClassLoader.java
benchmarks/src/jmh/java/com/linecorp/armeria/internal/common/ClassLoadBenchmark.java
thrift/src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java
thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftTreeStructureTest.java

Motivation:
When decoding TTEXT protocol to Thrift Struct, FieldMetaData does not provide class instance,
it tries to load class from FQCN.
If TTEXT is used in production, the thread could be blocked by ClassLoader.
```java
java.lang.Thread.State: RUNNABLE
at sun.misc.URLClassPath$Loader.getResource(URLClassPath.java:727)
at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
- locked <0x00000004cc90fcf8> (a java.lang.Object)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass( …
```

Fix a bug where ClassLoader blocks thread when using TTEXT

---

jetty/src/main/java/com/linecorp/armeria/server/jetty/ArmeriaConnector.java
jetty/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceStartupTest.java

Prevented NPE in ArmeriaConnector during Jetty server startup with DEBUG logging enabled. Added a check for "armeriaServer" instance being NULL and return some mockup values.

Fix for issue #2688 (armeria-jetty: ArmeriaConnector - NPE when DEBUG logging enabled)

---

core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/test/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandlerTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerKeepAliveHandlerTest.java
core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java

Motivation:
A PING scheduler does not work if a ping interval is less than an idle timeout.
Because idle timeout scheduler will be triggered before PING scheduler.
But this constrain has drawbacks.
* Users might want to check the connection status without idle timeout.
* 0 idle timeout could mean Long.MAX_VALUE, not just disable it.
Modifications:
* Sent PING evnt if idle timeout is set to 0
Result:
A PING scheduler could detect dead connections without a idle timeout handler.

Allow PING scheduling with no idle timeout

---

core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandler.java
core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java

Motivation:
If a connection is closed unexpectedly by network shutdown,
the remote peer does not receive closing signals such as GOAWAY frame and
the connection is alive until cleaning up by request timeout, idle timeout, or PING fail.
When PING write fails, KeepAliveHandler tries to close the connection, which takes for the idle timeout.
Because the idle timeout is configured as `gracefulShutdownTimeoutMillis` for Netty Http2ConnectionHandler.
https://github.com/line/armeria/blob/fec9fb833275eba59eb9afaf25fc8b7c28132f80/core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java#L56-L62
Modifications:
* Close a connection immediately if KeepAliveHandler is closing.
Result:
Clean up a dead connection immediately when PING write fails.

Fix a bug where a connection is not closed immediatley when HTTP/2 PING write fails

---

core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
testing-internal/src/main/java/com/linecorp/armeria/internal/testing/NettyServerExtension.java

Related to #2698 
**Motivation**
If `needsRetryWithH1C=true` with `ProxyConfig`, the retry attempts to eventually connect to the `proxyAddress` instead of `destinationAddress`. Fix this
**Modifications**
- Remember `proxyDestinationAddress` from a successful`ProxyConnectionEvent`.
- Use `proxyDestinationAddress` for `retryWithH1C`
- Add tests for http/2 upgrade, preface request retries

Handle h1c retry failure correctly for proxy requests

---

spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/SimpleHttpCodeStatusMapper.java
spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/SimpleHttpCodeStatusMapperTest.java

Hi, I tried Spring Boot 2.3.0 GA with Armeria 0.99.5
But my app couldn't start due to ClassNotFoundException.
HealthStatusHttpMapper has been deprecated since 2.2.0 and deleted since 2.3.0
We can use `HttpCodeStatusMapper` or `SimpleHttpCodeStatusMapper` instead of it.
```
2020-05-16 00:54:21.586  WARN 88826 --- [           main] o.s.boot.SpringApplication               : Unable to close ApplicationContext
java.lang.IllegalStateException: Failed to introspect Class [com.linecorp.armeria.spring.actuate.ArmeriaSpringActuatorAutoConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5010be6]
at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
at …
```

Fix ClassNotFoundException for Spring Boot 2.3.0

---

core/src/main/java/com/linecorp/armeria/common/RequestContextStorage.java
core/src/main/java/com/linecorp/armeria/common/RequestContextStorageWrapper.java
core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
it/context-storage/src/test/java/com/linecorp/armeria/common/CustomRequestContextStorageProvider.java
it/context-storage/src/test/java/com/linecorp/armeria/common/RequestContextStorageCustomizingTest.java

Motivation:
There's currently no way to perform an additional operation on top of
the `RequestContextStorage` implementation discovered via `ServiceLoader`.
Modifications:
- Added `RequestContextStorage.hook(Function)` so that a user is allowed
to modify the current `RequestContextStorage`.
- `RequestContextStorage` is now `Unwrappable`.
- Added `RequestContextStorageWrapper`
Result:
- A user can install a custom hook in runtime, usually at startup time,
like other frameworks.

Add `RequestContextStorage.hook()`

---

core/src/main/java/com/linecorp/armeria/common/logging/RequestScopedMdc.java
core/src/test/java/com/linecorp/armeria/common/logging/RequestScopedMdcTest.java

Motivation:
Traditionally, MDC properties were bound to the current thread, but this
does not work really well for asynchronous applications, like Armeria.
Modifications:
- Added `RequestScopedMdc` which:
- provides an access to an internal map property of `RequestContext`
- replaces the default `MDCAdapter` of SLF4J so that `MDC.get()` and
`getCopyOfContextMap()` looks into the request-scoped context map
Result:
- A user can easily bind an MDC property to a `RequestContext` and log
it using a logging framework.
```java
// In some non-Armeria thread:
WebClient client = ...;
try (SafeCloseable ignored = Clients.withContextCustomizer(ctx -> {
RequestScopedMdc.copy(ctx, "transactionId");
}) {
client.execute(...);
}
```

Add `RequestScopedMdc` for request-scoped MDC properties

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
core/src/main/java/com/linecorp/armeria/common/RequestContext.java
core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestScopedMdc.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java

Motivation:
When a user tries to retrieve a context attribute while not searching
for the root context, he or she has to do the following:
RequestContext ctx = ...;
if (ctx instanceof ClientRequestContext) {
((ClientRequestContext) ctx).ownAttr(ATTR);
} else {
ctx.attr(ATTR);
}
.. which is pretry inconvenient.
Modifications:
- Pull up `root()`, `ownAttr()` and `ownAttrs()` from
`ClientRequestContext` to `RequestContext`
Result:

Pull up `root` and `ownAttr(s)` access methods

---

core/src/main/java/com/linecorp/armeria/common/logging/RequestScopedMdc.java
core/src/test/java/com/linecorp/armeria/common/logging/RequestScopedMdcTest.java

Motivation:
A user will expect the following case works:
ServiceRequestContext sctx = ...;
try (SafeCloseable ignored = sctx.push()) {
RequestScopedMdc.put(sctx, "transactionId", "1234");
ClientRequestContext cctx = ...;
try (SafeCloseable ignored2 = cctx.push()) {
assert MDC.get("transactionId").equals("1234");
}
}
.. which does not work currently, because `RequestScopedMdc` does not
look up the root context's map.
Modifications:
- Make `RequestScopedMdc.get()`, `getAll()` and `getCopyOfContextMap()`
look for the root context map.
- Reduced the memory footprint of overall map iteration by using
only `Object2ObjectMap`s.
- `Object2ObjectMap` uses a special variant of `Iterator` when iterating
over other `Object2ObjectMap`s.
- Reduced the memory footprint of `copyAll()` and …

Make `RequestScopedMdc` properties are inherited

---

core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java

Motivation:
https://ci.appveyor.com/project/line/armeria/builds/33021210/job/r29iqinga5cxk497#L55
```
WebClientBuilderTest > authorityHeader() FAILED
org.opentest4j.AssertionFailedError:
Expecting:
<false>
to be equal to:
<true>
but was not.
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at com.linecorp.armeria.client.WebClientBuilderTest.authorityHeader(WebClientBuilderTest.java:87)
```
Modifications:
- Remove asserting …

Fix flaky test `WebClientBuilderTest.authorityHeader()`

---

docs-client/src/lib/transports/annotated-http.ts

The `SyntaxHighlighter` component doesn't parse the response as HTML, so `&lt;` and `&gt;` don't render as `<` and `>`, respectively.
This PR replaces them with the actual characters.

Do not use HTML entities for zero-length response

---

benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
brave/src/main/java/com/linecorp/armeria/server/brave/ServiceRequestContextAdapter.java
core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/DefaultEventLoopScheduler.java
core/src/main/java/com/linecorp/armeria/client/EventLoopScheduler.java
core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointSelector.java
core/src/main/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/StaticEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
core/src/test/java/com/linecorp/armeria/client/DefaultEventLoopSchedulerTest.java
core/src/test/java/com/linecorp/armeria/client/MaxNumEventLoopsPerEndpointTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithContextAwareTest.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithEmptyEndpointGroupTest.java

Related: #1910
Motivation:
A client request to an empty `EndpointGroup` fails immediately with an
`EmptyEndpointGroupException`, even if there is a `Retrying(Rpc)Client`
in the decorator chain. As a result, a user cannot recover from the case
of an empty `EndpointGroup`.
Modifications:
- Change the contract of `EndpointSelector.select()` to return `null`
when there's no `Endpoint` to select instead of throwing an
`EmptyEndpointGroupException`.
- Make `DefaultClientRequestContext` handle the case where 
`EndpointGroup.select()` returns `null` so that `init()` does not treat
it as failure.
- Make `AbstractRetryingClient` handle the case where
`EndpointGroup.select()` returns `null` so that it can continue retrying.
- Modify the signature of `ClientFactory.acquireEventLoop()` and …

Allow retrying when an `EndpointGroup` is empty.

---

core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
it/micrometer1.3/build.gradle
settings.gradle

Motivation:
A user might uses Armeria 0.99.x with Micrometer 1.3.x.
We should guarantee that works.
Modifications:
- Add test module which covers the compatibilty with Micrometer 1.3.9
Result:
- You can now use Armeria 0.99.6 with Micrometer 1.3.x

Guarantee backward compatibility with Micrometer 1.3.x

---

.appveyor.build.sh
.appveyor.yml
docs-client/README.md
docs-client/build.gradle
docs-client/package.json
site/README.md
site/build.gradle
site/src/pages/community/developer-guide.mdx
spring/boot1-autoconfigure/build.gradle

Motivation:
See: https://github.com/line/gradle-scripts/pull/75
Modifications:
- Used the new `lint` and `generateSources` task added in
https://github.com/line/gradle-scripts/pull/75
- Renamed `npm run start` to `npm run develop` for consistency between
`docs-client` and `site`
- Renamed `checkWeb` or `lint` to `eslint` and made them depend on the
new `lint` task.
- Updated the developer guide so that a user runs `./gradlew
generateSources` before importing, because it will prevent the initial
compilation errors, depending on how IDE was configured.
Result:
- `./gradlew lint` runs all linters.
- `./gradlew generateSources` generates all sources.

Clean up build tasks

---

.appveyor.yml
.gitattributes

Motivation:
Using different line endings for different OSes has the following
issues:
- We sometimes break builds on Windows due to the line ending
difference.
- Artifacts (e.g. source JARs) built on Windows will have different
contents, which is not good for reproducible builds.
Modifications:
- Enforce UNIX line ending for all text files except `*.bat` and
`*.cmd`.
- Add more binary extensions.
Result:
- Fixes #2750

Use LF line ending for all OSes

---

grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/MetadataUtil.java
grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/MetadataUtilTest.java

Current implementation of `ArmeriaServerCall.close(Status status, Metadata metadata)` may send duplicate headers `:send`, `grpc-message`, `grpc-status`, and `armeria.grpc.ThrowableProto-bin`.
For example, when `StatusRuntimeException` with metadata containing `:status`, `grpc-status`, etc. is thrown, then server sends duplicate headers.
https://gist.github.com/okue/35ecbfe96c9d344a1abefc36acb0867e
```
[armeria-common-worker-nio-2-1] WARN  c.l.a.client.logging.LoggingClient - Response: { cause=io.grpc.StatusException: UNAUTHENTICATED: Error in unaryCall2, headers=[EOS, :status=200, :status=200, content-type=application/grpc+proto, grpc-status=16, grpc-message=Error in unaryCall2, content-type=application/grpc+proto, grpc-status=16, grpc-message=Error in unaryCall2, …
```

Specific headers such as :status, grpc-message, etc. in gRPC should not be duplicate

---

core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/test/java/com/linecorp/armeria/client/Http2ClientSettingsTest.java
core/src/test/java/com/linecorp/armeria/client/HttpSessionHandlerTest.java

Motivation:
If idle connections times out before the HTTP/2 SETTINGS frame is received, NPE is raised.
Modification:
- Returns `false` from `hasUnfinishedResponse()` method in `HttpSessionHandler` if the SETTINGS frame is not received yet.
Result:
- You no longer see NPE in `HttpSessionHandler` when HTTP/2 SETTINGS frame is not received from the server.

Fix NPE in HttpSessionHandler

---

core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/test/java/com/linecorp/armeria/client/Http1ConnectionReuseTest.java

Motivation:
When an HTTP/1.1 connection is reused, the connection should be returned to the pool after the request and response are complete.
Modification:
- Return the HTTP/1.1 connection to the pool after request and response are complete if pipelining is not enabled.
Result:
- You no longer see `EncoderException` when reusing the HTTP/1.1 connections.

Return HTTP/1.1 connection to the pool after request is complete

---

core/src/main/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandler.java
core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
core/src/main/java/com/linecorp/armeria/client/Http2ClientKeepAliveHandler.java
core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandler.java
core/src/main/java/com/linecorp/armeria/server/Http1ServerKeepAliveHandler.java
core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
core/src/main/java/com/linecorp/armeria/server/Http2ServerKeepAliveHandler.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
core/src/test/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandlerTest.java
core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java

Motivation:
Sometimes users might want to disconnect an active connection after a certain period of time.
This is useful when balance loads with an L4 load balancer which not understand HTTP2 connection.
By closing connections periodically, new connections are able to spread to other servers.
Modifications:
- Add `defaultServerMaxConnectionAgeMillis` flag. This option is disabled by default.
- Add `maxConnectionAge{Millis} to `ServerBuilder`.
- Record `CONNECTION_START_TIME_NANO` when a channel is initialized.
- Disconnect a connection after exceeding `maxConnectionAge` by sending:
- "Connection: close" for HTTP/1
- GOAWAY frame for HTTP/2
- Fix a bug where `channel.close()` throws NullPointerException when idle timeout is set to 0
Result:
- You can now disconnect an old connection.

Provide a way to close a connection when exceeding the maximum age on server-side

---

site/src/pages/docs/advanced-logging.mdx

Just `s/export/exports` in `site/src/pages/docs/advanced-logging.mdx`

Fix typo: </exports> -> </export>

---

docs-client/build.gradle
site/build.gradle

https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json
https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
The CI command offers massive improvements to both the performance and reliability of builds for continuous integration / continuous deployment processes, providing a consistent and fast experience for developers using CI/CD in their workflow.
(It reduces 30 seconds of the time to build site in our CI. 😄 )

Use npm ci instead npm install

---

core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java

Motivation:
https://ci.appveyor.com/project/line/armeria/builds/33334589/job/7hj0jwt7lkhavc2h#L5
```java
ServerMaxConnectionAgeTest > http1MaxConnectionAge() FAILED
Expecting:
<1365L>
to be close to:
<1000L>
by less than 35% but difference was 36.5%.
(a difference of exactly 35% being considered valid)
at com.linecorp.armeria.server.ServerMaxConnectionAgeTest.http1MaxConnectionAge(ServerMaxConnectionAgeTest.java:132)
```
Modifications:
- Measure the connection close time in the `ConnectionPoolListener` for a more accurate time.
Result:
Less Flaky 🙏

Fix flaky test `ServerMaxConnectionAgeTest.http1MaxConnectionAge`

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java

Motivation:
Given the following annotated service:
public class MyService {
@Get("/get")
public String get(@Param boolean value) {
return String.valueOf(value);
}
}
`GET /get?value=` or `GET /get?value=badvalue` injects `false` into
the parameter `value`, which is unclear to many users.
Modifications:
- Use a custom function for parsing a boolean parameter instead of
`Boolean.valueOf()`.
Result:
- Less surprising behavior
- `true`, `false`, `0` and `1` are supported.
- Fixes #2767

Validate a boolean parameter strictly in annotated services

---

core/src/main/java/com/linecorp/armeria/common/auth/OAuth1aToken.java
core/src/main/java/com/linecorp/armeria/common/auth/OAuth1aTokenBuilder.java
core/src/main/java/com/linecorp/armeria/server/auth/OAuth1aTokenExtractor.java
core/src/test/java/com/linecorp/armeria/common/auth/OAuth1aTokenTest.java
core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
docs-client/package-lock.json

Motivation:
Related https://github.com/line/armeria/pull/2680#discussion_r416371720
The current implementation for building OAuth 1a token isn't convenient.
Modifcations:
- Add `OAuth1aTokenBuilder`.
Result:
- You can now easily create `OAuth1aToken`.

Add builder for OAuth1aToken

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
site/src/pages/docs/server-annotated-service.mdx

#2760 
- Add `java.time.Period` type to `AnnotatedServiceTypeUtil`'s supported element types.
- The `AnnotatedDocServiceTest`'s unit tests are passed when I added `java.time.Period` to service.

Support java.time.Period type for `@Param` annotation

---

logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
logback/src/test/resources/com/linecorp/armeria/common/logback/testXmlConfig.xml

Motivations:
Now, `<exports>` tag like the following does not work.
```xml
<exports>remote.ip, remote.port, attrs.baz:com.example.AttrKeys#BAZ</exports>
```
Modifications:
- fix `RequestContextExportingAppender#setExports`
- based on https://github.com/okue/armeria/blob/bdecd1e8826b80e8dd76c63714979fb7480ecfe9/logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java#L199
- add a testcase for `<exports>...</exports>`

Logback <exports> tag does not work

---

site/src/pages/docs/server-annotated-service.mdx

The documentation still references `@ConditionalHeader` which doesn't exist anymore. This PR updates the documentation to reference `@MatchesHeader` instead.

Rename @ConditionalHeader in documentation

---

examples/README.md

Related: https://github.com/line/armeria-examples/pull/4
TODO: Support unapplied example projects which use `build.gradle.kts`

Add Gitpod links for armeria-examples

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactoryRegistry.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunction.java
core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java
core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunction.java
core/src/main/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunction.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceAnnotationAliasTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceBuilderTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceGenericsTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceHandlersOrderTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
core/src/test/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunctionTest.java
core/src/test/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunctionTest.java
core/src/test/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunctionTest.java
examples/annotated-http-service/src/main/java/example/armeria/server/annotated/MessageConverterService.java
site/src/pages/docs/server-annotated-service.mdx

Motivation:
Some generic converters such as `JacksonRequestConverterFunction` need
to get the complete type parameter information from annotated service
methods, so that the type of elements of a container type is known.
For example, let's say a user posts a JSON array:
[1, 2, 3]
to an annotated service method:
@Post("/post")
public String post(List<Long> values) {
return Joiner.on(", ").join(values);
}
Without proper type parameter information, `JacksonRequestConverterFunction`
cannot convert the elements into `Long`.
Modifications:
- (Breaking) Changed the signature of `RequestConverterFunction.convertRequest()`
so that a converter is given with `ParameterizedType`.
- (Breaking) `Optional` is now always handled automatically.
- If you wrote a `RequestConverterFunction` that converts to …

Provide type parameter information to `RequestConverterFunction`

---

core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java

`Subsctiption.cancel()` can happen after the stream message is complete.
So just adding a little time to wait will solve the problem.
Close #2763

Fix flaky test in PublisherBasedStreamMessageTest

---

core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java
core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java
core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClient.java
core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClientBuilder.java
core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
core/src/main/java/com/linecorp/armeria/common/logging/RegexBasedSanitizer.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestOnlyLog.java
core/src/main/java/com/linecorp/armeria/common/util/Functions.java
core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java

Motivation:
A user sometimes needs to sanitize a `RequestLog` depending on
additional information available in `RequestContext`, e.g. current
request path.
Modifications:
- Use `BiFunction<RequestContext,...>` instead of `Function` for
sanitization.
- `RegexBasedSanitizer` is now a `BiFunction`.
- Deprecate the methods that require `Function`s in:
- `Logging{Client,RpcClient,Service}Builder`
- `RequestOnlyLog.toRequestOnlyString()`
- `RequestLog.toResponseOnlyString()`
Result:
- A user can implement a sanitizer that behaves differently dependin on
the current context.
- The methods that require `Function`s in the following methods have
been deprecated:
- `Logging{Client,RpcClient,Service}Builder`
- `RequestOnlyLog.toRequestOnlyString()`
- `RequestLog.toResponseOnlyString()`
/cc @andrewoma

Provide `RequestContext` to `RequestLog` sanitizers

---

core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java

**Motivation**
Related: #2801 
Proxy client can hang when a connection is established, but the connection is closed without a `ProxyConnectEvent`.
1) If a `ProxyConnectEvent` is never received, we don't mark the session as complete.
2) Since the session isn't completed, the first write is never invoked
3) Previously we had been relying on `ProxyHandler`s pending write failures to be notified of proxy failure (`HttpRequestSubscriber.operationComplete` used to close the response previously). 
Try to fail the `sessionPromise` on proxy connect exception

Fail immediately on proxy connect exception

---

spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaGracefulShutdownConfigurationTest.java
spring/boot-autoconfigure/src/test/resources/config/application-gracefulShutdownTest.yml

Motivation:
It is an operation to apply similarly by utilizing shutdown-related properties provided by Spring Boot.
Modification:
- When this option is enabled, `ArmeriaServerConfigurator`, which sets `ServerBuilder.gracefulShutdownTimeout (..., ...)`, is registered as a Spring Bean.
- The default timeout is 30 seconds as provided by Spring Boot.
- This uses `@Value` for 1.x compatibility, It would be nice to change this later.
Result:
- Fixed #2784

Support shutdown property of spring boot

---

core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java

Motivation:
There is a flaky test on CI build of Windows.
https://ci.appveyor.com/project/line/armeria/builds/33590131/job/ldyjqjdblci54j2q#L58
```
ServerMaxConnectionAgeTest > [1] protocol=H1C FAILED
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in com.linecorp.armeria.server.ServerMaxConnectionAgeTest that uses com.linecorp.armeria.common.SessionProtocol
Expecting:
<1845.49376>
to be close to:
<1000.0>
by less than 25% but difference was 84.54937600000001%
```
Modifications:
* Modify the tolerance to between 0.8 seconds to 2 seconds from the relative 25%
Result:
Less flaky

Fix flaky test in `ServerMaxConnectionAgeTest.http1MaxConnectionAge`

---

benchmarks/build.gradle
dependencies.yml
examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
examples/grpc-kotlin/gen-src/main/java/example/armeria/grpc/kotlin/Hello.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtoReflectionServiceInterceptor.java
it/server/build.gradle

Motivation:
gRPC-Java [1.30.0](https://github.com/grpc/grpc-java/releases/tag/v1.30.0) has been released
We need a workaround for `ProtoReflectionService`. Because it does not implement `InternalNotifyOnServerBuild` anymore.
See https://github.com/grpc/grpc-java/pull/6967 #2806
It is a temporary workaround until upstream handles https://github.com/grpc/grpc-java/issues/7138.
Modifications:
- Upgrade gRPC to 1.30.0 from 1.29.0
- Add ProtoReflectionServiceInterceptor that injects dummy server to
gRPC context.
Result:
You can run gRPC 1.30.0 with Armeria server.
Fixes #2806

Update gRPC-Java to 1.30.0

---

core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/test/java/com/linecorp/armeria/common/PublisherBasedHttpResponseTest.java

Some of the subscribers violated Reactive Stremas 2.3 which is:
`Subscriber.onComplete()` and `Subscriber.onError(Throwable t)` MUST NOT call any methods on the `Subscription` or the `Publisher`.
https://github.com/reactive-streams/reactive-streams-jvm#2.3
Co-authored-by: ikhoon <ih.pert@gmail.com>

Abide by the rule Reactive Streams 2.3

---

core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java
core/src/main/java/com/linecorp/armeria/client/AbstractRuleWithContentBuilder.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRule.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleBuilder.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleUtil.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContent.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContentBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleUtil.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContent.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientRuleTest.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleBuilderTest.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
core/src/test/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderTest.java

Motivation:
A user wants to determine whether a request was successful or not from
the value of a trailer, which is currently not possible.
Modifications:
- Added `onResponseTrailers()` to `AbstractRuleBuilder` and its
subtypes, including:
- `CircuitBreakerRuleBuilder`
- `CircuitBreakerRuleWithContentBuilder`
- `RetryRuleBuilder`
- `RetryRuleWithContentBuilder`
- Added `requiresResponseTrailers()` to rule types, including:
- `CircuitBreakerRule`
- `CircuitBreakerRuleWithContent`
- `RetryRule`
- `RetryRuleWithContent`
- Updated `CircuitBreakerClient` and `RetryingClient` to respect
`requiredResponseTrailers()` flag and wait until response trailers are
available.
- Removed the `toString()` implementations in some builder classes.
Result:
- A user can break the circuit or …

Add `onResponseTrailers()` to circuit breaker and retry rule builders

---

core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
docs-client/src/containers/MethodPage/index.tsx

Motivation:
`PATCH` method is allowed to use request body in DocService. See #2756
While checking the spec, `DELETE` may have request body.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE
Modifications:
- Add `PATCH` and `DELETE` to request body allowed methods.
Result:
You can now use request body with `PATCH` and `DELETE` in Debug page.
Fixes #2756

Fix a bug where `PATCH` method could not use request body in DocService

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
core/src/main/java/com/linecorp/armeria/server/annotation/ServiceName.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestLogNameTest.java
site/src/pages/docs/server-annotated-service.mdx

Motivation:
`RequestLog.serviceName()` is introduced in #2780
To override the service name in an annotated service, `@ServiceName` annotation would be useful.
See #2809
Modifications:
- Add `@ServiceName` annotation for an annotated service class and method.
- method annotation has a higher priority than class annotation.
- Update documentation
Result:
You can now override the default service with `@ServiceName` annotation in the annotated services.
Fixes #2809

Add `@ServiceName` annotation for annotated service

---

eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ServerSetRegistrationTest.java

Motivation:
Currently, if a user specifies a port that the server doesn't open when registering
the information of a server to Eureka or ZooKeeper, `UpdatingListener` replaces the port with one of the active ports.
However, we have to use the specified port to register because a user really intended to use it in such a case that
the server is instantiated in a container and uses fort forwarding from the outside.
Modification:
- Use the specified port when registering the information of a server in `EurekaUpdatingListener` and `ZooKeeperUpdatingListener`.
Result:
- The specified port is used in `EurekaUpdatingListener` and `ZooKeeperUpdatingListener`.

Respect the specified port when registering service discovery instance

---

docs-client/package-lock.json
docs-client/package.json
docs-client/src/containers/MethodPage/DebugPage.tsx

Motivation:
Some users might not know that they can specify example requests or headers for DebugPage.
Related: #2690
Modifications:
- Add a tip to the top of Debug console
Result:
More user friendly.

Add a documentation link of example requests for DebugPage

---

dependencies.yml
kafka/src/main/java/com/linecorp/armeria/server/logging/kafka/KafkaAccessLogWriter.java
kafka/src/test/java/com/linecorp/armeria/server/logging/kafka/KafkaAccessLogWriterTest.java

Motivation:
We haven't upgraded Kafka for a long time but there's no reason to do that.
One of our customers is using `armeria-kafka` with Kafka 2.5.0 without a problem so I think there are no compatibility issues.
Modification:
- Kafka 1.1.1 -> 2.5.0

Update Kafka to 2.5.0

---

core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerMetrics.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/MetricCollectingCircuitBreakerListenerTest.java

Motivation:
`MetricCollectingCircuitBreakerListener` currently only keeps track of
event counters. It would be more convenient if we provide gauges that
represent the snapshot state of them.
Modifications:
- Add `state` gauge whose value is 1 (CLOSED), 0 (OPEN) or 0.5
(HALF_OPEN).
Result:
- Easier to get the snapshot status of circuit breakers from monitoring
system.

Add gauges for circuit breakers

---

spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractServiceRegistrationBean.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedExampleRequest.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerConfigurator.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ExampleHeaders.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcExampleHeaders.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcExampleRequest.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcServiceRegistrationBean.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/HttpServiceRegistrationBean.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/MeterIdPrefixFunctionFactory.java
spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceRegistrationBean.java

Motivation:
Many new features are added to Armeria fluent service binding builder.
But we omitted to port the features to Spring registration beans.
The registration beans switch to `ArmeriaServerConfigrator` and `DocServiceConfigrator` without difficulty.
See #2787 for more information.
Modifications:
- Deprecate HttpServiceRegistrationBean
```java
// Before:
@Bean
public HttpServiceRegistrationBean myService() {
return new HttpServiceRegistrationBean()
.setServiceName("myService")
.setService(new MyService())
.setRoute(Route.builder().path("/ok").methods(HttpMethod.GET, HttpMethod.POST).build())
.setDecorators(LoggingService.newDecorator());
}
// After:
@Bean
public ArmeriaServerConfigurator myService() {
return server -> {
server.route()
.path("/ok")
.methods(HttpMethod.GET, …
```

Deprecate Spring registration beans

---

benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
core/src/main/java/com/linecorp/armeria/client/Endpoint.java
core/src/main/java/com/linecorp/armeria/client/UserClient.java
core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
core/src/main/java/com/linecorp/armeria/client/endpoint/CompositeEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointSelector.java
core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/StaticEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
core/src/main/java/com/linecorp/armeria/common/util/AbstractListenable.java
core/src/main/java/com/linecorp/armeria/common/util/UnmodifiableFuture.java
core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
core/src/main/java/com/linecorp/armeria/internal/common/util/IdentityHashStrategy.java
core/src/test/java/com/linecorp/armeria/client/ClientRequestContextDelayedInitTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelectorTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
licenses/web-licenses.txt
thrift/src/main/java/com/linecorp/armeria/internal/client/thrift/DefaultTHttpClient.java

Motivation:
Currently, sending a request will fail immediately with an
`EmptyEndpointGroupException` when the target `EndpointGroup` is empty
without waiting at all.
If we could wait until the `EndpointGroup` has at least one `Endpoint`,
we will be able to avoid the `EmptyEndpointGroupException` at least for
the case where the `Endpoint`s disappear temporarily.
Modifications:
- Rename `EndpointSelector.select()` to `selectNow()`.
- Add `EndpointSelector.select()` that performs asynchronous endpoint
selection with timeout.
- Add `AbstractEndpointSelector` that implements the asynchronous
`select()`.
- Modify `DefaultClientRequestContext` and `ClientUtil` to use the new
asynchronous `EndpointSelector.select()` if `selectNow()` returns
`null`, so that it waits up to the connect timeout.
- …

Asynchronous endpoint selection

---

core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionCustomizer.java
core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java

Preparation for https://github.com/line/armeria/issues/2762.
Motivations:
Currently, `MeterIdPrefixFunction` can be customized with [`andThen`](https://github.com/line/armeria/blob/armeria-0.99.7/core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java#L179-L193) which takes a function of type `(MeterRegistry, MeterIdPrefix) -> MeterIdPrefix`.
But, without taking `RequestLog`, we cannot append header values to `MeterIdPrefix`.
Modifications:
- Add `andThen: (MeterRegistry, RequestOnlyLog, MeterIdPrefix) -> MeterIdPrefix`
- Deprecate the original version `andThen(BiFunction<MeterRegistry, MeterIdPrefix, MeterIdPrefix>)`
Results:
Users can customize `MeterIdPrefixFunction` easily like
```java
MeterIdPrefixFunction
.ofDefault("hoge")
.andThen((registry, log, id) -> { …
```

Add MeterIdPrefixFunction.andThen to customize MeterIdPrefix using RequestLog

---

core/src/main/java/com/linecorp/armeria/common/unsafe/PooledAggregatedHttpResponse.java
core/src/main/java/com/linecorp/armeria/common/unsafe/PooledHttpRequest.java
core/src/main/java/com/linecorp/armeria/common/unsafe/PooledHttpResponse.java
core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFile.java
core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFileBuilder.java
core/src/main/java/com/linecorp/armeria/server/file/AggregatedHttpFile.java
core/src/main/java/com/linecorp/armeria/server/file/AggregatedHttpFileBuilder.java
core/src/main/java/com/linecorp/armeria/server/file/CachingHttpFile.java
core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpFile.java
core/src/main/java/com/linecorp/armeria/server/file/FileService.java
core/src/main/java/com/linecorp/armeria/server/file/FileSystemHttpFile.java
core/src/main/java/com/linecorp/armeria/server/file/HttpDataFile.java
core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
core/src/main/java/com/linecorp/armeria/server/file/HttpFileBuilder.java
core/src/main/java/com/linecorp/armeria/server/file/NonExistentAggregatedHttpFile.java
core/src/main/java/com/linecorp/armeria/server/file/NonExistentHttpFile.java
core/src/main/java/com/linecorp/armeria/server/file/StreamingHttpFile.java
core/src/test/java/com/linecorp/armeria/server/file/CachingHttpFileTest.java
core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
site/src/pages/docs/server-http-file.mdx

Motivation:
`AggregateHttpFile` extends `HttpFile` unlike other `Aggregated*`
classes, such as `AggregatedHttpRequest`, breaking our API consistency.
Modifications:
- (Breaking) Make `AggregatedHttpFile` not extend `HttpFile` anymore.
- Add `AggregatedHttpFile.toHttpFile()`
- Add `NonExistentAggregatedHttpFile`.
- (Breaking) `HttpFile.nonExistent()` returns an `HttpFile` instead of
`AggregatedHttpFile`.
- (Breaking) `HttpFile.of(HttpData, ...)` returns an `HttpFile` instead
of `AggregatedHttpFile`.
- (Breaking) Rename `AbstractHttpFile.headers()` to `additionalHeaders()`
to avoid a method signature clash.
- Add `PooledAggregatedHttpResponse.of()`
- Use `PooledAggregatedHttp{Request,Response}.of()` when aggregating,
instead of calling the constructor directly.
Result:
- …

Separate `HttpFile` and `AggregateHttpFile` from each other

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
core/src/main/java/com/linecorp/armeria/internal/common/DefaultTimeoutController.java
core/src/main/java/com/linecorp/armeria/internal/common/TimeoutController.java
core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
core/src/test/java/com/linecorp/armeria/internal/common/DefaultTimeoutControllerTest.java
core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java

Motivation:
a gRPC client sends a request timeout in nanoseconds using `grpc-timeout` header field.
Armeria server converts it milliseconds internally.
Nanoseconds and microseconds precision will be dropped because of this conversion.
Let's say a gRPC timeout value is `10,900,000ns`.
Before sending a request, the upstream gRPC client schedules a timeout in nanoseconds.
However, the Armeria server schedules a timeout in 10ms(without decimal point).
The server will cancel a request earlier than the upstream client. Then the request ends with `CANCELLED`, not `DEADLINE_EXCEEDED`. 
This is not a critical problem in the real world because of network time.
But we can reduce unexpected failures in `ArmeriaGrpcServerInteropTest.deadlineExceeded()`
See #2812
Modifications:
- Make …

Allow a request to schedule timeout in nanoseconds precision

---

brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java

Motivation:
The `Span.start()` and `Span.finish()` estimate the current time using
`baseEpochMicros + (System.nanoTime() - baseTickNanos)`.
However, Armeria achieves the current time using `System.currentTimeMillis() * 1000` in Java8.
The two different way of getting the current time could cause an error of a millisecond.
Sometimes the tolerance makes the server appear to finish earlier than child in test case.
This is not a problem in the Brave{Service,Client} because they only use Armeria timestamp.
Modifications:
- Add 1 millseconds delay to HttpResponse
Result:
Closes #2833

Fix flaky test `BraveServiceIntegrationTest.childCompletesBeforeServer`

---

site/src/plugins/gatsby-remark-draw-patched.js

Motivation:
`gatsby-remark-draw-patched` plugin generates diagram URLs that start
with `//`, which is not correct.
Modifications:
- Generate diagramURLs that start with `/` instead of `//`.
Result:
- Our web site shows the diagrams correctly now.

Fix the URLs of diagrams in the web site

---

site/src/layouts/base.tsx
site/src/layouts/header.module.less
site/src/layouts/header.tsx
site/src/layouts/mdx.module.less
site/src/layouts/mdx.tsx

Motivation:
It is hard to navigate from one page to another in mobile view.
Modifications:
- Show the globel ToC instead of the page ToC when:
- The current layout is single-column and ToC button is clicked.
- The current layout is dual-column.
- Merge two hamburger buttons into one.
- Adjust the right margin of social icons and hamburger button for
aesthetics' sake.
Result:
- Fixes #2871

Improve mobile navigation

---

brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
build.gradle
core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/Clients.java
core/src/main/java/com/linecorp/armeria/common/AggregatedHttpRequest.java
core/src/main/java/com/linecorp/armeria/common/AggregatedHttpResponse.java
core/src/main/java/com/linecorp/armeria/common/HttpData.java
core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/main/java/com/linecorp/armeria/common/RequestContext.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
core/src/main/java/com/linecorp/armeria/internal/common/AbstractContextAwareFuture.java
core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
core/src/test/java/com/linecorp/armeria/server/TestConverters.java
dependencies.yml
grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/TestServiceImpl.java
rxjava2/src/main/java/com/linecorp/armeria/common/rxjava2/RequestContextAssembly.java
rxjava3/src/main/java/com/linecorp/armeria/common/rxjava3/RequestContextAssembly.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java

Motivation:
There are some useful annotations in errorprone.
Modifications:
- Use `@FormatMethod` with `@FormatString` and `@MustBeClosed` where applicable.
- Replace `@CheckReturnValue` and `@GuardedBy` with the ones in errorprone.
- Remove `@NotThreadSafe` that doesn't mean much.
Result:
- You can do more static checks with `@FormatMethod` with `@FormatString` and `@MustBeClosed` from errorprone.

Use annotations in errorprone

---

eureka/src/test/java/com/linecorp/armeria/client/eureka/ArmeriaEurekaClientTest.java

Motivation:
There's a race condition in `ArmeriaEurekaClientTest` where
`EurekaHttpClientWrapper.endpoints()` adds an `EndpointGroup` listener
after the endpoints are ready, making the returned `CompletableFuture`
never complete.
Modifications:
- Use `whenReady().join()`
Result:
- No more hanging build, especially in CI

Fix `ArmeriaEurekaClientTest` not to hang

---

core/src/main/java/com/linecorp/armeria/client/ClientHttp2ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
core/src/test/java/com/linecorp/armeria/server/ProxyServerAuthorityHeaderTest.java

Motivation:
An HTTP/2 request can have a `Host` header and we don't have to fill `:authority` header automatically if the request headers has the `Host` header.
Modification:
- Do not fill `:authority` header if `Host` header exists
Result:
- You no longer see the automatically filled `:authority` header if `Host` header exists in HTTP/2 requests.
- (Breaking) HTTP/2 Clients do not translate a `Host` header to the `:authority` header.

Do not fill `:authority` header if `Host` header exists in HTTP/2

---

spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcServiceRegistrationBean.java

Motivation:
gRPC service does not require a path prefix to register it to ServerBuilder.
The migration guide in #2838 uses 'path'.
Modifications:
- Use `service(HttpServiceWithRoutes, decorators)` instead
Result:
Reduce the confusion of code migration

Update GrpcServiceRegistrationBean migration guide

---

core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java

**Motivation**
While addressing comments @minwoox left, I realized the current implementation doesn't support nested ssl's properly.
https://github.com/line/armeria/pull/2752#discussion_r451341624
To be specific, `SslHandshakeCompletionEvent`s from proxy's `SslHandler` confuses armeria into thinking the ssl negotiation succeeded.
This causes `h1` requests to proceed although ssl negotation hasn't occurred, and `h2`, `https` requests to fail.
Alternatively, we may also consider dropping ssl support for proxies altogether if the cost of maintaining seems too high.
😭 😢 😭 😢 😭 😢 😭 😢 😭 😢 😭 😢 
Check `SslHandler` for client requests actually completed before proceeding with http requests.

Successful events for proxy ssl should be ignored

---

.github/CODEOWNERS

I don't use Armeria much lately. It's still my favorite framework so I hope that changes but I think it's important for everyone that my review should not be required or expected for gRPC changes. I still watch the repo so may chime in anyways, and of course happy anytime to be added as a reviewer to a PR individually instead of automatically.

Remove anuraaga from owners

---

core/src/main/java/com/linecorp/armeria/client/Endpoint.java
core/src/test/java/com/linecorp/armeria/client/EndpointTest.java

- #2869 
- Ignore userInfo when parsing `Endpoint`.

Ignore userInfo when parsing Endpoint

---

core/src/main/java/com/linecorp/armeria/common/logging/ContentPreviewerFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/common/logging/LengthLimitingContentPreviewer.java
core/src/test/java/com/linecorp/armeria/common/logging/ContentPreviewerFactoryTest.java

Motivation:
When creating a ContentPreviewerFactory withtout specifying `maxLength(...)`,
A created ContentPreviewer from the factory will have zero `maxLength`.
```java
ContentPreviewerFactory factory =
ContentPreviewerFactory.builder()
.text((unused1, unused2) -> true)
.build();
```
- The zero `maxLength` makes `length` zero always in the ContentPreviewer.
https://github.com/line/armeria/blob/e95e07b528092d90566281dac7673a71305a2705/core/src/main/java/com/linecorp/armeria/common/logging/LengthLimitingContentPreviewer.java#L52
- And also `length` could be set to 0 according to consumed content length.
https://github.com/line/armeria/blob/e95e07b528092d90566281dac7673a71305a2705/core/src/main/java/com/linecorp/armeria/common/logging/LengthLimitingContentPreviewer.java#L69
If the `length` …

Fix a bug where ContentPreviewer unexpectly releases an HttpData

---

core/src/main/java/com/linecorp/armeria/server/ServerConfig.java

Motivation:
There's no point of returning `Supplier<? extends RequestId>`.
Modifications:
- Return `Supplier<RequestId>` instead.
Result:
- Simpler method signature with less cognitive load

Use simpler return type for `ServerConfig.requestIdGenerator()`

---

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java

Related #2900
It's hard to distinguish where the response is from when many Armeria Clients are used.
If we add the remote address to the exception message, we can easily notify it.

Add more information to `ProtocolViolationException`

---

core/src/main/java/com/linecorp/armeria/client/HttpClient.java
core/src/main/java/com/linecorp/armeria/client/WebClient.java
core/src/main/java/com/linecorp/armeria/common/HttpRequestDuplicator.java
core/src/main/java/com/linecorp/armeria/common/HttpResponseDuplicator.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageDuplicator.java
core/src/main/java/com/linecorp/armeria/server/HttpService.java
core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionHandlerFunction.java
core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunction.java
core/src/main/java/com/linecorp/armeria/server/auth/AuthFailureHandler.java
eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/EurekaWebClient.java
saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceFunction.java
saml/src/main/java/com/linecorp/armeria/server/saml/SamlSingleSignOnHandler.java

Motivation:
While fixing various buffer leaks in our code, I found most leaks were
occurring because we forgot to subscribe on the `StreamMessage` objects
returned. We could add the `@CheckReturnValue` annotation to the methods
that return a `StreamMessage` so that errorprone users gets an error in
such cases.
Modifications:
- Annotate stream-returning methods with `@CheckReturnValue`.
Result:
- Less mistakes in the future

Add `CheckReturnValue` annotation on streaming output

---

core/src/main/java/com/linecorp/armeria/client/Endpoint.java

`Endpoint` is logged fairly often and thus it'd be nice if we use the
thread-local `StringBuilder` when converting it into a `String`.

Use thread-local buffer in `Endpoint.toString()`

---

core/src/main/java/com/linecorp/armeria/client/proxy/ProxyConfigSelector.java
core/src/main/java/com/linecorp/armeria/client/proxy/StaticProxyConfigSelector.java

Motivation:
I think most users won't implement `ProxyConfigSelector.connectFailed()`.
If we make it a default method, then we have only one abstract interface
method.
Modifications:
- Make `ProxyConfigSelector.connectFailed()` a functional interface.
- Reordered methods.
Result:
- A user can write a `ProxyConfigSelector` using a lambda expression.

Make `ProxyConfigSelector` a functional interface

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/annotation/Blocking.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceBlockingTest.java

Motivation:
Currently, `@Blocking` could be used only for a method
to run a service on blocking task executor.
If users want to run all services on blocking task executor,
they have to annotate all methods. It would cause a bad user experience.
I think we can widen `@Blocking` annotation target to class level without harmless.
Modifications:
- Add `ElementType.TYPE` to target of `@Blocking`
- Clean up unused parameters in test code
- Add `@SafeVarargs` for generic varags.
Result:
You can now annotate `@Blocking` annotation at the class level.

Allow `@Blocking` annotation to be used at the class level

---

core/src/test/java/com/linecorp/armeria/server/ServiceBindingTest.java

Motivation:
Some test methods in `ServiceBindingTest` does not wait until the
`RequestLog`s are fully recorded, which can cause the tests to fail
depending on how system schedules threads.
Modifications:
- Use Awaitility to wait until all `RequestLog`s are collected.

Fix flaky `ServiceBindingTest`

---

.appveyor.build.sh

Motivation:
I made a small mistake in the build script that neutralizes the attempt
to utilize hard links for build caches.
Modifications:
- Do not create the cache directory before checking its existence.
- Use different cache directories for different build profiles.
Result:
- Much less disk usage in the build machines

Use hard links for build caches

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceBlockingTest.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java

Motivation:
As like `GrpcServiceBuilder.useBlockingTaskExecutor(boolean)`,
we can give the same option to annotated services.
It would be useful when a user doesn't want to use `@Blocking` annotation.
Modifications:
- Add `useBlockingTaskExecutor(boolean)` to:
- `AnnotatedServiceBindingBuilder`
- `VirtualHostAnnotatedServiceBindingBuilder`
- Add test cases for verifying the added code
Result:
- You can now run an annotated service on blocking task executor using
`AnnotatedServiceBindingBuilder.useBlockingTaskExecutor(boolean)`.
```java
.annotatedService()
.pathPrefix("/blockingService")
.useBlockingTaskExecutor(true)
.build(new MyAnnotatedService());
```
- Fixes #2923

Add `useBlockingTaskExecutor()` to annotated service binding builders

---

core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
core/src/main/java/com/linecorp/armeria/client/ClientOption.java
core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
core/src/test/java/com/linecorp/armeria/client/ClientFactoryOptionsTest.java
core/src/test/java/com/linecorp/armeria/client/ClientOptionsBuilderTest.java
core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/EurekaClientUtil.java
grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
junit5/src/test/java/com/linecorp/armeria/testing/junit5/server/mock/MockWebServiceExtensionTest.java
retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilderTest.java
thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java

Motivation:
`*Options` seems to be a better place to host constants because it's
more consistent with other constant classes such as `HttpHeaderNames`
and `GrpcClientOptions`.
Modifications:
- Move all constants in `Client(Factory)Option` to
`Client(Factory)Options` and deprecate the old ones.
Result:
- More consistency
- A user gets the core options from `ClientOptions` and gRPC options
from `GrpcClientOptions`.
- Closes #2917

Move `Client(Factory)Option.CONSTANT` to `Client(Factory)Options`

---

zookeeper3/src/test/java/com/linecorp/armeria/common/zookeeper/ZooKeeperTestUtil.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceDiscoveryCompatibilityTest.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ServerSetRegistrationTest.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java

- Retry starting a server so that it doesn't fail with an
`address already in use` error.

Fix more flaky tests in `armeria-zookeeper3`

---

site/src/components/mailchimp.module.less
site/src/components/mailchimp.tsx
site/src/layouts/footer.module.less
site/src/layouts/footer.tsx
site/src/layouts/header.module.less
site/src/layouts/header.tsx
site/src/layouts/mdx.module.less
site/src/layouts/mdx.tsx
site/src/pages/community/articles.mdx
site/src/pages/community/index.mdx
site/src/pages/news/sign-up.mdx

- Added newsletter sign-up form to:
- Sidebar on mobile
- Right ToC pane on desktop
- This replaces the page jump control because we have the global ToC
on the left pane already.
- Made the e-mail icon lighter.
- Changed the placeholder from 'E-mail' to 'Your e-mail'.
- Changed the button label from 'Sign-up' to 'Subscribe'.
- Made the input field and button have the same height.
- Added `buttonType` property to `Mailchimp`.
- Now using `default` button type by default. It was `primary` before.
- `Mailchimp` is not lazy-loaded anymore. It appears in every page anyway.

Improve newsletter sign-up forms

---

brave/src/main/java/com/linecorp/armeria/server/brave/ServiceRequestContextAdapter.java
brave/src/test/java/com/linecorp/armeria/server/brave/ServerRequestContextAdapterTest.java
core/src/main/java/com/linecorp/armeria/server/CatchAllPathMapping.java
core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
core/src/main/java/com/linecorp/armeria/server/ExactPathMapping.java
core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java
core/src/main/java/com/linecorp/armeria/server/PathMapping.java
core/src/main/java/com/linecorp/armeria/server/PrefixPathMapping.java
core/src/main/java/com/linecorp/armeria/server/RegexPathMapping.java
core/src/main/java/com/linecorp/armeria/server/RegexPathMappingWithPrefix.java
core/src/main/java/com/linecorp/armeria/server/Route.java
core/src/main/java/com/linecorp/armeria/server/Routers.java
core/src/main/java/com/linecorp/armeria/server/file/FileService.java
core/src/test/java/com/linecorp/armeria/server/CatchAllPathMappingTest.java
core/src/test/java/com/linecorp/armeria/server/ExactPathMappingTest.java
core/src/test/java/com/linecorp/armeria/server/ParameterizedPathMappingTest.java
core/src/test/java/com/linecorp/armeria/server/PathWithPrefixTest.java
core/src/test/java/com/linecorp/armeria/server/PrefixPathMappingTest.java
core/src/test/java/com/linecorp/armeria/server/RegexPathMappingTest.java
core/src/test/java/com/linecorp/armeria/server/RouteTest.java

Motivation:
`Route.meterTag()` is not suitable for span name or url pattern.
Because it contains extra information such as `exact:` or `prefix:`.
See #2932 for the detailed information.
`Route.loggerName()` and `Route.meterTag()` are not used internally anymore.
I think users could easily replace them with newly introduced methods like `RequestLog.name()`,
`RequestLog.serviceName()` or `Route.pathPattern()`.
Modifications:
- Add `pathPattern()` method to `Route`, `PathMapping` and their subclasses.
The `pathPattern()` will return a route string according to the `Route.pathType()`
- `RoutePathType.EXACT` - "/foo" or "/foo/bar"
- `RoutePathType.PREFIX` - "/foo/*"
- `RoutePathType.PARAMETERIZED` - "/foo/:bar" or "/foo/:bar/:qux"
- `RoutePathType.REGEX` - "/**/foo"
- …

Add human-readable route string for Route

---

site/src/pages/docs/advanced-dropwizard-integration.mdx
site/src/pages/docs/advanced-saml.mdx
site/src/pages/docs/advanced-spring-webflux-integration.mdx
site/src/pages/docs/setup.mdx

Motivation:
Some artifact names have been changed in Armeria 0.99.8. #2843
However the official documentation was not changed.
Modifications:
- Use correct artifact names
- Use `Tabs` component for spring-webflux configuration.
Result:
Fix old artifact names.

Fix wrong artifact versions in documentation

---

core/src/main/java/com/linecorp/armeria/client/DefaultEventLoopScheduler.java
core/src/test/java/com/linecorp/armeria/client/DefaultEventLoopSchedulerTest.java
core/src/test/java/com/linecorp/armeria/client/MaxNumEventLoopsPerEndpointTest.java

Motivations:
Currently, the first `EventLoop` in `EventLoopGroups` is always chosen to send the first request thus,
the first DNS query as well if the `ClientFactory` is created with the default `EventLoopScheduler`.
It will be a little bit better if we spread the load to the `EventLoop`s for the first requests when a lot of `ClientFactory`s are used.
Modifications:
- Choose the first `EventLoop` randomly.
Result:
- Less load for the first `EventLoop`

Chooses the first `EventLoop` to send a request randomly

---

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java

Motivation:
Some users want to use smaller ping interval than 10 seconds.
Modifications:
- Reduce the minimum allowed ping interval from 10 seconds to 1 second
Result:
- Can send pings for the peers whose keep alive timeout is less than 10
seconds.

Reduce the minimum allowed ping interval

---

grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/Base64Decoder.java
grpc-protocol/src/test/java/com/linecorp/armeria/common/grpc/protocol/Base64DecoderTest.java

Motivation:
The [spec](https://tools.ietf.org/html/rfc4648#section-3.1) says that
```
Implementations MUST NOT add line feeds to base-encoded data unless
the specification referring to this document explicitly directs base
encoders to add line feeds after a specific number of characters.
```
So we should not add line-feed when base64 encoding.
Motivations:
- Do not add line-feed when base64 encoding.
- Address comments from @anuraaga in #2938.
Result:
- grpc-web-text does not contain line-feed characters.

Fix a bug where grpc-web-text add line-feed when base64 encoding

---

grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java

Motivation:
I made a mistake in #2938 that the `ByteBufInputStream` is not closed.
Modification:
- Close `ByteBufInputStream`
Result:
- Fewer leaks

Fix a leak in `ArmeriaClientCall`

---

grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReader.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReaderTest.java

Motivation:
HttpStreamReader receives `onComplete()` and `onError()` signal from `apply(result, cause)`
because there was no way to propagate an cause to `Subscriber`.
After #2248 work, the cause is propagated correctly.
By removing BiFunction from super class, we can remove the hard-coded signal delivery
Modifications:
- Remove `BiFunction` from `HttpStreamReader`
- Remove `whenComplete()` callbacks in `FramedGrpcService` and `ArmeriaClientCall`
- Replace `eventLoop.submit()` with `eventLoop.execute()` where the returned future is not needed.
- Limit the max size of stack trace elements for each cause to 10 in `ThrowableProto` to avoid max header size exceeded
Result:
`HttpStreamReader` abides by `Subscriber`'s `onComplete()` and `onError()`

Remove BiFunction from HttpStreamReader

---

spring/boot2-webflux-autoconfigure/build.gradle
spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java

Hi.
Currently can't use DocServiceConfigurator in boot2-webflux-autoconfigure, so I'd like to add it.

Add DocServiceConfigurator into boot2-webflux-autoconfigure

---

core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
core/src/test/java/com/linecorp/armeria/internal/common/TimeoutSchedulerTest.java

Motivation:
When a user clears a request timeout and wants to set a new timeout from the start of the request,
a TimeoutScheduler will schedule the timeout from now.
For example:
```java
ServiceRequestContext ctx = ...;
// Perform heavy works
...
// Passed 500ms from the start.
ctx.clearRequestTimeout();
// The timeout will be trigged in 1000ms from the now.
// '1000ms from the now' means 1500ms from the start of the request.
ctx.setRequestTimeoutMillis(TimeoutMode.SET_FROM_START, 1000);
```
Modifications:
- Fix bug in `setTimeoutNanosFromStart()` in `TimeoutScheduler`
Result:
- A request timeout will be scheduled from the start of the request correctly
after clearing the previous timeout.

Fix a bug where `TimeoutMode.SET_FROM_START` schedules a wrong timeout

---

grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/GrpcTrailersUtil.java
grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebRetryTest.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebTextTest.java
grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramerTest.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/FramedGrpcServiceTest.java

Motivation:
We hardcoded the content-type with `application/grpc+proto` when sending gRPC Trailers-Only.
It is no harm to set the value because there's no following messages.
But I think it's better to set the content-type of the corresponding gRPC request so that a user
doesn't get surprised.
Modifications:
- Set the content-type of the corresponding gRPC request to the gRPC Trailers-Only.
Result:
- gRPC Trailers-Only now has the content-type of the corresponding gRPC request.

Fix to set content-type correctly for gRPC Trailers-Only

---

core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerLoadBalancerInteropTest.java

**Motivation:**
When HTTP HEAD request is handled by Spring WebFlux's RouterFunction and 
RouterFunction returns ServerResponse without body, 
(like `route(HEAD("/monitor/l7check"), request -> ok().build())`)
CancelledSubscriptionException is exposed to application leaving error logs like below.
```
2020-08-03 22:41:31.310 DEBUG 69471 --- [-worker-nio-2-1] o.s.w.s.adapter.HttpWebHandlerAdapter    : [1fa05b2c8118e6cf] HTTP HEAD "/monitor/l7check"
2020-08-03 22:41:31.356 DEBUG 69471 --- [-worker-nio-2-1] o.s.w.r.f.s.s.RouterFunctionMapping      : [1fa05b2c8118e6cf] Mapped to org.springframework.web.reactive.function.server.RouterFunctionDsl$HEAD$1@2bd0af50
2020-08-03 22:41:31.393 ERROR 69471 --- [-worker-nio-2-1] o.s.w.s.adapter.HttpWebHandlerAdapter    : [1fa05b2c8118e6cf] Error …
```

Ignore CancelledSubscription when handling HTTP HEAD

---

site/src/pages/docs/advanced-spring-webflux-integration.mdx
site/src/pages/docs/client-retry.mdx

When i pasted example code at this page '[advanced-spring-webflux-integration](https://armeria.dev/docs/advanced-spring-webflux-integration)', I found that CircuitBreakerStrategy has been removed.
CircuitBreakerStrategy was changed on [0.99.6](https://armeria.dev/release-notes/0.99.6 ), but docs has invalid code yet.

Fix invalid docs for CircuitBreakerStrategy

---

spring/boot2-webflux-autoconfigure/build.gradle
spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryAutoConfiguration.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java

Hi.
If users customize WebFlux app's `management.server.port` setting as follows, the app can't start.
```yaml
management:
server:
port: 18080
```
Because if `management.server.port` is not equals to `server.port`, [DifferentManagementContextConfiguration](https://github.com/spring-projects/spring-boot/blob/v2.3.2.RELEASE/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/web/server/ManagementContextAutoConfiguration.java#L115-L116) will be enabled then `ArmeriaReactiveWebServerFactory#getWebServer(HttpHandler)` will be called twice.
The process flow is the following.
1st call of `ArmeriaReactiveWebServerFactory#getWebServer(HttpHandler)`:
- https://github.com/spring-projects/spring-framework/blob/v5.2.8.RELEASE/spring-contex …

WebFlux app can't start if management.server.port is customized

---

brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientPipeliningTest.java
core/src/test/java/com/linecorp/armeria/client/HttpClientTimeoutTest.java
core/src/test/java/com/linecorp/armeria/client/proxy/HAProxyClientIntegrationTest.java
core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
core/src/test/java/com/linecorp/armeria/server/ProxyProtocolEnabledServerTest.java
core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java
core/src/test/java/com/linecorp/armeria/server/logging/HttpServiceLogNameTest.java
grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
it/server/src/test/java/com/linecorp/armeria/server/http/ClientAuthIntegrationTest.java
retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunctionTest.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSslConfigurationTest.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortHttpsTest.java
testing-internal/src/main/java/com/linecorp/armeria/internal/testing/SimpleChannelHandler.java
testing-internal/src/main/java/com/linecorp/armeria/internal/testing/SimpleChannelHandlerFactory.java
thrift0.13/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
thrift0.13/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java

Motivation:
DynamicBehaviorHandler could cause unexpected leak problem base on the following scenario:
1. Tests related to socks are finished successfully.
2. The socks decoder tries to pass the remain `ByteBuf`s to a next handler.
3. A test that is not related to socks changes a handler logic via DYNAMIC_HANDLER.setXXX().
4. The data produced in 2) is passed to the handler made in 3).
5. The new handler produces ClassCastException when receiving unexpected messages.
```java
java.lang.ClassCastException:
class io.netty.buffer.AdvancedLeakAwareByteBuf cannot be cast to
class io.netty.handler.codec.http.HttpRequest (io.netty.buffer.AdvancedLeakAwareByteBuf and io.netty.handler.codec.http.HttpRequest are in unnamed module of loader 'app')
at …
```

Fix leaks in tests of DynamicBehaviorHandler and others

---

examples/context-propagation/dagger/build.gradle
examples/context-propagation/kotlin/build.gradle.kts
examples/context-propagation/manual/build.gradle
examples/context-propagation/rxjava/build.gradle

Without it, no outputs...
```
> Task :examples:context-propagation-dagger-example:run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
<============-> 95% EXECUTING [3m 23s]
> IDLE
> :examples:context-propagation-dagger-example:run
```

Add slf4j-simple to examples

---

dependencies.yml
reactor3/build.gradle
reactor3/src/main/java/com/linecorp/armeria/common/reactor3/RequestContextHooks.java
reactor3/src/main/java/com/linecorp/armeria/common/reactor3/package-info.java
reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareFluxTest.java
reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareMonoTest.java
settings.gradle

Motivation:
We have hooks for `RxJava` which automatically propagates `RequestContext`.
But we don't have one for Reactor.
Modifications:
- Add `RequestContextHooks.enable()` to enable propagating `RequestContext` automatically.
- Reactor 3.3.8.RELEASE -> 3.3.9.RELEASE
Result:
- You can now enable automatic `RequestContext` propagation during Reactor operations.
To-do:
- `ParallelFlux` is not supported at the moment. See https://github.com/reactor/reactor-core/issues/2328

Support `RequestContext` propagation during Reactor operations

---

dependencies.yml
examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/HelloServiceImpl.kt
examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/Main.kt
examples/grpc-kotlin/src/test/kotlin/example/armeria/grpc/kotlin/HelloServiceTest.kt
grpc/build.gradle
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaCoroutineContextInterceptor.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java

Motivation:
`CoroutineContextServerInterceptor` is newly introduced in gRPC-Kotlin [0.1.5](https://github.com/grpc/grpc-kotlin/releases/tag/v0.1.5).
Armeria gRPC server can inject the current `RequestContext` to Coroutine Context using it.
The issue that `inHalfClose` unexpectly calls `ServerCall.close()` seems resolved by https://github.com/grpc/grpc-kotlin/pull/157.
I cannot reproduce it anymore.
Modifications:
- Add `ArmeriaCoroutineContextInterceptor` that is working only for gRPC-Kotlin stub.
- Remove `inHalfClose` flag in ArmeriaServerCall
Results:
- You can now get the current `RequestContext` from the Coroutine Context of gRPC-Kotlin by default.

Upgrade gRPC-Kotlin to 0.1.5

---

core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
core/src/test/java/com/linecorp/armeria/common/stream/FixedStreamMessageTest.java

Motivation:
After a Subscription has been cancelled, `Subscription.request(n)` should be NOPs.
https://github.com/reactive-streams/reactive-streams-jvm#3.6
However `OneElementFixedStreamMessage` throws `AssertionError` by the following condition.
https://github.com/line/armeria/blob/744098d4ed83a65c6668fd863afebae14f5e2a1c/core/src/main/java/com/linecorp/armeria/common/stream/OneElementFixedStreamMessage.java#L69
Modifications:
- Ignore additional `Subscription.request(n)` signals
when the stream has been closed already in FixedStreamMessage.
Result:
- `OneElementFixedStreamMessage` does not throw `AssertionError` anymore
when receiving `Subscription.request(n)` signal.

Abide by Reactive Streams spec 3.6 in FixedStreamMessage

---

retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriber.java
retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilderTest.java

Motivation:
The `HttpRespone` used in retrofit is not closed when the return type of the interface is void
Modifications:
- Cancel the `HttpResponse` if the return type is void.
Result:
- Close #3006
- `HttpResponse`s used in retrofit are always completed.

Fix a bug where retrofit response is not completed

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/KotlinUtil.java
kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaCoroutineUtil.kt
kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaKotlinUtil.kt

Motivations:
Functions defined in `CoroutineUtil` and `KotlinUtil` are visible now.
Modifications:
- Make them `internal`. (`internal` methods of another module are not visible to Kotlin, but visible to Java)
- Add `Armeria` prefix to indicate that they are for armeria internal.

Add internal modifier to kotlin utility functions

---

core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
core/src/main/java/com/linecorp/armeria/common/auth/BasicToken.java
core/src/main/java/com/linecorp/armeria/common/auth/OAuth1aToken.java
core/src/main/java/com/linecorp/armeria/common/auth/OAuth2Token.java

Motivation:
Our header-value-returning methods are named inconsistently, sometimes
as `toHeaderValue()` and sometimes as `asHeaderValue()`
Modifications:
- Renamed `toHeaderValue()` to `asHeaderValue()`
Result:
- API consistency

Rename `toHeaderValue()` to `asHeaderValue()`

---

core/src/main/java/com/linecorp/armeria/common/RequestContext.java
core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java

Motivation:
We forgot to add `RequestContext.hasAttr()` and `hasOwnAttr()` in #2322
Modifications:
- Added `RequestContext.hasAttr()` and `hasOwnAttr()`.
Result:
- Easier to check if the context has an attribute value associated with
an attribute key.

Add `RequestContext.hasAttr()` and `hasOwnAttr()`

---

brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientTest.java
brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceTest.java

Motivation:
We'd better to use our default parser for `HttpTracing` which are `ArmeriaHttp(Client|Server)Parser`
rather than Brave's default parser.
Modification:
- Override (Client|Server)(Request|Response)Parser with `ArmeriaHttp(Client|Server)Parser`
if they are the default brave parsers in `Brave(Client|Service)`.
Result:
- `ArmeriaHttp(Client|Server)Parser` are used by default in `Brave(Client|Service)`.

Use `ArmeriaHttp(Client|Server)Parser` by default in Brave decorators

---

grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcServerInterceptorTest.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServerInterceptorTest.java

Motivation:
When a gRPC request is closed by `ServerInterceptor` while starting a call,
ArmeriaServerCall throws `NullPointerException`. For example
```java
@Override
public <ReqT, RespT> Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata metadata,
ServerCallHandler<ReqT, RespT> next) {
call.close(Status.PERMISSION_DENIED, metadata);
return NOOP_LISTENER;
}
```
This is caused by `listener` which is null at the moment. The `listener` is not initialized when `call.close()` is called in the interceptor.
https://github.com/line/armeria/blob/8a1281f1d2b827f516247b8f9eb6210f2a047efa/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L492-L495
The `listener` will be set by the returned value of `startCall(call, metadata)`. …

Fix a bug where gRPC server throws NPE when a call is closed by ServerInterceptor

---

spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java
spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java

Motivation:
Armeria Spring Integration always uses `MeterIdPrefixFunction.ofDefault` when `enable-metrics` is set to true.
It'd be good if users can configure the `MeterIdPrefixFunction` Armeria uses.
and https://github.com/line/armeria/issues/2762#issuecomment-681819264
Modifications:
- Add an argument `Optional<MeterIdPrefixFunction>` to `ArmeriaAutoConfiguration.armeriaServer`
- Add an argument `MeterIdPrefixFunction` to `ArmeriaConfigurationUtil.configureServerWithArmeriaSettings`
Result:
The `MeterIdPrefixFunction` bean which users register will be used.
If the bean is not present, `MeterIdPrefixFunction.ofDefault` will be used.

Use MeterIdPrefixFunction bean when integrated with Spring Boot

---

core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClientBuilder.java
core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java

#3029 
Add `loggerName(String)` to `LoggingDecoratorBuilder`.
Users can configure `LoggingDecoratorBuilder`'s `logger` only using name.
Prevent passing null to `LoggingDecoratorBuilder.logger()` because of compile failure (have to case null as `Logger` of `String`).

Allow to set logger of `LoggingDecoratorBuilder` using name

---

core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java
core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java

Motivation:
It's not easy to recognize what is the problem if an exception is raised while making request and response log strings
because there's no log for the exception and of course, request and response logs are not left as well.
Modification:
- Log the exception that is raised while making request and response log strings.
Result:
- You can now get the log of the exception which is raised while making request and response logs.

Log the exception while making request and response log strings.

---

eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
site/src/pages/docs/client-service-discovery.mdx
site/src/pages/docs/server-service-registration.mdx
site/src/pages/docs/setup.mdx
site/src/pages/docs/toc.json

Motivation:
I didn't add the documentation about Eureka.
Modifications:
- Add server-service-registration
- Remove advanced-zookeeper and move the contents to server-service-registration and client-service-discovery

Add Eureka service discovery documentation

---

spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/PrometheusMetricExposureTest.java
spring/boot2-actuator-autoconfigure/src/test/resources/application-managedMetricPath.yml
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java

Motivation:
Currently, `MetricCollectingService` is not registered as a decorator when `metricsPath` is set to empty.
https://github.com/line/armeria/blob/e872d75a03de3bc384b7416d16c82dfd73187ccb/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java#L109
From the original specification, this is not expected behavior.
https://github.com/line/armeria/blob/fbe90f0f2a952578012a552c26b3f4f8bdb33c8c/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java#L279-L285
Users might want to hide the metric path from the public port and expose it only via the management port of the Spring Actuator.
Modification:
- Bind a `MetricCollectingService` decorator when `eanbleMetrics` is true.
Result:
- Armeria Spring …

Fix a bug where metrics are not collected when `metricsPath` is set to empty in Spring Boot

---

core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java

Motivation:
`HttpResponseException` and `HttpStatusException` are raised by user code so we do not have to log the stack trace.
Modification:
- Do not log the stacktrace of `HttpStatusException` and `HttpResponseException` in `LoggingService`.
Result:
- Close #3053
- You no longer see the stacktrace of `HttpStatusException` and `HttpResponseException` in logging.

Do not log stack trace of Http(Status|Response)Exception

---

spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpRequest.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaWebClientWithRetryingClientTest.java

Motivation:
Currently, we propagate the exception from the `HttpRequest` to WebFlux `WebClient`.
However, this causes some unexpected behavior such as propagating `CancelledSubscriptionException`
instead `FailFastException` when `RetyringClient` is used.
We should rather propagate the exception of `HttpResponse`.
Modification:
- Progate the exception from `HttpResponse` not from `HttpRequest`.
Result:
- You now see the proper exception from WebFlux `WebClient`.

Fix a bug where wrong exception is propagated to WebFlux `WebClient`

---

reactor3/src/main/java/com/linecorp/armeria/common/reactor3/RequestContextHooks.java
reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareFluxTest.java
reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareMonoTest.java

Motivation:
Reactor subscriber context is not propagated properly.
Modifications:
- Delegate `currentContext()` call to the original `Subscriber` in `ContextAwareCoreSubscriber`
Result:
- Reactor subscriber context is now propagated.

Fix a bug where reactor subscriber context is not propagated

---

site/src/pages/docs/server-grpc.mdx

We haven't supported grpc-web-text so we recommended using unofficial gRPC web client
, which supports grpc-web-json, to communicate with the Armeria server.
Now, because we support both grpc-web-text and grpc-web-json, we don't have to recommend the unofficial client.

Fix documentation which recommends to use unofficial gRPC web client

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
core/src/test/java/com/linecorp/armeria/internal/common/TimeoutSchedulerTest.java
grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunctionTest.java

Motivation:
A `TimeoutScheduler` could be intialized various points such as:
- HttpResponseSubscriber.operationComplete()
- Http1ResposneDecoder.channelRead() with `NEED_HEADERS` status
We need a guard to make sure that a TimeoutScheduler is initialized once.
Modifications:
- Check `state` before initializing TimeoutScheduler.
Result:
A TimeoutScheduler is initialized exactly once even if it is called multiple times

Fix bug where TimeoutScheduler is intialized more than once

---

core/src/main/java/com/linecorp/armeria/common/util/Version.java
site/src/pages/docs/client-retry.mdx

I encountered two strange things while upgrading from 0.97.0 to 1.0.0.
Not confident about `partial()` though.

Fix stale documents due to changed APIs

---

core/src/test/java/com/linecorp/armeria/common/FlagsTest.java

On Windows, the `FlagsTest.dumpOpenSslInfoDoNotThrowStackOverFlowError()` test will fail because it cannot find `Flags.class` in the classpath (`url` will be `null`). This PR replaces `File.separatorChar` with `'/'` so the class(es) can be found successfully.
I'm not sure why this was fine on CI. Maybe it's a problem on my PC?

Fix failing FlagsTest on Windows

---

docs-client/src/components/GotoSelect/index.tsx
docs-client/src/components/VariableList/index.tsx

When using the `Go to` dropdown menu, the selected method is still shown after the dropdown menu is reopened. I think if we hide the currently selected method, it's more obvious you can search again as the text cursor is clearly visible.
- Hide the input box while the dropdown is open.
- Fix an ESLint warning about defining an unnamed function.

Hide input in 'Go to' menu while dropdown is open

---

core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
docs-client/webpack.config.ts

Webpack produces an `index.html` file for `docs-client` that includes `main.js` without any hash, which can cause browser cache issues. During my upgrade to Armeria 1.0.0, clicking on a method produced a blank page since the browser would load the cached JS bundle and cause a runtime error.
- Append a hash to the included JS bundle in `index.html`.
- Add `Cache-Control` header to statically served files.
- `index.html` now references `main.js?<hash>`, which forces the browser to fetch the new file between releases.

Append a hash to the JS bundle in docs-client to avoid caching issues

---

eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
site/src/pages/docs/server-service-registration.mdx
zookeeper3/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListenerBuilder.java

When I see `armeria-eureka`, I found that `ServerBuilder` doesn't have `addListener`.
I revise them 😄

Fix incorrect method name in service discovery examples

---

site/src/pages/docs/setup.mdx

Fix a typo in the document [Setting up a project](https://armeria.dev/docs/setup/)

Fix typo in document, paramters -> parameters 

---

spring/boot1-autoconfigure/build.gradle
spring/boot2-actuator-autoconfigure/build.gradle
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaBeanPostProcessor.java
spring/boot2-webflux-autoconfigure/build.gradle

Fix typo (`boot-autoconfigure` -> `boot2-autoconfigure`)

Fix typo (`boot-autoconfigure` -> `boot2-autoconfigure`)

---

core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
core/src/test/java/com/linecorp/armeria/client/HttpClientRequestPathTest.java

Motivation:
When a request is sent with absolute URI that does not contrains path,
```java
var client = WebClient.of();
client.get("https://google.com").aggregate();
```
then the request is failed with:
```
Caused by: com.linecorp.armeria.common.stream.ClosedStreamException: received a RST_STREAM frame: PROTOCOL_ERROR
```
The request is rejected by remote peers because it has an empty `:path` pseudo-header.
From the [HTTP/2 spec](https://tools.ietf.org/html/rfc7540#section-8.1.2.3),
> This pseudo-header field MUST NOT be empty for "http" or "https"
URIs; "http" or "https" URIs that do not contain a path component
MUST include a value of '/'.
Modifications:
- Set path to `/` if it is empty
Results:
Armeria client sets the default path(`/`) properly if it is empty.

Fix a bug where a request is sent with an empty `:path` pseudo-header.

---

examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/HelloServiceImpl.java
examples/grpc-reactor/src/main/proto/hello.proto
examples/grpc-reactor/src/test/java/example/armeria/grpc/reactor/HelloServiceTest.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java

Motivation:
Reactive gRPC starts to subscribe to upstream messages when `onReady` signal is delivered.
https://github.com/salesforce/reactive-grpc/blob/ce3b3b20e8192c5e6b38b2ed596531242d9708c0/common/reactive-grpc-common/src/main/java/com/salesforce/reactivegrpc/common/AbstractSubscriberAndProducer.java#L91-L97
Upstream gRPC-Java server invokes the signal - `onReady` when an HTTP headers is received.
https://github.com/grpc/grpc-java/blob/9b73e2365da502a466b01544f102cd487e374428/core/src/main/java/io/grpc/internal/AbstractStream.java#L280-L287
However, `ArmeriaServerCall` invokes `listener.onReady()` only when a response is written completely.
https://github.com/line/armeria/blob/2bc23e60cea9f6adc1415c8d08a34baf2b90ce80/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall. …

Fix a bug where reactive-grpc fails to send stream responses

---

logback/src/main/java/com/linecorp/armeria/common/logback/UnionMap.java
logback/src/test/java/com/linecorp/armeria/common/logback/UnionMapTest.java

Current UnionMap#entrySet doesn't return the same size like UnionMap#size.
Fix https://github.com/line/armeria/issues/3044
--
Found an issue can be fixed and @anuraaga already has the correct code, so copy from there.

Make UnionMap#entrySet won't return multiple values for same key

---

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
eureka/src/main/java/com/linecorp/armeria/server/eureka/InstanceInfoBuilder.java
eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java

Motivation:
We almost always use milliseconds as the default unit for representing a
duration or interval.  `EurekaEndpointGroupBuilder.registryFetchIntervalSeconds()`
is the only exception we have.
Modifications:
- Add `EurekaEndpointGroupBuilder.registryFetchIntervalMillis()` which
deprecates `registryFetchIntervalSeconds()`
- Improved validation for `registryFetchInterval(Duration)`
- `HealthCheckedEndpointGroupBuilder` now overrides `retryIntervalMillis()`.
Result:
- Consistency
- (Deprecation) `EurekaEndpointGroupBuilder.registryFetchIntervalSeconds()`
has been deprecated in favor of `registryFetchIntervalMillis()`.

Use milliseconds as an interval unit in `EurekaEndpointGroup`

---

core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
core/src/main/java/com/linecorp/armeria/client/logging/ContentPreviewingClient.java
core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java
core/src/test/java/com/linecorp/armeria/client/HttpResponseDecoderTest.java

Motivation:
We currently, abort the request when the client receives the response.
However, if the request is not complete, the AbortedStreamException is propagated to the response
even though the client received the response normally.
Modifications:
- Complete response before aborting request in `HttpResonseDecoder`
- Change to use the attribute to apply `ContentPreviewing(Client|Service)` only once.
Result:
- You can now get the normal response even when the request is not fully sent.

Complete response before aborting request

---

spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/HealthCheckServiceConfigurator.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
spring/boot2-webflux-autoconfigure/build.gradle
spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java

- #3130
- Spring Boot users can only set path of the `HealthCheckService`. They can't set `response`, `updatable` or others.
- Allow users to configure the `HealthCheckService` by registering `HealthCheckServiceConfigurator` beans:
```java
@Bean
public HealthCheckServiceConfigurator healthCheckServiceConfigurator() {
return builder -> builder.updatable(true);
}
```
- Of course `HealthCheckService` is enabled only if `ArmeriaSettings#healthCheckPath` is not null or empty.
- Close #3130

Allow user to configure `HealthCheckService` in Spring integration

---

dependencies.yml

Motivation:
`jmh-gradle-plugin` has been upgraded to 0.5.1 and 0.5.2 from 0.5.0
with releasing Armeria 1.1.0 and 1.2.0.
However the newer versions of `jmh-gradle-plugin` are not working on the lastest JMH core from 1.24 to 1.26.
I saw the following error message when running JMH with Gradle.
```
Caused by: org.gradle.api.GradleException: Error while instantiating tests: unable to set 'list' on Runner. This plugin version doesn't seem to be compatible with JMH 1.26. Please report to the plugin authors at https://github.com/melix/jmh-gradle-plugin/.
at me.champeau.gradle.IsolatedRunner.tryUpdateFieldViaReflection(IsolatedRunner.java:98)
at me.champeau.gradle.IsolatedRunner.updateBenchmarkList(IsolatedRunner.java:76)
at me.champeau.gradle.IsolatedRunner.run(IsolatedRunner.java:56)
at …
```

Downgrade jmh-gradle-plugin to 0.5.0

---

site/src/pages/docs/advanced-dropwizard-integration.mdx

The previous way this was written rendered quite strangely (https://armeria.dev/docs/advanced-dropwizard-integration/). This is an attempt to make it better.

advanced-dropwizard-integration: Fix formatting errors

---

core/src/main/java/com/linecorp/armeria/common/logging/ExportGroup.java
core/src/main/java/com/linecorp/armeria/common/logging/ExportGroupBuilder.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilder.java
core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
logback/src/main/java/com/linecorp/armeria/common/logback/ExportGroupConfig.java
logback/src/main/java/com/linecorp/armeria/common/logback/ExportGroupConfiguration.java
logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
logback/src/test/java/com/linecorp/armeria/common/logback/CustomObject.java
logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
logback/src/test/resources/com/linecorp/armeria/common/logback/testXmlConfig.xml
site/src/pages/docs/advanced-logging.mdx

Motivations:
https://github.com/line/armeria/issues/3086
Currently, to add a prefix, users have to write many and redundant key patterns like this.
```xml
<exports>
armeria.remote.host=remote.host,
armeria.remote.ip=remote.ip,
armeria.remote.port=remote.port,
armeria.req.content_length=req.content_length,
armeria.req.direction=req.direction,
armeria.req.service_name=req.service_name,
armeria.req.name=req.name,
armeria.req.path=req.path,
...
</exports>
```
Modifications:
- Add `ExportGroup` and `ExportGroupBuilder`
- Logback configuration can be seen as a set of `ExportGroup`
- Move the logic for `setExport(s)` to `ExportGroupBuilder`
Results:
You can specify a prefix for MDC keys using the `<prefix>` element.
```xml
<prefix>...</prefix> 
<export>...</export>
<exports>...</exports> …
```

Support prefix option for Logback integration

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtilTest.java

This changeset adds the ability to convert String parameters
(those marked with `@Query`, `@Header` and `@Param`) to be converted
to any arbitrary object type, provided that the class has at least
one of the following methods (discovered in order):
- `public static T of(String)`
- `public static T valueOf(String)`
- `public static T fromString(String)`
- `public T(String)`
If a method exists but throws an exception on conversion, the next will
NOT be tried.
Closes #2574

Add arbitrary param parsers

---

docs-client/src/components/GotoSelect/index.tsx
docs-client/src/containers/MethodPage/DebugPage.tsx

- Issue #3129 reported by @adriancole 
- `docs-client` JavaScript bundle size is quite large. After analyzing it, I realized we include syntax highlighting rules for _all_ languages supported by `highlight.js`
- Only import and register JSON syntax highlighting in `react-syntax-highlighter`
- Remove unnecessary `@ts-ignore` annotations
- Reduced JS bundle size from 1430 kB to 650 kB
Before | After
:------:|:-----:

Reduce docs-client JS bundle size

---

core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java
core/src/test/java/com/linecorp/armeria/client/HttpClientContextCaptorTest.java
core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java

Armeria client rejects the URL containing colon in the first segment like `https://example.com/foo:bar`.
Since `PathAndQuery.parse()` rejects the path which contains colon in first segment.
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java#L375
However, RFC says it's only for relative-path reference.
https://tools.ietf.org/html/rfc3986#section-3.3
> In addition, a URI reference (Section 4.1) may be a relative-path reference, 
> in which case the first path segment cannot contain a colon (":") character.
Then, Armeria should accept the URL containing colon in the first segment.
I removed colon check method from `PathAndQuery`, because it only accepts absolute path.

Allow colon character in first segment of absolute path

---

docs-client/package-lock.json
docs-client/package.json
docs-client/src/containers/MethodPage/DebugPage.tsx
docs-client/src/containers/MethodPage/EndpointPath.tsx
docs-client/src/containers/MethodPage/HttpHeaders.tsx
docs-client/src/containers/MethodPage/HttpQueryString.tsx
docs-client/src/containers/MethodPage/index.tsx
docs-client/src/containers/MethodPage/style-dropdown.css
docs-client/src/lib/types.ts
licenses/web-licenses.txt

- In effort to reduce the JS bundle size, we can use Material-UI components instead of extra dependencies
- Replace `react-select` with Material-UI's `Select` component
- Use `value=""` to keep controlled component "uninitialized" so the user can repeat the last selection
- Before this change, the user had to select another option, which is impossible if there's only one item
- Unify DocService appearance and slightly improve UX
- Remove a dependency and reduce `docs-client` bundle size by 10 kB

Replace react-dropdown with Material-UI's Select

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTimeoutTest.java

Motivation:
When a stream is closed by a remote peer, `ArmeriaServerCall` is closed by `res.whenComplete()` listener.
https://github.com/line/armeria/blob/6e24e7817f8be94ab21ddba7879e9f84ca840229/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L173-L182
If a service performs a long running task, `ArmeriaServerCall.sendHeaders()` or
`ArmeriaServerCall.sendMessage()` will be called when a response is written.
Because gRPC-Java `ServerCallStreamObserver` implementation invokes `ServerCall` even if a call is cancelled with some conditions.
https://github.com/grpc/grpc-java/blob/d52b359631ee1ac46f47d72d1015e1dd6ce9312c/stub/src/main/java/io/grpc/stub/ServerCalls.java#L346-L358
Modifications:
- Check `cancelled` flag before validating the closing states.
Result:
- …

Fix a bug where a gRPC ServerCall is invoked after a stream is closed

---

core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java

Motivation:
- Issue: #2970 Use Caffeine in `RefresingAddressResolver`
- Currently, `RefresingAddressResolver` will expire if the DNS caches is not hit. Let's keep the cache entry even if it was not hit. But it means can be increased indefinitely the size of map.
- By using Caffeine in `RefresingAddressResolver` as cache implementation, we may limit the usage even if the DNS cache entry is not expired ever.
Modifications:
- Change the life cycle of the DNS cache entry so that it does not expire.
- Use Caffeine for limiting the usage of DNS caches.
Results:
- Fixes #2970

Use Caffeine in `RefresingAddressResolver`

---

core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/server/file/FileServiceBuilder.java

Motivation:
The descriptions of `*cacheSpec` and `defaultBackoffSpec` flags do not
explain what they do exactly in their first sentence.
Modifications:
- Update the Javadoc of the methods that returns or accepts a Caffeine
specification string or backoff specification string so that it's more
user-friendly.
Result:
- Hopefully easier to understand that these flags do actually.

Clean up cacheSpec and backoffSpec documentation

---

core/src/main/java/com/linecorp/armeria/client/Endpoint.java
core/src/test/java/com/linecorp/armeria/client/EndpointTest.java

Motivation:
`Endpoint.withIpAddr()` accepts an IPv6 address with a scope ID
specified. However, Armeria's networking layer does not accept an IPv6
address with a scope ID.
Modifications:
- Strip the scope ID from the specified IPv6 address in
`Endpoint.withIpAddr()`.
- Added more test cases for `withIpAddr()`
Result:
- Fixes #3158

Strip the IPv6 scope ID in `Endpoint.withIpAddr()`

---

core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/KeyedRetryConfigMapping.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryConfig.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryConfigBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryConfigMapping.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClientBuilder.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/KeyedRetryConfigMappingTest.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
grpc/src/test/java/com/linecorp/armeria/internal/client/grpc/GrpcClientUnwrapTest.java
thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java

This PR adds the ability to map retry config (total attempts, response timeout) to elements from the context and/or request.
This effectively means that the user can vary retry config by host, method, path, and/or any other element from the context/request.
Feature request issue: https://github.com/line/armeria/issues/3128

Mapping retry config by context/request parameters

---

core/src/main/java/com/linecorp/armeria/client/endpoint/CompositeEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/LazyList.java
core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java
core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
core/src/test/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroupTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckEndpointGroupFlakyTest.java
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckEndpointGroupRaceTest.java

Motivation:
When `EndpointGroup.orElse(...)` is used and the endpoint group is wrapped by `HealthCheckedEndpointGroup`,
there's a chance that endpoints are not set forever in this situation:
1. `OrELseEndpointGroup.whenReady()` is completed with the second endpoint group.
2. The first `EndpointGroup.setEndpoints(...)` are called.
3. `HealthCheckedEndpointGroup` is created.
In this case, the health check requests are sent to the second endpoint group to filter unhealthy endpoints.
However, because `OrELseEndpointGroup.endpoints()` returns the endpoint group in the first `EndpointGroup`, there's always no matching.
Modifications:
- Delay to set the `List<EndpointGroup>` for the `whenReady()` future.
- It's set when the list is first accessed.
- Use `delegate.endpoint()` instead of …

Fix a bug where HealthCheckedEndpointGroup.endpoints() is not set

---

core/src/test/java/com/linecorp/armeria/common/DefaultSplitHttpResponseTest.java

Motivation:
A CompletableFuture returned by `SplitHttpResponse.headers()` can be completed with
normal HTTP headers even if downstream cancels its subscription before requesting the first item.
Because SplitHttpResponse tries to prefetch HTTP headers when `HttpResponse.split()` is called.
Modifications:
- Check HTTP headers before a cancel signal is triggered.
Result:
- Remove a flaky test in DefaultSplitHttpResponseTest
- Fixes #3186

Fix flaky test: DefaultSplitHttpResponseTest.cancelResponse

---

core/build.gradle
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/ScalaUtil.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
dependencies.yml
examples/grpc-scala/build.gradle
examples/grpc-scala/src/main/resources/META-INF/services/com.linecorp.armeria.server.docs.DocServicePlugin
examples/grpc-scala/src/main/scala/example/armeria/grpc/scala/Main.scala
examples/grpc-scala/src/test/scala/example/armeria/grpc/scala/HelloServiceTest.scala
gradle.properties
scalapb/scalapb_2.12/build.gradle
scalapb/scalapb_2.13/build.gradle
scalapb/scalapb_2.13/src/main/resources/META-INF/services/com.linecorp.armeria.server.docs.DocServicePlugin
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/common/scalapb/ScalaPbJsonMarshaller.scala
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbConverterUtil.scala
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbGrpcDocServicePlugin.scala
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunction.scala
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunctionProvider.scala
scalapb/scalapb_2.13/src/test/proto/hello.proto
scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/HelloServiceImpl.scala
scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/HelloServiceTest.scala
scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunctionTest.scala
scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseAnnotatedServiceTest.scala
site/src/pages/docs/setup.mdx

Motivation:
Scala standard libary provides [Future](https://www.scala-lang.org/api/2.12.3/scala/concurrent/Future.html) that is similar to `CompletableFuture`.
By supporting Scala Future, ScalaPB users can return a Scala Future that completes a `GeneratedMesage`
without explicitly converting it to `CompletableFuture`.
Modifications:
- Add `scala-library` as a `optionalImplementation` to core module
- Add `ScalaUtil` for supporting Scala types
- Make `ExecutionContext`, which wraps `eventLoop`, a default injectable type for annotated service
- Users can easily execute async task on top of Armeria's event loop
```scala
@Get("/items/{id}")
def items(@Param id: Int)(implicit ec: ExecutionContext): Future[String] = {
Future {
// Perform asynchronous task using Armeria's event loop
...
}
}
``` …

Support Scala Future for annotated services

---

docs-client/src/containers/MethodPage/DebugPage.tsx

- The copy/clear response buttons and tooltips on DocService seem misaligned
- Wrap buttons in `<Grid container>` and `<Grid item>` to position them in the same row
Before | After
:------:|:-----:
- Buttons are in the same line and tooltips align with them

Fix positioning of copy/clear response buttons in DocService

---

site/src/pages/docs/server-grpc.mdx

**Motivation**
Currently, it seems like grpc-web now supports server-side streaming request (I've verified by calling an armeria server from my browser w/ the `@improbable-eng` lib and works great 👍 )
I'd just like to update the docs since this statement scared me a little when I started out researching.
Ref: https://grpc.io/blog/state-of-grpc-web/#feature-sets

Update docs to reflect current grpc-web support

---

core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java
core/src/main/java/com/linecorp/armeria/server/Routers.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestLogNameTest.java
core/src/test/java/com/linecorp/armeria/server/RouteDecoratingTest.java
core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java

Motivation:
Related #3160 
Modifications:
- In the case of route decorator router, modified to be created as `SequentialRouter`
- Modified to insert the route decorator forward when adding
- Modified order to `configureServerWithArmeriaSettings`
- Modified test
- `AnnotatedServiceRequestLogNameTest`
- `ContentPreviewingServiceTest`
- `RouteDecoratingTest`
- Modified javadoc of `RouteDecoratingService`
Result:
- Correct route decorator evaluation order
- Fixed #3160

Fix route decorator evaluation order

---

jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerTest.java
testing-internal/src/main/webapp/index.jsp
tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java

Motivation:
`ServletRequest.getProtocol()` currently returns `null` or always
`HTTP/1.1` regardless of actual session protocol when using
`TomcatService` or `JettyService`.
Modifications:
- Make `TomcatService` and `JettyService` set the protocol value
properly.
- Update `WebAppContainerTest` so it makes sure
`ServiceRequest.getProtocol()` returns a correct value.
Result:
- Fixes an interoperability issue with Servlet code that relies on
`ServletRequest.getProtocol()`.

Make ServletRequest.getProtocol() return a correct value

---

core/src/main/java/com/linecorp/armeria/common/stream/ByteBufDeframerInput.java
core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframer.java
core/src/test/java/com/linecorp/armeria/common/stream/ByteBufDeframerInputTest.java

Motivation:
When a `ByteBuf` is added to `ByteBufDeframerInput` after it is closed,
the `ByteBuf` is not properly released.
Modifications:
- Release a added `ByteBuf` if `ByteBufDeframerInput` is closed.
Result:
- No more leak.

Fix a leak in `ByteBufDeframerInput`

---

core/src/main/java/com/linecorp/armeria/client/DefaultDnsQueryLifecycleObserver.java
core/src/main/java/com/linecorp/armeria/common/stream/ByteBufDeframerInput.java
core/src/main/java/com/linecorp/armeria/common/stream/DefaultHttpDeframer.java
core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframer.java
core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframerHandler.java
core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframerInput.java
core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframerOutput.java
core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java
core/src/test/java/com/linecorp/armeria/common/stream/HttpDeframerTest.java
grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/HttpDeframerUtil.java
grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerHandler.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerHandlerTest.java
grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpDeframerTckTest.java
grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerTest.java

- Split `HttpDeframer` into an interface and an implementation.
- We can save some extra object allocation.
- We can hide the implementation detail, like extending
`DefaultStreamMessage`.
- Added `@UnstableApi` wherever applicable.
- Fixed a bug where `HttpDeframer` sometimes increases the upstream
demand to a value greater than 1.
- Removed redundant code from the gRPC code base.
- Fix a bug where `DefaultDnsQueryLifecycleObserver` does not strip
the scope ID from an IP address.
- Fix flakiness in `DnsMetricTest`.

Clean up `HttpDeframer` and gRPC

---

.appveyor.build.sh
docs-client/.npmrc
docs-client/build.gradle
site/.npmrc
site/build.gradle

Motivation:
We're having frequent build failures due to connectivity issues with
registry.npmjs.org or raw.githubusercontent.com.
- node-gradle-plugin caches the downloaded nodejs/npm binary under a
project directory, but our CI script caches only a home directory.
- `npm ci` command always checks whether its cache is up-to-date.
The build will fail if it fails to contact registry.npmjs.org,
even if we have cached data.
- `pngquant-bin` never caches when it downloads a pre-built `pngquant`
binary file. If download fails, the build fails and there's no way
to cache this at the moment.
- When a user runs `./gradlew lint` it triggers `:site:npmInstall`,
even if the user is not interested in building the site. This increases
the chance of build failure because it triggers the installation of …

Cache frontend packages

---

core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeaders.java
core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilder.java
core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
core/src/main/java/com/linecorp/armeria/common/RequestHeaderGetters.java
core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java
core/src/test/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilderTest.java

Motivation:
Accept-Language is a client supplied header detailing what locales the
client user prefers and the weight of the preference. It's
mostly useful to detect the default language of the site.
Modifications:
Added method `acceptLanguages()` and `selectLocale(supportedLocales)` to
`RequestHeaderGetters`. `acceptLanguages()` is lazy and cached.
Added `acceptLanguages(acceptedLanguages)` to `RequestHeadersBuilder`.
Closes #3179

Add Accept-Language parsing and prioritizing

---

core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/KeyedRetryConfigMapping.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryConfig.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryConfigBuilder.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryConfigMapping.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java

Motivation:
There are some missing Javadoc in a `RetryingClient` and related classes.
Modifications:
- Replace `@code` with `@link` if applicable.
- Clean up indentation
- Check null on a returned value of a function.
Result:
Keep code consistency

Clean up `RetryingClient`

---

core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java

Motivation:
A publisher of `DefaultStreamMessage` does not send `onComplete` signal,
if the current demand is 0 and `whenConsumed()` is registered.
https://github.com/line/armeria/blob/bd09b15ff507ba9872937a9762c05ade4ebbe76c/core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java#L422-L425
The publisher will send an `onComplete` signal when the next request is received.
This could be a problem when a Subscriber requests only one element and expects an `onComplete` signal.
Modifications:
- Complete `whenConsumed()` when `DefaultStreamMessage` regardless of the count of `demand`
Result:
-  `DefaultStreamMessage.whenConsumed()` is always completed if a queue is empty.

Make `DefaultStreamMessage.whenConsumed()` completed even when `demand` is 0

---

zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java

Motivation:
Occasionally ZooKeeperRegistrationTest failed because of a duplicate port number.
```java
ZooKeeperRegistrationTest > curatorRegistrationSpec() FAILED
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in com.linecorp.armeria.common.zookeeper.ZooKeeperTestUtil that uses com.linecorp.armeria.server.Server
Expecting code not to raise a throwable but caught
<"java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```
Modifications:
- Allocate a new port if a server fails to start
Result:
- Clean up flaky tests

Fix flaky test in `ZooKeeperRegistrationTest.curatorRegistrationSpec()`

---

core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
core/src/test/java/com/linecorp/armeria/common/stream/AbortableSubscriberBlackboxTckTest.java

Motivation:
If a upstream publishes a null, `AbortableSubscriber` in `PublisherBasedStreamMessage` should raise NullPointerException.
https://github.com/reactive-streams/reactive-streams-jvm#2.13
Modifications:
- Throws NPE if a parameter of `onNext()`, `onSubscriber()` and `onError()` is null
- Add Subscriber TCK for `AbortableSubscriber`
Result:
- `AbortableSubscriber` now raises `NullPointerException` correctly when receiving a null value.
- Fixes #3212

Abide by Reactive Streams specification 2.13

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/common/RequestContextWrapperTest.java

Lately I've been working a lot on safety of context propagation due to some production issues. I'm thinking of porting https://github.com/open-telemetry/opentelemetry-java/blob/master/api/context/src/main/java/io/opentelemetry/context/StrictContextStorage.java to Armeria. First thing I found was that `RequestContextWrapper` seems to have drifted making it harder to extend that class.

Implement more methods in RequestContextWrapper.

---

core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceDestroyedConnectorTest.java

Motivation:
NPE is raised in `TomcatService` when the server is shutdown.
Modification:
- Respond with 503 if the `Connector` is in the stopped state in `TomcatService`.
Result:
- You no longer see NPE in `TomcatService` when stopping the server.
- Close #3136

Fix NPE in `TomcatService` when the server is shutdown.

---

tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceDestroyedConnectorTest.java

I forgot to set the base dir of Tomcat in the test in #3218.
Without the base dir, the test generates files to the wrong directory.

Set base dir for tomcat in test

---

eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/DataCenterInfoSerializer.java
eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/InstanceInfo.java

The server side DataCenterInfo default implement would not allow "metadata" field. 
Maybe it is better to make "DataCenterInfo" as a public interface and allow user to provide  other implements.
Test with spring cloud eureka server.

Fix eureka instanceinfo searilization

---

core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
core/src/main/java/com/linecorp/armeria/internal/common/AbstractHttp2ConnectionHandler.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java
core/src/test/java/com/linecorp/armeria/internal/common/AbstractHttp2ConnectionHandlerTest.java

Motivation:
If a client sends data after a GOAWAY frame is sent by a remote peer,
Netty disgards the received data and raises `Http2Exception: Stream x does not exist`.
It is an expected behavior and does not leave a warn message to nofity users.
Modifications:
- Add  `Http2Exception: Stream x does not exist` to expected exceptions
Result:
- You no longer see `Http2Exception: Stream x does not exist` error message anymore.
- Fixes #3208

Add `Http2Exception: Stream x does not exist` as an expected exception

---

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java

…tGroup`
Motivation:
Should reflect the change of endpoints in `HealthCheckedEndpointGroup` even when the weight of an endpoint is changed.
This also fixes another bug which health check multiple times for duplicate endpoints. Related #3230
Modification:
- Refresh endpoints in `HealthCheckedEndpointGroup` when the weight of an endpoint is changed.
- Fix a bug where multiple health check is executed for the same endpoints.
Result:
- The endpoints of `HealthCheckedEndpointGroup` are updated when the weight of an endpoint is changed.
- Do not execute duplicate health checks anymore for the same endpoint.

Refresh endpoints when the weight is changed in `HealthCheckedEndpointGroup`

---

core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java

Motivation:
Add useful API to `MeterIdPrefixFunction`. See #3241.
Modifications:
- Add `withTags(Tag... tags)` method in `MeterIdPrefixFunction`
- Add corresponding test case
Result:
- You can now use `withTags(Tag... tags)` method.
- Fixes #3241.

Add `MeterIdPrefixFunction.withTags(Tag...)`

---

core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaServerGracefulShutdownLifecycle.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerGracefulShutdownLifecycle.java

Checked the document https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/reference/htmlsingle/#boot-features-graceful-shutdown, the graceful shutdown also use SmartLifeCycle, so if we make `Server` utilize it, we can start Armeria's graceful shutdown before the tomcat or at the same time(depends on the springboot's graceful setting). So there is no 503 when we have a request to tomcat during Armeria's graceful shutdown.
There is one implementation detail that our phase is `Integer.MAX_VALUE`. And spring provides 2 types of web lifecycle. `WebServerStartStopLifecycle` & `WebServerGracefulShutdownLifecycle`. 
* `WebServerStartStopLifecycle`'s phase is `Integer.MAX_VALUE-1`, so it will wait for Armria shutdown complete.
* Unfortunately, the phase of `WebServerGracefulShutdownLifecycle` is …

Make Armeria server can shutdown before unmanaged tomcat in springboot.

---

core/build.gradle
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java
core/src/main/java/com/linecorp/armeria/common/util/TransportType.java
core/src/main/java/com/linecorp/armeria/internal/common/util/ChannelUtil.java
core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/test/java/com/linecorp/armeria/common/FlagsTest.java
core/src/test/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolverTest.java
core/src/test/java/com/linecorp/armeria/internal/common/util/ChannelUtilTest.java

Motivations:
Some users prefer reducing their distribution size or solving build
issues by excluding certain transitive dependencies. We could make
Armeria run even if `netty-transport-native-epoll` and
`netty-incubator-transport-native-io_uring` are missing in the class
path.
Modifications:
- Moved the logic that refers to epoll/io_uring classes to
`TransportTypeProvider` and used dynamic class loading.
- Moved the references to `EpollChannelOption.EPOLL_MODE` to
`ChannelUtil` and used dynamic class loading.
- Added the methods which were previously missing in `TransportType`:
- `socketChannelType()`
- `datagramChannelType()`
- `isAvailable()`
- `unavailabilityCause()`
- Deprecated the methods that merely delegates to `TransportType` in
`EventLoopGroups`.
- Removed the workaround for …

Allow using Armeria without epoll or io_uring JARs

---

spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaBeanPostProcessor.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortTest.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortsTest.java

Motivation:
In Spring Framework, `@LocalServerPort` values are not injected into the object to be made into a bean. However, `@LocalArmeriaPort` and `@LocalArmeriaPorts` in Armeria may have to be changed because such tests exist.
Modification:
- Fixed LocalArmeriaPortTest
- Fixed LocalArmeriaPortsTest
- Fixed typo
Result:
Fixed the wrong test.

Fix test for `@LocalArmeriaPort(s)`

---

core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientRetryTest.java

Motivation:
When creating a derived context, we check whether the `RpcRequest` is `null` or not
if `ctx.rpcRequest()` is not `null` in the consturctor of `DefaultClientRequestContext`.
```
private DefaultClientRequestContext(...) {
if (ctx.rpcRequest() != null) {
assert rpcRequest != null;
}
...
}
```
However, the assertion can be false.
The `rpcRequest` of the derived context is set later after the derived context is created so we don't know the timing.
Also, we call:
```java
ctx.logBuilder().defer(RequestLogProperty.REQUEST_CONTENT,
RequestLogProperty.RESPONSE_CONTENT);
```
that guarantees the `rpcRequest` of the derived context is set later when the request content of the parent context is set.
So we can completely remove the assertion.
Modification:
- Remove the assertion in …

Fix a bug where NPE is raised when retrying a gRPC request

---

consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java

Motivation:
```
ConsulEndpointGroupTest > initializationError FAILED
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in
com.linecorp.armeria.internal.consul.ConsulTestBase that uses com.pszymczyk.consul.ConsulStarterBuilder null within 10 seconds.
```
Modifications:
- Increase the timeout in `await()` to reduce flakiness
Result:
- Clean up flaky test in Consul

Fix flaky test in Consul

---

core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClient.java
site/src/pages/docs/client-circuit-breaker.mdx
site/src/pages/release-notes/1.3.0.mdx

- #3135 deprecated `newPerHostAndMethodDecorator()`, but the method in `CircuitBreakerRpcClient` hasn't been marked as deprecated
- Deprecate `CircuitBreakerRpcClient.newPerHostAndMethodDecorator()`
- Update wrong PR link in release notes
- Update documentation
- Method deprecations are consistent

Deprecate CircuitBreakerRpcClient.newPerHostAndMethodDecorator()

---

tomcat9/build.gradle

- `tomcat-embed-jasper` is used for JSP, not crucial for `TomcatService`
- `tomcat-embed-jasper` scans manifest, so some user can suffer `InvocationTargetException` from `TldScanner` even if don't use JSP
- Change `tomcat-embed-jasper` from `api` to `testImplementation`
- Remove `tomcat-embed-el` because `tomcat-embed-jasper` includes it
- armeria-tomcat will not include JSP dependencies as default
- **BREAKING CHANGE** An user who use armeria-tomcat and JSP have to declare `tomcat-embed-jasper` explicitly

Exclude `tomcat-embed-jasper` from exposed dependencies

---

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
core/src/main/java/com/linecorp/armeria/client/ClientHttp1ObjectEncoder.java
core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
core/src/main/java/com/linecorp/armeria/common/Http1HeaderNaming.java
core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
core/src/test/java/com/linecorp/armeria/client/Http1HeaderNamingTest.java
core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java

Motivation:
Armeria normalizes HTTP headers with lower cases for performance.
However, insensitive HTTP headers are rejected by some HTTP/1 servers.
See #3196 for more information.
Modifications:
- Add `Http1HeaderNaming` rule for customizing HTTP/1 header names.
- Add `http1HeaderNaming` to `ClientFactoryBuilder`
- Use the injected `http1HeaderNaming` in `ClientHttp1ObjectEncoder`
Result:
- You can now set your own HTTP/1 header naming rule using `ClientFactoryBuilder.http1HeaderNaming()`.
- Fixes #3196

Add `Http1HeaderNaming` rule for WebClient

---

docs-client/src/components/GotoSelect/index.tsx

- Let's say we have `A` and `B` endpoints
- If the user selects `A` from the `Go to...` dropdown and navigates to `B` from the sidebar
- Browser is now on the `B` endpoint, but the dropdown still has `A` selected
- User cannot navigate back to `A` from the `Go to...` dropdown since the `change` event is not triggered
Instead of calling `navigateTo()` in `handleSelection()`, split the logic into two steps:
1. `handleChange()` updates the currently selected value
2. `handleClose()` calls `navigateTo()` with the current value
Reference: [Autocomplete API](https://material-ui.com/api/autocomplete/)
- User can now correctly navigate to the item that's already selected

Fix 'Go to' selection handling in docs-client

---

core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
jetty9.3/build.gradle
jetty9/src/main/java/com/linecorp/armeria/server/jetty/ArmeriaEndPoint.java
jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
settings.gradle

Motivation:
Some of our customers use Jetty 9.3 and `armeria-jetty9` works only with
Jetty 9.4 due to the internal breaking API changes between Jetty 9.3 and
9.4.
Modifications:
- Dynamically resolve `Request.setAsyncSupported()` so that it works for
both `setAsyncSupported(boolean, Object)` and
`setAsyncSupported(boolean, String)`.
- Reimplement `ArmeriaEndPoint` so it works for both Jetty 9.3 and 9.4.
- Add `:jetty9.3` to make sure `JettyService` work with Jetty 9.3.
Result:
- `armeria-jetty9` works with both Jetty 9.4 and 9.3.

Support Jetty 9.3

---

eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java

1.  Fix instanceId may be null in method serverStopping, if  it is set by  fillAndCreateNewInfo.
2. Fix NoSuchElementException("No context was captured; no request was made?") may be thrown by contextCaptor.get(), if register enter: ( If we did not have the right jackson version) https://github.com/line/armeria/blob/a4724be4640fbe699776620b8bf36a93dced6135/eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/EurekaWebClient.java#L84

Fix eureka registration

---

core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java

Motivation:
In certain circumstances, such as `HttpRequest` is not properly subscribed and request timeout happens,
the access log is not recorded when the response is sent.
It's recorded later when the original response is completed.
Modification:
- Call `RequestLogBuilder.endRequest()` also when the response is sent.
Result:
- You can see the access log right away when the response is sent.

Fix to leave an access log when the response is sent

---

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/internal/common/util/SslContextUtilTest.java
core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java

Motivation:
A user sometimes wants to use the cipher suites discouraged in HTTP/2
specification for some reason.
Modifications:
- Add `tlsAllowUnsafeCiphers()` to `ServerBuilder` and
`VirtualHostBuilder`.
- Add `ClientFactoryBuilder.tlsAllowUnsafeCiphers()` without a
parameter for convenience, like we have
`ServerBuilder.tlsSelfSigned()` and `tlsSelfSigned(boolean)`.
Result:
- Customizability for interoperability with legacy

Add `tlsAllowUnsafeCiphers()` to `ServerBuilder` and `VirtualHostBuilder`

---

core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java

- I forgot to override `LoggingDecoratorBuilder#logger(String)` on `LoggingServiceBuilder` in #3035
- Override `LoggingDecoratorBuilder#logger(String)` on `LoggingServiceBuilder`
- We can use:
```java
LoggingService.builder()
.logger("foo")
.requestLogLevel(...)
...
```

Override logger(String) on `LoggingServiceBuilder`

---

core/src/main/java/com/linecorp/armeria/common/Flags.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt

Motivation:
The order of route decorators have been changed from forwarding order to reversing order in #3166.
This is a behavior change because users need to change their code to keep the original decoration order.
We can give an option to use the legacy order by enabling `Flags.useLegacyRouteDecoratorOrdering()` without modification of user code.
Modifications:
- Add `Flags.useLegacyRouteDecoratorOrdering()` to enable the legacy route decoration ordering.
```java
Server server =
.service("/users", userService)
.decoratorUnder("/", loggingDecorator)
.decoratorUnder("/", authDecorator)
.decoratorUnder("/", traceDecorator)
.build();
// if '-Dcom.linecorp.armeria.useLegacyRouteDecoratorOrdering=true' is configured,
// a request will go through the below decorators' order to …
```

Allow using the legacy decoration order with `Flags.useLegacyRouteDecoratorOrdering()`

---

core/src/main/java/com/linecorp/armeria/common/AbstractHttpHeadersBuilder.java
core/src/main/java/com/linecorp/armeria/common/ContentDisposition.java
core/src/main/java/com/linecorp/armeria/common/ContentDispositionBuilder.java
core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeaders.java
core/src/main/java/com/linecorp/armeria/common/HttpHeaderGetters.java
core/src/main/java/com/linecorp/armeria/common/HttpHeaders.java
core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
core/src/main/java/com/linecorp/armeria/common/HttpHeadersBuilder.java
core/src/main/java/com/linecorp/armeria/common/MediaType.java
core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
core/src/main/java/com/linecorp/armeria/common/QueryParams.java
core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java
core/src/main/java/com/linecorp/armeria/common/ResponseHeadersBuilder.java
core/src/main/java/com/linecorp/armeria/common/StringValueConverter.java
core/src/test/java/com/linecorp/armeria/common/ContentDispositionTest.java
core/src/test/java/com/linecorp/armeria/common/DefaultHttpHeadersBuilderTest.java
core/src/test/java/com/linecorp/armeria/common/HttpHeadersBaseTest.java
core/src/test/java/com/linecorp/armeria/common/StringMultimapDerivedApiConsistencyTest.java
dropwizard2/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaServerFactory.java

Motivation:
[`Content-Disposition`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header parser and builder are required to to support multipart message.
See #253 #2894
Modifications:
- Forked `ContentDisposition` parser and builder from Spring Framework and optimized it for Armeria.
- Add a `contentDisposition()` getter to `HttpHeaderGetter` and its subclass.
- Add `plain/text` and `multipart/form-data` used for multipart message to `MediaType`
- Check `ContentDisposition` type when converting an abitrary object in StringValueConverter
Result:
You can now add and get `Content-Disposition` header from and to HttpHeaders.

Add `Content-Disposition` header codec (Multipart 1/4)

---

site/src/pages/docs/advanced-structured-logging.mdx

Motivation:
I found a tiny error in the example of `ContentPreveiwerFactoryBuilder`.
AFAIK, the APIs of `ContentPreviewFactoryBuilder` is following:
```java
public ContentPreviewerFactoryBuilder text(MediaType... mediaTypes);
public ContentPreviewerFactoryBuilder text(Iterable<MediaType> mediaTypes);
public ContentPreviewerFactoryBuilder text(BiPredicate<? super RequestContext, ? super HttpHeaders> predicate);
```
Modifications:
- Fix an example to be consistent with `ContentPreviewFactoryBudiler` API
Result:
Polished document.

Fix unknown API example in advanced-structured-logging document

---

consul/src/main/java/com/linecorp/armeria/client/consul/ConsulEndpointGroup.java
consul/src/main/java/com/linecorp/armeria/client/consul/ConsulEndpointGroupBuilder.java
consul/src/main/java/com/linecorp/armeria/internal/consul/AgentServiceClient.java
consul/src/main/java/com/linecorp/armeria/internal/consul/CatalogClient.java
consul/src/main/java/com/linecorp/armeria/internal/consul/ConsulClient.java
consul/src/main/java/com/linecorp/armeria/internal/consul/ConsulClientUtil.java
consul/src/main/java/com/linecorp/armeria/internal/consul/HealthClient.java
consul/src/main/java/com/linecorp/armeria/server/consul/ConsulUpdatingListener.java
consul/src/main/java/com/linecorp/armeria/server/consul/ConsulUpdatingListenerBuilder.java
consul/src/test/java/com/linecorp/armeria/client/consul/ConsulEndpointGroupTest.java
consul/src/test/java/com/linecorp/armeria/server/consul/ConsulUpdatingListenerTest.java

This adds support for three Consul features:
- Creating Consul EndpointGroups that point to different datacenters.
- Filtering of Consul Endpoints using builtin Consul filters.
- Adding tags to Consul services on registration.

Add support for datacenters, tags and filtering to Consul

---

core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
core/src/test/java/com/linecorp/armeria/client/Http2ClientRefusedStreamTest.java

Motivation:
As per [8.1.4. Request Reliability Mechanisms in HTTP/2](https://tools.ietf.org/html/rfc7540#section-8.1.4),
a request that received `REFUSED_STREAM` could be safely retried because the server-side did not process anything from the stream.
> ```
> The REFUSED_STREAM error code can be included in an RST_STREAM
> frame to indicate that the stream is being closed prior to any
> processing having occurred.  Any request that was sent on the
> reset stream can be safely retried.
> ```
Motifications:
- Wrap `ClosedStreamExeception` with `UnprocessedException` when `REFUSED_STREAM` is received
Result:
You can now safely retry a request which received `REFUSED_STREAM` with RetryingClient.

Wrap `ClosedStreamExeception` with `UnprocessedRequestException` when `REFUSED_STREAM` is received

---

core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationNetUtil.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaAutoConfigurationWithConsumerTest.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaPropertyPortTest.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerArmeriaCustomKeyOverSpringTest.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerAutoConfigurationTest.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerCustomKeyAlias2Test.java
spring/boot2-webflux-autoconfigure/src/test/resources/config/application-test_armeria_port.yml
spring/boot2-webflux-autoconfigure/src/test/resources/config/application-test_armeria_ssl_custom_key_over_spring.yml

…tegration
Motivation:
Currently, Armeria TLS is configured twice if the Spring property has Armeria TLS configuration.
This raises an exception so the server can't be started.
The compression is applied multiple times as well.
Two ports are opened when
Modifications:
- Fix a bug where Armeria TLS is configured twice.
- Fix a bug where compression setting is applied multiple times
- Fix a bug where two ports are open when an Armeria port is specified in the property file
- Refactor `ArmeriaReactiveWebServerFactory`
- Fix a bug where `Consumer<ServerBuilder>` is not applied
- Fix a bug where `HealthChecker` and `HealthCheckServiceConfigurator` beans are not applied.
Result:
- You can now use Armeria TLS configuration using the Spring property file for Reactive Spring integration.
- You can …

Fix a bug where Armeria TLS is configured twice in Reactive Spring integration

---

zookeeper3/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroup.java
zookeeper3/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
zookeeper3/src/test/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroupTest.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceExternalClientUsageTest.java

Motivation
---
If a user wants to use an external `Curator` client in`ZooKeeperUpdatingListener` and the `Curator` instance was already started. The user can see the following exception.
```
java.lang.IllegalStateException: Cannot be started more than once
at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:311)
at com.linecorp.armeria.server.zookeeper.ZooKeeperUpdatingListener.serverStarted(ZooKeeperUpdatingListener.java:123)
at com.linecorp.armeria.server.Server$ServerStartStopSupport.notifyStarted(Server.java:658)
at com.linecorp.armeria.server.Server$ServerStartStopSupport.notifyStarted(Server.java:400)
at com.linecorp.armeria.common.util.StartStopSupport.notifyListeners(StartStopSupport.java:374)
at …
```

Fix `IllegalStateException` error when the external client was already started

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
core/src/main/java/com/linecorp/armeria/server/annotation/HttpFileResponseConverterFunction.java
core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceResponseConverterTest.java

* #3258
* Add `HttpFileResponseConverterFunction` and add it to `defaultResponseConverters` in `AnnotatedService`.
* `HttpFile` can be a return type in annotated services.
```java
@Head("...")
@Get("...")
HttpFile getFile() {
return HttpFile.of(...);
}
```

Add support for `HttpFile` auto-conversion in annotated services

---

annotation-processor/src/main/java/com/linecorp/armeria/server/annotation/processor/DocumentationProcessor.java

Use `SourceVersion` latest to avoid compile time warning:
> Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '11'
I'm not sure why gradle showing `TimeTrackingProcessor`, but I think this warning coming from Armeria processor as when I remove it from compilation warning dissappear.

Use SourceVersion.latest for the annotation processor

---

core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientStubFactory.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactoryUtil.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/JavaGrpcClientStubFactory.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/KotlinGrpcClientStubFactory.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/NullGrpcClientStubFactory.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ReactorGrpcClientStubFactory.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ScalaPbGrpcClientStubFactory.java
grpc/src/main/resources/META-INF/services/com.linecorp.armeria.client.grpc.GrpcClientStubFactory
grpc/src/test/java/com/linecorp/armeria/internal/client/grpc/CustomGrpcClientFactoryTest.java

Motivation:
A factory for gRPC clients is hard-coded and a user can not plug-in a custom factory.
He/she has to send a PR for adding a new client factory to the existing factory logic.
See #3214 for more information.
Modifications:
- Add `GrpcClientStubFactory` and load it via SPI.
- The unified gRPC client factory is split into each client provider.
- Add `GrpcClientOptions.GRPC_CLIENT_STUB_FACTORY` for registering a `GrpcClientStubFactory` without SPI.
- This is useful if a gRPC client factory has a runtime dependency.
```java
Clients.builder("gproto+http://127.0.0.1")
.option(GrpcClientOptions.GRPC_CLIENT_STUB_FACTORY.newValue(new GrpcClientStubFactory() {
@Override
public ServiceDescriptor findServiceDescriptor(Class<?> clientType) {
return HelloServiceGrpc.SERVICE;
}
@Override
public …
```

Provide a way to register a custom gRPC client stub factory

---

grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java

Currently, `GrpcServiceBuilder` doesn't have a method to add multiple `ServerServiceDefinition` though it has `addService(ServerServiceDefinition)`.
This method will be useful for users who are using `io.grpc.ServerInterceptors.intercept()`.

Add multiple ServerServiceDefinition to GrpcServiceBuilder

---

core/src/main/java/com/linecorp/armeria/server/healthcheck/DefaultHealthCheckUpdateHandler.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckUpdateHandler.java
core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckUpdateListener.java
core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java

If user want to prevent setting health check as healthy at startup, for such as warming up, user should register additional  `HealthChecker`.
- Add `startUnhealthy` option which disables setting healthy when the `Server` starts.
- Add `HealthCheckUpdateListener.java` for receiving `HealthCheckService` update events.
- Users can prevent that the `Server` health check is always healthy without registering additional `HealthChecker`.
- Users can register health check update listener.

Add option to start `HealthCheckService` unhealthy and register listener

---

core/src/main/java/com/linecorp/armeria/common/RequestContext.java
core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java

Related issue: https://github.com/line/armeria/issues/2611
If RequestContext provides run(Runnable) or call(Callable) we can reduce boilerplate code and simplify it.

Provide more ways to run with context

---

core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/main/java/com/linecorp/armeria/common/PublisherBasedHttpResponse.java
core/src/main/java/com/linecorp/armeria/internal/common/stream/PrependingPublisher.java
core/src/test/java/com/linecorp/armeria/common/PublisherBasedHttpResponseTest.java
core/src/test/java/com/linecorp/armeria/internal/common/stream/PrependingPublisherTckTest.java

Motivation:
Provide an easy way to build a `HttpResponse` with `ResponseHeaders` and a `Publisher<HttpObject>`.
Modifications:
Added `PrependingPublisher` that can prepend an object to a `Publisher` of the same type.
Result:
Closes #3089

HttpResponse.of(ResponseHeaders,Publisher<HttpObject>)

---

site/src/pages/docs/server-docservice.mdx

`DocService` seems to use unframed requests. No need to enable gRPC-Web.
https://github.com/line/armeria/blob/master/docs-client/src/lib/transports/grpc-unframed.ts
slack: https://line-armeria.slack.com/archives/C1NGPBUH2/p1612152775044500

Correct DocService documentation

---

site/src/pages/docs/advanced-structured-logging.mdx

I found a typo on the [Armeria site](https://armeria.dev/docs/advanced-structured-logging/).
The following content is containing meaningless `}`. So I remove it.
`Thrift - a service type (e.g, com.foo.ThriftService$AsyncIface or com.foo.ThriftService$Iface})
`
-> 
`Thrift - a service type (e.g, com.foo.ThriftService$AsyncIface or com.foo.ThriftService$Iface)`

Fix a typo in the structured logging site page

---

site/src/pages/news/20210202-newsletter-2.mdx
site/src/styles/antd-overrides.less

A workaround for overlapping embedded tweets in Safari browser.

Add an explicit width for embedded tweet in newsletter

---

jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
jetty9/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java
testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerTest.java

Related: #3320
Motivation:
`JettyService` is currently incapable of running a Jetty handler which
makes use of `Request.startAsync()`. It'd be great if we support it as
well.
Modifications:
- Use `HttpChannel.handle()` instead of `Server.handle()` so that
request state is managed correctly by Jetty, fixing issues with
asynchronous request processing.
- Simplify `ArmeriaHttpTransport`.
- It doesn't have to buffer everything before sending out a response
anymore.
- `Content-Length` header is not set anymore when a Servlet sends a
streaming response, which is normal.
- Write `HttpData` with the `endOfStream` flag set when Jetty tells us
it's sending the last content.
- Write trailers set by Jetty (for Jetty 9.4+).
Result:
- Closes #3320
- `JettyService` can now handle asynchronous Servlets. …

Support async request handling in `JettyService`

---

core/build.gradle

Motivation:
If a DNS query is sent, the following warning messages is prinited on macOS.
```java
WARN  i.n.r.d.DnsServerAddressStreamProviders - Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.
java.lang.ClassNotFoundException: io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
```
Modifications:
- Add `netty-resolver-dns-native-macos` as a transitve dependencies
- `netty-resolver-dns-native-macos` is only [9KB](https://mvnrepository.com/artifact/io.netty/netty-resolver-dns-native-m …

Add `netty-resolver-dns-native-macos` as a transitive dependency

---

consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/LazyDynamicEndpointGroupTest.java

…EndpointGroup`
Motivation:
If an `EndpointGroup` is not initialized with initial values,
a gRPC client will raise an `IllegalStateException` with the following message:
```java
io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@3830513a
java.lang.IllegalStateException: Should call init(endpoint) before invoking this method.
```
A `WebClient` waits a connection timeout for the `EndpointGroup` to have at least one Endpoint by @trustin's work (#2837)
However, a gRPC client does not wait for the `EndPointGroup` and start a gRPC request immediately.
Modifications:
- Add `DefaultClientRequestContext.whenIntialized()` which completes
when a `ctx` is initialized with an `EndpointGroup`.
- Defer a gRPC call until a `whenIntialized()` is completed.
Result:
- You no …

Fix a bug where an `IllegalStateException` is raised on a non-ready `EndpointGroup`

---

core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorCloseTest.java

Motivation:
The duplicator should not release any elements that are not subscribed yet.
However, the duplicator has a bug that releases elements when
the duplicator is closed even there are unsubscribed subscribers.
Modification:
- Check if there are unsubscribed subscribers before releasing elements
- Do not release if there are unsubscribed ones.
Result:
- You are no longer see `IllegalArgumentException` when using `RetryingClient`.

Fix not to release elements before subscribed in duplicator

---

grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTrailersTest.java

Motivation:
In a unary call and client-streaming, some gRPC client requests 1 message and expects to receive a message and close the call
even though the official gRPC-Java stub requests 2 and expects a message.
https://github.com/grpc/grpc-java/blob/613439c97e8ab3a62670411fd9367aa126fed2cf/stub/src/main/java/io/grpc/stub/ClientCalls.java#L412-L415
Modifications:
- Adjust `numMessages` to 2 if one message is requested and a `MethodType` is `UNARY` or `CLIENT_STREAMING`
Result:
You can now correctly receive a gRPC response even if a gRPC client requests one message.

Fix a bug where trailers is not properly received by non-official gRPC client

---

core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
site/src/pages/docs/client-http.mdx

Motivation:
The current `WebClient` documentation does not provide a brief introduction from which users can learn the overall features of `WebClient`.
Modifications:
- Add simple introduction for decorator, service discovery and ClientFactory.
- Link to the detailed documentation

Add documentation for brief introduction of WebClient features

---

core/src/main/java/com/linecorp/armeria/client/WebClientRequestPreparation.java
core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
core/src/main/java/com/linecorp/armeria/common/HttpRequestBuilder.java
core/src/test/java/com/linecorp/armeria/common/HttpRequestBuilderTest.java

Motivation:
A `Publisher` cannot be set as a content with `HttpRequestBuilder`.
Since it was difficult to append trailers when a `Publisher` is fully consumed.
However, now, we can easily make it with `StreamMessage.concat(Publisher...)` which has been added recently.(#3254)
Modifications:
- Add `HttpRequestBuilder.content(MediaType, Publiisher<? extends HttpData>)`
Result:
You can now fluently build an `HttpRequest` with a `Publisher<HttpData>`.

Provide a way to bulid an `HttpRequest` with a `Publisher`

---

core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaBeanPostProcessorConfiguration.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerGracefulShutdownLifecycle.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationDisabledTest.java
spring/boot2-autoconfigure/src/test/resources/config/application-disabled.yml

If no `ArmeriaServerConfigurator` or `Consumer<ServerBuilder>` in the spring context. The `AbstractArmeriaAutoConfiguration` would create an `ArmeriaServerGracefulShutdownLifecycle `bean with `server = null`.
Should we return null in the `armeriaServer` method ?
```
@Bean
@Nullable
public Server armeriaServer(
```
If whould make ` @ConditionalOnBean(Server.class)` match success even if the method return null, and user have to check the server is null or not.
Other solutions:
1. Add a custom Conditional annotation to `armeriaServer`, to check if any   `ArmeriaServerConfigurator` or `Consumer<ServerBuilder>` bean in the context. But maybe in most case , we would like to create an  ArmeriaServerConfigurator instance only if there is a server bean.
2. Start up armeria server, whether there …

Don't create ArmeriaServerGracefulShutdownLifecycle bean when Armeria server is not available

---

thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java

The request header should use the `ThriftFunction.name`, not the name in `Iface` method.
In our old thrift server, the response header's method name maybe camelcase, `THttpClientDelegate.readApplicationException`  will be failed.
```java
private static TApplicationException readApplicationException(....) {
// omits...
if (!func.name().equals(msg.name)) {
return new TApplicationException(TApplicationException.WRONG_METHOD_NAME, msg.name);   
}
// omits ...
}
```
Use `ThriftFunction.name` instead of `iface` method name.
```java
final TMessage header = new TMessage(fullMethod(ctx, func.name()), func.messageType(), seqId);
```
Relative issue: #3269

Use func.name() to build Thrift request header

---

it/thrift-fullcamel/src/test/java/server/thrift/CamelNameThriftServiceTest.java
it/thrift-fullcamel/src/test/thrift/main.thrift
thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftFunction.java
thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftServiceMetadata.java

If we define a thrift service:
```thrift
service SayHelloService {
// Test a underscored method name
string say_hello(1:string name)
// Test a upcamel method name
string SayHelloNow(1:string name)
// Test a lowcamel method name
string sayHelloWorld(1:string name)
}
```
When compile with fullcamel option in thrift java compiler, the server and client will failed to find `SayHelloNow` method.
Currently `fullcamel` support use `CaseFormat` to convert and to support only underscore style method name.
But UpCamel style method name will also be convert to lowCamel in thrift compiler.
Because we could not know thrift method style properly, so we use the algorithm in thrift java compiler to do the low camel convert.
See https://github.com/apache/thrift/blob/master/compiler/cpp/src/thrift/generate/ …

Fix a bug where UpCamel style method names in Thrift not supported

---

.appveyor.build.sh
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
gradle/scripts/lib/java.gradle
scalapb/scalapb_2.12/build.gradle
scalapb/scalapb_2.13/build.gradle
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/common/scalapb/ScalaPbJsonMarshaller.scala
scalapb/scalapb_2.13/src/test/proto/messages.proto
scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/common/scalapb/ScalaPbJsonMarshallerTest.scala

When returning a ScalaPB message of [the `sealed-oneof` flavour](https://scalapb.github.io/docs/sealed-oneofs/),
the JSON marshaller does not marshal the wrapping message.
This changeset corrects that by detecting the case where the value passed in
is a `GeneratedSealedOneof`, and then marshalls the container message.

Fix the scalapb json marshaller for sealed-oneof messages

---

core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnaryGrpcService.java
grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnaryGrpcServiceTest.java

Motivation:
It'd be useful to have a `ServiceRequestContext` available as a
parameter and thread-local variable in the `handle()` methods in
`AbstractUnsafeUnaryGrpcService` and `AbstractUnaryGrpcService`.
Modifications:
- Add `ServiceRequestContext` as a parameter of `handle()` methods.
- Push the current context before calling `handle()`.
Result:
- Convenience

Make `ServiceRequestContext` available in `Abstract*UnaryGrpcService.handle()`

---

core/src/main/java/com/linecorp/armeria/client/encoding/DecodingClient.java
core/src/main/java/com/linecorp/armeria/client/encoding/DecodingClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/encoding/HttpDecodedResponse.java
core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/client/encoding/DecodingClientTest.java
core/src/test/java/com/linecorp/armeria/client/encoding/HttpDecodedResponseTest.java

Motivation:
Currently, `DecodingClient` does nothing if an accept-encoding is specified.
https://github.com/line/armeria/blob/6da4e23b198cb769bc97dfe23f4e2eaed73254bf/core/src/main/java/com/linecorp/armeria/client/encoding/DecodingClient.java#L87-L90
However, some users might want to specify accept-encoding header and decode the response content using `DecodingClient`.
Modifications:
- Add `DecodingClientBuilder` in order to fluently build a `DecodingClient` with various options.
- Add `autoFillAcceptEncoding(boolean)` to `DecodingClientBuilder`
- If this option is disabled, `DecodingClient` will respect user-defined accept-encoding header
- Add `strictContentEncoding(boolean)` to `DecodingClientBuilder`
- If this option is enabled and unsupported encoding is received from an abnormal …

Add `DecodingClientBuilder`

---

core/build.gradle
dependencies.yml
scalapb/scalapb_2.12/build.gradle
scalapb/scalapb_2.13/build.gradle
settings.gradle

- Extracted `scala-library` and `gradle-scalafmt` version to
`dependencies.yml`.
- Updated `scala-library` from 2.13.4 to 2.13.5 and 2.12.12 to 2.12.13
- Removed the `grpc-scalapb_2.13` flag from `:scalapb_2.12` because we
reuse the source code generated by `:scalapb_2.13`.
- Added the `no_aggregation` flag to `:scalapb_2.12` because it conflicts
with `:scalapb_2.13` during aggregation. We currently don't do any
aggregation for Scala code, but we will get an error once we start to
aggregate.
- Made `:scalapb_2.12` depend on `:scalapb_2.13:generateTestProto`
instead of `:scalapb_2.13:compileTestScala`.

Clean up Scala builds

---

core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointWeightTransition.java
core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategyBuilder.java

Motivation:
The property name `numberSteps` is somewhat unclear. It has to be
`numberOfSteps` or `totalSteps` to make it clear that it signifies the
total number of steps required to complete the ramp-up.
Modifications:
- Rename `numberSteps` to `totalSteps`
Result:
- Clarity
- (Breaking change) `WeightRampingUpStrategyBuilder.numberSteps()` has
been removed.

Rename `numberSteps` to `totalSteps` in `WeightRampingUpStrategy` API

---

core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
core/src/main/java/com/linecorp/armeria/server/Route.java
core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
core/src/test/java/com/linecorp/armeria/server/FallbackServiceTest.java
core/src/test/java/com/linecorp/armeria/server/RouteDecoratingServiceTest.java

Related issues:
- #3365 
- https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2345#discussion_r579026286
Motivation:
A user sometimes wants to know whether the current request is mapped
into a fallback route. It'd be nice if we have something like the
following:
ctx.config().route().isFallback()
Modifications:
- Added `Route.isFallback()`.
- Added `RouteBuilder.FALLBACK_ROUTE` for an internal use.
- Specified `FALLBACK_ROUTE` instead of `Route.ofCatchAll()` when
binding a fallback service.
- Added `FallbackServiceTest` that tests the cases where the fallback
route is matched.
- Moved the test case for preflight requests from
`RouteDecoratingServiceTest` to `FallbackServiceTest`, because they
really didn't test route decorators.
Result:
- Closes #3365
- A user can …

Add `Route.isFallback()`

---

brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceTest.java
core/src/main/java/com/linecorp/armeria/server/TransientServiceOption.java

- Requests to `HealthCheckService` are traced by `BraveService`. It's inconvenient because meaningful requests are sampled less when there are lots of L7HC requests.
- Add `WITH_TRACING` to `TransientServiceOption`.
- Do not trace requests to `TransientService` if it does not have `WITH_TRACING` option.
- The `BraveService` does not trace requests to the `TransientService` like the `HealthCheckService`.

Do not trace requests to `TransientService` by default

---

core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/test/java/com/linecorp/armeria/server/HttpResponseSubscriberTest.java

Motivation:
If a `HttpResponseSubscriber` receives an HTTP trailers, it cancels the upstream immediately to clean up elements in the upstream queue.
When all `HttpObject`s are fully consumed, users does not expect that `StreamMessage.whenComplete()` completes with an `CancellationException`.
Modifications:
- Do not cancel an upstream and send a request when an EOS or an HTTP trailers is received.
- Cancel the upstream when a message is received after the status becomes `DONE`
Result:
- You no longer see `CancellationException` when a HttpResponse is fully consumed.

Fix a bug where a `StreamMessage` is canceled after fully consumed by a `Subscriber`

---

core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java
core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java
core/src/main/java/com/linecorp/armeria/common/ClientCacheControl.java
core/src/main/java/com/linecorp/armeria/common/logging/ContentPreviewerFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/test/java/com/linecorp/armeria/client/IgnoreHostsTrustManagerTest.java
core/src/test/java/com/linecorp/armeria/client/proxy/ProxyConfigTest.java
core/src/test/java/com/linecorp/armeria/internal/common/ContextAwareFutureTest.java
core/src/test/java9/com/linecorp/armeria/internal/common/Java9ContextAwareFutureTest.java
dropwizard2/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaSettings.java
eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
grpc/src/test/proto/com/linecorp/armeria/grpc/testing/metrics.proto
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationDisabledTest.java

Motivation:
- Inspect by proofreading
Modifications:
- criterias -> criteria
- deteremines -> determines
- all directived -> all directives
- seprate -> separate
- nomalizedPathPattern -> normalizedPathPattern
- http2MaxFramSize -> http2MaxFrameSize
- autyType -> authType
- Addresss -> Address
- extesion -> extension
- DroppWizard -> DropWizard
- misconfigued -> misconfigured
- Reponse -> Response
- disabed -> disabled
- disalbed -> disabled
Result:
- Fixed mistypo

Fix typo in whole project

---

grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnaryGrpcService.java
grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnaryGrpcServiceTest.java

Motivation:
The return type of `Abstract*UnaryGrpcSerivce.handleMessage()` can be
relaxed from `CompletableFuture` to `CompletionStage`, so we give our
users more freedom in their implementation details.
Modifications:
- Change the return type of `Abstract*UnaryGrpcService.handleMessage()`
from `CompletableFuture` to `CompletionStage`.
Result:
- Less implementation detail in the public API

Change the return type of `Abstract*UnaryGrpcService.handleMessage()`

---

core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java

Motivation:
Fix https://github.com/line/armeria/issues/3036
Modification:
Due to for each loop calling HttpResponseWrapper#close and trigger this#removeResponse during looping. We think it may be the reason of NPE at `HttpResponseWrapper#close`. Try to remove through iterator first then calling close method.

Fix NullPointerException in failUnfinishedResponses

---

core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt

Motivation:
If bootstrap#register failed, we still can get channel and it fails at connect with evenloop is null problem. Add listener to connect when register is succeed. 
Result:
Not really fixes https://github.com/line/armeria/issues/3369, but we can have better error message to know the reason.
--
Currently I'm not sure if it's easy to write test for this case. Any idea?

Make client connect has better exception message when channel doesn't have event loop

---

core/src/main/java/com/linecorp/armeria/server/streaming/JsonTextSequences.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java
protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufResponseAnnotatedServiceTest.java
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/common/scalapb/ScalaPbJsonMarshaller.scala
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbConverterUtil.scala
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala
scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunction.scala
scalapb/scalapb_2.13/src/test/proto/hello.proto
scalapb/scalapb_2.13/src/test/proto/messages.proto
scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/HelloServiceImpl.scala
scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/HelloServiceTest.scala
scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseAnnotatedServiceTest.scala

Motivation:
Currently, a list of Protobuf messages can be converted to JSON array in annotated service.
It would be useful to support JSON Text sequences for `Publisher` and `Stream` type,
when users want to convert a gRPC streaming response to a stream of JSON messages.
Modifications:
- Convert a `Publisher` or `Stream` into `"application/json-seq"` by `{Protobuf,ScalaPb}ResponseConverterFunction`.
- Add new factory methods that convert an arbitrary object into a JSON string.
- The converters were strongly bound to Jackson's `ObjectMapper`.
- Fix a bug where [sealed oneofs](https://scalapb.github.io/docs/sealed-oneofs/) are not properly (de)serialized by ScalaPb{Request,Response}ConverterFunction` and `ScalaPbJsonMarshaller`.
Result:
- You can now convert a stream of Protobuf messages …

Support JSON Text streaming for Protobuf Messages

---

core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpServiceBuilder.java
thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/THttpServiceBuilderTest.java

Motivation:
A user might define his/her own exception in the Thrift service and use it in the client and server side.
If we provide a way to convert an exception into an `RpcResponse`, he/she can easily
translate the exceptions that are defined in JDK or 3rd party libraries into an `RpcResponse`.
Here are related resources.
- https://github.com/line/centraldogma/blob/master/server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaExceptionTranslator.java
- https://github.com/line/centraldogma/blob/master/server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/Converter.java#L183
- https://github.com/line/centraldogma/blob/master/common-legacy/src/main/thrift/CentralDogma.thrift#L81
Modifications:
- Add `THttpServiceBuilder.exceptionHandler(...)`
- …

Provide a way to convert an exception into an RpcResponse in Thrift service

---

site/build.gradle

Motivation:
`site:clean` currently depends on `site:npmClean` that actually depends
on `site:npmInstall`. `site:npmInstall` can take longer than usual
because it has to fetch all site build dependencies first.
Modifications:
- Let Gradle delete all known build output of `site` so `site:clean`
doesn't have to invoke `site:npmInstall` and `site:npmClean`.
Result:
- Better experience for contributors

Do not trigger `site:npmInstall` on `site:clean`

---

.appveyor.build.sh
consul/build.gradle
consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
testing-internal/src/main/resources/logback-test.xml

Motivation:
`ConsulTestBase` downloads the Consul binary frmo a remote repository
and caches it so that it doesn't have to download again.
Sometimes the download takes more than a minute, causing JUnit to fail
the tests downloading the binary.
Modifications:
- Move the binary download process to the build script so
`ConsulTestBase` never downloads anything as long as it's invoked from
Gradle.
Result:
- `ConsulTestBase` and its subtypes should not fail with timeout
anymore.

Download the Consul binary before starting tests

---

core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt

Motivation:
Since 4edffc8c11bd74665d652a1fd108d6a0307b6733, we check whether epoll
and io_uring native transports are available or not upfront. However,
there's a known issue in Netty where `Socket.isIPv6Preferred()` can
return a wrong value when more than one native transport are loaded:
- https://github.com/netty/netty/issues/10909
Modifications:
- Force-reinitialize `Socket` by calling its private method after a new
native library is loaded, so that `Socket.isIPv6Preferred()` always
returns a correct value.
- Print the Netty version just in case we have any dependency issues.
Result:
- We don't get the 'Address family not supported by protocol' or
'Connection refused' error anymore.
- Works around https://github.com/netty/netty/issues/10909 until it's
fixed.

Force-reinitialize `io.netty.channel.unix.Socket` after loading a native library

---

.appveyor.build.sh
.appveyor.yml
build.gradle
consul/src/main/java/com/linecorp/armeria/client/consul/ConsulEndpointGroupBuilder.java
consul/src/main/java/com/linecorp/armeria/server/consul/ConsulUpdatingListenerBuilder.java
core/src/main/java/com/linecorp/armeria/common/ContentDispositionBuilder.java
core/src/main/java/com/linecorp/armeria/common/RequestHeaderGetters.java
core/src/test/java/com/linecorp/armeria/client/cookie/DefaultCookieJarTest.java
dependencies.yml
gradle/wrapper/gradle-wrapper.properties
protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java
protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java
resteasy/src/main/java/com/linecorp/armeria/client/resteasy/ArmeriaResteasyClientBuilder.java
site/src/pages/community/developer-guide.mdx
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/HealthCheckServiceConfigurator.java

- Fixed Javadoc errors which started to appear since JDK 15
- Now requires JDK 15 to perform a release
- Does not reject JDK 11 anymore, since JDK 11 is still a popular choice
among Java devs.
- Updated the build error message to reflect this change.
- Updated Gradle to 6.8.3
- Updated the JDK/JREs we use for CI
- Updated ProGuard to 7.1-beta1 (required for Java 15)
- Updated the build requirements in the developer guide.
- We don't recommend SDKMan anymore since it does not list old JDK
releases, giving people hard time installing JDK 15.
- Fixed a flaky test: `com.linecorp.armeria.client.cookie.DefaultCookieJarTest.maxAge()`

Make Armeria buildable with JDK 15

---

core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java

Motivation:
When a `PathStreamMessage` is created with an empty file,
it is hard to tell whether the stream message is open immediately.
Because we have to open the file to check the size.
Motivations:
- Exclude `PathStreamMessage` from the validation which checks whether the stream is closed.
Result:
- No more flakiness
- Fixes #3423

Fix a flaky test in `PathStreamMessageTckTest`

---

core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
core/src/main/java/com/linecorp/armeria/server/Route.java
core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
core/src/main/java/com/linecorp/armeria/server/Routers.java
core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java
core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
core/src/test/java/com/linecorp/armeria/server/HttpServerAutoRedirectTest.java
core/src/test/java/com/linecorp/armeria/server/RouterTest.java
core/src/test/java/com/linecorp/armeria/server/RoutingTrieTest.java

Motivation:
Currently `RoutingTrie` can find a route only based on the request path. But there's lots of conditions
used to resolve a correct path such as HTTP methods, content-type header, accept header, and even
a certain HTTP header and/or parameter.
So we need to check whether a route is acceptable for the request or not earlier than now,
in order to avoid picking up wrong routes.
Modifications:
- Introduce `NodeProcessor<?>` and pass a node into it when the node is selected as a candidate.
- Create a `RouteCandidateCollectingNodeProcessor` and pass it to `RoutingTrie#find` method when finding
`ServiceConfig` instances from `RoutingTrie`.
- It holds `Routed` instances resolved while visiting the trie.
- If a node is not acceptable for the request, it would be dropped.
- Create a new …

Fix a bug where a request has failed to be routed when both a '/path' and a '/{var}' path mappings exist with different HTTP methods

---

core/build.gradle

Motivation:
At `/core/build.gradle`, we use incorrect managed dependency names, such
as `io.netty:netty-resolver-dns-native-macos`, resulting in `null`
versions.
Modifications:
- Use `io.netty:netty-bom` instead.
Result:
- Our build doesn't attempt to retrieve the POM for a non-existing
artifact version (`null`) anymore.

Fix incorrect managed dependency names

---

core/src/main/java/com/linecorp/armeria/client/metric/AbstractMetricCollectingClient.java
core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingClient.java
core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingClientBuilder.java
core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingRpcClient.java
core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingRpcClientBuilder.java
core/src/main/java/com/linecorp/armeria/common/metric/AbstractMetricCollectingBuilder.java
core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java
core/src/main/java/com/linecorp/armeria/server/metric/MetricCollectingService.java
core/src/main/java/com/linecorp/armeria/server/metric/MetricCollectingServiceBuilder.java
core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/HelloConfiguration.java

Fixes #3404
~Just opening a draft PR for feedback. 
Still need to implement `MetricCollectingClient` and `MetricCollectingRpcClient`.
Please let me know if this approach is good.~
- Allow users to specify which requests should be considered successful when incrementing metrics. Currently there is hardcoded logic that checks the statusCode here https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java#L168-L171
- Added builders for `MetricCollectingService`, `MetricCollectingClient` and `MetricCollectingRpcClient`
- Added an example usage of specifying the `successFunction` predicate
- Added a unit test in `RequestMetricSupportTest`

Allow to customize success status for request metrics

---

core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java

* Needs for a new MDC property which can be used for tracing logs within a same `ServiceRequestContext` (#3429). 
* Add new built-in MDC property, `req.root_id`.

Add new built-in MDC property `req.root_id`

---

core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
core/src/test/java/com/linecorp/armeria/internal/common/CancellationSchedulerTest.java

… timed out
Motivation:
A `{Request,Response}TimeoutException` is instanticated when a `CancellationScheduler` is intialized.
https://github.com/line/armeria/blob/214ae3bcf18bdf8fd0cb29196ac5b9542e13b397/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L118-L120
If a server is working as expected, a timeout exception early created would be meaningless creation and overhead.
Modification:
- Remove `initialCause` from `CancellationScheduler` and add `server`
flag used for lazily creating `TimeoutException`
- `RequestTimeoutException.get()` is used for server-sides
- `ResponseTimeoutException.get()` is used for clien-sides
Result:
- A timeout exception is created only when a request or response is timed out

Defer instantiation of a TimeoutException until a request actually is timed out

---

brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.java

…rrentTraceContext`
Motivation:
`RequestContext.contextAwareExecutor()` has been removed from our code base #2834
Modifications:
- Remove the invalid `RequestContext.contextAwareExecutor()` from the warn message
Result:
Less confusion

Remove invaild method name from the warn message in `RequestContextCurrentTraceContext`

---

core/src/main/java/com/linecorp/armeria/internal/server/JacksonUtil.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java
core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
core/src/main/java/com/linecorp/armeria/server/streaming/JsonTextSequences.java
kotlin/build.gradle.kts
kotlin/src/test/kotlin/com/linecorp/armeria/server/JacksonModuleAnnotatedServiceTest.kt
scala/scala_2.12/build.gradle
scala/scala_2.13/build.gradle
scala/scala_2.13/src/test/scala/com/linecorp/armeria/server/JacksonModuleAnnotatedServiceTest.scala
scala/scala_2.13/src/test/scala/com/linecorp/armeria/server/ServerSuite.scala

Motivation:
Kotlin and Scala users should have to use a custom Jackson `Module` for `Jackson{Request,Response}ConverterFunction` such as:
- https://github.com/FasterXML/jackson-module-kotlin
- https://github.com/FasterXML/jackson-module-scala
The custom `Jackson{Request,Response}ConverterFunction`s should be declared to a service builder every time. For example:
```scala
val scalaObjectMapper = JsonMapper.builder().addModule(DefaultScalaModule).build()
Server
.builder()
.annotatedService()
.requestConverters(new JacksonRequestConverterFunction(scalaObjectMapper))
.responseConverters(new JacksonResponseConverterFunction(scalaObjectMapper))
.build(myScalaService)
...
```
It would be boilerplate code if users just want to use the custom modules with default configurations.
Modifications:
- …

Support Kotlin's data class and Scala's case class in the default Jackson converter of annotated service

---

core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
core/src/test/java/com/linecorp/armeria/client/WebClientRequestPreparationTest.java
core/src/test/java/com/linecorp/armeria/common/HttpRequestBuilderTest.java

Motivation:
`AbstractHttpRequestBuilder.buildPath()` has the following bugs:
- It treats `{}` and `:/` as a path parameter.
- It treats a port number in an absolute URI as a path parameter.
- It doesn't handle the case where a path contains a query string already.
Modifications:
- Reject a path parameter with an empty name in `pathParam()` and
`pathParams()`.
- Skip a path parameter with an empty name in `buildPath()`
- If a path already contains a query string, append the query parameters
specified with `queryParam()` using `&`.
- Optimization:
- Do not create a `StringBuilder` if possible.
- Do not use `StringBuilder.replace()`.
Result:
- A path parameter with an empty name is ignored.
- An absolute URI can now be used with `WebClient.prepare()`.
- A user can specify a query string both …

Fix incorrect path parameter substitutions in `AbstractHttpRequestBuilder`

---

core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java

Motivation:
When a user uses a Netty JAR without native libraries included, he or
she will see the following exception during the initialization phase:
```
java.lang.reflect.InvocationTargetException: null
...
caused by: java.lang.UnsatisfiedLinkError: 'void io.netty.channel.unix.Socket.initialize(boolean)'
...
```
Modifications:
- Do not log when `Socket.initialize()` failed due to a
`UnsatisfiedLinkError`.
- Log at DEBUG level otherwise, because it's useful only to devs.
Result:
- Less verboseness.
- Doesn't surprise a user anymore.
- Fixes #3457

Do not log verbosely when `Socket.initialize()` fails.

---

grpc/build.gradle
scala/scala_2.12/build.gradle
scala/scala_2.13/build.gradle

Motivation:
The following modules do not really require
`javax.annotation:javax.annotation-api` to build or run:
- `armeria-grpc`
- `armeria-scala_2.12`
- `armeria-scala_2.13`
Modifications:
- Remove `javax.annotation:javax.annotation-api` from the modules listed
above.
Result:
- Fixes #3445

Remove unused `javax.annotation:javax.annotation-api` dependencies

---

core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
core/src/main/java/com/linecorp/armeria/common/HttpMethod.java
core/src/main/java/com/linecorp/armeria/server/AbstractHttpService.java
core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
core/src/test/java/com/linecorp/armeria/client/HttpClientRequestPathTest.java
core/src/test/java/com/linecorp/armeria/common/HttpMethodTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerConnectMethodTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerTooLargeContentTest.java

Motivation:
To use WebSockets with HTTP/2, we need to allow a CONNECT request with
a `:protocol` pseudo header at least, as specified in:
- https://datatracker.ietf.org/doc/rfc8441
(RFC 8411, Bootstrapping WebSockets with HTTP/2)
Modifications:
- Added `HttpHeaderNames.PROTOCOL`
- Added `AbstractHttpService.doConnect()`
- Armeria now rejects all HTTP/1 `CONNECT` requests explicitly.
- We never supported it anyway and it never worked.
- Armeria now rejects all HTTP/2 `CONNECT` requests without a
`:protocol` pseudo header.
- We never supported it anyway and it never worked.
- Added `HttpMethod.tryParse()`
- Renamed `Http1RequestDecoderTest` to `HttpServerTooLargeContentTest`
Result:
- We can start to implement WebSockets once Netty adds support for a
`:protocol` pseudo …

Prepare to support WebSockets over HTTP/2

---

benchmarks/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java

Motivation:
- Investigate the bottleneck or time-consuming job to improve the performance with data
- Increase [the rank in TechEmpower](https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=plaintext&l=zik0vz-sf)
Modifications:
- Add a benchmark for plaintext
Result:
- <img width="614" alt="2" src="https://user-images.githubusercontent.com/11401808/113807639-7bf24000-979f-11eb-82da-fe6d3e6ddba7.png">
- <img width="591" alt="flame graph" src="https://user-images.githubusercontent.com/11401808/113807657-84e31180-979f-11eb-8102-bf01b77df43d.png">

Add a benchmark for plaintext

---

brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java

Motivation:
A thread is stuck to take a Span from a `BlockingQueue`.
I guess the client cancels a request before the server receives and handles it by `BraveService`.
Modifications:
- Increase the timeout to 3 milliseconds to 3 seconds
- The computing power of CI is pretty low. 😞
Result:
- No more hanging tests
- Hopefully fixes #3492

Increase timeout to fix flaky test in BraveIntegrationTest

---

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
core/src/test/java/com/linecorp/armeria/client/Http1ResponseDecoderTest.java

Sorry about the delay and thanks for your patience 🙏 
**Motivation**
I've updated my thoughts in the issue: https://github.com/line/armeria/issues/3055#issuecomment-828560365
tldr; this PR basically attempts to suppress warning logs when a server-side initiated 408 request timeout message is sent to client side.
I wasn't able to reproduce this behavior with http2 (I'm guessing http2 would rely on RST_STREAM for this kind of behavior), so I've only handled this for http1.
**Modifications**
- Add a check for `Connection: close`, `status code: 408` in `client/Http1ResponseDecoder` when reading headers.

Handle request timeout correctly for HTTP

---

core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
core/src/test/java/com/linecorp/armeria/server/HttpServerConnectMethodTest.java

Motivation:
When translating HTTP/2 headers to HTTP/1 headers,
Armeria removes the disallowed list from the headers.
For example, `"Connection"` is prohibited to use in HTTP/2
https://tools.ietf.org/html/rfc7540#section-8.1.2.2
A "Connection: close" header specified for closing a connection is removed by the filter.
https://github.com/line/armeria/blob/32eabd2eb1f1be73f03a6425fa193631064cf2db/core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java#L156
As a result, the client releases the inactive connection to the pool,
though the connection is closed by the server.
Modifications:
- Destroy `KeepAliveHandler` on a failed request so that
a "Connection: close" header correctly is included in the response headers.
Result:
Armeria server now correctly sends `"Connection: …

Correctly sends "Connection: close" header on disallowed HTTP/1 requests

---

.github/workflows/actions_build.yml
consul/src/test/java/com/linecorp/armeria/client/consul/ConsulEndpointGroupTest.java
consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
consul/src/test/java/com/linecorp/armeria/server/consul/ConsulUpdatingListenerTest.java
core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java
core/src/test/java/com/linecorp/armeria/client/DnsTimeoutUtil.java
core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceDiscoveryCompatibilityTest.java

Motivation:
- A server is restarted in a consul test.
The restart could be failed because the port bound to the server
could be acquired by the socket.
```
ConsulEndpointGroupTest > testConsulEndpointGroupWithUrl() FAILED
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:88)
at com.linecorp.armeria.client.consul.ConsulEndpointGroupTest.testConsulEndpointGroupWithUrl(ConsulEndpointGroupTest.java:108)
Caused by:
io.netty.channel.unix.Errors$NativeIoException: bind(..) …
```

Clean up flaky tests

---

.github/workflows/actions_build.yml
consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java
core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
core/src/test/java/com/linecorp/armeria/server/management/ManagementServiceTest.java
examples/server-sent-events/src/main/java/example/armeria/server/sse/Main.java
examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
gradle/scripts/lib/common-git.gradle
thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceExternalClientUsageTest.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java

Motivation:
I thought #3511 was fixed by the previous PR(#3515).
However, it is reproduced with a different error.
Let's say that a `Publisher` is created from `Flux.interval(1000)...`.
A `Subscriber` should drain an item within a second.
If `Subscriber` could not consume the produced item, the `Publisher` 
will complete the stream with an `OverflowException`. 
https://stackoverflow.com/questions/60077245/project-reactor-how-to-handle-overflowexception-from-flux-interval
It is possible when an event loop is hard to take CPU cycles.
Modifications:
- GitHub Actions
- Use macOS for JaCoCo coverage
- JaCoCo failed to run with self-hosted runner.
- Reduce max-workers from 4 to 2 for stable builds on non self-hoshed runners.
- `MainTest`
- Add `onBackpressureDrop()` to the `Flux` to avoid an …

Clean up flaky tests (3rd round)

---

core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt

Motivation:
A `PathAndQuery` is stored into a cache even though it was already cached.
The `put` operation consumes meaningless CPU cycles.
https://github.com/line/armeria/blob/dbfc1cdbbacb7c15d8128b5b40972de28a82930e/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L432-L43://github.com/line/armeria/blob/dbfc1cdbbacb7c15d8128b5b40972de28a82930e/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L432-L434
We don't need to store it again it was cached.
Modifications:
- Add `cached` flag to check the cache status
Result:
Better CPU usage

Avoid unnesssary put operations for `PathAndQuery`

---

spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java

We didn't have code completion for `armeria.ssl`, so I added it.
before
after

Add code completion for armeria.ssl

---

core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcRetryWithCircuitBreakerTest.java

Motivation:
`DefaultRequestLog.propagateResponseSideLog()` did not propagate a response trailers to its parent.
It could cause not to complete a response if a `CircuitBreakerClient` with `CircuitBreakerRuleWithContent` wraps a `RetryingClient` with `RetryRuleWithContent`.
```java
RetryRuleWithContent<HttpResponse> retryRuleWithContent = ...;
CircuitBreakerRuleWithContent<HttpResponse> cbRuleWithContent = ...;
Clients.builder(server.uri(SessionProtocol.HTTP, GrpcSerializationFormats.PROTO))
.decorator(LoggingClient.newDecorator())
.decorator(RetryingClient.newDecorator(retryRuleWithContent))
.decorator(CircuitBreakerClient.newDecorator(circuitBreaker, cbRuleWithContent))
.build(TestServiceBlockingStub.class);
```
Because a `CircuitBreakeerClient` waits for the parent's response trailers …

Propagate the response tailers of a child log to the parent log

---

spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationSecureTest.java
spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/PrometheusMetricExposureTest.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationDisabledTest.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaGracefulShutdownConfigurationTest.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSslConfigurationTest.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortHttpsTest.java

Found maybe using unexpected class for loading ApplicationContext when checking flaky test. (This doesn't fix the flaky test I think, just make the code using correct class)
* Change package name of Configuration class importing
* Remove durplicate `OkService`

Fix spring boot test using wrong TestConfiguration class for loading ApplicationContext

---

core/src/main/java/com/linecorp/armeria/common/DefaultRpcRequest.java
core/src/main/java/com/linecorp/armeria/common/RpcRequest.java
core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
core/src/main/java/com/linecorp/armeria/internal/common/util/ServiceNamingUtil.java
core/src/main/java/com/linecorp/armeria/server/ServiceNaming.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcLogUtil.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/HandlerRegistry.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java

…full method name on demand
Motivation:
A service name and method name are extracted from a full method name for every request.
It consumes a few CPU cycles. 😆
Actually, the service names and their method names are good to cache because they are not changed at all.
Modifications:
- Add `serviceName()` to `RpcRequest` in addition to `serviceType()`
- Add some fatory methods taking a service name to `RpcRequest`.
- Early build simple method names and reuse them for better performance
- Remove `ServiceNamingUtil.fullTypeRpcServiceName()` in favor of `RpcRequest.serviceName()`
Result:
Optimized code and slightly better performance

Use a precomputed serviceName and method name instead of splitting a full method name on demand

---

core/src/main/java/com/linecorp/armeria/server/ServerConfig.java

Motivation:
If users do not specify a virtual host, we don't have to check the domain mapping.
Because it should always be served by the default virtual host.
Modifications:
- If virtual hosts are not specified, return `defaultVirtualHost` directly without additional looking up.
Result:
Better performance

Skip to check wildcard domains when no virtual host is used.

---

benchmarks/README.md
benchmarks/build.gradle
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
dependencies.yml

- me.champeau.gradle.jmh-gradle-plugin:0.5.0 -> me.champeau.jmh.jmh-gradle-plugin:0.6.4
- `jmh.include` has been replaced with `jmh.includes`
- Please use `-Pjmh.includes=<regex>` instead

Upgrade jmh-gradle-plugin to 0.6.4

---

benchmarks/src/jmh/java/com/linecorp/armeria/internal/server/annotation/MethodInvokerBenchmark.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java

- Modified AnnotatedService to use MethodHandle to invoke target annotated method
- Added MethodInvokerBenchmark to confirm performance gains

AnnotatedService to use MethodHandle in place of java.lang.reflect.Method

---

examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/HelloConfiguration.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/MetricCollectingConfigurator.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/MetricCollectingServiceConfigurator.java
spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
spring/boot2-webflux-autoconfigure/build.gradle
spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java

This PR relates to https://github.com/line/armeria/pull/3410
- Currently the custom success function is not compatible with ArmeriaAutoConfiguration, so allow users to configure it by defining a `@Bean` returning a MetricCollectingConfigurator.
- Added a `MetricCollectingConfigurator`
- Cleanup `HelloConfiguration.java`, remove the `MetricCollectingService` decorator, since its incompatible with ArmeriaAutoConfiguration, and we also don't have meter registries in the minimal example project.
- Added a unit test in `ArmeriaAutoConfigurationTest`

Allow users to specify metric success function with ArmeriaAutoConfiguration

---

core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
core/src/test/java/com/linecorp/armeria/internal/common/CancellationSchedulerTest.java

Motivation:
A `NullPointerException` could be raised by `CancellationScheduler`
if a callback of `whenCancelling()` calls `clearTimeout(false)` twice.
```java
cancellationScheduler.whenCancelling().thenRun(() -> {
scheduler.clearTimeout(false);
scheduler.clearTimeout(false);
});
```
- When a request is about to time out, a scheduler executes `invokeTask()`.
The current state is `SCHEDULED` at that moment.
- `whenCancelling()` is completed and its callbacks are executed.
- When the first `clearTimeout(false)` is invoked:
- `scheduledFuture` cannot be cancelled. Because `invokeTask()` is running.
- `scheduledFuture` is set to null, but it does not change the status.
Since scheduledFuture is executed already.
- When the second `clearTimeout(false)` is invoked:
- It tries to access …

Fix `NullPointerException` in `CancellationScheduler`

---

core/src/main/java/com/linecorp/armeria/client/WebClientRequestPreparation.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/client/WebClientRequestPreparationTest.java

Motivation:
`WebClientRequestPreparation` has `responseTimeout()` but not
`maxResponseLength()`.
Modifications:
- Added `WebClientRequestPreparation.maxResponseLength()`
Result:
- Convenience

Add `WebClientRequestPreparation.maxResponseLength()`

---

core/src/main/java/com/linecorp/armeria/common/annotation/NonNullByDefault.java

Motivation:
Kotlin 1.5 supports nullability annotations with the `TYPE_USE` target:
- Arrays
- Varargs
- Fields
- Type parameters and their bounds
- Type arguments of base classes and interfaces
See https://kotlinlang.org/docs/whatsnew15.html#improvements-to-handling-nullability-annotations
Armeria does not return a collection or array containing null values.
Therefore, we could apply `TYPE_USE` target globally for letting users type-safely access
values without the platform type(`!`).
For example:
```kotlin
// Copmile
val forwarded: MutableList<String> = headers.getAll(HttpHeaderNames.FORWARDED)
// Not compile: "Kotlin: Type mismatch: inferred type is (Mutable)List<String> but MutableList<String?> was expected"
val forwarded: MutableList<String?> = …
```

Add `ElementType.TYPE_USE` to `NonNullByDefault`

---

core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
core/src/test/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceTest.java

Motivation:
- #3551 Should not swallow server errors of `TransientService`
Modifications:
- Log response in case of server error regardless of `TransientServiceOption`.
- Modify verifications of `HealthCheckServiceTest` and `PrometheusExpositionServiceTest` as they are `TransientService`s.
Result:
- Leave a log for a failed request(5xx Server Error) even though the request is served by `TransientService`.
- Close #3551

Do not swallow server errors of `TransientService`

---

core/src/main/java/com/linecorp/armeria/internal/common/util/ServiceNamingUtil.java
core/src/main/java/com/linecorp/armeria/server/ServiceNaming.java
core/src/main/java/com/linecorp/armeria/server/SimpleTypeServiceNaming.java
core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
core/src/test/java/com/linecorp/armeria/server/logging/AnnotatedServiceLogNameTest.java

Motivation:
- Even if trailing dollar signs had been stripped by https://github.com/line/armeria/pull/3468#discussion_r619992030, it was only applied to `ServiceNaming.simpleTypeName()`.
- For consistency, it seems better to apply `ServiceNaming.fullTypeName()` and `ServiceNaming.shorten()` also.
Modifications:
- Add tests related `ServiceNaming.fullTypeName()` and `ServiceNaming.shorten()` to `ServiceNamingTest`.
- Add a test for `ServiceNaming.shorten()` to `AnnotatedServiceLogNameTest`.
- Introduce a utility to trim trailing dollar signs in `ServiceNamingUtil`.
Result:
- Trailing dollar signs are removed in `fullTypeName()`, `simpleTypeName()`, and `shorten()`.

Trim trailing dollar signs in `fullTypeName()` and `shorten()` of `ServiceNaming` for consistency

---

core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java

Motivation:
```
HttpServerRequestTimeoutTest > setRequestTimeoutAfterNoTimeout() FAILED
java.util.concurrent.CompletionException: com.linecorp.armeria.common.stream.ClosedStreamException: received a RST_STREAM frame: INTERNAL_ERROR
at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2108)
at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:88)
```
An `OverflowException` could be raised when using `Flux.interval(...)`
See #3525 for details
Modifications:
- Add `onBackpressureDrop()` where `Flux.interval()` is used to generate
a response content.
Result:
Fixes #3557

Fix flaky `HttpServerRequestTimeoutTest`

---

core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
core/src/test/java/com/linecorp/armeria/client/WebClientRequestPreparationTest.java

Motivation: Found small code can be cleanup when checking https://github.com/line/armeria/issues/3569 
Detail changes:
* `setTimeoutNanosFromNow0` always has `newTimeoutNanos > 0` if the caller is  `setTimeoutNanosFromNow` only.
* There is a `Math.max(1, timeoutNanos - passedTimeNanos0)` & `checkArgument(timeoutNanos > 0, "timeoutNanos: %s (expected: > 0)", timeoutNanos);`
* Make `eventLoop.execute` also reduce the delay time

Cleanup CancellationScheduler to provide more accurate timeout nanos

---

core/src/test/java/com/linecorp/armeria/server/ServiceRequestCancellationTest.java

Motivation:
```
ServiceRequestCancellationTest > [2] protocol=h2c FAILED
Expecting throwable message:
<null>
to contain:
<"received a RST_STREAM frame: CANCEL">
but did not.
Throwable that failed the check:
com.linecorp.armeria.common.ClosedSessionException
```
A test could see a `ctx` set by a previous test
Modifications:
- Set null to `ctxRef` after each test
Result:
- Clean up flakiness
- Fixes #3556

Fix flaky `ServiceRequestCancellationTest`

---

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
core/src/test/java/com/linecorp/armeria/common/HttpRequestSubscriberTest.java

Motivation: Current LoggingClient won't log the additional headers, we think it's the bug & HttpRequestSubscriber should update it with all merged headers
Modification:
* Change HttpRequestSubscriber to not just update the RequestLog with firstHeaders.
Result:
Fixes #3579

HttpRequestSubscriber should update RequestLogBuilder with all sent request headers

---

site/src/pages/release-notes/1.8.0.mdx

Micrometer [1.7.0](https://github.com/micrometer-metrics/micrometer/releases/tag/v1.7.0) requires Prometheus `simpleclient` 0.10.0 or later.
Unfortunately, there is a breaking change on meter names in `simpleclient` [0.10.0](https://github.com/prometheus/client_java/releases/tag/parent-0.10.0).
It would be worth mentioning the changes in the release note.

Add a notice for Micrometer 1.7.0 upgrade in 1.8.0

---

core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
core/src/main/java/com/linecorp/armeria/server/DefaultDecodedHttpRequest.java
core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/server/DefaultDecodedHttpRequestTest.java
core/src/test/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequestTest.java

Motivation:
`EmptyFixedStreamMessage` has a small memory footprint and it is
optmized for emtpy elements.  We can apply `EmptyFixedStreamMessage`
for an empty body request such as `GET`, `OPTION` and so on.
Modifications:
- Add `EmptyContentDecodedHttpRequest` for holding an `ReqeustHeaders` only.
- Make `DecodedHttpRequest` interface and rename the orignal
`DecodedHttpRequest` to `DefaultDecodedHttpRequest`
- Apply `EmptyContentDecodedHttpRequest` to `Http{1,2}RequestDecoder`
Benchmark Result:
- Workload: `wrk -t12 -c400 -d60s http://127.0.0.1:8080/foo`
- Results
- Master branch
```
Running 1m test @ http://127.0.0.1:8080/foo
12 threads and 400 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    13.59ms   29.49ms 375.99ms   87.99%
Req/Sec    12.62k     5.96k   52.48k …
```

Use `EmptyFixedHttpRequest` for an empty body request

---

benchmarks/src/jmh/java/com/linecorp/armeria/common/stream/StreamMessageBenchmark.java

**Motivation**
While running benchmarks, I found that running with `DefaultStreamMessage` on `noExecutor` fails consistently.
I'm guessing we need to wait until the close event is notified before performing the sum check
Failing benchmark command for master branch:
```
java -jar benchmarks/build/libs/armeria-benchmarks-1.8.1-SNAPSHOT-jmh.jar StreamMessageBenchmark.noExecutor -i 1 -wi 1 -f 1 -p flowControl=false -p num=20 -p streamType=DEFAULT_STREAM_MESSAGE
```
Failure logs
```
15:12:28.769 [com.linecorp.armeria.common.stream.StreamMessageBenchmark.noExecutor-1-1] WARN  c.l.a.c.s.StreamMessageBenchmark - Stream not completed
<failure>
java.lang.IllegalStateException: Did not compute the expected sum, the stream implementation is broken, expected: 190, got: -1
at …
```

Wait to close stream before proceeding in DefaultStreamMessage.noExecutor benchmark

---

core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java

Motivation:
Related #3485
When a user uses a Netty JAR without native libraries included, he or
she will see the following exception during the initialization phase:
```
java.lang.UnsatisfiedLinkError: ...
...
```
Modifications:
- Do not log when `Socket.initialize()` failed due to an `UnsatisfiedLinkError`.
Result:
- Less verboseness.

Do not log verbosely when Socket.initialize() fails (second).

---

site/README.md
site/src/components/code-block.tsx
site/src/pages/docs/advanced-client-interoperability.mdx
site/src/pages/docs/server-annotated-service.mdx
site/src/pages/docs/toc.json

This PR adds a `Client interoperability` page to `Advanced` section in the documentation. Specifically, it describes how to make Axios fully compatible with Armeria annotated services.

Add a 'Client interoperability' page to 'Advanced' section

---

core/src/main/java/com/linecorp/armeria/common/RpcResponse.java
thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/THttpServiceBuilderTest.java

Motivation:
Peel `RpcResponse` exception, to fix behavior where expected exception is returned as TException since it was wrapped in `CompletionException`. Clients of THttpService may receive a throwable wrapped in a `CompletionException` when using a DecoratingRpcService that throws an exception asynchronously
Modifications:
- peel exception in RpcResponse and THttpService#handleException()
Maybe related to https://github.com/line/armeria/pull/998 where we added peeling to `RpcResponse` but only in the case when `value instanceof RpcResponse`

Peel RPC response exception

---

.gitattributes
.github/workflows/public-suffixes.yml
core/build.gradle

Motivation:
Public Suffix List is automatically updated when building projects.
It should be inefficient to update the public_suffixes.txt on every PR.
Additionally, the unexpectedly updated file makes contributors embarrassed.
We've repeatedly explained why the file was changed to them. #3546
Modifications:
- Remove `PublicSuffixesTask` dependency from build phases.
- Add a GitHub Actions job that schedules to update the public suffix list 
every day.
Result:
- Improved build process and less noise in PR diffs
- Fixes #3546
Result:

Add a scheduled job that updates public suffix list periodically

---

core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/server/logging/AnnotatedServiceLogNameTest.java
examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/Main.kt
kotlin/src/main/java/com/linecorp/armeria/server/kotlin/CoroutineContextService.java
site/src/pages/docs/server-annotated-service.mdx

…d service
Motivation:
The global `defaultServiceNaming` should be applied to the annotated service
unless the service has its own policy.
Modifications:
- Remove setting the name of the annotated service as a default name in the `DefaultServiceConfigSetters`.
- The name of the annotated service will be used anyway if there's no `ServiceNaming` set.
- Remove the usage of deprecated `ServiceConfig.defaultServiceName()`.
Result:
- You can now set the service name of an annotated service using the global `defaultServiceNaming`.

Fix that the gloabl `defaultServiceNaming` is not applied to annotated services

---

core/src/test/java/com/linecorp/armeria/server/healthcheck/ScheduledHealthCheckerTest.java

Motivation: 
https://github.com/line/armeria/issues/3609
And scheduled task is using submit, we can't guarantee that it starts before server started 
Modification:
Using `await().untilAsserted` to guarantee the result.

Fix flaky ScheduledHealthCheckerTest.stopSchedulingAfterStop

---

.github/workflows/public-suffixes.yml

Motivation:
Currently, GitHub Actions scheduled job runs on all fork repo,
because of the lack of some secrets, the job is impossible to
succeed forever, causing noisy notifications. Also, the job is
not expected to be executed in fork repos I think.
Modifications:
- Add condition to the job to only run it when the current repo
is `line/armeria`.
Result:
- Schedule jobs are run on `line/armeria` repo only.

Do not run schedule task in fork repos

---

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java

#3623 
**Motivation**
- Users can expect even late subscriptions to be run on the executor specified
- For consistent behavior with `StreamMessage`s which will be introduced in the future

Notify late subscriber signals on the late subscriber's event loop

---

core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java

Motivation:
Currently, `CircuitBreakerClient` can wait for `RequestLogProperty.RESPONSE_TRAILERS`
depending on `CircuitBreakerRule`.
https://github.com/line/armeria/blob/7bf1873fa71766f1040a6581ed1dd0e3687b51a8/core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java#L295-L298
The `responseFuture` can be completed only when a trailers is received
from a remote peer. Even though a trailers was sent by a remote peer, it
cannot be passed to `RequestLog` since `InboundTrafficController`
prevents data from being read from a channel buffer when a large number of messages in
`DecodedHttpResponse` are not consumed by a `Subscriber`.
https://github.com/line/armeria/blob/6f21290a3e6e3bb2af22d8a9061d472dcabda545/core/src/main/java/com/linecorp/armeria/client/DecodedHttp …

Fix `CircuitBreakerClient` to return a `HttpResponse` immediately without waiting for headers or trailers

---

junit5/src/main/java/com/linecorp/armeria/testing/junit5/server/mock/MockWebServerExtension.java

This mock web server works fairly well even without JUnit5. Just one small problem with currently having to hackily call beforeTestExecution with a null object.
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3231/files#diff-a4b04a34d9795622c4a0d1e3f21f097e2d410937c17051ba6c7f16c8f7f34c26R62

Add a reset method to MockWebServerExtension for use outside JUnit5.

---

core/src/main/java/com/linecorp/armeria/server/AbstractBindingBuilder.java
core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java

Motivation:
I've missed adding Javadoc before merging the following PR:
https://github.com/line/armeria/pull/3562
Modifications:
- Add Javadoc to `AbstractBindingBuilder#exclude` and `RouteBuilder#exclude` methods.

Add Javadoc about path patterns

---

core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
core/src/test/java/com/linecorp/armeria/common/stream/AbortableSubscriberBlackboxTckTest.java
core/src/test/java/com/linecorp/armeria/common/stream/FilteredStreamMessageTest.java
core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java
core/src/test/java/com/linecorp/armeria/common/stream/SubscriptionOptionTest.java
spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerCompressionLeakTest.java

…reamMessage`
Motivation:
The implementations of `StreamMessage` in Armeria are in charge of releasing the pooled objects
when the subscriber subscribes without the `WITH_POOLED_OBJECTS` option.
However, `PublisherBasedStreamMessage` currentyly ignores `WITH_POOLED_OBJECTS` option.
We should respect that so that the subscriber does not have to deal with when it does not specify
`WITH_POOLED_OBJECTS` option.
Modifications:
- Respect `SubscriptionOption.WITH_POOLED_OBJECTS` in `PublisherBasedStreamMessage`.
- The Subscriber who does not specify `WITH_POOLED_OBJECTS` when subscribing does not have to release
the pooled objects by itself anymore.
Result:
- Close #3608
- You can use Spring WebFlux integration with compression enabled.
- You do not have to release the pooled objects when …

Respect `SubscriptionOption.WITH_POOLED_OBJECTS` in `PublisherBasedStreamMessage`

---

core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
core/src/test/java/com/linecorp/armeria/client/HttpClientFactoryTest.java

Motivation:
It's be nice if `ClientFactory` has `numConnections()` like `Server`,
so that a user can easily figure out how many connections it is managing.
Modifications:
- Add `Clientfactory.numConnections()`, get connection count from allChannels directly.
- Add test for multiple h1c request & multie servers
Result:
- Closes #3596

Add ClientFactory.numConnections()

---

.github/PULL_REQUEST_TEMPLATE.md
core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
site/src/pages/community/developer-guide.mdx

Motivation:
It will be nice if we provide the GitHub PR template.
Modifications:
- Add .github/PULL_REQUEST_TEMPLATE.md
Result:
- You can now easily write the PR description using this template.

Add PR template

---

spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java

Without error handling at this level, the response future is never touched and the request times out (giving a 503 with no log)
Closes #3633

#3633 Handle errors when invoking a WebOperation

---

core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
it/jackson-provider/src/test/java/com/linecorp/armeria/common/CustomJacksonModuleProvider.java

Motivation:
`LazyDynamicEndpointGroupTest.emptyEndpoint()` sometimes failed in CI
builds. #3381 It expects to fail the test with `EmptyEndpointException`,
however, it fails with `ClosedStreamException`.
After digging the issue, I find out that there is a race in `whenInitialized`.
If the `acquiredEventLoop.execute()` is executed immediately and completed earlier than
returning the method,
https://github.com/line/armeria/blob/d4880fe12690d2dafd2c5e7fa9f24c3b24837a00/core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java#L307-L309
the callbacks of `ctx.whenInitialized()` will be invoked before a `RequestLog`
is completed.
https://github.com/line/armeria/blob/207c5e038f59802dca769936a50e219a5fe308ea/grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaC …

Complete `DefaultClientRequestContext.whenIntialized()` after fully initializing a context

---

core/src/test/java/com/linecorp/armeria/common/multipart/MultipartDecoderTckTest.java
core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java

Motivation:
An empty `MultipartDecoder` may cause `MultipartDecoder.whenComplete()` to be
completed asynchronously because of the thread scheduling.
Modifications:
- Remove the custom implementation and include `MultipartDecoder` into
opened streams.
Result:
- Closes #3612
- Stable CI builds

Fix flaky `MultipartDecoderTckTest.required_completionFutureMustCompleteOnTermination0`

---

core/src/main/java12/com/linecorp/armeria/internal/common/package-info.java

Motivation:
Fix build failure
> [ant:checkstyle] [ERROR] /Users/kezhenxu94/workspace/armeria/core/src/main/java12/com/linecorp/armeria/internal/common/CurrentJavaVersionSpecific.java:1: Missing package-info.java file. [JavadocPackage]
Modifications:
- Add `package-info.java` in java12/com/linecorp/armeria/internal/common 
Result:
- Build successfully without error.

Add missing package-info.java for java12 package

---

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
core/src/test/java/com/linecorp/armeria/server/ConnectionLimitingHandlerIntegrationTest.java
grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java

Motivation:
It may be useful if a user can create a new event loop or blocking task executor that has the same life cycle with a `ClientFactory` or `Server`:
```java
ClientFactory
.builder()
.workerGroup(3)
.build()
Server
.builder()
.workerGroup(3)
.blockingTaskExecutor(10)
...
.build()
```
Modifications:
- Added `ClientFactoryBuilder.workerGroup(int)`
- Added `ServerBuilder.workerGroup(int)`
- Added `ServerBuilder.blockingTaskExecutor(int)`
Result:
- Closes #3597

Add shortcut methods that create event loops and blocking task executor thread pool

---

examples/grpc-scala/build.gradle
it/grpc/scala/build.gradle
scalapb/scalapb_2.12/build.gradle

Motivation:
After upgrading Gradle to 7.1, we frequently see compile errors on Scala projects:
```
> Task :it:grpc:scala:compileTestScala
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:25: object hello is not a member of package com.linecorp.armeria.grpc.scala
did you mean Hello?
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:26: object hello is not a member of package com.linecorp.armeria.grpc.scala
did you mean Hello?
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala:49: not found: type HelloServiceStub
[Error] /Users/ikhun/src/armeria/it/grpc/scala/src/test/scala/com/linecorp/armeria …
```

Disable incremental compile for Scala projects

---

core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
core/src/main/java/com/linecorp/armeria/common/MediaType.java
core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
core/src/main/java/com/linecorp/armeria/common/multipart/DefaultMultipart.java
core/src/main/java/com/linecorp/armeria/common/multipart/Multipart.java
core/src/main/java/com/linecorp/armeria/common/multipart/Multiparts.java
core/src/test/java/com/linecorp/armeria/common/multipart/MultipartIntegrationTest.java

Motivation:
- Fix a bug found (duplicate 'content-type' header insertion, when 'content-type' header already present in RequestHeaders)
- Extend Multipart to better support HttpResponse
- Add mode multipart types and headers to support broader multipart use cases
Modifications:
1) fixed DefaultMultipart for duplicate 'content-type' header insertion, when 'content-type' header already present in RequestHeaders;
2) added support for HttpResponse conversion (toHttpResponse() methods) to Multipart;
3) added multipart HttpResponse code samples and tests;
4) added more multipart mime types to MediaType:
- multipart/related (RFC 2112);
- multipart/mixed (RFC 1521);
- multipart/alternative (RFC 1521);
- multipart/parallel (RFC 1521);
- multipart/digest (RFC 1521);
- multipart/signed (RFC 1847);
- …

A set of fixes and enhancements for multipart package

---

.github/workflows/actions_build.yml

Motivation:
Sometimes we are missing checkstyle violations because we mistake the
checkstyle fails for flaky tests. It would be easy to check the
violations if we separately run the checkstyle job.
Modifications:
- Add checkstyle job to GitHub Actions builds
Result:
Easily see checkstyle violations.

Run checkstyle job independently

---

.github/workflows/actions_build.yml
consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java

Motivation:
An embedded Consul frequently fails to start in CI environment. #3514 #3231
It could be easy to check meaningful test failures by disabling Consol
tests from main builds. It could apply to other flaky tests.
Modifications:
- Disable Consul tests from the main builds by default and run them
separately.
- Run `ZooKeeperRegistrationTest.curatorRegistrationSpec()` only with `FLAKY_TESTS` flags.
Result:
Less noise in CI builds

Split flaky tests from the main CI builds

---

spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationServiceUtil.java

Motivation:
`org.springframework.boot.actuate.endpoint.OperationArgumentResolver`
has been added in Spring Boot 2.5. We should not use the class if it is not
in the classpath. `NoClassDefFoundError` will be raised when Spring Boot 2.4
is used.
```java
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/OperationArgumentResolver
at com.linecorp.armeria.spring.actuate.ArmeriaSpringActuatorAutoConfiguration.lambda$actuatorServerConfigurator$1(ArmeriaSpringActuatorAutoConfiguration.java:185)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
```
Modifications:
- Extract `acceptHeadersResolver()` to a separate class so that the
`OperationArgumentResolver` is lazily loaded only when it is in the
classpath.
Result:
- You no …

Make Spring integration compatible with Spring Boot 2.4

---

examples/annotated-http-service-kotlin/build.gradle.kts
examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/Main.kt
examples/annotated-http-service-kotlin/src/test/kotlin/example/armeria/server/annotated/kotlin/AnnotatedServiceTest.kt
examples/annotated-http-service/build.gradle
examples/annotated-http-service/src/main/java/example/armeria/server/annotated/Main.java
examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedServiceTest.java
examples/graphql/build.gradle
examples/graphql/src/main/java/example/armeria/server/graphql/Main.java
examples/graphql/src/test/java/example/armeria/server/graphql/GraphqlServiceTest.java
examples/grpc-kotlin/build.gradle.kts
examples/grpc-reactor/build.gradle
examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/Main.java
examples/grpc-reactor/src/test/java/example/armeria/grpc/reactor/HelloServiceTest.java
examples/grpc/build.gradle
examples/grpc/src/main/java/example/armeria/grpc/Main.java
examples/grpc/src/test/java/example/armeria/grpc/HelloServiceTest.java
examples/server-sent-events/build.gradle
examples/server-sent-events/src/main/java/example/armeria/server/sse/Main.java
examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
examples/static-files/build.gradle
examples/static-files/src/main/java/example/armeria/server/files/Main.java
examples/static-files/src/test/java/example/armeria/server/files/MainTest.java
examples/thrift/build.gradle
examples/thrift/src/main/java/example/armeria/thrift/Main.java
examples/thrift/src/test/java/example/armeria/thrift/HelloServiceTest.java

Motivation:
We manually create the `Server` in examples.
However, we have `ServerExtension` that manages the lifecycle of the server so it's better to use it.
Modification:
- Use `ServerExtension` in examples.
Result:
- Clean up

Use `ServerExtension` in examples

---

core/src/main/java/com/linecorp/armeria/internal/common/util/ChannelUtil.java
core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
core/src/test/java/com/linecorp/armeria/internal/common/util/ChannelUtilTest.java

Motivation:
We have to use integer value to set TCP_USER_TIMEOUT
https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollSocketChannelConfig.java#L110
Modification:
- Use integer instead of a long value.
Result:
- You no longer see `ClassCastException` when TCP_USER_TIMEOUT of `EpollChannelOption` and `IOUringChannelOption` are set

Fix type casting error when setting TCP_USER_TIMEOUT

---

core/src/main/java/com/linecorp/armeria/server/ServerPort.java
jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
site/src/pages/release-notes/1.9.1.mdx
testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerTest.java
testing-internal/src/main/webapp/index.jsp
tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java

Motivation:
Lots of Servlet applications try to get the `Host` header from a
`ServlerRequest`. When Armeria converts its HTTP/2 request to a Tomcat
or Jetty request, it currently simply skips `:authority` header.
Modifications:
- Made sure `:authority` header is converted to `host` header.
- Fixed a bug where `ServerPort.hasProtocol()` returns `false` when a
user specified `SessionProtocol.{H1,H2,H1C,H2C}`.
Result:
- Better Servlet compatibility.
- `ServerPort.hasProtocol(SessionProtocol)` doesn't return `false`
anymore when a user specifies `H1`, `H2`, `H1C` or `H2C`.

Convert `:authority` header to `host` header in `{Tomcat,Jetty}Service`

---

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageCollectingTest.java

Motivation:
`DecodedHttp{Request,Response}` removes an object from the inbound
traffic when `onRemoval()` is called. The current implementation of
`StreamMessage.collect()` in `DefaultStreamMessage` calls `onRemoval()`
when a stream is closed via `close()`. That means the inbound traffic
will be removed only after the messages of a stream are fully received.
Modifications:
- Immediately drain the objects from the `queue` of
`DefaultStreamMessage` whenever they are written to the `queue`
when `collect()` is called so that `onRemoval()` is called right away.
Result:
You no longer see a `ResponseTimeoutException` when collecting a large number of
message using `Http{Request,Response}.aggreagte()`.

Fix to call `onRemoval()` immediately when using `StreamMessage.collect()`

---

core/src/main/java/com/linecorp/armeria/internal/common/util/ChannelUtil.java
core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
core/src/main/java/com/linecorp/armeria/internal/server/annotation/KotlinUtil.java
grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/KotlinGrpcClientStubFactory.java
grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
reactor3/src/main/java/com/linecorp/armeria/common/reactor3/RequestContextHooks.java
spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ThriftServiceUtils.java

Motivation:
Armeria tries to load some classes in the dependencies using reflection.
This can cause a problem when a user shades the dependencies.
Modifications:
- Try to determine the class name dynamically when loading it in
runtime.
Result:
Armeria doesn't fail to load a class in shaded Netty, Thrift, Reactor or
even Armeria itself.

Make Armeria more resilient to shaded dependencies

---

benchmarks/build.gradle
benchmarks/src/jmh/java/com/linecorp/armeria/common/stream/StreamMessageBenchmark.java

Motivation:
1) When running `StreamMessageBenchmark`, a warning message is printed when `join()` is called from an event loop for `DefaultStreamMessage.whenCompleted()` (which is an `EventLoopCheckingFuture`)
```
java.lang.IllegalStateException: Blocking event loop, don't do this.
at com.linecorp.armeria.common.util.EventLoopCheckingFuture.maybeLogIfOnEventLoop(EventLoopCheckingFuture.java:103)
at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:87)
at com.linecorp.armeria.common.stream.StreamMessageBenchmark$StreamObjects.computedSum(StreamMessageBenchmark.java:109)
at com.linecorp.armeria.common.stream.StreamMessageBenchmark$StreamObjects.access$300(StreamMessageBenchmark.java:63)
at com.linecorp.armeria.common.stream.StreamMessageBenchmark.notJm …
```

Benchmark module fails to build jar due to missing dependency version

---

site/build.gradle

Motivation:
The public fields are not included by `ApiIndexTask`.
Modifications:
- Add `.field-details` to the CSS selector used for selecting public
APIs.
Result:
We can link public fields in the documentation.
For example:
```
<type://HttpStatus#NO_CONTENT>
```

Make public fields linked with documentation.

---

.github/workflows/actions_build.yml
site/build.gradle

Motivation:
It is difficult to check the result of site lint from the smoke test.
We can also improve the overall build speeds by splitting the site task.
Modifications:
- Add new site job build to GitHub Actions.
Result:
Easier to check site lint violations and faster build speed.

Run site job separately

---

jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
jetty9/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java

Motivation:
`JettyService` still has different behavior from Jetty in term of when
it raises an `EofException`. Jetty doesn't raise an `EofException` when
a handler attempts to write to a closed connection, while `JettyService`
does.
Modifications:
- `JettyService` doesn't raise an `EofException` anymore.
- Added test cases:
- An `EofException` is not raised when writing after timeout.
- An `EofException` is not raised when writing after disconnection.
- An `IOException` or `EofException` is raised when writing after a
handler closed its output stream on its own.
Result:
- Same behavior with Jetty when the request stream has been closed
unexpectedly.

Do not raise an `EofException` in `JettyService`

---

settings.gradle

Motivation:
Kotlin related modules are missing `kotlin` flags.
Modifications:
- Add `kotlin` flag
Result:
- Enables working with Kotlin in the examples module.

Add missed kotlin flag

---

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java

Motivation:
Recently, I found a new flaky test on `DefaultStreamMessage.collect()`:
https://github.com/line/armeria/runs/2978966336?check_suite_focus=true#step:7:1160
```
...
Caused by:
java.lang.IllegalArgumentException: expectedSize cannot be negative but was: -1
at com.linecorp.armeria.internal.shaded.guava.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:39)
at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.builderWithExpectedSize(ImmutableList.java:731)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.drainAll(DefaultStreamMessage.java:233)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.collectAll(DefaultStreamMessage.java:213)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$collect$1(DefaultStreamMessage …
```

Fix `DefaultStreamMessage.collect()` to collect elements using serialization loops

---

grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java

The original link in grpc-gateway has been moved to googleapis repo.

Fix a dead link of `code.proto` in `GrpcStatus`

---

core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
core/src/main/java/com/linecorp/armeria/common/stream/FuseableStreamMessage.java
core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
core/src/test/java/com/linecorp/armeria/common/RequestMapTest.java
core/src/test/java/com/linecorp/armeria/common/ResponseMapTest.java
core/src/test/java/com/linecorp/armeria/common/stream/FuseableStreamMessageTest.java

Motivation:
It would be useful to transform an error emitted by `StreamMessage`
into another.
Modifications:
- Add `StreamMessage.mapError()` that converts an error into another.
- Make `HttpRequest.mapError()` and `HttpResponse.mapError()` override
`StreamMessage.mapError()`.
- Refactor `FuseableStreamMessage` to handle error functions.
Result:
- You can now transform an error of `StreamMessage` into another using
a function.
```java
StreamMessage streamMessage = StreamMessage.aborted(ClosedStreamException.get());
StreamMessage transformed = streamMessage.mapError(ex -> {
if (ex instanceof ClosedStreamException) {
return new IllegalStateException(ex);
} else {
return ex;
}
});
```

Add `StreamMessage.mapError()`

---

.github/workflows/actions_build.yml
consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
core/build.gradle
gradle/scripts/lib/java.gradle
testing-internal/src/main/java/com/linecorp/armeria/internal/testing/FlakyTest.java
thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceDiscoveryCompatibilityTest.java
zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java

Motivation:
It is a hassle to add `assumeThat(..)` for excluding flaky tests.
It is also not a good way to exclude a whole class or its subclass.
For convenient sake, we can use JUnit5's `@Tag` annotation and filter in or out
using `includeTags` and `excludeTags`.
Modifications:
- Add `@FlakyTest` annotation to exclude a flaky test method or class
from the smoke test.
- Mark `GracefulShutdownIntegrationTest` as a flaky test.
Result:
Easy to maintain flaky tests

Exclude flaky tests using annotation
