line/armeria

- build.gradle
IntelliJ fails to compile example projects because of a wrong target
bytecode version. It marks the target bytecode of examples as Java 8.
We allow to use Java 11 for examples.
Modification:
- Set 11 to `sourceCompatibility` and `targetCompatibility` for examples
Result:
Compile Armeria project with IntelliJ built-in Java compiler
> Make examples Java 11 compatible with IntelliJ

- build.gradle
- dependencies.yml
Hello there! I'm using armeria in my Java project and I'm attempting to update my armeria version from 1.6.0 to the latest 1.9.2. While attempting to update I ran into a [linkage error](https://jlbp.dev/glossary.html#linkage-error). This problem is caused by #3640 which updated fastutil to 8.5.4. fastutil made a change to in 8.5.4 which restructured fastutil into multiple jars. armeria is missing one of the dependency jars and thus missing some fastutil classes. The fix is to add the dependency fastutil which includes the missing classes.
```
[ERROR] Linkage Checker rule found 6 reachable errors:
Class com.linecorp.armeria.internal.shaded.fastutil.booleans.BooleanConsumer is not found;
referenced by 2 class files
com.linecorp.armeria.internal.shaded.fastutil.booleans.BooleanIterable …
```
> Add fastutil dependency to fix fastutil linkage error

- core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleUtil.java
- core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
- core/src/test/java/com/linecorp/armeria/client/HttpResponseDecoderTest.java
- core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
Motivation:
`duplicator.duplicate()` should be called before the duplicator is closed.
However, when we combine two `RetryRuleWithContent`, we call `duplicator.duplicate()` for the second rule
after the duplicator is closed.
Modifications:
- Abort the duplicator after `duplicator.duplicate()` is called for the second retry rule.
- Use `AggreatedHttpResponse.toHttpResponse()` if the `HttpResponse` is already aggregated in `RetryingClient`.
Result:
- The second `RetryRuleWithContent` is now applied to decide to retry or not.
> Fix a bug that calls duplicator.duplicate() after the duplicator is closed

- core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
I found another exception that we missed catching when calling `Socket.initialize()`:
```
[main] DEBUG c.l.a.i.c.util.TransportTypeProvider - Failed to force-initialize 'io.netty.channel.unix.Socket':
java.lang.ClassNotFoundException: io.netty.channelio.netty.channel.unix.Socket
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:466)
at com.linecorp.armeria.internal.common.util.TransportTypeProvider.findClass(TransportTypeProvider.java:181)
at …
```
> Fix CNFE in TransportTypeProvider

- core/src/main/java/com/linecorp/armeria/client/GoAwayReceivedException.java
- core/src/main/java/com/linecorp/armeria/client/RefusedStreamException.java
- core/src/main/java/com/linecorp/armeria/client/ResponseCancellationException.java
- core/src/main/java/com/linecorp/armeria/client/ResponseTimeoutException.java
- core/src/main/java/com/linecorp/armeria/client/WriteTimeoutException.java
- core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java
- core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitTimeoutException.java
- core/src/main/java/com/linecorp/armeria/server/RequestCancellationException.java
- core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClientTest.java
Motivation:
We shouldn't use `RequestTimeoutExceptino` on the client side.
It would be nice if we introduce a new exception that is used when a request times out in `ConcurrencyLimitingClient`.
Modification:
- Add `ConcurrentLimitTimeoutException`.
Result:
- `ConcurrentLimitTimeoutException` is now raised when a request times out in `ConcurrentLimitingClient`.
> Introduce ConcurrentLimitTimeoutException

- core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
- grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcStatusFunction.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
- grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
- grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframer.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
- grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpDeframerTckTest.java
- grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcStatusMappingTest.java
- it/grpc/kotlin/src/test/kotlin/com/linecorp/armeria/grpc/kotlin/HelloServiceTest.kt
- it/grpc/reactor/src/test/java/com/linecorp/armeria/grpc/reactor/HelloServiceTest.java
- it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala
Motivation:
`GrpcStatusFunction` does not take a `RequestContext` as a argument.
It would be better to handle an exception with a `RequestContext`
because a `RequestContext` carries various information related to a
request. See #3692
Modifications:
- Breaking) Add `RequestContext` as the first argument of `GrpcStatusFunction`
```java
// Before:
GrpcService.builder()
.exceptionMapping((throwable, metadata) -> {
if (throwable instanceof IllegalArgumentException) {
return Status.INVALID_ARGUMENT;
}
return null;
});
// After:
GrpcService.builder()
.exceptionMapping((ctx, throwable, metadata) -> { // 👈👈👈
if (throwable instanceof IllegalArgumentException) {
return Status.INVALID_ARGUMENT;
}
return null;
});
```
Result:
- You can access a `RequestContext` from a `GrpcStatusFunction`.
- …
> Make `GrpcStatusFunction` access `RequestContext`

- core/src/main/java/com/linecorp/armeria/common/util/BlockingTaskExecutor.java
- core/src/main/java/com/linecorp/armeria/common/util/BlockingTaskExecutorBuilder.java
- core/src/main/java/com/linecorp/armeria/common/util/DefaultBlockingTaskExecutor.java
- core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
- core/src/test/java/com/linecorp/armeria/common/util/BlockingTaskExecutorBuilderTest.java
Motivation:
After #3389, `allowCoreThreadTimeout` option has disappeared.
For that reason, the number of waiting threads has increased.
Modifications:
- Automatically enable `allowCoreThreadTimeout` option if `keepAliveTime`
is enabled.
Result:
`BlockingTaskExecutor`'s idle threads will now be terminated after timeout again.
> Automatically enable `allowCoreThreadTimeout` option if `keepAliveTime`   is enabled in `BlockingTaskExecutor`

- core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
Motivation:
If a `FixedStreamMessage` is aborted while being subscribed,
a `NullPointerException` could be raised the following condition.
1. A `executor` was set, so `FixedStreamMessage` regards this stream as subscribed.
https://github.com/line/armeria/blob/3588a5167689a4419d6018326db2d8e10f7b98c2/core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java#L300-L305
2. However, a `subscriber` will be set later in an event loop.
https://github.com/line/armeria/blob/3588a5167689a4419d6018326db2d8e10f7b98c2/core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java#L116-L127
Modifications:
- Set `executor` after `subscriber` is set
- Abort late subscribers in the specified executor.
Result:
You no longer see a `NullPointException` when a `StreamMessage` …
> Fix `NullPointerException` in `FixedStreamMessage`

- core/src/main/java/com/linecorp/armeria/server/Server.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
- core/src/main/java/com/linecorp/armeria/server/ServerPort.java
- core/src/test/java/com/linecorp/armeria/server/ServerEphemeralLocalPortTest.java
Motivation:
`ServerBuilder.localPort()` currently binds only at the default loopback
address, which is one of `127.0.0.1` and `::1`. As a result, a client
that tries to connect to `127.0.0.1` or `::1` may get the 'connection
refused' error.
Modifications:
- Updated `ServerBuilder.localPort()` so it binds at both `127.0.0.1`
and `::1`.
- Updated `Server` to bind at the same port number for both `127.0.0.1`
and `::1` if a user specified the port number `0` with `localPort()`.
- However, a user will not see this behavior if a user specified the
ports with other methods such as `port()` and `http()`.
Result:
- Fixes #3725
> Bind both IPv4 and IPv6 loopback addresses in `ServerBuilder.localPort()`

- core/build.gradle
- core/src/main/java/com/linecorp/armeria/client/encoding/DecodingClientBuilder.java
- core/src/main/java/com/linecorp/armeria/common/encoding/AbstractStreamDecoder.java
- core/src/main/java/com/linecorp/armeria/common/encoding/BrotliStreamDecoder.java
- core/src/main/java/com/linecorp/armeria/common/encoding/StreamDecoderFactories.java
- core/src/main/java/com/linecorp/armeria/common/encoding/StreamDecoderFactory.java
- core/src/main/java/com/linecorp/armeria/common/encoding/ZlibStreamDecoder.java
- core/src/main/java/com/linecorp/armeria/server/encoding/DecodingService.java
- core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java
- core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncoders.java
- core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodingType.java
- core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
- core/src/test/java/com/linecorp/armeria/client/encoding/DecodingClientTest.java
- core/src/test/java/com/linecorp/armeria/client/logging/ContentPreviewingClientTest.java
- core/src/test/java/com/linecorp/armeria/common/encoding/BrotliStreamDecoderTest.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
- core/src/test/java/com/linecorp/armeria/server/encoding/DecodingServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/encoding/HttpEncodersTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
- gradle.properties
Motivation:
- #3544 
Modifications:
- Add `Brotli4j` in `core/build.gradle`.
- Add `BR` in `HttpEncodingType`.
- Modify `determineEncoding` to handle `br` properly.
- Change type of `getEncodingOutputStream` into `OutputStream` to cover `BrotliOutputStream`
TODO in this PR:
Result:
- Armeria can support Brotli compress.
- Closes #3544
> Add Brotli support in `EncodingService`

- grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
- grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/DeframedMessage.java
- grpc-protocol/src/main/java/com/linecorp/armeria/internal/client/grpc/protocol/InternalGrpcWebUtil.java
- grpc-protocol/src/main/java/com/linecorp/armeria/internal/client/grpc/protocol/package-info.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcWebTrailersExtractor.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClientTest.java
- it/grpcweb/build.gradle
- it/grpcweb/src/test/java/com/linecorp/armeria/server/grpc/protocol/UnaryGrpcWebServiceTest.java
Motivation:
#3638. `UnaryGrpcClient` only supports `gproto` currently. We could support `gproto-web` and `gproto-web-text` as well for better compatibility with frontends.
Modifications:
- Add support for `grpc-web` and `grpc-web-text` to `UnaryGrpcClient`.
- Moved `InternalGrpcWebUtil` from `com.linecorp.armeria.internal.client.grpc` to `com.linecorp.armeria.internal.client.grpc.protocol`.
Result:
- Closes #3638
- `UnaryGrpcClient` supports `gproto` currently. We could support `gproto-web` and `gproto-web-text`.
> Add support for grpc-web and grpc-web-text to the UnaryGrpcClient.

- .github/workflows/actions_build.yml
- gradle.properties
Motivation:
Our 'flaky-tests' job sometimes fails with the following error:
Expiring Daemon because JVM heap space is exhausted
It's somewhat unclear why this happens to only 'flaky-tests' job, but we
could work around this by adjusting the build parameters.
Modifications:
- Update the max JVM heap size of the Gradle daemon.
- Reduce the parallelism from 8 to 2 for 'flaky-tests'.
- Run `check` rather than `build` for 'flaky-tests'.
- Dump full thread dump when 'flaky-tests' is stuck.
Result:
- Closes #3742
> Reduce the resource consumption of flaky tests

- core/src/main/java/com/linecorp/armeria/internal/common/GracefulConnectionShutdownHandler.java
- core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
Motivation:
The `CompletableFuture` returned by `Server.stop/close()` is completed
when all accepted connections are closed. To get notified when an
accepted connection is closed, it listens to the Netty `ChannelPromise`
returned by `Channel.close()`.
In HTTP/2, the `ChannelPromise` returned by `Channel.close()` is
completed by `GracefulConnectionShutdownHandler`. However,
`GracefulConnectionShutdownHandler` can fail to complete the
`ChannelPromise` when the task scheduled by
`GracefulConnectionShutdownHandler` is cancelled before it completes the
`ChannelPromise`.
Modifications:
- Ensure the `ChannelPromise` is always completed when a connection is
closed.
- No need to pass around the promise anymore.
- Respect the return value of `drainFuture.cancel()`.
- Prefer …
> Fix a bug where `Server.stop/close()` never finishes

- core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithMetricsTest.java
Motivation:
`RequestLogBuilder.startRequest()` was not called for the child logs when `RetryingClient` is used.
Modification:
- Call `RequestLogBuilder.startRequest()` when creating a derived context.
Result:
- `requestDurationNanos`, `responseDurationNanos` and `totalDurationNanos` of a child log are properly calculated.
> Fix a bug that request start time is not set properly for child logs

- grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServerInterceptorTest.java
Motivation:
Add `GrpcServiceBuilder.intercept()` to allow that `io.grpc.ServerInterceptor` can directly be injected to `GrpcServiceBuilder` so that users don't have to wrap a gRPC service using `ServerInterceptors.intercept()` when adding the service.
Modifications:
- Add method `GrpcServiceBuilder.intercept()`.
Result:
- Closes #3694.
- `GrpcServiceBuilder` supports adding `ServerInterceptors` fluently.
> Add `GrpcServiceBuilder.intercept()` to inject interceptor fluently

- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
Motivation:
Sometimes, a user might want to suppress the warning message about
inconsistent or missing Netty versions emitted when loading the
`TransportTypeProvider` class.
Modifications:
- Added a new flag `warnNettyVersions` which is `true` by default.
- Added more details to the warning message:
- Why this message is showing up.
- How to turn the warning off.
Result:
- Closes #3572
> Add a flag that disables the Netty version warning

- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
- core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Motivation:
`RequestLog.toStringRequestOnly()` and `toStringResponseOnly()`
currently doesn't invalidate its cached string representation when a
user specified a different sanitizer function. This can lead to an
unintended leak of sensitive information when the string is cached with
a wrong sanitizer function. For example:
RequestLog log = ...;
String a = log.toStringRequestOnly();
String b = log.toStringRequestOnly(headersSanitizer, contentSanitizer);
assert !a.equals(b); // This fails currently.
Modifications:
- Kept the sanitizer functions used for generating the cached string.
- Invalidated the cache when the cached string was generated with
different sanitizer functions.
- `RequestLog.toString()` produces a tad bit prettier string when it has
children.
Result:
- No …
> Invalidate `RequestLog.toString*()` cache when sanitizer functions are different

- core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
- core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
- grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
- grpc-protocol/src/main/java/com/linecorp/armeria/internal/client/grpc/protocol/UnaryGrpcClientFactory.java
- grpc-protocol/src/main/java/com/linecorp/armeria/internal/client/grpc/protocol/UnaryGrpcClientFactoryProvider.java
- grpc-protocol/src/main/resources/META-INF/services/com.linecorp.armeria.client.ClientFactoryProvider
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClientTest.java
Motivation:
UnaryGrpcClient currently cannot be created using a standard client builder interface.
Modifications:
- Add UnaryGrpcClientFactory and UnaryGrpcClientFactoryProvider.
- Add `boolean isClientTypeSupported(Class<?> clientType)` method to `ClientFactory` interface to allow having multiple client factories for the same scheme - `DefaultClientFactory` uses it to resolve GrpcClientFactory or UnaryGrpcClientFactory for schemes supported by both client factories based on the provided client type.
Result:
- UnaryGrpcClient can be created using a standard client builder interface.
> Add client factory and provider for UnaryGrpcClient.

- core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java
Motivation:
Armeria currently uses `URI` to validate an HTTP/1 request path unlike
HTTP/2. `URI` has more strict validation rules than `PathAndQuery`, so a
client sending harmless yet illegal characters such as double quote
(`"`) will be rejected with a `400 Bad Request` response.
This behavior isn't really great in terms of user experience because:
- The validation behavior between HTTP/1 and 2 are different.
- A user cannot use harmless characters such as `"` when making a
request using a tool like `curl` and `telnet`.
Modifications:
- Do not use `URI` for request path validation.
- Simplify `ArmeriaHttpUtil`'s conversion logic because we don't accept
absolute URIs anyway.
Result:
- Armeria now accepts harmless yet illegal characters in a request path
for HTTP/1 connections, like it did …
> Relax overly-strict request path validation for HTTP/1

- spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
- spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java
- spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ByteBufLeakTest.java
- spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ErrorWebExceptionHandlerTest.java
Motivation
When using Spring Boot WebFlux integration, `ErrorWebExceptionHandler` is used to convert an exception to a response.
However, it's not working properly because `ArmeriaServerHttpResponse` sends the response headers first even before the actual response is made.
That makes `ErrorWebExceptionHandler` cannot convert the exception to a response because the response headers is already sent.
Modifications
- Make `ArmeriaServerHttpResponse` extend `AbstractServerHttpResponse` in WebFlux.
Result:
- `ErrorWebExceptionHandler` in WebFlux converts an exception to a response correctly.
> Fix a bug that ErrorWebExceptionHandler is not applied properly

- site/src/pages/tutorials/rest/blog/add-services-to-server.mdx
- site/src/pages/tutorials/rest/blog/implement-create.mdx
- site/src/pages/tutorials/rest/blog/implement-read.mdx
- site/src/pages/tutorials/rest/blog/implement-update.mdx
Motivation:
Modifications:
- Fix `implenment` typo to `implement`.
Result:
- Fix the REST tutorial documents link.
> Fix a typo of link in the REST tutorials

- core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/common/util/SystemInfo.java
- core/src/main/java/com/linecorp/armeria/internal/client/DnsUtil.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- core/src/test/java/com/linecorp/armeria/server/ServerEphemeralLocalPortTest.java
Motivation:
In an environment like a Docker container, it's pretty common that IPv6
is disabled completely. It's not enough to rely only on
`NetUtil.isIpV4StackPreferred()` in such a case.
Modifications:
- Added `SystemInfo.hasIpV6()`
- Moved `DnsUtil.anyInterfaceSupportsIpV6()` into `SystemInfo.HasIpV6`.
- Fixed a problem where `ServerEphemeralLocalPortTest` fails on a system
without IPv6 support at all.
Result:
- A user can now easily check if the system has a working IPv6 stack
using `SystemInfo.hasIpV6()`.
> Add `SystemInfo.hasIpV6()`

- core/src/main/java/com/linecorp/armeria/client/logging/ContentPreviewingClient.java
- core/src/main/java/com/linecorp/armeria/client/logging/ContentPreviewingClientBuilder.java
- core/src/main/java/com/linecorp/armeria/internal/logging/ContentPreviewingUtil.java
- core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java
- core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceBuilder.java
- core/src/test/java/com/linecorp/armeria/client/logging/ContentPreviewingClientTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
Motivation:
- #3791
Modifications:
- Add `ContentPreviewingClientBuilder` and `ContentPreviewingServiceBuilder`.
- Add `requestContentSanitizer` `BiFunction` which sanitizes request content preview if produced is not null.
- Add `responseContentSanitizer` `BiFunction` which sanitizes response content preview if produced is not null.
Result:
- Closes #3791
- Users can sanitize content preview of a request or response.
> Allow to sanitize request or response content preview

- benchmarks/build.gradle
- dependencies.yml
Motivation:
Since the version upgrade, running benchmarks with parameters results in the following exception
```
Execution failed for task ':benchmarks:jmh'.
> Error while evaluating property 'benchmarkParameters' of task ':benchmarks:jmh'
> Failed to calculate the value of task ':benchmarks:jmh' property 'benchmarkParameters'.
> Failed to query the value of extension 'jmh' property 'benchmarkParameters'.
> Cannot get the value of a property of type java.util.Map with value type org.gradle.api.provider.ListProperty as the source contains a value of type java.util.ArrayList.
```
Additionally, there was a bug in evaluating parameters which was addressed by the following PR
https://github.com/melix/jmh-gradle-plugin/pull/201
The fix has been published with version 0.6.6 (along with other …
> Fix a bug where benchmark parameters aren't respected

- benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
- core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
- core/src/main/java/com/linecorp/armeria/server/Server.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
- core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
- core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceBlockingPerRouteTest.java
- core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
- core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
Motivation:
`blockingTaskExecutor` is currently a server-level property. This pull request makes it possible to be configured per-route.
Modifications:
- Add a configuration option `blockingTaskExecutor` in `ServiceBindingBuilder`.
Result:
- Closes #3740.
- Users can specify a `blockingTaskExecutor` per-route:
```java
Server
.builder()
.route()
.get("/foo")
.blockingTaskExecutor(fooExecutor)
.build(fooService)
.route()
.get("/bar")
.blockingTaskExecutor(barExecutor)
.build(barService)
.build()
```
> Allow specifying different `blockingTaskExecutor` per route

- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
- it/grpc/kotlin/src/test/kotlin/com/linecorp/armeria/grpc/kotlin/HelloServiceTest.kt
Motivation:
gRPC-Kotlin cancels a call when a call is exceptionally completed.
https://github.com/grpc/grpc-kotlin/blob/b7d06483bf597cd4a10e3ed2ef52b21ca95c80ad/stub/src/main/java/io/grpc/kotlin/ClientCalls.kt#L318-L327
It triggers `ArmeriaClientCall.close()` recursively.
https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java#L287-L303
Modifications:
- Use `closed` flag to prevent a call from closing repeatedly.
Result:
- gRPC client calls are now closed exactly once.
- Fixes #3799
> Fix a bug where a gRPC client call is closed twice

- core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
- core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
- core/src/main/java/com/linecorp/armeria/client/ClientOptionsBuilder.java
- core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
- core/src/main/java/com/linecorp/armeria/common/auth/AuthToken.java
- core/src/main/java/com/linecorp/armeria/common/auth/BasicToken.java
- core/src/main/java/com/linecorp/armeria/common/auth/OAuth1aToken.java
- core/src/main/java/com/linecorp/armeria/common/auth/OAuth2Token.java
- core/src/main/java/com/linecorp/armeria/server/auth/BasicTokenExtractor.java
- core/src/main/java/com/linecorp/armeria/server/auth/OAuth1aTokenExtractor.java
- core/src/main/java/com/linecorp/armeria/server/auth/OAuth2TokenExtractor.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
- core/src/test/java/com/linecorp/armeria/common/auth/OAuth1aTokenTest.java
- core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/auth/BasicTokenTest.java
- core/src/test/java/com/linecorp/armeria/server/auth/OAuth2TokenTest.java
- eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
- eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
- eureka/src/test/java/com/linecorp/armeria/client/eureka/ArmeriaEurekaClientTest.java
- retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
Now we can only use the following way to add authorization to `HealthCheckedEndpointGroup`
```java
HealthCheckedEndpointGroup.builder(xx, xx)
.withClientOptions(it -> it.setHeader(
HttpHeaders.AUTHORIZATION,
BasicToken.of(username, password).asHeaderValue()
));
```
it'd be nice to have a builder method proposed in this patch.
- Add `auth` builder method to allow easily specify authorization token when health checking EndpointGroup.
- Users can use `HealthCheckedEndpointGroup.builder(xx, xx).auth()` to specify authorization in `HealthCheckedEndpointGroup`.
> Add `auth` builder method to `HealthCheckedEndpointGroupBuilder`

- core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerAdditionalHeadersTest.java
Motivation:
A request was failed, `HttpResponseSubscriber` did not merge the error
response with additional response headers / trailers.
Modifications:
- Merge response headers and trailers before writing a recovered
response.
Result:
You can now correctly send additional response headers and trailers
even if the request is failed.
> Fix a bug where additional headers are not sent when a request is failed.

- brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
Motivation:
I'm suspecting leak detection is running before the hook in BraveService completes.
The following `close` isn't being called
https://github.com/line/armeria/blob/8c45211dfcb631402fb58e4162fdb423af5a0f04/brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java#L110
at the point when leak detection is run
https://github.com/openzipkin/brave/blob/5be287b91c3d18da9fc7a597d71b12b27be6043c/brave-tests/src/main/java/brave/test/ITRemote.java#L164
I'm suspecting that the response is fully written 
https://github.com/line/armeria/blob/8c45211dfcb631402fb58e4162fdb423af5a0f04/brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java#L142
before the scope is actually closed
https://github.com/line/armeria/blob/8c45211dfcb631402fb58e4162fdb423af5a0f04/brave/src/ …
> Address flaky test BraveServiceIntegrationTest.childCompletesBeforeServer

- spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
- spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
- spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/PrometheusMetricExposureTest.java
Motivation:
`WebEndpointResponse` from an actuator response has the content type of the response, but we don't set it properly.
Modification:
- Respect the content type of the `WebEndpontResponse`.
Result:
- You no longer see a wrong content type from an actuator response header.
> Fix a bug that a wrong content type is set in an actuator reponse

- core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
- core/src/main/java/com/linecorp/armeria/internal/common/HttpHeadersUtil.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
- core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
- core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/InvalidResponseMetadataTest.java
Motivation:
Currently, pseudo request headers could be written as a response headers
that violates HTTP/2 specification.
https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.4
Modifications:
- Exclude pseudo request headers from response headers when converted to Netty headers.
Result:
You no longer see pseudo request headers in a response headers.
> Disallow pseudo request headers in response headers

- site/src/pages/docs/advanced-production-checklist.mdx
- site/src/pages/docs/advanced-saml.mdx
- site/src/pages/docs/client-decorator.mdx
- site/src/pages/docs/client-factory.mdx
- site/src/pages/docs/server-access-log.mdx
- site/src/pages/news/20210202-newsletter-2.mdx
- site/src/pages/release-notes/0.80.0.mdx
- site/src/pages/release-notes/0.86.0.mdx
- site/src/pages/release-notes/0.88.0.mdx
- site/src/pages/release-notes/0.91.0.mdx
- site/src/pages/release-notes/0.94.0.mdx
- site/src/pages/release-notes/0.95.0.mdx
- site/src/pages/release-notes/1.6.0.mdx
Motivation:
Trying to clean up several `*.mdx` pages.
Modifications:
- Several typo fixes in the docs.
- Several typo fixes in the release notes.
- Fix broken link on the `client-decorator.mdx` page.
Result:
- Link towards `/docs/advanced-structured-logging` on the `client-decorator.mdx` page works again.
- Cleaner documentation.
> Fix typos and broken link

- core/src/main/java/com/linecorp/armeria/common/MediaType.java
- core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
Motivation:
Add new media type constants as requested in #3680
Modifications:
- Added the `BROTLI` media type, linking to IETF RFC 7932 and with a content type of `application/brotli`
- Added the `ZSTD` media type, linking to IETF RFC 8478 and with a content type of `application/zstd`
Result:
- Closes #3680.
- Adds media type support for BROTLI & ZSTD.
> Add new media types

- grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/StatusCodes.java
- grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
- grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/protocol/StatusCodesTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnaryGrpcServiceTest.java
Motivation:
`AbstractUnsafeUnaryGrpcSerivce` and `AbstractUnaryGrpcService`
currently do not respect the status code and description a user
specified with `ArmeriaStatusException`.
Modifications:
- Now peeling the exception before checking the exception type.
- Added test cases
- Now using one callback instead of two for handling a unary gRPC call
for more efficiency.
- Added more constants to `StatusCodes`.
Result:
Throwing an `ArmeriaStatusException` now overrides the gRPC status code
and description as expected.
> Make `AbstractUnaryGrpcService` handle `ArmeriaStatusException` properly

- core/src/main/java/com/linecorp/armeria/server/annotation/decorator/CorsDecorator.java
- core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
- core/src/main/java/com/linecorp/armeria/server/cors/ChainedCorsPolicyBuilder.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicyBuilder.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
- core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
Motivation:
#3839 
Modifications:
- Add `allowAllRequestHeaders` to `CorsServiceBuilder` and `CorsPolicyBuilder`.
- Set `Access-Control-Allow-Headers` to be as same as `Access-Control-Request-Headers` if `allowAllRequestHeaders`.
Result:
- Closes #3839
- Users can allow all HTTP headers while not using wildcard.
> Support to allow all `Access-Control-Allow-Headers`

- core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java
- core/src/main/java/com/linecorp/armeria/client/limit/AsyncConcurrencyLimit.java
- core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimit.java
- core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitBuilder.java
- core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java
- core/src/main/java/com/linecorp/armeria/client/limit/ConditionalConcurrencyLimit.java
- core/src/main/java/com/linecorp/armeria/client/limit/Futures.java
- core/src/test/java/com/linecorp/armeria/client/limit/AsyncConcurrencyLimitTest.java
- core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClientTest.java
Motivation:
Implementation of a concurrency limiter based on an async semaphore-like structure. 
There is some code taken from the core netty on how to do this properly and performant
Modifications:
- Introduce ConcurrencyLimit (an AsyncSemaphore like implementation)
- Wire the default implementation in the main client to enforce the limit
Result:
- Closes #3478 
- The change does not modify the main interface so it should not impact users using it previously
> Issue-3478: concurrency limit with semaphore like implementation

- eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
Motivation:
If pass empty  appName to EurekaEndpointGroup by mistake. It would  pick `ApplicationConverter` as response  converter.
But the server return `applications` for path  '/apps/'.  A deserialization exception would be thrown.
Modifications:
- check args in builder.
Result:
- `EurekaEndpointGroupBuilder` now fails if an empty string is specified for `appName` and other parameters.
> Fail if an empty string is specified for EurekaEndpointGroupBuilder

- site/src/pages/docs/client-circuit-breaker.mdx
Motivation:
- Fix a bug in the site document.
- Use `CircuitBreakerListener.metricCollecting` because deprecated `MetricCollectingCircuitBreakerListener` has been no longer exposed. 
Modifications:
- Use `CircuitBreakerListener` instead of `MetricCollectingCircuitBreaker`
Result:
- Can see the following page <a href="https://armeria.dev/docs/client-circuit-breaker">here</a>
> Use CircuitBreakerListener.metricCollecting in side document

- site/src/pages/docs/client-retry.mdx
**Motivation**:
The javadoc hyperlink of `RetryRule` is broken on the [doc](https://armeria.dev/docs/client-retry#retryrule):
**Modifications**:
Changed `:api:RetryRule` to `<type://RetryRule>`.
**Result**:
The hyperlink of `RetryRule` works correctly.
> Update site doc client-retry.mdx

- grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java
- site/src/pages/docs/server-docservice.mdx
Motivation:
Currently, Armeria accepts `.dsc` file only as gRPC descriptor set.
However some user might want to use another filename such as `*.pb` or `*.bin`.
Modifications:
- Accept the following extensions from `GrpcDocStringExtractor` as gRPC descriptor set file.
- `.bin`
- `.desc`
- `.dsc`
- `.pb`
- `.protobin`
Result:
- `GrpcDocStringExtractor` now reads description from `bin`, `desc`, `dsc`, `pb`, and `protobin` file.
> Accept more file extensions from GrpcDocStringExtractor

- site/src/pages/community/developer-guide.mdx
Include JDK 16 for developing Armeria.
> Update JDK version to 16 in the developer guide

- core/src/main/java/com/linecorp/armeria/client/encoding/DecodingClient.java
- core/src/test/java/com/linecorp/armeria/client/encoding/DecodingClientTest.java
Motivation:
Currently, it's possible to add duplicated encodings (e.g gzip, deflate) in the request headers, either with `HttpRequestBuilder` or with `RequestHeadersBuilder`. But `DecodingClient`  doesn't accept duplicated values (more specifically, guava's `ImmutableMap` doesn't accept duplicated keys), and throws an exception.
Modifications:
Use an `ImmutableSet` instead of an `ImmutableList` when getting the encodings from the request, which dedups the values.
Result:
- `DecodingClient` does not raise an exception anymore when duplicated encodings are specified.
- They are silently ignored.
> DecodingClient - accept duplicated encoding values

- docs-client/src/containers/MethodPage/DebugPage.tsx
While testing an annotated service that accepts parameters from an HTTP query string, I noticed that the value is not correctly cleared when the form input is empty.
1. Specify `foo=bar` as the HTTP query string
2. Request will be sent to `/hello?foo=bar`
3. Clear the text field
4. Requests are still sent to `/hello?foo=bar`
- Clear the `queries` and `headers` fields in `onSubmit()` if the form input is empty
- `queries` and `headers` fields are now correctly cleared when we empty the input form in DocService.
> Correctly clear HTTP query string and headers in DocService

- docs-client/src/components/VariableList/index.tsx
Motivation:
DocService shows docString as a single-line string until now, so users cannot format their docString.
Modifications:
- Add `<pre>` tag to docString.
Result:
- The sentences in the description sections are now correctly rendered in DocService.
> DocService shows multiline docString

- core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
- core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
Motivation:
https://github.com/line/armeria/pull/3908#discussion_r743448825
Once a request reaches `HttpSessionHandler#invoke`
https://github.com/line/armeria/blob/d39c8f5719d7de7eef26df37917cc2df786b5b53/core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java#L169
`HttpResponseDecoder.unfinishedResponses` hae been incremented from either of the three following locations:
1. https://github.com/line/armeria/blob/d39c8f5719d7de7eef26df37917cc2df786b5b53/core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java#L276
2. https://github.com/line/armeria/blob/d39c8f5719d7de7eef26df37917cc2df786b5b53/core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java#L788
3. https://github.com/line/armeria/blob/d39c8f5719d7de7eef26df37917cc2df786b5b53/core/src/main/java/co …
> Fix the case where `unfinishedResponses` isn't decremented on early abort

- graphql-protocol/src/main/java/com/linecorp/armeria/internal/server/graphql/protocol/GraphqlUtil.java
- graphql-protocol/src/test/java/com/linecorp/armeria/internal/server/graphql/protocol/GraphqlUtilTest.java
Motivation:
If `accept` is a wildcard in GraphqlService it won't work.
Modifications:
- Fix `GraphqlUtil`
Result:
- Fix bug
> Fix bug for accept wildcard case in `GraphqlService`

- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
- core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerProtocolViolationTest.java
Motivation:
If a protocol violation is triggered after initialization of a request
context:
1. The associated request is also closed with the violation cause.
https://github.com/line/armeria/blob/117a21e17ec9e30b0c3c2d74d16fdde3cab62434/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L239-L240
2. The cause closing the request will be converted into a `HttpResponse` by
the default `ServerErrorHandler`.
https://github.com/line/armeria/blob/117a21e17ec9e30b0c3c2d74d16fdde3cab62434/core/src/main/java/com/linecorp/armeria/server/DefaultServerErrorHandler.java#L95-L95
3. An `HttpResponseSubscriber` subscribes to `HttpResponse` and tries to
write on a wire even though the response headers for protocol violation
was written already.
In addition to the duplicate headers …
> Fix a bug where protocol violation errors trigger duplicate headers writes

- core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
- core/src/main/java/com/linecorp/armeria/internal/client/endpoint/StaticEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/internal/client/endpoint/package-info.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/LazyDynamicEndpointGroupTest.java
Motivation:
Although, #3876 addressed `java.lang.IllegalStateException: Should call
init(endpoint) before invoking this method` in 1.13.0, we still got a report the
problem from [Armeria Slack](https://line-armeria.slack.com/archives/C1NGPBUH2/p1637622827071100).
The problem could occur if the following two conditions are met:
1) `EndpointGroup` was resolved and has non-empty endpoints when creating an `ArmeriaClientCall`.
https://github.com/line/armeria/blob/c21a88ff59daa2101712a8e1da41a6281f2c0878/grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java#L173
2) The endpoints in the `EndpointGroup` become empty somehow when the ArmeriaClientCall initializes `ClientRequestContext`.
https://github.com/line/armeria/blob/d78b52f3bc62ed1c4f5037f092ea1f514156d880/core …
> Make sure to start a gRPC client call after the initialization of an `Endpoint`

- core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java
- core/src/main/java/com/linecorp/armeria/server/Server.java
- core/src/test/java/com/linecorp/armeria/common/util/StartStopSupportTest.java
- core/src/test/java/com/linecorp/armeria/server/ServerListenerTest.java
Motivation:
In our javadoc, it is stated that if `ServerListener#serverStarting` throws an exception `Server` startup is aborted.
https://github.com/line/armeria/blob/43bd08248ba86ab5942f781da33b11a42fe3b1a5/core/src/main/java/com/linecorp/armeria/server/ServerListener.java#L34-L37
However, this behavior currently isn't supported since the introduction of `StartStopSupport`.
Additionally, we have verified that this is still a valid use case. (i.e. users may want to do some validation before proceeding with server startup)
Modifications:
I think it is difficult to cleanly decouple the behavior of `StartStopSupport` and `Server` without breaking changes (see 580560de57c77755300460c3aeccd540366148bf for the attempt). I also think it is acceptable for `StartStopSupport` to support the …
> Abort server startup if `ServerListener.serverStarting` throws an exception 

- core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
- core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
- core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
- core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextTest.java
**Related Issue** #3955
Currently, we support `pathParams`, `pathParam` on `ServiceRequestContext`.
So it seems good to support `queryParams`, `queryParam` too.
- Add `queryParams`, `queryParam` on `ServiceRequestContext`.
- You can now use `queryParams` to get `QueryParams` on `ServiceRequestContext`.
- Close #3955 issue
> Add `queryParams()` to `ServiceRequestContext`

- site/src/components/steps.tsx
Motivation:
With the upcoming addition of gRPC tutorial, the stepper in the REST tutorial displays steps of the gRPC tutorial as well.
Modifications:
- Check the parent directory of the tutorial page and compose a stepper of sibling pages only.
Result:
- The stepper shows steps of the sibling pages only. (i.e. REST tutorial steps only on REST tutorial pages, gRPC tutorials steps only on gRPC tutorial pages)
> Limit steps for composing a tutorial stepper

- core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java
- core/src/test/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceTest.java
Motivation:
- I saw some of my service has few MB of exported response. Maybe better to make it ~async~ and not converting to single `byte[]`
Modifications:
- Using ByteArrayOutputStream and HttpData.wrap
Result:
- Avoid creating single large `byte[]` explicitly. Especially if `ctx.alloc` uses direct buffer.
- ~Reduce the chance of blocking request executor. e.g. `JvmThreadMetrics#getThreadStateCount` is using `ThreadMXBean#getThreadInfo` and it's might be an expensive operation.  (maybe not that impact)~
> Change Prometheus exporter's ByteArrayOutputStream to ByteBufOutputStream

- core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java
- core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContent.java
- thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Motivation:
- #2899
- #3875
Modifications:
- Add more shortcuts for `RetryRule` which accept `Backoff`.
- Add more shortcuts for `RetryRuleWithContent`.
Result:
- Closes #2899
- Closes #3875
- Users may conveniently create a `RetryRule` with their specific `Backoff`.
- Users may conveniently create a `RetryRuleWithContent`.
> Add more shortcuts for `RetryRule` and `RetryRuleWithContent`

- grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
- grpc/src/test/java/com/linecorp/armeria/internal/client/grpc/CustomGrpcClientFactoryTest.java
Motivation:
Users are able to add `ClientInterceptors` using upstream gRPC's API after a client stub is created.
it would be convenient to fluently add `ClientInterceptor` using `GrpcClientOptions`.
Modifications:
- Add `INTERCEPTORS` to `GrpcClientOptions` as a static field.
- Create a new Channel that will call interceptors before starting a call on the given `ArmeriaChannel` in `GrpcClientFactory#newClient`.
Result:
- Closes #3964
- Set gRPC's `ClientInterceptor` using `GrpcClientOptions`
```java
// Don't need to mutate the created client stub anymore
final HelloServiceStub helloService = 
Clients.builder(grpcUri)
.option(GrpcClientOptions.INTERCEPTORS.newValue(List.of(myInterceptor1, myInterceptor2))
.build(HelloServiceStub.class);
```
> Provide a way to set a gRPC's ClientInterceptor using GrpcClientOptions

- core/src/main/java/com/linecorp/armeria/client/cookie/CookieClient.java
- core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
- core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
- core/src/main/java/com/linecorp/armeria/common/stream/FuseableStreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/ResponsePeekTest.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessagePeekTest.java
- thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpHeaderTest.java
**Related Issue** #3097
Currently, we support `mapHeaders`, `mapData`, `mapTrailer`, `mapError` operators at #3624 #3668
So it seems good to support `peek*` operators too.
- Add `peek` operator on `StreamMessage`
- Add `peekHeaders` operator on `HttpResponse`
- Replace `mapHeaders` with `peekHeaders` where we don't modify headers
- You can now use `peekHeaders` to check headers on `HttpResponse`
> Add `StreamMessage.peek()`

- .github/workflows/public-suffixes.yml
GPG key for Armeria jobs has been changed.
Although the change has been added in https://github.com/line/armeria/pull/3933/files#diff-e653a7cb66998c21490ff4e6b23489e7a24f59114fa06056803ef6d0ae098ce3,
the PR still needs reviews.
Before merging the PR, this update will fix the consistent failures of https://github.com/line/armeria/actions/workflows/public-suffixes.yml.
> Update GPG passphrase for the `Public Suffix List` job

- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
Motivation:
I spent some time trying to figure out why I was getting `UNKNOWN` error from my grpc service.  After digging in the debugger, I found it was due to an exception that this warning message logs about.  However, because the exception itself is not logged, it is hard to figure out what's going on.
By adding an exception to this warning message, we will make it easier for people to figure out the cause of `UNKNOWN` errors.
Modifications:
- Simply added throwable as second argument to `logger.warning` call
Result:
Should make it easier to debug.
> Add exception to warning log in FramedGrpcService.

- site/src/pages/community/articles.mdx
Motivation:
Add a new japanese conference video. 
I made a presentation about Armeria integration of LINE STORE at the Japanese conference, [Spring Fest 2021](https://springfest2021.springframework.jp/) this month, and then the youtube video is posted. 
I would like to share it as the community slide and video.
Modifications:
- Add a new `Article` tag for it.
Result:
- The `Article` is shown in the following image.
> Add a new japanese conference video

- core/src/main/java/com/linecorp/armeria/common/ClientCookieDecoder.java
- core/src/test/java/com/linecorp/armeria/common/ClientCookieDecoderTest.java
- core/src/test/java/com/linecorp/armeria/common/HttpHeaderCachedValuesTest.java
Motivation:
Handle `SameSite` attribute of `header` string and set it to decoded cookie.
Modifications:
- Add match condition with `SameSite` attribute and set value if the value is available.
- Replace `Cookie.of` to `Cookie.ofSecure` in test case because the replacement not work before due to missing `SameSite` attribute. ref: https://github.com/line/armeria/pull/3939
Result:
- Closes #3968. (If this resolves the issue.)
> Handle missing `SameSite` attribute in `ClientCookieDecoder`

- core/src/main/java/com/linecorp/armeria/common/stream/AsyncMapStreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/stream/AsyncMapStreamMessageTest.java
Motivation:
Currently StreamMessage allows modifying the stream with a synchronous operation via `map`. It would be useful to allow using an asynchronous operation in the same way.
Modifications:
- Add `AsyncMapStreamMessage` which uses an async function to modify the stream
- Add `StreamMessage.mapAsync()` to allow easily creating AsyncMapStreamMessage from an existing stream
Result:
- Closes #3916
- You can now use mapAsync on StreamMessage to modify a stream using an async operation
> Add mapAsync method to StreamMessage

- .github/workflows/actions_build.yml
- site/build.gradle
Armeria' `self-hosted` runners run on old Linux distributions.
We installed some native c libraries for building nodejs' c-binding modules.
Especially, `node_modules` in `site` needs newest native dependencies that ain't easy to install using `yum`.
`ubuntu-latest` managed by GitHub might be better for compatibility.
> Use GitHub managed runners to build site

- docs-client/src/containers/App/index.tsx
- docs-client/src/lib/specification.tsx
Motivation:
Users may have multiple services, messages and/or enums with the same names but the different package names. However, DocService currently shows only their simple names in the UI, so it is not easy to distinguish them.
Modifications:
- Make DocService show the package name of the services, messages and/or enums when finding name conflicts.
Result:
- Users now can see the package name of their services, messages and enums with the same names from DocService.
> Make DocService show fully qualified names when finding name conflicts

- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http2ServerUpgradeCodec.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerUpgradeHandler.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerUpgradeHandlerTest.java
- core/src/test/java12/com/linecorp/armeria/server/JavaHttpClientUpgradeTest.java
Motivation:
Netty's HttpServerUpgradeHandler fully aggregates a request to handle an
upgrade request. The maximum allowed length for aggregation is hard-coded
with 16384. If the payload size of an upgrade request is greater than 16384,
the request always fails. See #3859 for more information.
Modifications:
- Fork `HttpServerUpgradeHandler` and remove `HttpObjectAggregator` from
super class.
- Only see HTTP headers to upgrade HTTP/1.x requests.
- After upgrading, an outbound hander for HTTP/1 codec will be removed
and HTTP/2 codec will be promoted.
- HTTP/1 codec will be fully removed after receiving the entire request.
- Forked `Http2ServerUpgradeCodec` and de-generalized and optimized for
Armeria.
Result:
- You no longer see `413 Request Entity Too Large` when receiving a cleartext(h2c) …
> Revamp `HttpServerUpgradeHandler` for cleartext upgrade

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
Motivation:
When I use a wildcard type for parameter like as follows, `AnnotatedService` is failed to initialize due to `Unsupported or invalid parameter type: ?`:
```java
@Get("/wildcard")
public String wildcard(RequestContext ctx, @Param List<? extends Object> container) {
return ctx.path();
}
```
It'd be ok for Java users since they may not use like the above. However, for Kotlin, it isn't when they use an interface as a generic type. IMHO, this is because Kotlin changes the type to the upper-bounded wildcard type. This is the reproducible code:
```kotlin
class AnnotatedService {
@Get("/")
fun foo(@Param("values") values: List<MyInterface>): String {
return "Hello, $values!";
}
}
interface MyInterface
```
Modifications:
- Resolve `WildcardType` to get the first upper bound when getting …
> Resolve `WildcardType` to get upper bound

- junit5/src/main/java/com/linecorp/armeria/testing/server/ServiceRequestContextCaptor.java
Motivation:
In the example code, the code to create a `WebClient` is missing, so I fixed it.
Modifications:
- Added code to create `WebClient` in example code.
Result:
- This has no effect on the behavior of existing code.
> Fix Javadoc for explaining usage in `ServiceRequestContextCaptor`

- core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthChecker.java
Motivation:
`HealthChecker.of()` currently returns a `HealthChecker`, but the actual
implementation implements `ListenableHealthChecker`. It's better give a
clear signal to our users that it's listenable.
Modifications:
- Change the return type of `HealthChecker.of()` from `HealthChecker` to
`ListenableHealthChecker`.
Result:
- (Breaking) `HealthChecker.of()` now returns `ListenableHealthChecker`
instead of `HealthChecker`.
> Return `ListenableHealthChecker` instead of `HealthChecker` for `HealthChecker.of()`

- dependencies.yml
Motivation:
- To use latest versions of protobuf
- To those who use kotlin dsl (https://github.com/grpc/grpc-kotlin), it helps to get protobuf associated changes for that
Modifications:
- Upgrade version of grpc-bom to 1.43.2 , protobuf to 3.19.2
Result:
- grpc libraries upgraded to version 1.43.2
- protobuf libraries upgraded to version 3.19.2
> Upgrade version of grpc-bom to 1.43.2 and protobuf to 3.19.2

- core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java
- core/src/test/java/com/linecorp/armeria/server/ParameterizedPathMappingTest.java
Motivation:
Support "capture the rest pattern" `{*foo}` or `:*foo` for URI Variable Syntax.
Modifications:
- Add validation for capture the rest pattern.
- Retrieve parameter name and value with the capture rest pattern.
Result:
- Closes #3031. (If this resolves the issue.)
- Support one of the syntaxes reported in #3994
> Support capture the rest pattern `{*foo}` or `:*foo` for URI Variable Syntax

- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
- grpc/src/test/proto/com/linecorp/armeria/grpc/testing/transcoding.proto
Motivation:
Received a bug report from @wasifaleem
Modifications:
- Handle `google.protobuf.Struct, Value, ListValue, Any` as well-known messages
which are not acceptable as HTTP GET parameters
- Do not find inner fields from the messages
Result:
- Users can specify `google.protobuf.Struct, Value, ListValue, Any` messages from their `proto` files.
- Closes #3986
> Support google.protobuf.Struct/Any from HttpJsonTranscodingService

- core/src/main/java/com/linecorp/armeria/common/StreamMessageBasedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/common/StreamMessageBasedHttpResponse.java
- core/src/main/java/com/linecorp/armeria/internal/common/stream/NonOverridableStreamMessageWrapper.java
- core/src/test/java/com/linecorp/armeria/common/StreamMessageBasedHttpMessageTest.java
Motivation:
If a method is inherited by both `default` of a interface and a method in a super class,
a subclass chooses the method in the superclass as a target method. `toDuplicate()` 
in `StreamMessageBasedHttpRequest` and `StreamMessageBasedHttpResponse` are implemented
by both `StreamMessageWrapper` and `Http{Request,Response}`.
Since the chosen `StreamMessageWrapper.toDuplicator()` is delegated to the underlying `StreamMessage`,
https://github.com/line/armeria/blob/3588a5167689a4419d6018326db2d8e10f7b98c2/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java#L104-L106
`DefaultStreamMessageDuplicator` is returned by `StreamMessageBasedHttp{Request,Response}.toDuplicator()`
where `DefaultHttp{Request,Response}Duplicator` is expected.
See #4030 for details. …
> Fix a bug where `HttpResponse.toDuplicator()` raises `ClassCastException`

- core/src/main/java/com/linecorp/armeria/client/circuitbreaker/AbstractCircuitBreakerClient.java
- core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreaker.java
- core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java
- core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientIntegrationTest.java
- core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java
- core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClientTest.java
- core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
Motivation :
Currently method naming `canRequest`  makes feel user just querying current state of circuit breaker. So it can cause unexpected side effect. 
We used circuit breaker like below with misunderstanding that `canRequest` doesn't change the circuit breaker state.
By calling `canRequest` twice, there are long HALF_OPEN state period from metric.
Because `canRequest` updates state from https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java#L130 
Therefore I suggest to change method name more clear.
```
if (!cb.canRequest()) {
// codes incurs GC 
}
// other codes 
if (!cb.canRequest()) {
throw new RuntimeException();
}
boolean success = false;
try {
success = client.sendRequest();
} finally {
if …
```
> Rename canRequest to tryRequest

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
- core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePluginTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/ParameterizedPathMappingTest.java
- examples/annotated-http-service/src/main/java/example/armeria/server/annotated/PathPatternService.java
- examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedServiceTest.java
Motivation:
Fix `RoutingTrie` fails with a parameterized rest paths( `{*foo}` ) pattern.
Modifications:
- Set trie path with `PREFIX` `"/foo/*` in `skeleton` , also `paths` if the path is rest paths pattern.
- Set `/foo/:*bar` pattern in normalized path pattern if the path is rest paths pattern.
- Replace `normalizeParameterized` to using `Route.patternString` in DocService.
Result:
- Closes #4034. (If this resolves the issue.)
> Fix `RoutingTrie` fails with a parameterized rest paths(`{*foo}`) pattern

- core/src/main/java/com/linecorp/armeria/common/MediaType.java
- core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
- core/src/main/java/com/linecorp/armeria/server/file/MimeTypeUtil.java
- core/src/test/java/com/linecorp/armeria/server/file/MimeTypeUtilTest.java
- Applied all the recent changes to `MediaType` from Guava
- Added a new constant: `AVIF` (`image/avif`)
- Updated the built-in MIME type mappings in `MimeTypeUtil` so that it
handles the following additional extensions properly:
- `.avif`
- `.heif`
- `.webp`
- `.webmanifest`
> Catch up the upstream changes in `MediaType` and add more constants

- core/src/main/java/com/linecorp/armeria/server/DefaultServerErrorHandler.java
- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
- core/src/main/java/com/linecorp/armeria/server/ServerErrorHandler.java
- core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/server/ServerHttpObjectEncoder.java
- core/src/test/java/com/linecorp/armeria/server/CustomServerErrorHandlerTest.java
Motivation:
A user sometimes wants to generate an error response differently
depending on a certain request header value. For example:
- Include a certain request header value in an error response for easier
troubleshooting; or
- Provide a different level of detail for the requests that contain
a certain header.
Modifications:
- Added an optional `RequestHeaders` parameter to `ServerErrorHandler`
methods.
- Modified `Http{1,2}RequestDecoder` so it constructs a `RequestHeaders`
as early as possible, so that `ServerErrorHandler` is given with a
non-null `RequestHeaders` in most cases.
- Updated `CustomServerErrorHandlerTest` to demonstrate this feature.
Result:
- (new feature) A user can generate an error response differently
depending on the request headers.
- (breaking changes) The method …
> Provide `RequestHeaders` to `ServerErrorHandler`

- core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
Motivation:
While `MoreMeters.distStatCfg` specifies that Micrometer's default `percentilePrecision` is not accurate enough, the correct/better value is never actually used in `MoreMeters`.
Modifications:
- Set `percentilePrecision` in `newTimer()` and `newDistributionSummary()`
Result:
- Meters created by `MoreMeters` are now using more accurate percentiles
> Correctly configure percentile precision in MoreMeters

- core/src/main/java/com/linecorp/armeria/server/file/FileService.java
- core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
Motivation:
When using FileService, the previous behaviour cleared the query params when a directory redirect
was made e.g. `/a?foo=1` ->  `/a/`. This causes problems with e.g. tracking and initial parameters for one-pagers.
Modifications:
- Query parameters are now copied when redirecting in `FileService`.
Result:
- Closes #4049
- This will change keep the query parameters when going to a `FileService`-served directory without a trailing `/`. Previous behaviour was undefined in tests.
> Keep query params when FileService redirects

- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilderTest.java
Motivation:
There is a regression that `DnsEndpointGroup` removes a trailing dot in a `hostname`.
https://github.com/line/armeria/blob/d78b52f3bc62ed1c4f5037f092ea1f514156d880/core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java#L55
The bug appeared in #3772 and applied to 1.11.0.
A trailing dot should be preserved to prevent DNS resolvers from trying
all search domains.
Slack thread: https://line-armeria.slack.com/archives/C1NGPBUH2/p1644861826570949
Modifications:
- Revert normalizing hostname using `InternetDomainName`
and use `Ascii.toLowerCase` instead.
Result:
`DnsEndpointGroup` now correctly respects a trailer dot of a hostname when resolving DNS records.
> Fix a bug where `DnsEndpointGroup` strips trailing `.`

- graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java
- graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceTest.java
- graphql/src/test/resources/test.graphqls
Motivation:
This PR adds test cases for null GraphQL variables (those sent in the "variables" part of the json body posted) and fixes the issue #4068.
Modifications:
Fixes issue with null variables in GraphQL json request.
Added test case for GraphQL that tests the three different cases:
- undefined in Apollo client, ie. variables is defined in `query`, but not set in `variables`
- null in Apollo client, ie. GraphQL variables is sent as null
- complex type with inner value in Apollo client, ie. non-null variable sent as json-object with non-null attribute on it
Result:
- Closes #4068
- Server will stop responding 500 when sending null GraphQL variable
> Fix for null GraphQL variables

- grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientBuilder.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientBuilderTest.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServicePathTest.java
Motivation:
Let's assume that a gRPC service name is `com.example.MySesrvice` and
the service is bound under `/grpc`. If a `/grpc` prefix is set to
`GrpcClients.path()`, a gRPC request sent to
`/grpccom.example.MySesrvice/MyMethod`. To avoid the unexpected path,
we can automatically append missing `/` to the path so that `/grpc`
can correctly send a request to `/grpc/com.example.MyService/MyMethod`.
Modifications:
- Append `/` to a gRPC Client path if missing
- Deprecate `GrpcClientBuilder.path()` and add
`GrpcClientBuilder.pathPrefix()` for less confusion.
Result:
- `GrpcClientBuilder` now correctly normalizes a path prefix.
- `GrpcClientBuilder.path()` has been deprecated in favor of `GrpcClientBuilder.pathPrefix()`.
> Append slash(`/`) to a gRPC client path prefix

- .github/workflows/publish-release.yml
- build.gradle
- site/src/pages/release-notes/1.14.0.mdx
The Java version of `publish` tasks is not updated to Java 17.
Update and force JDK version to use 17 when publishing new artifacts to
Maven Central.
> Use Java 17 to publish artifacts

- core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/EmptyEndpointGroupException.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
Motivation:
Modifications:
- When `DnsEndpointGroup` sets an empty endpoint, a warning log is printed
- When `EmptyEndpointGroupException` is thrown, the relevant `EndpointGroup.toString()` is also stored in the exception
- `EndpointGroup.toString()` is now implemented. Since there may be many `endpoints`, `endpoints` is truncated
Result:
- Users have more transparency on why they encounter an `EmptyEndpointGroupException`
> Leave additional logs for empty endpoint groups

- core/src/test/java/com/linecorp/armeria/server/healthcheck/ScheduledHealthCheckerTest.java
Motivation:
https://github.com/line/armeria/runs/5077167539?check_suite_focus=true
```
ScheduledHealthCheckerTest > awareUnhealthy() FAILED
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a com.linecorp.armeria.server.healthcheck.ScheduledHealthCheckerTest null within 1 seconds.
at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
at app//com.linecorp.armeria.server.healthcheck.ScheduledHealthCheckerTest.awareUnhea …
```
> Fix test failures in `ScheduledHealthCheckerTest.awareUnhealthy()`

- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java
- core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java
Motivation:
Some vulnerable double dots patterns are prohibited by default when
a raw path is parsed.
https://github.com/line/armeria/blob/e2697a575e9df6692b423e02d731f293c1313284/core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java#L40-L45
Some users' point of view, the validation is too conservative for query strings because:
- RFC3986 informs `.` is an unserved character.
https://datatracker.ietf.org/doc/html/rfc3986#appendix-A
- JDK's `URLEncoder` does not percent-encode on `.`.
https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/net/URLEncoder.java#L137
See #4091 for details. 
Modifications:
- Add `Flags.allowDoubleDotsInQueryString()` that allows double dots (`..`) in query string.
Result:
- You can now allow double dots (`..`) in …
> Add a flag that allows double dots in query strings

- settings/checkstyle/checkstyle-suppressions.xml
- settings/checkstyle/checkstyle.xml
Motivation:
Checkstyle consumes huge memories to parse a giant generated file.
```
Caused by: java.lang.Error: Error was thrown while processing /home1/www/actions-runner/_work/armeria/armeria/thrift0.13/gen-src/test/java/com/linecorp/armeria/service/test/thrift/hbase/Hbase.java
at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:310)
at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.processFiles(CheckstyleAntTask.java:367)
at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.realExecute(CheckstyleAntTask.java:331)
at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.execute(CheckstyleAntTask.java:302)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
at …
```
> Exclude generated files from checkstyle linting

- core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/InvalidRequestMessageTest.java
Motivation:
A `RequestLog.requestContent()` of a gRPC request can not be set
with the following condition.
- An exception is raised before `ArmeriaServerCall` receives the first
`DeframedMessage`
- An exception is raised while `ArmeriaServerCall` deserializes a
malformed message.
Modifications:
- Use `abort()` instead of `cancel()` to cancel and propagate the cause
to upstream and the request log.
- Try to log `RequestLog.requestContent()` when a call is closed.
Result:
`GrpcService` now logs `RequestLog.requestContent()` for invalid requests.
> Fix to set `RequestLog.requestContent()` correctly for invalid gRPC requests

- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageTest.java
@trustin suggested an awesome idea to write a StreamMessage<T> into a File or Path. 
```java
interface StreamMessage<T> {
default CompletableFuture<Void> writeTo(Path destination, Function<? super T, ? extends HttpData> mapper, options...) {
// Delegate to StreamMessages.writeTo(...)
}
}
```
- Add `StreamMessage.writeTo() `
- Edit the StreamMessageTest by referring to the existing streamMessagesTest.
- We can now write file using `StreamMessge.writeTo()`
- Closes #4048
> Provide a general way to write an StreamMessage to a file

- grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java
- grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractorTest.java
- grpc/src/test/proto/com/linecorp/armeria/grpc/testing/options.proto
- grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
Motivation:
gRPC doc generation fails when options and extensions were being used in proto files.
The test cases have been modified so the `test.proto` file contains an example option. Before changing `GrpcDocStringExtractor`, it wasn't able to produce documentation because of a duplicate key in the map. It was causing the whole Documentation Service to crash.
We might want to consider displaying `options` in documentation service in the future but this implementation un-blocks users who can't use the service because of the aforementioned bug.
The issue is described in #4123 in more detail.
Modifications:
- Ignore comments written on proto service options or extensions.
Result:
- Closes #4123
- The documentation service doesn't crash the whole Armeria service anymore when proto files have …
> fix: grpc doc generation failing for options and extensions

- .github/workflows/actions_build.yml
- gradle.properties
Motivation:
Our CI build sometimes fails with an `OutOfMemoryError` from Gradle.
Modifications:
- Added `-XX:+HeapDumpOnOutOfMemoryError` option to Gradle JVM
- Updated the GitHub Actions workflow so it uploads `java_pid*.hprof` in
case of build failure.
Result:
Will hopefully get a better idea on why OOME occurred.
> Generate the heap dump when Gradle fails with OutOfMemoryError

- spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaWebServer.java
I'm using Armeria at work. Recently, the following exception has occurred during unit testing.
```
Caused by: org.springframework.boot.web.server.WebServerException: Failed to start ArmeriaWebServer
at com.linecorp.armeria.spring.web.reactive.ArmeriaWebServer.start(ArmeriaWebServer.java:100)
at org.springframework.boot.web.reactive.context.WebServerManager.start(WebServerManager.java:55)
at org.springframework.boot.web.reactive.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:40)
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
... 107 common frames omitted
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
``` …
> Improve exception message of `WebServerException` when server fails to start

- examples/grpc-scala/src/test/scala/example/armeria/grpc/scala/HelloServiceTest.scala
- examples/grpc/src/test/java/example/armeria/grpc/HelloServiceTest.java
- scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/HelloServiceTest.scala
Motivation:
Fix test failure of `HelloServiceTest.getLotsOfReplies()` for #3518
Modifications:
- Enlarge the timeout
- Add debug message to help finding the issue
- Using Atomic* for variables accessed by multiple threads
Result:
- Closes #3518 until it happen again.
> Fix test failure of HelloServiceTest.getLotsOfReplies()

- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategyTest.java
Motivation:
A `NoSuchElementException` can be raised when the endpoints are fully replaced in
`RampingUpEndpointWeightSelector`, because `shouldRampUpWithPreviousRampedUpEntry`
may return `true` but `filterOldEndpoints` clears the entries.
Modifications:
- Call `filterOldEndpoints` at the beginning and reuse its result for all the cases
including `ramp up with previous`, `rampup with next` or `add new entry`.
Result:
- Closes #3776
- No more `NoSuchElementException` when endpoints are fully changed.
> Fix NoSuchElementException raised by RampingUpEndpointWeightSelector

- core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java
- core/src/main/java/com/linecorp/armeria/server/HttpStatusException.java
- core/src/main/java/com/linecorp/armeria/server/file/FileService.java
- core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
- core/src/main/java/com/linecorp/armeria/server/file/NonExistentHttpFile.java
- core/src/main/java/com/linecorp/armeria/server/healthcheck/DefaultHealthCheckUpdateHandler.java
- core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
- core/src/test/java/com/linecorp/armeria/server/file/HttpFileTest.java
- thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
- thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpErrorResponseTest.java
Motivation:
An `HttpResponseException` has an `HttpResponse`. The thrown response
is extracted by the default `ServerErrorHandler` and converted to 
a normal `HttpResponse`. There are downsides to `HttpResponseException`.
As the response is wrapped by `HttpResponseException`,
decorators can not access the `HttpObject`s of the response in the
exception using `mapXXX`.
Users may find it hard to mutate the thrown `HttpResponse` because 
recovery should be done first. Therefore, it would be better not to use 
`HttpResponseException` internally or recover it before passing
the response to decorators so that users use `HttpResponse.mapXXX` to
transform a returned response in decorators.
Modifications:
- Add `HttpFile.ofRedirect(location)` to indicate a file in a different
location.
- Recover an …
> Fix not to use `Http{Response,Status}Exception` internally

- core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerKeepAliveHandlerTest.java
Stack trace 1:
```
HttpServerKeepAliveHandlerTest > closeByClientIdleTimeout(SessionProtocol, boolean) > com.linecorp.armeria.server.HttpServerKeepAliveHandlerTest.closeByClientIdleTimeout(SessionProtocol, boolean)[1] FAILED
Expecting actual:
2041.1256999999998
to be close to:
2764.0
by less than 25% but difference was 26.153194645441395%.
(a difference of exactly 25% being considered valid)
at com.linecorp.armeria.server.HttpServerKeepAliveHandlerTest.lambda$closeByClientIdleTimeout$0(HttpServerKeepAliveHandlerTest.java:162)
at com.linecorp.armeria.server.HttpServerKeepAliveHandlerTest.closeByClientIdleTimeout(HttpServerKeepAliveHandlerTest.java:160)
```
Stack trace 2:
```
KeepAliveHandlerTest > shouldNotWritePingIfConnectionIsActive() FAILED …
```
> Mark `KeepAliveHandlerTest` and `HttpServerKeepAliveHandlerTest` as flaky

- .github/workflows/actions_build.yml
Motivation:
We are getting `OutOfMemoryError` during the build on a CI machine
spontaneously. According to the heap dump, ProGuard keeps the data
required for shading JARs indefinitely, incurring memory pressure on the
Gradle JVM.
Modifications:
- Run `shadedJar` and `shadedTestJar` tasks in a separate step so that
other tasks are unaffected by them.
Result:
Hopefully no `OOME` during CI
> Reduce memory pressure while running tests in CI

- core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
- core/src/test/java/com/linecorp/armeria/client/Http1ResponseDecoderTest.java
Motivation:
#3060 had handled request timeout on http1 connections.
However, I had falsely assumed that netty `HttpResponseStatus` was a singleton and compared by reference.
It turns out that this isn't the case if the provided `reasonPhrase` doesn't match that of `netty`'s. (the reported reason phrase was `Request-Timeout` with a hyphen)
https://github.com/netty/netty/blob/824a0b803431c58bd8dfe25a30413d7ff9759e8f/codec-http/src/main/java/io/netty/handler/codec/http/HttpResponseStatus.java#L467
Modifications:
- Modify `ArmeriaHttpUtil#isRequestTimeoutResponse` to compare by status code.
Result: 
Now, even for custom reason phrases request timeout on h1 should be correctly handled.
> Handle request timeout correctly by comparing status codes

- retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
Motivation: 
- I've seen this while I'm trying to use retrofit.
Modifications:
- Fix a wrong link in javadoc
Result:
- No more confusion
Long time no see!
> Fix a wrong link in Javadoc of ArmeriaRetrofitBuilder#addConverterFactory

- graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java
- graphql-protocol/src/test/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlServiceTest.java
Motivation:
In GraphqlService, if `query` and `operationName` are not of string
type, `ClassCastException` is thrown
Modifications:
- Add the validation code that checks the type before implicit conversion.
Result:
- No `ClassCastException` is thrown.
- Fixes #4104
> Fix `ClassCastException` in `GraphqlService`

- .github/workflows/actions_build.yml
- .github/workflows/public-suffixes.yml
- .github/workflows/publish-release.yml
Motivation:
`core:processTestResources` fails with the following exception:
```
Caused by: org.gradle.internal.execution.fingerprint.InputFingerprinter$InputFileFingerprintingException: Cannot fingerprint input file property 'rootSpec$1': Failed to create MD5 hash for file '/home1/www/actions-runner/_work/armeria/armeria/core/src/test/resources/com/linecorp/armeria/server/file/bar/??.txt' as it does not exist.
at org.gradle.internal.execution.fingerprint.impl.DefaultInputFingerprinter$InputCollectingVisitor.visitInputFileProperty(DefaultInputFingerprinter.java:141)
...
Caused by: java.io.FileNotFoundException: /home1/www/actions-runner/_work/armeria/armeria/core/src/test/resources/com/linecorp/armeria/server/file/bar/??.txt (No such file or directory)
```
Modifications:
- Add `LC_ALL` …
> Enforce UTF-8 when running CI

- core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java
- core/src/test/java/com/linecorp/armeria/common/multipart/MimeParserTest.java
- core/src/test/java/com/linecorp/armeria/common/multipart/MultipartTest.java
Motivation:
In `Multipart.from(request)`, an exception is thrown when using a request with a multipart whose content is empty.
Modifications:
- When reading the body, check the body length and return `EmptyByteBuf` if empty.
Result:
- Closes #4175
> Fix parsing error for BodyPart when an empty file

- core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
- core/src/main/java/com/linecorp/armeria/common/HttpRequestSetters.java
- core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
- core/src/test/java/com/linecorp/armeria/common/HttpRequestBuilderTest.java
Related #4160
Motivation:
- I summarize the well-documented [issue](https://github.com/line/armeria/issues/4160#issue-1174939262) by @jrhee17 
- Some users may want to add multiple query param values for a single key.
- However, `WebClient.prepare().queryParam()` perform a `QueryParamsBuilder#setObject` by default, making it difficult to execute such a query programmatically.
```
WebClient.prepare()
.get("/")
.queryParam("id", 1)
.queryParam("id", 2)
.queryParam("id", 3)
.execute();
```
Modifications:
- Use addObject() instead of setObject() in `AbstractHttpRequestBuilder.queryParam()`
- Use add() instead of set() in `AbstractHttpRequestBuilder.queryParams()`
Result:
- Users can add multiple query param values with a single key when using `WebClient.prepare()`
- Users can use either …
> Provide a way to add multiple QueryParams with a single key when using WebClient.prepare()

- core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/server/CertificateUtil.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/server/Server.java
- core/src/test/java/com/linecorp/armeria/server/ServerTlsCertificateMetricsTest.java
- core/src/test/java/com/linecorp/armeria/server/ServerTlsHandshakeMetricsTest.java
Motivation:
- A user would want to keep the counter of TLS handshake success/failure.
- The TLS certificate expiry metrics we added at #4109 uses hostname
instead of hostname pattern, potentially increasing the cardinality of
the metrics.
Modifications:
- Added `CertificateUtil` which extracts and caches the common name of
X.509 certificates.
- Added TLS handshake metrics to `HttpServerPipelineConfigurator`.
- Cleaned up the TLS handshake exception handling in
`HttpServerPipelineConfigurator` once again.
- The TLS certificate expiry metrics now use `hostname.pattern` instead
of `hostname` for reduced cardinality.
- Changed the name of TLS certificate expiry metrics from
`armeria.server.certificate.*` to `armeria.server.tls.certificate.*`
for consistency.
- Renamed …
> Add metrics for TLS handshakes / Reduce TLS certificate expiry metrics cardinality

- core/src/main/java/com/linecorp/armeria/internal/client/dns/SearchDomainDnsResolver.java
- core/src/test/java/com/linecorp/armeria/internal/client/dns/SearchDomainDnsResolverTest.java
- core/src/test/java/com/linecorp/armeria/internal/client/dns/SearchDomainTest.java
Motivation:
If a search domain starts with a dot(`.`), a DNS resolution failed with
an `IllegalArgumentException`.
```
Caused by: java.lang.IllegalArgumentException: Empty label is not a legal name
at java.base/java.net.IDN.toASCIIInternal(IDN.java:284)
at java.base/java.net.IDN.toASCII(IDN.java:123)
at java.base/java.net.IDN.toASCII(IDN.java:152)
at com.linecorp.armeria.internal.client.dns.DnsQuestionWithoutTrailingDot.<init>(DnsQuestionWithoutTrailingDot.java:53)
at com.linecorp.armeria.internal.client.dns.DnsQuestionWithoutTrailingDot.of(DnsQuestionWithoutTrailingDot.java:48)
at com.linecorp.armeria.internal.client.dns.SearchDomainDnsResolver$SearchDomainQuestionContext.newQuestion(SearchDomainDnsResolver.java:153)
at com.linecorp.armeria.internal.client.dns.SearchDomainDnsResolver$Sear …
```
> Fix a bug where a DNS resolution is failed with a search domain starting with a dot

- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckerContext.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroupTest.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupInitialFailureTest.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
Motivation:
Since a failed response is automatically retried with a backoff, it
makes sense to ignore unhealthy responses. However, if there is a
misconfiguration or an unexpected network disruption, users find it
difficult to detect the cause of unhealthy endpoints.
They will just see an `EmptyEndpointGroupException` like the following after
a connection timeout.
```java
Caused by: com.linecorp.armeria.client.endpoint.EmptyEndpointGroupException:
Unable to select endpoints from: HealthCheckedEndpointGroup{endpoints=[], numEndpoints=0, candidates=[...], numCandidates=5, selectionStrategy=class com.linecorp.armeria.client.endpoint.WeightedRoundRobinStrategy, initialized=true}
at com.linecorp.armeria.client.endpoint.EmptyEndpointGroupException.get(EmptyEndpointGroupException.java:39)
``` …
> Warn the initial failure of health checks for `HealthCheckedEndpointGroup`

- examples/grpc/src/main/java/example/armeria/grpc/Main.java
- examples/grpc/src/test/java/example/armeria/grpc/HelloServiceTest.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlerTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
Motivation:
- https://github.com/line/armeria/issues/4114
Modifications:
- Include a stacktrace in a response in `UnframedGrpcErrorHandler` when `verboseResponse` is `true`.
Result:
- Closes https://github.com/line/armeria/issues/4114
> Include a stacktrace in a response for unframed gRPC service when verboseResponse is enabled

- eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
- eureka/src/test/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupFailoverTest.java
As talked in [slack chat](https://line-armeria.slack.com/archives/C1NGPBUH2/p1649939278790489?thread_ts=1649937254.857659&cid=C1NGPBUH2)
If an exception happens in the fetchRegistry method. The endpoint group would not schedule the fetching registry.
Add some exception-catching to schedule the fetching.
Result:
- schedule the fetch even if an exception happened.
> Fix eureka may stop schedule the fetching registry

- core/src/main/java/com/linecorp/armeria/common/stream/NoopSubscriber.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageTest.java
Motivation:
Provide a method to do a no-op subscribe to a `StreamMessage` #4145
Some users may want to use `StreamMessage#peek` to perform some options, but not want the entire message to be in memory (as is done by `StreamMessage#collect`). The functionality may be similar to `Flux#subscribe`
Modifications:
- Add no-op `subscribe` to `StreamMessage`
Result:
- we can now use no-op `subscribe` for draining data from `StreamMessage`.
- Closes #4145
> Add no-op subscribe

- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
- core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/annotation/Delimiter.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
- site/src/pages/docs/server-annotated-service.mdx
Motivation:
- Some APIs need comma-delimited multi parameters: `/hello1?number=1,2,3`.
- https://www.baeldung.com/spring-request-param#mapping-a-multi-value-parameter
Modifications:
- Added `@Delimiter` annotation that splits the value of query parameter or header
with the specified delimiter
- Added `AnnotatedServiceBindingBuilder.queryDelimiter()` that splits the value of query parameter with the specified delimiter
Result:
- A comma-delimited query parameter or header can be split easily.
> Support comma-delimited multi `@Param` or `@Header`

- core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java
- core/src/main/java/com/linecorp/armeria/server/ExactPathMapping.java
- core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
- core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java
- core/src/main/java/com/linecorp/armeria/server/RegexPathMappingWithPrefix.java
- core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
- core/src/test/java/com/linecorp/armeria/server/AbstractPathMappingTest.java
- core/src/test/java/com/linecorp/armeria/server/MappedPathTest.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java
Motivation:
`RoutingResult.path()` should return a mapped path by `Route`.
Let's say a service which routes to `/users/{userId}` is prefixed
with `/api/v1`. If a request path is `/api/v1/users/1234`,
- `ServiceRequestContext.path()` is equal to `/api/v1/users/1234`
- `ServiceRequestContext.mappedPath()` should be equal to `/users/1234`
Before #4086, a prefixed path is internally mapped with
`PrefixPathMapping`. So a prefix path is correctly stripped.
https://github.com/line/armeria/blob/d336d8981f03001f5a12ecae3363e98b698bb08b/core/src/main/java/com/linecorp/armeria/server/PrefixPathMapping.java#L67
\#4086 introduced `Route.withPrefix()` and all `PathMapping`s are able
to be prefixed. Consequently, other `PathMapping` implementations such
as `ExactPathMapping`, should remove the prefix …
> Make `RoutingResult.path()` correctly return the mapped path

- eureka/src/test/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupFailoverTest.java
Motivation:
`EurekaEndpointGroupFailoverTest` can be easily failed if the server
fails to acquire an ephemeral port within the timeout.
Modifications:
- Mark `shouldRefreshEndpointsAfterFailure()` as a `@FlakyTest`
Result:
Less noise in CI builds.
> Make `EurekaEndpointGroupFailoverTest` flaky

- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRandomDistributionEndpointSelector.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRandomDistributionEndpointSelectorTest.java
Motivation:
I saw suspicious stack traces from the thread dump reported from LINE's
internal channel.
```java
daemon prio=5 os_prio=0 cpu=14048767.37ms elapsed=148187.24s tid=0x00007f0c710eb000 nid=0xb556 runnable  [0x00007f06fbb8d000]
java.lang.Thread.State: RUNNABLE
at com.linecorp.armeria.client.endpoint.WeightedRandomDistributionEndpointSelector.selectEndpoint(WeightedRandomDistributionEndpointSelector.java:87)
at com.linecorp.armeria.client.endpoint.WeightRampingUpStrategy$RampingUpEndpointWeightSelector.selectNow(WeightRampingUpStrategy.java:169)
at com.linecorp.armeria.client.endpoint.DynamicEndpointGroup.selectNow(DynamicEndpointGroup.java:87)
```
Many threads in the thread dump got stuck in the same line.
It seemed that a `WeightedRandomDistributionEndpointSelector` couldn't …
> Fix a bug where `WeightedRandomDistributionEndpointSelector` gets stuck in an infinite loop

- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupIntegrationTest.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
Motivation:
I got a report from @eisig that `EndpointSelectionStrategy.rampingUp()`
did not work with `HealthCheckedEndpointGroup`.
Slack thread: https://line-armeria.slack.com/archives/C1NGPBUH2/p1650438670771329?thread_ts=1650324855.491319&cid=C1NGPBUH2
The bug will be reproducible by the following steps:
- If new `Endpoint`s are added to a `DynamicEndpointGroup` which
`HealthCheckEndointGroup` delegates to, a new context group is added to
`contextGroupChain`.
https://github.com/line/armeria/blob/1ec5a6828c6b8245dec738519b6f543a7878e349/core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java#L160
- The old context chain will be moved when the first check of the new context
group has been completed. …
> Fix a bug where duplicate healthy endpoints are set to `HealthCheckedEndpointGroup`

- core/src/test/java/com/linecorp/armeria/server/file/DefaultMediaTypeResolverTest.java
Motivation:
- https://bugs.openjdk.java.net/browse/JDK-8273655
- https://github.com/openjdk/jdk/commit/65ed0a742e65fe7e661e8da2adea6cd41992869e
- JDK has modified the default `content-types.properties` mappings recently, causing failures in some tests.
- https://github.com/line/armeria/actions/runs/2291723521
Modifications:
- Use `.bin` over `.gz` for some tests
Result:
- CI passes for more recent jdk versions
> Fix failing `DefaultMediaTypeResolverTest` tests

- grpc/src/test/java/com/linecorp/armeria/server/grpc/InternalReflectionUtilsTest.java
Motivation:
`InternalReflectionUtilsTest` was located in `test/proto/...`.
Modifications:
- Move `InternalReflectionUtilsTest` under `test/java/...`
Result:
Test `InternalReflectionUtilsTest` with CI jobs.
> Move a misplaced test file

- .github/workflows/actions_build.yml
- .github/workflows/public-suffixes.yml
- .github/workflows/publish-release.yml
Motivation:
https://github.com/line/armeria/runs/6621970139?check_suite_focus=true
Recently an error is being returned from cloudflare when installing java causing unnecessary noise.
Hopefully, `adoptium.net` doesn't have this issue.
It is better that we migrate anyways as per their recommendation:
Modifications:
- Modify to use temurin for github actions runners (not self-hosted)
Result:
- Hopefully less flaky tests/actions
> Use temurin instead of adopt

- core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
Motivation:
`WriteTimeoutException` is defined as an exception thrown if the first message write doesn't complete within a specified time. This specification holds for requests with bodies.
However, requests without bodies never throw a `WriteTimeoutException` because:
1) Requests without bodies complete their stream immediately
https://github.com/line/armeria/blob/5a2c7202aa17b6e43a90808e2a27fdf69df18417/core/src/main/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessage.java#L141-L148
2) This in turn, cancels the write timeout immediately
https://github.com/line/armeria/blob/5a2c7202aa17b6e43a90808e2a27fdf69df18417/core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java#L261
Modifications:
- Remove the call to `HttpRequestSubscriber#cancelTimeout` when …
> Correctly throw `WriteTimeoutException` for requests without content

- spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpConnector.java
- spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpRequest.java
Motivation:
`ArmeriaClientHttpConnector, createRequest()` creates armeria's `WebClient` per http call.
we can reuse armeria's  `WebClient` , so I propose reuse armeria's `WebClient` in `ArmeriaClientHttpConnector`.
Modifications:
- reuse armeria's WebClient instance in `ArmeriaClientHttpConnector`.
- make base-specified armeria's WebClient non-base URI WebClient.
Result:
- less GC cost a bit if the user uses Spring WebClient integration
> Reuse armeria's WebClient instance when using the integration for Spring webflux's WebClient

- spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
Motivation:
`ArmeriaSettings.internalServices` is not List type.
Result:
omitted
> Fix javadoc of ArmeriaSettings.java

- jetty9/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTlsReverseDnsLookupTest.java
Motivation:
`JettyServiceTlsReverseDnsLookupTest.mutualTlsAttrs(SessionProtocol)`
fails on Windows. #4273 Reserse-lookup result for `127.0.0.1` is
`127.0.0.1` itself on Windows. I debugged the tests locally and figured
out the reason.
- The first lookup successfully found the hostname such as
`DESKTOP-XXX`.
https://github.com/openjdk/jdk/blob/b544b8b7d43907e93263db31ba3cc6d5951bcaee/src/java.base/share/classes/java/net/InetAddress.java#L810-L811
- JDK tried to get all IP addresses using the acquired hostname to
prevent spoofing.
https://github.com/openjdk/jdk/blob/b544b8b7d43907e93263db31ba3cc6d5951bcaee/src/java.base/share/classes/java/net/InetAddress.java#L824-L829
- The IP addresses resolved by the hostname only contain public IPs and
`127.0.0.1` is not included in the result.
- JDK …
> Skip a validation the reverse-lookup result of `127.0.0.1` for Windows

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/KotlinUtil.java
- kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaKotlinUtil.kt
- kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/NullableTypeSupportTest.kt
Motivation:
`AnnotatedService` requires `@Nullable` annotations for nullable resolved values even when it is used with Kotlin which offers nice null-safety with nullable types.
Modifications:
- Add `isMarkedNullable` method to `KotlinUtil`.
- Make `AnnotatedValueResolver#Builder` detect Kotlin nullable types of `Field` and `Parameter` and allow null values for them.
Result:
- Now you don't need to add `@Nullable` annotations to nullable arguments & fields in `AnnotatedService` if they are Kotlin nullable types(`?`).
- Closes #4144
> Add Koltlin nullable type support to `AnnotatedService`

- core/src/main/java/com/linecorp/armeria/common/HttpHeaders.java
- core/src/main/java/com/linecorp/armeria/common/QueryParams.java
- core/src/main/java/com/linecorp/armeria/common/ServerCacheControl.java
- core/src/test/java/com/linecorp/armeria/common/HttpHeadersTest.java
- core/src/test/java/com/linecorp/armeria/common/QueryParamsTest.java
- core/src/test/java/com/linecorp/armeria/common/ServerCacheControlTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/file/FileServiceAdditionalHeadersTest.java
- graphql/src/test/java/com/linecorp/armeria/internal/server/graphql/GraphqlDocServiceTest.java
Motivation:
According to `Cache-Control` spec, `must-revalidate` operates together with "stale" state, and an easy (the only?) way to specify "stale" is by adding `max-age=0` to the `Cache-Control` response header.
See #4290 for more information.
Modifications:
- Added `max-age=0` to the `ServerCacheControl.DISABLED` and `ServerCacheControl.REVALIDATE` constants
Result:
- Closes #4290
- Should only have benign effect.
Theoretically a user of Cache-Control could've used e.g. `ServerCacheControl.DISABLED.toBuilder().mustRevalidate(false).build()` and get unexpected result, but I doubt it.
> Add max-age ServerCacheControl.DISABLED/REVALIDATE

- benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/Server.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
- core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
- core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ShutdownSupport.java
- core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
- core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilderTest.java
- core/src/test/java/com/linecorp/armeria/server/ServiceBindingBuilderTest.java
- core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
- core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
- dropwizard2/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaServerFactory.java
- thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
Motivation:
When users want to set multiple `AccessLogWriter`, they need to chain the `AccessLogWriter` by themselves
because the writer set later overwrite the previous one.
```java
AccessLogWriter fooWriter = ...
AccessLogWriter barWriter = ...
ServerBuilder sb1 = ...
sb1.accessLogWriter(fooWriter, false);
sb1.accessLogWriter(barWriter, true); // Not OK because fooWriter is overwritten
ServerBuilder sb2 = ...
sb2.accessLogWriter(fooWriter.andThen(barWriter), false); // OK
```
However, it's not convenient and also it's problem if users want to shut down one of the `AccessLogWriter`s when the server shuts down.
It would be nice to chain the multiple `AccessLogWriter` inside the builder and shut down the `AccessLogWriter`s only those who need it.
Modifications:
- Chain `AccessLogWriter` …
> Chain the AccessLogWriter if another one is previously set

- core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTck.java
Motivation:
Working on #4058, I found `PublisherBasedStreamMessage` failed with
`required_spec303_mustNotAllowUnboundedRecursion`.
```java
Gradle suite > Gradle test > com.linecorp.armeria.common.stream.DefaultByteStreamMessageTckTest > required_spec303_mustNotAllowUnboundedRecursion FAILED
java.lang.AssertionError: Got 2 onNext calls within thread: Thread[armeria-common-worker-epoll-2-3,5,main], yet expected recursive bound was 1
at org.testng.Assert.fail(Assert.java:110)
at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:229)
at org.reactivestreams.tck.PublisherVerification$19$2.onNext(PublisherVerification.java:781)
at com.linecorp.armeria.common.stream.PublisherBasedStreamMessage$AbortableSubscriber.onNext0(PublisherBasedStreamMessage.java:337)
at …
```
> Fix Reactive Streams 3.3 violation in `PublisherBasedStreamMessage`

- retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
- retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/PipeBuffer.java
- retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriber.java
- retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryLargeStreamTest.java
Motivation:
Recognized that Armeria-retrofit's streaming mode sometimes requests more data from the heap even though there is still data in the buffer.
Modifications:
- Check if buffer exhausted before request next item
- Fix deprecated api of `ResponseBody.create`
- Fix test not using streaming mode
Result:
- Armeria retrofit will request upstream on demand
> Fix while streaming retrofit not request upstream on demand

- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageInputStream.java
- core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStream.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStreamTest.java
**Related Bug Issue** #4268 
We found some bugs on `StreamMessageInputStream`
1. If `httpDataConverter` returns `HttpData.empty()`, `StreamMessageInputStreamSubscriber` should request the next element to the upstream to produce bytes but currently doesn't request any element
2. `StreamMessageInputStream` could call `subscriber.request()` even if `byteBufsInputStream` has enough data
- If `httpDataConverter` returns `HttpData.empty()`, `StreamMessageInputStreamSubscriber` requests the next element to the upstream
- `StreamMessageInputStream` calls `subscriber.request()` only when `byteBufsInputStream` has not enough data
- Fix two bugs on `StreamMessageInputStream`
- ✅ Close #4268 issue
> Fix bugs while converting `StreamMessage` to `InputStream`

- core/src/main/java/com/linecorp/armeria/common/multipart/Multiparts.java
- core/src/test/java/com/linecorp/armeria/common/multipart/MultipartsTest.java
Motivation:
If a boundary in a multipart content-type header is missing,
`Multiparts.getBoundary()` should throw an `IllegalStateException` not
`NullPointerException` #4193
Modifications:
- Check the nullness of the return list for a boundary parameter.
Result:
- `Multiparts.getBoundary()` now throws a `IllegalStateExcepion` instead
of `NullPointerException when a boundary is missing.
- Fixes #4193
> Fix a bug where `Multiparts.getBoundary()` throws a `NullPointerException` when a boundary is missing

- grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/UnaryServerCall.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServerInterceptorTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/StreamingServerCallTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/UnaryServerCallTest.java
Motivation:
`ServerInterceptor`s bound to a `GrpcService` run in an event loop even if
`GrpcServiceBuilder.useBlockingTaskExecutor(true)` option is specified.
See #4275 for details
Modifications:
- Use a blocking executor to run `ServerInterceptor`s
Result:
- You can now run `ServerInterceptor`s in a blocking task executor when
`GrpcServiceBuilder.useBlockingTaskExecutor(true)` is enabled.
- Fixes #4275
> Run gRPC's `ServerInterceptor` in a blocking executor if `useBlockingTaskExecutor` is enabled.

- core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java
If it is not a global exception handler, users may be interested in recovering an exception.
So, we can add a shortcut method for those requirements.
For example
```java
HttpResponse failed = HttpResponse.ofFailure(new IllegalStateException("Oops..."));
failed.recover(IllegalArgumentException.class, 
cause -> HttpResponse.of(HttpStatus.BAD_REQUEST))
.recover(IllegalStateException.class, 
cause -> HttpResponse.of(HttpStatus.INTERNAL_SERVER_ERROR))
.recover(....)
```
Users may be to want recover shortcut specific exception class type.
- Add `recover()` shortcut method in `HttpResponse`
- Close #4279
- You can now map a specific exception to an <type://HttpResponse>.
```java
HttpResponse recovered =
response.recover(IllegalStateException.class,
cause -> HttpResponse.of("Fallback"));
```
> Recover HttpResponse according to a specific exception class

- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceLogNameTest.java
Motivation:
`GrpcServiceLogNameTest.logName()` accesses `RequestLog.name()` using 
`RequestLogAccess.partial()` that unsafely accesses `RequestLog` without waiting for the completion event.
https://github.com/line/armeria/blob/49054ad7f22a7f2d64faaeb694674b0df09ad165/grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceLogNameTest.java#L105
I thought the `.partial()` was safe if `RequestLog.name()` was set before a response completed.
However, the hypothesis was wrong. `RequestLog.name()` could be set even after the write of a response is completed.
`RequestLog.name()` can be set while executing `.endRequest()`.
https://github.com/line/armeria/blob/daae15d426ffb2581fdff9f10f16ec69f90b7a36/core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java#L1041-L1046
; …
> Fix the test failure of `GrpcServiceLogNameTest.logName()`

- dependencies.yml
- retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
Motivation:
Armeria doesn't explicitly declare a `okhttp` version in it's published pom files.
In the previous release, there was a usage of `okhttp3` 4.x.x API. However, most of our dependencies have a transient version dependency on `okhttp3` 3.x.x.
Due to this issue, retrofit calls aren't completed correctly due to a `NoSuchMethodException`, causing requests to hang
Modifications:
- Use `okhttp3` 3.x.x when compiling armeria
- Revert to using `okhttp3` 3.x.x APIs only
Result:
- Users don't experience indefinitely waiting retrofit calls
> Enforce `okhttp` dependency version to `3.14.9`

- site/gatsby-config.js
Motivation:
We use `sv-SE` locale to generate ISO8601 like date String. e.g. (2022-07-10 12:31:32 GMT+9)
https://stackoverflow.com/questions/25050034/get-iso-8601-using-intl-datetimeformat/58633686#58633686
However, the String uses a space as a delimiter for separating date and time and it's not allowed anymore in ISO 8601.
https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations
Also, the converted String is not properly parsed back to the Date object by dayjs in certain browsers(Safari)
so [this](https://github.com/line/armeria/blob/master/site/src/layouts/footer.tsx#L28) doesn't work properly.
Modifications:
- Use the default locale which dayjs easily converts to the Date object
Result:
- You no longer see NaN from the site.
> Use default locale(en-US) for `currentBuildDate` in Gatsby

- dependencies.yml
- it/okhttp/build.gradle
- retrofit2/build.gradle
Motivation:
Previously, our `dependencies.yml` has had `okhttp3` version set as `4.x.x `.
With the following [pull request](https://github.com/line/armeria/pull/4342/files), I had tried fixing the `okhttp3` version to be compatible with `retrofit` for Armeria builds.
However, it turns out the `okhttp3` downgrade is causing a test failure in the `it:okhttp` module for mac only.
Modifications:
- Globally define `okhttp3` version to `4.10.10`
- Strictly define `retrofit2` module's `okhttp3` version to `3.14.9`
Result:
- Closes #4345
> Set okhttp version explicitly in `retrofit2` module

- core/src/main/java/com/linecorp/armeria/client/DefaultBlockingWebClient.java
- core/src/main/java/com/linecorp/armeria/client/DefaultRestClient.java
- core/src/main/java/com/linecorp/armeria/common/util/AbstractUnwrappable.java
- core/src/main/java/com/linecorp/armeria/common/util/Unwrappable.java
- core/src/test/java/com/linecorp/armeria/common/util/AbstractUnwrappableTest.java
- scala/scala_2.13/src/main/scala/com/linecorp/armeria/client/scala/ScalaRestClient.scala
Motivation:
Currently, it is possible to retrieve the root `Unwrappable` if one knows the type using `Unwrappable#as(Class<?>)`.
However, sometimes users may just want to retrieve the underlying root type quickly without caring what type the object actually is.
One such example of this case may be when one simply wants to check for equality of the underlying type.
https://github.com/line/armeria/blob/8b0225ec63e231428276f30b92f8357eb7876b03/core/src/main/java/com/linecorp/armeria/common/ThreadLocalRequestContextStorage.java#L49
One may want to check whether the underlying `RequestContext` is equal in the above scenario.
Another option I think we have is to add a "root"-esque API to `RequestContext`.
I think this is also a good idea, at the risk of ABI compatibility if we decide to …
> Introduce a way to retrieve the innermost wrapped object of `Unwrappable` easily

- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
Motivation:
`HealthEndpointGroup.allHealthyEnpoints()` is used to get all health
endpoints from `contextGroupChain`, which is called when either
the healthiness of an `Endpoint` is updated after a health check
https://github.com/line/armeria/blob/554d5963bef33162b1cb077077336de3ef3aadfb/core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java#L252-L263
or when the first `contextGroup` is resolved.
https://github.com/line/armeria/blob/554d5963bef33162b1cb077077336de3ef3aadfb/core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java#L171-L181
`allHealthyEndpoints`, in turn, assumes that at least one `contextGroup` is
available when it is called. However, if an `Endpoint` is updated while
an …
> Fix a bug where `HealthEndpointGroup` raises `NoSuchElementException` while closing

- kotlin/src/main/kotlin/com/linecorp/armeria/client/kotlin/CoroutineRestClient.kt
Motivation:
Noticed some warnings while building the project:
`> Task :kotlin:compileKotlin
w: Argument -Xopt-in is deprecated. Please use -opt-in instead
w: /Users/wjdalstn/Documents/GitHub/armeria/kotlin/src/main/kotlin/com/linecorp/armeria/client/kotlin/CoroutineRestClient.kt: (33, 12): Type parameter 'T' has nullable upper bounds while non-nullable version is expected. This warning will become an error soon. See https://youtrack.jetbrains.com/issue/KT-36770 for details
w: /Users/wjdalstn/Documents/GitHub/armeria/kotlin/src/main/kotlin/com/linecorp/armeria/client/kotlin/CoroutineRestClient.kt: (33, 20): Type parameter 'T' has nullable upper bounds while non-nullable version is expected. This warning will become an error soon. See https://youtrack.jetbrains.com/issue/KT-36770 for …
> Remove warning in task :kotlin:compileKotlin

- core/src/main/java/com/linecorp/armeria/server/AggregatingDecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
- core/src/test/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequestTest.java
- core/src/test/java/com/linecorp/armeria/server/ServerRequestDurationTest.java
- core/src/test/java/com/linecorp/armeria/server/StreamingDecodedHttpRequestTest.java
Motivation:
The start time of a request indicates when a server receives the first
headers of a request and it is recorded when `HttpServiceHandler`
receives the decoded request from `Http{1,2}RequestDecodeder`.
Previously, `Http{1,2}RequestDecoder` passes a request right after the
first `RequestHeaders` is received. So it was correctly recorded as expected.
However, after `ExchangeType` has been introduced, a fully aggregated
request is passed to `HttpServerHandler` if `ExchangeType.UNARY` or
`ExchangeType.RESPONSE_STREAMING` is set.
Modifications:
- Recode `requestStartTimeNanos` and `requestStartTimeMicros` when
request headers is received in `Http{1,2}RequestDecoder`
Result:
- `requestStartTimeNanos` and `requestStartTimeMicros` are now correctly
recoded when `RequestHeaders` is …
> Fix a bug where request duration is incorrectly recoded.

- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
Motivation:
The following message is always warned when `ArmeriaChannel` class is
initialized for the first time.
```
... WARN  c.l.a.i.c.grpc.GrpcExchangeTypeUtil - Unknown MethodType: UNKNOWN; using BIDI_STREAMING
```
This message was meant to detect unexpected `MethodType` which a
`ServerMethodDefinition` provides.
https://github.com/line/armeria/blob/49054ad7f22a7f2d64faaeb694674b0df09ad165/grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java#L163-L164
However, as `ArmeriaChannel` iterates `MethodType.vaules()` containing
`MethodType.UNKNOWN` to pre-build `RequestOptions` and reuse it.
https://github.com/line/armeria/blob/435aeedcb007382250e4ee71311a5ff2c56615ae/grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java#L71-L72
Slack thread: …
> Remove a false postive warning for unknown `MethodType` in `ArmeriaChannel`

- core/src/main/java/com/linecorp/armeria/server/ServiceRouteUtil.java
- core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
Motivation:
Assume that a cors preflight request is made for `http://host/path`. This PR attempts to ensure that cors preflight requests for paths with query parameters (i.e. `http://host/path?a=b`) are handled correctly.
Previously, cors preflight requests were handled correctly for paths with query parameters.
https://github.com/line/armeria/blob/dd33f1c84140383f750434690fec9915898f68cc/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L352-L354
Since armeria version 1.15.0, the raw path is used to query for a cors service. This change deviates from the previous behavior.
https://github.com/line/armeria/blob/0d3fa085fe0ab22f8818a7fcde363d0ce6ac196a/core/src/main/java/com/linecorp/armeria/server/ServiceRouteUtil.java#L48-L67
Modifications:
- Even for cors preflight …
> Correctly handle cors preflight requests for paths with query params

- core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
- core/src/test/java/com/linecorp/armeria/server/file/HttpFileTest.java
Motivation:
Able to serve file from OSGI bundle classloader
Modifications:
Add bundle: as the allowed protocol to create HttpFile
Result:
- Closes #4371
> Fix file serving from OSGI bundle classloader

- core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/common/stream/ClosedStreamException.java
- core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
Motivation:
`ClosedStreamException` is raised when a {@link StreamMessage} or an HTTP/2 stream
has been closed unexpectedly. Whereas, `ClosedSessionException` is raised
when the connection to the remote peer has been closed unexpectedly.
Modifications:
- Use `ClosedSessionException` and `ClosedStreamException` correctly according to its usage.
Result:
- `ClosedSessionException` and `ClosedStreamException` are raised correctly according to its usage.
> Use ClosedSessionException and ClosedStreamException correctly

- core/src/test/java/com/linecorp/armeria/common/FlagsTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtilTest.java
- dependencies.toml
- gradle/scripts/lib/scala.gradle
- gradle/wrapper/gradle-wrapper.properties
- graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceTest.java
- it/spring/boot2-tomcat8/build.gradle
- licenses/web-licenses.txt
- scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseAnnotatedServiceTest.scala
- spring/boot1-autoconfigure/build.gradle
- spring/boot2-autoconfigure/build.gradle
- tomcat8/build.gradle
- Brave 5.13.9 -> 5.13.10
- Bucket4j 7.5.0 -> 7.6.0
- Curator 5.2.1 -> 5.3.0
- Dropwizard metrics 2.1.0 -> 2.1.1
- GraphQL-Java 18.2 -> 19.0
- GraphQL-Kotlin 5.3.2 -> 6.1.0
- gRPC-Java 1.47.0 -> 1.48.0
- java-jwt 3.19.1 -> 4.0.0
- Jetty 9.4.46.v20220331 -> 9.4.48.v20220622
- kafka-clients 3.2.0 -> 3.2.1
- Kotlin 1.7.0 -> 1.7.10
- Kotlin Coroutine 1.6.3 -> 1.6.4
- Micrometer 1.9.1 -> 1.9.2
- Netty 4.1.78.Final -> 4.1.79.Final
- Protobuf 3.19.2 -> 3.21.1
- Reactor 3.4.19 -> 3.4.21
- RESTEasy 5.0.2.Final -> 5.0.4.Final
- Sangria 3.0.0 -> 3.0.1
- Scala 2.12.15 -> 2.12.16, 3.1.2 -> 3.1.3
- scala-collection-compat 2.7.0 -> 2.8.1
- Spring Boot 2.7.1 -> 2.7.2
- Spring Web 5.3.21 -> 5.3.22
- Tomcat8 8.5.78 -> 8.5.81
- Tomcat9 9.0.62 -> 9.0.65
- Build
- Checkstyle 10.3.1 -> 10.3.2
- Dagger 2.42 -> …
> Upgrade dependencies

- core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/SelectionTimeoutTest.java
Motivation:
If a selection timeout is larger than a response timeout, it is clamped
to a response timeout.
https://github.com/line/armeria/blob/554d5963bef33162b1cb077077336de3ef3aadfb/core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java#L96
It ignores the need for users to set large selection timeouts in a warmup
situation.
Modifications:
- Use `selectionTimeoutMillis` as is to schedule a selection timeout.
Result:
`EndpointSelector` now correctly waits for the selection timeout of an
`EndpointGroup`.
> Don't limit a max selection timeout to a response timeout in `EndpointSelector`

- grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlers.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlerTest.java
Motivation:
`UnframedErrorHandler#ofJson` and `UnframedErrorHandler#ofRichJson` perform similar tasks, but have a slightly different format. It is probably better that we unify the two APIs so that 1) users are less confused by similar APIs 2) and we have an API format that is widely used across different open sources.
Modifications:
- Copy contents of `UnframedErrorHandler#ofRichJson` to `UnframedErrorHandler#ofJson`, and add `grpc-code` for backwards compatibilty.
Result:
- Less confusing APIs
> Integrate `ofRichJson` to `ofJson`

- dependencies.toml
Motivation:
The dependency version of `com.google.guava:failureaccess` should be
`1.0.1` but Guava's version (`31.1-jre`) is set.
Actually, it does not cause any problems because only the metadata such
`exclusions` and `relocations` are used to shade Guava.
Anyway, it would be better to use the correct value for being future-proof.
Modifications:
- Set `com.google.guava:failureaccess` to 1.0.1
Result:
Fix a migration mistake.
> Fix the wrong Guava `failureaccess` version

- core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
- logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Motivation:
MDC properties are useful for logging data in a structured manner.
Currently, when a request/response is successful `req.content`, `res.content` is being filled.
However, there is no structured log which expresses why a request/response failed.
It would also be useful if users can accumulate failure reason via `req.cause`, `res.cause`
Modifications:
- Introduce `req.cause`, `res.cause` which represents the throwable by `Throwable#printStackTrace`
Result:
> Introduce a `BuiltInProperty` representing the request/response failure cause 

- .github/workflows/publish-site.yml
- .post-release-msg
Motivation:
As a part of the automation of the release process, I want to automatically
update https://armeria.dev when a new version is released.
Modifications:
- Add a new GitHub Actions job that deploys the Armeria site
using https://github.com/peaceiris/actions-gh-pages
Result:
One more step towards release automation.
> Automatically publish the Armeria site using GitHub Actions

- spring/boot2-actuator-autoconfigure/build.gradle
- spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ReactiveHealthEndpointWebExtensionUtil.java
- spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
- spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationServiceUtil.java
- spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaSpringActuatorReactiveIndicatorTest.java
- spring/boot2-webflux-autoconfigure/src/test/resources/config/application-test_actuator.yml
Motivation:
If an autoconfigure module is in the classpath, [HealthEndpointWebExtension](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/HealthEndpointWebExtension.java) is used for handling an actuator request.
Whereas, if a WebFlux module is also in the classpath, [ReactiveHealthEndpointWebExtension](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/ReactiveHealthEndpointWebExtension.java) is used which returns `Mono`.
We should handle the `Mono` response.
Modifications:
- Handle `Mono` response in `WebOperationService`.
Result:
- Close #4396 
- You can now use Armeria Spring actuator …
> Fix that reactive health endpoint is not handled correctly

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/ClassUtil.java
- core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayResponseConverterFunction.java
- core/src/main/java/com/linecorp/armeria/server/annotation/HttpFileResponseConverterFunction.java
- core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
- core/src/main/java/com/linecorp/armeria/server/annotation/ServerSentEventResponseConverterFunction.java
- core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/ClassUtilTest.java
- protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java
- protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java
- rxjava2/src/main/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunction.java
- rxjava3/src/main/java/com/linecorp/armeria/server/rxjava3/ObservableResponseConverterFunction.java
- scala/scala_2.13/src/test/scala/com/linecorp/armeria/server/ClassUtilTest.scala
- scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbConverterUtil.scala
- scalapb/scalapb_2.13/src/main/scala_2/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunction.scala
- scalapb/scalapb_3/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunction.scala
Motivation:
Currently, the behavior of `AnnotatedService` with void return type(including `Publisher<Void>` and `CompletableFuture<Void>`) is confusing and users often struggle to find the right way to return `204 No Content` with `AnnotatedService`.
- Adding `@StatusCode(204)` with class-level `@ProducesJson` results in 500 errors if the return type is `void`)
- Returning `Mono<Void>` or `CompletableFuture<Void>` gives 200 response by default while returning `void` gives 204.
Modifications:
- Make `AnnotatedService` not set `Content-Type` header when the `status.isContentAlwaysEmpty()` is `true`.
- Make `Publisher<Void>`, `CompletionStage<Void>` return type gives 204 status code by default.
Result:
- Closes #4390
- You no longer see 500 errors for returning `void`, `Publisher<Void>` or …
> Fix `AnnotatedService` behavior with `void` return types

- core/src/test/java/com/linecorp/armeria/client/endpoint/SelectionTimeoutTest.java
Motivation: 
https://github.com/line/armeria/issues/4407
Modifications:
- Increase the base timeout and tolerance
Result:
- Reduce noise in CI builds. 
- Fixes #4407
> Fix the test failure of `SelectionTimeoutTest.select_timeout()`

- core/src/main/java/com/linecorp/armeria/common/MediaType.java
- core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceResponseMediaTypeTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
Motivation:
Armeria `UnframedGrpcService` doesn't support alternative protobuf content types
Modifications:
- add `application/x-protobuf` and `application/x-google-protobuf` to MediaType
- add isProtobuf() function
- identify Protobuf contentType in UnframedGrpcService using isProtobuf()
- respond with request-given protobuf content type for deframed response
Result:
- Closes #4355
- Armeria `UnframedGrpcService` now supports `application/x-protobuf` and `application/x-google-protobuf` media types.
> Add support for alternative protobuf content types

- build.gradle
Motivation:
I found out that `String.substring()` is used without considering the length of the string.
We always use `6000` for the `endIndex` but the length of the string can be lower than the `endIndex`.
The length of the string should be greater or equal to the `endIndex`.
Modification:
- Use `Math.min` to apply a shorter length when calling `String.substring`.
Result:
- You no longer see `StringIndexOutOfBoundsException` from `reportFailedTests` task.
> Fix IndexOutOfBoundsException in build.gradle

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/ResponseConverterFunctionUtil.java
- core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunctionProvider.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/TestSpiConverterProvider.java
- protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java
Motivation:
`DelegatingResponseConverterFunctionProvider` and
`RequestConverterFunctionProvider` uses `create` as a prefix of the API.
But `ResponseConverterFunctionProvider` uses `new` as a prefix.
Consistent naming for similar APIs can give a better developer
experience.
Modifications:
- Rename `newResponseConverterFunction` to `createResponseConverterFunction`
in `ResponseConverterFunctionProvider`
Result:
Better developer experience.
Note that this is not an additional breaking change because it has not
been deployed yet.
> Rename `newResponseConverterFunction` to `createResponseConverterFunction` in `ResponseConverterFunctionProvider`

- site/src/pages/community/articles.mdx
We had Youtube live last April, and the site only showed the slides so far. 
The LINE DevRel team posted the recorded videos, so I'd like to add them to the site as well.
> Add Armeria Youtube videos

- spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
- spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationPriorityTest.java
- spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortHttpsTest.java
- spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/RetryableArmeriaServerGracefulShutdownLifecycle.java
- spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/RetryableArmeriaServerGracefulShutdownLifecycleTest.java
Motivation:
If a random port (0) for internal services or managed services is
specified in Spring configuration, the Spring integration module
allocate available ports early and use them to configure additional
service later.
https://github.com/line/armeria/blob/948763acc7911c951e37dbd35132edd253ea3934/spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java#L258-L260
This is not a problem in production mode.
However, in testing situations, many test servers are started simultaneously 
with a random port and the available ports can be acquired by them. #4391 #4329
Modifications:
- Add `RetryableArmeriaServerGracefulShutdownLifecycle` to retry a
server with a backoff at most N times.
Result:
- This is not a perfect …
> Retry when Spring tests fails to start a `Server` with a random port obtained in advance

- consul/src/main/java/com/linecorp/armeria/client/consul/ConsulEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupInitialFailureTest.java
- eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
- thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ClientRequestContextPushedOnCallbackTest.java
Motivation:
See #4404
If we add information of `DynamicEndpointGroup` to the `TimeoutException`, it would help to debug.
Modification:
- Add `EndpointGroup` to the `TimeoutException` message.
- Override `toString` in the subclasses of `DynamicEndpointGroup`
Result:
- Close #4404
> Add EndpointGroup info to TimeoutException for DynamicEndpointGroup.whenReady() future

- site/src/pages/docs/advanced-scalapb.mdx
Motivation:
Fix `ScalaPBJsonMarshaller` to `ScalaPbJsonMarshaller` in the ScalaPB integration documentation
Modifications:
- Just update code examples in the documentation
Result:
- No impact except for correcting the documentation
> Fix ScalaPbJsonMarshaller class name in doc

- protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionProvider.java
- protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java
- protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionTest.java
- protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionTest.java
- scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbConverterUtil.scala
- scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunctionTest.scala
- scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunctionTest.scala
Motivation:
`RequestConverterFunctionProvider#createResponseConverterFunction`, `ResponseConverterFunctionProvider#createResponseConverterFunction` is called to check if a request/response can be handled for all available request/response types in annotated services.
The previous `Protobuf[Request|Response]ConverterFunctionProvider` assumes that only 1-depth parameterized requests will be received. However, it is fairly common for json request/response objects to be defined with multiple levels of parameterized types.
This pull request fixes the current implementation so that at least a `ClassCastException` will not be thrown.
As a result of this PR, `Protobuf[Request|Response]ConverterFunctionProvider` will not handle nested protobuf types.
When used by default configuration, this causes …
> `Protobuf` converter providers don't attempt to illegally cast nested parameterized types

- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategyTest.java
Motivation:
`RampingUpEndpointWeightSelector` creates a new endpoint selector when a listener added to the `EndpointGroup` is invoked.
https://github.com/line/armeria/blob/790a2db01a8514b591bde90932ab18f63693829e/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java#L139-L145 
If a `DynamicEndpointGroup` is not initialized, listeners won't be invoked when the initial values are set.
So `.selectNow()` can raise a `NullPointerException`. 
https://github.com/line/armeria/blob/790a2db01a8514b591bde90932ab18f63693829e/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java#L175-L177
Modifications:
- Initialize `WeightedRandomDistributionEndpointSelector` with an empty selector which is replaced with the actual selector when the …
> Fix a bug where `WeightRampingUpStrategy` raises a NPE when a `DynamicEndpointGroup` is not initialized

- core/src/main/java/com/linecorp/armeria/common/stream/ByteStreamMessageOutputStream.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/stream/ByteStreamMessageOutputStreamTest.java
**Related Issue** #3092
```java
public HttpResponse serve(...) {
var stream = StreaMessage.fromOutputStream(this:startBlockingService);
return HttpRsponse.builder(headers)
.content(stream)
.build()
}
private void startBlockingService(OutputStream os) {
// perform blocking operation
var data0 = readDataFromSomeWhere0();
// os.write() will be blocked if the subscriber of the returned HttpResponse hasn't consumed data0 yet.
os.write(data0);
var data1 = readDataFromSomeWhere1();
os.write(data1);
os.close();
}
```
>   See comment https://github.com/line/armeria/pull/4186#issuecomment-1211699740
- We decide to introduce `StreamMessage.fromOutputStream()` on previous discussion
- Add `StreamMessage.fromOutputStream()`
- You can now use `StreamMessage.fromOutputStream()` to write on …
> Add `StreamMessage.fromOutputStream()`

- spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
- spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
Motivation:
`enable-auto-injection` spring configuration property was introduced but wasn't correctly added to `spring-configuration-metadata.json` by spring configuration processor.
This is because the current getter for `enable-auto-injection` property doesn't follow spring's getter naming convention, which expects the method name to start with `get` or `is`, and thus not being correctly recognized by the annotation processor.
See [PropertyDescriptorResolver.java#L104](https://github.com/spring-projects/spring-boot/blob/44b88cc88c2e848154a98ae17c03b1cd6c8f5830/spring-boot-project/spring-boot-tools/spring-boot-configuration-processor/src/main/java/org/springframework/boot/configurationprocessor/PropertyDescriptorResolver.java#L104) and …
> Add `enable-auto-injection` prop in `spring-configuration-metadata.json`

- core/src/main/java/com/linecorp/armeria/common/multipart/DefaultMultipart.java
- core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java
- core/src/main/java/com/linecorp/armeria/common/multipart/Multipart.java
- core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java
- core/src/test/java/com/linecorp/armeria/common/multipart/MimeParserTest.java
- core/src/test/java/com/linecorp/armeria/common/multipart/MultipartTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceMultipartTest.java
Motivation:
A `Multipart` can be terminated with the ending boundary without a body part. For example, the following request is totally valid:
```
POST /test.html HTTP/1.1
Host: example.org
Content-Type: multipart/form-data;boundary="boundary"
--boundary--
```
We must not raise an exception in that case.
Modifications:
- Do not raise an exception when `Multipart` has the ending boundary only.
- Propagate an exception in `MultipartDecoder` to the subscriber correctly.
- Change to return `false` from `StreamMessage.isEmpty()` when the `StreamMessage` is created from a empty `Multipart`
- Because it produces the ending boundary.
Result:
- You no longer see a 500 response when an empty multipart request is sent.
> Fix Multipart not to raise an exception when closing boundary only

- core/src/main/java/com/linecorp/armeria/server/docs/FieldInfoBuilder.java
- protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufNamedTypeInfoProvider.java
- protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufNamedTypeInfoProviderTest.java
- protobuf/src/test/proto/messages.proto
- protobuf/src/test/resources/com/linecorp/armeria/server/protobuf/ProtobufNamedTypeInfoProviderTest_specification.json5
Motivation:
`DocService` can throw an exception if a `protobuf` `Struct` doesn't have any fields. (which is valid)
See https://line-armeria.slack.com/archives/C1NGPBUH2/p1663556941998359 for more details
Modifications:
- Only iterate recursively through structs if children is non-empty
Result:
- `DocService` is displayed correctly.
> Protobuf docservice handles structs with empty children correctly

- core/src/main/java/com/linecorp/armeria/common/AggregatedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/common/HttpRequestUtil.java
- core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpRequestTest.java
Motivation:
I found out it's useful when:
- in a decorator, aggregating an `HttpRequest` to sign header with the body content
- converting the aggregated request back to the `HttpRequest` with the new header
Modification:
- Add `AggregatedHttpRequest.toHttpRequest(headers)`.
Result:
- You can now convert an `AggregatedHttpRequest` to an `HttpRequest` with a new headers.
> Add AggregatedHttpRequest.toHttpRequest(headers)

- benchmarks/jmh/build.gradle
- core/build.gradle
- core/src/main/java/com/linecorp/armeria/internal/common/DefaultJacksonObjectMapperProvider.java
- core/src/test/java/com/linecorp/armeria/internal/common/JacksonUtilTest.java
- dependencies.toml
- gradle/scripts/version-catalog.gradle
Motivation:
Armeria requires at least Java 8, and Jackson is the official JSON library of Armeria. `jackson-modules-java8` is de facto standard library for Java 8 ecosystem. There is no reason not to add them to the transitive dependencies. As a result, users don't need to manually align their Jackson version with Armeria's.
Modifications:
- Add `com.fasterxml.jackson.datatype:jackson-datatype-jdk8` and `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` as transitive dependencies.
- Miscellaneous) Reorganize `dependencies.toml` so that all dependencies declare their version using `version.ref` which in turn helps maintainers upgrade versions more conveniently.
Result:
- `com.fasterxml.jackson.datatype:jackson-datatype-jdk8` and …
> Add `jackson-modules-java8` dependency to the core module

- grpc/src/main/java/com/linecorp/armeria/server/grpc/DefaultHttpJsonTranscodingOptions.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingOptions.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingOptionsBuilder.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingQueryParamMatchRule.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingQueryParamNaming.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingOptionsBuilderTest.java
- grpc/src/test/proto/com/linecorp/armeria/grpc/testing/transcoding.proto
Motivation:
fixes #4401 
Modifications:
- Add HttpJsonTranscodingOptions and HttpJsonTranscodingOptionsBuilder
- add GrpcServiceBuilder Api that consumes HttpJsonTranscodingOptions when setting enableHttpJsonTranscoding
- check HttpJsonTranscodingOptions in HttpJsonTranscodingService, then add fields with camelCase keys in buildField function if camelCaseQueryParam option is set to true
Result:
- Closes #4401
- No breaking changes: changes are only applied when the new camelCaseQueryParam option is set to true
- HttpJsonTranscoding endpoint can handle both snake_case and camelCase form of query parameters when option is set
```java
HttpJsonTranscodingOptions options =
HttpJsonTranscodingOptions.builder()
.queryParamMatchRules(LOWER_CAMEL_CASE)
...
.build();
GrpcService.builder()
// Enable …
```
> Support camelcase for HttpJsonTranscodingService Query Parameters

- core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
- core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
- core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
- core/src/main/java/com/linecorp/armeria/common/AggregationOptions.java
- core/src/main/java/com/linecorp/armeria/common/AggregationOptionsBuilder.java
- core/src/main/java/com/linecorp/armeria/common/DefaultAggregationOptions.java
- core/src/main/java/com/linecorp/armeria/common/HttpData.java
- core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
- core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
- core/src/main/java/com/linecorp/armeria/common/stream/AggregationSupport.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/main/java/com/linecorp/armeria/unsafe/PooledObjects.java
- core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
- core/src/test/java/com/linecorp/armeria/common/AggregationOptionsTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/DefaultHttpRequestTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/DefaultHttpResponseTest.java
- eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
- grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/UnaryServerCall.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceItTest.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceSupportHttpJsonTranscodingTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java
- thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
- thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
Motivation:
We provide a way to cache `HttpRequest.aggregate()` in #4366. It can be mainly used in a decorator to get the body of an `HttpRequest`. When `HttpRequest.aggregate()` is called in a decorator, if the destination service is an annotated service, there's no problem. However, if a gRPC service or a Thrift service calls `HttpRequest.aggregateWithPooledObjects()`, the service raises an exception.
Modifications:
- Add `AggregationOptionsBuilder.usePooledObjects(alloc, preferCached)`
- If the `preferCached` is true, it returns the cached aggregated message.
Result:
- `GrpcService` and `ThriftService` no longer throw double subscription exceptions when the request is aggregated in a decorator.
- (Deprecated) `HttpRequest.aggregateWithPooledObjects()` and …
> Return cached aggregated message for following withPooledObjects call

- grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/InvalidResponseLengthTest.java
Motivation:
If a wrong content-length is set, the request/stream is reset by the Netty HTTP/2 codec. Most gRPC server call implmentations do not set a `content-length` to response headers. But some gRPC implementations such as Monix-gRPC send a `content-length` which was in the request content-length. I guess the runtime uses the incoming `Metadata` as the response `Metadata` itself.
Related: https://github.com/monix/monix-grpc/issues/43
Modifications:
- Remove the `content-length` in headers of the gRPC streaming response if set
Result:
- A custom content-length is automatically stripped when response streaming is used in `GrpcService`.
> Remove an invalid `content-length` in a gRPC streaming response.

- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
Motivation:
Wrong response contenttype served for http json transcoding endpoints as result of #4364 
Modifications:
- since AbstractUnframedGrpcService$frameAndServe uses the provided responseContentType parameter directly as the resulting http contenttype, application/json should be provided in HttpJsonTranscodingService instead of application/grpc+json
- alternative would be to respond with the request contenttype ex) JSON -> JSON / JSON_UTF_8 -> JSON_UTF_8 
Result:
- Closes #4473
> Respond with application/json for httpjson transcoding endpoints

- core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
- core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
- core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
- core/src/test/java/com/linecorp/armeria/common/RequestContextWrapperTest.java
Motivation:
RequestContextWrapper$delegate is deprecated since #4308 
Modifications:
- replaced all occurrences of delegate() with unwrap()
> Remove use of deprecated method RequestContextWrapper$delegate

- grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePlugin.java
- grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePluginTest.java
Motivation:
`GrpcDocServicePlugin` fails when using wrapped `GrpcService` since 1.18.0.
Modifications:
- Use unwrapped `GrpcService` in `generateSpecification` of `GrpcDocServicePlugin`.
Result:
- Closes #4487.
- GrpcDocServicPlugin works with GrpcService when HTTP JSON transcoding is enabled and GrpcService is wrapped.
> Fix failure of `GrpcDocServicePlugin` when `HttpEndpointSupport` is wrapped

- core/src/main/java/com/linecorp/armeria/common/stream/CancelledSubscriptionException.java
- core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/test/java/com/linecorp/armeria/server/Http1KeepAliveTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingFailureTest.java
Motivation:
If `connection: close` header is recevied, `HttpServerHandler` closes a connection when an `HttpResponse` is completed.
https://github.com/line/armeria/blob/f6c4debed749f77d71aec836e98bdffef6537273/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L412-L425 However, `HttpResponse` completion does not guarantee that the response is fully written to the connection. If a response write starts after the completion of `HttpResponse.whenComplete()`, a response could write to a closed connection which causes
`io.netty.channel.StacklessClosedChannelException`.
Modifications:
- Start the post-process of a response after the response is really written to the channel.
- Add `completionFuture` and make it complete when `AbstractHttpResponseHandler` finishes all write …
> Fix a bug where a connection is closed before a response is written in HTTP/1.x

- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/test/java/com/linecorp/armeria/server/AggregatedHttpResponseHandlerTest.java
Motivation:
`AbstractHttpResponseHandler` writes the response body generated by a service as it is, even if the method it handles always has empty response body, such as HEAD.
Modification:
- Fixed `AbstractHttpResponseHandler` so it doesn't write the response body when the request method is HEAD.
- Also, explicitly released the body which was unnecessarily generated by a service.
Result:
- Armeria doesn't send a bad response with non-empty body anymore when:
- a service's `ExchangeType` is `UNARY`; and
- a service generates non-empty body for a HEAD request.
- Fixes #4511
> Ensure response body is not sent for a HEAD request

- core/src/main/java/com/linecorp/armeria/server/Server.java
Motivation:
Clean up dead code that was introduced by https://github.com/line/armeria/commit/aa647fae9278fa54c4f303c29e1db8f058fbaf78 and removed by https://github.com/line/armeria/commit/84dd0cfea367f2c41720d13cb87a5bf477174d00
Modifications:
- Remove dead code `Server#shutdownExecutor`
Result:
- No impact
> Clean up dead code in `Server`

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/DefaultNamedTypeInfoProvider.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/DefaultNamedTypeInfoProviderTest.java
- core/src/test/resources/com/linecorp/armeria/internal/server/annotation/JsonNamedTypeInfoProviderTest_specification.json5
- kotlin/src/test/kotlin/com/linecorp/armeria/internal/server/annotation/DataClassDefaultNameTypeInfoProviderTest.kt
Motivation:
- #4506
Modifications:
* Use `BeanPropertyDefinition#getInternalName` to find the right constructor parameter or getter.
- Unlike `BeanPropertyDefinition#getName` `#getInternalName` is derived from accessor and is not based on annotations or naming strategy.
* Use `@JsonProperty` annotation-based matching strategy to find the right field or constructor parameter for the fields without accessor(getter).
- `#getInternalName` is generated based on annotations or naming strategy if there's no available accessor for a field.
Limitation:
* `@JsonProperty` annotation-based field matching strategy may not cover POJOs without `@JsonProperty` and de/serialized with  non-default naming strategy .
Result:
- Closes #4506
> Create correct `FieldInfo` for renamed object fields in `DocService`

- docs-client/src/components/VariableList/index.tsx
- docs-client/src/containers/MethodPage/ReturnType.tsx
- docs-client/src/containers/MethodPage/index.tsx
Motivation:
Especially for gRPC methods, not seeing the fields of parameters and return type is very frustrating. You should click and visit another page to see the parameters and the return type. It also makes using the `debug form` harder.
Modifications:
- Update `MethodPage` to have collapsible request and response types.
Result:
- Closes #4481 
https://user-images.githubusercontent.com/7023385/196294177-758e5b6a-9cb5-426a-afb8-85b54b5a6447.mov
> make params and return collapsible

- core/src/main/java/com/linecorp/armeria/internal/common/AbstractHttp2ConnectionHandler.java
Motivation:
We sometimes encounter situations where  HTTP/2 header frames are lost due to an exception.
Although a RST frame is sent in this case, remotes are still able to send data for the offending stream, which ends up in error logs which armeria doesn't understand.
e.g.
```
io.netty.handler.codec.http2.Http2Exception: Stream 1147 does not exist
```
Although normally it might be noisy to be alerted of such failures, it might be useful to view such logs when debugging.
Modifications:
- Added logging for HTTP/2 `StreamError`
- Added logging for connection errors just in case as well.
Result:
- Easier to debug http2 failure logs.
> Add debug logs for http2 stream errors

- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
Motivation:
Current codes spit warn logs when an interceptor throws an exception. 
```java
private <I, O> void startCall(ServerMethodDefinition<I, O> methodDef, ServiceRequestContext ctx,
HttpRequest req, MethodDescriptor<I, O> methodDescriptor,
AbstractServerCall<I, O> call) {
final Listener<I> listener;
try {
listener = methodDef.getServerCallHandler()
.startCall(call, MetadataUtil.copyFromHeaders(req.headers()));
} catch (Throwable t) {
call.setListener((Listener<I>) EMPTY_LISTENER);
final Metadata metadata = new Metadata();
call.close(GrpcStatus.fromThrowable(statusFunction, ctx, t, metadata), metadata);
logger.warn(
"Exception thrown from streaming request stub method before processing any request data" +
" - this is likely a bug in the stub implementation.", t);
return;
}
```
On the …
> Remove warn log that is thrown when an interceptor throws an exception

- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/test/java/com/linecorp/armeria/server/UnfinishedRequestTest.java
Motivation:
If a connection is closed, unfinished requests are aborted.
https://github.com/line/armeria/blob/e94bbd075b745098a76e514e870a6c1803cbeec8/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L236-L246
When the unfinished requests are aborted, their responses are aborted as well. The abortion signal completes `resWriteFuture` exceptionally and its callback tries to remove the request from `unfinishedRequests`.
https://github.com/line/armeria/blob/e94bbd075b745098a76e514e870a6c1803cbeec8/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L418-L430
This recursive removal while iterating `unfinishedRequests` causes `ConcurrentModificationException`.
Modifications:
- Do not remove a request from `unfinishedRequests` if it is called in `cleanup()` …
> Fix `ConcurrentModificationException` in `HttpServerHandler`

- site/src/pages/release-notes/1.20.3.mdx
Motivation:
When the target release version changed from 1.21.0 to 1.20.3, some PRs were already merged into the master branch. So their milestone should be changed and the release notes also need to be updated.
Modifications:
- Add #4515, #4507, #4484 and #4492 to the release notes.
Result:
Update the missing issues and PRs.
> Update missing release notes in 1.20.3

- core/src/main/java/com/linecorp/armeria/internal/common/LeakTracingRequestContextStorage.java
- it/trace-context-leak/src/test/java/com/linecorp/armeria/internal/common/TraceRequestContextLeakTest.java
Motivation:
I found that the log contains too many duplicate information while I was investingating on #4498 The `TraceableRequestContext` has the delagate which another `TraceableRequestContext` so it shows the duplicate stack trace multiple times by the number of the context is pushed.
```
Trying to call object wrapped with context [sreqId=.../test#GET]
The previous RequestContext is pushed at the following stacktrace
at com.linecorp.armeria.internal.common.LeakTracingRequestContextStorage$TraceableServiceRequestContext.<init>(LeakTracingRequestContextStorage.java:118)
...
The previous RequestContext is pushed at the following stacktrace
at com.linecorp.armeria.internal.common.LeakTracingRequestContextStorage$TraceableServiceRequestContext.<init>(LeakTracingRequestContextStorage.java:118 …
```
> Remove duplicate information from context leak stack trace

- core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/test/java/com/linecorp/armeria/server/LongUrlTest.java
Motivation:
When a long URI is received, [`414 Request-URI Too Long`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414) is expected to return. However, currently, `400 Bad Request` is returned.
Modifications:
- If the cause of a decoder failure for HTTP/1 request is `TooLongHttpLineException`, return 414.
- Propagate decoder failures to `ServerErrorHandler.onProtocolViolation()`.
- Added a debug log to see a received `Http2Settings` easily as `HttpServerHandler` did.
Result:
- `414 Request-URI Too Long` is now correctly returned for long URIs in HTTP/1.
- Fixes #4478
> Fix to return `414 Request-URI Too Long` for a long URI

- core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
- core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithDecoratorTest.java
Motivation:
When an exception is raised in the decorator between `RetryingClient` and the network layer, the exception is not correctly set to `RequestLog.responseCause()` so that users cannot use the exception to make a decision.
Modification:
- Call `derivedCtx`'s `RequestLogBuilder.endResponse(cause)` when the response is completed exceptionally.
Result:
- Close #4558 
- You can now use the exception, which is raised in the decorator, to make a decision for retrying.
> Fix to set cause correctly in RetryingClient

- core/src/main/java/com/linecorp/armeria/client/AbstractEventLoopState.java
- core/src/main/java/com/linecorp/armeria/client/DefaultEventLoopScheduler.java
- core/src/main/java/com/linecorp/armeria/client/HeapBasedEventLoopState.java
- core/src/main/java/com/linecorp/armeria/client/OneEventLoopState.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/FileWatcherRegistry.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/RestartableThread.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRandomDistributionEndpointSelector.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
Motivation:
synchronized should be removed because they should be avoided when using virtual threads
resolves part of https://github.com/line/armeria/issues/4510
Modifications:
- Replaced all _synchronized_  under core/client package with ReentrantLock
> Replace synchronized under core/client with ReentrantLock

- core/src/main/java/com/linecorp/armeria/internal/common/BuiltInDependencyInjector.java
- core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
- core/src/main/java/com/linecorp/armeria/server/annotation/decorator/LoggingDecoratorFactoryFunction.java
- core/src/main/java/com/linecorp/armeria/server/annotation/decorator/RateLimitingDecoratorFactoryFunction.java
- core/src/main/java/com/linecorp/armeria/server/annotation/decorator/RequestTimeout.java
- core/src/main/java/com/linecorp/armeria/server/annotation/decorator/RequestTimeoutDecoratorFunction.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/RequestTimeoutAnnotationTest.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
Motivation:
Provide a way to set a request timeout using annotation
Modifications:
- Add @interface RequestTimeout
- Add RequestTimeoutDecoratorFunction
Result:
- Closes #4463
- users can use RequestTimeout annotation to set request timeout to service methods
> implement request timeout annotation

- core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
- core/src/test/java/com/linecorp/armeria/server/docs/DocServiceReconfigureTest.java
Motivation:
Previously, `DocService` wasn't able to handle the changed services as a result of `reconfigure`.
```
sb = Server.builder()
.annotatedService("/hello", new HelloService())
.serviceUnder("/docs", DocService.builder().build())
...
sb.reconfigure(sb2 -> sb2.annotatedService("/hello2", new HelloService())
.serviceUnder("/docs", DocService.builder().build()))
```
- If a shared `DocService` is used, services wouldn't be updated and the old specification would be used.
- If a new `DocService` is added, appropriate callbacks wouldn't be called and `/specifications.json` would result in a 404.
https://github.com/line/armeria/blob/cae3b6da373101c0976e2d00f1f3cbb706d07e00/core/src/main/java/com/linecorp/armeria/server/docs/DocService.java#L217-L220
We may note that `Server#configs` is …
> Reload `DocService` on server reconfigure

- core/src/main/java/com/linecorp/armeria/common/util/AbstractListenable.java
- core/src/main/java/com/linecorp/armeria/common/util/AbstractOption.java
- core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java
- core/src/main/java/com/linecorp/armeria/common/util/ShutdownHooks.java
- core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java
Motivation:
for virtual threading, we should replace synchronized with reentrantLock
resolves part of https://github.com/line/armeria/issues/4510
Modifications:
- replace all synchronized with reetrantLock under `common/util`
> Replace synchronized under common/util with reentrantLock

- core/src/main/java/com/linecorp/armeria/client/AbstractDnsResolverBuilder.java
- core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
- core/src/main/java/com/linecorp/armeria/client/DnsCacheBuilder.java
- core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- it/flags-provider/src/test/java/com/linecorp/armeria/common/BaseFlagsProvider.java
- it/flags-provider/src/test/java/com/linecorp/armeria/common/FlagsProviderTest.java
- settings/checkstyle/checkstyle-suppressions.xml
- settings/checkstyle/checkstyle.xml
- site/src/pages/docs/advanced-metrics.mdx
- site/src/pages/docs/client-circuit-breaker.mdx
- spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
- spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Motivation:
Most open source projects using `micrometer` use `Metrics.globalRegistry()` as the default `MeterRegistry`.
At the same time, the default `meterRegistry` used by `armeria` is `Metrics.globalRegistry()`.
This may be problematic since users may be interested in only `armeria` metrics, but metrics for other integration may also be included. I propose that `armeria` records metrics to `Flags#meterRegistry()` by default.
Note: I've intentionally excluded adding this flag to `SystemDefaultFlags`. If needed, I suppose we can accept a class name and instantiate it although I think such a flag wouldn't have much usage.
Modifications:
- Add a new `Flags#meterRegistry` which returns a `CompositeMeterRegistry`.
- Change all internal usages of `Metrics#globalRegistry` to …
> Provide a way to configure the default `MeterRegistry` from `Flags`

- core/src/test/java/com/linecorp/armeria/client/DocServiceAssetCompressionTest.java
- docs-client/webpack.config.ts
Motivation:
The size of an uncompressed js file for `DocService` is about 2.5MB. The size is quite huge. It would be worth compressing the file since modern browsers can decompress the file after receiving it. If some user agents do not support compression, DocService automatically uncompresses the content on the fly before sending out the file.
Modifications:
- Add `deleteOriginalAssets` option to `CompressionWebpackPlugin`
https://webpack.js.org/plugins/compression-webpack-plugin/#deleteoriginalassets
- Add a unit test to ensure the original asserts are deleted
Result:
- Deleted uncompressed `DocService` assets that were added unintentionally.
- Fixes #4500
> Remove uncompressed JavaScript files from the core artifact.

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
Motivation:
Currently for annotated services, the return type of void methods can be `200` if a `@Produces` annotation is added.
```
@Get("/")
public void get() {
// 204
}
@Get("/")
@ProducesJson
public void getJson() {
// 200
}
```
We have decided to always return 204 (with the exception of `@StatusCode`) for void methods.
1. It may be more confusing for users under what conditions 200/204 is returned.
2. It is difficult to keep track and return valid values for each `Content-Type`. For instance, `200` with `Content-Type: application/json` returns `null` with the current implementation by default.
However, `200 OK` with `Content-Type: application/xml` won't return a valid `xml`. (`armeria` returns an empty response)
Modifications:
- Set the default return status code to 204 irregardless …
> Return 204 on void return types irregardless of `@Produces`

- core/src/main/java/com/linecorp/armeria/client/Clients.java
- core/src/main/java/com/linecorp/armeria/client/DefaultBlockingWebClient.java
- core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
- core/src/main/java/com/linecorp/armeria/client/DefaultRestClient.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
- core/src/test/java/com/linecorp/armeria/client/DerivedClientTest.java
- scala/scala_2.13/src/main/resources/META-INF/services/com.linecorp.armeria.client.ClientFactoryProvider
- scala/scala_2.13/src/main/scala/com/linecorp/armeria/client/scala/ScalaRestClient.scala
- scala/scala_2.13/src/main/scala/com/linecorp/armeria/client/scala/ScalaRestClientFactory.scala
- scala/scala_2.13/src/main/scala/com/linecorp/armeria/client/scala/ScalaRestClientFactoryProvider.scala
- scala/scala_2.13/src/test/scala/com/linecorp/armeria/client/scala/RestClientSuite.scala
Motivation:
When a new client is derived from an existing client using `Clients.newDerivedClient()`, all options should be copied to the new client and the original `EndpointGroup` should be reserved. It seems to have already been considered by `newDerivedBuilder()` but there is one API missing. https://github.com/line/armeria/blob/81ac954d41ee8420898ba298f9d0a766c3d37b71/core/src/main/java/com/linecorp/armeria/client/Clients.java#L317-L319
The following API called `builder` instead of `newDerivedBuilder`. 
https://github.com/line/armeria/blob/81ac954d41ee8420898ba298f9d0a766c3d37b71/core/src/main/java/com/linecorp/armeria/client/Clients.java#L303-L306
As a consequence, a derived client tries to send a request to `armeria-group-`. …
> Fix a bug where an EndpointGroup is not copied to a derived client.

- core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
- core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
- core/src/test/java/com/linecorp/armeria/server/Http1PipelineTest.java
Motivation:
Let's say a late request is completed first while the first request is being processed. The response to the late request is added to `pendingWritesMap` to preserve the order of responses in HTTP/1. Before the response is added to a queue, `lastResponseHeadersId` is updated to the ID of the late request.
https://github.com/line/armeria/blob/b127cd27252f6a454130f66d1175a06faed01f09/core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java#L79-L95
It is a bug because the actual headers are queued and not written. Although a normal response for the first request is completed, the response is canceled because `HttpResponseSubscriber` assumes the order of response is reversed.
https://github.com/line/armeria/blob/0930b184bf00f98692a2e0b3eb044410e78a8173/core/src/ma …
> Fix a deadlock when a late response are written first in HTTP/1 pipelining

- core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
- it/flags-provider/src/test/java/com/linecorp/armeria/common/BaseFlagsProvider.java
Motivation:
We've decided to return `MeterRegistry` for `Flags#meterRegistry` on the grounds that
1) We would be exposing a mutable API by returning a `CompositeMeterRegistry`
2) MeterRegistry is more general
Modifications:
- Modify all instances of `CompositeMeterRegistry` to `MeterRegistry`
Result:
- `Flags.meterRegistry` returns a `MeterRegistry`
> `Flags#meterRegistry` returns a `MeterRegistry`

- build.gradle
- core/build.gradle
- gradle/scripts/README.md
- gradle/scripts/lib/java.gradle
- gradle/scripts/settings-flags.gradle
- settings.gradle
Motivation:
Some modules may need to target a java version higher than other modules to compile correctly.
This PR proposes a `java(\\d+)` flag which sets the target java version for compilation.
Modifications:
- Remove special logic for `:examples` in `build.gradle`
- Set the `-release` flag in `core/build.gradle` for `buildJdkVersion >= 9` to avoid compilation errors.
- Without this change, the actual error message might be shadowed (i.e. invalid flag exception instead of invalid class version exception)
- Introduce an `extractTargetJavaVersion` method which extracts the target version from a `java(\\d+)` flag.
- The default is set to 8. If a lower version than the default is specified an exception is thrown. (e.g. `java3`)
- Set the compatibility to `targetJavaVersion`, and skip tests …
> Add a `java(\\d+)` flag

- core/src/main/java/com/linecorp/armeria/client/RequestOptionsSetters.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
- core/src/test/java/com/linecorp/armeria/server/PortBasedVirtualHostTest.java
Motivation:
A port-based virtual host does not have a specific hostname so it doesn't make sense to configure TLS. Users need to configure TLS to the `ServerBuilder` which is the default host or create a name-based virtual host to apply different TLS settings.
Modification:
- Raise an exception if TLS is set to a port-based virtual host.
- Make `RequestOptionsSetters` public to render the Javadoc correctly.
Result:
- An exception is raised if TLS is set to a port-based virtual host.
> Raise an exception if TLS is set to port-based virtual host

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/HandlerRegistry.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBlockingTest.java
- grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
Motivation:
It is described in the following Issue.
https://github.com/line/armeria/issues/4389
Modifications:
- When building `HandlerRegistry`, find `ServerMethodDefinition`  that needs to be executed on the blocking executor
- In `FramedGrpcService#startCall`, in addition to `useBlockingTaskExecutor` field, check if the blocking executor is used for each `ServerMethodDefinition`.
Result:
- Closes #4389
- Users can easily know whether a service runs on a blocking executor.
- Selectively apply a blocking executor to the methods.
```java
class MyGrpcServiceImpl extends MyGrpcServiceImplBase {
@Blocking
public void blockingCall(...) {
...
}
public void nonBlockingCall(...) {
...
}
}
@Blocking
class MyBlockingGrpcServiceImpl extends MyGrpcServiceImplBase {
public void blockingCall1(...) { …
```
> Support @Blocking annotation for gRPC services

- core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
- core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncoders.java
- core/src/test/java/com/linecorp/armeria/client/DocServiceAssetCompressionTest.java
- docs-client/build.gradle
- docs-client/webpack.config.ts
Motivation:
Some platforms do not support Brotli by default.
If the DocService assets are created using brotli and a client sends the request with `accept-encoding: gzip`, the client wouldn't be able to use DocService.
Modification:
- Use Gzip by default for compressing assets
Result:
- DocService front-end assets are now compressed using Gzip.
> Use Gzip for compressing DocService front-end assets by default

- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
- docs-client/src/containers/MethodPage/DebugPage.tsx
- docs-client/src/containers/MethodPage/RequestBody.tsx
- docs-client/src/lib/strings.ts
Motivation:
Setting multiple example requests aren't displayed contrary to multiple headers/queries/paths.
Modifications:
- Add a select component which allows users to select a request.
- Truncate the displayed value in case the example request is too long.
Result:
- #4576
> Support example request dropdown for `DocService`

- core/src/main/java/com/linecorp/armeria/common/encoding/AbstractStreamDecoder.java
- core/src/main/java/com/linecorp/armeria/common/encoding/BrotliStreamDecoder.java
- core/src/main/java/com/linecorp/armeria/common/encoding/ZlibStreamDecoder.java
- core/src/test/java/com/linecorp/armeria/server/encoding/DecoderLengthLimitTest.java
Motivation:
`maxAllocation` of `ZlibDecoder` does not limit the max length of the entire stream data. It only limits the length of each chunk of data.
Modifications:
- Make `ZlibStreamDecoder` check the total length after decompression to validate the streaming content length.
Result:
`DecodingService` and `DecodingClient` now correctly limit the max length of decompressed streaming data.
> Fix to limit the max length for compressed chunked data

- core/src/test/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroupTest.java
Motivation:
This change resolves local build failure for some users with space character in their home directory's folder names path leading up to server-list.properties file.
Modifications:
- `final Path resourcePath = new File(resourceUrl.getFile()).toPath();` was replaced with `final Path resourcePath = new File(resourceUrl.toURI().getPath()).toPath();` in PropertiesEndpointGroupTest.java
Result:
- Users facing this issue now have a successful local build.
> Fix local build failure from no such file exception caused by space character in path to server-list.properties

- spring/boot2-actuator-autoconfigure/src/test/resources/application-autoConfTest.yml
- spring/boot2-actuator-autoconfigure/src/test/resources/application-managedMetricPath.yml
- spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationNetUtil.java
- spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
- spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java
- spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalhostAddressTest.java
- spring/boot2-autoconfigure/src/test/resources/config/application-autoConfTest.yml
- spring/boot2-autoconfigure/src/test/resources/config/application-deprecatedIpTest.yml
- spring/boot2-autoconfigure/src/test/resources/config/application-localhostAddressTest.yml
Motivation:
Spring allows Users to specify a hostname because Spring converts the input to an InetAddress.
So we need to also allow users to specify a hostname.
Modifications:
- adding ArmeriaSettings.address whose type is InetAddress
- deprecating ArmeriaSettings.ip
Result:
- Closes #4597
> Deprecate ArmeriaSettings.ip and add ArmeriaSettings.address

- gradle/scripts/.gitrepo
- gradle/scripts/README.md
- gradle/scripts/lib/java.gradle
- site/src/pages/community/developer-guide.mdx
- site/src/pages/docs/setup.mdx
Motivation:
Update the URLs of OpenJDK in the documents because the new OpenJDK binaries from AdoptOpenJDK are no longer distributed and have been migrated to Eclipse Temurin.
It seems that this project have already used Eclipse Temurin on CI.
Modifications:
- Update the documents and URLs
Result:
- The URLs refer to Eclipse Temurin
> Use Eclipse Temurin instead of AdoptOpenJDK

- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
- core/src/main/java/com/linecorp/armeria/common/logging/RequestLogProperty.java
- core/src/main/java/com/linecorp/armeria/common/logging/RequestOnlyLog.java
- core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java
- core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
Motivation:
A server admin might want to track the usage of an API that who calls it. If we provide a way to set the authenticated user and print it out using the `%u` format of the access log, the admin can easily track it.
Related: https://httpd.apache.org/docs/current/mod/mod_log_config.html
Modifications:
- Add `RequestLogBuilder.authenticatedUser(name)` and `RequestLog.authenticatedUser()`.
- Print `RequestLog.authenticatedUser()` using `%u` format of the access log.
Result:
- You can now set and see the authenticated user of a request in an access log.
> Add `RequestLog.authenticatedUser()`

- site/src/components/emoji.tsx
Motivation:
Emoji link is broken in https://armeria.dev/.
The emoji URL generated by `Emoji` is https://twemoji.maxcdn.com/2/svg//2728.svg,
but expected link is https://twemoji.maxcdn.com/2/svg/2728.svg.
Basically, this is a bug of library `react-easy-emoji`.
The library should remove `/` from `baseUrl` when `option.size` is empty string.
https://github.com/appfigures/react-easy-emoji/blob/v1.8.1/lib/makeTwemojiRenderer.js#L35
As a workaround, we can specify `baseUrl` as URL without ending with `/` and `size` as empty string.
Modifications:
- Modify `baseUrl` parameter in `site/src/components/emoji.tsx` not to end with `/`.
Result:
Upstream issue:
- https://github.com/appfigures/react-easy-emoji/issues/25
> Fix broken emoji in web site

- core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/server/Server.java
- core/src/test/java/com/linecorp/armeria/ReconfigureTlsTest.java
- core/src/test/java/com/linecorp/armeria/server/ReconfigureTlsTest.java
Motivation:
Currently, a TLS configuration is not updated with `Server.reconfigure()` because `HttpServerPipelineConfigurator` refers to the `sslContexts` made when a server is built initially and the reference won't change.
Modifications:
- Make `HttpServerPipelineConfigurator` read `sslContexts` from `UpdatableServerConfig` whenever a new HTTPS connection starts.
Result:
You can now dynamically update TLS configurations with `Server.reconfigure()`.
> Make TLS settings updated with `Server.reconfigure()`

- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
- grpc/src/test/proto/com/linecorp/armeria/grpc/testing/transcoding.proto
Motivation:
Bug in HttpJsonTranscodingService when serializing FieldMask parameter
Result:
- Closes #4633
> Fix HttpJsonTranscodingService to accept google.protobuf.FieldMask field as string

- core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java
- core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java
Motivation:
According to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) the valid characters for the path component are:
a-z A-Z 0-9 . - _ ~ ! $ & ' ( ) * + , ; = : @
Modifications:
- [] was removed from allowedPathChars in PathAndQuery.java
- broken tests was fixed in PathAndQueryTest.java by removing [] and %5B%5D from declared and expected values respectively in method allReservedCharacters().
Result:
- Should close #4607
- [] no longer allowed as path chars
> Remove [] from allowed path chars

- site/src/pages/tutorials/grpc/blog/define-service.mdx
- site/src/pages/tutorials/grpc/blog/implement-create.mdx
- site/src/pages/tutorials/grpc/blog/implement-delete.mdx
- site/src/pages/tutorials/grpc/blog/implement-read.mdx
- site/src/pages/tutorials/grpc/blog/implement-update.mdx
- site/src/pages/tutorials/grpc/blog/index.mdx
- site/src/pages/tutorials/grpc/blog/run-service.mdx
Motivation:
1. build.gradle code blocks in [grpc tutorial introduction - Try writing blog service yourself](https://armeria.dev/tutorials/grpc/blog#try-writing-blog-service-yourself) miss the armeria-grpc artifact.
2. BlogService.java code blocks in [Test run service - 1. Declare an empty service](https://armeria.dev/tutorials/grpc/blog/run-service#1-declare-an-empty-service) miss the declaration of logger. It may have been omitted by the author's intention but [REST tutorials](https://armeria.dev/tutorials/rest/blog/create-server/#1-create-a-server-instance) have explicitly declared logger variable. Therefore, I think it is good to specify it in the grpc tutorial as well.
3. Typo in code blocks of step 3 of [Test run service - 4. Write a …
> Fix a typo of grpc tutorials

- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
- grpc/src/test/proto/com/linecorp/armeria/grpc/testing/transcoding.proto
Motivation:
Bug in HttpJsonTranscodingService when finding descriptor for nested message types
Result:
- Closes #4631
> Fix HttpJsonTranscodingService to find field descriptor with `field.getMessageType()`

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
- it/thrift0.9.1/src/test/thrift/main.thrift
- thrift/thrift0.12/build.gradle
- thrift/thrift0.12/src/test/thrift/TTextProtocolTest.thrift
- thrift/thrift0.12/src/test/thrift/main.thrift
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDescriptiveTypeInfoProvider.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDescriptiveTypeInfoProviderTest.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePluginTest.java
- thrift/thrift0.13/src/test/thrift/main.thrift
- thrift/thrift0.17/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePluginTest.java
- thrift/thrift0.9/build.gradle
- thrift/thrift0.9/src/test/thrift/main.thrift
Motivation:
Currently, we don't resolve the Thrift [typedef](https://thrift.apache.org/docs/idl#typedef) fields correctly.
Modifications:
- Resolve Thrift typedef fields correctly using `Field.getGenericType()`.
- Use `i8` instead of `byte` for Thrift 0.12+ to remove the warning.
Result:
- The Thrift typedefs are correctly resolved.
> Support Thrift TypeDef in DocService

- grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/AsyncServerInterceptor.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/DeferredListener.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/AsyncServerInterceptorTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/DeferredListenerTest.java
Motivation:
The upstream `ServerInterceptor` of gRPC-Java does not allow executing an asynchronous task in an interceptor. The API is designed to return a `Listener` synchronously.
https://github.com/grpc/grpc-java/blob/b7164f0791d405e002d67c1e01603e0df9d1cc9f/api/src/main/java/io/grpc/ServerInterceptor.java#L55
It makes users difficult to use the existing asynchronous API in the interceptors. The blocking threads can be exhausted easily if there are slow responses from servers having problems.
It should be useful if you can use `CompletableFuture` to compose asynchronous tasks without blocking threads.
The original idea is suggested from https://github.com/line/armeria/issues/4275#issuecomment-1144604754 /cc @be-hase
Modifications:
- Add `AsyncServerInterceptor` that allow returning …
> Add `AsyncServerInterceptor` for gRPC services

- core/src/main/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessage.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessageTest.java
Motivation:
We got a report about `NullPointerException` from LINE internally.
```
java.lang.NullPointerException: at index 0
at com.linecorp.armeria.internal.shaded.guava.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:229)
at com.linecorp.armeria.internal.shaded.guava.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:219)
at com.linecorp.armeria.internal.shaded.guava.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:213)
at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.construct(ImmutableList.java:353)
at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.of(ImmutableList.java:109)
at com.linecorp.armeria.internal.common.stream.TwoElementFixedStreamMessage.drainAll(TwoElementFixedStreamMessage.java:75)
at …
```
> Fix a `NullPointerException` raised while an aborted `FixedStreamMessage` is being collected.

- core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
- core/src/test/java/com/linecorp/armeria/server/Http1ServerEarlyDisconnectionTest.java
Motivation:
It would be legitimate that an HTTP/1 client closes a connection after data is fully received. Although the connection is closed, the stream on the server side can be still open. Because `HttpResponseSubscriber` may be complete after fully sending data and then receiving `onComplete()` signal. Receiving `onComplete()`, `HttpResponseSubscriber` tries to write an empty chunk as a mark of EOS to the disconnected channel. https://github.com/line/armeria/blob/fee87f8da942d0e6343e814489524b73db60ef3b/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L317-L320
The write attempt would fail with `ClosedSessionException` and the failure is set to `responseCause`. Practically, `responseCause` is meaningless and false positive.
Modifications:
- Check a connection …
> Fix a bug where `ClosedSessionException` is set to `responseCause` for a success response.

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactoryRegistry.java
- kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/DataClassDocServiceTest.kt
Motivation:
When an annotation is applied to Kotlin data class, Kotlin compiler constructor parameters with the annotation and adds the fields as well.
```kt
data class ExampleQueries(
@Param
val application: String,
@Param
val topic: String,
@Param
val group: String,
)
```
Annotated services extract both the fields from the constructor and fields using reflection. The problem was reported by #3454 and fixed by #3461. However, there is a bug in detecting duplicates.
See for the detail. https://github.com/line/armeria/issues/3454#issuecomment-1408392569
Modifications:
- Check both `httpElementName` and `anntationType()` if they are not equal to provide a consistent comparison.
Result:
You no longer see duplicate parameters in `DocService` when parameter annotations for a request object are …
> Fix a bug where duplicate parameters are shown in DocService

- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/test/java/com/linecorp/armeria/server/LongHttp1HeadersTest.java
Motivation:
Netty HTTP/1 codec raises `TooLongHttpHeaderException` if headers exceed the max length limit. However, `Http1RequestDecoder` does not take account into `TooLongHttpLineException` and returns "400 Bad Request" instead.
Modifications:
- Make `Http1RequestDecoder` return `431 Request Header Fields Too Large` if a Netty HttpRequest fails with `TooLongHttpHeaderException`
Result:
- `431 Request Header Fields Too Large` is now returned instead of `400 Bad Request` if the size of headers exceeds `ServerBuilder.http1MaxHeaderSize()`.
- Fixes #4609
> Return "431 Request Header Fields Too Large" for long headers on HTTP/1

- core/src/main/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessage.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/EventExecutorWrapper.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessageTest.java
A `NullPointerException` caused due to a race condition between `collect()` and `abort()` was fixed in #4652. Howerver, we got another reoprt from Slack community. https://line-armeria.slack.com/archives/C1NGPBUH2/p1675994120153789
```java
2023-02-09T02:08:55,526 [armeria-common-worker-epoll-3-3] WARN  com.linecorp.armeria.internal.common.stream.FixedStreamMessage - Subscriber.onError() should not raise an exception. subscriber: null
com.linecorp.armeria.common.util.CompositeException: 2 exceptions occurred.
at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.onError0(FixedStreamMessage.java:247) ~[armeria-1.21.1-SNAPSHOT.jar:?]
at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.onError(FixedStreamMessage.java:237) ~[armeria-1.21.1-SNAPSHOT.jar:?]
at …
```
> Fix another `NullPointerException` in `FixedStreamMessage`

- build.gradle
Motivation:
While publishing jobs were running, I was able to observe the following warning even on the latest java version.
```
Expiring Daemon because JVM heap space is exhausted
```
https://github.com/line/armeria/actions/runs/4130787453/jobs/7137809757
We also recently observed builds in java 8 fail due to insufficient heap space.
- Machine specs
- Windows: 2 cores, 7 GB
- Mac: 3 cores, 14 GB
- Linux: 8 cores, 16 GB (c5.2xlarge)
ref: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
By default, we use the number of cores as the count of forked processes:
https://github.com/line/armeria/blob/a5ab6f556c2d647b3a62080354c0d2bea77188c4/build.gradle#L91
We also allocate up to 1.5G for the main gradle task (although I believe when run with the …
> Increase max heap size for each java fork

- core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandler.java
Motivation:
Provide a more recent version of the RFC document that describes the same thing
Modifications:
Fix KeepAliveHandler#onPingAck comment
Result:
Closes #4665
> Fix onPingAck comment

- site/src/pages/release-notes/1.16.2.mdx
- site/src/pages/release-notes/1.22.0.mdx
- Added the release note for 1.16.2, the backport release for #4608 and #4583.
- Added @rhodo to the release note for 1.22.0 because he is the person who reported #4583 initially.
> Add the release note for 1.16.2 and credit @rhodo in 1.22.0

- gradle.properties
- site/src/pages/community/developer-guide.mdx
Motivation:
- Our developer guide tells our contributors to use an old JDK that doesn't work for our build anymore.
- Some contributors reported they are getting `OOME` when trying to build with the default JVM settings. (Credit: @chris-ryan-square)
Modifications:
- Explicitly stated that we need JDK 17. Removed `-19` part to keep things simple and straightforward.
- Increased the default JVM heap size from 1536 (128 * 12) to 1792 (128 * 14) to reduce the chance of `OOME`.
Result:
Better experience to our fellow contributors.
> Update the build requirements and the default JVM options

- site/src/pages/release-notes/1.22.0.mdx
Motivation:
Modifications:
- Fix the micrometer version in the release notes for 1.22.0 to the correct version
Result:
- A more accurate description of upgraded dependencies
> Fix the micrometer version in release notes for 1.22.0

- .github/workflows/actions_build.yml
Motivation:
We recently enabled GitHub merge queue to make sure the PR being merged doesn't introduce any unexpected build failure.
However, it seems like we have explicitly tell GitHub to run builds, on top of just enabling merge queue.
Modifications:
- Add `merge_group:` event listener to `actions_build.yml` so that GitHub triggers the build for the changesets in the merge queue before merging anything.
Result:
> Build the changesets in GitHub merge queue before merging

- core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageWriter.java
- core/src/main/java/com/linecorp/armeria/common/stream/ByteStreamMessageOutputStream.java
- core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWriter.java
- core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
**Related Issue** #4253 
https://github.com/line/armeria/blob/0016f868b15cae6d8568004f3288ed86621a7b93/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageAndWriter.java#L23
- As there is no public API for a streaming writer, we directly instantiate DefaultStreamMessage.
```java
StreamWriter writer = new DefaultStreamMessage(); // directly using DefaultStreamMessage constructor
writer.write(...);
writer.close();
```
- #4186  will provide a way to write a StreamMessage using OutputStream
- But to convert a StreamMessage to OutputStream, users should use directly `DefaultStreamMessage` as well
- That might be not what we want. `DefaultStreamMessage` is `@UnstableApi` and a part of implementations, so we have to hide the implementation detail
- Rename `StreaMessageAndWrtier` …
> Add `StreamMessageWriter` and `StreamMessage.streaming()`

- core/src/main/java/com/linecorp/armeria/common/stream/PathStreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/stream/PathStreamMessageTest.java
**Related PR** https://github.com/line/armeria/pull/4058
> https://github.com/line/armeria/blob/bc48105148d652e2e48e788c94bec007882c31dc/core/src/main/java/com/linecorp/armeria/common/stream/DefaultByteStreamMessage.java#L140
> 
> (Just curiotiy) Should we handle `overflow` here similar with `DefaultByteStreamMessage`?
> e.g offset(5) + lenth(Long.MAX_VALUE) = end(-xxx.., overflow) 
> 
> ```java
> assert position <= end; // if offset(5) + lenth(Long.MAX(), end is -xxx and this assertion failed
> if (position < end) { ... }
> ```
> on `L343`, we check `assert position <= end` so this assertion may failed on overflow case
- See https://github.com/line/armeria/pull/4058#discussion_r1118292165
- We should handle overflow on `PathStream.range(offset, length)` properly
- PathStream.range(1, …
> Handle overflow on `PathStreamMessage#range(offset, length)`

- build.gradle
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/InitiateConnectionShutdownTest.java
- core/src/test/java/com/linecorp/armeria/server/ServerTest.java
- core/src/test/java/com/linecorp/armeria/server/SniServerTest.java
- core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
- dependencies.toml
- testing-internal/build.gradle
- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerTest.java
- thrift/thrift0.12/build.gradle
- thrift/thrift0.13/build.gradle
- thrift/thrift0.14/build.gradle
- thrift/thrift0.15/build.gradle
- thrift/thrift0.16/build.gradle
- thrift/thrift0.17/build.gradle
- thrift/thrift0.9/build.gradle
- tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/ManagedTomcatServiceTest.java
- tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/UnmanagedTomcatServiceTest.java
Motivation:
Apache HttpClient works a little differently from armeria's client and is useful for internal testing.
For example, square brackets are not encoded by default.
I would like to use HttpClient's HTTP/2 functionality which is available starting from version 5 for use in the following PR.
https://github.com/line/armeria/pull/4721
Note that thrift client has a direct dependency on HttpClient4, and thus the dependency remains for thrift modules
Modifications:
- Migrate to HttpClient 5
- Use HttpClient 4 for thrift modules
Result:
- Most internal usages are migrated to Apache HttpClient 5
> Upgrade to Apache HttpClient 5

- core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
- core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
- core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
- core/src/test/java/com/linecorp/armeria/server/AbsoluteRequestUriTest.java
Motivation:
HTTP/1 allows a client to send a request whose request path is actually an absolute URI:
GET https://foo.com/bar HTTP/1.1
Host: proxy.com
However, Armeria does not accept such a request and returns a 400 Bad Request response.
Unfortunately, we can't allow such absolute URIs as they are because:
- Armeria's HTTP message model is based on HTTP/2, which doesn't allow an absolute path in `:path` pseudo header.
- Existing Armeria applications also assume that a request path is always an absolute path in Armeria.
Modifications:
- Added a new configuration property named `absoluteUriTransformer` that allows a user to transform the absolute URI in an HTTP/1 request into an absolute path. e.g.
```java
builder.absoluteUriTransformer(absoluteUri -> {
// https://foo.com/bar -> /bar
return …
```
> Allow serving an HTTP/1 request with absolute URI.

- core/src/main/java/com/linecorp/armeria/server/FallbackService.java
- core/src/main/java/com/linecorp/armeria/server/RegexPathMappingWithPrefix.java
- core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
- core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
- core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceImplicitHeadTest.java
- core/src/test/java/com/linecorp/armeria/server/CachingRoutingContextTest.java
- core/src/test/java/com/linecorp/armeria/server/RoutingContextTest.java
- core/src/test/java/com/linecorp/armeria/server/VirtualHostTest.java
Motivation:
To resolve #4038 
> Many server frameworks(e.g. [Spring](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-requestmapping-head-options), express) create an implicit request mapping to HEAD when there's a request handler for GET.
> 
> The feature can be useful as client sometimes just want to check the existence of resources without receiving the whole body and almost always the handlers for @Get and @Head should be the same.
> 
> Currently, armeria needs 3 annotations to do the same thing.
> 
> ```
> @Get
> @Head
> @Path("/some-file")
> public HttpResponse someFile(ServiceRequestContext ctx) {
>     // ...
>     return client.execute(RequestHeaders.of(ctx.method(), "/some-object-storage-path"));
> }
> ```
Modifications:
- Implement …
> Add implicit request mapping to @Head when the service is mapped to @Get

- core/src/main/java/com/linecorp/armeria/common/stream/AbstractByteStreamMessageBuilder.java
- core/src/main/java/com/linecorp/armeria/common/stream/InputStreamStreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/InputStreamStreamMessageBuilder.java
- core/src/main/java/com/linecorp/armeria/common/stream/PathStreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/PathStreamMessageBuilder.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/main/java/com/linecorp/armeria/internal/common/stream/InternalStreamMessageUtil.java
- core/src/test/java/com/linecorp/armeria/common/stream/InputStreamStreamMessageTckTest.java
- core/src/test/java/com/linecorp/armeria/common/stream/InputStreamStreamMessageTest.java
**Related Issue** #3937
```java
static StreamMessage<HttpData> of(InputStream inputStream) {...}
```
- It would be nice if we provide a way to convert an InputStream to a StreamMessage<HttpData> that splits the binary by the bufferSize.
- Add `StreamMessage.of(inputStream)`
- Add `InputStreamStreamMessage` and builder
- You can now use `StreamMessage.of(inputStream)` to convert an `InputStream` to `StreamMessaeg<HttpData>` that splits the binary by the bufferSize
- Close https://github.com/line/armeria/issues/3937 issue
> Add `StreamMessage.of(inputStream)`

- core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java
- core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java
Motivation:
When a path or query string contains a `#` character, Armeria normalizes it into `#` regardless whether its percent-encoded or not. For example, the following two paths are normalized into `/#.json`, which is not desirable:
- `/#.json`
- `/%23.json`
Modifications:
- Made `PathAndQuery` always percent-encode `#`.
- Renamed the poorly named `RESERVER_CHARS`.
Result:
- Fixes #4751
- `#` character is now always percent-encoded in both path and query string.
> Fix `#` character encoding in URIs

- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
Motivation:
Typo in `WeightedRoundRobinSelector` javadoc 
Modifications:
Below javadoc should be modified. It seems that the weights are 3, 5, 7 but the javadoc indicates as if `b` has the highest weight. 
<as-is>
`if endpoint weights are 3,5,7, then select result is abcabcabcbcbcbb abcabcabcbcbcbb ...`
<to-be>
`if endpoint weights are 3,5,7, then select result is abcabcabcbcbccc abcabcabcbcbccc ...`
Result:
Fix typo
> Fix javadocs for `WeightedRoundRobinSelector`

- core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroupBuilder.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroupBuilder.java
- core/src/main/java/com/linecorp/armeria/internal/client/dns/DefaultDnsResolver.java
- core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilderTest.java
- core/src/test/java/com/linecorp/armeria/internal/client/dns/DefaultDnsResolverTest.java
Motivation:
Implementing #4695, I assumed that a DNS resolver is executed by an event loop.
- `DnsEndpointGroup` schedules DNS queries using an event loop.
https://github.com/line/armeria/blob/10583eb0f34e0de9ef38654d808b1ce3db7eb0c2/core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java#L115
- `RefreshingAddressResolver.doResolve(...)` is invoked by the event loop that is set to `DnsResolverGroupBuilder`.
https://github.com/line/armeria/blob/39efeb240b95c8969c81e94eca8ed07f1f4026df/core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java#L107
However, both assumptions were wrong.
- `DnsEndpointGroup` and `DefaultDnsResolver` can have different event loops if no event loops are specified. Because `DnsEndpointGroupBuilder.eventLoop()` returns a …
> Ensure `DnsResolver` is executed by `EventLoop`

- core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
Motivation:
Prevent an **IllegalArgumentException** from being thrown when the following conditions match
- `Http1VerboseWriteException` is sampled
- Both calls to `Http1ObjectEncoder.write` fail for the same reason (same `Throwable` instance)
Modifications:
- Fix Throwable combination code
Result:
- Closes #4749
> Prevent self reference in addSuppressed

- junit5/src/main/java/com/linecorp/armeria/testing/server/ServiceRequestContextCaptor.java
Motivation:
ClientRequestContextCaptor has isEmpty() but ServiceRequestContextCaptor doesn't.
Modifications:
- Add ServiceRequestContextCaptor.isEmpty()
Result:
- Closes #4757
> Add ServiceRequestContextCaptor.isEmpty()

- build.gradle
- gradle.properties
Our build still fails when running with JDK 8 even after increasing the max heap size. Increase again, this time to 2GiB. Java compiler's max heap size also has been increased to 768MiB.
> Increase the JVM heap for Gradle to avoid OOME

- core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
- core/src/test/java/com/linecorp/armeria/server/HeadMethodLeakTest.java
Motivation:
If a HEAD request is received, a server should discard the content of a response and return headers only. However, there was a [regression](https://github.com/line/armeria/pull/3956/files#diff-368938fb6a538f212fadf2ca09779cd5a6e05002c393454e7fc4b03361b588ccR153) in which pooled data is not released if the response body has more than two chunks. `setDone(false)` does not cancel the upstream. 
https://github.com/line/armeria/blob/a83388c18b31d400f36ff7346902b30f9c194ee7/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L152-L161 
We should instead use `setDone(true)` to release unconsumed data.
Modifications:
- Cancel an `HttpResponse`'s body if a HEAD method is received or data is published or a stream is closed.
Result:
Fixed a memory leak where a …
> Fix buffer leak with HEAD requests

- core/src/main/java/com/linecorp/armeria/internal/common/HttpMessageAggregator.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
- core/src/test/java/com/linecorp/armeria/server/HeadMethodLeakTest.java
Motivation:
A pooled `ByteBuf` instance is reused so we can't tell its `refCnt` is 0 forever after the `ByteBuf` is freed.
https://github.com/netty/netty/blob/44b7e5b12d8dff3d07dfb773680120cc20f7e203/buffer/src/main/java/io/netty/buffer/PooledDirectByteBuf.java#L38
When I logged `refCount` of `ByteBuf`s in `HeadMethodLeakTest`, they became 1 from 0 during assertions.
Modifications:
- Use Unpooled allocator instead
Result:
Clean up flaky tests
> Fix flaky `HeadMethodLeakTest`

- core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
- core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
- core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
- core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Motivation:
As described in #4753, user-configured `RetryConfigMapping` is evaluated multiple time per original/logical request. Twice for the original try, and an additional evaluation per each try. Not only this behavior could be surprising for users, it's also a performance penalty as most of the `RetryConfigMapping`s idempotent (don't change in between the retries).
Modifications:
- Only evaluate `RetryConfigMapping` once and store the result in `ClientReqeustContext`.
Result:
- Closes #4753
> Fix a bug where RetryConfigMapping is evaluated multiple times per req

- core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java
- core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleBuilder.java
- core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContentBuilder.java
- core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleBuilder.java
- core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
- core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java
- core/src/main/java/com/linecorp/armeria/internal/common/InternalGrpcWebTrailers.java
- core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientRuleTest.java
- core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleBuilderTest.java
- core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilderTest.java
- core/src/test/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderTest.java
- grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/GrpcWebTrailers.java
- grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcWebTrailers.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientRetryTest.java
Related issue: #4496
Motivation:
A user might want to write a circuit breaker or retry rule that makes a decision based on gRPC trailers. Accessing gRPC trailers can be tricky because they can be present in either HTTP headers, trailers or even content (if gRPC Web). It would save a lot of duplicate effort to write a filter that checks difference places if we provide a built-in filter for gRPC trailers.
Modifications:
- Add `AbstractRuleBuilder.onGrpcTrailers()`
- Modify `AbstractRuleBuilderUtil` so it handles a gRPC trailers filter.
- Move the core logic of `GrpcWebTrailers` to `InternalGrpcWebTrailers` in the `core` module, because otherwise `AbstractRuleBuilderUtil` cannot access gRPC Web trailers.
- Add `AbstractRuleBuilder.requiresResponseTrailers()` to reduce duplication
- Add …
> Add `AbstractRuleBuilder.onGrpcTrailers()`

- logback/src/main/java/com/linecorp/armeria/common/logback/LoggingEventWrapper.java
Motivation:
Improve compatibility with logback 1.3.x.
`armeria-logback` has compatibility with logback 1.3.x and logstash-logback-encoder 5.3:
* logback 1.3.x introduces the `ILoggingEvent#getInstant()` method which returns null by default.
* logstash-logback-encoder 5.3 uses `ILoggingEvent#getInstant()` in case of using logback 1.3.x or higher
* As a result, logging system is broken when uses logback 1.3.x and logstash-logback-encoder 5.3.
This change enables us to migrate Spring Boot 3 smoothly.
I also submitted the PR to logback https://github.com/qos-ch/logback/pull/652 
But, I am not sure that the PR will be accepted.
Modifications:
- Add method `LoggingEventWrapper#getInstant()` that implements `ILoggingEvent#getInstatnt()`
- It doesn't have `@Override` because armeria depends on …
> Add newly-added method from logback 1.3 to support compatibility

- saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java
Motivation:
Recently, I've had trouble debugging an `InvalidSamlRequestException`. It turned out to be that the timestamp of the instance was lagged so the validation failed. I think if we add the current time, it will be a lot easier to debug this lagging problem.
Modification:
- Add the current time to `InvalidSamlRequestException` when the exception is raised by the time lagging.
Result:
- Better debugging
> Add current time to the invalid SAML request exception

- core/src/main/java/com/linecorp/armeria/common/stream/FuseableStreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/stream/FuseableStreamMessageTest.java
Related issue: #4852
Motivation:
`FuseableStreamMessage.collect()` throws a `NPE` when only `mapError()` is applied to a normal `StreamMessage`.
```java
StreamMessage.of(1, 2, 3, 4)
.mapError(IllegalStateException::new)
// Raises a NullPointerException
.collect().join();
```
The `function` field in `FuseableStreamMessage` can be null if no `map()` is applied to `FuseableStreamMessage`.
https://github.com/line/armeria/blob/871d87297e4d051241589cb1ae95641cbc83f880/core/src/main/java/com/linecorp/armeria/common/stream/FuseableStreamMessage.java#L162
The problem only happens when `collect()` method is called. `subscribe()` method already takes the case into account.
Modifications:
- Use the original object as is if `function` is null.
Result:
- You no longer see `NullPointerException` when …
> Fix `NullPointerException` in `FuseableStreamMessage`

- .github/workflows/actions_build.yml
- benchmarks/jmh/build.gradle
- build.gradle
- core/build.gradle
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessageVerification.java
- gradle/scripts/.gitrepo
- gradle/scripts/lib/common-dependencies.gradle
- gradle/scripts/lib/common-git.gradle
- gradle/scripts/lib/java-alpn.gradle
- gradle/scripts/lib/java-coverage.gradle
- gradle/scripts/lib/java-rpc-proto.gradle
- gradle/scripts/lib/java-rpc-thrift.gradle
- gradle/scripts/lib/java-shade.gradle
- gradle/scripts/lib/java.gradle
- gradle/scripts/lib/kotlin.gradle
- gradle/scripts/lib/scala.gradle
- gradle/wrapper/gradle-wrapper.properties
- it/micrometer1.3/build.gradle
- it/thrift0.9.1/build.gradle
- junit4/build.gradle
- kotlin/build.gradle.kts
- settings.gradle
- spring/boot2-actuator-autoconfigure/build.gradle
- spring/boot2-autoconfigure/build.gradle
- spring/boot2-webflux-autoconfigure/build.gradle
- spring/boot3-actuator-autoconfigure/build.gradle
- spring/boot3-autoconfigure/build.gradle
- spring/boot3-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationTest.java
Motivation:
[Gradle 8](https://docs.gradle.org/8.0/release-notes.html) has been released.
Modifications:
- In Gradle 8, dependencies can't be declared in a resolvable configuration (`canBeResolved=true`). `gradle-scripts` used resolvable configurations such as `compileClasspath`, `runtimeClasspath` to inject platform dependencies. https://github.com/line/armeria/blob/20969832640bcc0fa66edc68c531891ab35cea25/gradle/scripts/lib/common-dependencies.gradle#L180-L183
```
* Where: Script '.../gradle/scripts/lib/common-dependencies.gradle'
* What went wrong: A problem occurred configuring project ':foobar'.
> Dependencies can not be declared against the `compileClasspath` configuration.
```
`platform` dependencies should be added to non resolvable and non
configurations. There is no workaround …
> Upgrade Gradle to 8.1.1

- grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcCallOptions.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Motivation:
While building the decorator-middleware for the gRPC clients, it can be useful to get access to the instance of the `CallOptions` used to send the client request. This PR introduces the new (experimental) API to fish `CallOptions` out of the `RequestContext` object. 
Modifications:
- Added new `GrpcCallOptions` API to save and retrieve gRPC's `CallOptions` to/from `RequestContext`
- ArmeriaChannel now saves the instance of `CallOptions` onto the context
- Added a test for the new functionality
Result:
- Closes #4776
> Introduce GrpcCallOptions

- it/thrift-fullcamel/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePluginTest.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePlugin.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceEntry.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePluginTest.java
- thrift/thrift0.17/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePluginTest.java
Motivation:
Fix the problem that ThriftDocServicePlugin maybe failed when thrift proto compile with fullcamel option.
For example, thrift proto like this
```
service GreetService {
string greet_hi(1: string name);
}
```
when use `java:fullcamel` in thrift compile, the doc service will failed to start, with exception like this
```
Caused by: java.lang.IllegalStateException: failed to find a class: hello.GreetService$greetHi_args
at com.linecorp.armeria.internal.server.thrift.ThriftDocServicePlugin.newMethodInfo(ThriftDocServicePlugin.java:210) ~[armeria-thrift0.9-1.23.1.jar:?]
at com.linecorp.armeria.internal.server.thrift.ThriftDocServicePlugin.lambda$newServiceInfo$4(ThriftDocServicePlugin.java:181) ~[armeria-thrift0.9-1.23.1.jar:?]
at …
```
> Fix `ThriftDocServicePlugin` maybe failed when thrift proto compile with fullcamel option

- core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/client/logging/ContentPreviewingClient.java
- core/src/main/java/com/linecorp/armeria/common/ResponseCompleteException.java
- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/main/java/com/linecorp/armeria/common/stream/CancelledSubscriptionException.java
- core/src/main/java/com/linecorp/armeria/common/util/UnmodifiableFuture.java
- core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java
- core/src/main/java/com/linecorp/armeria/internal/common/stream/EmptyFixedStreamMessage.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java
- core/src/test/java/com/linecorp/armeria/client/HttpResponseDecoderTest.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageCollectingTest.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java
- core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/HttpRequestNotSubscribedTest.java
- core/src/test/java/com/linecorp/armeria/server/Http1KeepAliveTest.java
- core/src/test/java/com/linecorp/armeria/server/UnfinishedRequestTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingFailureTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
Motivation:
A customer wants #4508 to be backported to 1.16.x because they require
more time to upgrade to a newer Armeria version.
Modifications:
- Backported #4508
- Backported #4494 because #4508 depends on it
- Backported #4524 that fixes a regression introduced in #4508
Result:
The customer buys some time until they upgrade Armeria.
> Backport #4494, #4508 and #4524 to 1.16

- site/src/pages/docs/server-timeouts.mdx
- site/src/pages/docs/toc.json
Motivation:
- Related issue: #4595
- Documentation exists for [configuring timeouts on the client-side](https://armeria.dev/docs/client-timeouts) of an application, but there is no documentation available for configuring timeouts on the server-side.
Modifications:
- Create a documentation of several ways to override request timeouts on a server.
Result:
- Closes #4595
> Add documentation for timeout at the server side

- graphql/src/main/java/com/linecorp/armeria/server/graphql/ExecutionIdGenerator.java
- graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilder.java
- graphql/src/test/java/com/linecorp/armeria/server/graphql/ExecutionIdGeneratorTest.java
Motivation:
- Currently, if an `ExecutionId` is not explicitly set for a query in GraphQL-Java, a default `ExecutionId` is generated using `UUID.randomUUID()`. However, this default approach has drawbacks. To address these limitations, this PR introduces the ability for users to customize the generation of `ExecutionId`.
Modifications:
- Introduce an `ExecutionIdGenerator` to enable customization of the execution ID generation mechanism using the `ServiceRequestContext`, query, and operation name.
- The `of()` method in the `ExecutionIdGenerator` interface provides a default implementation that automatically assigns the execution ID as the ID of the `ServiceRequestContext`, allowing for convenient generation of execution IDs.
- The method `executionIdGenerator()`, is introduced in the …
> Provide a way to customize GraphQL ExecutionId

- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/InternalTestingBlockHoundIntegration.java
Motivation:
```
java.base/java.io.PrintStream.implWriteln(PrintStream.java:848)
at java.base/java.io.PrintStream.writeln(PrintStream.java:825)
at java.base/java.io.PrintStream.println(PrintStream.java:1167)
at org.slf4j.impl.SimpleLogger.write(SimpleLogger.java:341)
at org.slf4j.impl.SimpleLogger.log(SimpleLogger.java:310)
at org.slf4j.impl.SimpleLogger.formatAndLog(SimpleLogger.java:379)
at org.slf4j.impl.SimpleLogger.warn(SimpleLogger.java:562)
at com.linecorp.armeria.common.logging.LogLevel.log(LogLevel.java:155)
```
Since logging can occur not only at `LogLevel.log` but from other code points as well, I think it's fine to just ignore `SimpleLogger`.
Modifications:
- Add `SimpleLogger.write` to list of rules to ignore to our internal blockhound rule.
Result:
- More stable builds
Credit …
> Allow `slf4j` `SimpleLogger` to block the eventloop when running the CI

- core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
- core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/ReservedCharsIntegrationTest.java
Motivation:
`?` is not in the preserved encoding character set. As a result, if `%3F` or `%3f` is included in a request path, it is converted into `?`.
https://github.com/line/armeria/blob/0df139a41cac430b3805f2774ac6d0c8ca4b4a68/core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java#L60-L60
`/foo/x%3Fy.json`, for example, is decoded into `/foo/x?y.json`. When a server parses the request path, `/foo/x` will be the path component, and `y.json` will be the query component. Although they wanted to send a path ending with `.json`.
Modifications:
- Add `?` to `PATH_MUST_PRESERVE_ENCODING` so that `RequestTarget` does not decode `%3F` in a path into `?`
Result:
You can now correctly send percent-encoded `?` in a request path.
> Preseve `%3F` (?) character in a request path

- core/src/main/java/com/linecorp/armeria/server/docs/JsonSchemaGenerator.java
- core/src/main/java/com/linecorp/armeria/server/docs/ServiceSpecification.java
- core/src/test/java/com/linecorp/armeria/server/docs/ServiceSpecificationTest.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/DuplicateStructInfoSpecificationTest.java
Motivation:
If a generated protobuf `Message` is used with both a gRPC service and an annotated service, `StructInfo.alias()` could be removed while merging `StructInfo`s. Because `ServiceSpecification.merge()` deduplicates `StructInfo`s that have the same name.
https://github.com/line/armeria/blob/6b7b1b0b638f3d780f5910a133daf24902af8d93/core/src/main/java/com/linecorp/armeria/server/docs/ServiceSpecification.java#L151-L155
Background:
gRPC `DocService` creates `StructInfo` from protobuf's `Descriptor`. The generated `Message` class is unknown in the `Descriptor`. Only the message name defined in the `.proto` file can be extracted to `StructInfo`.
However, annotated services make `StructInfo` from `Message` generated by the protobuf compiler. The class name of `Message` is injected as an …
> Fixed a bug where `StructInfo` is not linked in DocService when a protobuf is used both for gRPC and annotated

- core/src/test/java/com/linecorp/armeria/client/endpoint/FileWatcherRegistryTest.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroupTest.java
Motivation:
At least on macOS 13.4 (and probably other OSes), `WatchService` seems not to notify the file changes quickly enough. As a result, we see the following tests fail:
- `FileWatcherRegistryTest.runnableWithExceptionContinuesRun`
- `PropertiesEndpointGroupTest.endpointChangePropagatesToListeners`
- `PropertiesEndpointGroupTest.propertiesFileRestart`
- `PropertiesEndpointGroupTest.propertiesFileUpdatesCorrectly`
Modifications:
- Migrated `FileWatcherRegistryTest` and `PropertiesEndpointGroupTest` from JUnit 4 to 5
- Added `@EnabledForJreRange` annotation on the problematic tests
Result:
- Build is more stable on the environment where `WatchService` is not very responsive.
- Fixes #3474 and #3075
> Disable the tests that involve NIO.2 `WatchService` on old JRE

- build.gradle
- consul/build.gradle
- consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
- core/build.gradle
- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/FileWatcherRegistryTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
- gradle/scripts/lib/java-shade.gradle
- gradle/scripts/lib/java.gradle
- gradle/scripts/lib/scala.gradle
- graphql/src/main/java/com/linecorp/armeria/server/graphql/DefaultGraphqlService.java
- spring/boot2-webflux-autoconfigure/build.gradle
- spring/boot3-webflux-autoconfigure/build.gradle
- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java
- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolderExtension.java
Motivation:
This PR fixes `shadedTest` task to run with JUnit 5 and the bugs that weren't caught by CI builds because of the aforementioned bug.
- `shadedTest`:
`shadedTest` was configured to run test suites with JUnit 4. It caused CI builds to pass successfully, although they failed with `gradle test` when I run locally.
While upgrading the Gradle version to 8, we had to use JVM test suites to use both JUnit and TestNG. In Gradle 8, `Test` didn't allow overring test frameworks. For that reason, `test` was migrated to test suites but `shadedTest` hasn't changed.
- `RequestLog.resposneCause()`:
Recently, I've encountered the following test failure repeatedly when I was running tests locally.
```java
GrpcClientTest > errorNoMessage() FAILED
Expecting actual not to …
```
> Fix a bug where `shadedTest` tests only Junit 4 suites

- .github/workflows/actions_build.yml
- settings.gradle
Motivation:
Note that github secrets are not available for actions triggered by forked pull requests: [ref](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks)
We have two choices
1. Using `pull_request` events:
- For push (merge) events, secrets are applied and the build cache is updated
- For pull requests from forked repositories, the build cache isn't updated. This means we can't take advantage of the build cache when checking out and reviewing pull requests locally.
- We can expect fewer cache uploaded, but higher hit rate
2. Using `pull_request_target` events:
- For all opened pull requests, secrets are applied and the build cache is updated
- For this type of event, the `.github` workflow files …
> Try enabling gradle enterprise

- grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
- grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/GrpcStatusTest.java
Motivation:
`FailFastException` is mapped to `Status.UNKNOWN` while `UnprocessedRequestException` is mapped to `Status.UNAVAILABLE`. https://github.com/line/armeria/blob/4c9dccf996dc062f8f77d7013de504141d9c8306/grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java#L125-L127
Both `FailFastException` and `UnprocessedRequestException` mean that a request did not work on a server, so it would be better to map to the same `Status`.
See #4805 for the detail.
Modifications:
- Fixed `GrpcStatus.fromThrowable()` to convert `FailFastException` to `Status.UNAVAILABLE`
Result:
- `FailFastException` is now correctly converted to `Status.UNAVAILABLE`.
- Fixes #4805
> Map `FailFastException` to gRPC `Status.UNAVAILABLE`

- spring/boot2-actuator-autoconfigure/build.gradle
- spring/boot2-actuator-autoconfigure/src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- spring/boot3-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationInternalServiceTest.java
Motivation:
As `AutoConfiguration.imports` in the test resource of `spring:boot3-actuator-autoconfigure` isn't copied to `spring:boot2-actuator-autoconfigure`, `PrometheusMetricExposureTest` didn't restart a server when it fails to start.
Related issue: #4941
Modifications:
- Copy `AutoConfiguration.imports` file in `boot3-autoconfigure/src/test/...' to `spring:boot2-actuator-autoconfigure`
Result:
Stabilize the CI build state
> Fix flaky `PrometheusMetricExposureTest`

- settings.gradle
Motivation:
Update gradle enterprise settings as suggested
Modifications:
- Add the commons plugin which adds additional metadata/tags
- Publish always if authenticated
- Enable uploadInBackground for local builds
Result:
- Better integration
- I've also verified locally that we don't get the `The Gradle Enterprise server (ge.armeria.dev) rejected the request due to authentication being required.` message
> Update gradle enterprise settings

- thrift/thrift0.12/src/test/thrift/main.thrift
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftRequiredFieldVerboseTest.java
- thrift/thrift0.13/src/test/thrift/main.thrift
- thrift/thrift0.9/src/test/thrift/main.thrift
Motivation:
We contain Thrift required field information if a Thrift request does not have the fields. Our Risk Assessment team recommended not having that information for security reasons.
Modification:
- Do not include Thrift required fields information in response
- They are included when `verboseResponses` is `true`.
Result:
- Thrift required field information is not included in the response by default.
> Do not include Thrift required field information in response

- gradle/scripts/lib/java-rpc-proto.gradle
- gradle/scripts/lib/kotlin.gradle
Motivation:
`gradle publish` fails to publish because of illegal usage in `grpc-kotlin` without dependencies.
```
Task ':grpc-kotlin:kotlinSourcesJar' uses this output of task
':grpc-kotlin:generateProto' without declaring an explicit or
implicit dependency. This can lead to incorrect results being produced,
depending on what order the tasks are executed.
```
https://github.com/line/armeria/actions/runs/5275219571/jobs/9540456642#step:8:1415
Modifications:
- Make `kotlinSourcesJar` depend on `generateProto` and `copyAlpnAgent`
Result:
Publish artifacts to Maven Central
> Fix Gradle `publish` task to work

- core/src/main/java/com/linecorp/armeria/common/logging/JsonLogFormatter.java
- core/src/main/java/com/linecorp/armeria/common/logging/JsonLogFormatterBuilder.java
- core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
- core/src/main/java/com/linecorp/armeria/common/logging/TextLogFormatter.java
- core/src/main/java/com/linecorp/armeria/common/logging/TextLogFormatterBuilder.java
- kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/Jsr305StrictTest.kt
Motivation:
`TextLogFormatterBuilder.build()` and `JsonLogFormatterBuilder.build()` return package-private classes that cause compilation errors when using them in different packages.
Modifications:
- Make `TextLogFormatterBuilder.build()` and `JsonLogFormatterBuilder.build()` return `LogFormatter` instead of the internal classes.
Result:
You can no longer see compilation errors when using `TextLogFormatterBuilder.build()` and `JsonLogFormatterBuilder.build()`.
> Fix a bug where builders of `LogFormatter` return internal classes

- core/src/test/java/com/linecorp/armeria/server/DomainSocketServerTest.java
Motivation:
I'm seeing the following CI failure often: https://github.com/line/armeria/actions/runs/5310769708/jobs/9613156056?pr=4968#step:7:1791
This is most likely since netty removes the directory, and then junit also tries to remove the directory and fails with a `NoSuchFileException`.
Modifications:
- Use the internal `TemporaryFolderExtension` for testing unix domain sockets. Note that the file is created directly under root since domain sockets have a max path length of approximately 110.
Result:
- More stable CIs
> Use TemporaryFolderExtension for flaky domain socket test

- core/src/main/java/com/linecorp/armeria/common/logging/JsonLogFormatter.java
- core/src/main/java/com/linecorp/armeria/common/logging/TextLogFormatter.java
- core/src/test/java/com/linecorp/armeria/common/logging/ContentPreviewInLogFormatterTest.java
Motivation:
I got a report that a content preview is not logged with `Logging{Service,Client}`.
Previously, a content preview could be used to log when sanitized content is null. https://github.com/line/armeria/blob/f6f479de876456aca34e231d2f7071c2fa26fd5d/core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java#L1528-L1530 When we migrated the code to `LogFomatter`, the condition has changed slightly. The new condition does not attempt to read a content preview when `RESPONSE_CONTENT` is available.
https://github.com/line/armeria/blob/f221c8fda5b92412d9985ea659d085168835aa05/core/src/main/java/com/linecorp/armeria/common/logging/TextLogFormatter.java#L229-L234
`RESPONSE_CONTENT` flag can be set with a null value for REST API. Because `RESPONSE_CONTENT` is mostly used …
> Fix a bug where content preview is not logged

- core/src/main/java/com/linecorp/armeria/server/FallbackService.java
- core/src/test/java/com/linecorp/armeria/server/FallbackServiceRedirectionTest.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerAutoRedirectTest.java
Motivation:
We send redirect responses in the `FallbackService` when
- the path does not end with '/'
- the route exists if '/' is appended to the path
This works in most situations except a reverse proxy exists and it rewrites the path. If we use the relative path, the client redirects correctly even with the reverse proxy.
Modification:
- Send redirect response with relative path location.
Result:
- The client redirects correctly even if a reverse proxy rewrites the path.
> Use relative path for redirection in FallbackService

- settings.gradle
This changeset updates foojay toolchain resolver plugin from 0.5.0 to 0.6.0. This new version contains the fixes for a few issues, including broken GraalVM download.
> Update foojay toolchain resolver plugin to 0.6.0

- core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java
This changeset fixes the following test failure in `TrailingDotAddressResolverTest`, which seems to affect only a certain environment:
```
TrailingDotAddressResolverTest > resolve() FAILED
Expected size: 1 but was: 3 in:
[ByteArrayDnsRecord(foo.com. 0 IN A 0B),
ByteArrayDnsRecord(foo.com. 0 IN AAAA 0B),
ByteArrayDnsRecord(foo.com. 0 IN CNAME 0B)]
at com.linecorp.armeria.client.TrailingDotAddressResolverTest.resolve(TrailingDotAddressResolverTest.java:95)
```
> Fix a failure in `TrailingDotAddressResolverTest`

- gradle/scripts/lib/java-versionprops.gradle
Motivation:
We have previously been writing `armeria.versions.properties` using `Properties#store`.
However, this behavior by default writes the current timestamp, and there is no way to configure this.
Meanwhile, the downstream `ShadedJar` task uses the properties file as an input.
Thus, `shadedJar` is not being cached on each invocation.
Since `assemble` depends on `shadedJar`, this is at least 30 seconds wasted on each build.
I've verified that the file is written correctly without the timestamp:
Also, the build scan comparison shows the inputs aren't changed on each `./gradlew core:clean core:shadedJar` invocation
build scan: https://ge.armeria.dev/scans?search.tags=coreShadedJar&search.timeZoneId=Asia/Seoul&selection.buildScanA=vxfiu2y47fpxe&selection.buildScanB=rmidkmhzhv5ak …
> Omit date when writing `armeria.versions.properties`

- core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
Motivation:
In recent Netty versions, our workaround of calling `Socket.initialize(boolean)` is not necessary anymore since Netty always call `Socket.initialize()` after loading a native library:
- https://github.com/netty/netty/blob/netty-4.1.94.Final/transport-native-unix-common/src/main/java/io/netty/channel/unix/Unix.java#L50-L59 
Modifications:
- Removed the workaround that calls `Socket.initialize()`.
Result:
- Cleaner code
> Remove the workaround in `TransportTypeProvider`

- core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
Motivation:
`DefaultStreamMessageTest.onSubscribeBeforeOnComlete()` fails frequently especially on GitHub managed runners. 8192 seems too much value to finish stably for CI machines.
https://github.com/line/armeria/actions/runs/5312615496/jobs/9707705116?pr=4966#step:7:1213
Modifications:
- Repeat 128 times if the test is run on the CI environment.
Result:
Reduce CI failures
> Fix flaky `DefaultStreamMessageTest.onSubscribeBeforeOnComlete()`

- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java
Motivation:
It is possible that the temporary file used as a unix socket is deleted by netty.
In this case, we can ignore the deletion from `TemporaryFolder`
https://github.com/line/armeria/actions/runs/5562070616/jobs/10160143512?pr=5036#step:7:1956
Modifications:
- Ignore file deletion error from `TemporaryFolder`
Result:
- Less flaky tests
> Ignore temporary folder file deletion exception

- .github/workflows/actions_build.yml
- build.gradle
- dependencies.toml
Motivation:
Tests are run up to 4 times by applying the retry plugin.
Even if the test passes on the nth try, the overall build still fails. (while recording test related metrics to gradle enterprise)
Locally verified: 
- https://ge.armeria.dev/s/qyplnd3amofjq
- Check the console logs to verify how many tasks have been actually run
- https://ge.armeria.dev/s/qyplnd3amofjq/console-log?task=:core:test
Modifications:
- Apply the gradle retry plugin
Result:
- More information on tests at the cost of slightly slower builds
> Apply the gradle enterprise test retry plugin

- gradle/scripts/lib/java.gradle
- settings/checkstyle/checkstyle.xml
Motivation:
We are passing `configProperties` to the checkstyle task, which is resulting in inconsistent inputs to our gradle task when run from different locations.
By setting the `configDirectory` property, we can use the `config_loc` property pre-defined by `checkstyle`.
ref: https://ge.armeria.dev/scans?search.tags=exp3*%2Cgradle/checkstyle-cache&search.timeZoneId=Asia/Seoul#selection.buildScanA=r4jnvs4tiabmg&selection.buildScanB=zhqrycgjdns7q
Modifications:
- Specify `configDirectory` instead of `configProperties`
Result:
- Input caching is done properly from different locations for checkstyle tasks.
> Ensure task inputs are consistent for checkstyle

- core/src/test/java/com/linecorp/armeria/client/DocServiceAssetCompressionTest.java
- docs-client/webpack.config.ts
Motivation:
This PR addresses two issues:
1. `reactHotLoader` is bundled into the production build, which contains additional information about the system. This has been resolved by selectively adding the `'react-hot-loader/babel'` plugin.
This can be observed by running the following command:
```sh
zfgrep 'reactHotLoader' docs-client/build/javaweb/com/linecorp/armeria/server/docs/main.js.gz
```
2. A random hash is added every time build is done for cache busting. Instead of using `HtmlWebpackPlugin.hash`, modified to use the `contenthash` in the filename to make the hash deterministic.
- ref: https://webpack.js.org/guides/caching/#output-filenames
Note that `index.html` is also updated accordingly by webpack.
ref: https://ge.armeria.dev/c/tvnyf5nfgy54g/wlr2xqtdkd73u/task-inputs?cacheabili …
> Ensure task inputs are consistent for `docs-client`

- core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java
- core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java
- core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
- core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClient.java
- core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClientBuilder.java
- core/src/main/java/com/linecorp/armeria/common/logging/DefaultLogWriter.java
- core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
- core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
- core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
- core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientDefaultLoggerTest.java
- core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceDefaultLoggerTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Motivation
I changed the default logger of `LoggingService` from `com.linecorp.armeria.server.logging.LoggingService` to `com.linecorp.armeria.common.logging.DefaultLogWriter` in #4943. This caused a breaking change to logging system if you are using the class name with a logger. This also applies to the `LoggingClient`.
We should fix it.
Modification
- Reverted to use `com.linecorp.armeria.server.logging.LoggingService` logger for `LoggingService` when `LogWriter` isn't set.
- Reverted to use `com.linecorp.armeria.client.logging.LoggingClient` logger for `LoggingClient` when `LogWriter` isn't set.
Result
- As in versions prior to 1.24.0, the default logger for `LoggingService` is now `com.linecorp.armeria.server.logging.LoggingService`.
- The default logger for `LoggingClient` is also …
> Fix a bug that default logger is changed for LoggingService and LoggingClient

- .github/workflows/publish-release.yml
Motivation:
npm isn't detected because NVM doesn't install node in `/usr/local/bin` Should set `NVM_DIR` and source `nvm.sh` for npm work correctly.
https://stackoverflow.com/questions/62863080/github-actions-err-bash-line-3-npm-command-not-found https://gist.github.com/danielwetan/4f4db933531db5dd1af2e69ec8d54d8a?permalink_comment_id=4057972
> Set NVM dir correctly for post release process

- brave/src/main/java/com/linecorp/armeria/client/brave/ClientRequestContextAdapter.java
- core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/main/java/com/linecorp/armeria/common/logging/RequestLogAccess.java
- core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseSubscriber.java
- core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
- core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
- resilience4j2/src/main/java/com/linecorp/armeria/resilience4j/circuitbreaker/client/Resilience4JCircuitBreakerCallback.java
Motivation:
The current implementation of RequestLog access in AbstractHttpResponseHandler is verbose and potentially inefficient. Each operation checks the availability of RequestLog properties separately, accessing a volatile variable and computing the available flags multiple times. Additionally, the code style does not align with efficient and concise Kotlin programming practices.
Modifications:
Introduce new API for accessing RequestLog only when specific flags are available
Provide Kotlin users with the ability to utilize null-safe calls
Result:
Improved efficiency of RequestLog access by reducing redundant checks and computations
Enhanced compatibility for Kotlin developers by enabling null-safe calls when accessing RequestLog properties
> Add getIfAvailable API (#4956)

- gradle/scripts/lib/java-rpc-thrift.gradle
Motivation:
We may save up to a minute if we properly define inputs/outputs for the `thriftCompile` gradle task.
The task is marked as cacheable by specifying `outputs.cacheIf { true }`.
Note that although `cacheIf { true }`, the task will still run if inputs/outputs change.
- Check without modifying input
- https://ge.armeria.dev/c/pp3h4hh4ivj6e/zg5b57ucqvvjg/task-inputs
- Check while modifying a single input manually
- https://ge.armeria.dev/c/qd4vy3a3da554/pp3h4hh4ivj6e/task-inputs
Build scan comparison with exp3:
- https://ge.armeria.dev/c/xvkcw3olkh2hk/bccchwpbbvo44/task-inputs?cacheability=cacheable,overlapping-outputs,validation-failure
Modifications:
- Specified the task inputs to all values defined in `project.ext` for thrift tasks.
- Marked `thriftCompile` tasks as cacheable …
> Better caching for `thriftCompile` tasks

- docs-client/src/containers/MethodPage/DebugInputs.tsx
- docs-client/src/containers/MethodPage/DebugPage.tsx
- docs-client/src/lib/specification.tsx
Motivation:
Some users find it inconvenient to use the new debug form especially when they have to refer to request specifications while writing requests.
As the debug page has enough space on the bottom side, it would be better to provide the two debug form styles.
Modifications:
- Add `DebugInputs` component to reuse components used for rendering a debug form.
- Render both an inline style and a modal style.
- Thanks to React state, the values of the two forms are fully synchronized.
Result:
You can now use either an inline debug form or a debug form modal when using `DocService`.
> Revive the legacy debug form in `DocService`

- gradle/scripts/lib/java-rpc-thrift.gradle
Motivation:
Cleaned up `CompileThriftTask` implementation, added better code separation between task execution and configuration and prepared for easier possible refactoring away from using `project.ext` block in favor of configuring the task deterministically.
Modifications:
- Moved the execution code of the `CompileThriftTask` to it's task action part.
- Specified all the inputs and outputs of `CompileThriftTask` and removed any external references in task action.
- Removed all the `project.ext` accesses from the task itself (in order not to introduce big changes I left it when configuring the task).
Result:
- Easier to understand the `CompileThriftTask` configuration and execution.
- Better code separation between task configuration and task execution.
- Prepared for easier possible …
> CompileThrift task update

- core/src/main/java/com/linecorp/armeria/internal/common/util/ChannelUtil.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/test/java/com/linecorp/armeria/client/DomainSocketClientTest.java
- core/src/test/java/com/linecorp/armeria/server/DomainSocketServerTest.java
Related issue: #5080
Motivation:
`ServiceRequestContext.localAddress()` and
`ServiceRequestContext.remoteAddress()` currently returns an
`InetSocketAddress(0.0.0.0:1)` for domain sockets in abstract namespace.
Modifications:
- Updated `ChannelUtil` to use the parent channel's local address for
server-side domain socket channels to retrieve their socket addresses
reliably
- Added a special hostname `<unknown>` to `HttpServerHandler.UNKNOWN_ADDR`
so that it's less confusing
Result:
- `ServiceRequestContext` now returns the correct socket addresses when
the request is being served via a domain socket in abstract namespace.
- It should be easier to understand the situation when a similar issue
(unknown address) arises again.
> Fix incorrect local and remote address when using domain socket in abstract namespace

- core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
Motivation:
`io_uring` is known to have much smaller system call overhead than other
transport types such as NIO, `epoll` and Kqueue. Therefore, we should
use fewer event loop threads when using `io_uring`.
Modifications:
- Changed `FlagsProvider.numCommonWorkers()` to require `TransportType`
- Made `DefaultFlagsProvider.numCommonWorkers()` not double the number
of CPU cores when the current transport type is `IO_URING`
Result:
- A user doesn't have to manually specify the optimal event loop count
when using `io_uring`.
> Use fewer event loops when using `io_uring` as transport

- core/src/test/java/com/linecorp/armeria/internal/common/metric/CaffeineMetricSupportTest.java
Motivation:
JUnit5 is recommended over JUnit 4 for several reasons
Modifications:
- Migrate JUnit 4 tests to JUnit 5
- Clean up
- Removed `@Nonnull` annotations, since armeria is non-null by default.
Result:
Migrated to JUnit 5
---
Hi, I'm trying to work on a JUnit 4 -> 5 migration.
~It's going to take some time to migrate all tests, so I'd like to make it as draft and going to open it when it's done, is that ok?~
-> I'm working on a separate branch :)
> Migrate some JUnit 4 tests to JUnit 5

- core/build.gradle
- core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
Motivation:
- Tests did not work for MRJAR because JUnit 5 was not set for `testJava9` or `testJava12`
- While fixing the issue, I found out that `JavaHttpClientUpgradeTest` for HTTP/2 fails to pass due to double write of headers.
- One is sent by `fail()`
- The other one is sent by the callback of `.abortResponse()` https://github.com/line/armeria/blob/de80c40588b9d3c4fb1d1791a2e798de0295f013/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L309-L314
Modifications:
- Set `useJUnitPlatform()` to `testJava{version}` test tasks.
- Check if a response headers was sent already before writing headers.
Result:
- Tests for Multi-release JAR now correctly run with `testJava9` and `testJava12` tasks.
- Fixed a bug where headers could be written twice if `content-length` was …
> Fix a bug where tests did not work for MRJAR

- docs-client/src/components/Description/index.tsx
- docs-client/src/components/VariableList/index.tsx
- docs-client/src/containers/App/index.tsx
- docs-client/src/containers/EnumPage/index.tsx
- docs-client/src/containers/MethodPage/ReturnType.tsx
- docs-client/src/containers/MethodPage/index.tsx
- docs-client/src/containers/StructPage/index.tsx
This PR makes minor adjustments to the DocService UI, to reduce the number of visual artifacts and provides a more consistent experimence. Additionally, it gets rid of all runtime exceptions to avoid any potential rendering issues.
- Render `Typography` inside `Description` as `span` instead of `p`, to get rid of `validateDOMNesting()` errors
- Vertically align `Expand{More,Less}` with the row text
- Remove extra margin and inconsistent row height when variable fields have a description
- Make sure table rows have the same length when `Expand{More,Less}` is present
- Remove a blank `Typography` at the end of `VariableList`
- Use a correct deduplication key for method endpoints, to get rid of `Encountered two children with the same key` errors
- Hide method/struct/enum description section …
> Fix various `docs-client` interface issues

- core/src/main/java/com/linecorp/armeria/internal/client/dns/CachingDnsResolver.java
- core/src/main/java/com/linecorp/armeria/internal/client/dns/DnsUtil.java
- core/src/test/java/com/linecorp/armeria/client/DnsTimeoutUtil.java
Motivation:
`CachingDnsResolver` should not cache any DNS queries that have timed out. However, it currently caches them when the timeout exception is buried in the exception's root cause or suppressed causes.
Modifications:
- Added `DnsUtil.isDnsQueryTimedOut()` to determine whether the DNS query failure was due to a timeout or not precisely
- Changed `DnsTimeoutUtil.assertDnsTimeoutException()` to use `DnsUtil.isDnsQueryTimedOut()`.
- Changed `CachingDnsResolver` to use `DnsUtil.isDnsQueryTimedOut()` in addition to the `instanceof UnknownHostException`.
Result:
- Armeria's DNS resolver doesn't cache a DNS query timeout.
> Do not cache DNS queries that have timed out

- core/src/main/java/com/linecorp/armeria/client/DefaultDnsCache.java
- core/src/main/java/com/linecorp/armeria/client/DnsCacheBuilder.java
- core/src/test/java/com/linecorp/armeria/client/DefaultDnsCacheTest.java
Motivation:
When creating a new connection, the DNS records cache is disabled to obtain a new IP address, but there may be a need to cache NXDOMAIN. The default `DnsCache` shares a cache for positive and negative results and does not allow zero TTL, so it is difficult to configure the desired settings with `DnsCacheBuilder`.
Modifications:
- Allow zero TTL for successful DNS records.
Result:
`DnsCache` now allows zero TTL for the resolved DNS records.
> Allow zero TTL for DNS cache

- grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceImplErrorTest.java
Motivation:
I found an exception is thrown when "Armeria tries to set Metadata, but the Metadata is corrupted". 
Modifications:
- Log an exception thrown while Armeria tries to set Metadata.
- Returns the default `Metadata` with `INTERNAL` code instead as a fallback `Metadata`.
Result:
- Fixed `GrpcService` to return an INTERNAL error code if an error occurs while serializing gRPC metadata.
- Closes #4625
> Log the exception raised while serializing gRPC metadata

- grpc/src/test/java/com/linecorp/armeria/server/grpc/InvalidGrpcMetadataTest.java
Motivation:
See #5120
Modifications:
- Used `whenComplete().join()` instead of `ensureComplete()`
- Renamed `GrpcServiceImplErrorTest` to `InvalidGrpcMetadataTest` to easily identify the purpose of the tests
Result:
Closes #5120
> Fix flaky `GrpcServiceImplErrorTest`

- .github/workflows/gradle-build-scan.yml
- .github/workflows/publish-release.yml
Motivation:
The GitHub Actions job for Gradle scan failed due to `.nvm/nvm.sh: No such file or directory`.
https://github.com/line/armeria/actions/runs/5899610915/job/16002384391
Node.js version wasn't specified in `actions/setup-node@v3` workflow, so the node version in `PATH` could be used. https://github.com/actions/setup-node#usage It can't make our CI portable to other systems.
Modifications:
- Specify Node.js 18 to `setup-node` workflow
- Remove curruped code related to `nvm`
- Use `npm ci` instead of `npm install`
- npm ci is a recommended way to install dependencies https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#npm
Result:
Hopely fix `.nvm/nvm.sh: No such file or directory` issue
> Specify Node.js version to GitHub Actions

- docs-client/src/containers/App/index.tsx
- docs-client/src/lib/transports/grpc-unframed.ts
Motivation:
I miss Armeria docs service a lot. So I am working on an implementation of the server side in Go to be able to reuse the excellent client :)
https://github.com/curioswitch/go-docs-handler/blob/main/examples/connect/main.go
Currently still WIP, the features of simple GreetService are implemented but still just a bit more work to finish it up. Normally I would wait until more completeness but I saw the "Update dependencies" PR :P
`protocol=gRPC` is added for better differentiation within the docs UI but is not necessary for actually making requests. Coincidentally, not including it provides compatibility with this Go gRPC server implementation called connect. While I doubt Armeria could officially implement servers in other languages / frameworks like this, may small best effort …
> Do not add protocol-gRPC when sending a request from docs client

- gradle/scripts/lib/java-shade.gradle
Motivation:
`trimShadedJar` may induce a build-cache miss due to a different file order. It may be worth sorting the libraryjars before adding them to avoid such cache misses.
ref: https://ge.armeria.dev/c/klccgbghrflqk/zbz73bzpwscrg/task-inputs?expanded=WyJkZ3hnY3Zsc2hua3R3LWluamFyZmlsZWNvbGxlY3Rpb24iLCJkZ3hnY3Zsc2hua3R3LWxpYnJhcnlqYXJmaWxlY29sbGVjdGlvbiIsImRneGdjdmxzaG5rdHctbGlicmFyeUphckZpbGVDb2xsZWN0aW9uLTEtZmlsZS1vcmRlciJd&task-text=trim
Modifications:
- Sort each jmod before adding to `libraryjars` for proguard
Result:
- More stability for build cache hits
> Sort jmods before adding to proguard jars for easier caching

- core/src/main/java/com/linecorp/armeria/common/annotation/UnstableApi.java
Motivation:
The retention policy of the `@UnstableApi` annotation is currently
`SOURCE`, which means `.class` files in our JAR will not be able to tell
bytecode-level analysis tools about whether a certain class or method is
unstable or not. Therefore, we cannot exclude the unstable API elements
from the API backward compatibility checks we'd like to introduce in the
future.
Modifications:
- Change the retention policy from `SOURCE` to `CLASS` so that our
`.class` files contains enough metadata about the stability of our
API.
Result:
- We can exclude the unstable API elements from our future API backward
compatibility tests.
> Change the retention policy of `@UnstableApi` to `CLASS`

- consul/src/main/java/com/linecorp/armeria/client/consul/ConsulEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
- eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
- javadoc/build.gradle
Motivation:
It's a bad idea to expose Guava classes from our public API because all
Guava classes are shaded into `com.linecorp.armeria.internal.shaded.guava`,
exposing the internal classes in the public API.
Modifications:
- Fixed the broken test in `javadoc/build.gradle`.
- Replaced `DynamicEndpointGroup.toStringHelper()` with `toString(Consumer)`.
Result:
- We do not leak internal classes in our public API anymore.
> Do not expose Guava's `ToStringHelper` from the public API

- core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java
Motivation:
It is very common for users to specify `CollectorRegistry.defaultRegistry` when creating a `PrometheusExpositionService` or its builder.
Modifications:
- Added two shortcut methods:
- `of()` -> `of(CollectorRegistry.defaultRegistry)`
- `builder()` -> `builder(CollectorRegistry.defaultRegistry)`
Result:
- Much more convenient and less verbose when creating a `PrometheusExpositionService`
> Add more factory methods to `PrometheusExpositionService`

- site/src/pages/release-notes/1.25.0.mdx
> Add release notes for 1.25.0

- core/src/test/java/com/linecorp/armeria/common/multipart/MultipartEncoderTckTest.java
Motivation:
`MultipartEncoderTckTest.required_spec101_XXX` fails quite often.
https://ge.armeria.dev/scans/tests?search.timeZoneId=Asia/Seoul&tests.container=com.linecorp.armeria.common.multipart.MultipartEncoderTckTest&tests.test=required_spec101_subscriptionRequestMustResultInTheCorrectNumberOfProducedElements
```java
java.lang.AssertionError: Publisher com.linecorp.armeria.common.multipart.MultipartEncoder@3eec8583 produced no element after first `request` within 200 ms
at org.testng.Assert.fail(Assert.java:98)
at org.reactivestreams.tck.TestEnvironment.flopAndFail(TestEnvironment.java:285)
at org.reactivestreams.tck.TestEnvironment$Receptacle.next(TestEnvironment.java:1047)
at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.nextElement(TestEnvironment.java:514)
at …
```
> Fix flaky `MultipartEncoderTckTest.required_spec101...`

- .github/actions/comment-build-scan.ts
- .github/workflows/gradle-build-scan.yml
Motivation:
A build scan may fail to upload if a Gradle build is corrupted somehow.
If there is no scan data in `.gradle/build-scan-data`, `./gradlew buildScanPublishPrevious` exits with 1, and then the subsequent commands will be halted.
Modifications:
- Ignore failed upload build scan and continue to upload the next data
- Use html_url for the workflow job
> Ignore empty Gradle build scans and continue to upload

- spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
Motivation:
Removed debug logs
Modifications:
- Removed debug logs
Result:
- Unnecessary debug logs don't confuse users
> Remove debug logs for `ArmeriaServerHttpResponse`

- build.gradle
Motivation:
The shaded jar contains a manifest file which contains the build java version including the patch version.
I propose that we ignore the manifest file for all projects since it doesn't really affect the output.
Note that the `trimShadedJar` is still executed, but I still think this is a big improvement. The `trimShadedJar` task isn't cached because of the `libraryJarFileCollection` input which I'm not sure there's much we can do about
https://ge.armeria.dev/c/vll4rsgncwdai/zawmc5it7jzkw/task-inputs?expanded=WyJkZ3hnY3Zsc2hua3R3LWxpYnJhcnlqYXJmaWxlY29sbGVjdGlvbiJd&task-text=trim
ref: https://ge.armeria.dev/s/coxkiutevscp4
Modifications:
- Added a normalization for all projects which ignores `META-INF/MANIFEST.MF` file
Result:
- Better caching even for different build jdk …
> Ignore manifest file for jars when computing task inputs

- .github/workflows/actions_build.yml
- settings.gradle
Motivation:
I'm seeing the following exception in our build:
https://github.com/line/armeria/actions/runs/6006711692/job/16291663362#step:9:809
```
Could not store entry fe26c95786e078f1daa3109effc3534a in remote build cache
java.lang.RuntimeException: Storing entry at 'https://ge.armeria.dev/cache/fe26c95786e078f1daa3109effc3534a' response status 403: Forbidden
at com.gradle.enterprise.agent.b.a.b.a(SourceFile:125)
at com.gradle.scan.plugin.internal.dep.org.apache.http.impl.cli
```
We should either:
- Only enable build cache uploads from our post job
- Allow build cache uploads for all builds in our CI. Note that if an access token is present, build scans will also be uploaded from our main CI. (and also uploaded from our postjob)
- Pull requests don't have access to secrets, so added an …
> Add gradle access token to main build

- docs-client/build.gradle
Motivation:
The output of `npm run build` is inconsistent across builds at the moment.
As a result, our jars are slightly different causing cache misses downstream.
It has been suggested that we can make the npm task cacheable.
To keep the current behavior, I also propose that we upload caches only on linux machines (like we've been doing so far) by adding an input to the current os family.
local run: https://ge.armeria.dev/c/y4by6h2mrop3u/gt25suskafqek/task-inputs?cacheability=cacheable,overlapping-outputs,validation-failure
run: https://ge.armeria.dev/s/zpv5sbkn6i6f2
Modifications:
- Added inputs/outputs with relative directories for the npm run task
- Added a `cacheIf` condition which caches the output of `buildWeb` per OS family type
- I also noticed that the lint task may not be run …
> Try making `buildWeb` cacheable

- site/src/pages/docs/server-decorator.mdx
Motivation:
Documentation was slightly off in two places
Modifications:
- Update from calling `new ServerBuilder()` to `Server.builder()` factory method
Result:
- No changes in code
> Documentation fix (constructor is package private)

- settings.gradle
Motivation:
This pull request attempts to enable local caching by default.
Doing so should be safe since this only adds an extra layer of caching on top of remote caching.
Modifications:
- Enable local caching by default
Result:
- Local caching is now available
> Enable local cache by default

- README.md
Added the "Revved up by Gradle Enterprise" badge, which links to https://ge.armeria.dev/
Motivation:
The badge is a standard way for OSS projects that are supported by Gradle Enteprise to have a link to their GE instance in their readme.
Modifications:
- Added the "Revved up by Gradle Enterprise" badge, which links to https://ge.armeria.dev/ to the main `README.md` file.
> Added the "Revved up by Gradle Enterprise" badge

- brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientTest.java
- brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceTest.java
- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/test/java/com/linecorp/armeria/client/InitiateConnectionShutdownTest.java
- core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientDefaultLoggerTest.java
- core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
- core/src/test/java/com/linecorp/armeria/client/observation/ObservationClientTest.java
- core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceDefaultLoggerTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/observation/ObservationServiceTest.java
- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/ImmediateEventLoop.java
Motivation:
Currently the thread which invokes our log callbacks (i.e. `RequestLogFuture`s) are usually from `ctx.eventLoop()`.
This is because most log callbacks are invoked from the encoder/decoder layer which are usually invoked from the channel event loop.
However, while working on https://github.com/line/armeria/pull/4136 now it is possible that `ctx.eventLoop()` is different from `ch.executor()`.
Whether we choose to use `ctx.eventLoop()` or `ch.executor()` when completing callbacks, it is probably important that we are consistent. Therefore, I propose that for now we complete all pending `RequestLogFuture` from `ctx.eventLoop()`
Modifications:
- Reschedule `DefaultRequestLog#completeSatisfiedFutures` to be executed from `ctx.eventLoop()` if not done so already
- Fix failing tests …
> Explicitly schedule pending `RequestLogFuture` on `ctx.eventLoop()`

- core/src/main/java/com/linecorp/armeria/client/Clients.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientDerivedClientTest.java
Motivation:
If a client is derived with `ClientOptions` configurator, client options containing collection values such as `decorators`, `rpcDecorators` are duplicated. For example, the original client has `LoggingClient -> CircuitBreakerClient` decorators, and the derived client will have `LoggingClient -> CircuitBreakerClient -> LoggingClient -> CircuitBreakerClient`.
Because `configurator` builds a new `ClientOptions` and appends it to the existing `ClientOptions`.
Modifications:
- Do not set the existing client options when using `ClientOptions` configurator.
Result:
You no longer see duplicate `ClientOptions` when creating a derived client with `<type://Clients#newDerivedClient(T,Function)>`.
> Fix a bug where `ClientOptions` of derived clients is duplicated

- core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
- core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/DeferredHttpResponseTest.java
- core/src/test/java9/com/linecorp/armeria/internal/common/HttpResponseCompletionStageTest.java
Motivation:
`CompletionStage<T> CompletableFuture.minimalCompletionStage()` returns a `MinimalStage` which implements `CompletionFuture` and raises `UnsupportedOperationException` if the methods only in `CompletionFuture` are called.
`HttpResponse.of(CompletionStage<HttpResponse>)` checks if the given value is an instance of `CompletableFuture` to use an optimized path for `CompletableFuture`. It is not working because `MinimalStage` can be set to the method parameter easily.
```java
CompletableFuture<HttpResponse> future = new CompletableFuture<>();
HttpResponse.of(future.minimalCompletionStage());
```
Discord discussion: https://discord.com/channels/1087271586832318494/1087272728177942629/1153277808630566942
Modifications:
- Do not check if a `CompletationStage` is an instance of …
> Fix a bug where `HttpResponse` can't complete with `CompletionStage`

- examples/context-propagation/kotlin/build.gradle.kts
- examples/context-propagation/kotlin/src/main/kotlin/example/armeria/contextpropagation/kotlin/MainService.kt
- kotlin/build.gradle.kts
- kotlin/src/main/kotlin/com/linecorp/armeria/common/kotlin/CoroutineContextAwareExecutor.kt
- kotlin/src/main/kotlin/com/linecorp/armeria/common/kotlin/CoroutineRequestContext.kt
- kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaCoroutineUtil.kt
- kotlin/src/test/kotlin/com/linecorp/armeria/common/kotlin/CoroutineContextAwareExecutorTest.kt
- kotlin/src/test/kotlin/com/linecorp/armeria/common/kotlin/CoroutineRequestContextTest.kt
Motivation:
- `ArmeriaRequestCoroutineContext` for Kotlin is an internal API that users shouldn't use. We need to provide a public API for that.
- It would be nice if we could add `ArmeriaRequestCoroutineContext(ctx)` automatically for `ContextAwareExecutor` dispatcher so that the context is automatically propagated even when threads are changed.
Modifications:
- Add `RequestContext.asCoroutineContext()` extension method that replaces the usage of `ArmeriaRequestCoroutineContext(ctx)`
- Add `ContextAwareExecutor.asCoroutineDispatcher()` extension method that returns the dispatcher with `RequestContext.asCoroutineContext()`.
Result:
- You can now easily propagate an Armeria `RequestContext` in kotlin using `ContextAwareExecutor.asCoroutineDispatcher()`.
> Add extension methods in Kotlin for request scoping

- core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
- core/src/main/java/com/linecorp/armeria/client/AbstractHttpResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
- core/src/main/java/com/linecorp/armeria/internal/client/HttpSession.java
- core/src/test/java/com/linecorp/armeria/client/HttpClientUpgradeTest.java
Motivation:
When the client sends an options request for upgrade, the server can respond with the following data in the order:
- 101 switching protocol
- HTTP/2 settings frame
- HTTP/2 response for the options request
When the client process the HTTP/2 response, an NPE is raised because:
- the end of stream of the response for options request is set to true and it triggers `Http2ResponseDecoder.onStreamClosed()`
- [HttpSessionHandler.isAcquirable()](https://github.com/line/armeria/blob/main/core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java#L285) is also called but NPE is raised because `responseDecoder` isn't set.
- The task for setting the response decoder is in the event loop queue: https://github.com/line/armeria/blob/863e27c5268631360c14e50e13cd3e38d84c9db5/core/sr …
> Fix NPE from `HttpSessionHander.isAcquirable()`

- site/src/pages/docs/server-docservice.mdx
- Use `<Tabs> - <TabPane> - <CodeBlock>`, instead of series of inline comment and codeblocks like "Using gradle: ```~", in [DocService docs](https://armeria.dev/docs/server-docservice)
- Add protobuf configuration for gradle kotlin DSL in gRPC docstring part
---
---
> Use `<Tabs>` for maven/gradle configuration in DocService docs

- core/src/main/java/com/linecorp/armeria/client/Bootstraps.java
- core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
Related: #5129
Motivation:
The `bootstrap` creation logic in the `HttpChannelPool`  is fairly complex. We want to simplify it by making it a separate class and data structure. from @minwoox 
Modifications:
- `inetBootstraps` and `unixBootstraps` were fields in `HttpChannelPool`, but have now been changed to fields in the own class `Bootstraps`.
Result:
- Closes #5129. (If this resolves the issue.)
- We've separate the bootstrap retrieval logic from `HttpChannelPool` to make it simple.
> Refactor bootstrap retrieval in `HttpChannelPool`

- core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
- core/src/test/java/com/linecorp/armeria/client/PendingAcquisitionTest.java
Motivation:
HTTP/2 connections expected to reuse are created without waiting for the pending acquisition if a request exceeds the max concurrent streams. A `ChannelAcquisitionFuture` is set with the desired session protocol such as `HTTP` or `HTTPS`. However, `H2C` or `H2` could be used to get a pending acquisition because it uses the actual session protocol. That results in a cache miss and creates additional connections.
Modifications:
- Use the desired session protocol to get a pending acquisition in `handlePiggyback`.
- Change `getPendingAcquisition` to check H2(C) if the desired protocol is `HTTP(S)`. Because it is safe to use HTTP/2 connection since `HTTP(S)` implies HTTP/2.
Result:
When a client exceeds max concurrent streams, a new connection is created and correctly reused from …
> Use the desired protocol to get a pending acquisition

- benchmarks/jmh/README.md
- benchmarks/jmh/build.gradle
- dependencies.toml
Motivation:
We don't have to use sbt-jmh-extras because the integration with async-profiler and JFR are merged to the JMH. https://github.com/sbt/sbt-jmh#using-java-flight-recorder--async-profiler
Modification:
- Remove `sbt-jmh-extras` dependency
- Update README.md and build.gradle
Result:
- Correct guide for JMH async profiler
> Update jmh configuration for async profiler

- core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
- core/src/test/java/com/linecorp/armeria/server/RouteTest.java
Motivation:
Currently, if the `DefaultRoute#withPrefix` API is used with an empty prefix, a new `DefaultRoute` will be allocated.
It has been pointed out that this can be improved on.
Modifications:
- Check if the prefix is a empty path, and return the original route if possible
Result:
- Slightly better memory footprint
> Don't allocate a route with an empty prefix

- core/src/main/java/com/linecorp/armeria/internal/server/RouteDecoratingService.java
- core/src/main/java/com/linecorp/armeria/server/AbstractAnnotatedServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/AbstractBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ContextPathAnnotatedServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/ContextPathDecoratingBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ContextPathServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ContextPathServicesBuilder.java
- core/src/main/java/com/linecorp/armeria/server/DecoratingServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostDecoratingServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
- core/src/test/java/com/linecorp/armeria/server/AbstractBindingBuilderTest.java
- core/src/test/java/com/linecorp/armeria/server/AbstractServiceBindingBuilderTest.java
- core/src/test/java/com/linecorp/armeria/server/ContextPathTest.java
- core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
Motivation:
It has been pointed out that users may want to add services/decorators under a certain prefix easily.
I propose that we introduce `ServerBuilder#contextPath(String...)`, `VirtualHostBuilder#contextPath(String...)` to achieve this. These methods will apply the same set of APIs as `ServerBuilder`, `VirtualHostBuilder` to ensure migration is easy.
```
.contextPath("/v1", "/v2")
.service(myService) // served under "/v1" and "/v2"
.and()
.virtualHost("foo.com")
.contextPath("/v3")
.service(myService) // served by virtual host "foo.com" under "/v3"
```
Conceptually,
- `ServerBuilder#contextPaths`, `VirtualHostBuilder#contextPaths` has been added, which returns a `ContextPathServicesBuilder`
- `ContextPathServicesBuilder` now accepts a parameter `contextPaths`
- All …
> Provide a way to add a context path to a subset of services

- core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/test/java/com/linecorp/armeria/client/retry/RedirectWithCookieClientTest.java
Motivation:
When `CookieClient` is used while enabling `followRedirects` option, `CookieClient` fails to relay the cookies of the redirection request.
`CookieClient` uses `peekHeaders(callback)` to see the response headers. `RedirectingClient` uses `log().whenAvailable(RequestLogProperty.RESPONSE_HEADERS)` to see response headers.  The key difference is that `peekHeaders()` is invoked when HttpResponse is subscribed or aggregated and `RequestLogProperty.RESPONSE_HEADERS` is immediately invoked when the response headers is received by the response decoder.
As `RedirectingClient` aborts the response after checking the response headers via the request log, the response is not subscribed at all which results in `CookieClient` not working.
Modifications:
- Split the redirect response to access …
> Fix a bug where `CookieClient` does not work with redirects

- core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
- core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
- core/src/main/java/com/linecorp/armeria/internal/common/DefaultCancellationScheduler.java
- core/src/main/java/com/linecorp/armeria/internal/common/NoopCancellationScheduler.java
- core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
- core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
- core/src/test/java/com/linecorp/armeria/internal/client/DefaultClientRequestContextTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/CancellationSchedulerTest.java
Motivation:
While working on https://github.com/line/armeria/pull/5212, I realized that `noopResponseCancellationScheduler` is an already completed scheduler.
When we create a `DefaultClientRequestContext` for the upgrade request, we use this scheduler.
https://github.com/line/armeria/blob/8e139d972f5137f9d1805ddda4a7aeae60fecd40/core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java#L550
However, actually what we want is a scheduler which never completes instead of an already completed scheduler.
For this reason, I propose that we separate a
- `CancellationScheduler#noop`: signifies a scheduler which never completes
- `CancellationScheduler#finished`: signifies a scheduler which already completed
Note that the upgrade request is already bound by …
> Introduce the `CancellationScheduler` interface

- grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
Motivation:
Modifications:
- Throw ISE in `GrpcServiceBuilder.build()` if transcoding is enabled but serialization format `JSON` is not set.
Result:
- Closes https://github.com/line/armeria/issues/5176
The detailed description on why this is an annoying issue is discussed in the issue.
> throw ISE when gRPC HTTP JSON transcoding is enabled but serialization format JSON is missing

- core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
- core/src/main/java/com/linecorp/armeria/common/CommonPools.java
- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/common/metric/CertificateMetrics.java
- core/src/main/java/com/linecorp/armeria/common/metric/EventLoopMetrics.java
- core/src/main/java/com/linecorp/armeria/common/metric/MoreMeterBinders.java
- core/src/main/java/com/linecorp/armeria/internal/common/util/CertificateUtil.java
- core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/server/Server.java
- core/src/main/java/com/linecorp/armeria/server/ServerSslContextUtil.java
- core/src/test/java/com/linecorp/armeria/client/ClientCertificateMetricsTest.java
- core/src/test/java/com/linecorp/armeria/server/ServerTlsCertificateMetricsTest.java
Motivation:
Armeria only provides metrics for server certificates. mTLS is also widely used in Kubernetes service mesh or for enhanced security.
If we provide validity metrics for client certificates, users will easily monitor expiration of the certificates.
Modifications:
- Add `CerfiticateMetrics` to easily register metrics for `X509Certificate`
- Set up metrics for client certificates when `HttpClientFactory` is created.
- Client certificates in `SslContextBuilder` are illegally accessed via reflections.
- TODO: Open an issue to Netty to expose `keyCertChain` in `SslContextBuilder` or introduce Armeria `SslContextProvider` 
- Move `CertificateUtil` to internal to use in the client modules.
- Fix `EventLoopMetrics` to take `MeterIdPrefix` which makes users easily add additional tags to …
> Add metrics for client certificates

- core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketUtil.java
- core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceTest.java
Motivation:
As described in #5165, `Connection` header for a WebSocket upgrade request can have multiple values.
Modifications:
- Establish a WebSocket session if the `Connection` and `Upgrade` headers contain the required value.
Result:
- Close #5165
- A WebSocket session is correctly established if the `Connection` and `Upgrade` headers contain the required value.
To-do:
- Add IT tests that establish WebSocket from FireFox and Chrome.
> Fix that `WebSocketService` rejects headers that have multiple values

- grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTimeoutTest.java
Motivation:
gRPC specification says:
> If Timeout is omitted a server should assume an infinite timeout.
> Client implementations are free to send a default minimum timeout
> based on their deployment requirements.
Armeria gRPC implementation does not follow the specification and uses the server's timeout as is.
Modifications:
- Clear a request timeout if no `grpc-timeout` header is set when `useClientTimeoutHeader` enabled
Result:
Armeria gRPC service no longer schedules a timeout if `grpc-timeout` header is omitted when `GrpcServiceBuilder.userClientTimeoutHeader()` is enabled.
> Disable request timeout if `grpc-timeout` is omitted while `useClientTimeoutHeader` is enabled.

- core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
- core/src/test/java/com/linecorp/armeria/server/ErrorHandlerOrElseTest.java
- core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
- core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
- graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilder.java
Motivation:
Some builders use `.orElse()` to allow multiple error handlers, while others allow only one and overwrite the previous value.
For consistency, it would be clear to allow multiple error handlers for all builder methods.
Modifications:
- Fixed `.errorHandler(..)` builder method to compose a new error handler with the old one.
Result:
You can add multiple `(Server|Service)ErrorHandler`s using server and service builder methods.
> Allow adding multiple `(Server|Service)ErrorHandler`s

- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerWithRetryTest.java
…t from RetryingClient
Motivation:
When a child log completes, `responseCause` is propagated as the last property with responseEndTime even if an
`UnprocessedRequestException` occurred before other response properties. 
https://github.com/line/armeria/blob/759bf3b079c0a759d60dc2536fefcefb1cd648d3/core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java#L661-L661
`RESPONSE_CAUSE` can not be used when the callbacks that depend on `RequestLogProperty.RESPONSE_HEADERS` or
`RequestLogProperty.RESPONSE_TRAILERS` are executed. 
https://github.com/line/armeria/blob/3a99e6adb00847422f1345d5a7bfa2d7ab1f8e6d/core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java#L350-L350
Consequently, `CircuitBreakerRule` can't use the cause to determine the …
> Fix a bug where responseCause is not propagated to `CircuitBreakerRule` from `RetryingClient`

- spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationSettingsUtil.java
- spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
- spring/boot3-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsBaseContextPathTest.java
- spring/boot3-autoconfigure/src/test/resources/config/application-baseContextPathTest.yml
Motivation:
The final task of context-path support is to configure the value with Spring auto-configuration.
Modifications:
- `context-path` properties to Armeria settings
- If set, the value is set to `ServerBuilder.baseContextPath()`
Result:
You can now set a base context path of a server via Spring auto-configuration.
```yml
armeria:
context-path: /api/v1
```
> Support context-path for Spring integration

- core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
- core/src/main/java/com/linecorp/armeria/client/ClientOptionsBuilder.java
- core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
- core/src/main/java/com/linecorp/armeria/client/RestClientBuilder.java
- core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContentBuilder.java
- core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
- core/src/main/java/com/linecorp/armeria/client/websocket/WebSocketClientBuilder.java
- core/src/main/java/com/linecorp/armeria/common/HttpRequestBuilder.java
- core/src/main/java/com/linecorp/armeria/common/HttpResponseBuilder.java
- it/builders/src/test/java/com/linecorp/armeria/OverriddenBuilderMethodsReturnTypeTest.java
Motivation:
I found some overridden methods were missed. https://github.com/line/armeria/pull/5107#discussion_r1368090886
While I was at it, I also fixed a test which goes through the entire classpath looking for builders ending with the String `Builder`.
Modifications:
- Fixed `OverriddenBuilderMethodsReturnTypeTest` to not ignore missing methods
- Fixed not overridden methods
Result:
- A more consistent fluent API experience
> Fix missed overridden methods

- core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
- core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
- core/src/main/java/com/linecorp/armeria/common/PublisherBasedHttpResponse.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/main/java/com/linecorp/armeria/internal/common/stream/SurroundingPublisher.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageEndWithTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/SurroundingPublisherTckTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/SurroundingPublisherTest.java
Related issue #4816 
> As a future work of https://github.com/line/armeria/pull/4727,
users might want to dynamically emit the last message depending on whether the upstream publisher completes successfully or exceptionally.
- On #4816, it's good to add `StreamMessage.endWith(finalizer)`
- Add `StreamMessage.endWith(finalizer)`
- Closes #4816 
- Now user can dynamically emit the last value depending on whether the `StreamMessage` completes successfully or exceptionally by using `StreamMessage.endWith(finalizer)`
> Add `StreamMessage.endWith(finalizer)`

- core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
- core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
Motivation:
The `SessionProtocol` event is rescheduled to fire it after `Http2Settings` is applied to `HttpSessionHandler`. 
https://github.com/line/armeria/blob/f93ccca0ea955b6e1858f2b7d95974b561a98423/core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java#L423-L426
This strategy relying on executors does not provide 100% correct order. We also got a report LINE internally that requests start before `Http2Settings` is applied to `HttpSessionHandler` which results in `RST_STREAM` due to a violation of the max concurrent stream.
Modifications:
- Remove the rescheduler for `SessionProcotol` and refactor `HttpSessionHandler` so that `sessionPromise` is completed when both `SessionProtocol` and `Http2Settings` are applied.
Result:
Armeria client no longer violates …
> Start HTTP/2 requests when HTTP2-Settings is applied

- core/src/main/java/com/linecorp/armeria/client/HAProxyHandler.java
- core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
Motivation:
1) `HAProxyHandler` is not a subclass of `ProxyHandler` so the whole proxy process is not bound by a connection timeout. https://github.com/line/armeria/pull/5223#discussion_r1372475060 We need to fix to start a session timeout to include HA proxy as a part of the session handshake.
2) A `ProxyConnectionEvent` is published as a connection is established without waiting for the result of `HAProxyMessage`. The event is rescheduled on the premise that the HAProxy message would be written and the HttpSessionHandler would enter the pipeline during the rescheduling.
It has worked well, but it doesn't provide perfect happen-before. Since `HttpSessionHandler` is added as the first listener of `connectionPromise` by #5223, if the connection is successful in the callback of …
> Publish `ProxyConnectionEvent` after `HAProxyMessage` is written

- core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandlerBuilder.java
- core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
Motivation:
It is not necessary to limit the maximum number of RST_STREAM frames for clients. https://github.com/netty/netty/pull/13671
Modifications:
- Disable the maximum number of RST_STREAM frames for HTTP/2 clients
Result:
- HTTP/2 clients do not limit the maximum number of RST frames per minute before the connection is closed. Only 1.26.0 is affected.
- Breaking) `Flags.defaultHttp2MaxResetFramesPerMinute()` has been removed and `Flags#defaultServerHttp2MaxResetFramesPerMinute()` is now used instead.
> Disable RST_STREAM frame limitation for HTTP/2 clients

- core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
Motivation:
While fixing #5163, I made a bug that `EndpointSelector` returns a null endpoint due to a race condition between an EndpointGroup initialization event and `EndpointSelector.select()`.
```
Caused by:
com.linecorp.armeria.client.endpoint.EndpointSelectionTimeoutException: Failed to select within 3200 ms an endpoint from: HealthCheckedEndpointGroup{endpoints=[Endpoint{127.0.0.1:46843, weight=1000}], numEndpoints=1, candidates=[Endpoint{127.0.0.1:46843, weight=1000}], numCandidates=1, selectionStrategy=class com.linecorp.armeria.client.endpoint.WeightedRoundRobinStrategy, initialized=true, initialSelectionTimeoutMillis=15000, selectionTimeoutMillis=3200, contextGroupChain=[HealthCheckContextGroup{contexts={Endpoint{127.0.0.1:46843, …
```
> Fixed bug where a null endpoint is returned

- spring/boot2-actuator-autoconfigure/build.gradle
- spring/boot2-actuator-autoconfigure/src/main/resources/META-INF/spring.factories
- spring/boot2-autoconfigure/build.gradle
- spring/boot2-autoconfigure/src/main/resources/META-INF/spring.factories
- spring/boot2-webflux-autoconfigure/build.gradle
- spring/boot2-webflux-autoconfigure/src/main/resources/META-INF/spring.factories
Motivation:
`org.springframework.boot.autoconfigure.AutoConfiguration.imports` was introduced in Spring Boot 2.7. The legacy `spring.factories` files in Spring integration modules have been migrated to
`AutoConfiguration.imports` to share the same files between Spring Boot 2 and 3.
Some uses are still using old Spring Boot versions (< 2.7) so they are having trouble upgrading Armeria version due to the removal of `spring.factories`. `spring.factories` is still supported in 2.7. For backward compatibility, the legacy `spring.factories` is a better to provide auto-configuration in the Spring Boot 2 modules.
Modifications:
- Revive `spring.factories` and do not copy `AutoConfiguration.imports` from Spring Boot 3 modules.
Result:
Fixed a bug where Armeria Spring integration is not compatible …
> Remove AutoConfiguration.imports and revert spring.factories for Spring Boot 2

- core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelectorTest.java
Motivation:
Calling `Collection.remove(T)` while iterating a `Collection` may result in `ConcurrentModificationException` or `NullPointerException`. So `Iterator.remove()` is recommended to remove an item while iteration.
A pending future in `AbstractEndpointSelector` may be removed from `pendingFutures` with `pendingFutures.remove()` while iterating as new `Endpoint`s are updated with `ListeningFuture.accept(null)`. That is the same case as above.
```java
NullPointerException: Cannot invoke "com.linecorp.armeria.client.endpoint.AbstractEndpointSelector$ListeningFuture.accept(java.lang.Void)" because "future" is null
at com.linecorp.armeria.client.endpoint.AbstractEndpointSelector.refreshEndpoints(AbstractEndpointSelector.java:154)
at …
```
> Fix NPE raised when pending futures of `AbstractEndpointSelector` is removed

- core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/jni-config.json
- core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/reflect-config.json
Motivation:
As reported in #5296, our GraalVM native image config is out of date.
Modifications:
- Re-ran `./gradlew nativeImageConfig` to generate the new configuration and merged it into `core/src/main/resources/META-INF`.
Result:
- Fixes #5296
> Update GraalVM native image config

- build.gradle
Motivation:
We may be able to increase build speeds locally if we enable PTS for non-CI builds
Modifications:
- Added a PTS setting for tests if the CI field is not set
- https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
Result:
- Faster local builds
> Try enabling PTS for non-CI builds

- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
Motivation:
Malformed json requests continued with an empty request instead of returning an error.
Modifications:
Throw an illegal argument exception when json processing fails instead of ignoring it. The surrounding service will translate it into a BAD_REQUEST response.
Result:
- Closes #5306 
- Requests with a malformed json body will now return a BAD_REQUEST status
> Fix to send 400 from gRPC HTTP/JSON transcoding service when the request is invalid

- core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/FuseableStreamMessage.java
- core/src/main/java/com/linecorp/armeria/internal/common/stream/InternalStreamMessageUtil.java
- core/src/test/java/com/linecorp/armeria/common/stream/FilteredStreamMessageTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewerCancellationTest.java
Motivation:
An `HttpResponse` is cancelled if either the `ResponseHeaders` is `END_OF_STREAM` or the content is expected to be empty. https://github.com/line/armeria/blob/9ddd6c1b76fdc0fe8943dd417e80773cb92eebdc/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L66-L67
If `SubscriptionOption.NOTIFY_CANCELLATION` is set when subscribing, `CancellationSubscripitonException` should be propagated through `Subscriber.onError()`. However, there was a bug in `FuseableStreamMessage` where this error was not propagated. `onError()` signal is ignored if the `StreamMessage` has been canceled.
https://github.com/line/armeria/blob/756c17797f95c1ddc7afbb8038ad046c080ba605/core/src/main/java/com/linecorp/armeria/common/stream/FuseableStreamMessage.java#L297-L300
Apart from that, …
> Fix a bug where `RequestLog` does not complete when `HttpResponse` is cancelled

- site/src/pages/docs/advanced-spring-boot-integration.mdx
Motivation:
In the Spring Boot Integration document, the sample YAML in the `Collecting metrics` section is using incorrect property and value.
Modifications:
- Change `health-check-path` to `metrics-path`
- Change `/internal/healthcheck` to `/internal/metrics`
Result:
- https://armeria.dev/docs/advanced-spring-boot-integration shows correct sample YAML in the `Collecting metrics` section.
> Fix incorrect sample metrics YAML property in Spring Boot integration documentation page

- examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/Main.java
- site/src/pages/docs/advanced-saml.mdx
Motivation:
When I follow https://armeria.dev/docs/advanced-saml/#configuring-your-server-as-a-service-provider, it shows following warnings which suggest to specify `-deststoretype pkcs12`.
```
JKSキーストアは独自の形式を使用しています。"keytool -importkeystore -srckeystore a.jks -destkeystore a.jks -deststoretype pkcs12"を使用する業界標準の形式であるPKCS12に移行することをお薦めします。
```
Modifications:
- Add -deststoretype pkcs12 option to example
Result:
- Less warns at example
> Use `-deststoretype pkcs12` to remove warning

- core/src/test/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessageTest.java
In the test, streamMessage is aborted before `subscribe0` is called: https://github.com/line/armeria/blob/33d1c5ec8f8d99b6bc6908aec01b5b0032ed4d3b/core/src/main/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessage.java#L361 https://github.com/line/armeria/blob/33d1c5ec8f8d99b6bc6908aec01b5b0032ed4d3b/core/src/main/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessage.java#L141-L144 Thus, `whenComplete` future is exceptionally completed before `subscriber.onSubscribe()` is called.
https://github.com/line/armeria/blob/33d1c5ec8f8d99b6bc6908aec01b5b0032ed4d3b/core/src/main/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessage.java#L381
Close #5362
> Fix flaky FixedStreamMessageTest

- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftFunction.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftServiceMetadata.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/DecoratingTHttpServiceTest.java
Motivation:
It would be very useful if we can use `@Decorator` or user defined annotation using `@DecoratorFactory` in `THttpService`.
Modifications:
- Store declared decorator annotations in `ThriftFunction`
- Decorate `THttpService` if there's declared annotations 
Result:
- Closes #4230
> Provide a way to decorate `THttpService` via annotation

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
Motivation:
The current implementation fails to convert `byte[]`, an implicitRequestObject, to `TypeSignature` correctly within the `AnnotatedDocServicePlugin`. [Reference](https://github.com/line/armeria/blob/6f0a1f65fbbc45b0a1ef870b163ee11b01f0bd31/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java#L498-L501)
Modifications:
- Use `AnnotatedDocServicePlugin.toTypeSignature()` to properly convert `byte[]` to `TypeSignature`. This method ensures proper checking of the type before conversion to a struct, as opposed to directly calling `TypeSignature.ofStruct()`.
Result:
- Close #5389.
- Implicit request objects are now correctly converted.
> Properly convert implicit request object in the annotated doc service to type signature

- core/src/main/java/com/linecorp/armeria/common/websocket/CloseByteBufWebSocketFrame.java
Motivation:
When "disconnect" is clicked in the Postman (which is a very common API testing application), a `CLOSE` frame is sent without any reason.
But the `reasonPhrase` function in armeria cannot correctly handle such case.
According to the RFC-6455, this is fully legal.
https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.1
Modifications:
- Reset the reader index if reason is empty
Result:
> Fix illegal state of the ByteBuf if the CLOSE frame does not contain a reason

- grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientBuilder.java
- grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientExceptionHandlerTest.java
Motivation:
This PR attempts to support `GrpcExceptionHandlerFunction` for gRPC client side
Modifications:
- Add `GrpcClientBuilder.exceptionHandler` which accepts a `GrpcExceptionHandlerFunction`
- Modify all `GrpcStatus.fromThrowable(Throwable)` calls to use `GrpcStatus.fromThrowable(GrpcStatusFunction, RequestContext, Throwable, Metadata)` instead
Result:
- Closes #5347
> Support gRPC exception handler for client-side

- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupInitializationRaceTest.java
Motivation:
If new `Endpoint`s are updated in `HealthCheckedEndpointGroup`, `HealthCheckedEndpointGroup` creates a new `HealthCheckContextGroup`. When the new `HealthCheckContextGroup` is initialized, the old `HealthCheckContextGroup` is removed for rolling updates.
The removal logic is added as a fallback to `contextGroup.whenInitialized()`. https://github.com/line/armeria/blob/3f54be0ce4370b24977994e247fa3816fde25e29/core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java#L175-L187 Since context groups are stored in the order in which they were inserted, if the callback added first is executed first, the old value will always be deleted and the latest value will be maintained.
`CompletableFuture` uses a stack structure for callbacks, so the …
> Fix a bug where all healthy endpoints are removed as `HealthCheckedEndpointGroup` is initialized

- core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
- core/src/test/java/com/linecorp/armeria/server/file/HttpFileTest.java
Motivation:
After zipkin upgraded to spring boot, our UI failed to load due to an unanticipated URL format:
```
java.lang.IllegalArgumentException: Unsupported URL: jar:nested:/Users/adrian/oss/zipkin/zipkin-server/target/zipkin-server-3.0.4-SNAPSHOT-exec.jar/!BOOT-INF/lib/zipkin-lens-3.0.4-SNAPSHOT.jar!/zipkin-lens/static/css/main.311b483b.css (must start with 'file:', 'jar:file', 'jrt:' or 'bundle:')
at com.linecorp.armeria.server.file.HttpFile.builder(HttpFile.java:206) ~[!/:?]
at com.linecorp.armeria.server.file.HttpFile.builder(HttpFile.java:230) ~[!/:?]
at com.linecorp.armeria.server.file.ClassPathHttpVfs.blockingGet(ClassPathHttpVfs.java:58) ~[armeria-1.26.4.jar!/:?]
at com.linecorp.armeria.server.file.AbstractBlockingHttpVfs.lambda$get$0(AbstractBlockingHttpVfs.java:82) …
```
> Allow HttpFile to pass a Spring Boot 3 nested jar URL

- eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/InstanceInfo.java
- eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
- eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
- eureka/src/main/java/com/linecorp/armeria/server/eureka/InstanceInfoBuilder.java
- eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
Motivation:
Zipkin has a custom health check service, in addition to the normal
one of type `HealthCheckService`. This is used to create a custom json
response and predated our use of Armeria. This custom one is mounted at
the path "/health" while the default is "/internal/health".
We recently added Eureka registration, but were not able to change the
path component without having to supply the scheme, host and port as
well. To work around this is a bit hacky, and I would like to remove it
as it cause log warnings.
This change is already supported upstream for similar reasons. See
https://github.com/Netflix/eureka/blob/2b09d77534eae703a36f79f99b27b4d6ed66c3f8/eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java#L663-L666
Modifications:
- Added a `healthCheckUrlPath` property …
> eureka: allow overriding the healthCheckUrlPath 

- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingQueryParamMatchRule.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
- grpc/src/test/proto/testing/grpc/transcoding.proto
Motivation:
Currently, LOWER_CAMEL_CASE and ORIGINAL_FIELD are used to match query params with protobuf messages.
It would be nicer if HttpJsonTranscodingQueryParamMatchRule supports json_name field option which is a well-known option that most protobuf JSON codecs implement
Modifications:
- Support for json_name in HttpJsonTranscodingQueryParamMatchRule
- The json name of the field is camelcase by default.  so, it is supported both when it is a camel case and when it is not.
( If json name is used, the default is origin field. https://protobuf.dev/programming-guides/proto3/#json)
Result:
- Closes #5193. (If this resolves the issue.)
- Use origin field and json name
- Use camel case and json name
> fix support json_name options

- benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
- core/src/main/java/com/linecorp/armeria/server/DefaultRoutingContext.java
- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
- core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandlerBuilder.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
- core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java
- core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServiceRouteUtil.java
- core/src/test/java/com/linecorp/armeria/server/CachingRoutingContextTest.java
- core/src/test/java/com/linecorp/armeria/server/RouteTest.java
- core/src/test/java/com/linecorp/armeria/server/RouterTest.java
- core/src/test/java/com/linecorp/armeria/server/RoutingContextSessionProtocolTest.java
- core/src/test/java/com/linecorp/armeria/server/RoutingContextTest.java
- core/src/test/java/com/linecorp/armeria/server/ServiceRouteUtilTest.java
- core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
Motivation:
`SessionProtocol` is needed for determining the exchange type in the [GraphQL over WebSocket Protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#graphql-over-websocket-protocol). https://github.com/line/armeria/pull/5280/files#diff-a47022183a66aad84e8b2d5e43fb0a07c27b5de0299c19b4cfaecd723d0a8e5eR111-R112
Modification:
- Add `SessionProtocol` property to the `RoutingContext`.
Result:
- `RoutingContext` now includes the `SessionProtocol` property, facilitating the determination of exchange types.
> Add `SessionProtocol` property to `RoutingContext`.

- core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListener.java
- core/src/main/java/com/linecorp/armeria/client/ConnectionPoolMetrics.java
- core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
- core/src/test/java/com/linecorp/armeria/client/ConnectionPoolCollectingMetricTest.java
Motivation:
There are no metrics for active connections on the client side out of the box. The number has to be computed by metric queries such as PromQL by subtracting `closed` from `opened`.
Otherwise, a custom metric should be implemented by users.
Modifications:
- Record `armeria.client.connections#value{state="active"}` in `MetricCollectingConnectionPoolListener` to get the active connections for a remote peer.
Result:
- You can now monitor the number of active connections with `armeria.client.connections#value{state="active"}`
- Closes #4277
> Add metrics for active connections on the client side

- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/JavaGrpcClientStubFactory.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/KotlinGrpcClientStubFactory.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ReactorGrpcClientStubFactory.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ScalaPbGrpcClientStubFactory.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ServiceDescriptorResolutionException.java
Motivation:
I got a report that it's not easy to trouble shoot when an exception is raised while creating a gRPC client stub because the exception is swallowed currently.
Modification:
- Introduce `ServiceDescriptorResolutionException` to capture exceptions raised during the invocation of `GrpcClientStubFactory#findServiceDescriptor(Class)` within Armeria's built-in factories.
- Store these exceptions and display them to the user if `GrpcClientFactory` fails to create the client stub.
Result:
-  You can now easily identify issues when failing to create a gRPC client stub.
> Enhance error reporting for failed gRPC client stub creation.

- .github/check-workflow-write-permission.sh
Because @dependabot sends pull requests to update the versions of GitHub Actions plugins in workflow files.
> Grant @dependabot write permission for workflow files.

- xds/src/main/java/com/linecorp/armeria/xds/ClusterRoot.java
- xds/src/main/java/com/linecorp/armeria/xds/ListenerRoot.java
- xds/src/test/java/com/linecorp/armeria/xds/XdsClientIntegrationTest.java
Motivation:
Close operations are done on the event loop from the following change: https://github.com/line/armeria/pull/5336#discussion_r1464615997
However, a flaky test has been introduced.
https://ge.armeria.dev/scans/tests?search.timeZoneId=Asia%2FSeoul&tests.container=com.linecorp.armeria.xds.XdsClientIntegrationTest&tests.test=multipleResources()#
In short, I believe the cause is we update the snapshot before close is fully completed.
Modifications:
- Add an await statement to `XdsClientIntegrationTest#multipleResources`
- Modified so that the `closed` boolean flag is set after the `unsubscribe` is completed
Result:
- Less xds related flaky tests
- Fixes #5411
> Handle flaky xds test

- kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/KubernetesBlockHoundIntegration.java
- kubernetes/src/main/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration
Motivation:
The following method is detected as a blocking operation because `doLockedAndSignal` acquires a lock with `ReentranceLock`.
```
at io.fabric8.kubernetes.client.http.HttpClientReadableByteChannel.doLockedAndSignal(HttpClientReadableByteChannel.java:71)
```
The lock is used to read the remaining data from the given `ByteBuffer`. The Armeria integration creates a fully readable `ByteBuffer` so the lock condition would not happen.
https://github.com/fabric8io/kubernetes-client/blob/2c4d01d6bbc3ef5f077e07611f3723ad49388b5a/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpClientReadableByteChannel.java#L128-L130
Modification:
- Add `KubernetesBlockHoundIntegration` and register `HttpClientReadableByteChannel.doLockedAndSignal()` as a safe call.
Result:
- No …
> Add `BlockHoundIntegration` for kubernetes integration moulde

- .github/dependabot.yml
Motivation:
The following [PR](https://github.com/line/armeria/pull/5377) attempts to update the `package-lock.json` file only.
I've read through the following documents, and believe that specifying the versioning strategy will help update the actual `package.json` dependencies
Modifications:
- Added a versioning strategy for dependabot
- Specified the interval to monthly so that it is better in-sync with our release schedule and we don't receive multiple update pull requests
Result:
- Improved dependabot pull requests
> Add dependabot configuration for `npm` dependencies

- .github/workflows/publish-release.yml
Motivation:
It requires effort to retry the release process due to a test failure.
It may be a better idea to
1) Verify that the build is stable before triggering the release
2) Enable test retries when running the final build for release
Modifications:
- Added a token, retry flag for release build
Result:
- More stable releases
> Retry test failure when publishing release

- .github/check-workflow-write-permission.sh
`GITHUB_ACTOR` name of @dependabot is not `dependabot` but `dependabot[bot]`.
> Fix the incorrect name of @dependabot in `check-workflow-write-permission.sh`

- eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
- eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
Motivation:
Currently, when armeria registers a server, it appends `:${port}` to Eureka VIP addresses to. While it makes sense to encode the port into the Eureka `serviceId`, the VIP address fields are meant to be hostnames or IPs. Encoding a port into the VIP address makes these unusable for certain clients like spring-cloud-sleuth who heuristically look for a port and only if it is absent trigger Eureka lookups.
Modifications:
- I removed the logic that appended `:${port}` to both the `vipAddress` and `secureVipAddress`
- I changed the test which actually proved the bug was present!
Result:
- Manual integration with zipkin, sleuth is now able to look up its endpoint in Eureka.
> Eureka: Remove encoded port from VIP address defaults

- eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/InstanceInfo.java
- eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
- eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
- eureka/src/main/java/com/linecorp/armeria/server/eureka/InstanceInfoBuilder.java
- eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
Motivation:
Following up on the improvements introduced in https://github.com/line/armeria/pull/5369, it's beneficial to extend the autofill feature to include `homePageUrl` and `statusPageUrl` of an `InstanceInfo`. This enhancement streamlines configuration by automatically populating these URLs based on corresponding path properties.
Modifications:
- Introduce `homePageUrlPath` and `statusPageUrlPath` properties to `InstanceInfo` and their respective builders.
- Implement autofill functionality for `homePageUrl` and `statusPageUrl` using the configured path properties.
Result:
- `homePageUrl` and `statusPageUrl` of an `InstanceInfo` in Eureka are correctly set if corresponding path properties are configured.
- Close #5464
> Autofill `homePageUrl` and `statusPageUrl` of an `InstanceInfo` in Eureka using path properties.

- core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListener.java
- core/src/main/java/com/linecorp/armeria/client/ConnectionPoolMetrics.java
- core/src/test/java/com/linecorp/armeria/client/ConnectionPoolCollectingMetricTest.java
Motivation:
An `IllegalArgumentException` is raised when `ConnectionPoolListener.metricCollecting()` is used to monitor connection pools. The changes in #5288 caused the problem.  The different types (`Gauge`, `Counter`) of meters are registered with the same name. Unfortunately, it wasn't caught by unit tests because the restriction only exists in `PrometheusMeterRegistry`. `SimpleMeterRegistry` was used to verify the code.
```java
java.lang.IllegalArgumentException: Failed to register Collector of type MicrometerCollector: armeria_client_connections is already in use by another Collector of type MicrometerCollector
at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:57)
at io.prometheus.client.Collector.register(Collector.java:307)
at …
```
> Fix a bug where duplicate keys are registered in client metrics

- .gitignore
- .idea/icon.svg
Motivation:
There is no intellij project icon.
Modifications:
- Add icon to `.idea/icon.svg`
- (Copied and edited [this logo file](https://github.com/line/armeria/blob/main/site/src/design/armeria_icon.svg) to trim space and make square)
Result:
- Looks good
example
Project icon can be set from welcome page
> Suggestion: Set intellij project icon

- site/src/pages/tutorials/index.mdx
Motivation:
The tutorial introduction (https://armeria.dev/tutorials) mentions the REST tutorial only.
Modifications:
- Rewrite the tutorial introduction to cover all tutorials including the gRPC and Thrift tutorials.
Result:
- Updates the tutorial introduction on Armeria site.
> Update the tutorial introduction

- .editorconfig
- benchmarks/jmh/src/jmh/kotlin/com/linecorp/armeria/internal/common/kotlin/AnnotatedServiceFlowBenchmark.kt
- examples/graphql-kotlin/src/test/kotlin/example/armeria/server/graphql/kotlin/GraphqlArmeriaClient.kt
- examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/HelloServiceImpl.kt
- grpc-kotlin/src/main/kotlin/com/linecorp/armeria/server/grpc/kotlin/CoroutineServerInterceptor.kt
- grpc-kotlin/src/test/kotlin/com/linecorp/armeria/server/grpc/kotlin/CoroutineServerInterceptorTest.kt
- it/grpc/kotlin/src/test/kotlin/com/linecorp/armeria/grpc/kotlin/TestServiceImpl.kt
- it/kotlin/src/test/kotlin/com/linecorp/armeria/it/AnnotatedServiceErrorMessageTest.kt
- kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaRequestCoroutineContext.kt
- kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/FlowAnnotatedServiceTest.kt
- kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt
Motivation:
Currently kotlin maximum line length is set with 140 which is default for ktlint_official(https://pinterest.github.io/ktlint/latest/rules/standard/#max-line-length)
Modifications:
- Set maximum line length of ktlint as 112. This rule is added by `.editorconfig` file.
- Apply ktlint
Result:
- Closes #5421
> Apply ktlint with `max_line_length` as 112

- examples/context-propagation/kotlin/src/main/kotlin/example/armeria/contextpropagation/kotlin/MainService.kt
- site/src/pages/docs/advanced-kotlin.mdx
- site/src/pages/docs/client-grpc.mdx
- site/src/pages/docs/server-grpc.mdx
Motivation:
Some links I tried to click were broken.
Modifications:
- Fix links to the examples.
- Add _See also_ links for kotlin-grpc related stuff.
> Fix links on kotlin docs and fix service request context propagation example

- core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
Fix `HttpHeaderNamesTest. httpHeaderNamesContainsAllFieldsInHttpHeadersInGuava` fail
- Add `SEC_AD_AUCTION_FETCH` and `AD_AUCTION_SIGNALS` to `HttpHeaderNames`
Result:
Closes: https://github.com/line/armeria/issues/5492
> Fix HttpHeaderNamesTest as upgrade Guava

- thrift/thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftFunction.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftMetadataAccess.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDescriptiveTypeInfoProvider.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePlugin.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/common/thrift/ThriftMetadataAccessTest.java
Motivation:
In old Thrift versions (< 0.9.3), the multi-threaded environment was not considered during the initialization process for the Thrift class. A workaround was committed at #4688 but only applied to DocService.
This problem can occur not only in `DocService` but also when creating Thrift clients and other parts, so it would be desirable to use `ThriftMetadataAccess.getStructMetaDataMap()` for places where `FieldMetaData.getStructMetaDataMap()` is used.
```java
// When creating Thrift clients
java.lang.IllegalArgumentException: failed to retrieve function metadata: ...
at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.registerFunction(ThriftServiceMetadata.java:239)
at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.lambda$init$2(ThriftServiceMe …
```
> Fix to thread-safely load Thrift classes for old libthrift (< 0.9.3)

- core/src/main/java/com/linecorp/armeria/client/WebSocketHttp1ClientChannelHandler.java
Motivation:
The following `IllegalReferenceCountException` could be raised during a HTTP/1 Websocket handshake.
```java
01:54:00.031 [armeria-common-worker-kqueue-2-2] WARN  c.l.a.i.client.PendingExceptionUtil - [id: 0xd2fa853c, L:/10.31.29.254:65140 - R:vks-api-prod.linecorp-dev.com/10.120.97.166:443] Unexpected suppressed exception:
com.linecorp.armeria.common.ClosedSessionException: null
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
at …
```
> Fix a possible `IllegalReferenceCountException` in WebSocket handshake

- grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMessageMarshaller.java
Motivation:
`InputStream`s returned by `method.streamRequest()` and `method.streamResponse()` were not closed after use. https://github.com/line/armeria/discussions/5520
Modifications:
- Use try-with-resource to close the `InputStream`s after use
Result:
Fixed a possible memory leak when a custom gRPC marshaler is used.
> Close `InputStream` after marshalling gRPC messages

- xds/src/main/java/com/linecorp/armeria/xds/ClusterSnapshot.java
- xds/src/main/java/com/linecorp/armeria/xds/ConfigSourceClient.java
- xds/src/main/java/com/linecorp/armeria/xds/EndpointSnapshot.java
- xds/src/main/java/com/linecorp/armeria/xds/ListenerSnapshot.java
- xds/src/main/java/com/linecorp/armeria/xds/RouteSnapshot.java
- xds/src/main/java/com/linecorp/armeria/xds/XdsConverterUtil.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsConstants.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointGroup.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointUtil.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/package-info.java
- xds/src/test/java/com/linecorp/armeria/xds/MostlyStaticWithDynamicEdsTest.java
- xds/src/test/java/com/linecorp/armeria/xds/XdsEndpointGroupTest.java
- xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
- xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteMetadataSubsetTest.java
- xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/XdsConverterUtilTest.java
Motivation:
More classes will be added related to client endpoint, so I propose that we move `XdsEndpointGroup` from the package `com.linecorp.armeria.xds` to `com.linecorp.armeria.xds.client.endpoint`.
Although this PR is mostly refactoring, a new API `EndpointGroup#of(ClusterSnapshot)` is added since `ConfigSourceClient` uses `GrpcService` to decide on the endpoint which will be used.
POC: https://github.com/line/armeria/pull/5450
Modifications:
- Move `XdsEndpointGroup`, `XdsConstants` to `com.linecorp.armeria.xds.client.endpoint`
- Introduce a new API `EndpointGroup#of(ClusterSnapshot)`
- Introduce `XdsEndpointUtil` and move `client.endpoint` related utility methods from `XdsConverterUtil`
Result:
- Preparation for adding new features to `XdsEndpointGroup` is done
> Migrate `XdsEndpointGroup` to `client.endpoint` (xDS-endpoint pt 2)

- graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlWebSocketSubscriber.java
- graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceSubscriptionTest.java
- graphql/src/test/resources/testing/graphql/subscription.graphqls
Motivation:
We received a report that when using `graphql-ws` in conjunction with coroutine `callbackFlow`, `awaitClose` is not called. Since the `awaitClose` block is used to clean up resources this is a possible leak.
The cause is the `Subscription` which is passed over via `ExecutionResult` is never cancelled.
From further analysis, I found that we call `ctx.cancel` when a `CLOSE` frame is received.
https://github.com/line/armeria/blob/85bbc6533d4462d44c2d9b370dc15de21f6ef123/graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlWebSocketSubscriber.java#L80
However, the `GraphqlWebSocketSubscriber` is not subscribed with the `NOTIFY_CANCELLATION` option.
https://github.com/line/armeria/blob/85bbc6533d4462d44c2d9b370dc15de21f6ef123/graphql/src/main/java/com/linecorp/armeria/se …
> Ensure subscriptions are completed when a request is completed

- site/src/design/README.md
- site/src/layouts/footer.tsx
- site/src/pages/community/design-resources.mdx
- site/src/pages/community/developer-guide.mdx
- site/src/pages/community/index.mdx
- site/src/pages/community/toc.json
- site/src/pages/docs/index.mdx
- site/src/pages/index.tsx
Motivation:
The company name (LINE Corporation) in the Armeria site is outdated.
Modifications:
- Update "LINE Corporation" to "LY Corporation"
Result:
- Update some texts in the footer and a few pages in the Armeria site.
> Update LINE Corporation to LY Corporation

- core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
- logback/logback12/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Motivation:
We use `ctx.log.authenticatedUser` to record the authenticated user in Central Dogma.
https://github.com/line/centraldogma/blob/54205bfcee1167f84bc1ab1a69e08fa0c3e3f2f3/server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java#L74
It would be more convenient to provide `authenticatedUser` as a built in property since it is already a part of the armeria core APIs anyways.
Modifications:
- Added a built in property for `RequestLogProperty.AUTHENTICATED_USER`
Result:
- Users can propagate `authenticatedUser` via mdc more conveniently
> Add authenticated user to mdc by default

- xds/src/main/java/com/linecorp/armeria/xds/ConfigSourceClient.java
- xds/src/test/java/com/linecorp/armeria/xds/ConfigSourceGrpcServiceTest.java
- xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
Motivation:
At the moment, there is no way for `ConfigSourceClient` to fetch resources with authorization.
This PR adds supports for `grpc_service.initial_metadata`
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto
Modifications:
- Check `grpcService.getInitialMetadataList()` and add header values to `ConfigSourceClient#GrpcServiceBuilder`
Result:
- More xDS use cases can be covered
> Support xDS grpc service initial metadata

- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/AccessLoggerIntegrationTest.java
Motivation:
It is a common use case to use `RequestContextExportingAppender` together with `AccessLogWriter`. However, in order for `RequestContextExportingAppender` to work, the `RequestContext` must be available.
https://github.com/line/armeria/blob/4bfa172606e8059194ccdb2e9fd36c6d22ada786/core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java#L204
For this reason, I propose that `config.accessLogWriter()::log` be called with the `RequestContext` set on the calling thread
Modifications:
- Searched all references of `config.accessLogWriter()::log` and wrapped in a `ctx.push` call.
Result:
- access logs are written with the `RequestContext` set on the calling thread.
> Access logs are written within the Request Context

- core/src/main/java/com/linecorp/armeria/client/WebClient.java
- core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
- core/src/test/java/com/linecorp/armeria/client/WebClientExchangeTypeTest.java
Motivation:
`ExchangeType` is a hint for performance optimization. If no `RequestOptions` is set, it is inferred from the type of `HttpRequest`. However, a custom `RequestOptions` is set, `ExchangeType` is not inferred even if the `RequestOptions.exchangeType()` is null.
Modifications:
- Use `ExchangeType.RESPONSE_STREAMING` if `RequestOptions.exchangeType()` is null and `HttpRequest` is an instance of `FixedStreamMessage`.
- If none of the above conditions are met, the method defaults to returning ExchangeType.BIDI_STREAMING.
Result:
`ExchangeType` is guessed correctly even if `RequestOptions` is set.
> Guess `ExchangeType` if it is not set in `RequestOptions`

- site/src/layouts/base.tsx
Motivation:
The absence of a trailing slash on the `redirectUrl` host of BaseLayout exposes the system to Open Redirect vulnerabilities when the matched value of the regex is altered.
Modifications:
- Added logic to append a trailing slash to the `redirectUrl` host.
Result:
- Open redirect vulnerabilities are mitigated on armeria.dev site.
> Prevent open redirect by appending a trailing slash

- core/src/main/java/com/linecorp/armeria/common/websocket/WebSocketFrame.java
- it/websocket/src/test/java/com/linecorp/armeria/it/websocket/WebSocketServiceItTest.java
Motivation:
There is a bug in the Websocket Server PING/PONG handing. When a PING message is sent to Server, the Server incorrectly sends out another PING message as a reply. This is because the code to create the PONG message has a bug in it. The problem is that when testing the PING/PONG mechanism, the Server incorrectly send a PING as a reply for a PING. And this caused whoever was sending the initial PING to receive an incorrect reply to the PING. This was only happening for the case when the PING message has data.
Modifications:
- In the method: `com.linecorp.armeria.common.websocket.WebSocketFrame#ofPong(byte[])`, there is the bug. I modified the code to return the correct Frame. See the files changed.
- I also created unit test for this case
Result:
- Websocker PING that contain …
> Websocket bug: PING to server sends PING Frame instead of PONG Frame

- core/src/main/java/com/linecorp/armeria/internal/server/RouteDecoratingService.java
- core/src/main/java/com/linecorp/armeria/internal/server/websocket/DefaultWebSocketService.java
- core/src/main/java/com/linecorp/armeria/server/DecoratingHttpServiceFunction.java
- core/src/main/java/com/linecorp/armeria/server/DecoratingService.java
- core/src/main/java/com/linecorp/armeria/server/FunctionalDecoratingHttpService.java
- core/src/main/java/com/linecorp/armeria/server/Server.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
- core/src/test/java/com/linecorp/armeria/server/ServiceAddedTest.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/DecoratingTHttpServiceTest.java
Motivation:
Checking the cause of CI failure, I found that `serviceAdded` is not called for the decorators directly added to a server. https://ge.armeria.dev/s/lqh63hxstqzou/tests/task/:xds:shadedTest/details/com.linecorp.armeria.xds.ConfigSourceGrpcServiceTest/testHeader()?top-execution=1
Previously, `serviceAdded` was only invoked for services and decorators wrapping the services. Decorators that were added dynamically were not being called:
- Route decorators
- Annotated decorators for Thrift
- Created by `DecoratingHttpServiceFunction`
Modifications:
- All internal decorators of `RouteDecoratingService` are correctly invoked.
- A condition is added logic to prevent duplicate calls and infinitive calls.
- Added a similar approach to `THttpService`.
- Added `serviceAdded` method to …
> Fix a bug where decorator's `serviceAdded` is not invoked

- core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
- core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
- core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
- core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
- core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
- core/src/main/java/com/linecorp/armeria/common/RequestTarget.java
- core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
- core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
- core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
- core/src/main/java/com/linecorp/armeria/internal/common/NonWrappingRequestContext.java
- core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
- core/src/test/java/com/linecorp/armeria/client/DomainSocketClientTest.java
- core/src/test/java/com/linecorp/armeria/client/RedirectingClientTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
Reported by @ohadgur at https://discord.com/channels/1087271586832318494/1209914423494311948
Motivation:
If a client is configured to follow redirects with `followRedirects()`, the client will validate the value of `Location` header before sending a follow-up request to the given redirect location. `RedirectingClient` validates and resolves the target location using `URI.resolve()` which rejects poorly encoded `Location` header values such as:
- `Location: /foo bar` (space should be percent-encoded)
- `Location: /?${}` (`$`, `{` and `}` should be percent-encoded.)
Such strict validation might not be suitable in real world scenarios and we could
normalize them just like a client validates and normalizes the initial request target.
Modifications:
- `RedirectingClient` now uses …
> Relax the validation of `Location` header when redirecting

- xds/src/main/java/com/linecorp/armeria/xds/AbstractRoot.java
- xds/src/main/java/com/linecorp/armeria/xds/ConfigSourceClient.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterEntry.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterManager.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/LoadBalancer.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/MetadataUtil.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/PrioritySet.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/SubsetLoadBalancer.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsAttributeAssigningEndpointGroup.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsAttributesKeys.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointGroup.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointSelector.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointUtil.java
- xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
- xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/HealthCheckedTest.java
- xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteMetadataSubsetTest.java
- xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/StrictDnsIntegrationTest.java
- xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/XdsConverterUtilTest.java
This PR attempts to support `DNS`, Health Checked clusters. This is done by converting `ClusterSnapshot` to an `EndpointGroup` via `XdsEndpointUtil#convertEndpoints`. The rest of the changes are simply refactoring.
Motivation:
There are three major points of change:
1. `XdsEndpointUtil#convertEndpointGroup` has been introduced which converts a `ClusterSnapshot` into an `EndpointGroup`.
This method essentially converts a `ClusterSnapshot` into a `DnsAddressEndpointGroup` or a `HealthCheckedEndpointGroup`. Note that only basic functionality is supported at this stage.
During this implementation, I found it convenient to refer to a `LbEndpoint` or `LocalityLbEndpoints` for a particular `Endpoint`. For this reason, `XdsAttributeKeys`, `XdsAttributeAssigningEndpointGroup` has been introduced …
> Support `STRICT_DNS`, `HealthCheck` for `XdsEndpointGroup` (xDS-endpoint pt 3)

- graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlWSSubProtocol.java
- graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceSubscriptionTest.java
Motivation:
When constructing the `Complete` message in the GraphQL over WebSocket Protocol, appending a string directly to the ID can lead to malformed messages if the input is manipulated by the user. This vulnerability could potentially allow users to create arbitrary responses by inputting malformed IDs.
Modification:
- Serialize the `Complete` message using a map instead of concatenating strings directly.
Result:
- The `Complete` message in the GraphQL over WebSocket Protocol is now constructed securely.
> Enhance security of the Complete message for GraphQL over WebSocket protocol

- core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
Motivation:
Currently a JVM shutdown hook is added when DefaultClientFactory is used for the first time ([code](https://github.com/line/armeria/blob/main/core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java#L80-L83)). It is possible that a JVM shutdown hook is being added after the JVM has started its shutdown and results in an exception below:
```
Caused by: java.lang.IllegalStateException: Shutdown in progress
at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:216)
at grpc_shaded.com.linecorp.armeria.client.DefaultClientFactory.<clinit>(DefaultClientFactory.java:79)
... 24 more
```
Modifications:
- Skip adding the hook if we explicitly disabled it.
- Add try-catch for ` …
> Avoid addShutdownHook to JVM during its shutdown

- kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaCoroutineUtil.kt
- kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/ValueClassTest.kt
Motivation:
The following error is raised when Kotlin value class is declared in the parameters of annotated services.
```
INFO: object is not an instance of declaring class
java.lang.IllegalArgumentException: object is not an instance of declaring class
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at kotlin.reflect.jvm.internal.calls.InlineClassAwareCaller.call(InlineClassAwareCaller.kt:135)
at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
at …
```
> Support for Kotlin value class in annotated services

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
- core/src/main/java/com/linecorp/armeria/server/annotation/Default.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/EmptyParameterWithDefaultAnnotationTest.java
Motivation:
Say we have an annotated service that uses `@Default `annotation to optionally bind query parameters.
```java
class MyService {
@Get("/list")
public String list(@Default @Param Integer page) {
...
}
}
```
It does not inject `null` if there is a parameter but no value. A NumberFormatException is raised when `/list?page=` is sent as the request path.
It would be better to solve this problem as follows the value of the parameter is empty.
Modifications:
- Logger will warn that the parameter value is not present (It may be intended, such as sending an empty string as the parameter)
- Inject an empty string `""` if the type of the parameter is `String`
- Inject `null` if the type of the parameter is not `String` such as `Integer`, `Boolean` and so on
- Throw an …
> Handle an empty query parameter with @Default

- core/src/main/java/com/linecorp/armeria/internal/server/websocket/DefaultWebSocketService.java
- core/src/main/java/com/linecorp/armeria/server/annotation/decorator/CorsDecorator.java
- core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
- core/src/main/java/com/linecorp/armeria/server/cors/ChainedCorsPolicyBuilder.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsDecoratorFactoryFunction.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicyBuilder.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
- core/src/main/java/com/linecorp/armeria/server/websocket/WebSocketServiceBuilder.java
- core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
- core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceCorsTest.java
Motivation:
Allow users to specify CORS allowed origins by regular expression or `Predicate<String>` 
Modifications:
Users can specify allowed origins by using regular expression or `Predicate<String>` like below. 
<b>CorsDecorator</b> 
```
@CorsDecorator(
originRegex = "http://example.*",
allowedRequestMethods = HttpMethod.GET
)
``` 
<b>`CorsService`'s `builderForOriginRegex` or `builder(Predicate<String> originPredicate)`</b>
```
sb.service("/cors15", myService.decorate(
CorsService.builderForOriginRegex("http://example.*")
.allowRequestMethods(HttpMethod.GET)
.newDecorator()));
sb.service("/cors17", myService.decorate(
CorsService.builder(origin -> origin.contains("example") || origin.contains("line"))
.allowRequestMethods(HttpMethod.GET)
.newDecorator()));
```
or per route 
``` …
```
> Add features to allow users specify regular expression or `Predicate` for CORS allowed origins 

- gradle.properties
Motivation:
Our project version should be greater than the latest release version, which is not the case at the moment.
Modifications:
- Update the project version from 1.27.3-SNAPSHOT to 1.28.0-SNAPSHOT.
Result:
- We now publish the SNAPSHOT JARs with the correct version.
> Update the project version to 1.28.0-SNAPSHOT

- .github/workflows/pr-stale.yml
Motivation:
There are many PRs that are open but stale. Possible reasons for the stale would be:
- An appropriate solution for a problem could not be found
- Maintainers or contributors are busy.
- A PR depends on other PRs or a library patch.
In order to separate and manage old PRs more systematically, it would be a good idea to add `stale` label to the PR.
For PRs marked as stale, maintainers will determine whether to close the PR or modify it themselves.
Modifications:
- Add a stale bot that marks inactive PRs for 30 days
- Auto-close is disabled.
- Don't mark issues as stale.
Result:
A stale bot is working in the Armeria repository on a daily basis.
> Add a stale bot

- core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
- core/src/test/java/com/linecorp/armeria/client/RedirectSignatureTest.java
- core/src/test/java/com/linecorp/armeria/client/RedirectingClientTest.java
Motivation:
Current implements can detect only cyclic redirect which comes back to original URL like `a --> b --> c --> a`.
And cannot detect some cases, for example, partial cyclic one like `a --> b --> c --> b` , however it returns [TooManyRedirectsException](https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java#L274-L277) instead of [CyclicRedirectsException](https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java#L266-L270).
This is caused because adding redirect info to `Multimap` to check the cyclic always returns `true`. ([code](https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2 …
> Improve incorrect cyclic redirect detection logic

- .github/dependabot.yml
Motivation:
In #5378, I'd followed the following [post](https://stackoverflow.com/questions/60201543/dependabot-only-updates-lock-file) to prevent [PR](https://github.com/line/armeria/pull/5541)s that only updates the `package-lock.json` file.
I hadn't realized that the indentation was off though 😅 
Modifications:
- Fixed indentation for npm versioning strategy
Result:
- Less noisy npm dependency updates
> Fix incorrect indentation in dependabot npm strategy

- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpHttpLoggingInterceptorTest.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMockServerTest.java
Motivation:
```
05:53:28.204 [Test worker] ERROR io.netty.util.ResourceLeakDetector - LEAK: ClientFactory.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
com.linecorp.armeria.client.DefaultClientFactory.<init>(DefaultClientFactory.java:101)
com.linecorp.armeria.client.ClientFactoryBuilder.build(ClientFactoryBuilder.java:964)
com.linecorp.armeria.client.kubernetes.ArmeriaHttpClientBuilder$ClientFactoryBuilderHolder.maybeBuild(ArmeriaHttpClientBuilder.java:168)
com.linecorp.armeria.client.kubernetes.ArmeriaHttpClientBuilder.clientFactory(ArmeriaHttpClientBuilder.java:146)
com.linecorp.armeria.client.kubernetes.ArmeriaWebSocketClient.webSocketClient(ArmeriaWebSocketClient …
```
> Close k8s client explicitly to avoid leak

- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpHttpLoggingInterceptorTest.java
Motivation:
We're seeing the following error and I don't think there's much we can do about it.
I propose that we just adjust the lenient setting - the original purpose of mockito strictness is probably not relevant here since we use a 3rd party's test anyways.
https://ge.armeria.dev/scans/tests?search.relativeStartTime=P28D&search.tags=CI%2Cnot:PR&search.timeZoneId=Asia%2FSeoul&tests.container=com.linecorp.armeria.client.kubernetes.ArmeriaHttpHttpLoggingInterceptorTest&tests.sortField=FLAKY&tests.test=responseBodyIsNotConsumed()
> Add lenient strictness to k8s test

- core/src/main/java/com/linecorp/armeria/internal/server/websocket/DefaultWebSocketService.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
- core/src/main/java/com/linecorp/armeria/server/websocket/WebSocketServiceBuilder.java
- core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
- core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceCorsTest.java
Motivation:
We are lowercasing origins we would like to check:
https://github.com/line/armeria/blob/d31dc60bb080a51915e528473c6d8c96d5c699eb/core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java#L79
However, we use the non-normalized origin in the request header to find the correct CORS policy to apply:
https://github.com/line/armeria/blob/d31dc60bb080a51915e528473c6d8c96d5c699eb/core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java#L109
Detailed logs can be found here: https://github.com/line/centraldogma/pull/940
Modifications:
- Use the lowercased request origin header to find the correct CORS policy
Result:
- Previous behavior is revived
> CORS origin is checked in a case-insensitive manner

- dependencies.toml
Motivation:
this fixes a thread safety issue on concurrent use of `Tag.tag` on a single span
https://github.com/openzipkin/brave/releases/tag/6.0.3
Modifications:
- changed the dependencies file
Result:
- no more concurrency issue
> Bump brave from 6.0.2 to 6.0.3

- core/src/main/java/com/linecorp/armeria/internal/common/stream/AbstractFixedStreamMessage.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/AggregatingDecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
- core/src/test/java/com/linecorp/armeria/server/AggregatingRequestTimeoutTest.java
- core/src/test/java/com/linecorp/armeria/server/ExceedingServiceMaxContentLengthTest.java
- jetty/jetty11/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
- jetty/jetty12/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
- jetty/jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
- saml/src/main/java/com/linecorp/armeria/server/saml/SamlService.java
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
- tomcat10/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Motivation:
If `ExchangeType` is `UNARY` or `RESPONSE_STREAMING` for a service, a timeout is scheduled after EOS is received. If it takes a long time to receive a full request body, the request will not end with 503 Service Unavailable even after the request timeout set by the user.
Modifications:
- Immediately fire a `DecodedHttpRequest` when request headers are received in `Http{1,2}RequestDecoder`
- `HttpServerHandler` uses `whenAggregated()` to wait for the unary request to be aggregated on behalf of `Http{1,2}RequestDecoder`
- Remove some methods specialized for `AggregatedDecodedHttpRequest` has been deleted
Result:
Unary and response streaming requests are now properly timed out if they fail to receive the body within the designated timeout period.
> Fixed bug where a request timeout is scheduled after receiving the entire body

- core/src/test/java/com/linecorp/armeria/server/ExceedingServiceMaxContentLengthTest.java
Motivation:
ref: https://github.com/line/armeria/actions/runs/8657061918/job/23738591838#step:11:1610
I believe the bytebuf release lifecycle doesn't have a causal relationship with receiving the response
> Wait until buffers are released in `ExceedingServiceMaxContentLengthTest.maxContentLength`

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java
Motivation:
- The annotation `@Description` is used to give a description for `Class`, `Method`, and `Method parameter` at Doc-service.
- The annotation `@Description` could only exist at Super class or Interface in order to give a common desecription for multiple other class which extend or implmenet them. (First initiative: https://github.com/line/armeria/discussions/5192)
- However, the `@Description` at Super class or Interface is ignored at Doc-service. Let's make it effective.
Modifications:
- Make `resolveTargetElements#AnnotationUtil` returns all `AnnotatedElement` not only for specific one but also for all in Super class and Interface when the given specific one is `Parameter`or `Method` type.
Result: …
> Make @Description annotation at super class/interface work

- core/build.gradle
Motivation:
Modifications:
From issue #5581, the class is exposed in the public API.
> Class io.netty.channel.unix.DomainSocketAddress is used as public method parameter in core/src/main/java/com/linecorp/armeria/common/util/DomainSocketAddress.java
Result:
- Closes #5581. (If this resolves the issue.)
- User can use [core] com.linecorp.armeria.common.util.DomainSocketAddress#asNettyAddress without adding dependency
> [Issue-5581] Change into transitive dependency(netty.transport.native.unix.common)

- core/src/main/java/com/linecorp/armeria/client/Endpoint.java
- core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
- core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
- core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
- core/src/main/java/com/linecorp/armeria/internal/common/SchemeAndAuthority.java
- core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
- core/src/test/java/com/linecorp/armeria/client/WebClientWithoutPortTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/SchemeAndAuthorityTest.java
Motivation:
- Make util method to deduplicate the code that strips the user info from authority
Modifications:
- ~Add `normalizeAuthority()`, `normalizeSchemeAndAuthority()` static method in `ArmeriaHttpUtil`~
- Add SchemeAndAuthorit class which is in charge of authority normalization
Result:
- Closes #5490. (If this resolves the issue.)
> Add SchemeAndAuthority class which is in charge of authority normalization

- core/src/test/java/com/linecorp/armeria/common/logging/JsonLogFormatterTest.java
- kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaCoroutineUtil.kt
- kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/NullableTypeSupportTest.kt
Motivation:
A regression was identified where an annotated service with a Kotlin suspend function does not work as expected when the parameter is nullable.
Modifications:
- Updated the function call to include null parameters when invoking `kFunction.callSuspendBy()`.
Result:
- The annotated service with a Kotlin suspend function works correctly even with a nullable parameter.
> Ensure annotated service with Kotlin suspend function supports nullable parameters

- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterEntry.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterManager.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/SubsetLoadBalancer.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointGroup.java
- xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
- xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteMetadataSubsetTest.java
- xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/XdsConverterUtilTest.java
Motivation
The default subset policy, `LbSubsetFallbackPolicy.NO_FALLBACK`, should be supported.
Modifications:
- Support `LbSubsetFallbackPolicy.NO_FALLBACK`
- Add `toString` methods for xDS classes
Result:
- `XdsEndpointGroup` now adheres to the `LbSubsetFallbackPolicy.NO_FALLBACK` policy.
> Support LbSubsetFallbackPolicy.NO_FALLBACK

- core/src/main/java/com/linecorp/armeria/common/stream/CancellableStreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/test/java/com/linecorp/armeria/server/RequestTimeoutTest.java
Motivation:
A hook needs to be added to the `HttpResponse` returned from an `HttpService` to allow recovery when the `HttpResponse` is aborted. This hook must be added to the outermost `HttpResponse` to effectively handle exceptions raised in any layer.
Additionally, `DeferredHttpResponse` contains a bug that causes `Subscriber.onError()` to be called twice under certain conditions. This occurs when:
- A `downstreamSubscription` is set and the `DeferredHttpResponse` is aborted, causing downstream onError to be called. https://github.com/line/armeria/blob/armeria-1.28.3/core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java#L311 https://github.com/line/armeria/blob/armeria-1.28.3/core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java#L390 …
> Add recovery hook to outermost HttpResponse and fix DeferredStreamMessage

- benchmarks/jmh/build.gradle
**Motivation**
We often run benchmarks several times without modifying the code.
However, with gradle up-to-date checks, we can often see that only the first run actually applies benchmarks.
I think it's reasonable that the jmh task output caching is always disabled
**Modifications**
Always disable output caching for jmh tasks
**Result**
It is easier to run benchmarks
> Disable output caching for jmh module

- site/src/pages/docs/server-access-log.mdx
Fix "Customizing timestamp format" link in server access log docs (https://armeria.dev/docs/server-access-log)
(built locally)
> Fix link in server access log docs

- core/src/main/java/com/linecorp/armeria/internal/common/util/ServiceNamingUtil.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceElement.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/DefaultAnnotatedService.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/HttpResultUtil.java
- core/src/main/java/com/linecorp/armeria/server/ContextPathAnnotatedServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServerErrorHandler.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/VirtualHostContextPathAnnotatedServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/annotation/AnnotatedService.java
- kotlin/src/main/java/com/linecorp/armeria/common/kotlin/CoroutineContexts.java
Motivation:
- Related issue: #5382
- It'd be nice if a user can access the information provided by `AnnotatredService`, but it is not part of the public API.
- Split `AnnotatedService` into `AnnotatedService` (interface) and 
`DefaultAnnotatedService` (implementation).
- Closes #5382
Before:
```java
ServiceRequestContext serviceRequestContext = ServiceRequestContext.current();
AnnotatedService service = serviceRequestContext.config().service().as(AnnotatedService.class);
// This doesn't compile.
// service.method(); 
// service.defaultStatus();
```
After:
```java
ServiceRequestContext serviceRequestContext = ServiceRequestContext.current();
AnnotatedService service = serviceRequestContext.config().service().as(AnnotatedService.class);
// This compiles and provides useful properties. …
```
> Make AnnotatedService public

- docs-client/src/containers/MethodPage/DebugPage.tsx
Motivation:
When copying a request as a cURL command in DocService, only the URL path is quoted. For example, `curl http://localhost:8080'/foo/bar'`. It would be better to quote the full URL, like `curl 'http://localhost:8080/foo/bar'`.
Modifications:
- Add quotes and call `escapeSingleQuote()` only when constructing the final URL
Result:
- The copied cURL command has the full URL quoted
Tested the following outputs:
- `curl [...] 'http://localhost:8080/foo/bar'`
- `curl [...] 'http://localhost:8080/foo/bar?qwe=asd'`
- `curl [...] 'http://localhost:8080/foo/bar?qwe="asd"'`
- `curl [...] 'http://localhost:8080/foo/bar?qwe='\''asd'\'''`
> Quote the full URL in cURL commands

- core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
Motivation:
Armeria allows overriding its default distribution metric config but `servieLevelObjectives` config is not respected in its timer metrics
Modification:
Made Armeria respect user-provided `serviceLevelObjectives` in its timer histogram metrics.
Result:
- Timer histogram metrics exposed by Armeria repects user-provided `serviceLevelObjectives`.
> Respect user-provided `serviceLevelObjectives` in timer histogram metrics

- .github/dependabot.yml
- .github/workflows/actions_build.yml
- .github/workflows/e2e-chaos-tests.yml
- .github/workflows/gradle-cache-check.yml
- .github/workflows/gradle-enterprise-postjob.yml
- .github/workflows/publish-release.yml
- build.gradle
- settings.gradle
Motivation:
Gradle enterprise plugin is rebranded as "Develocity" since 3.17 and several core functionalities have been deprecated, and will be removed in a future plugin version.
Modification:
- Migrate gradle enterprise plugin to the develocity plugin ([migration guide](https://docs.gradle.com/develocity/gradle-plugin/legacy/#develocity_migration))
- Simple renames.
- Remove explicit `taskInputFiles` setting. Since 3.17, hashes of inputs of tasks will be captured by default.
- Remove `buildScan.publishAlways`. The updated Develocity `buildScan.publishing` publishes a Build Scan by default.
Result:
Gradle enterprise plugin is migrated to the Develocity plugin.
---
> WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity …
> Migrate gradle enterprise plugin to develocity

- core/src/test/java/com/linecorp/armeria/server/logging/AccessLoggerIntegrationTest.java
Motivation:
`ServiceRequestContext` does not implement `equals()` which results in an intermittent failure due to comparing instance references.
ref: https://github.com/line/armeria/actions/runs/8655794720/job/23735309425?pr=5593#step:10:1210
Modifications:
- Compare the requestId instead
Result:
- Less flaky tests
> Fix flaky `AccessLoggerIntegrationTest`

- core/build.gradle
- core/src/main/java/com/linecorp/armeria/internal/common/util/MinifiedBouncyCastleProvider.java
- core/src/main/java/com/linecorp/armeria/internal/common/util/SelfSignedCertificate.java
- core/src/test/java/com/linecorp/armeria/internal/common/util/MinifiedBouncyCastleProviderTest.java
Motivation:
`SelfSignedCertificate` fails to generate a self-signed certificate and throws a
`NullPointerException` when all of the following conditions are met:
- DEBUG-level logging of JDK security event is enabled; and
- A user has no Bouncy Castle dependency.
JDK security event logging and the absence of Bouncy Castle interact with each other in the following way:
- With logging enabled, JDK tries to retrieve the `PublicKey` for logging via `java.security.cert.Certificate#getPublicKey()`, but it returns `null`.
- `Certificate.getPublicKey()` returns `null` because Armeria internally relies on a minimal version of Bouncy Castle that doesn't have all the necessary algorithms.
Modifications:
- Updated ProGuard settings so that all the necessary classes are included in the shaded JAR.
- …
> Fix self-signed certificate generation failure

- site/src/components/code-block.tsx
- site/src/pages/community/developer-guide.mdx
Motivation:
When copying code from documentation, "$" is copied. It's painful to copy code with "$" because users will have to delete the it everytime. 
Modifications:
- Omit the "$" when it's a prefix 
Result:
- Closes #<https://github.com/line/armeria/issues/5322>. (If this resolves the issue.)
- Code is copied without "$" prefix
> [Docs] Omit "$" character when copying code 

- grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientBuilder.java
- grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
- grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMessageMarshaller.java
- grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/UnaryServerCall.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientBuilderTest.java
- grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/GrpcMessageMarshallerTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/DeferredListenerTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/StreamingServerCallTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/UnaryServerCallTest.java
Motivation:
- This PR adds option to use marshaller that specified in gRPC `MethodDescriptor`
- Related Issue #5103
- Partial solved: Option to use marshaller that specified in gRPC `MethodDescriptor`
- Unsolved part: Provide way to add custom marshaller
Modifications:
- New option `useMethodMarshaller`
- default value is `false`
- Add validate logic for `GrpcServiceBuilder` and `GrpcClientBuilder` to check that `unsafeWrapDeserializedBuffer` and `useMethodMarshaller` are mutually exclusive
Result:
- Have new option `useMethodMarshaller`
- Throw `IllegalStateException` when both `unsafeWrapDeserializedBuffer` and `useMethodMarshaller` are enabled
> Add option to respect the marshaller specified in gRPC MethodDescriptor

- core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
- core/src/main/java/com/linecorp/armeria/common/logging/ClientConnectionTimings.java
- core/src/main/java/com/linecorp/armeria/common/logging/ClientConnectionTimingsBuilder.java
- core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java
- core/src/test/java/com/linecorp/armeria/client/TlsHandshakeTimingTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
- settings.gradle
Motivation:
Collect the timings related with TLS handshake. If a request was the first in a connection, armeria could also provide it in a RequestLog to tell a user that the request timing has been affected by TLS handshake.
Modifications:
- Add TLS handshake related field in `ClientConnectionTimings`
- Add TLS handshake duration metric field at MetricCollectingClient
- Start collecting the TLS handshake timer in the case below.
- ~~If the client is enabled as `TCP fast open` in the first request, start the timer before the TCP connection.~~
- start the timer when netty calls `SslHandler.channelActive()`
Result:
- Closes #3647
> Collect timings related with TLS handshake

- saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java
- saml/src/test/java/com/linecorp/armeria/server/saml/SamlServiceProviderTest.java
- site/src/pages/docs/advanced-saml.mdx
Motivation:
This PR addresses a code enhancement in the SamlAssertionConsumerFunction by initializing the messageContext variable at the beginning of the method. This change is intended to streamline the assignment and handling of messageContext, ensuring that it can be consistently used throughout the method, particularly in exception handling scenarios.
Modifications:
Declared messageContext at the method start to allow its use across the entire method scope, including within try and catch blocks.
Result:
- Closes #5401 
- The refactor ensures messageContext is available for error handling.
> Refactor messageContext initialization for enhanced scope availability in SamlAssertionConsumerFunction

- core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
- core/src/main/java/com/linecorp/armeria/common/MediaType.java
- core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
Motivation:
Added necessary headers and MediaTypes for Git HTTP, as a follow-up to https://github.com/line/centraldogma/pull/954.
> Add headers and MediaTypes for Git HTTP

- core/src/main/java/com/linecorp/armeria/client/WebClientRequestPreparation.java
- core/src/test/java/com/linecorp/armeria/client/WebClientRequestPreparationTest.java
Motivation:
Resolve issue #5454 with proper handling of ObjectMapper instance.
Modifications:
- Pass the provided ObjectMapper to the ResponseAs.json method:
`WebClientRequestPreparation.asJson(Class<? extends T> clazz, ObjectMapper mapper)`.
Result:
- The `asJson` method pass the provided ObjectMapper instance to the `ResponseAs.json` method as it should
- Closes #5454
> Fix asJson method to pass mapper in WebClientRequestPreparation

- settings/checkstyle/checkstyle.xml
Motivation:
In the latest developer guide, it is recommended to use `Copyright $today.year LY Corporation`, but the check-style settings have not been adapted accordingly. When this copyright notice is used, a check-style warning occurs.
Modifications:
- Updated check-style setting for LY corp copyright
Result:
- Using either LINE copyright or LY copyright will pass the check-style test.
> update check-style setting for LY corp copyright

- core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/test/java/com/linecorp/armeria/client/Http2ClientPrefaceTest.java
Motivation:
There are two modes to negotiate cleartext HTTP/2 connections. They are HTTP/2 connection preface and HTTP/1 upgrade requests. The default behavior is determined by `ClientFactoryOptions.useHttp2Preface()`. This option affects' http' and `h2c`, so even if a user uses `h2c` with prior knowledge, an upgrade request will be sent if `useHttp2Preface() == false`.
With prior knowledge, it is an unwanted behavior for `useHttp2Preface()` option to affect `h2c` scheme. `h2c` is an explicit scheme whose negotiation should be fixed to the HTTP/2 connection preface. Its endpoint may not understand the HTTP/1 upgrade.
So it would make more sense to apply to `useHttp2Preface()` option to adjust the default behavior of `http`.  If both `http` and `h2c` follow `useHttp2Preface()`, there is no …
> Always use HTTP/2 preface for H2C

- core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
- core/src/main/java/com/linecorp/armeria/common/stream/NoopCancellableStreamMessage.java
- core/src/main/java/com/linecorp/armeria/server/AggregatingDecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServerErrorHandler.java
- core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
- core/src/test/java/com/linecorp/armeria/server/AggregatingRequestTimeoutTest.java
- core/src/test/java/com/linecorp/armeria/server/RequestTimeoutTest.java
Motivation:
Currently, the server always responds with a 503 status if a `RequestTimeoutException` is raised. However, according to the RFC 9110, the correct response in this case should be a 408 status code. https://httpwg.org/specs/rfc9110.html#status.408
```
The 408 (Request Timeout) status code indicates that the server did not receive a complete request message within the time that it was prepared to wait.
```
Modification:
- Introduced `DecodedHttpRequest.isNormallyClosed()` to check if the request was received fully.
- Updated the server to send a 408 response when a request times out and the service didn't receive the request fully.
Result:
- The server now returns a 408 status if a service didn't receive the request fully and the request times out.
- Issue #5579 has been closed.
> Respond with 408 status when the server didn't receive the request fully

- core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
- oauth2/src/main/java/com/linecorp/armeria/client/auth/oauth2/OAuth2Client.java
- oauth2/src/test/java/com/linecorp/armeria/client/auth/oauth2/OAuth2ClientRetryTest.java
Motivation:
When `OAuth2Client` fails to acquire a granted access token, it directly returns a failed response. As the response is returned, `RequestLog` is not completed.
`RetryingClient` waits for some properties of `RequestLog` to be completed. Therefore, the incomplete `RequestLog` causes `RetryingClient` to get stuck.
This PR is a temporary workaround to fix the problem. The deadlock phenomenon will occur easily if a decorator returns a response directly. I created #5714 in which I will try to solve this problem ultimately.
Modifications:
- If `getAccessToken()` completes exceptionally, completes the log and then returns a failed response.
Result:
Fixed a bug where `RetryingClient` gets to deadlock when `OAuth2Client` fails to obtain an access token.
> Fix a possible deadlock when `OAuth2Client` is used with `RetryingClient`

- core/src/main/java/com/linecorp/armeria/client/Endpoint.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
- core/src/main/java/com/linecorp/armeria/internal/client/endpoint/RampingUpKeys.java
- core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategyTest.java
Motivation:
The motivation for this PR stems from #5688.
The current `WeightRampingUpStrategy` internally maintains the ramping up status of endpoints. However, it is possible that although an `EndpointGroup` has just been created certain endpoints must be considered already ramped up. For instance, in xDS we newly create an `EndpointGroup` every time a `ClusterSnapshot` is updated. However, even if a `ClusterSnapshot` has changed, we need to retain an endpoint's ramping up status.
To resolve this, I propose a timestamp based solution. Specifically, I believe an `Endpoint` can maintain a state `createdAtNanos` and `WeightRampingUpStrategy` can refer to this value to determine the ramp-up status. We can also allow users to specify their own timestamp via an attribute if they are …
> Refactor `WeightRampingUpStrategy` to be timestamp based

- core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java
- core/src/test/java/com/linecorp/armeria/server/cors/CorsServerErrorHandlerTest.java
Motivation:
This PR is follow-up of https://github.com/line/armeria/pull/5632#discussion_r1595038769 and #5670 that `ctx.findService()` should be used to find `CorsService` added with route decorators.
Modifications:
- Use `ctx.findService()` to find `CorsService` in the service chain of a request
Result:
CorsServerErrorHandler now correctly handles response exceptions even if `CorsService` is added as a route decorator.
(Not need to be mentioned in the release notes)
> Fix `CorsServerErrorHandler` to work with dynamic `CorsService`

- core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
Motivation:
The `maxClientHelloLength` was hardcoded to 4KiB in https://github.com/line/armeria/pull/4974. However, this value does not cover all cases, so we need to provide a way for users to change this value to suit their needs.
Modifications:
- Added `Flags.defaultMaxClientHelloLength()` which allows users to configure the value.
Result:
- You can now configure the maximum length of a TLS client hello message that a server allows by using the `-Dcom.linecorp.armeria.defaultMaxClientHelloLength=<integer>` JVM option.
- The default value of `defaultMaxClientHelloLength` is now 16KiB.
> Provide a way to configure the `maxClientHelloLength` that a server allows

- core/src/main/java/com/linecorp/armeria/server/DefaultServerErrorHandler.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/test/java/com/linecorp/armeria/server/ServerErrorHandlerTest.java
Motivation:
An event loop of the `Channel` of a request is used to subscribe to a returned `HttpResponse`.
https://github.com/line/armeria/blob/3112b50cb6d2bd0cd31bac17796c5e6a01cc347c/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L453-L457
The channel event loop is not a context-aware event loop, so `ServiceRequestContext` is not available in the thread local. As a result, request-scoped MDC won't work.
Modifications:
- Push `ServiceRequestContext` before calling `ServerErrorHandler.onServiceException()`
Result:
`ServiceRequestContext` is now correctly propagated to `ServerErrorHandler`.
> Fix to propagate `ServiceRequestContext` to `ServerErrorHandler`

- xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RampingUpTest.java
Motivation:
This PR handles the following flaky test
https://ge.armeria.dev/s/p7k6qi4mxuzu4/tests/task/:xds:shadedTest/details/com.linecorp.armeria.xds.client.endpoint.RampingUpTest/checkEndpointsAreRampedUp()
Following the change of https://github.com/line/armeria/pull/5693, now calling `EndpointGroup#selectNow` may return `null` if the `RampingUpEndpointWeightSelector#updateEndpoints` is not completed yet since updates are already scheduled on the event loop.
https://github.com/line/armeria/blob/8bad3305a8e1843c049537395368266215245df6/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java#L149
For this reason, although `XdsEndpointGroup` is in the correct state, `EndpointGroup#selectNow` may return `null`.
I propose that we just call `EndpointGroup#select` …
> Handle flaky `RampingUpTest` tests

- core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
- core/src/main/java/com/linecorp/armeria/internal/common/util/ReentrantShortLock.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelectorTest.java
Motivation:
Following the change of https://github.com/line/armeria/pull/5693, now calling `EndpointGroup#selectNow` may return `null` if the `RampingUpEndpointWeightSelector#updateEndpoints` is not completed yet since updates are always scheduled on the event loop.
https://github.com/line/armeria/blob/8bad3305a8e1843c049537395368266215245df6/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java#L149
In addition, most `EndpointGroup` implementations use `AbstractEndpointSelector`.
Whenever a change is made to the `EndpointGroup#endpoints`, [refreshEndpoints](https://github.com/line/armeria/blob/8bad3305a8e1843c049537395368266215245df6/core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java#L148) is called.
The expectation here …
> Using `WeightRampingUpStrategy` with `AbstractEndpointSelector` can fail to select initial endpoints

- junit4/src/main/java/com/linecorp/armeria/testing/junit4/server/ServerRule.java
- junit5/src/main/java/com/linecorp/armeria/internal/testing/ServerRuleDelegate.java
- junit5/src/main/java/com/linecorp/armeria/testing/junit5/server/ServerExtension.java
- junit5/src/test/java/com/linecorp/armeria/testing/junit5/server/ServerExtensionWithWebSocketClientTest.java
- sangria/sangria_2.13/src/test/scala/com/linecorp/armeria/server/sangria/ServerSuite.scala
- scala/scala_2.13/src/test/scala/com/linecorp/armeria/server/ServerSuite.scala
- scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ServerSuite.scala
Motivation:
Added `webSocketClient` which directly connects to `ServerExtension` 
Modifications:
- `ServerExtension`: Added `webSocketClient` method which users can easily use to retrieve a webSocketClient which connects to `ServerExtension` 
- `ServerRuleDelegate`: Added `webSocketClient` 
Result:
- Closes #<https://github.com/line/armeria/issues/5538>. (If this resolves the issue.)
> Add `webSocketClient` in `ServerExtension`

- core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorChildSubscriberTest.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
Motivation:
Subscriber methods must be called by the executor that is specified when subscribing to a `StreamMessage`. However, the methods of the duplicator's child stream subscriber are currently being called from the duplicator's executor, which is incorrect.
Modifications:
- Updated the implementation to ensure that the duplicator's child stream subscriber methods are called by the correct executor as specified during subscription.
Result:
- The duplicator's child stream subscriber methods are now called by the correct executor.
> Fix to call the duplicator's child stream subscriber methods by the correct executor

- core/src/test/java/com/linecorp/armeria/internal/client/dns/DefaultDnsResolverTest.java
Motivation:
Fix #5725
Modifications:
- resolve is using resolveAll when questions has more than 1 item. So change to  resolveAll and avoid creating ctx which schedules cancel before stopwatch.
Result:
- Closes #5725
> Fix flaky test in DefaultDnsResolverTest

- native-image-config/build.gradle.kts
Motivation:
`project.buildDir` has been deprecated in favor of `layout.buildDirectory` in Gradle.
Modifications:
- Replaced all `project.buildDir` usages
- Replaced `if-else` chain with `when`
Result:
Less deprecation warnings when importing Armeria into IntelliJ IDEA
> Fix deprecation warnings in native-image-config/build.gradle.kts

- core/src/main/java/com/linecorp/armeria/client/WebClient.java
- core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
- core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
- core/src/main/java/com/linecorp/armeria/internal/common/HeaderOverridingHttpRequest.java
- core/src/test/java/com/linecorp/armeria/client/WebClientExchangeTypeTest.java
- core/src/test/java/com/linecorp/armeria/common/AggregationOptionsTest.java
- grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
- oauth2/src/main/java/com/linecorp/armeria/internal/common/auth/oauth2/OAuth2Endpoint.java
Motivation:
The `RetryingClient` uses `ExchangeType` to decide whether to use `HttpRequestDuplicator`: https://github.com/line/armeria/blob/7474525b8cf25f02be6df7c38510a8fb6a88cb1f/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L245-L246 Thus, setting the proper `ExchangeType` is important.
`ExchangeType` is currently inferred from the `HttpRequest` implementation: https://github.com/line/armeria/blob/7474525b8cf25f02be6df7c38510a8fb6a88cb1f/core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java#L285-L288
However, `DefaultWebClient` wraps the request, which results in incorrect `ExchangeType` detection: https://github.com/line/armeria/blob/7474525b8cf25f02be6df7c38510a8fb6a88cb1f/core/src/main/java/com/linecorp/armeria/client/Defa …
> Fix `ExchangeType` detection for `HeaderOverridingHttpRequest`.

- examples/tutorials/grpc/src/main/java/example/armeria/server/blog/grpc/GrpcExceptionHandler.java
- grpc-kotlin/src/test/kotlin/com/linecorp/armeria/server/grpc/kotlin/CoroutineServerInterceptorTest.kt
- grpc/src/main/java/com/linecorp/armeria/common/grpc/DefaultGrpcExceptionHandlerFunction.java
- grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcExceptionHandlerFunction.java
- grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcExceptionHandlerFunction.java
- grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcExceptionHandlerFunctionBuilder.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
- grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframer.java
- grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/UnwrappingGrpcExceptionHandleFunction.java
- grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
- grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientBuilderTest.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientExceptionHandlerTest.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
- grpc/src/test/java/com/linecorp/armeria/common/grpc/DefaultGrpcExceptionHandlerFunctionTest.java
- grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcExceptionHandlerFunctionBuilderTest.java
- grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/TestServiceImpl.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/AsyncServerInterceptorTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcExceptionHandlerAnnotationOnlyTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcExceptionHandlerTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcStatusMappingTest.java
- it/grpc/kotlin/src/test/kotlin/com/linecorp/armeria/grpc/kotlin/TestServiceTest.kt
- it/grpc/reactor/src/test/java/com/linecorp/armeria/grpc/reactor/TestServiceTest.java
- it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/TestServiceTest.scala
Motivation:
When an exception is raised, `GrpcService` creates a new `Status` from `Status.getCause()` via `GrpcExceptionHandlerFunction`. This can result in sending an incorrect status in certain situations:
- If the original exception is a `StatusRuntimeException` containing the `Status` that the user wants to send.
- The original exception has already been converted into a `Status` via `Status.fromThrowable()`: https://github.com/grpc/grpc-java/blob/5770114d08dcd352f2288ef52d17e1833530323c/stub/src/main/java/io/grpc/stub/ServerCalls.java#L389
- This converted `Status` is ignored and a new, potentially incorrect `Status` is created by `GrpcExceptionHandlerFunction` and sent.
Modifications:
- Added a `Status` parameter to the `GrpcExceptionHandlerFunction.apply()` method.
- Updated the …
> Add `Status` parameter to `GrpcExceptionHandlerFunction.apply()` method.

- core/src/main/java/com/linecorp/armeria/server/docs/JsonSchemaGenerator.java
Motivation:
- The `StructInfo` `alias` has the same value as the `name` causing a duplicate key exception when building  `typeSignatureToStructMappingBuilder`. 
- Occurred when setting up a HTTP service which consumes protobuf messages
Modifications:
- Checks that the `struct` and `alias` don't have the same name to avoid duplicate key exception (alias is created here https://github.com/line/armeria/blob/main/protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufDescriptiveTypeInfoProvider.java#L106)
Result:
- Improves the `JsonSchemaGenerator.java` for the documentation service by allowing resources to have the same alias and name as is the default behavior of https://github.com/line/armeria/blob/main/protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufDescri …
> Fix JsonSchemaGenerator to handle StructInfo with same alias and name

- .github/workflows/actions_build.yml
- core/build.gradle
- core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
- gradle/scripts/README.md
- gradle/scripts/lib/java-shade.gradle
Motivation:
`HttpHeaderNamesTest` failed locally because we omitted three headers when upgrading the Guava version to 33.2.0.
We can't detect the problem from our CI builds since all fields of Guava `HttpHeaders` are removed by the `trimShadedJar` task on which the `build` task depends. The fields are actually used for testing.
Modifications:
- Keep `HttpHeaders` and `MediaType` of Guava from trimming to avoid unexpected test results.
- Add `-PpreferShadedTests=<boolean>` option to run unshaded tests along with shaded tests
- This option is disabled by default to avoid running the same tests twice.
- Add missing headers to `HttpHeaderNames`
Result:
New headers from Guava have been added to `HttpHeaderNames`.
> Synchronize HttpHeaderNames with Guava

- core/src/main/java/com/linecorp/armeria/server/AbstractContextPathAnnotatedServiceConfigSetters.java
- core/src/main/java/com/linecorp/armeria/server/AbstractContextPathServiceBindingBuilder.java
- core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
- core/src/test/java/com/linecorp/armeria/server/contextpath/test/ServiceBuilderSelfTypeTest.java
Motivation:
While refactoring Central Dogma, I found that some methods of service binding builders return internal classes or super types.
Modifications:
- Pass `SELF` type to super classes to return the class itself
Result:
Service binding builder methods now correctly return the self-types.
> Fix `*ServiceBindingBuilder` to return the correct self type

- core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
- core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
- core/src/main/java/com/linecorp/armeria/internal/common/util/ReentrantShortLock.java
Motivation:
https://github.com/line/armeria/issues/5749
While re-investigating this issue, I found that the probably cause is the changes introduced by https://github.com/line/armeria/pull/5693
Previously, when `updateEndpoints` is called the `endpointSelector` was initialized from the same thread 
https://github.com/line/armeria/blob/da7f76a7eebf9b03a51ff68a9245269eee4a5a6d/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java#L147-L150
However after the PR above,  `updateEndpoints` doesn't update the `endpointSelector` immediately and instead schedules an update task
https://github.com/line/armeria/blob/191fb7db981d1d47de8ce50be0b0f6d5d9dfa8ee/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java#L150
For this reason, even if …
> `WeightRampingUpStrategy` uses locks to avoid occasional selection failure for `XdsEndpointGroup`

- core/src/main/java/com/linecorp/armeria/server/ServerMetrics.java
- core/src/test/java/com/linecorp/armeria/server/ServerMetricsTest.java
Motivation:
`MetricCollectingService` uses `.active.requests` to track the number of the current requests. If `armeria.server` is used as the prefix of the meter name, the name conflicts with "armeria.server.active.requests" in `ServerMetrics`.
`ServerMetrics.activeRequests()` counts all requests including `TransientService` which is excluded by `MetricCollectingService` with no `TransientServiceOption`. So, semantically, it would be better to use `.all` to the meter name to indicate that it counts all requests.
Modifications:
- Rename "armeria.server.active.requests" in `ServerMetrics` to "armeria.server.all.requests{state=active}".
- Rename "armeria.server.pending.requests" in `ServerMetrics` to "armeria.server.all.requests{state=pending}".
Result:
The meter names in `ServerMetrics` no …
> Change conflicting meter names  in `ServerMetrics`

- core/src/main/java/com/linecorp/armeria/server/file/FileService.java
- core/src/main/java/com/linecorp/armeria/server/file/FileServiceBuilder.java
- core/src/main/java/com/linecorp/armeria/server/file/FileServiceConfig.java
- core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
Motivation:
I prefer clean URL patterns without a trailing slash so `/app/projects` is preferred over `/app/projects/`.  If I built `/app/projects` with a Javascript framework, `/app/projects/index.html` or `/app/projects.html` may be exported by the framework which is a common feature.
In `FileService`, `/app/projects/index.html` can be served by `/app/projects/` path, but cannot be found by `/app/projects`. A trailing slash `/` can be converted into `/index.html` or an auto index page. As some fallback logics are already implemented, I didn't want to add a new fallback option for a trailing slash.
Alternatively, I propose an option that appends an extension if there is no file for the request path. For example, a request sent to `/app/projects` also finds `/app/projects.[ext]` as a …
> Provide a way to set fallback file extensions for `FileService`

- core/src/test/java/com/linecorp/armeria/server/ServerMetricsTest.java
Motivation:
- https://ge.armeria.dev/s/4nbxggtjahu5w/tests/task/:core:shadedTest/details/com.linecorp.armeria.server.ServerMetricsTest/checkWhenOk(SessionProtocol%2C%20long%2C%20long)%5B1%5D?top-execution=1
- https://ge.armeria.dev/s/ymlrbcecdkwz4/tests/task/:core:shadedTest/details/com.linecorp.armeria.server.ServerMetricsTest/checkWhenRequestTimeout(SessionProtocol%2C%20long%2C%20long)%5B1%5D?top-execution=1
The above flaky tests are failing relatively often: https://ge.armeria.dev/scans/tests?search.timeZoneId=Asia%2FSeoul&tests.container=com.linecorp.armeria.server.ServerMetricsTest#
Cancelling the request doesn't guarantee that the server-side request is closed immediately.
Modifications:
- Added an `await` condition which waits until the active request in server-side has indeed been …
> Fix flaky `ServerMetrics` tests

- core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java
- core/src/test/java/com/linecorp/armeria/server/ProtocolViolationHandlingTest.java
Motivation:
`CorsServerErrorHandler` was added as the first error handler by #5632 `CorsServerErrorHandler` does not handle an exception but delegates it to the default one or user-defined handler and injects CORS headers.
`CorsServerErrorHandler` overrode `onServiceException` to delegate but omitted to override `onProtocolViolation`. As a result, a user-defined `onProtocolViolation` wasn't invoked.
Modifications:
- Override `onProtocolViolation()` and delegate to `serverErrorHandler`
Result:
A protocol violation is now correctly handled by `ServerErrorHandler.onProtocolViolation()`
> Fix a bug where a protocol violation is not handled by `ServerErrorHandler`

- graphql/src/main/java/com/linecorp/armeria/server/graphql/DefaultGraphqlService.java
- graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlErrorHandler.java
- graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlErrorHandlerTest.java
- graphql/src/test/resources/testing/graphql/test.graphqls
Motivation:
If `GraphQL.execute(input)` returns a `CompletableFuture` completing exceptionally, `NullPointException` is raised while handling `ExecutionResult`.
```java
java.lang.NullPointerException: Cannot invoke "graphql.ExecutionResult.getData()" because "executionResult" is null
at com.linecorp.armeria.server.graphql.DefaultGraphqlService.lambda$execute$1(DefaultGraphqlService.java:117)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
```
Modifications:
- Check if `cause != null` before accessing `executionResult` in the callback of `executeGraphql(ctx, input)`.
Result:
- `NullPointerException` is no longer raised when `GraphqlService` handles …
> Handle a null ExecutionResult in `GraphqlService`

- core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
- core/src/main/java/com/linecorp/armeria/client/HAProxyHandler.java
- core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
Motivation:
While working on https://github.com/line/armeria/pull/5793, I found that there were unnecessary `ProxyConnectException` related handling in the request handler. This is most likely due to the fact that `HaProxyHandler` works differently from the other proxy handlers in that the session is completed, and then a connection event is published.
This was probably when I was less familiar with netty. I propose that the `HaProxyHandler` complete the session similarly to the other handlers. A connection attempt is made first, and then the `sessionPromise` is succeeded or failed accordingly.
Modifications:
- `HaProxyHandler` doesn't succeed the `sessionPromise` immediately, but waits for the result of the `connect` future.
- Remove `ProxyConnectException` related logic in all places …
> Refactor `HaProxy` exception handling

- core/src/main/java/com/linecorp/armeria/client/Endpoint.java
- core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
Motivation:
It seems inconsistent that `Endpoint#withAttr` merges the attribute to the existing attributes, whereas `Endpoint#withAttrs` simply replaces the previous attributes.
I propose that we modify the behavior of `Endpoint#withAttrs` to be aligned with `Endpoint#withAttr`. Additionally, in order to support the previous behavior, I propose a new API `Endpoint#replaceAttrs` be added.
I've confirmed that there are no uses of this API at least internally.
ref: https://github.com/line/armeria/pull/5785#discussion_r1654225883
Modifications:
- Modified the behavior of `Endpoint#withAttrs` to merge attributes
- Added a new API `Endpoint#replaceAttrs` to support the previous behavior
Result:
- More consistent APIs
- Preparation for https://github.com/line/armeria/pull/5785
> Modify behavior of `Endpoint#withAttrs` to merge attributes

- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/test/proto/testing/grpc/transcoding.proto
Motivation:
- #5828 
- When an rpc method has transcoding options, the server won't start up.
Modifications:
- Warn and skip the method instead of preventing server startup.
Result:
- Closes #5828
- Server can start if a gRPC non-unary rpc is configured to have transcoding options.
> fix: logger.warn instead of ISE on transcoding options for non-unary gRPC

- resteasy/src/main/java/com/linecorp/armeria/client/resteasy/ArmeriaJaxrsClientEngine.java
- resteasy/src/test/java/com/linecorp/armeria/server/resteasy/CalculatorServiceClientServerTest.java
Motivation:
A `ClientFactory` leak was detected in `CalculatorServiceClientServerTest`
```java
10:19:16.263 [Test worker] ERROR io.netty.util.ResourceLeakDetector - LEAK: ClientFactory.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
com.linecorp.armeria.client.DefaultClientFactory.<init>(DefaultClientFactory.java:101)
com.linecorp.armeria.client.ClientFactoryBuilder.build(ClientFactoryBuilder.java:998)
com.linecorp.armeria.client.resteasy.ArmeriaResteasyClientBuilder.buildWebClient(ArmeriaResteasyClientBuilder.java:193)
com.linecorp.armeria.client.resteasy.ArmeriaResteasyClientBuilder.build(ArmeriaResteasyClientBuilder.java:210) …
```
> Fix `ClientFactory` leaks in `ResteasyClient`

- .github/workflows/actions_build.yml
We create branches for patch versions that need to be verified by CI.
Reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
> '**' : Matches all branch and tag names. This is the default behavior when you don't use a branches or tags filter.
> Make CI run all branches on push

- site/src/pages/index.tsx
Motivation:
LY corporation's web pages are inaccessible from EU, where our users are.
Modifications:
- Replaced the URL of LY corporation with its Wikipedia page.
Result:
- One less broken link
> Link the Wikipedia page instead of the LY corporation homepage

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedElementNameUtil.java
- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
Motivation:
We must not convert the header name specified in `@Header` when creating an annotated service.
This is a regression introduced by #5547, affecting 1.29.0 through 1.29.3.
Modifications:
- Do not convert the header name specified in `@Header`.
Result:
- An annotated service that has a `@Header` with the specified name now works correctly.
> Do not convert `@Header` name when the name is specified

- docs-client/build.gradle
- site/build.gradle
Motivation:
Our CI has occasionally been failing to download Node.js 16.19.1 for the past few days. https://github.com/line/armeria/actions/runs/10200377198/job/28219691450?pr=5580#step:5:26
```
Could not determine the dependencies of task ':docs-client:nodeSetup'.
> Failed to query the value of task ':docs-client:nodeSetup' property 'nodeArchiveFile'.
> Could not resolve all files for configuration ':docs-client:detachedConfiguration1'.
> Could not download node-16.19.1-linux-x64.tar.gz (org.nodejs:node:16.19.1)
> Could not get resource 'https://nodejs.org/dist/v16.19.1/node-v16.19.1-linux-x64.tar.gz'.
> Read timed out
```
We encountered a similar problem in Central Dogma CI. Some details are somewhat different but the download failure also happened in Central Dogma. The problem was …
> Upgrade Node.js to 22.3.0

- site/src/components/emoji.tsx
Because maxcdn.com has shut down.
Closes #5850
> Use cdn.jsdelivr.net for twemoji

- docs-client/src/containers/App/index.tsx
Motivation:
- Some service/struct names can be too long and cause app to look weird.
https://github.com/line/armeria/issues/5091#issuecomment-2248330838
Modifications:
- Make texts in sidebar wrap.
- Limit sidebar to occupy at most 40% of the window width.
Result:
Wrapping example:
> fix: doc service webpage sidebar should limit to 40% window width

- core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
- core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
Motivation:
RFC 3986 doesn't prohibit control characters in a request target as long as it's percent-encoded. However, `DefaultRequestTarget` doesn't allow any control characters except `\r` and `\n` in a query string.
This is to reject potentially harmful paths such as `/foo\nbar` but it can be overly strict to some users.
Modifications:
- `DefaultRequestTarget` now allows the following control characters additionally:
- TAB (0x09)
- FS (0x1C)
- GS (0x1D)
- RS (0x1E)
- US (0x1F)
- However, other control characters will remain prohibited until there's a good reason to allow them.
- Simplified `appendOneByte()` by introducing additional `BitSet`s of percent-encodable characters.
Result:
- A user can send and receive an HTTP request whose `:path` contains the following characters now:
- TAB …
> Allow some control characters in a request target

- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageInputStream.java
- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageInputStreamTest.java
Motivation:
The `InputStream` returned from `StreamMessage.toInputStream()` should raise an exception if the original `StreamMessage` is closed with an exception. Currently, the `InputStream` only returns `-1` in such cases, which does not inform the caller of the underlying issue.
Modification:
- Updated the implementation to propagate the exception to the `InputStream` if the original `StreamMessage` is closed with an exception.
Result:
- The `InputStream` now correctly raises an exception if the original `StreamMessage` is closed with an exception.
> Propagate exception from `StreamMessage` to `InputStream`.

- core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
- core/src/main/java/com/linecorp/armeria/internal/common/SchemeAndAuthority.java
- core/src/main/java/com/linecorp/armeria/internal/common/util/BitSetUtil.java
- core/src/test/java/com/linecorp/armeria/client/UnderscoredAuthorityTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/SchemeAndAuthorityTest.java
- core/src/test/java/com/linecorp/armeria/server/ServiceFinderTest.java
Motivation:
The authority part in a URI was validated by
`URI.parseServerAuthority()` which only allows alphanumeric characters, `.` and `-`.
https://github.com/openjdk/jdk/blob/dc35f3e8a84c8f622a4cabb8aee0f96de2e2ea30/src/java.base/share/classes/java/net/URI.java#L3513-L3515
As a result, if underscore (`_`) is set in an authority, `URISyntaxException` is raised. We think the rule is too strict because a request can also be sent to an instance when CSLB is used. `_` is a valid character in a DNS record. Users may want to send a request to a host whose name is `beta_api.cloud.instance-123.somewhere.com`.
Related: #5814
Modifications:
- Remove the usage of `URI.parseServerAuthority()` in `SchemeAndAuthority`
- Parse a hostname and a port from a raw authority.
Result:
- Validation is relaxed …
> Loosen the validation rule for URI authority

- core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageCollectingTest.java
Motivation:
`upstream.cancel()` is called after `onError(ex)`
https://github.com/line/armeria/blob/6a01398173b3abaea8fd7f613193ea7ba6376e88/core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java#L225-L228 So the test `data` may not be released when `filtered.collect().join()` completes exceptionally.
Modifications:
- Wrap the assertion with `await()`
Result:
Fix the flaky test
> Fix flaky `StreamMessageCollectingTest.filteredStreamMessage_exception()`

- core/src/test/java/com/linecorp/armeria/client/ContextCancellationTest.java
Motivation:
Let me just remove the validation like @minwoox suggested
Modifications:
- Removed the validation on request context.
Result:
- https://github.com/line/armeria/issues/5868
> Fix flaky test `ContextCancellationTest`

- core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
- core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
- core/src/main/java/com/linecorp/armeria/internal/common/DefaultCancellationScheduler.java
- core/src/main/java/com/linecorp/armeria/internal/common/NoopCancellationScheduler.java
- core/src/test/java/com/linecorp/armeria/client/retry/RetryTimeoutCancellationTest.java
Motivation:
Originally, when a request is derived, the parent's timeout scheduler is not canceled. This was not a problem until the `ResponseTimeoutMode.FROM_START` feature was added because the timeout did not start at this point. 
When `ResponseTimeoutMode.FROM_START` is set, a timeout task is scheduled before it is derived. So it needs to be canceled. Otherwise, the uncanceled scheduler task may cause a leak because referenced objects are not GC'd until the task is completed.
Modifications:
- Cancel the timeout scheduler of the parent request when it is derived.
Result:
Fixed a bug where timeout tasks leak when using `ResponseTimeoutMode.FROM_START` with `RetryingClient`.
> Fix a bug where the parent's timeout is not cancelled in `RetryingClient`

- core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
Motivation:
#5769 
Modifications:
- Added tearDown method with `@AfterEach` in order to reset each count variables used in tests
When executing this test in my local env, this test succeeded and I wasn't sure why this test failure was caused.
But, after adding this tearDown method, we will be able to avoid inappropriate variables staying  in cnt variables.
Result:
- Closes #5769 
- `Test failure: com.linecorp.armeria.server.ServerBuilderTest.contextHook()` will be resolved.
> Test failure: com.linecorp.armeria.server.ServerBuilderTest.contextHook()

- README.md
This PR uses markdown rather HTML in the README file.
> chore: use markdown rather than HTML in README

- core/src/main/java/com/linecorp/armeria/server/auth/OAuth2TokenExtractor.java
Motivation:
Invalid authorization is a client error so there isn't much a server maintainer can do. It seems better to use `DEBUG` to detect problems during development. `WARN` could be noisy because it may be related to a monitoring system.
Modifications:
- Use `DEBUG` to log an invalid authorization header.
Result:
An invalid authorization header is now logged at `DEBUG` by the OAuth2 token extractor.
> Use `DEBUG` to log `invalid authorization header` in `OAuth2TokenExtractor`

- core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java
Motivation:
Docs were confusing when using the framework. Needed to dig into the code to find the default multipler. So let's add it in the documentation
> Update documentation for default value in Backoff.exponential where multiplier is not specified

- core/src/test/java/com/linecorp/armeria/server/InitiateConnectionShutdownTest.java
Motivation: 
- #5743
- #5333
- #3982
I'm not sure this change could resolve the flakiness but it would be worthwhile to explicitly wait for a connection to close before checking invocations.
Modifications:
- Wait for `clientChannel` to be closed.
Result:
- Closes #5743
- Closes #5333
- Closes #3982
I will reopen the issues if the flaky is reproduced.
> Fix flaky `InitiateConnectionShutdownTest`

- core/src/main/java/com/linecorp/armeria/common/ResponseEntity.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceResponseConverterTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/ResponseEntityUtilTest.java
- rxjava3/src/test/java/com/linecorp/armeria/server/rxjava3/ObservableResponseConverterFunctionTest.java
Motivation:
This PR adds more static constructors to `ResponseEntity` to match those available in the deprecated `HttpResult`.
Modifications:
- Add static constructors for `HttpStatus`
- Replace `Void` return type with `<T>` (breaking change)
- Add missing tests to `rxjava3` module
Result:
- `ResponseEntity` can now be used the same way that `HttpResult` was used.
> Add missing static constructors to `ResponseEntity`

- spring/boot2-webflux-autoconfigure/build.gradle
- spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/AbstractServerHttpResponseVersionSpecific.java
- spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/AbstractServerHttpResponse.java
- spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/AbstractServerHttpResponseVersionSpecific.java
- spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpHandlerAdapter.java
- spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
- spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ObservationTest.java
Motivation:
It seems like Armeria's spring integration response `ServerHttpResponse` is not always set correctly.
In detail, it seems like we can confirm that `getStatusCode` returns `UNKNOWN` unless `setStatusCode` is called explicitly.
1. When a successful response is returned, we refer to the response headers used. This is similar to the upstream implementation which falls back to the response which is actually returned.
https://github.com/spring-projects/spring-framework/blob/d2ea5b444812b4c55e00fecb7b6451073677061d/spring-web/src/main/java/org/springframework/http/server/reactive/ReactorServerHttpResponse.java#L72-L76
2. When `Armeria` returns a response instead of `Spring`, the response is never committed. Now, the `doOnCancel` is listened to and the response is committed …
> `ServerHttpResponse` sets the response `statusCode` correctly

- core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/jni-config.json
- core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/reflect-config.json
- core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/resource-config.json
- native-image-config/build.gradle.kts
- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftMetadataAccess.java
Motivation:
GraalVM native image tool fails to generate a working binary since
Armeria 1.30.0, due to its outdated metadata. Special thanks to @Dogacel
who reported this issue.
Modifications:
- Updated the GraalVM native image metadata.
- Removed the redundent `../../` from the resource lookup in `ThriftMetadatAccess`.
Result:
Armeria is again compatible with GraalVM native image tool.
> Update GraalVM native image metadata

- grpc/src/main/java/com/linecorp/armeria/server/grpc/ServerCallUtil.java
- grpc/src/test/java/com/linecorp/armeria/server/grpc/DeferredListenerTest.java
Motivation:
There was a bug in `AsyncServerInterceptor` where a `ForwardingServerCall` was not unwrapped properly via reflection. Because of that, OpenTelemetry's `TracingServerCall` that wraps the existing `ServerCall` using `ForwardingServerCall` was rejected by the following condition.
https://github.com/line/armeria/blob/6dd5cd18dcdc32431316f272128287b2037249d3/grpc/src/main/java/com/linecorp/armeria/server/grpc/DeferredListener.java#L51-L52
Modifications:
- Use the correct reflection API to unsafely access `ForwardingServerCall.delegate()`.
Result:
- Fix a bug where `AsyncServerInterceptor` is incompatible with the OpenTelemetry gRPC agent.
- Closes #5937
> Fixed `AsyncServerInterceptor` to be compatible with OpenTelmetry

- core/src/main/java/com/linecorp/armeria/common/StringMultimap.java
Motivation:
In the addObject and addObjectAndNotify methods, the fromObject(value) function is being called redundantly. This results in unnecessary computations, which could affect performance and reduce code readability. By removing the redundant calls to fromObject(value), we can improve the efficiency and clarity of the code.
Modifications:
- Modified the addObject method to pass the original value directly to the addObjectAndNotify method without calling fromObject(value).
- Updated the addObjectAndNotify method to perform the fromObject(value) call once, ensuring it is not called multiple times for the same value.
Result:
- Improved code readability and maintainability.
- Eliminated the redundant fromObject(value) calls, enhancing performance.
> Avoid redundant fromObject(value) calls in addObject methods

- core/src/main/java/com/linecorp/armeria/internal/server/CorsHeaderUtil.java
- core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java
- core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
- core/src/test/java/com/linecorp/armeria/server/cors/CorsServerErrorHandlerTest.java
- spring/boot3-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationTest.java
Motivation:
`ServerErrorHandler.renderStatus()` is used in `DefaultServerErrorHandler` and may not be called in a custom `ServerErrorHandler`. Attempting to inject CORS headers via `CorsServerErrorHandler.renderStatus()` may not work.
Modifications:
- Use `ctx.mutateAdditionalResponseHeaders()` to set CORS headers instead of mutating the response headers.
- Store whether a CORS is set by `CorsService` to ctx.attr().
- The value is used in `CorsServerErrorHandler` to set if missing
Result:
- CORS headers for failed requests are now correctly set even when a custom `ServerErrorHandler` is configured.
- Fixes #5493
> Fix a bug where CORS headers are not injected when a `ServerErrorHandler` is set

- core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
- core/src/main/java/com/linecorp/armeria/common/RequestTarget.java
- core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
- core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
- core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
- core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
- core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
- core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
- core/src/test/java/com/linecorp/armeria/server/RawPathTest.java
Motivation:
It may be useful if we have access to the original request path unmodified. For example we have use cases where the decoding rules are different from the ones at `decodedPath`.
Modifications:
- Added `rawPath` method in `RequestTarget` to store the rawPath.
- The rawPath is from the unmodified ':path' header at the server side; the client side target, it's always null.
- Added `rawPath` method in `ServiceRequestContext`, it's always non null for server-side targets.
Result:
- Closes #5931.
- Users will get access to the raw request path for a request.
> Introduce rawPath in RequestTarget and ServiceRequestContext

- nacos/src/test/java/com/linecorp/armeria/internal/nacos/NacosClientBuilderTest.java
- nacos/src/test/java/com/linecorp/armeria/internal/nacos/NacosTestBase.java
Motivation:
For some reason, it seems like the main CI doesn't run docker tests.
In any case, I found that Nacos tests are failing due to incorrect server uri settings.
Modifications:
- Fixed the test URI to prepend a `/nacos` uri
Result:
- Nacos tests pass now
> Fix failing nacos tests

- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseSubscriber.java
- core/src/main/java/com/linecorp/armeria/server/AccessLogWriterUtil.java
- core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- core/src/main/java/com/linecorp/armeria/server/logging/AccessLogWriter.java
- core/src/test/java/com/linecorp/armeria/server/logging/AccessLoggerIntegrationTest.java
Motivation:
As described in https://github.com/line/armeria/issues/5984, there are instances of unnecessary request context push/pop operations related to access logging when the access log writer is disabled. These operations are redundant since the logging path does not need to be triggered when the writer is disabled. Optimizing this behavior reduces unnecessary overhead in such cases.
Modifications:
- Added `AccessLogWriterUtil#maybeWriteAccessLog`
- Writes access log only when `TransientServiceOption#WITH_ACCESS_LOGGING` is enabled and the access log writer is not disabled.
- Updated `AbstractHttpResponseHandler` and `HttpServerHandler`
Result:
- Closes https://github.com/line/armeria/issues/5984.
- Removes unnecessary context push/pop operations for access logging when the access …
> Introduce AccessLogWriterUtil and Remove Unnecessary RequestContext Push/Pop

- core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
- core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
- core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
Motivation:
It has been reported that `log.whenComplete` is not completing in some cases in #5981.
The cause seems to be a race condition between `DefaultRequestLog#endRequest` and `DefaultRequestLog#requestContent`. Completion of `log.whenComplete` is important because
1) it is semantically bound to an HTTP request 2) users (including us) have clean up logic using `log.whenComplete`.
I propose that simply `endRequest` only sets `name` if content is not deferred, and `requestContent` sets `name` if content is deferred. The logic is easier to reason about, and there are minimal performance implications since a lock is held anyways.
Modifications:
- `#endRequest` sets `name` if `requestContent` isn't deferred
- `#requestContent` sets name if `requestContent` is deferred
Result:
- Closes …
> Fix race condition where `log.whenComplete` may not complete

- gradle.properties
- settings.gradle
Motivation:
```
Caused by: java.lang.IllegalStateException: Can't add different class with same name: com/linecorp/armeria/common/logback/LoggingEventWrapper
at org.jacoco.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:106)
at org.jacoco.core.analysis.Analyzer$1.visitEnd(Analyzer.java:100)
at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:395)
at org.jacoco.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:100)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:749)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:117)
at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:133)
... 152 more
```
Modifications:
- Set `no_aggregation` flag to …
> Fix Jacoco failure

- build.gradle
- gradle/scripts/.gitrepo
- gradle/scripts/lib/common-dependencies.gradle
- gradle/scripts/lib/java-shade.gradle
- grpc/build.gradle
Motivation:
With the recent release of 1.31.0, we received a report that protobuf 4 has been included as an api dependency.
This is probably a mistake since 1) the community isn't ready for protobuf 4 2) it's usually safer to follow the protobuf version used by `grpc-java`.
The `api` configuration is a consumable configuration, which means it is difficult to detect these kind of issues directly.
However, by checking the runtime dependencies for tests we can infer whether a version is inadvertently bumped.
In order to detect such mishaps, I also propose that a `failOnVersionConflict` variant is added.
Because naively introducing `failOnVersionConflict` introduces many conflicts, I've added a variant which checks for specified dependencies only. (inspired by …
> Exclude protobuf 4.x from `armeria-grpc` module

- kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroup.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMockServerTest.java
Motivation:
When a Kubernetes service is updated, a new Pod watcher is created and receives events. The old cache should have been cleared at this point, but it was not removed, so stale endpoints were exposed.
Modifications:
- Clear `podToNode` map when a new Pod watcher is created
Result:
Fixed a bug where stale endpoints remained when a Kubernetes service was updated.
> Fix a bug where stale endpoints in `KubernetesEndpointGroup` aren't updated

- core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java
- core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckUpdateHandler.java
Motivation:
When implementing a custom `HealthCheckUpdateHandler`, I just wanted to add validation in front of the default implementation. However, it wasn't possible because the default implementation has package-private visibility.
Modifications:
- Expose the default `HealthCheckUpdateHandler` via `HealthCheckUpdateHandler.of()`
Result:
You can now use the default `HealthCheckUpdateHandler` via `HealthCheckUpdateHandler.of()`
> Expose the default `HealthCheckUpdateHandler`

- .github/workflows/actions_build.yml
Motivation:
macos-12 is no longer supported in GitHub Actions. 
- https://github.com/line/armeria/actions/runs/12177357989?pr=5941
- https://github.com/actions/runner-images/issues/10721
Modifications:
- Use macos-latest instead.
Result:
Revive macOS CI
> Use `macos-latest` for CI builds

- core/src/main/java/com/linecorp/armeria/client/AbstractHttpResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/client/HttpResponseWrapper.java
- core/src/main/java/com/linecorp/armeria/client/WebSocketHttp1ClientChannelHandler.java
- core/src/main/java/com/linecorp/armeria/client/WebSocketHttp1ResponseWrapper.java
- core/src/main/java/com/linecorp/armeria/internal/client/ClientRequestContextExtension.java
- core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
- core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
- core/src/main/java/com/linecorp/armeria/internal/common/DefaultCancellationScheduler.java
- core/src/main/java/com/linecorp/armeria/internal/common/NoopCancellationScheduler.java
- core/src/test/java/com/linecorp/armeria/client/retry/ResponseTimeoutFromStartTest.java
- grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
Motivation:
A bug was reported that `ResponseTimeoutMode.FROM_START` does not work correctly when used with a `RetryingClient`. The cause was because how the `responseTimeout` is calculated for `RetryingClient`.
`RetryingClient` bounds `responseTimeout` by computing the `responseTimeout` on each iteration from its internal `State`.
https://github.com/line/armeria/blob/fa76e99fa6132545df3a8d05eeb81c5681ec8953/core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java#L188
If the `CancellationScheduler` has not been started yet, the set timeout is returned as-is via `CancellationScheduler#timeoutNanos` and is set at for the derived ctx.
https://github.com/line/armeria/blob/fa76e99fa6132545df3a8d05eeb81c5681ec8953/core/src/main/java/com/linecorp/armeria/internal/client/D …
> `ResponseTimeoutMode.FROM_START` works correctly with `RetryingClient`

- kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpClientFactory.java
- kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/ArmeriaWebSocketClient.java
- kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroup.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupFaultToleranceTest.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMockServerTest.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/TestKubernetesClientBuilderCustomizer.java
Motivation:
A watcher in `KubernetesEndpointGroup` automatically reconnects when it fails to connect to the remote peer. However, it does not reconnect when a `WatcherException` is raised.
```
io.fabric8.kubernetes.client.WatcherException: too old resource version: 573375490 (573377297)
at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onStatus(AbstractWatchManager.java:401)
at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:369)
at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:52)
at com.linecorp.armeria.client.kubernetes.ArmeriaWebSocket.onNext(ArmeriaWebSocket.java:106)
at com.linecorp.armeria.client.kubernetes.ArmeriaWebSocket.onNext(ArmeriaWebSocket.java:37) …
```
> Automatically reconnect Kubernetes watcher when closed exceptionally

- core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
- core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListener.java
- core/src/main/java/com/linecorp/armeria/client/ConnectionPoolMetrics.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
- core/src/test/java/com/linecorp/armeria/client/ConnectionPoolCollectingMetricTest.java
- core/src/test/java/com/linecorp/armeria/client/ConnectionPoolMetricsTest.java
- core/src/test/java/com/linecorp/armeria/client/Http1ResponseDecoderTest.java
Motivation:
We observed that threads were blocked when multiple connections were closed simultaneously and the endpoint had a small number of event loops.
https://github.com/line/armeria/blob/fa76e99fa6132545df3a8d05eeb81c5681ec8953/core/src/main/java/com/linecorp/armeria/client/ConnectionPoolMetrics.java#L79-L85
We have no exact evidence, but I guess Micrometer's `remove()` operation may take a long time. The other logic is a simple HashMap operation that does not block for a long time.
Modifications:
- Add a dedicated GC thread to remove inactive meters whose active connections are 0.
- A jitter is added to prevent GC from executing simultaneously.
- Unsed meters are removed every hour + jitter.
- `ConnectionPoolListener` now implements `SafeCloseable` so users should close it when it …
> Periodically remove inactive connection pool metrics

- docs-client/build.gradle
- site/build.gradle
Motivation:
I observed that `:docs-client:npmInstall` failed frequently. https://github.com/line/armeria/actions/runs/12268833874/job/34231348528?pr=5941#step:9:1028
I don't know the root cause, but it would be worth upgrading to the latest version.
https://nodejs.org/en/about/previous-releases#looking-for-latest-release-of-a-version-branch
Modifications:
- Node.js 22.3.0 -> 22.10.0
- NPM 10.8.1 -> 10.9.0
Result:
Fix the failure of `npm install`
> Bump Node.js version

- core/src/main/java/com/linecorp/armeria/client/Endpoint.java
- core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
- core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
- core/src/test/java/com/linecorp/armeria/client/TrailingDotSniTest.java
Motivation:
A trailing dot specified in a hostname can be used to make DNS queries to avoid using search domains. However, the trailing dot should be removed for SNI.
https://datatracker.ietf.org/doc/html/rfc6066#section-3
> The hostname is represented as a byte string using ASCII encoding
> without a trailing dot.
Modifications:
- Add `Endpoint.withTrailingDot()` to remove a trailing dot if present. 
- Use an `Endpoint` without a trailing dot to create a remote address which is used for SNI.
Result:
- Fixed a bug where a trailing dot was included in the hostname used by SNI.
- Closes #6044
> Fix a bug where a tailing dot is not stripped for SNI

- core/build.gradle
- core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
- core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
- core/src/main/java/com/linecorp/armeria/common/CommonPools.java
- core/src/main/java/com/linecorp/armeria/common/CoreBlockHoundIntegration.java
- core/src/main/java/com/linecorp/armeria/common/NonBlocking.java
- core/src/main/java/com/linecorp/armeria/common/ReactorNonBlockingUtil.java
- core/src/main/java/com/linecorp/armeria/common/util/EventLoopCheckingFuture.java
- core/src/main/java/com/linecorp/armeria/internal/common/util/EventLoopThread.java
- reactor3/src/test/java/com/linecorp/armeria/common/reactor3/EventLoopNonBlockingTest.java
Motivation:
The `reactor.core.scheduler.NonBlocking` interface was introduced to `armeria-core` in #1665 to make `Schedulers.isInNonBlockingThread()` return `true` for an Armeria `EventLoop`. However, a conflict arises when building Java modules because the `NonBlocking` interface clashes with Reactor's own definition.
Modifications:
- Moved `NonBlocking` to `com.linecorp.armeria.common` to resolve the module conflict while retaining its utility for identifying non-blocking threads.
- Updated to call `Schedulers.registerNonBlockingThreadPredicate` if Reactor is available in the classpath.
- Adjusted `CoreBlockHoundIntegration` to update the non-blocking thread predicate.
Result:
- Resolved the Java module conflict with the `NonBlocking` interface.
> Fix Conflict for `NonBlocking` Interface in Reactor Integration

- core/src/main/java/com/linecorp/armeria/common/ContentTooLargeException.java
- core/src/main/java/com/linecorp/armeria/common/ContentTooLargeExceptionBuilder.java
- core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequestWriter.java
- core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
- core/src/test/java/com/linecorp/armeria/server/ExceedingServiceMaxContentLengthTest.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
Motivation:
Currently, large requests are rejected only after the transferred bytes exceed the configured limit. This behavior is sub-optimal for requests that include a valid Content-Length header indicating the request is already too large. By rejecting such requests earlier—when the header is read—we can improve resource utilization and reduce unnecessary processing.
Modifications:
- Added a field to ContentTooLargeException to indicate when the exception is raised during header processing.
- Implemented content-length-based early rejection in Http1ObjectDecoder and Http2ObjectDecoder.
Result:
Result:
- Closes #5880
- Requests with a Content-Length header exceeding the allowed limit can now be rejected early in the request flow, reducing wasted resources and improving efficiency.
> Early Rejection of Large Requests Based on Content-Length Header

- .github/workflows/actions_build.yml
- .github/workflows/publish-release.yml
To get more benefits from parallelism.
YAML runner tag | vCPU | Memory
-- | -- | --
ubicloud-standard-16 | 16 | 64GB
> Use ubicloud-standard-16 to run CI builds

- core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
- grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java
- grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCallTest.java
- grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServiceJsonSchemaTest.java
Motivation:
When blockingTaskExecutor is used in a gRPC service, tasks handling gRPC requests are queued if the executor is busy with heavy blocking jobs. https://github.com/line/armeria/blob/0960d091bfc7f350c17e68f57cc627de584b9705/grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java#L363 If these tasks are delayed for too long, the corresponding gRPC requests may time out and get cancelled. Despite the cancellation, the queued tasks are still executed once the executor becomes available, leading to unnecessary processing. https://github.com/line/armeria/blob/0960d091bfc7f350c17e68f57cc627de584b9705/grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java#L394-L404
Modifications:
- Updated `AbstractServerCall.invokeOnMessage()` …
> Prevent Execution of Delayed Tasks for Cancelled gRPC Requests

- core/src/main/java/com/linecorp/armeria/client/Endpoint.java
- core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
Motivation:
We observed `OutOfMemoryError` in internal CI tests when a new `Endpoint` is created.
```
com.linecorp.armeria.xds.client.endpoint.EndpointsPool$$Lambda$754/1708334230@3a58f44e
java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOfRange(Arrays.java:3664)
at java.lang.String.<init>(String.java:207)
at java.lang.StringBuilder.toString(StringBuilder.java:412)
at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:593)
at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:87)
at java.lang.String.valueOf(String.java:2994)
at java.lang.StringBuilder.append(StringBuilder.java:136)
at com.linecorp.armeria.internal.shaded.guava.collect.AbstractMapEntry.toString(AbstractMapEntry.java:70)
at java.lang.String.valueOf(String.java:2994)
at …
```
> Exclude attributes from `Endpoint.toString()`

- consul/src/main/java/com/linecorp/armeria/internal/consul/ConsulClient.java
Motivation:
The existing Javadoc in ConsulClient.java contains ambiguous and grammatically inconsistent descriptions for several methods. This patch clarifies the purpose, parameters, and return values of the methods, ensuring that users understand what each method does.
Modifications:
- Refined Javadoc for service registration, deregistration, and endpoint retrieval methods for better clarity and consistency.
Result:
- After merging this PR, users will benefit from clearer and more accurate documentation in the ConsulClient class.
> Improve ConsulClient Javadoc

- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
Motivation:
When `HealthCheckedEndpointGroup` is closing, the internally managed endpoints are cleared.
https://github.com/line/armeria/blob/011741dc51cf328b78488655e78ceca1cdc0a1b3/core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java#L135 In fact, the closing process is not a problem. However, when the endpoints change, the change is propagated to `EndpointSelector`. Some `EndpointSelector` implementations warn about the empty endpoints. The warning is not a real problem but a false positive alarm.
https://github.com/line/armeria/blob/62da203bd9e11d669476e6999937352749cd7339/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java#L81 
For better compatibility with `EndpointSelector` implementations, I propose …
> Stop updating endpoints when `HealthCheckedEndpointGroup` is closing

- core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
- core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
This pull request addresses #6058 
Currently, `@Param` cannot be mapped to a Map, but this change enables that functionality, allowing query parameters to be handled as a Map.
- Introduced logic in `AnnotatedValueResolver` to detect when a parameter is of type Map and the `@Param` annotation has an unspecified value.
- Future enhancements may include supporting the mapping of specific values to a Map when the `@Param` value is explicitly specified.
- Added a new method `ofQueryParamMap` to handle the creation of an AnnotatedValueResolver for mapping all query parameters into a Map.
- Query parameters are collected into a Map using the stream-based collector.
- Updated the existing logic to ensure this behavior only applies when the `@Param` value is unspecified and the parameter type is …
> Support for HTTP GET map parameters

- core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
Motivation:
Each `CacheEntry` should be bound to a specific `RefreshingAddressResolver`, and the associated DNS refresh query must be executed using its own executor. However, there was a bug where the refresh query could be mistakenly executed by the executor of a different resolver accessing the same `CacheEntry`.
Modifications:
- Ensured that the DNS refresh query is always executed by the correct `RefreshingAddressResolver`'s executor.
Result:
- DNS refresh query is executed by the correct executor.
- Close #5891 #6003
> Fix a bug where an incorrect executor used for DNS refresh query

- core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
- core/src/test/java/com/linecorp/armeria/client/RequestAutoAbortLeakTest.java
Motivation:
The motivation for this PR is better stated in https://github.com/line/armeria/issues/6104.
Modifications:
- Modified so that when a request is aborted with a `ResponseCompleteException`, the stream is reset with `CANCEL` for http2 or the connection is closed for http1.
Result:
- Connections do not hold references on automatically aborted requests, resulting in less memory pressure.
> Reset the stream when a response is completed before its corresponding response

- core/src/main/java/com/linecorp/armeria/client/AbstractDnsResolverBuilder.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java
Motivation:
We received a report where it seemed like DNS nameservers do not correctly reflect changes in `/etc/resolv.conf`.
The following issue has been pointed out to be a likely culprit:
https://github.com/netty/netty/issues/14364
Given that we don't release as often recently and the cause isn't very clear, I propose that we expose methods that might solve the issue.
`servicetalk` seems to have also applied a similar fix recently: https://github.com/apple/servicetalk/pull/3073/files.
Modifications:
- Expose `datagramChannelStrategy` which provides an option to create a channel per-resolution
- Expose `socketChannelType` so that users may use tcp-fallback in case resolution via udp doesn't work as expected
- Given that it is difficult to test these settings, added a basic regression …
> Expose experimental settings for dns

- core/src/main/java/com/linecorp/armeria/common/logging/DefaultLogWriter.java
- core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapper.java
- core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
- core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
- core/src/test/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapperTest.java
- core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
- core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Motivation:
The `ResponseLogLevelMapper.of()` did not use the `SuccessFunction` to determine whether a response was successful.
Modifications:
- Updated `ResponseLogLevelMapper.of()` to use the `SuccessFunction` when determining the success of a response.
Result:
- Log levels for responses are now correctly mapped based on the `SuccessFunction`.
> Fix Missing Use of `SuccessFunction` in Determining Response Success for Log Levels

- core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
- core/src/test/java/com/linecorp/armeria/server/cors/test/CorsBuilderTest.java
Motivation:
ref: https://discord.com/channels/1087271586832318494/1087272728177942629/1341502341517545585
Modifications:
- Exposed the build method and added a test located in a different package
Result:
- `CorsPolicyBuilder#build` is exposed publicly again
> Expose `CorsPolicyBuilder#build`

- core/src/main/java/com/linecorp/armeria/client/cookie/DefaultCookieJar.java
- core/src/test/java/com/linecorp/armeria/client/cookie/DefaultCookieJarTest.java
Motivation:
The `DefaultCookieJar` does not handle cases where cookies with the same name are set.
Modifications:
- Added processing in accordance with [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265#page-24):
- Overwrites existing cookies when a cookie with the same name, domain, and path is set.
- If the existing cookie has the `HttpOnly` flag set and the new cookie is created by a non-HTTP API, the new cookie is ignored.
Result:
- Correctly handles setting cookies with the same name.
- Closes #5870.
> Add handling for cookies with the same name to `DefaultCookieJar`

- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
- core/src/main/java/com/linecorp/armeria/common/CommonPools.java
Motivation:
The method `Schedulers.registerNonBlockingThreadPredicate` was introduced in Reactor 3.7.0+. To maintain compatibility with older Reactor versions, we should only register the EventLoop as a non-blocking thread if this method is available. If the method is unavailable (i.e., in Reactor versions lower than 3.7.0), a warning log should be emitted instead of causing an error.
Modifications:
- Check for the existence of `Schedulers.registerNonBlockingThreadPredicate` before invoking it.
- If the method is unavailable, log a warning instead of attempting registration.
Result:
- Ensured compatibility with both newer and older Reactor versions.
> Register EventLoop as a Non-Blocking Thread in Reactor Scheduler 3.7.0+

- core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
- core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
- core/src/main/java/com/linecorp/armeria/internal/common/SplitHttpMessageSubscriber.java
- core/src/test/java/com/linecorp/armeria/common/stream/DuplicatorCumulativeDemandTest.java
- core/src/test/java/com/linecorp/armeria/server/GracefulShutdownBuilderTest.java
Motivation:
The cumulative demand in a duplicator is mistakenly calculated, causing it to reach the maximum value incorrectly.
Modifications:
- Corrected the calculation logic for cumulative demand in the duplicator.
Result:
- The cumulative demand in a duplicator is correctly calculated.
> Fix Incorrect Calculation of Cumulative Demand in Duplicator

- kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroup.java
- kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupBuilder.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/FaultInjectingKubernetesClientBuilderCustomizer.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMaxWatchAgeTest.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/ServiceWatchCountingKubernetesClientBuilderCustomizer.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/ServiceWatchCoutingKubernetesClientBuilderCustomizer.java
Motivation:
Currently, the KubernetesEndpointGroup watch is designed to stay active for as long as possible and automatically restart when an error occurs. However, in practice, maintaining a long-running watch session inevitably leads to errors, causing it to terminate and restart. From the perspective of monitoring observers, these errors could be false-positive noise.
To help prevent these errors, I would suggest periodically closing the watch when it reaches a certain lifespan and creating a new one.
Modifications:
- Add `maxWatchAge()` option to `KubernetesEndpointGroupBuilder`
- If unset, the maximum age of a `Watch` defaults to 10 minutes.
- Refactor `KubernetesEndpointGroup` to start a new watch service when the maximum age is reached.
Result:
You can now set the maximum age of a …
> Allow configuring the maximum age of Kubernetes `Watch`

- core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
- core/src/test/java/com/linecorp/armeria/client/HeaderListSizeExceptionTest.java
Motivation:
When an `UnprocessedRequestException` is raised, the client should not send an `RST_STREAM`.
Modifications:
- Updated the `Http2ResponseDecoder` to avoid sending `RST_STREAM` when `UnprocessedRequestException` occurs.
Result:
- The client does not send an `RST_STREAM` when an `UnprocessedRequestException` is raised.
> Do not send RST_STREAM when UnprocessedRequestException is raised

- kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroup.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMockServerTest.java
Motivation:
We need to specify the k8s namespace if it's specified.
Result:
- `KubernetesEndpointGroup` works properly even when the namespace is specified.
> Use namespace when retreiving k8s services

- kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroup.java
- kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMockServerTest.java
Motivation:
A race condition may occur where outdated watchers update endpoints while `start()` is cleaning them up at the beginning. As a result, the outdated endpoints were not removed in `KubernetesEndointGroup`.
Modifications:
- Increase `updateId` to prevent `Watcher`s referencing a lower `updateId` from updating endpoints.
Result:
Fixed a bug where outdated endpoints were not removed in `KubernetesEndpointGroup`.
> Prevent the old `Watcher`s from updating endpoints in `KubernetesEndointGroup`

- spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationNetUtil.java
Motivation:
I woud like to configure my Spring Boot application's port dynamically using `ArmeriaServerConfigurator`. However, if I leave the armeria ports section empty, it defaults to 8080. 
https://github.com/line/armeria/blob/845192b5dfd549fac5388d6d9bc4ec9e2daa0d07/spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java#L90-L93
I think we should prevent this default behavior to not break anyone's compatibility. So I updated the code so that we filter out any ports that are `-1`. Default behavior was throwing an exception during initialization, so I think it is fine to change this behavior.
Modifications:
- Don't initialize server ports that are less than 0.
- Somewhat relates to #5039
Result:
I have tested this manually by modifying …
> fix: prevent spring auto-configuration from assigning a random port if a port with number -1 is given

- core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
- core/src/main/java/com/linecorp/armeria/internal/client/AbstractAsyncSelector.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/SelectionTimeoutTest.java
- core/src/test/java/com/linecorp/armeria/internal/client/AbstractAsyncSelectorTest.java
Motivation:
`AbstractEndpointSelector` is a useful abstract which allows users to select and `Endpoint` asynchronously only by implementing `AbstractEndpointSelector#selectNow`. However, the current implementation has limitations in that 1) Only `Endpoint` can be selected 2) It is difficult to customize the timing when the pending futures must be reconsidered for completion.
While working on the introduction of an `XdsPreprocessor` https://github.com/line/armeria/pull/6096, I found it is useful to be able to select a value asynchronously in the following locations:
1) When a request is executed, the request must wait until a `ListenerSnapshot` is fetched
https://github.com/line/armeria/blob/6bbc2ac0a0ae74014bd686979d34767ba9a8236d/xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ …
> Introduce `AbstractAsyncSelector`

- core/src/main/java/com/linecorp/armeria/client/DefaultDnsCache.java
- core/src/main/java/com/linecorp/armeria/client/DnsCache.java
- core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
- core/src/test/java/com/linecorp/armeria/client/NoopDnsCache.java
- core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
Motivation:
The `RefreshingAddressResolver` is added to the `DnsCache` as listener but is never removed from it when the resolver is closed. This makes the `DnsCache` hold a strong reference (internally, in the `CopyOnWriteArrayList` that stores all the listeners) of it even when the resolver is closed, which may cause memory leak if the `DnsCache` is a global one and lives for the lifetime of the JVM.
Modifications:
- Removes the `DnsCacheListener` from the `DnsCache` to make it eligible for GC.
Result:
- Closes https://github.com/line/armeria/issues/6173.
- When the resolver is closed, the `DnsCache` no longer stores it in the list and hence no longer holds a reference of it.
> Remove DnsCacheListener from DnsCache when resolver is closed

- core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
- core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
Motivation:
While debugging https://github.com/line/armeria/issues/5880#issuecomment-2735723709, I found that `onSubscribe` could be emitted after `onError`.
This is a clear violation of specifications https://github.com/reactive-streams/reactive-streams-jvm?tab=readme-ov-file#1.7 and https://github.com/reactive-streams/reactive-streams-jvm?tab=readme-ov-file#1.9.
I propose that before aborting, `onSubscribe` is called if it hasn't been called yet. To prevent `onSubscribe` being called multiple times, `invokedOnSubscribe` is used as a guard.
Modifications:
- Extracted `maybeInvokeOnSubscribe` and called it also from `notifySubscriberOfCloseEvent0`
Result:
- We no longer observe race conditions between `onSubscribe` and `onError` when aborting a `StreamMessage`.
> Handle a race condition where `onSubscribe` may be emitted downstream after `onError`

- core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
- saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java
Motivation:
`HealthCheckedEndpointGroup` uses a list instead of a set to gather all endpoints, allowing for potential duplicates. However, when checking endpoints before adding them from the old group, it iterates over all elements, leading to issues. A separate set is needed to handle this properly.
Modifications:
- Introduced an additional set to track endpoints when updating from the old group.
Result:
- Ensures efficient endpoint updates in `HealthCheckedEndpointGroup`.
> Fix duplicate endpoint handling in `HealthCheckedEndpointGroup`

- core/src/main/java/com/linecorp/armeria/client/HttpResponseWrapper.java
Motivation:
If an `EndpointGroup` is used to send the request, `request.authority()` will be null. Consequently, log messages for unexpected exceptions lack the remote peer information, making it harder for users to identify the root cause.
Modification:
- Prepend `ClientRequestContext` to the expected warning mesage.
Result:
Remote peer information is correctly logged when an unexpected request failure occurs on the client side.
> Add request context information to unexpected exception logs

- .github/workflows/actions_build.yml
Motivation:
The same tests were run by the `pull_request` and `push` events, which would be a waste of resources.
Modifications:
- Exclude `dependabot/**` branches from the `on.push` event.
- Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-excluding-branches
Result:
Remove redundant tests in CI
> Exclude dependabot branches to avoid running the same tests twice.

- site/src/pages/docs/client-retry.mdx
- site/src/pages/docs/client-thrift.mdx
Motivation:
I found an incorrect class name and the use of deprecated functions in the document.
Therefore I fixed it to use the recommended function instead.
Modifications:
- Change `ThriftClient` to `ThriftClients`
- Use `RetryConfig` instead of deprecated functions.
Result:
- The corrected document will be displayed.
> fix documents for client-thrift and client-entry

- saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java
- saml/src/main/java/com/linecorp/armeria/server/saml/SamlEndpoint.java
- saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceProviderBuilder.java
- saml/src/test/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunctionTest.java
- saml/src/test/java/com/linecorp/armeria/server/saml/SamlEndpointTest.java
Motivation:
Previously, the recipient URI in a SAML assertion was compared using a strict string equality check. This caused false negatives when the URI was semantically equivalent but had minor differences, such as missing default ports.
Modifications:
- Introduced `isSameUri()` in `SamlAssertionConsumerFunction` to compare URIs by scheme, host, path, and port.
- Updated `SamlEndpoint` to reject URIs with empty or root (`/`) paths.
- Improved `SamlEndpoint.toUriString()` to append the default port only when the host is missing.
Result:
- Recipient URIs in SAML assertions are now compared more robustly, reducing the chance of false mismatches.
> Improve URI comparison and validation in SAML components

- core/src/main/java/com/linecorp/armeria/client/AbstractDnsResolverBuilder.java
- core/src/test/java/com/linecorp/armeria/client/DnsOverTcpTest.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TestTcpDnsServer.java
Motivation:
DNS over TCP configuration should be enabled by default in DNS resolvers. However, the default setting was unintentionally disabled during the implementation of #6127.
Motifications:
- Revert the default settings to re-enable TCP fallback in DNS resolver.
Result:
The default DNS resolver now correctly performs TCP fallback.
> Fixed a bug where the default setting for DNS over TCP was unintentionally disabled

- core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsMessageUtil.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TcpDnsQueryDecoder.java
- core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TestTcpDnsServer.java
Motivation:
A memory leak was detected while running `DnsOverTcpTest`. Related: https://github.com/netty/netty/pull/15033
Modifications:
- Forked `TcpDnsQueryDecoder` and applied a patch to fix the memory leak.
Result:
Stabilize CI builds
> Fix a memory leak in `DnsOverTcpTest`

- core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
Motivation:
I found that the `VirtualHost#normalizeHostnamePattern` method was performing unnecessary operations.
Modifications:
- Moved the code to remove the wildcard from `hostnamePattern` inside the `if then` scope.
Result:
- I expect that operations to be performed only if `hostnamePattern` is not a wildcard.
> Fix the `VirtualHost#normalizeHostnamePattern` method to not perform unnecessary operations

- core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListener.java
- core/src/test/java/com/linecorp/armeria/client/ConnectionPoolListenerTest.java
Related: #5159
**Motivation:**
Add `andThen` method to `ConnectionPoolListener` to chain more than one listener
**Modifications:**
- In `ConnectionPoolListener`, add `andThen` method.
- In `ConnectionPoolListenerTest`, add test
**Result:**
- Closes #5159
- Supersedes #5166 This PR replaces the changes proposed in #5166, which is now outdated.
- Now, we could chain more than one listener
> Add `andThen` method to `ConnectionPoolListener`

- core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
- core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
- core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
- core/src/main/java/com/linecorp/armeria/common/PublisherBasedHttpResponse.java
- core/src/main/java/com/linecorp/armeria/common/SplitHttpMessage.java
- core/src/main/java/com/linecorp/armeria/common/SplitHttpRequest.java
- core/src/main/java/com/linecorp/armeria/common/SplitHttpResponse.java
- core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
- core/src/main/java/com/linecorp/armeria/internal/common/stream/SurroundingPublisher.java
- core/src/test/java/com/linecorp/armeria/common/SplitHttpMessageTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/SurroundingPublisherTckTest.java
- core/src/test/java/com/linecorp/armeria/internal/common/stream/SurroundingPublisherTest.java
- grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientRetryTest.java
Motivation:
During the implementation of #5714, `HttpResponse.split()` was used to extract the headers from a streaming response. After applying a `RetryRule`, the new response was reconstructed in
https://github.com/line/armeria/blob/3a35abe68c80c0af8594600ce677df49e09a9e0e/core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java#L429 
However, because `SplitHttpResponse.body()` only publishes the data payloads and handles trailers separately, the trailers was missing in the reconstructed response, leading to a bug.
Modifications:
- Fixed `SurroundingPublisher` to allow the last element to be emitted asynchronously.
- Added `SplitHttpRequest.unsplit()` and `SplitHttpResponse.unsplit()` to re-create an `HttpResponse` from the split headers, body and trailers.
- Fixed …
> Fix a bug where the trailers of a streaming response was dropped by RetryingClient

- core/src/main/java/com/linecorp/armeria/client/endpoint/CompositeEndpointGroup.java
Motivation:
`CompositeEndpointGroup` has a race condition that can occur when multiple child `EndpointGroup`s notify listeners at the same time from different threads. Consider the following sequence of events involving two groups, A and B:
1. A's listener is invoked by thread A. https://github.com/line/armeria/blob/2367de299f71478bd93a618bd40b70a3676656c0/core/src/main/java/com/linecorp/armeria/client/endpoint/CompositeEndpointGroup.java#L64
2. Thread A sets `dirty = true`. https://github.com/line/armeria/blob/2367de299f71478bd93a618bd40b70a3676656c0/core/src/main/java/com/linecorp/armeria/client/endpoint/CompositeEndpointGroup.java#L65
3. Thread A sets `dirty = false`. https://github.com/line/armeria/blob/2367de299f71478bd93a618bd40b70a3676656c0/core/src/main/java/com/linecorp/armeria/cl …
> Fix a race condition in CompositeEndpointGroup

- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
- core/src/test/java/com/linecorp/armeria/common/FlagsTest.java
Motivation:
Currently we use `com.linecorp.armeria.preferHttp1=true` instead of defaultPreferHttp1. Make it support defaultPreferHttp1 and keep preferHttp1.
Modifications:
- Support defaultPreferHttp1 and fallback to preferHttp1 if we can't find defaultPreferHttp1
Result:
- Using the same property name with javadoc
> Make SystemPropertyFlagsProvider support defaultPreferHttp1 with the same name

- thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDocStringExtractor.java
Motivation:
We encountered an issue where namespace doesn't exist for central dogma artifacts.
https://mvnrepository.com/artifact/com.linecorp.centraldogma/centraldogma-common-legacy
While the cause in this case is unknown, it is definitely possible that namespaces doesn't exist given the `merge` option.
https://github.com/apache/thrift/blob/ef6a6c282a659a3e80add7e2d23ddb6855df34e2/compiler/cpp/src/thrift/generate/t_json_generator.cc#L352-L354
Since it is unlikely thrift docs for files without namespaces will be correctly mapped anyways, I propose that we just ignore thrift docs without package names instead of the assertion so that users can at least view the doc service.
Modifications:
- Continue thrift docstring extraction when the java namespace isn't available instead of asserting …
> Remove assumption that namespace always exists for thrift docs

- site/src/pages/docs/client-service-discovery.mdx
Modifications:
- In `client-service-discovery.mdx`, some EndpointGroup example code has typo
- There are semicolon right after `builder(...)` but it has more successive method calls.
- In `ConsulEndpointGroupBuilder` example, `build()` should not be called.
Result:
- Fixed typo and errors in docs
> Fix typo in client-side service discovery docs

- core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
- core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
- core/src/test/java/com/linecorp/armeria/server/Http2ResetStreamTest.java
- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/NettyServerExtension.java
- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/netty/Http2ClientFrameInitializer.java
- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/netty/HttpFrameAggregator.java
- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/netty/SimpleHttp2Connection.java
- testing-internal/src/main/java/com/linecorp/armeria/internal/testing/netty/package-info.java
Motivation:
The PR #6166 modified server-side behavior to send a `RST_STREAM` frame when the corresponding Armeria's `HttpRequest` and `HttpResponse` are completed. The assumption was that since the user was done using the `HttpRequest` and `HttpResponse`, the underlying stream can be cleaned up.
https://github.com/line/armeria/blob/a4bcb3e3b2a90a41b0066601d97da2fb04af5347/core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java#L146-L149
The code was written to check Netty's `Http2Stream` before sending a `RST_STREAM` - this is because sending a `endStream` would close the underlying stream anyways regardless of whether a `RST_STREAM` is sent.
However, when frames are flow controlled, `Http2Stream`'s state is updated after armeria's post-response future is invoked. To …
> Server doesn't send a `RST_STREAM` frame after `endStream` is sent

- dependencies.toml
- settings.gradle
- thrift/thrift0.22/build.gradle
Motivation:
This PR is a follow-up to #6254, and adds support for Thrift 0.22.
Modifications:
- Added the `thrift0.22` module, using the same setup as `thrift0.21`
Result:
- Armeria supports Thrift 0.22.0
> Add support for Thrift 0.22.0

- dependencies.toml
- it/xds-client/build.gradle
- it/xds-client/src/test/java/com/linecorp/armeria/xds/it/EndpointCollectingDecorator.java
- it/xds-client/src/test/java/com/linecorp/armeria/xds/it/RoutingTest.java
- it/xds-client/src/test/java/com/linecorp/armeria/xds/it/XdsResourceReader.java
- settings.gradle
- xds/src/main/java/com/linecorp/armeria/xds/ParsedFilterConfig.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/FilterUtil.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointUtil.java
Motivation:
After merging https://github.com/line/armeria/pull/6299, I found some bugs when the filter config is not specified.
In detail:
- If the filter config is not specified, `ConfigTypeCase.CONFIGTYPE_NOT_SET` may be set.
- The config passed may be a default `Any` type if not specified
The bugs were found while implementing an integration test
Modifications:
- Modified not to fail filter config parsing when `ConfigTypeCase.CONFIGTYPE_NOT_SET`
- Modified to return a null config if the default `Any` is specified
Result:
- Filters which do not specify a config send requests correctly
> Fix bugs when validating xDS filter configuration

- core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
- core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
- core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
- core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
- core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
- core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/Flags.java
- core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
- core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
- core/src/main/java/com/linecorp/armeria/internal/client/DecodedHttpResponse.java
- core/src/main/java/com/linecorp/armeria/internal/common/InboundTrafficController.java
- core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
- core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
- core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
- core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
- core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
- core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
- core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
- core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
- core/src/test/java/com/linecorp/armeria/client/HttpClientFlowControlTest.java
- core/src/test/java/com/linecorp/armeria/client/HttpResponseWrapperTest.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerFlowControlTest.java
- core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
- core/src/test/java/com/linecorp/armeria/server/StreamingDecodedHttpRequestTest.java
Motivation:
Since `InboundTrafficController` operates at the TCP level, it isn't aligned with HTTP/2 flow control. As a result, a stream may receive more than its stream window size allows and interfering with other streams from receiving data.
Related: #6253
Modifications:
- Integrated `InboundTrafficController` with HTTP/2 `Http2LocalFlowController`
- Invokes `Http2LocalFlowController.consumeBytes()` when steam data is consumed to send a `WINDOW_UPDATE` frame.
- Introduced `{ServerBuilder,ClientFactoryBuilder}.http2StreamWindowUpdateRatio` to customize the threshold to send WINDOW_UPDATE frames.
- Fixed `client.Http2ResponseDecoder` and `server.Http2RequestDecoder` to defer reporting the consumed data length.
- The length is not reported via `InboundTrafficController` when the data is …
> Ensure HTTP/2 flow control to work at the stream level

- grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
- grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
Motivation
HttpJsonTranscodingService currently fails with 400 Bad Request when handling a request with Content-Type: application/json and no body, even if the corresponding google.api.http rule uses body: "*". This behavior is inconsistent with common implementations such as Envoy and grpc-gateway, which treat empty bodies as {} in such cases.
⸻
Modifications
- **HttpJsonTranscodingService**
- Added a fallback to use an empty JSON object when body empty ( content-length: 0 )
- Treat **empty request bodies** as `{}` when **all** of the following are true:
- **Content-Type**: `application/json`
- **google.api.http rule**: `body: "*"`
⸻
Result
- Closes #6319.
- Users can now send requests with Content-Type: application/json and an empty body without receiving a 400 Bad Request error.
- …
> feat: accept empty content body in HttpJsonTranscodingService

- core/src/main/java/com/linecorp/armeria/common/util/AsyncLoader.java
- core/src/main/java/com/linecorp/armeria/common/util/AsyncLoaderBuilder.java
- core/src/main/java/com/linecorp/armeria/common/util/DefaultAsyncLoader.java
- core/src/test/java/com/linecorp/armeria/common/util/DefaultAsyncLoaderTest.java
- nacos/src/main/java/com/linecorp/armeria/internal/nacos/LoginClient.java
Motivation:
If `AsyncLoader` provides a way to load the cached value dynamically, we may flexibly respond to external changes. For example, if the certificates of Athenz changes, the cached OAuth2 keys need to be refreshed.
Modifications:
- Main change) Add `load(boolean forceLoad)` to `AsyncLoader` to fetch a new value from the given loader.
- Add `refreshAfterLoad()` option to `AsyncLoaderBuilder` to easily refresh a cached value after the load.
- `Add `name()` option to `AsyncLoaderBuilder`.
- The name is used to a prefix when logging.
- Cached values are excluded from the logging because they can be sensitive when used with a token client.
Result:
You can now focibliy refresh the cached value in `AsyncLoader`
> Add option to force reload values in `AsyncLoader`

- core/src/main/java/com/linecorp/armeria/common/CoreBlockHoundIntegration.java
Motivation:
BlockHound reported `SslContext.buildKeyStore()` as a blocking operation.
```
Thread[#82,armeria-common-worker-epoll-3-7,5,main]
java.lang.Exception: java.io.FileInputStream#readBytes
at com.linecorp.armeria.internal.testing.InternalTestingBlockHoundIntegration.writeBlockingMethod(InternalTestingBlockHoundIntegration.java:86)
at reactor.blockhound.BlockHound$Builder.lambda$install$8(BlockHound.java:488)
at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:89)
at java.base/java.io.FileInputStream.readBytes(FileInputStream.java)
at java.base/java.io.FileInputStream.read(FileInputStream.java:287)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119)
at java.base/sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:432)
at …
```
> Exclude `SslContext.buildKeyStore()` from BlockHound reports

- athenz/src/main/java/com/linecorp/armeria/client/athenz/AthenzClient.java
- athenz/src/main/java/com/linecorp/armeria/common/athenz/TokenType.java
- athenz/src/main/java/com/linecorp/armeria/internal/common/athenz/AthenzHeaderNames.java
- athenz/src/main/java/com/linecorp/armeria/server/athenz/RequiresAthenzRole.java
- athenz/src/test/java/com/linecorp/armeria/common/athenz/TokenTypeTest.java
- athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzAnnotatedServiceTest.java
- athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzIntegrationTest.java
Motivation:
I realized that Athenz has replaced the `Yahoo-Role-Auth` header with `Athenz-Role-Auth` header for sending role tokens.
Modifications:
- Raname the orignal `ROLE_TOKEN` to `YAHOO_ROLE_TOKEN`
- Add `ATHENZ_ROLE_TOKEN`
Result:
Users can use `Athenz-Role-Auth` header for sending role tokens.
> Support `Athenz-Role-Auth` header in Athenz module

- athenz/src/test/java/com/linecorp/armeria/client/athenz/AccessTokenClientTest.java
- athenz/src/test/java/com/linecorp/armeria/client/athenz/RoleTokenClientTest.java
- athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzAnnotatedServiceTest.java
- athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzDocker.java
- athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzExtension.java
- athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzIntegrationTest.java
- athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzInvalidPolicyDataTest.java
- athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzPolicyLoaderTest.java
- core/src/test/java12/com/linecorp/armeria/server/JavaHttpClientUpgradeTest.java
- dependencies.toml
- examples/athenz/build.gradle
- examples/athenz/src/main/java/example/armeria/athenz/GrpcServiceImpl.java
- examples/athenz/src/main/java/example/armeria/athenz/Main.java
- examples/athenz/src/main/java/example/armeria/athenz/RestServiceImpl.java
- examples/athenz/src/main/proto/hello.proto
- examples/athenz/src/test/java/example/armeria/athenz/AthenzTest.java
- examples/context-propagation/dagger/src/main/java/example/armeria/contextpropagation/dagger/Main.java
- gradle.properties
- settings.gradle
- site/src/pages/docs/advanced-athenz.mdx
- site/src/pages/docs/toc.json
- site/src/pages/release-notes/1.33.0.mdx
Motivation:
The documentation and examples help users quickly integrate Athenz.
Modifications:
- Add `advanced-athenz.mdx` for Athenz documentation
- Move Athenz docker logic from `AthenzExtension` into `AthenzDocker` so that it can be used independently of JUnit.
- Add `examples/athenz` for providing fully working Athenz examples
Result:
More comprehensive documentation
> Add Athenz documentation and example

- licenses/web-licenses.txt
Fixed caching by updating web-licenses to be in line with the state after the build
Motivation:
We've noticed that if you run two consecutive clean builds, the 2nd build has a lot of cache misses, due to the `<subproject>/build/resources/main/META-INF/com.linecorp.armeria.versions.properties` [differs (in each subproject)](https://ge.solutions-team.gradle.com/c/ualzqlfqciga4/woog2eg6cpf5e/task-inputs?cacheability=cacheable,overlapping-outputs,validation-failure&expanded=WyJybWt6ZzRkY2xkcGZtLWNsYXNzcGF0aCIsInJta3pnNGRjbGRwZm0tY2xhc3NwYXRoLTAtMCJd#change-rmkzg4dcldpfm-classpath-0-0-0). After an investigation, we found that the property `<subproject>.repoStatus` differs, which is caused by the git state not being clean after the first build because of changes in the …
> Fixed caching by updating web-licenses

- core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
- core/src/main/java/com/linecorp/armeria/client/RefusedStreamException.java
- core/src/test/java/com/linecorp/armeria/client/Http2ClientRefusedStreamTest.java
- it/xds-client/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteEntryMatcherTest.java
- it/xds-client/src/test/java/com/linecorp/armeria/xds/it/RetryTest.java
- it/xds-client/src/test/java/com/linecorp/armeria/xds/it/RouteMatcherTest.java
- it/xds-client/src/test/java/com/linecorp/armeria/xds/it/TimeoutTest.java
- it/xds-client/src/test/java/com/linecorp/armeria/xds/it/VirtualHostRoutingTest.java
- xds/src/main/java/com/linecorp/armeria/xds/ListenerXdsResource.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ConfigSupplier.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/FilterUtil.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/RetryStateFactory.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/RouteEntryMatcher.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/RouterFilter.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/SelectedRoute.java
- xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsCommonUtil.java
Motivation:
This changeset attempts to implement retries automatically for xDS clients.
While doing so, three points are modified:
1) In order to support the rule `refused-stream`, `RefusedStreamException` is returned instead of `ClosedStreamException`. As this better reflects why a request was closed, I believe this is preferable independent of this changeset.
2) A bug where a router's `Filter#getName` was used instead of `Filter#getTypeUrl` was found. This behavior was fixed. Note that this bug only affects `Xds*Preprocessor`s, and `XdsEndpointGroup` remains unaffected.
3) `RetryStateFactory` has been introduced which creates a `RetryingClient` based on the retry policy. The expected behavior can be found here:
documentation ref: …
> Support retries for `XdsPreprocessor`

- core/src/main/java/com/linecorp/armeria/server/file/FileService.java
- core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
Motivation:
Range requests may be made for services serving data with large content (`FileService`).
ref: https://datatracker.ietf.org/doc/html/rfc9110#name-range-requests
Currently, `FileService` doesn't support ranged requests, but at the same time there is no reason to reject range requests.
Returning normally (with a 200) should gracefully let clients know that range requests are not supported.
Modifications:
- `FileService` responds to `HEAD` requests with a 200 response
Result:
- #6392
> `FileService` responds to `HEAD` range requests

- core/src/main/java/com/linecorp/armeria/client/HttpResponseWrapper.java
- core/src/test/java/com/linecorp/armeria/client/RequestLogCompleteTest.java
Motivation:
A race condition existed in the client-side response decoder.  Consider this situation:
- A client receives a response header and the response is open:
- https://github.com/line/armeria/blob/e94aceef3266283075fcb5da680f9e29e31f49b7/core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java#L203
- The client call `res.close()` if `endOfStream` is true:
- https://github.com/line/armeria/blob/e94aceef3266283075fcb5da680f9e29e31f49b7/core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java#L237
- Let's say another thread aborts the response at this point.
- The client sets the `closed` to true:
- https://github.com/line/armeria/blob/9bb52da34cf9121fed1efa7af7599ab4aacdf752/core/src/main/java/com/linecorp/armeria/client/HttpResponseWrapper.java#L219
- …
> Fix race condition causing incomplete client logs on abort

- core/src/main/java/com/linecorp/armeria/common/Flags.java
- it/flags-cyclic-dep/src/test/java/com/linecorp/armeria/common/FlagsCyclicDependencyTest.java
- it/flags-cyclic-dep/src/test/resources/logback-test.xml
Motivation:
A cyclic dependency existed between the Flags and `RequestContextUtil` classes. `RequestContextUtil`'s static initializer calls `Flags.requestContextStorageProvider()`, and when `RequestContextExportingAppender` is enabled, the `Flags` static initializer could indirectly call `RequestContextUtil.get()`. This created a race condition where two concurrent threads could cause a deadlock while initializing these two classes.
Modification:
- The call to `FlagsLoaded.set()` was moved to the very end of the static initialization block in the `Flags` class.
Result:
The deadlock `Flags` and `RequestContextUtil` static initialization is eliminated.
> Fix deadlock between Flags and RequestContextUtil static initialization

- core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
- thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
**Motivation**
`RetryingRpcClientTest.doNotRetryWhenResponseIsCancelled` is brittle because it assumes that cancelling the response after delegating to `RetryingRpcClient` will always result in exactly one attempt. However, there is no guarantee about the number of attempts made between `res = delegate.execute()` and `res.cancel()`.
I propose rewriting the test to verify two guarantees:
1. If the response is cancelled before `RetryingRpcClient.execute` is called, `RetryingRpcClient` performs no attempts.
2. If the response is cancelled after `RetryingRpcClient.execute` is called, `RetryingRpcClient` performs at most one additional attempt after cancellation.
The first guarantee is straightforward to test. For the second, we currently lack a way to signal cancellation before invoking …
> Fix `RetryingRpcClientTest.doNotRetryWhenResponseIsCancelled`
