src/main/java/com/linecorp/armeria/client/HttpConfigurator.java
Fix typo in `HttpConfigurator` class.
(`http2preferedProtocols` -> `http2preferredProtocols`)
=> Fix typo in HttpConfigurator

src/site/sphinx/_static/overrides.css
Documentation layout was strange in Firefox. (tested on Mac Firefox 42)
=> Fix side nav logo in Firefox

src/main/java/com/linecorp/armeria/server/ServiceEntry.java
Motivation:
ServerConfig.toString() triggers a StackOverflowError because of the cyclic
dependency between VirtualHost and ServiceEntry.
ServerConfig.toString() calls VirtualHost.toString(), VirtualHost.toString()
calls ServiceEntry.toString(), ServiceEntry.toString() calls
VirtualHost.toString(), and so on.
Modification:
Change ServiceEntry.toString() so that it does not call
VirtualHost.toString() but just call VirtualHost.hostnamePattern(),
which should be enough for the stringification of ServiceEntry.
Result:
ServerConfig.toString() works fine.
=> Fix StackOverflowError in ServerConfig.toString()

src/main/resources/com/linecorp/armeria/server/docs/assets/js/armeria.js, src/main/resources/com/linecorp/armeria/server/docs/index.html
Motivation:
The sidebar is hidden by default in mobile view, and it is able to toggle the visibility.
The problem is that it is not hidden again when a user clicks a link in the sidebar. A user has to close it all the time, and it is definitely bad user experience.
Modification:
Collapse the sidebar when clicking a link in the sidebar in mobile view
Result:
Better user experience for mobile doc service
=> Fix sidebar to be collapsed in mobile view

src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, src/test/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandlerTest.java
Motivation:
I add test case consider case of #14
Modifications:
* add test-case of idle timeout event throws twice by ``IdleStateHandler``  on `HttpClientIdleTimeoutHandler``
* add test-case of ``HttpServerIdleTimeoutHandler``
* Increase Timeout of ThriftOverHttpClientTest (1sec -> 10sec)
result
proof HttpClientIdleTimeoutHandler and HttpServerIdleTimeoutHandlerTest has no problem about   https://github.com/line/armeria/issues/14
=> Add TestCases for HttpClientIdleTimeoutHandler and HttpServerIdleTimeoutHandlerTest

pom.xml
.. for the following JRE versions:
- 1.8.0_60 (Fix the wrong ALPN-boot version)
- 1.8.0_65
- 1.8.0_66
Also:
- Change the scope of alpn-api from 'compile' to 'provided'. According
to Jetty's ALPN documentation:
"To implement this interaction, Jetty's ALPN implementation provides an
API to applications, hosted at Maven coordinates
org.eclipse.jetty.alpn:alpn-api. You need to declare this dependency
as provided, because the alpn-boot Jar already includes it (see the
previous section), and it is therefore available from the boot
classpath."
- Related issue: https://github.com/netty/netty/issues/4480
=> Add more ALPN-related Maven profiles

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java, src/test/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceTest.java
Motivation:
`Content-Type` header is missing in `TomcatServiceInvocationHandler.convertResponse`.
Modification:
Add `Content-Type` header if it is possible
Result:
Correct `Content-Type` header value
=> Add Content-Type header for TomcatService

src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
Motivation
@trustin reported  ``HttpClientIdleTimeoutHandlerTest `` test case failed when change to netty 4.1.0.BETA8
I caused by incorrect assert.
Exceptions
Pass Test Case
=> fix Invalid assert on HttpClientIdleTimeoutHandlerTest

pom.xml, src/main/java/com/linecorp/armeria/client/HttpRemoteInvoker.java, src/main/java/com/linecorp/armeria/common/ServiceInvocationContext.java, src/test/java/com/linecorp/armeria/server/GracefulShutdownIntegrationTest.java
Related: #21
Motivation:
Given that ServiceInvocationContext is almost always available in the
server-side thread, it is inconvenient to call Optional.get() to get the
current thread's ServiceInvocationContext.
Modifications:
- Make ServiceInvocationContext.current() return
ServiceInvocationContext instead of Optional and throw
IllegalStateException when the context is unavailable
- Add ServiceInvocationContext.mapCurrent() for a caller who does not
expect an exception when the context is unavailable
- Add jsr305 as an optional dependency to use the `@Nullable` annotation
Result:
More user-friendly API
=> Make ServiceInvocationContent.current() return non-Optional

src/main/java/com/linecorp/armeria/client/pool/SafeKeyedChannelPoolHandler.java
I found typo on ``SafeKeyedChannelPoolHandler``.
=> fix typo on SafeKeyedChannelPoolHandler

src/main/java/com/linecorp/armeria/common/util/Functions.java
Related: #29
Motivation:
When there are more than two functions to compose, Functions.compose()
isn't useful enough.
Modifications:
- Add the overloaded Functions.compose() methods that accept up to 9
functions
- Add Javadoc
Result:
Easier to build a decorator when some or all decorators are method
handles
=> Add more Functions.compose() methods to compose more than 2 functions

NOTICE.txt, pom.xml, src/main/java/com/linecorp/armeria/client/ClientBuilder.java, src/main/java/com/linecorp/armeria/client/ClientCodec.java, src/main/java/com/linecorp/armeria/client/ClosedSessionException.java, src/main/java/com/linecorp/armeria/client/DecoratingClientCodec.java, src/main/java/com/linecorp/armeria/client/DecoratingInvocationHandler.java, src/main/java/com/linecorp/armeria/client/DecoratingRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/Http2ClientIdleTimeoutHandler.java, src/main/java/com/linecorp/armeria/client/HttpConfigurator.java, src/main/java/com/linecorp/armeria/client/HttpRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java, src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/client/http/SimpleHttpClientCodec.java, src/main/java/com/linecorp/armeria/client/logging/LoggingClientCodec.java, src/main/java/com/linecorp/armeria/client/thrift/ThriftClientCodec.java, src/main/java/com/linecorp/armeria/common/http/AbstractHttpToHttp2ConnectionHandler.java, src/main/java/com/linecorp/armeria/common/http/Http1ClientCodec.java, src/main/java/com/linecorp/armeria/common/http/package-info.java, src/main/java/com/linecorp/armeria/server/DecoratingServiceCodec.java, src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, src/main/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandler.java, src/main/java/com/linecorp/armeria/server/ServerInitializer.java, src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java, src/test/java/com/linecorp/armeria/client/http/SimpleHttpClientCodecTest.java, src/test/java/com/linecorp/armeria/client/thrift/ThriftClientCodecTest.java, src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java, src/test/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandlerTest.java, src/test/java/com/linecorp/armeria/server/thrift/THttp2Client.java, src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp1Test.java
Changes related with Netty 4.1.0.Beta8 upgrade:
- Add common.http.Http1ClientCodec to:
- work around the bug in Netty HttpClientCodec
netty/netty#4504 for more info
- add onCloseRequest() as an extension point
- Add common.http.AbstractHttpToHttp2ConnectionHandler to
- remove the code duplication in HttpConfigurator and
ServerInitializer
- Avoid using the builder pattern for building Http2ConnectionHandler,
because it doesn't really simplify construction a lot
- Reorganize the client-side pipeline construction
- HttpConfigurator.finishConfiguration() now adds most of the common
handlers
- Remove HttpSessionChannelFactory.SESSION_ACTIVE and SessionListener
- Change the way how the activeness of a session is determined
- Active if and only if the pipeline contains HttpSessionHandler
- Move …
=> Upgrade to Netty 4.1.0.Beta8 / Interop with Jetty and cURL

src/main/java/com/linecorp/armeria/client/ClientOptions.java, src/main/java/com/linecorp/armeria/client/http/SimpleHttpRequest.java, src/main/java/com/linecorp/armeria/common/http/ImmutableHttpHeaders.java
Motivation:
Sometimes a user need to override the default `Content-Type` and
`Accept` header values set by invoker/codec implementation. For example,
a user might want to add a parameter to the MIME type:
Content-Type: application/x-thrift; protocol=tbinary schema=v3
Modification:
- Remove `Content-Type` and `Accept` from the blacklist
- Sort the blacklisted header name list
- Make a defensive immutable copy when building a value of
ClientOptions.HTTP_HEADERS
Result:
More freedom to users
=> Un-blacklist 'Content-Type' and 'Accept' from ClientOption.HTTP_HEADERS

src/main/java/com/linecorp/armeria/common/MimeTypeParams.java, src/main/java/com/linecorp/armeria/common/SerializationFormat.java, src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java, src/main/java/com/linecorp/armeria/server/docs/EndpointInfo.java, src/main/java/com/linecorp/armeria/server/docs/ServiceInfo.java, src/main/java/com/linecorp/armeria/server/docs/Specification.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftService.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceCodec.java, src/main/resources/com/linecorp/armeria/server/docs/assets/css/armeria.css, src/main/resources/com/linecorp/armeria/server/docs/assets/fonts/fonts.css, src/main/resources/com/linecorp/armeria/server/docs/assets/js/armeria.js, src/main/resources/com/linecorp/armeria/server/docs/index.html, src/test/java/com/linecorp/armeria/common/SerializationFormatTest.java, src/test/java/com/linecorp/armeria/common/thrift/text/TTextProtocolTest.java, src/test/java/com/linecorp/armeria/server/docs/DocServiceTest.java, src/test/java/com/linecorp/armeria/server/docs/ServiceInfoTest.java, src/test/java/com/linecorp/armeria/server/docs/SpecificationTest.java, src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
- Add EndpointInfo to represent:
- hostname(pattern) and path of a Service
- default MIME type
- available MIME types
- Replace ServiceInfo.debugPath() with endpoints()
- ServiceInfo exposes all available path information
- We exposed TTEXT paths only previously.
- Fix a bug where submitting in a debug form fails with Not Acceptable
- Fix a bug where StructContext fails to encode TApplicationException
- Update the frontend
- Add a section for rendering PathInfo
- Better error handling
- Overall style cleanup
Misc:
- Parse MIME type parameter properly
- Fix a test failure on Windows
=> Expose service path and formats in DocService

src/main/java/com/linecorp/armeria/server/PrefixPathMapping.java
Motivation:
PrefixPathMapping.equals() does not consider stripPrefix flag, making
the equals() method returns true on two PrefixPathMappings with the
same prefix and different stripPrefix flags
Modifications:
Modify PrefixPathMapping.equals() to consider the stripPrefix flag
Result:
One less bugs
=> Fix PrefixPathMapping.equals()

src/main/java/com/linecorp/armeria/server/docs/DocService.java, src/main/java/com/linecorp/armeria/server/http/file/HttpVfs.java, src/main/java/com/linecorp/armeria/server/http/file/MimeTypeUtil.java
Motivation:
HttpVfs.AbstractEntry relies on URLConnection.guessContentTypeFromName()
to determine the MIME type of an entry.
It seems like OpenJDK as well as other JREs do not return the correct
MIME types for some widely-used file extensions such as .css and .js.
Modern browsers warns about missing/incorrect 'Content-Type' of a file.
Some browsers such as Internet Explorer even refuse to load it.
Modification:
- Add MimeTypeUtil to provide more reliable MIME type detection for the
essential file extensions
- Set the content type of 'specification.json' to application/json in
DocService
- Add more constructors to the HttpVfs.Entry implementations so that a
user can specify the content type explicitly
Result:
- DocService works fine on Internet Explorer
- Chrome does not complain about …
=> Reliable MIME type detection for essential file types

src/main/java/com/linecorp/armeria/client/http/SimpleHttpClientCodec.java, src/test/java/com/linecorp/armeria/client/http/SimpleHttpClientCodecTest.java
- Calls Uri.toASCIIString() instead of Uri.getPath()
There was a time when armeria's context.path() included query parameter, and I seem to have mixed that up here...
=> Fix SimpleHttpClientCodec not keeping query string of uris.

src/main/java/com/linecorp/armeria/client/ClientBuilder.java, src/main/java/com/linecorp/armeria/client/ClientInvocationHandler.java, src/main/java/com/linecorp/armeria/client/http/SimpleHttpRequest.java
Motivation:
The InvocationHandler implementation in ClientBuilder does not handle
the public methods in Object class: toString(), hashCode() and equals()
Whenever a user or a debugger attempts to call one of those methods, the
caller will observe an unexpected behavior from the InvocationHandler.
Modifications:
- Extract the InvocationHandler implementation to a dedicated class:
- ClientInvocationHandler
- Implement the public methods in Object
- Fix NPE in SimpleHttpRequest.toString() when content is null, which
can happen when a debugger tries to call toString() before
construction is finished
- Fix NPE when the proxied method has no argument
Result:
Application does not fall apart even when it calls a public method
declared in java.lang.Object.
=> Implement the public methods in Object for dynamic proxy

src/main/java/com/linecorp/armeria/common/SerializationFormat.java, src/main/java/com/linecorp/armeria/server/ServiceCodec.java, src/main/java/com/linecorp/armeria/server/http/HttpServiceInvocationContext.java, src/main/java/com/linecorp/armeria/server/logging/LoggingServiceCodec.java, src/main/java/com/linecorp/armeria/server/metrics/MetricCollectingService.java, src/main/java/com/linecorp/armeria/server/metrics/MetricCollectingServiceCodec.java, src/main/java/com/linecorp/armeria/server/metrics/ServiceMetricConsumer.java, src/main/java/com/linecorp/armeria/server/metrics/package-info.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceCodec.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceInvocationContext.java, src/test/java/com/linecorp/armeria/common/SerializationFormatTest.java, src/test/java/com/linecorp/armeria/server/metrics/MetricCollectingServiceCodecTest.java, src/test/java/com/linecorp/armeria/server/metrics/ServiceMetricConsumerTest.java
Introduced classes are expected to be used with proper consumers which
can be implemented for own purposes. (integrate with dropwizard metrics,
or other in-house metric utilities)
=> Add service metrics decorator

src/test/java/com/linecorp/armeria/server/docs/StructInfoTest.java, src/test/thrift/main.thrift
Motivation:
```
[WARNING:src/test/thrift/main.thrift:73]
"slist" is deprecated and will be removed in a future compiler version.
This type should be replaced with "string".
[WARNING:src/test/thrift/main.thrift:85]
No field key specified for foos, resulting protocol may have conflicts
or not be backwards compatible!
[WARNING:src/test/thrift/main.thrift:86]
No field key specified for foos, resulting protocol may have conflicts
or not be backwards compatible!
```
- `slist` is deprecated. https://issues.apache.org/jira/browse/THRIFT-1994
Modification:
- Remove `slist` fields
- Add field keys for the missing
Result:
No more build warnings :smile:
=> Remove build warnings

src/main/java/com/linecorp/armeria/client/DnsNameResolverGroup.java, src/main/java/com/linecorp/armeria/client/RemoteInvokerFactory.java
Motivation:
- The current default of 3 queries per resolve is overly restrictive
when there are more than 2 name servers available.
- A known issue in Netty: https://github.com/netty/netty/pull/4541
Modifications:
- Fork DnsNameResolverGroup until the proposed change is merged:
https://github.com/netty/netty/pull/4542
- Work around the known DNS resolver issue in Netty by overriding the
default DnsServerAddresses and increasing the maxQueriesPerResolve
property
Result:
More robust DNS name resolution when there are even number of DNS
servers available
=> More robust DNS name resolution

src/main/java/com/linecorp/armeria/client/RemoteInvokerFactory.java, src/main/java/com/linecorp/armeria/server/Server.java
.. because there's no way for a user to close the default RemoteInvokerFactory
=> Use daemon threads for the default RemoteInvokerFactory

pom.xml, src/main/java/com/linecorp/armeria/client/HttpConfigurator.java
Motivation:
Once an upgrade to HTTP/2 is finished in a cleartext connection, the
server sends the response for the upgrade request to the client via the
stream 1. Armeria client currently does not handle it explicitly,
causing the response to reach at the end of the pipeline. This is not
necessarily harmful, but it will pollute our DEBUG log level because
Netty will log any messages that reach at the end of the pipeline.
Modifications:
- Make UpgradeHandler handle the upgrade response so that Netty does not
complain
- Change the next version to 0.6.1.Final
Result:
Less noisy log messages
=> Handle HTTP/2 upgrade response from the stream 1

src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
HttpSessionHandler.MultiplexWaitsHolder.poll() does not remove the polled request, causing a leak.
Also, replaced LinkedList with ArrayDeque for better performance and memory usage
=> Fix a leak in an HTTP/2 connection

src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
Fixes
```
java.lang.NullPointerException: null
at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[na:1.8.0_60]
at java.util.regex.Matcher.reset(Matcher.java:309) ~[na:1.8.0_60]
at java.util.regex.Matcher.<init>(Matcher.java:229) ~[na:1.8.0_60]
at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[na:1.8.0_60]
at com.linecorp.armeria.server.HttpServerHandler.logUnexpectedException(HttpServerHandler.java:473) [armeria-0.6.2.Final.jar!/:na]
```
=> Support unexpected exceptions that don't have a cause string.

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java
- Original work by @delegacy
- Improve HTTP request header conversion
- Improve HTTP response header conversion
- Add HTTP request content conversion
=> Fix missing HTTP request content conversion in TomcatService

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java, src/test/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceTest.java, src/test/resources/tomcat_service/query_string.jsp
Motivation:
TomcatServiceInvocationHandler does not set the 'queryString' property
of Coyote Request object during the conversion.
Modifications:
- Call Request.queryString().setString() if HttpRequest.uri() has a
query string
- Add the test cases for GET and POST with query parameters
Result:
Web application gets query parameters correctly.
=> Fix missing query string conversion in TomcatService

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java
Motivation:
When a user calls TomcatService.forCurrentClassPath(), the caller class
is determined to be TomcatService instead of the actual caller class.
Modification:
Increase the call depth parameter from 2 to 3
Result:
TomcatService.forCurrentClassPath() works as expected.
=> Fix wrong call depth in TomcatService.forCurrentClassPath()

src/main/java/com/linecorp/armeria/client/HttpRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/common/ServiceInvocationContext.java, src/main/java/com/linecorp/armeria/common/TimeoutException.java, src/main/java/com/linecorp/armeria/server/http/HttpService.java, src/main/java/com/linecorp/armeria/server/http/file/HttpFileServiceInvocationHandler.java, src/main/java/com/linecorp/armeria/server/http/healthcheck/HttpHealthCheckService.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceInvocationHandler.java, src/test/java/com/linecorp/armeria/server/GracefulShutdownIntegrationTest.java, src/test/java/com/linecorp/armeria/server/http/healthcheck/HttpHealthCheckServiceTest.java
Motivation:
When a client does not receive a response or a server fails to process a
request within time limit, an invocation promise is rejected regardless
the final outcome of the invocation.
In such a case, a ServiceInvocationHandler or a remote invoker
implementation might attempt to resolve or reject the promise which is
already rejected with TimeoutException. Handling this sort of situations
is very common, and thus we should provide it as part of Armeria.
Modifications:
- Add ServiceInvocationContext.resolvePromise() and rejectPromise() to
provide a simple and robust way to resolve or reject a promise in a
ServiceInvocationHandler
- Use resolvePromise() and rejectPromise() wherever possible.
- Fix a bug where WriteTimeoutException is raised rather than …
=> More robust resolution/rejection of a promise

pom.xml
Motivation:
We had to add a new profile for each OpenJDK/OracleJDK release to make
Maven choose the correct alpn-boot.jar and npn-boot.jar. As a result,
our pom.xml has a large number of `<profile/>` sections.
Modifications:
- Use jetty-alpn-agent, which chooses the correct alpn-boot.jar and
npn-boot.jar automatically to remove all the nasty profile sections
from pom.xml
- Visit https://github.com/trustin/jetty-alpn-agent for more info
Result:
Cleaner pom.xml
=> Use jetty-alpn-agent to simplify pom.xml

src/main/java/com/linecorp/armeria/common/ServiceInvocationContext.java, src/main/java/com/linecorp/armeria/common/ServiceInvocationContextAwareEventLoop.java, src/main/java/com/linecorp/armeria/common/ServiceInvocationContextAwareFuture.java, src/main/java/com/linecorp/armeria/common/ServiceInvocationContextAwarePromise.java, src/main/java/com/linecorp/armeria/common/ServiceInvocationContextProgressivePromise.java, src/test/java/com/linecorp/armeria/common/ServiceInvocationContextTest.java
Currently, when writing an asynchronous service that does multiple RPCs, the RPC callbacks will likely be called with no ServiceInvocationContext.current() set. This is because the initial invocation removes the context right away to allow processing another event from the event loop, here
https://github.com/line/armeria/blob/master/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L264
We need a mechanism for propagating the invocation context to when the RPC callbacks fire (and may trigger additional RPCs, callbacks, etc), otherwise context-dependent features (think zipkin) will not work.
This PR adds methods for propagating context into callback methods, including an executor that will do it automatically for any subitted tasks. In general, service code will want to to …
=> Add methods to ServiceInvocationContext for propagating context into callback invocations.

src/main/java/com/linecorp/armeria/common/ServiceInvocationContext.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java, src/test/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceTest.java, src/test/resources/tomcat_service/addrs_and_ports.jsp, src/test/resources/tomcat_service/index.jsp, src/test/resources/tomcat_service/query_string.jsp
Related: #81
Motivation:
When TomcatServiceInvocationHandler converts a Netty HTTP request to a
Coyote request, it should set the remoteAddr() and remoteHost() property
of the Coyote request.
Modifications:
- Fill remoteAddr/remoteHost/remotePort/localAddr/localName/localPort of
Coyote request
- Add ServiceInvocationContext.localAddress() to get the local address
and port
- Fix the content-type of the test JSP pages
Result:
Fixes #81
=> Set remoteHost/Addr/Port and localName/Addr/Port of Coyote request

src/main/java/com/linecorp/armeria/server/Server.java
This can be useful for scheduling lightweight periodic tasks to happen in the background for the lifetime of the server, for example refreshing some cache with the result of an asynchronous rpc.
=> Add a method to access an event loop created by the server.

pom.xml, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceBuilder.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceConfig.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java, src/test/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceTest.java
Related: #83
Motivation:
Tomcat registers JMX MBeans using the configured service name, which is
often 'Catalina' as written in the default Tomcat server.xml file.
TomcatService currently does not use 'Catalina' but
'Tomcat-over-Armeria' as the default service name. It makes the legacy
JMX clients confused because they assume a Tomcat MBean always has the
name 'Catalina'.
Also, a user might want to set some additional properties of Tomcat
which might not be used by an ordinary web applications. e.g.
Service.addExecutor().
Modifications:
- Add serviceName() and engineName() property
- Change the default service/engine name to 'Catalina' which is the
default in conf/server.xml
- Add configurator() builder operation so that a user can configure the
server more freely
- …
=> Add more configuration properties to TomcatService

src/main/java/com/linecorp/armeria/client/ClientInvocationHandler.java, src/main/java/com/linecorp/armeria/client/Clients.java, src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, src/test/thrift/main.thrift
Related: #95
Motivation:
Given that the creation of a new client is relatively an expensive
operation, a user might want to create a client that reuses the
RemoteInvoker and ClientCodec of an existing client while using an
alternative ClientOptions.
A good example is writing an API proxy that forwards a certain set of
HTTP headers such as access tokens, as explained in #95.
Modifications:
- Add Clients.newDerivedClient() that creates a derived client from an
existing client created by ClientBuilder or Clients.newClient()
- Add a test case for Clients.newDerivedClient() to
ThriftOverHttpClientTest
- Add HeaderService to assert that the derived client sends an
expected header
- Simplify the method comparison of ClientInvocationHandler. It doesn't
really need to use Method.equals() that …
=> Add a way to create a derived client

src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java, src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/common/ServiceInvocationContext.java, src/main/java/com/linecorp/armeria/common/http/AbstractHttpToHttp2ConnectionHandler.java, src/main/java/com/linecorp/armeria/common/util/Exceptions.java, src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
Motivation:
When Armeria is under heavy load that it cannot keep up with, exceptions
will be triggered, and some of them do not really need logging.
Here's the list of the exceptions which are triggered very usually in
case of socket disconnection due to timeout / connection reset by peer
errors:
- IOException: connection reset by peer / broken pipe
- Http2Exception$StreamException: Stream closed
- ClosedChannelException
- ClosedSessionException
Also, an attempt to close a HTTP/2 connection with pending writes can
cause unnecessarily long stack trace because of the following steps they
involve:
1. Channel.close() triggers AbstractHttpToHttp2ConnectionHandler.close().
2. AbstractHttpToHttp2ConnectionHandler.close() triggers Http2Stream.close().
3. Http2Stream.close() fails the promise of …
=> Reduce the unnecessarily noisy/long exceptions

pom.xml, src/main/java/com/linecorp/armeria/client/DefaultHostsFileEntriesResolver.java, src/main/java/com/linecorp/armeria/client/HostsFileParser.java, src/main/java/com/linecorp/armeria/client/HttpConfigurator.java, src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java, src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/client/RemoteInvokerFactory.java, src/main/java/com/linecorp/armeria/client/SessionProtocolNegotiationCache.java, src/main/java/com/linecorp/armeria/client/SessionProtocolNegotiationException.java, src/main/java/com/linecorp/armeria/common/util/Exceptions.java, src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, src/main/java/com/linecorp/armeria/server/ServerPort.java, src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java, src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, src/test/java/com/linecorp/armeria/server/ServerTest.java, src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Motivation:
The current HTTP/1-to-2 upgrade has the following slightly inter-related
issues:
1. When a user specifies an explicit session protocol (H1C/H1/H2C/H2)
instead of HTTP/HTTPS, the session creation must fail when the
negotiated protocol does not match exactly. For example, when a user
specified H2C, a rejected upgrade request should fail session creation.
2. When connecting to a host whose name is registered in /etc/hosts, the
'Host' header of the HEAD upgrade request is not set to the host name
but the host address.
3. When a user specifies HTTP/HTTPS as session protocol and the remote
host does not support H2C/H2, the client currently keeps sending the
HEAD upgrade request. We could cache the list of the hosts with no
HTTP/2 support, so we do not send upgrade requests …
=> More efficient and correct H1C-to-H2C upgrade

src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, src/main/java/com/linecorp/armeria/server/ServiceUnavailableException.java, src/main/java/com/linecorp/armeria/server/http/tomcat/ManagedTomcatServiceInvocationHandler.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java, src/test/java/com/linecorp/armeria/server/http/tomcat/UnmanagedTomcatServiceTest.java
Beware: this PR is still in POC state, don't merge this as is.
Motivation:
Introduce a way to setup TomcatService using existing Embedded Tomcat
instance.  possible usage can be found at [HERE](https://github.com/blmarket/spring-boot-armeria-demo/blob/master/src/main/java/com/linecorp/DemoApplication.java)
Modification:
Split TomcatServiceInvocationHandler into two classes,
introduced class is instantiated using configured hostname and
Connector, and provides ServiceInvocationHandler interface using those
values.
(TBD) I've left TomcatServiceInvocationHandler for
backward-compatibility. But as this class is not public, roles of the
class can be migrated into `TomcatServiceBuilder`, with little logical
changes.
(TBD) name of introduced class is not yet determined.
Result:
Easier …
=> Add connector based TomcatServiceInvocationHandler

pom.xml, src/main/java/com/linecorp/armeria/client/tracing/ClientTracingInterceptor.java, src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java, src/main/java/com/linecorp/armeria/client/tracing/HttpTracingRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/tracing/TracingRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/tracing/package-info.java, src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java, src/main/java/com/linecorp/armeria/server/tracing/HttpTracingServiceInvocationHandler.java, src/main/java/com/linecorp/armeria/server/tracing/ServerTracingInterceptor.java, src/main/java/com/linecorp/armeria/server/tracing/TracingServiceInvocationHandler.java, src/main/java/com/linecorp/armeria/server/tracing/package-info.java, src/test/java/com/linecorp/armeria/client/tracing/HttpTracingRemoteInvokerTest.java, src/test/java/com/linecorp/armeria/client/tracing/TracingRemoteInvokerTest.java, src/test/java/com/linecorp/armeria/common/tracing/HttpTracingTestBase.java, src/test/java/com/linecorp/armeria/common/tracing/TracingTestBase.java, src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceInvocationHandlerTest.java, src/test/java/com/linecorp/armeria/server/tracing/TracingServiceInvocationHandlerTest.java
Introduces distributed tracing capability to armeria clients/servers. This enables us to watch timing data among the whole armeria rpc chain. 
This feature depends on [brave](https://github.com/openzipkin/brave) distributed tracing library compatible with [zipkin](http://zipkin.io/).
```java
// Create a brave instance with service name, span collector, and sampling rate.
Brave brave = new Brave.Builder("FibClientMain")
.spanCollector(new ScribeSpanCollector("127.0.0.1", 9410))
.traceSampler(Sampler.create(0.01f))
.build();
FibService.Iface fibClient =
new ClientBuilder("tbinary+http://127.0.0.1:8080/thrift/fib")
.decorator(HttpTracingClient.decorator(brave))
.build(FibService.Iface.class);
```
```java
// Create a brave instance with service name, span collector, and sampling rate.
Brave …
```
=> distributed tracing for armeria

src/main/java/com/linecorp/armeria/common/util/Exceptions.java
I think that 2nd "!" of these should not be. These javadoc says, "log-if-not-isExpected", but the code is "nothing-if-not-isExpected".
**[Background]**
In some service, too many "Connection reset" exceptions like below are logged after version up the armeria (0.8.0.Final -> 0.9.0.Final).
It may be the effect of https://github.com/line/armeria/pull/105 (released in [0.9.0.Final](https://github.com/line/armeria/releases/tag/armeria-0.9.0.Final))
```
2016-03-03 18:10:36.424 WARN  nioEventLoopGroup-7-6 com.linecorp.armeria.server.HttpServerHandler:53 - [id: 0x648cec6b, L:/XX.XX.XX.XX:20012 - R:/YY.YY.YY.YY:30664] Unexpected exception:
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_66]
at …
```
=> Fix log skip condition

src/main/java/com/linecorp/armeria/client/RemoteInvokerOptions.java, src/main/java/com/linecorp/armeria/server/ServerBuilder.java
Motivation:
The current default maxFrameLength values for client and server are 10
MB and 1 MB respectively. Having different default values gives a user
surprises.
Modifications:
Use the same default maxFrameLength value (10 MB) for client and server
Result:
Fixes #118
=> Use the same default maxFrameLength for both sides

src/main/java/com/linecorp/armeria/client/ClientBuilder.java, src/main/java/com/linecorp/armeria/client/ClientInvocationHandler.java, src/main/java/com/linecorp/armeria/client/Clients.java, src/main/java/com/linecorp/armeria/client/DecoratingRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/HttpRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/RemoteInvoker.java, src/main/java/com/linecorp/armeria/client/RemoteInvokerFactory.java, src/main/java/com/linecorp/armeria/client/tracing/TracingRemoteInvoker.java, src/test/java/com/linecorp/armeria/client/tracing/TracingRemoteInvokerTest.java
Motivation:
EventLoop to perform the actual invocation is determined at the
HttpRemoteInvoker.invoke() method, which is the last moment right before
the invocation.
It means decorating RemoteInvokers does not have an access to the
EventLoop, nevertheless the EventLoop can be determined from the
beginning of the invocation.
A decorating RemoteInvoker with an access to an EventLoop could create
Future/Promise and schedule a task, which will be useful when building
an advanced decorator such as a circuit breaker.
Modifications:
- Add EventLoop parameter to RemoteInvoker.invoke()
- Determine the EventLoop to perform the invocation in
ClientInvocationHandler instead of in HttpRemoteInvoker
- Move HttpRemoteInvoker.eventLoop() to ClientInvocationHandler
- Reorder the methods in …
=> Make EventLoop available to RemoteInvoker.invoke()

src/main/java/com/linecorp/armeria/client/ClientInvocationHandler.java, src/main/java/com/linecorp/armeria/client/ClosedSessionException.java, src/main/java/com/linecorp/armeria/client/HttpRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java, src/main/java/com/linecorp/armeria/common/http/AbstractHttpToHttp2ConnectionHandler.java, src/main/java/com/linecorp/armeria/common/util/Exceptions.java, src/main/java/com/linecorp/armeria/server/Server.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceCodec.java
Motivation:
ClientInvocationHandler wraps an exception raised by
RemoteInvoker.invoke() with UndeclaredThrowableException if it is a
checked exception that's not listed in the method's 'throws' clause.
However, this behavioe is redundant because Java's proxy generator
(sun.misc.ProxyGenerator) already does that for us:
Modifications:
- Simplify exception handling code
- Refrain from using PlatformDependent wherever possible
Result:
Less code
=> Simplify exception handling in ClientInvocationHandler

pom.xml, src/main/java/com/linecorp/armeria/client/RemoteInvokerFactory.java, src/main/java/com/linecorp/armeria/common/ServiceInvocationContextAwareFuture.java, src/main/java/com/linecorp/armeria/common/util/NativeLibraries.java, src/main/java/com/linecorp/armeria/server/Server.java
- Upgrade to Netty 4.1.0.CR5
- Use epoll when running on linux-x86_64
- Use BoringSSL for SSL when running on linux-x86_64
- Use different event loop names for different transport types
- Use different event loop names for bosses and workers
- Log the availability of epoll and BoringSSL
=> Upgrade to Netty 4.1.0.CR5 / Use epoll and BoringSSL when running on linux-x86_64

src/main/java/com/linecorp/armeria/client/HttpConfigurator.java, src/main/java/com/linecorp/armeria/client/HttpRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/HttpSession.java, src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java, src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
Related issue: #69
Motivation:
When we keep an HTTP/2 connection long enough to handle more than 1G
requests, the stream ID will exceed Integer.MAX_VALUE. It's probably a
good idea for an Armeria client to close the connection before hitting
the limit.
Modifications:
- Add HttpSession that provides the operations related with session
management
- Replace the static methods in HttpSessionHandler with get() which
returns HttpSession that provides everything needed
- Do not return the channel to the pool if the number of the sent
requests exceeds a threshold
- Close the channel if the number of the sent requests exceeds a
threshold and there are no requests that await responses
Result:
- Fixes #69
=> Disconnect before HTTP/2 stream ID overflows

pom.xml, src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreaker.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerBuilder.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerConfig.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerMapping.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/EventCount.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/EventCounter.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/ExceptionFilter.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/FailFastException.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMapping.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounter.java, src/main/java/com/linecorp/armeria/client/circuitbreaker/package-info.java, src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerBuilderTest.java, src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java, src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRemoteInvokerTest.java, src/test/java/com/linecorp/armeria/client/circuitbreaker/EventCountTest.java, src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java, src/test/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounterTest.java
Provides a failure detection and fallback mechanism based of circuit breaker pattern.
```java
Iface helloClient = new ClientBuilder("tbinary+http://127.0.0.1:8080/hello")
.decorator(
CircuitBreakerClient.newDecorator(
new CircuitBreakerBuilder("hello").build()
)
)
.build(Iface.class);
```
You can specify a unit of failure detection from the following:
* per remote service (as shown in the example above)
* per method
* per remote host
* per remote host and method
```java
// Setup with per-method failure detection
AsyncIface helloClient = new ClientBuilder("tbinary+http://127.0.0.1:8080/hello")
.decorator(
CircuitBreakerClient.newPerMethodDecorator(
method -> new CircuitBreakerBuilder(method).build()
)
)
.build(AsyncIface.class);
```
Once a failure is detected, A `FailFastException` is …
=> circuit breaker for armeria

src/main/java/com/linecorp/armeria/client/HttpConfigurator.java, src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java, src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
Motivation:
Because HttpSessionHandler is added only after protocol negotiation is
complete, a message or an exception triggered before then has a chance
of hitting the tail of the pipeline. As a result, a user can see the
following messages from Netty:
> An exceptionCaught() event was fired, and it reached at the tail of
> the pipeline.
and:
> Discarded inbound message {} that reached at the tail of the pipeline.
Modifications:
- Refactor HttpSessionChannelFactory and HttpSessionHandler so that
HttpSessionHandler is always available as soon as the connection
attempt is successful
- Move protocol negotiation signal processing to HttpSessionHandler so
that HttpSessionChannelFactory focuses on the connection attempt
Result:
- No more warning messages which confuses a user
- Slightly cleaner …
=> Fix 'exceptionCaught/inbound message reached at the tail of the pipeline' warnings

src/test/java/com/linecorp/armeria/server/http/tomcat/UnmanagedTomcatServiceTest.java
Motivation:
UnmanagedTomcatServiceTest does not specify the base directory of the
Tomcat, which makes the Tomcat create an empty 'tomcat.8080' directory
under the project root directory. It could be created somewhere under
'/target' instead for less distraction.
Modifications:
- Set the baseDir of Tomcat explicitly
Result:
Cleaner build
=> Do not create 'tomcat.8080' directory under project root directory

src/main/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandler.java, src/main/java/com/linecorp/armeria/client/HttpConfigurator.java, src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/common/http/Http2GoAwayListener.java, src/main/java/com/linecorp/armeria/common/util/Exceptions.java, src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, src/main/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandler.java, src/main/java/com/linecorp/armeria/server/ServerInitializer.java
Motivation:
When a connection is closed before session protocol negotiation succeeds
or fails, the Promise of session creation is not notified immediately
but only after the session creation timeout. As a result, the
notification of session creation due to an unexpected disconnection can
take up to as long as connection timeout (3.2 seconds by default)
Also, we need to log more:
- the information about GOAWAY frames we sent and received
- the current session protocol when an unexpected exception occurred
Modifications:
- Try to reject the session creation promise when a connection has been
closed.
- Add Http2GoAwayListener and add it to both client and server
connections so that we have more information about GOAWAY frames we
send and receive.
- Log the current session protocol when …
=> Fix delayed notification of session creation failure and log GOAWAY frames

src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, src/main/java/com/linecorp/armeria/server/ServiceConfig.java, src/test/java/com/linecorp/armeria/server/http/HttpServiceTest.java
Motivation:
An HTTP/2 stream can be closed by various reasons, such as RST_STREAM
and GOAWAY frame. If Armeria server attempts to write a response to a
closed connection or a closed HTTP/2 stream, Netty's Http2Connection
will reject it with an unexpected exception, such as:
Http2Exception: Cannot create stream 1 since this endpoint has
received a GOAWAY frame with last stream id 0
Http2Exception: Request stream N is not correct for server
connection
Http2Exception: Request stream ODD_N is not correct for server
connection
Modifications:
- Make sure that the connection is still active and the HTTP/2 stream
associated with the response is still not closed
- Replace useHeadOfBlocking flag with http2conn field which becomes
non-null when upgraded to HTTP/2
- Remove redundant …
=> Do not attempt to send a response to a closed connection/stream

src/main/java/com/linecorp/armeria/common/http/AbstractHttpToHttp2ConnectionHandler.java, src/main/java/com/linecorp/armeria/common/http/Http2GoAwayListener.java, src/main/java/com/linecorp/armeria/common/util/Exceptions.java
Motivation:
An HTTP/2 GOAWAY frame with non-zero error code sometimes gives an empty
debugData, making it hard to determine the root cause of the error.
Modifications:
- Add the following information to debugData:
- the exact type of Http2Exception
- the original message of Http2Exception
- the exact type, message and stack trace of the cause of Http2Exception
- Add Exceptions.traceText() to stringify the stack trace of an
exception
- Fix incorrect Logger level check
Result:
We will have more information when we get an error GOAWAY frame.
=> Add more debug information to HTTP/2 GOAWAY frame

src/main/java/com/linecorp/armeria/server/Server.java
Motivation:
In a certain case where a Server fails to start up, Server.stop0() can
be invoked even before Server.gracefulShutdownHandler is set.
Modifications:
Do not use Optional for simplicity.
Result:
No more NPE
=> Fix NPE when Server startup fails

src/main/java/com/linecorp/armeria/server/Server.java, src/main/java/com/linecorp/armeria/server/http/tomcat/ArmeriaWebResourceRoot.java, src/main/java/com/linecorp/armeria/server/http/tomcat/JarSubsetResourceSet.java, src/main/java/com/linecorp/armeria/server/http/tomcat/ManagedTomcatServiceInvocationHandler.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceBuilder.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceConfig.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatUtil.java, src/test/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceTest.java
Motivation:
1) Tomcat does not allow us to use a JAR file whose extention is not
'.war' as a web application:
- https://github.com/apache/tomcat/blob/4166a2b96f482f8bf7b0024836dab53d3594710e/java/org/apache/catalina/webresources/StandardRoot.java#L722
2) When TomcatService is created via forClassPath(Class, String), the
service construction fails if the specified class is packaged in a .JAR
file. forClassPath(Class, String) currently requires the specified class
to exist in a directory, which is not always true.
Modifications:
- Replace Tomcat's StandardRoot with ArmeriaWebResourceRoot to accept
any JAR files
- Add JarSubsetResourceSet which allows a user to specify non-root web
application path in a JAR file
- Note that the upstream JarResourceSet is used unless specified
explicitly.
- …
=> Make Tomcat allow a .JAR file that contains a webapp

pom.xml, src/main/java/com/linecorp/armeria/client/RemoteInvokerFactory.java, src/main/java/com/linecorp/armeria/client/RemoteInvokerOption.java, src/main/java/com/linecorp/armeria/client/RemoteInvokerOptions.java, src/test/java/com/linecorp/armeria/client/http/SimpleHttpClientIntegrationTest.java, src/test/java/com/linecorp/armeria/client/http/SimpleHttpClientSniTest.java, src/test/java/com/linecorp/armeria/server/AbstractServerTest.java, src/test/java/com/linecorp/armeria/server/SniServerTest.java
- Add SniServerTest and SimpleHttpClientSniTest to test Armeria's SNI
support
- Improve HTTPS support of AbstractServerTest by adding a few more
utility methods
- Add RemoteInvokerOption.ADDRESS_RESOLVER_GROUP so that we don't need
to query DNS servers to test client-side SNI support
- Upgrade Apache HttpClient to 4.5.2 to use setSSLNameVerifier()
=> Add test cases for SNI support

src/main/java/com/linecorp/armeria/client/HttpConfigurator.java, src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/client/RemoteInvokerOption.java, src/main/java/com/linecorp/armeria/client/RemoteInvokerOptions.java, src/main/java/com/linecorp/armeria/server/ServerInitializer.java, src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
Related: #142
Motivation:
Armeria client currently sends a 'HEAD / HTTP/1.1' request to issue a
protocol upgrade, as recommended by the RFC, but it can cause heavy load
on the server side if the service bound at / does not implement HEAD
method optimally. When many Armeria clients creates a lot of connections
concurrently, the server might not respond to the upgrade request in a
timely manner.
Modifications:
- Add RemoteInvokerOption.USE_HTTP2_PREFACE which is true by default
- When set to true, Armeria client uses 'PRI * HTTP/2.0' preface
string instead of the old 'HEAD / HTTP/1.1' request to upgrade from
H1C to H2C.
- A user can specify a system property to change the default value of
the USE_HTTP2_PREFACE option.
- Implement the H1C-to-H2C upgrade that uses the HTTP/2 preface string, …
=> Use the HTTP/2 preface string for H1C-to-H2C upgrade

src/main/java/com/linecorp/armeria/client/metrics/MetricCollectingClient.java, src/main/java/com/linecorp/armeria/common/metrics/DropwizardMetricConsumer.java, src/main/java/com/linecorp/armeria/server/metrics/MetricCollectingService.java, src/test/java/com/linecorp/armeria/server/metrics/DropwizardMetricsIntegrationTest.java
Motivation:
There's no way for a user to create a metric entry with different prefix
than 'client' or 'server' when using the newDropwizardDecorator()
methods in MetricCollectingClient/Service.
Modifications:
- Remove the hard-coded 'client' and 'server' prefix.
- Rename the parameter 'serviceName' to 'metricName' and let users use
MetricRegistry.name()
Result:
More control to the users
=> Give full control over the metric name of Dropwizard Metrics integration

src/main/java/com/linecorp/armeria/client/RemoteInvokerFactory.java
Related: https://github.com/netty/netty/issues/5179
Motivation:
When you attempt to make a lot of connection attempts to the same target
host at the same time and our DNS resolver does not have a record for it
in the cache, the DNS resolver will send as many DNS queries as the
number of connection attempts.
As a result, DNS server will reject or drop the requests, making the
name resolution attempt fail.
Modifications:
Keep the list of name resolution queries and subscribe to the future of
the matching query instead of sending a duplicate query.
Result:
Duplicate DNS queries are gone.
=> Do not send duplicate DNS queries when the same one is in progress

src/main/resources/com/linecorp/armeria/server/docs/assets/js/armeria.js
=> Fix the broken links for classes in DocService

src/main/java/com/linecorp/armeria/client/HttpConfigurator.java, src/main/java/com/linecorp/armeria/client/HttpRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/HttpSession.java, src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java, src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/client/RemoteInvokerOptions.java, src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, src/test/java/com/linecorp/armeria/server/ServerTest.java
Motivation:
1)
The old Armeria server does not handle an HTTP request whose path is '*'
correctly. As a result, sending an HTTP/2 connection preface string will
make the server close the connection immediately.
HttpConfigurator.DowngradeHandler does not handle the case where the
connection is closed before the first 4 bytes are received, and thus it
fails to downgrade to H1C.
2)
Armeria server raises an unexpected exception when the path of an HTTP
request is not an absolute path rather than responding with 400 Bad
Request.
Also, it doesn't handle 'OPTIONS * HTTP/1.1' requests because of the
same reason.
Modifications:
- Make sure DowngradeHandler switches to H1C when less than 4 bytes were
received before disconnection.
- Use 'HEAD / HTTP/1.1' again as the default upgrade mechanism for …
=> Fix backward compatibility with old Armeria servers

pom.xml, src/main/java/com/linecorp/armeria/server/ExecutorBasedExecutorService.java, src/main/java/com/linecorp/armeria/server/InterminableExecutorService.java, src/main/java/com/linecorp/armeria/server/ServerConfig.java, src/main/java/com/linecorp/armeria/server/http/jetty/ArmeriaConnector.java, src/main/java/com/linecorp/armeria/server/http/jetty/JettyService.java, src/main/java/com/linecorp/armeria/server/http/jetty/JettyServiceBuilder.java, src/main/java/com/linecorp/armeria/server/http/jetty/JettyServiceConfig.java, src/main/java/com/linecorp/armeria/server/http/jetty/JettyServiceInvocationHandler.java, src/main/java/com/linecorp/armeria/server/http/jetty/package-info.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceBuilder.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceConfig.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java, src/test/java/com/linecorp/armeria/server/http/WebAppContainerTest.java, src/test/java/com/linecorp/armeria/server/http/jetty/JettyServiceTest.java, src/test/java/com/linecorp/armeria/server/http/jetty/UnmanagedJettyServiceTest.java, src/test/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceTest.java
- Add JettyService and its builder
- Add WebAppContainerTest and make TomcatServiceTest and
JettyServiceTest extend it
- Make ServerConfig.blockingTaskExecutor() return ExecutorService
instead of Executor, because many components including Jetty requires
an ExecutorService which provides more useful operations such as
submit()
- Add ExecutorBasedExecutorService
- Add InterminableExecutorService
=> Add JettyService

pom.xml, src/main/java/com/linecorp/armeria/server/docs/ClassInfo.java, src/main/java/com/linecorp/armeria/server/docs/EnumInfo.java, src/main/java/com/linecorp/armeria/server/docs/ExceptionInfo.java, src/main/java/com/linecorp/armeria/server/docs/FieldInfo.java, src/main/java/com/linecorp/armeria/server/docs/FunctionInfo.java, src/main/java/com/linecorp/armeria/server/docs/ListInfo.java, src/main/java/com/linecorp/armeria/server/docs/MapInfo.java, src/main/java/com/linecorp/armeria/server/docs/ServiceInfo.java, src/main/java/com/linecorp/armeria/server/docs/SetInfo.java, src/main/java/com/linecorp/armeria/server/docs/StructInfo.java, src/main/java/com/linecorp/armeria/server/docs/ThriftDocString.java, src/main/java/com/linecorp/armeria/server/docs/TypeInfo.java, src/test/java/com/linecorp/armeria/server/docs/ThriftDocStringTest.java, src/test/resources/META-INF/armeria/thrift/ThriftTest.json, src/test/resources/META-INF/armeria/thrift/ThriftTest.thrift, src/test/resources/META-INF/armeria/thrift/cassandra.json
Motivation:
Current DocService's json output doesn't contain JavaDoc string.
And, the latest Thrift compiler support `--gen json` option and it contains doc strings.
So, we can merge doc strings to DocService's output using json.
This commit is first part of adding docstring to DocService.
Modifications:
Read JSONs generated by Thrift if exists and build `*Info` models.
Result:
DocService's JSON output contains doc strings.
=> Add doc strings to DocService's json output

src/main/java/com/linecorp/armeria/server/Server.java, src/main/java/com/linecorp/armeria/server/ServerConfig.java, src/main/java/com/linecorp/armeria/server/VirtualHost.java, src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java, src/main/java/com/linecorp/armeria/server/http/jetty/ArmeriaThreadPool.java, src/main/java/com/linecorp/armeria/server/http/jetty/JettyService.java, src/main/java/com/linecorp/armeria/server/http/jetty/JettyServiceBuilder.java, src/main/java/com/linecorp/armeria/server/http/jetty/JettyServiceConfig.java, src/main/java/com/linecorp/armeria/server/http/jetty/JettyServiceInvocationHandler.java, src/main/java/com/linecorp/armeria/server/http/tomcat/ManagedConnectorFactory.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceBuilder.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceConfig.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java, src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java, src/test/java/com/linecorp/armeria/server/http/WebAppContainerTest.java, src/test/java/com/linecorp/armeria/server/http/jetty/JettyServiceTest.java, src/test/java/com/linecorp/armeria/server/http/jetty/UnmanagedJettyServiceTest.java, src/test/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceTest.java, src/test/java/com/linecorp/armeria/server/http/tomcat/UnmanagedTomcatServiceTest.java
- Add VirtualHost.defaultHostname
- Unless specified, it is determined from the user-specified hostname
pattern or the current machine's hostname
- Add Server.defaultHostname() which is a shortcut to
config().defaultVirtualHost().defaultHostname()
- Use Server.defaultHostname() if a user does not specify hostname when
creating JettyService or TomcatService
- Add missing configuration options to JettyServiceBuilder
- Merge TomcatServiceInvocationHandler and
ManagedTomcatServiceInvocationHandler
- Move the part related with the managed one to
ManagedConnectorFactory
- Call Tomcat/Jetty Server.destroy() when it is managed and stopped.
- Fix UnsupportedOperationException in ThreadPoolExecutor.stop() when
embedded Jetty is stopped
- Add ArmeriaThreadPool
- Fix Tomcat LifeCycleExceptions while …
=> Add {VirtualHost, Server}.defaultHostname()

src/main/java/com/linecorp/armeria/client/metrics/MetricCollectingClientCodec.java, src/main/java/com/linecorp/armeria/common/metrics/DropwizardMetricConsumer.java, src/main/java/com/linecorp/armeria/common/metrics/DropwizardRequestMetrics.java, src/main/java/com/linecorp/armeria/common/metrics/MetricConsumer.java, src/main/java/com/linecorp/armeria/server/metrics/MetricCollectingServiceCodec.java, src/test/java/com/linecorp/armeria/server/metrics/MetricCollectingServiceCodecTest.java, src/test/java/com/linecorp/armeria/server/metrics/MetricConsumerTest.java
Motivation:
Currently there are metrics like success and failures, but it is important to
monitor how many requests are in progress to figure out each API's status.
Modifications:
- Add MetricConsumer.invocationStart() to record requests' starting point
- Use the method on Client and Service codecs
Result:
Users can monitor each API's processingRequests counter to check its current
status.
=> Record each API's processing requests as a metric for monitoring

src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java, src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, src/test/resources/logback-test.xml
Motivation:
We log too much when running tests and Travis truncates the log file
when browsing it online. We can download the full raw log file, but it's
not as convenient as before
Modifications:
- Disable LoggingClient/Service, KeyedChannelPoolLoggingHandler by
default
- Simplify pre-upgrade request logging
- Clear stack trace of an expected exceptions in tests
Result:
Significantly reduced log file size
=> Reduce the amount of log messages while testing

src/main/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandler.java, src/main/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandler.java
Motivation:
HttpClient/ServerIdleTimeoutHandler currently propagates an
IdleStateEvent unless it triggers a request/response timeout.
However, there's no handler in Armeria that has interest in an
IdleStateEvent.
Also, HttpServerHandler logs an IdleStateEvent as an unexpected user
event, which is misleading.
Modifications:
- HttpClient/ServerIdleTimeoutHandler does not propagate an
IdleStateEvent anymore
Result:
No more misleading 'unexpected user event' message
=> Do not propagate IdleStateEvent to suppress misleading 'unexpected user event' message

.travis.yml, .travis/clean-m2-repo.sh, .travis/install-jdk.sh
- Download the Oracle JDK 8u92 from the official site
- Untar the downloaded JDK tarball into `~/.jdk/<version>`
- Create a symlink at `~/.jdk/default` for the untar'd directory
- Cache `~/.jdk` if everything worked as expected
=> Use the newer Oracle JDK in Travis CI

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceBuilder.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceConfig.java
Motivation:
A LifecycleException can occur while stopping a TomcatService if:
- a user bound more than one TomcatService built by TomcatServiceBuilder
- and used the default Realm (NullRealm)
When a TomcatService stops, the NullRealm will be stopped and destroyed.
After then, when another TomcatService stops, it will attempt to stop
the same NullRealm, which will fail with LifecycleException because it
has been destroyed by the first TomcatService.
Modifications:
Create a new NullRealm instead of using a singleton
Result:
No more LifecycleException
Related stack trace:
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardService[TomcatServiceTest-JAR]]
at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:228)
at …
=> Fix LifecycleException when stopping Tomcat

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java
Motivation:
TomcatService(InvocationHandler) logs the following (or similar) message
when starting, stopping and destroying embedded Tomcat:
Starting an embedded Tomcat: Server[-2]
.. which is not useful to identify the Server instances when a user is
using more than one Servers.
Modifications:
- Add TomcatService.toString(Server) and use it wherever a Server is
stringified
Result:
Better-looking log message:
Starting an embedded Tomcat: (serviceName: TomcatServiceTest,
catalinaBase: /tmp/tomcat-armeria.7377474203691902870)
=> Log meaningful identifier of embedded Tomcat

src/main/java/com/linecorp/armeria/server/docs/Specification.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftService.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceCodec.java
Motivation:
A Thrift service implementation may not implement .Iface/.AsyncIface
interfaces directly when the service implementation implements another
interface or abstract class that extends or implements
.Iface/.AsyncIface. For example:
public abstract class AbstractMyService implements Service.Iface {}
public class MyService extends AbstractMyService { ... }
Trying to get the list of implemented interfaces via
MyService.class.getInterfaces() will not return Service.Iface, leading
DocService to think MyService is not a Thrift service implementation.
This issue has been fixed in 665e6415b98dc3f7a1a34f2fb90b64e5653478cc
for ThriftService previously, but the fix did not cover DocService.
Modifications:
- Add ThriftService.interfaces() that returns all .Iface/.AsyncIface
interfaces a …
=> Fix broken interface discovery for Thrift services in DocService

src/main/java/com/linecorp/armeria/common/thrift/text/TTextProtocol.java
Motivation:
ThriftServiceCodec keeps the TProtocol implementations in a thread-local
cache to avoid repetitive instantiation of TProtocol instances.
TTextProtocol.reset() does not re-initializes its writer and context
stack, which makes it possible for a previously failed call corrupts the
state of TTextProtocol.
Modifications:
TTextProtocol.reset() now clears the writer and context stack and adds
the initial stack elements.
Result:
A previously failed TText Thrift call does not corrupt the state of the
codec
=> Fix incomplete TTextProtocol.reset()

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java
Motivation:
A user was able to use TomcatService with Tomcat 7 by instantiating a
TomcatService via the forConnector() factory method.
However, it does not work anymore because e06096dd115d4a7ebf7f28f6315f2ddec05c50b2
introduced the call to the method that does not exist in Tomcat 7 but
only in Tomcat 8+.
Modifications:
Do not call Server.getCatalinaBase() if the current Tomcat version is
less than 8.
Result:
A user can create a TomcatService with a Tomcat 7 Connector again.
=> Fix NoSuchMethodError when using Tomcat 7 Connector

src/main/java/com/linecorp/armeria/server/docs/ThriftDocString.java
Motivation:
When com.linecorp.armeria.thrift.jsonDir doesn't exist, WARN log will occured.
`12:04:57.463 [WARN ](o.r.Reflections) [main] given scan urls are empty. set urls in the configuration`
Modifications:
Check jsonDir before scan.
Result:
DocService will not warn when jsonDir doesn't exist.
=> Fix Reflections' WARN log when jsonDir doesn't exist.

src/main/resources/com/linecorp/armeria/server/docs/assets/css/armeria.css, src/main/resources/com/linecorp/armeria/server/docs/assets/js/armeria.js, src/main/resources/com/linecorp/armeria/server/docs/index.html, src/test/resources/META-INF/armeria/thrift/cassandra.json
Motivation:
Current DocService's html view doesn't contain JavaDoc string.
This is second part of adding docstring to DocService.
Modifications:
Render DocString to html view if it exists.
Result:
DocService's html output contains DocString.
=> Add DocService's docString to html view

src/main/java/com/linecorp/armeria/server/docs/FieldInfo.java, src/main/java/com/linecorp/armeria/server/docs/ListInfo.java, src/main/java/com/linecorp/armeria/server/docs/MapInfo.java, src/main/java/com/linecorp/armeria/server/docs/SetInfo.java, src/main/java/com/linecorp/armeria/server/docs/StructInfo.java, src/main/java/com/linecorp/armeria/server/docs/ThriftDocString.java, src/main/java/com/linecorp/armeria/server/docs/TypeInfo.java, src/test/java/com/linecorp/armeria/server/docs/ThriftDocStringTest.java, src/test/resources/META-INF/armeria/thrift/cassandra.json, src/test/thrift/cassandra.thrift
* functions: Supports A style only.
* structs: Supports A style only.
* functions: Supports A style only.
* structs: **Supports both A and B styles**.
```
/**
A TokenRange describes part of the Cassandra ring, it is a mapping from a range to
endpoints responsible for that range.
@param start_token The first token in the range
@param end_token The last token in the range
@param endpoints The endpoints responsible for the range (listed by their configured listen_address)
@param rpc_endpoints The endpoints responsible for the range (listed by their configured rpc_address)
*/
struct TokenRange {
1: required string start_token,
2: required string end_token,
3: required list<string> endpoints,
4: optional list<string> rpc_endpoints
5: optional list<EndpointDetails> endpoint_details,
}
```
``` …
```
=> Fix #186 DocService Struct field docstrings are not reliably included

pom.xml
.. and remove dependency classifier which includes Windows and macOS
binaries.
=> Upgrade tcnative-boringssl to the latest version

src/site/sphinx/_static/overrides.css, src/site/sphinx/_templates/versions.html
We recently create a public Slack group:
- https://line-armeria.slack.com/
We also deployed Slackin at Heroku for simpler signup:
- https://slackin-line-armeria.herokuapp.com/
This commit adds the Slack invitation badge that publishes our public
Slack group in our web site.
=> Add the Slack invitation badge

pom.xml, src/main/java/com/linecorp/armeria/client/HttpRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java, src/main/java/com/linecorp/armeria/client/RemoteInvokerFactory.java, src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java, src/main/java/com/linecorp/armeria/client/tracing/HttpTracingRemoteInvoker.java, src/main/java/com/linecorp/armeria/client/tracing/TracingRemoteInvoker.java, src/main/java/com/linecorp/armeria/common/ServiceInvocationContextAwareEventLoop.java, src/main/java/com/linecorp/armeria/server/Server.java, src/main/java/com/linecorp/armeria/server/ServerConfig.java, src/main/java/com/linecorp/armeria/server/VirtualHost.java, src/main/java/com/linecorp/armeria/server/tracing/HttpTracingServiceInvocationHandler.java, src/test/java/com/linecorp/armeria/common/tracing/HttpTracingTestBase.java, src/test/java/com/linecorp/armeria/server/tracing/TracingServiceInvocationHandlerTest.java
- Brave 3.9.0
- Jackson 2.7.5
- Jetty 9.3.10
- Jetty ALPN agent 2.0.3
- Netty 4.1.2.Final
- Netty TCNative (BoringSSL-static) 1.1.33.Fork18
- Tomcat 8.0.36
- Related changes:
- Remove the references to the deprecated/removed APIs
=> Upgrade the dependencies to their latest stable versions

src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceCodec.java
Motivation:
When a ServiceCodec.decodeRequest() raises an exception,
HttpServerHandler will close the connection immediately without sending
anything. Instead, the server should send a '400 Bad Request' response.
Modifications:
- HttpServerHandler now catches an exception raised by
ServiceCodec.decodeRequest() and responds with a '400 Bad Request'
response.
- ThriftServiceCodec.decodeRequest() now catches an exception raised by
TProtocol.readMessageBegin() and returns a failed DecoderResult
instead of raising an exception.
Result:
- Armeria server sends a 400 Bad Request even if
ServiceCodec.decodeRequest() raises an exception.
- ThriftServiceCodec.decodeRequest() deals with a bad request better.
=> Do not produce an empty response when ServiceCodec raises an exception

pom.xml
- Netty 4.1.3
- Netty TCNative (BoringSSL static) 1.1.33.Fork19
- Jetty ALPN API 1.1.3.v20150715
- jMock 2.8.2
- json-unit 1.13.0
- Maven plugins
- os-maven-plugin 1.5.0
- build-helper-maven-plugin 1.11
- maven-compiler-plugin 3.5.1
- maven-surefire-plugin 2.19.1
- maven-jar-plugin 3.0.2
- maven-source-plugin 3.0.1
- maven-site-plugin 3.5.1
- maven-project-info-reports-plugin 2.9
- maven-javadoc-plugin 2.10.4
=> Update dependencies to their latest stable versions

pom.xml, src/build/tomcat80-compat.groovy, src/main/java/com/linecorp/armeria/server/http/tomcat/ArmeriaWebResourceRoot.java, src/main/java/com/linecorp/armeria/server/http/tomcat/ManagedConnectorFactory.java, src/main/java/com/linecorp/armeria/server/http/tomcat/Tomcat80ProtocolHandler.java, src/main/java/com/linecorp/armeria/server/http/tomcat/Tomcat85ProtocolHandler.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceInvocationHandler.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatUtil.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatVersion.java, src/site/sphinx/setup-gradle.rst, src/site/sphinx/setup-maven.rst
Motivation:
8.5.4 is the latest stable Tomcat version and Armeria's TomcatService does not
work with it.
Modifications:
- Replace TomcatProtocolHandler into two:
- Tomcat80ProtocolHandler for Tomcat 7.5-8.0
- Tomcat85ProtocolHandler for Tomcat 8.5
- Add the Groovy script that removes the ProtocolHandler methods newly
added in 8.5 from Tomcat80ProtocolHandler so that it does not have the
classes that do not exist in Tomcat 7.5-8.0 in method signatures
- Replace the direct Service.getContainer() calls with
TomcatUtil.engine(Service) due to its method signature difference
between 8.0 and 8.5
- Adapt to Tomcat's InputBuffer and OutputBuffer had signature changes
- Move the Tomcat version detection logic to TomcatVersion
- Fix an assertion error which occurs when ArmeriaWebResourceRoot is
used …
=> Make TomcatService support Tomcat 8.5

pom.xml, src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java, src/main/java/com/linecorp/armeria/common/http/HttpHeaders.java
- Netty 4.1.4.Final
- Jackson 2.7.6
- Jetty 9.3.11
- Jetty ALPN agent 2.0.4
- Brave 3.9.1
- AssertJ 3.5.2
- build-helper-maven-plugin 3.12
- Fix Javadoc errors
- Fix RejectedExcutionException log messages
=> Upgrade dependencies and fix build issues

pom.xml
Allows tests to run from directories with spaces (common on Windows).
=> Add quotes to javaagent path.

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java
Tomcat (or maybe spring) uses server port, not local port, for things like returning a port number to a client (e.g., when returning Location headers for 302 redirects).
Without setting server port, it is defaulted to 80, so http://localhost:9000/ would try to redirect to http://localhost/foo, not http://localhost:9000/foo
I'm not too sure on this, but from my reading here
http://stackoverflow.com/questions/2184286/difference-between-getlocalport-and-getserverport-in-servlets
the only time serverPort and localPort would be different is if using apache with tomcat's native AJP java protocol, not http proxying (I'm not aware of any proxy http header that transmits a port number). Since this is rare nowadays, forcing local and server port to be the same seems fine, though a followup could …
=> Set serverPort of coyote request in addition to local port.

src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
Motivation:
DefaultServiceRequestContext does not set maxRequestLength and
requestTimeoutMillis to their default values retrieved from
ServerConfig.
Modifications:
- Initialize maxRequestLength and requestTimeoutMillis properly
Result:
Configured default settings are respected.
=> Fix a bug where some server-side default settings are not applied

src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java, src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java, src/test/java/com/linecorp/armeria/server/http/WebAppContainerTest.java, src/test/resources/tomcat_service/addrs_and_ports.jsp
I realized that the previous fix wasn't really a fix, and that my intuition of headers not including port information was wrong - of course the Host header existed.
Found the code in tomcat that populates serverName/port by host header, so mimicing it here was the correct solution.
https://github.com/apache/tomcat/blob/trunk/java/org/apache/coyote/http11/Http11Processor.java#L1670
=> Use Host header to populate serverName and serverPort, like Tomcat does.

src/main/java/com/linecorp/armeria/common/http/DefaultAggregatedHttpMessage.java
Will make it easier to, for example, verify in mocks. Since this is aggregated, not streamed, it doesn't have the semantic issues that HttpRequest does.
=> Add equals/hashcode to DefaultAggregatedHttpMessage.

src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java, src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java, src/main/java/com/linecorp/armeria/client/UserClient.java, src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java, src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java, src/main/java/com/linecorp/armeria/common/RequestContext.java, src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java, src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java, src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java, src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java, src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, src/main/java/com/linecorp/armeria/server/thrift/ThriftCallService.java, src/main/java/com/linecorp/armeria/server/tracing/AbstractTracingService.java, src/test/java/com/linecorp/armeria/common/RequestContextTest.java, src/test/java/com/linecorp/armeria/it/logging/HttpTracingIntegrationTest.java, src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Motivation:
We currently use RequestContext.push(..) to propagate a RequestContext
to a non-I/O thread or to replace the current context with another.
When propagating a RequestContext a non-I/O thread, the onEnter and
onExit callbacks must be invoked, while they should not be invoked when
replacing a context.
RequestContext.push(...) currently never invokes the callbacks, which
can lead to inconsistent state transition between threads.
Modifications:
- Modify RequestContext.push() so that the caller can choose to call the
callbacks, where the default behavior is to call the callback
- Add RequestContext.invokeOnEnter/ExitCallbacks()
- Reorganize the type hierarchy of RequestContext and its subtypes
- Split AbstractRequestContext into:
- AbstractRequestContext
- NonWrappingRequestContext …
=> Fix RequestContext propagation and callback invocation

src/main/java/com/linecorp/armeria/client/tracing/AbstractTracingClient.java, src/main/java/com/linecorp/armeria/server/tracing/AbstractTracingService.java, src/test/java/com/linecorp/armeria/it/logging/HttpTracingIntegrationTest.java
Motivation:
Pre-0.21 used a Thrift method name as Zipkin span name, but 0.21 always
uses HTTP method name.
Modifications:
- Use RpcRequest.method() as Zipkin span name if available via
RequestLog
Result:
More conprehensive and Backward-compatible behavior
=> Use RpcRequest.method() as Zipkin span name

pom.xml, src/main/java/com/linecorp/armeria/client/RemoteInvokerFactory.java
Motivation:
According to the Oracle documentation:
> java.net.preferIPv4Stack (default: false)
>
> If IPv6 is available on the operating system, the underlying native
> socket will be an IPv6 socket. This allows Java applications to
> connect to, and accept connections from, both IPv4 and IPv6 hosts.
>
> If an application has a preference to only use IPv4 sockets, then
> this property can be set to true. The implication is that the
> application will not be able to communicate with IPv6 hosts.
which means, if DnsNameResolver returns an IPv6 address, a user (or
Netty) will not be able to connect to it.
Modifications:
- Disable IPv6 DNS queries when -Djava.net.preferIPv4Stack=true is set
Result:
No more intermittent connection attempt failure due to IPv6 addresses in
an IPv4-only …
=> Do not send an AAAA DNS query when -Djava.net.preferIPv4Stack=true (0.20)

src/main/java/com/linecorp/armeria/client/NonDecoratingClientFactory.java
Motivation:
According to the Oracle documentation:
> java.net.preferIPv4Stack (default: false)
>
> If IPv6 is available on the operating system, the underlying native
> socket will be an IPv6 socket. This allows Java applications to
> connect to, and accept connections from, both IPv4 and IPv6 hosts.
>
> If an application has a preference to only use IPv4 sockets, then
> this property can be set to true. The implication is that the
> application will not be able to communicate with IPv6 hosts.
which means, if DnsNameResolver returns an IPv6 address, a user (or
Netty) will not be able to connect to it.
Modifications:
- Disable IPv6 DNS queries when -Djava.net.preferIPv4Stack=true is set
Result:
No more intermittent connection attempt failure due to IPv6 addresses in
an IPv4-only …
=> Do not send an AAAA DNS query when -Djava.net.preferIPv4Stack=true (0.21)

src/main/java/com/linecorp/armeria/client/http/DefaultSimpleHttpClient.java
Motivation:
DefaultSimpleHttpClient did not used query and fragment from original
URI from request.
Modifications:
- Build string from path, query and fragment in original URI so query
and fragment are not removed.
Result:
Proper request while using `SimpleHttpClient`
=> Fix query and fragment removed from request

src/main/java/com/linecorp/armeria/client/http/Http1ResponseDecoder.java, src/main/java/com/linecorp/armeria/client/http/Http2ResponseDecoder.java, src/main/java/com/linecorp/armeria/client/http/HttpRequestSubscriber.java, src/main/java/com/linecorp/armeria/client/http/HttpResponseDecoder.java, src/main/java/com/linecorp/armeria/client/http/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/common/http/HttpRequest.java, src/main/java/com/linecorp/armeria/common/reactivestreams/PublisherWithCloseFuture.java, src/main/java/com/linecorp/armeria/common/reactivestreams/QueueBasedPublisher.java, src/main/java/com/linecorp/armeria/common/reactivestreams/RichPublisher.java, src/main/java/com/linecorp/armeria/internal/http/Http1ObjectEncoder.java, src/test/java/com/linecorp/armeria/client/http/HttpClientIntegrationTest.java
Motivation:
Even if an Armeria HttpClient finishes sending a request, its response
timeout is not scheduled until the first response header is received,
which is not correct.
Modifications:
- Make HttpResponseWrapper.scheduleTimeout() idempotent
- Call HttpResponseWrapper.scheduleTimeout() even for informational
headers
- Call HttpResponseWrapper.scheduleTimeout() if finished sending the
request
Result:
Correct response timeout behavior
Motivation:
When a user sends a GET/HEAD/DELETE/TRACE request which is supposed to
have empty content, Armeria sets the 'transfer-encoding: chunked' header
followed by a zero-length chunk.
It is not strictly prohibited by HTTP/1.1 to send such a request, it is
not desirable to do so and some servers do not accept it.
Modifications:
- Assume empty content …
=> Fix response timeout & Do not send a GET request with the transfer-encoding header

src/main/java/com/linecorp/armeria/common/http/DeferredHttpResponse.java, src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java, src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
Motivation:
Sometimes you cannot prepare your HttpResponse or StreamMessage instance
when returning from Service.serve() or Client.execute(). It will be
useful to have a placeholder StreamMessage implementation whose stream
is actually delegated from another StreamMessage.
Modifications:
- Add DeferredStreamMessage and DeferredHttpRequest
Result:
Easier to write a Service or a Client that delays its execution.
=> Add DeferredStreamMessage and DeferredHttpResponse

src/main/java/com/linecorp/armeria/server/docs/DocService.java, src/main/java/com/linecorp/armeria/server/docs/ServiceInfo.java, src/main/java/com/linecorp/armeria/server/docs/Specification.java, src/main/resources/com/linecorp/armeria/server/docs/assets/css/armeria.css, src/main/resources/com/linecorp/armeria/server/docs/assets/js/armeria.js, src/main/resources/com/linecorp/armeria/server/docs/index.html, src/test/java/com/linecorp/armeria/server/docs/DocServiceTest.java, src/test/java/com/linecorp/armeria/server/docs/ServiceInfoTest.java, src/test/java/com/linecorp/armeria/server/docs/SpecificationTest.java
Motivation:
Sometimes a service can use additional HTTP Headers when processing requests, but it is not possible to do that with the current DocService.
Modifications:
* Add an area in DocService to add additional HTTP Headers when calling APIs from DocService
* Make DocService take service-to-sampleHttpHeaders from its constructor
=> Add an area to send additional HTTP Headers when requesting from DocService

src/main/java/com/linecorp/armeria/client/SessionOption.java, src/main/java/com/linecorp/armeria/client/SessionOptions.java, src/main/java/com/linecorp/armeria/client/http/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java, src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClient.java, src/main/java/com/linecorp/armeria/client/limit/package-info.java, src/main/java/com/linecorp/armeria/common/http/DeferredHttpResponse.java, src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java, src/main/java/com/linecorp/armeria/common/stream/NoopSubscriber.java, src/test/java/com/linecorp/armeria/client/SessionOptionsTest.java, src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClientTest.java, src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
Motivation:
It is often useful to limit the concurrent number of active requests.
Modifications:
- Add ConcurrencyLimitingClient and ConcurrencyLimitingHttpClient with
maxConcurrency and timeout settings
- Add DeferredStreamMessage.close()
- Remove SessionOption.MAX_CONCURRENCY
- Abort the client HTTP request if its response has been closed
already
- Add NoopSubscriber for easier testing
Result:
Implemented MAX_CONCURRENCY option using a decorator.
=> Add ConcurrencyLimiting(Http)Client

src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java, src/main/java/com/linecorp/armeria/server/DecoratingService.java, src/main/java/com/linecorp/armeria/server/http/encoding/HttpEncodedResponse.java, src/main/java/com/linecorp/armeria/server/http/encoding/HttpEncoders.java, src/main/java/com/linecorp/armeria/server/http/encoding/HttpEncodingService.java, src/main/java/com/linecorp/armeria/server/http/encoding/HttpEncodingType.java, src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java, src/test/java/com/linecorp/armeria/server/http/encoding/HttpEncodersTest.java
When enabled, the server will look for the Accept-Encoding header from a client and respect it if set to gzip or deflate.
Encoding doesn't happen if
1) The user is publishing a response with Content-Encoding set. It's presumed the user has encoded the content themselves and we won't reencode.
2) Not part of accepted media types
3) The response has a small fixed content-length (e.g., not using chunked / framed encoding). For larger ones, we switch to chunked encoding and do the compression for a hopefully larger return.
Miscellanous:
- Fix a docstring
=> Add support for HTTP encoding server responses.

src/main/java/com/linecorp/armeria/client/http/Http2ResponseDecoder.java, src/main/java/com/linecorp/armeria/client/http/HttpClientPipelineConfigurator.java, src/main/java/com/linecorp/armeria/client/http/HttpResponseDecoder.java, src/main/java/com/linecorp/armeria/client/http/HttpSessionHandler.java, src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, src/main/java/com/linecorp/armeria/server/http/DecodedHttpRequest.java, src/main/java/com/linecorp/armeria/server/http/Http1RequestDecoder.java, src/main/java/com/linecorp/armeria/server/http/Http2RequestDecoder.java, src/main/java/com/linecorp/armeria/server/http/HttpServerPipelineConfigurator.java, src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java
Motivation:
When there is no service that matches the request path,
HttpServerHandler does not initialize a DecodedHttpRequest with a
ServiceRequestContext because it cannot create a context for a
non-existent service. This leaves DecodedHttpRequest.ctx to be null, and
attempting to access it may result in NPE.
Modification:
- Use defaultMaxRequestLength when DecodedHttpRequest.ctx is not
available
- Disallow sending beyond defaultMaxRequestLength if the server
responded already on a request to a non-existent service
- Ignore an empty HTTP/2 DATA frame so that the Subscriber always gets a
non-empty HttpData
- Close the stream instead of sending a GOAWAY frame when a client sends
too large content, so that other streams are not interrupted
- Do not send a GOAWAY frame when received the …
=> Fix potential NPE and missing maxRequestLength enforcement

src/main/java/com/linecorp/armeria/common/http/AggregatedHttpMessage.java, src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java, src/test/java/com/linecorp/armeria/server/http/healthcheck/HttpHealthCheckServiceTest.java
Motivation:
1. We found a problem where HttpHealthCheckService sends a chunked
response rather than a non-chunked one with 'content-length' header.
It turned out that AggregatedHttpMessage.of() does not set the
'content-length' header, making the encoder fall back to chunked
encoding.
2. Also, some ancient load balancers seem to send an HTTP/1.0 request
which does not have the 'Host' header. Armeria currently sends a 400 Bad
Request response to the request without 'Host' header.
Modifications:
- Set the 'content-length' header when necessary in
AggregatedHttpMessage.of()
- Do not send 400 Bad Request response when Host header is not set. Just
assume the default host name.
- Add a test case that makes sure the response from
HttpHealthCheckService is not chunked and an HTTP/1.0 request is …
=> Set 'content-length' header when creating AggregatedHttpMessage / Handle an HTTP/1.0 request

src/main/java/com/linecorp/armeria/client/http/HttpClient.java, src/main/java/com/linecorp/armeria/client/http/HttpClientDelegate.java, src/main/java/com/linecorp/armeria/internal/http/ArmeriaHttpUtil.java, src/test/java/com/linecorp/armeria/client/http/HttpClientIntegrationTest.java
Motivtion:
HttpClientDelegate does not set the :scheme header when sending an
HTTP/2 request, which is clearly a protocol violation.
Modifications:
Set the :scheme header when sending an HTTP/2 request.
Result:
Fixes interoperability
=> Set the :scheme header when sending an HTTP/2 request.

src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java, src/test/java/com/linecorp/armeria/server/http/WebAppContainerTest.java, src/test/java/com/linecorp/armeria/server/http/jetty/JettyServiceTest.java, src/test/java/com/linecorp/armeria/server/http/jetty/UnmanagedJettyServiceTest.java, src/test/java/com/linecorp/armeria/server/http/tomcat/TomcatServiceTest.java, src/test/resources/tomcat_service/index.jsp
Without a correct scheme, Tomcat apps can't do http<->https redirects correctly.
=> Set scheme in TomcatService.

src/main/java/com/linecorp/armeria/client/http/HttpClientDelegate.java, src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java, src/test/java/com/linecorp/armeria/client/http/HttpClientIntegrationTest.java, src/test/java/com/linecorp/armeria/server/http/HttpServerPathTest.java
Motivation:
It is pretty common mistake for an HTTP client sends more than one
consecutive slashes in its request path. e.g. /foo//bar rather than
/foo/bar
It will be useful if we sanitize this sort of mistakes automatically.
Modifications:
- Replace /{2,} with / when an HttpClientDelegate sends a request
- Replace /{2,} with / when HttpServerHandler serves an HTTP request
Result:
More resilent to ill-behaving clients
=> Replace two or more consecutive slashes (/) in request path

src/main/java/com/linecorp/armeria/server/DecoratingService.java, src/main/java/com/linecorp/armeria/server/DecoratingServiceFunction.java, src/main/java/com/linecorp/armeria/server/FunctionalDecoratingService.java, src/main/java/com/linecorp/armeria/server/Service.java, src/test/java/com/linecorp/armeria/server/ServiceTest.java, src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java, src/test/java/com/linecorp/armeria/server/tracing/TracingServiceTest.java
Motivation:
Service.decorate() does not work well with lambda expressions. For
example:
service.decorate(s -> (ctx, req) -> s.serve(ctx, req));
will decorate 'service' with the Service implemented by the lambda
expression. However, because its as() and serviceAdded() were not
implemented properly, the resulting service will not behave correctly.
Modifications:
- Add a functional interface 'DecoratingServiceFunction' which can be
used for writing a decorating service using a lambda expression
- Add Service.decorate(DecoratingServiceFunction) which creates a
decorating service that implements as() and serviceAdded() properly
- Add Service.decorate(Class<?> serviceType) which creates a decorating
service via reflection. This is useful when the compiler fails to
determine which decorate() …
=> Lambda expression friendly Service decoration

NOTICE.txt, licenses/LICENSE.grpc.bsd.txt, pom.xml, settings/checkstyle/checkstyle-suppressions.xml, src/main/java/com/linecorp/armeria/common/http/DefaultHttpHeaders.java, src/main/java/com/linecorp/armeria/common/http/HttpHeaders.java, src/main/java/com/linecorp/armeria/common/http/ImmutableHttpHeaders.java, src/main/java/com/linecorp/armeria/internal/grpc/NettyWritableBuffer.java, src/main/java/com/linecorp/armeria/internal/grpc/NettyWritableBufferAllocator.java, src/main/java/com/linecorp/armeria/server/grpc/ArmeriaGrpcServerStream.java, src/main/java/com/linecorp/armeria/server/grpc/ArmeriaMessageReader.java, src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java, src/main/java/com/linecorp/armeria/server/grpc/InternalHandlerRegistry.java, src/main/java/com/linecorp/armeria/server/grpc/ServerCallImpl.java, src/main/java/com/linecorp/armeria/server/http/HttpResponseSubscriber.java, src/test/java/com/linecorp/armeria/server/grpc/ArmeriaGrpcServerStreamTest.java, src/test/java/com/linecorp/armeria/server/grpc/ArmeriaMessageReaderTest.java, src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java, src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServer.java, src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerBuilder.java, src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
This is closer to TomcatService than THttpService in that it only really adds logic to marshal headers and byte blobs, and relies on GRPC logic to handle them appropriately. 
Why would an armeria user use GRPC instead of the natively supported Thrift?
- Full support for request/response streaming
- Protocol buffer generated code can be a nice change
- Efficient clients on a variety of platforms (Android, iOS, Go, etc)
Why would a GRPC user use armeria for their servers?
- Support for HTTP1 (not verified, will probably require some followup work). HTTP1 should open GRPC to the browser and work better with Cloud load balancers that generally translate HTTP2 -> HTTP1
- Once implemented, DocService and Grpc on the same server
- And any other servers they feel like having on the same server …
=> Add support for hosting GRPC services in an armeria server.

src/main/java/com/linecorp/armeria/client/ClientRequestContext.java, src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java, src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java, src/main/java/com/linecorp/armeria/client/UserClient.java, src/main/java/com/linecorp/armeria/client/http/DefaultHttpClient.java, src/main/java/com/linecorp/armeria/client/thrift/DefaultTHttpClient.java, src/main/java/com/linecorp/armeria/client/thrift/THttpClient.java, src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java, src/main/java/com/linecorp/armeria/client/thrift/THttpClientFactory.java, src/main/java/com/linecorp/armeria/client/thrift/THttpClientInvocationHandler.java, src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java, src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java, src/test/java/com/linecorp/armeria/client/tracing/TracingClientTest.java
Related: #242 and #240
Motivation:
Community request for TMultiplexedProtocol. TMultiplexedProtocol is a
simple variation of Thrift which prepends a service name to the method
name field (e.g. serviceName:methodName) so that a single endpoint can
serve the requests for different Thrift services
Modifications:
- Add ClientRequestContext.fragments()
- Use the fragment part of the request URI as the service name of a
multiplexed Thrift call
- Add THttpClient.executeMultiplexed()
Result:
A user can make a multiplexed Thrift call:
// The service name is 'foo'.
FooService.Iface client =
Clients.newClient("tbinary+http://127.0.0.1:8080/thrift#foo",
FooService.Iface.class);
=> Support client-side TMultiplexedProtocol

pom.xml, src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp1Test.java
- Update netty-tcnative-boringssl-tcnative to 1.1.33.Fork21
- Exclude netty-codec-http2 from grpc-interop-testing to avoid version
clashes
=> Update Netty to 4.1.5.Final

src/site/sphinx/setup-gradle.rst
- Escape a backslash so that parsed-literal directive handles it
correctly
- Update the regular expression so that the recent jetty-alpn-agent
version numbers are handled correctly (Thanks @dayflower)
=> Fix invalid regular expression in example gradle script

src/main/java/com/linecorp/armeria/internal/logging/DropwizardMetricConsumer.java, src/test/java/com/linecorp/armeria/internal/logging/DropwizardMetricConsumerTest.java
Apply this change will make metric name from GET/POST to ${path}#GET/${path}#POST.
=> Change metric name of http request/response

src/main/java/com/linecorp/armeria/server/http/file/HttpFileService.java, src/main/java/com/linecorp/armeria/server/http/file/HttpVfs.java, src/main/java/com/linecorp/armeria/server/http/file/MimeTypeUtil.java, src/test/java/com/linecorp/armeria/server/http/file/HttpFileServiceTest.java, src/test/resources/com/linecorp/armeria/server/http/file/bar/bar.unknown
=> Fix NPE in HttpFileServiceTest for files without a detectable mime type.

src/main/java/com/linecorp/armeria/client/AllInOneClientFactory.java, src/main/java/com/linecorp/armeria/client/ClientFactory.java, src/main/java/com/linecorp/armeria/client/NonDecoratingClientFactory.java, src/main/java/com/linecorp/armeria/client/http/HttpClientFactory.java
Motivation:
Before 0.21, the I/O event loop threads created by ClientFactory
(RemoteInvokerFactory) were daemon threads. However, they are not daemon
threads anymore, preventing a client application from terminating
automatically when its main thread exited already.
Modifications:
- Add the constructors that can specify whether the event loop threads
are daemon threads or not to some ClientFactory implementations:
- NonDecoratingClientFactory
- HttpClientFactory
- AllInOneClientFactory
- Make ClientFactory.DEFAULT use daemon threads
Result:
The default ClientFactory threads have saner life cycle.
=> Use daemon threads for default ClientFactory threads

src/main/java/com/linecorp/armeria/internal/http/ArmeriaHttpUtil.java, src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java
Motivation:
HTTP/2 specification forbids setting the 'connection' header for HTTP/2
messages: https://tools.ietf.org/html/rfc7540#section-8.1.2.2
cURL (Nghttp2 to be precise) rejects the response that contains a
'connection' header. As a result, attempting to query an Armeria HTTP/2
server with cURL fails.
Modifications:
- Do not add (or remove) the 'connection' header when the current
protocol is HTTP/2
Result:
- Conformance with standard
- Interoperability
=> Do not set 'connection' header for HTTP/2 messages

src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java
Motivation:
When cleartext H1C-to-H2C upgrade occurs, HttpServerHandler uses the
reception of an HTTP/2 SETTINGS frame as a signal of successful upgrade.
When an HTTP/2 SETTINGS frame is received, HttpServerHandler will
replace its responseEncoder (Http1ObjectEncoder) with a new
Http2ObjectEncoder.
However, when a client sends more than one SETTINGS frame, the second
SETTINGS frame will make HttpServerHandler replace its responseEncoder
again, closing the Http2ObjectEncoder created when the first SETTINGS
frame was received.
A closed Http2ObjectEncoder causes unexpectedly closed streams.
Modifications:
Do not replace Http2ObjectEncoder but only Http1ObjectEncoder.
Result:
- The H1C request with HTTP/2 upgrade headers set is handled correctly.
- Interoperability with cURL
=> Do not close Http2ObjectEncoder on an HTTP/2 SETTINGS frame

src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java, src/main/java/com/linecorp/armeria/common/thrift/ThriftCall.java, src/main/java/com/linecorp/armeria/internal/thrift/ThriftFieldAccess.java, src/main/java/com/linecorp/armeria/internal/thrift/ThriftFunction.java, src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, src/test/java/com/linecorp/armeria/server/metrics/DropwizardMetricsIntegrationTest.java, src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java, src/test/thrift/main.thrift
Motivation:
When a Thrift operation has a parameter or a return value whose type is
binary, a ThriftCallService will fail with a ClassCastException. It is
primarily because TBase.getFieldValue() for a binary field returns a
byte array (byte[]) while TBase.setFieldValue() requires a ByteBuffer.
Also, it is not very easy to figure out the root cause of this sort of
internal server errors because the stack trace of the
TApplicationException shown on the client-side tells a user only the
exception type and message of the server-side exception. There's no way
to get the server-side stack trace.
Modifications:
- Add an internal utility class 'ThriftFieldAccess' which converts a
byte[] into a ByteBuffer
- Use it everywhere TBase.getFieldValue() is used.
- When an internal server error occurs, …
=> Fix ClassCastException when using Thrift binary type

src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, src/main/java/com/linecorp/armeria/server/ChainedVirtualHostBuilder.java, src/main/java/com/linecorp/armeria/server/InternalVirtualHostBuilder.java, src/main/java/com/linecorp/armeria/server/ServerBuilder.java, src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java, src/site/sphinx/client-basics.rst, src/test/java/com/linecorp/armeria/server/ChainedVirtualHostBuilderTest.java
**Motivation**
Setting of defaultVirtualHost and virtualHost will propose a method to be processed at the same level in serverBuilder.
**Modifications**
modified class:
- ServerBulder - add method for configure to build default virtual host
- VirtualHostBuilder - add constructor for contain ServerBuilder, add method for return ServerBuilder
**Result**
I think that looks more fluent.
Proceed as follows
```
ServerBuilder sb = new ServerBuilder();
Server server =
sb.port(8080, SessionProtocol.HTTP) // Add a port to listen
.withDefaultVirtualHost() // Add services to the default virtual host.
.serviceAt(...)
.serviceUnder(...)
.and().withVirtualHost("*.foo.com") // Add a virtual host.
.serviceAt(...)
.serviceUnder(...)
.and().build(); // Build
```
**etc**
modified file: …
=> Fluent API for building virtual hosts with ServerBuilder

pom.xml, src/build/versions-props.groovy, src/main/java/com/linecorp/armeria/client/http/HttpHeaderUtil.java, src/main/java/com/linecorp/armeria/common/util/Version.java, src/test/java/com/linecorp/armeria/client/http/HttpClientIntegrationTest.java
PR resolves #267 
Motivation:
- Hard to distinguish client version in server, generally need for statistics.
- Sometimes, the version information is quite useful for client/server apps.
(e.g. negotiating capabilities, work-around with known bugs, ...)
Modifications:
- Added a groovy script to generate a Java class with project name & version
- Fixed some tests that rely on hard-coded UA string
Result:
- Now UA string is `${project.name}/${project.version}`
- The version information is accessible as public constant string.
=> Add version information to default user-agent header

settings/checkstyle/checkstyle.xml, src/main/java/com/linecorp/armeria/client/http/package-info.java, src/main/java/com/linecorp/armeria/server/ServerBuilder.java, src/main/java/com/linecorp/armeria/server/ServerConfig.java, src/main/java/com/linecorp/armeria/server/grpc/package-info.java, src/main/java/com/linecorp/armeria/server/http/cors/CorsConfig.java, src/main/java/com/linecorp/armeria/server/http/cors/CorsService.java, src/main/java/com/linecorp/armeria/server/http/cors/CorsServiceBuilder.java, src/main/java/com/linecorp/armeria/server/http/cors/package-info.java, src/main/java/com/linecorp/armeria/server/http/encoding/package-info.java, src/test/java/com/linecorp/armeria/server/http/HttpServerCorsTest.java
Related: #206 #205
Credits:
Original work by @jprante. @trustin made cosmetic improvements and cleanup.
Motivation:
Armeria HTTP server lacks CORS (cross-origin resource sharing) support.
Modifications:
- Add CorsConfig and CorsConfigBuilder, forked from Netty project
- Replace CorsConfigBuilder.disable() with CorsConfig.DISABLED
- Property getters in CorsConfig throws an IllegalStateException when
disabled.
- Add CorsService that handles CORS preflight requests and emits CORS
response headers
- Add HttpServerCorsTest
- Add JavadocPackage checkstyle rule
- Update existing package-info.java
Result:
Armeria gets CORS support.
=> Add CORS support

NOTICE.txt, licenses/LICENSE.json-minify.mit.txt, src/main/resources/com/linecorp/armeria/server/docs/assets/js/armeria.js, src/main/resources/com/linecorp/armeria/server/docs/assets/js/vendor/json-minify-0.1.js, src/main/resources/com/linecorp/armeria/server/docs/assets/js/vendor/json-prettify-0.1.js, src/main/resources/com/linecorp/armeria/server/docs/index.html, src/test/java/com/linecorp/armeria/server/docs/DocServiceTest.java
Motivation:
JSON.parse() can lose the digits of a large integer value when parsing a
JSON string. Therefore, specifying a 64-bit integer as a parameter can
cause the loss of precision.
Modifications:
- Do not use JSON.parse() when handling the debug form or the query
parameters.
- Use json-minify to minify the JSON in the debug form instead.
- json-minify was licensed under MIT license by Kyle Simpson.
- Use json-prettify to prettify the JSON in the query parameters
instead.
- json-prettify was forked from json-minify.
- Split the 'req' query parameter into 'args and 'http_headers' as we
initially wished to (/cc @taicki)
- More validation
- Add SleepService to DocServiceTest so that it's easier to test an
operation that accepts a long integer
- Use AssertJ instead of …
=> (De)serialize large integers correctly in the DocService debug form / Add 'sticky HTTP headers' checkbox in the DocService debug form

src/main/java/com/linecorp/armeria/internal/logging/DropwizardMetricConsumer.java, src/main/java/com/linecorp/armeria/internal/logging/DropwizardRequestMetrics.java
Motivation:
Commit c2dad254f19f5b3eccec987efde850b34eac9e32 introduced a regression
where a new DropwizardRequestMetrics instance is created for every
request, because it used RequestLog as a key of the Map that holds
DropwizardRequestMetrics. As a result, the Map will grow infinitely.
Modifications:
- Use String as a key again
Result:
Leak is gone.
=> Fix DropwizardRequestMetrics leak

pom.xml, src/main/java/com/linecorp/armeria/server/grpc/ArmeriaGrpcServerStream.java, src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java, src/test/resources/logback-test.xml
Motivation:
- ArmeriaGrpcServerStream.writeFrame() does not release the ByteBuf,
resulting a LEAK error from Netty.
- ArmeriaGrpcServerInteropTest logs its messages via JUL, which is not
consistent.
Modifications:
- Release the ByteBuf in ArmeriaGrpcServerStream.writeFrame()
- Use SLF4J when running ArmeriaGrpcServerInteropTest
Result:
- ByteBuf leak is gone.
- No more log messages from java.util.logging
=> Fix ByteBuf leak in ArmeriaGrpcServerStream

src/main/java/com/linecorp/armeria/client/http/HttpHeaderUtil.java
Motivation:
HttpClient sends the 'user-agent' header with incorrect version
information. It's sending artifactId instead of artifactVersion.
Modifications:
- Use artifactVersion instead of artifactId
- Use correct class loader
Result:
The 'user-agent' header value includes the version information.
=> Fix missing version information in user-agent header

pom.xml, src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java, src/main/java/com/linecorp/armeria/common/logging/AbstractMessageLog.java, src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, src/main/java/com/linecorp/armeria/common/logging/DefaultResponseLog.java, src/main/java/com/linecorp/armeria/common/logging/RequestLog.java, src/main/java/com/linecorp/armeria/common/logging/ResponseLog.java, src/main/java/com/linecorp/armeria/common/thrift/ApacheThriftCall.java, src/main/java/com/linecorp/armeria/common/thrift/ApacheThriftMessage.java, src/main/java/com/linecorp/armeria/common/thrift/ApacheThriftReply.java, src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
Motivation:
There's currently no way to get the protocol-dependent RPC request and
response objects from RequestLog and ResponseLog.
Modifications:
- Add ApacheThriftCall and ApacheThriftReply
- Add RAW_RPC_REQUEST and RAW_RPC_RESPONSE attribute
- Set RAW_RPC_REQUEST and RAW_RPC_RESPONSE attribute where applicable
- Add test cases that ensures the required attributes are available in
RequestLog and ResponseLog
- Improve MessageLog.toString()
- Optimize using StringBuilder in lieu of MoreObjects.ToStringHelper
- Exclude RAW_RPC_REQUEST and RAW_RPC_RESPONSE from the attributes
- Exclude 'channel' property since it's often logged by service logger
- Use simpler attribute names
Result:
- A user can access the low-level details about RPC calls.
- Log messages from LoggingClient/Service look …
=> Add RAW_RPC_REQUEST and RAW_RPC_RESPONSE to RequestLog and ResponseLog

src/main/java/com/linecorp/armeria/server/docs/FunctionInfo.java, src/main/resources/com/linecorp/armeria/server/docs/assets/js/armeria.js, src/test/java/com/linecorp/armeria/server/docs/DocServiceTest.java
Motivation:
- Let DocService to handle oneway function as well
Modifications:
- Fix DocService not to try finding _result class for DocService
- Display static text in the response field of DocService if the response is empty with successful HTTP code
Result:
- Users can test oneway function on DocService as well
=> Fix DocService to handle oneway function properly

src/main/java/com/linecorp/armeria/client/http/HttpClientPipelineConfigurator.java, src/main/java/com/linecorp/armeria/internal/TrafficLoggingHandler.java, src/main/java/com/linecorp/armeria/server/http/HttpServerPipelineConfigurator.java
Motivation:
It is sometimes necessary to investigate protocol-level traffic to
figure out the root cause of the problem.
Modifications:
- Add a Netty handler 'TrafficLoggingHandler` which logs the traffic at
TRACE level
- Server-side traffic is logged at
'com.linecorp.armeria.traffic.server'.
- Client-side traffic is logged at
'com.linecorp.armeria.traffic.client'.
- Note that the TrafficLoggingHandler is always added to
ChannelPipeline so that a user can turn the logging on or off at
runtime.
Result:
A user can look into the socket traffic easily without modifying Armeria
source code and inserting Netty LoggingHandler. In Logback, a user can
add the following configuration to enable traffic logging:
<logger name="com.linecorp.armeria.traffic" level="TRACE" />
To enable traffic logging …
=> Log socket traffic at TRACE level

core/src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java
Motivation:
HttpServerHandler.CLOSE attempts to get the current HttpServer instance
via HttpServer.get() when logging an exception. However, the
HttpServer.get() can return null, resulting in a NullPointerException,
when the connection is already cleaned up.
Modifications:
Handle the case where HttpServer.get() returns null.
Result:
One less NPE
=> Fix NullPointerException from HttpServerHandler.CLOSE

core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java, core/src/main/java/com/linecorp/armeria/common/logging/AbstractMessageLog.java, core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/DefaultResponseLog.java, core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java, core/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Motivation:
It is currently possible that the CompletableFuture of RequestLog is
complete before the CompletableFuture of ResponseLog is complete.
In such a case, a user can access the incomplete RequestLog via
ResponseLog.request().
Modifications:
- Complete the CompletableFuture of ResponseLog only after the
CompletableFuture of RequestLog is complete.
- Use CompletableFuture.whenComplete() instead of handle() when
AbstractMessageLog adds a callback to the futures it is interested,
because it is not supposed to consume the result but only to monitor
Result:
- A user cannot access the incomplete state of RequestLog via
ResponseLog.request()
=> Ensure RequestLog future is completed always before ResponseLog future

build.gradle, site/build.gradle
- Add groups and descriptions to commonly used tasks without
description
- Do not run 'git' command more than once if the previous execution
failed
- Apply the 'base' plugin to the 'site' project so that the common tasks
such as 'clean' and 'build' are populated automatically
- Rename the 'apidocs' task to 'javadoc' to match the task names of Java
projects
=> Clean up the build script

tomcat/src/main/java/com/linecorp/armeria/server/http/tomcat/ManagedConnectorFactory.java
Apply this change will fix `java.io.IOException: Unable to create the directory`. But even this throws exception, it still works. So this PR just fix annoying msg.
reference: http://www.mail-archive.com/users@tomcat.apache.org/msg122417.html
```
java.io.IOException: Unable to create the directory [/private/var/folders/pg/hr1wt4pd4yl97t21pl33lf_00000gp/T/tomcat-armeria.4815329135503493333/webapps/ROOT]
at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:115) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:618) [tomcat-embed-core-8.0.30.jar:8.0.30]
at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:744) [tomcat-embed-core-8.0.30.jar:8.0.30]
at …
```
=> Fix create directory failed when using war for TomcatService

core/src/main/java/com/linecorp/armeria/client/routing/EndpointGroupException.java, core/src/main/java/com/linecorp/armeria/client/routing/EndpointGroupRegistry.java, core/src/test/java/com/linecorp/armeria/client/routing/EndpointGroupRegistryTest.java, core/src/test/java/com/linecorp/armeria/client/routing/StaticEndpointGroupTest.java
Motivation:
In a multiple-classloader environment, an application can invoke
EndpointGroupRegistry.register() multiple times with the same group name
when the application is reloaded by the class loader, causing register()
trigger an EndpointGroupException.
Modifications:
- Remove EndpointGroupRegistry.replace()
- Make EndpointGroupRegistry.register() replace.
- Add EndpointGroupRegistry.unregister()
Result:
Less surprising behavior
=> Make EndpointGroupRegistry.register() replace and Add unregister()

core/src/main/java/com/linecorp/armeria/client/http/SimpleHttpRequestBuilder.java, core/src/main/java/com/linecorp/armeria/internal/http/ArmeriaHttpUtil.java, core/src/main/java/com/linecorp/armeria/server/http/Http1RequestDecoder.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServerPathTest.java
Motivation:
Armeria currently responds with 500 Internal Server Error when an HTTP/1
client sends a request with an invalid path. Armeria should respond with
400 Bad Request instead.
Modifications:
- Split ArmeriaHttpUtil.toArmeria(HttpMessage) into toArmeria(HttpRequest)
and toArmeria(HttpResponse) for clarity
- Raise URISyntaxException rather than IllegalArgumentException when
request path is invalid for distiction from other runtime exceptions
- Handle the case where a client sends a path that starts with '//' so
that 400 Bad Request response is not sent
Result:
- Sensible response code
- Server log is not polluted by invalid requests anymore.
=> Send 400 Bad Request instead of 500 Internal Server Error on invalid request path

core/src/main/java/com/linecorp/armeria/common/RequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContextAwareEventLoop.java, core/src/main/java/com/linecorp/armeria/common/RequestContextAwareExecutorService.java, core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/thrift/ThriftCallService.java, tomcat/src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java
Motivation:
So far, RequestContext.blockingTaskExecutor() was not context-aware,
meaning a user had to make his or her task context-aware by calling
RequestContext.makeContextAware(Runnable). It is error-prone and
inconvenient.
Modifications:
- Add RequestContextAwareExecutorService
- Make RequestContextAwareEventLoop extend it
- Add RequestContext.makeContextAware(ExecutorService)
- Make RequestContext.blockingTaskExecutor() always return the
context-aware version
- Update the API documentation of ServerConfig.blockingTaskExecutor()
Result:
User-friendliness
=> Make RequestContext.blockingTaskExecutor() context-aware

core/src/main/java/com/linecorp/armeria/server/http/healthcheck/HttpHealthCheckService.java, core/src/test/java/com/linecorp/armeria/server/http/healthcheck/HttpHealthCheckServiceTest.java
Motivation:
Some load balancers use a HEAD request instead of a GET request to check
the health of a host.
Modifications:
- Implement HttpHealthCheckService.doHead()
Result:
HttpHealthCheckService works with the load balancers that sends a HEAD
request.
=> Support HEAD method on HttpHealthCheckService

core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/RequestTimeoutChangeListener.java, core/src/main/java/com/linecorp/armeria/server/http/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java, core/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java
Motivation:
Unlike the client side, we may not know the appropriate timeout value of
the current request until the full request content is received. For
example, a Thrift service operation could have a 'timeout' parameter
that determines the request timeout.
That is, it is possible that the request timeout is known *after* the
timeout task has been scheduled by HttpResponseSubscriber already. In
such a case, updating the request timeout with
ServiceRequestContext.setRequestTimeout() will not have any effect.
Modifications:
- Add RequestTimeoutChangeListener which is notified by
DefaultServiceRequestContext when request timeout is changed by a
user
- Update HttpResponseSubscriber so that it implements
RequestTimeoutChangeListener and thus it reschedules the timeout task
on …
=> Allow rescheduling server-side request timeout

core/src/main/java/com/linecorp/armeria/client/Clients.java, core/src/main/java/com/linecorp/armeria/client/UserClient.java, core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java, core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContext.java, core/src/main/java/com/linecorp/armeria/common/logging/MessageLogConsumerInvoker.java, core/src/main/java/com/linecorp/armeria/common/util/SafeCloseable.java, core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java, core/src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java, core/src/test/java/com/linecorp/armeria/it/thrift/ThriftThreadLocalHttpHeaderTest.java, logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java, site/src/sphinx/client-thrift-custom-http-headers.rst, site/src/sphinx/client.rst
Motivation:
There's no simple way for a user to specify HTTP headers when making a
Thrift call via *.Iface and *.AsyncIface clients.
Modifications:
- Add Clients.withHttpHeaders() and withHttpHeader() which allows a user
to set a thread-local HTTP header manipulator function
- Make UserClient pick up the thread-local HTTP header manipulator
function set by withHttpHeaders()
- Add SafeCloseable
- Remove RequestContext.PushHandle and use SafeCloseable instead
Result:
- A user can send a custom HTTP header without using decorator.
=> Add Clients.withHttpHeaders() and withHttpHeader()

core/src/main/java/com/linecorp/armeria/client/NonDecoratingClientFactory.java
Motivation:
netty/netty#5923 fixes a critical DNS resolution problem. We should
backport it until a new Netty version is released.
Modifications:
- Override the DnsNameResolver.DECODER field with the fixes decoder,
using a reflection hack
- Remove the workaround for netty/netty#5657, since the fix is in Netty
4.1.6.Final
Result:
DNS resolution works as expected
=> Backport the fix for broken DefaultDnsRecordDecoder

jetty/src/main/java/com/linecorp/armeria/server/http/jetty/JettyService.java
Motivation:
When JettyService copies the output from Jetty to an HttpData, it has to
respect the position of the ByteBuffer provided by Jetty.
Modification:
- Respect the position of the ByteBuffer provided by Jetty
Result:
No more data corruption in JettyService
=> Fix data corruption in JettyService

build.gradle, core/src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java, gradle.properties, logback/build.gradle, logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
Motivation:
When a Service throws an unexpected exception in its `service()` method,
HttpServerHandler.handleRequest() will log the exception at WARN level.
When the exception is logged, the thread-local RequestContext must be
set so that RequestContextExportingAppender picks it up.
However, we currently pop the RequestContext too early, and thus
RequestContextExportingAppender does not see the thread local
RequestContext.
Modifications
- Pop the current RequestContext as late as possible
- Fix potential race condition in RequestContextExportingAppender
Result:
- An unexpected exception from a Service will be logged with more
information.
- RequestContextExportingAppender will not cause other Appender to throw
ConcurrentModificationException by making a copy
=> Do not pop the current RequestContext too early when a Service throws an unexpected exception

core/src/main/java/com/linecorp/armeria/client/routing/EndpointGroup.java, core/src/test/java/com/linecorp/armeria/client/routing/EndpointGroupTest.java
Motivations:
It is often useful to provide some endpoints in one EndpointGroup and
other endpoints in the other EndpointGroup. And there is no way to bind
such two EndpointGroup under the same endpoint group name.
Modifications:
- Add EndpointGroup.orElse
Results:
A user can combine two EndpointGroup
```
EndpointGroupRegistry.register(
"myGroup",
new StaticEndpointGroup().orElse(new StaticEndpointGroup()),
WEIGHTED_ROUND_ROBIN);
```
=> Add EndpointGroup.orElse(EndpointGroup)

zookeeper/src/test/java/com/linecorp/armeria/client/endpoint/zookeeper/ZooKeeperEndpointGroupTest.java
Motivation:
ZooKeeperEndpointGroupTest creates the ZooKeeper work directory under
'target' dierctory. Gradle uses 'build' as the build output directory
unlike Maven. As a result, the offending test case leaves the cruft
files outside the 'build' directory.
Modifications:
- Change the rootDir from 'target' to 'build/zookeeper'
Result:
No more untracked files reported by Git after a build
Assigned to @imasahiro since he reviewed the original PR by @jonefeewang
=> Change ZooKeeper test rootDir from target to build/zookeeper

core/src/main/java/com/linecorp/armeria/common/logging/AbstractMessageLog.java, core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/DefaultResponseLog.java, core/src/main/java/com/linecorp/armeria/common/logging/MessageLog.java, core/src/main/java/com/linecorp/armeria/common/logging/MessageLogBuilder.java, core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java, core/src/main/java/com/linecorp/armeria/common/logging/ResponseLog.java, core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogBuilder.java, core/src/main/java/com/linecorp/armeria/internal/logging/DropwizardMetricConsumer.java, core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLog.java, core/src/test/java/com/linecorp/armeria/internal/logging/DropwizardMetricConsumerTest.java, logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporter.java
Motivation:
MessageLog.startTimeNanos() and startTimeMillis() may misleads a user
think startTimeNanos = startTimeMillis * 1000000, which is not correct.
Modifications:
- Replace start/endTimeNanos() with durationNanos()
- Add ResponseLog.responseTimeNanos()
Result:
Less confusion
=> Replace MessageLog.start/endTimeNanos() with durationNanos()

site/src/sphinx/setup-gradle.rst, site/src/sphinx/setup-maven.rst
.. because it's outdated.
- Remove the configuration related with Jetty ALPN agent
- We support Windows, Linux and OS X using netty-tcnative-boringssl-static.
- List all module dependencies
=> Update setup-gradle.rst and setup-maven.rst

core/src/main/java/com/linecorp/armeria/client/thrift/DefaultTHttpClient.java, core/src/main/java/com/linecorp/armeria/common/DefaultRpcRequest.java, core/src/main/java/com/linecorp/armeria/common/RpcRequest.java, core/src/main/java/com/linecorp/armeria/common/RpcResponse.java, core/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java, core/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, core/src/test/java/com/linecorp/armeria/server/ServiceTest.java, core/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java, zipkin/src/test/java/com/linecorp/armeria/client/tracing/TracingClientTest.java, zipkin/src/test/java/com/linecorp/armeria/server/tracing/TracingServiceTest.java
Related issue: #350
Motivation:
- Attempting to send a null parameter fails since 0.33.0 due to the use
of ImmutableList.copyOf() and GuavaCollectors.toImmutableList(), which
does null checks on elements.
- We could make users' lives easier by adding some static factory
methods to RpcRequest and RpcResponse
Modifications:
- Do not use ImmutableList.copyOf() and
GuavaCollectors.toImmutableList() when constructing the RPC parameter
list
- Add various static factory methods to RpcRequest and RpcResponse
- Add more convenience constructors to DefaultRpcRequest
Result:
- Fixes #350, the regression introduced in 0.33.0
- A user can instantiate RpcRequest and RpcResponse more easily.
=> Do not check null on RpcRequest parameters / Easier instantiation of RpcRequest and RpcResponse

retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactory.java, retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallSubscriber.java, retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/CompletableCallback.java, retrofit2/src/test/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactoryTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallSubscriberTest.java
Motivation:
- Original armeria-retrofit will convert huge response body to single byte[].
Modifications:
- Using subscriber to add response data to okio.Buffer which creates multiple.
Result:
- Avoid humongous object creation which is not good for memory management.
=> Avoid creating humongous object when armeria retrofit get large response

core/src/main/java/com/linecorp/armeria/server/http/auth/AuthTokenExtractors.java, core/src/main/java/com/linecorp/armeria/server/http/auth/BasicToken.java, core/src/main/java/com/linecorp/armeria/server/http/auth/BasicTokenExtractor.java, core/src/main/java/com/linecorp/armeria/server/http/auth/HttpAuthService.java, core/src/main/java/com/linecorp/armeria/server/http/auth/HttpAuthServiceBuilder.java, core/src/main/java/com/linecorp/armeria/server/http/auth/HttpAuthServiceImpl.java, core/src/main/java/com/linecorp/armeria/server/http/auth/OAuth1aToken.java, core/src/main/java/com/linecorp/armeria/server/http/auth/OAuth1aTokenExtractor.java, core/src/main/java/com/linecorp/armeria/server/http/auth/OAuth2Token.java, core/src/main/java/com/linecorp/armeria/server/http/auth/OAuth2TokenExtractor.java, core/src/main/java/com/linecorp/armeria/server/http/auth/package-info.java, core/src/test/java/com/linecorp/armeria/server/http/auth/AuthServiceTest.java
Hello. Here is a concept-proof commit which resolves #259 and #258.
Here is my approach: Http Authorization routine, including rate-limiting routine, can be represented in the form of Predicate of Authorization Token with its internal state (e.g., Set of valid tokens, API usage rate, etc.). So, I implemented a helper method in HttpAuthSevice which creates DecoratingServiceFunction<HttpRequest, HttpResponse> with given Predicate. For example, HttpAuthService#basic returns a DecoratingServiceFunction which inspects authorization header and handle the request to delegate.
This commit only includes basic authorization. If you agree with my approach, I will continue on the other authorization methods like Oauth1.0a, Oauth2, and so on. Thanks.
=> Implement HTTP authorization decorator service

core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointSelectionStrategy.java, core/src/main/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategy.java, core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java, core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
Motivation:
- WeightedRoundRobinStrategy does not refresh min/max/sumWeight even if endpointGroup return different endpoint lists.
Modifications:
- Calculate min/max/sumWeight everytime
- Add RoundRobinStrategy
Results:
- Endpoint's weight are applied correctly
=> Update weight dynamicaly

NOTICE.txt, core/src/main/java/com/linecorp/armeria/server/logging/CountingSampler.java, core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java, core/src/main/java/com/linecorp/armeria/server/logging/SampledLoggingService.java, core/src/main/java/com/linecorp/armeria/server/logging/Sampler.java
When a server receives many requests, we cannot records all logs
through LoggingService due to server resource limitation. To adjust
this, sample logs.
=> Add SampledLoggingService

core/src/main/java/com/linecorp/armeria/client/http/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/client/http/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/server/http/HttpResponseSubscriber.java, core/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java
Motivation:
When a user disables the timeout dynamically by calling
ServiceRequestContext.setRequestTimeoutMillis(0), the response stream is
never marked as completed because HttpResponseSubscriber.cancelTimeout()
will always return false, preventing HttpResponseSubscriber.onComplete()
from sending the 'end of stream'.
Modifications:
- Set the timeoutFuture to null when canceling it so that
cancelTimeout() returns true
- Add the test case for the bug to ThriftDynamicTimeoutTest
Result:
One less bugs
=> Fix a bug where Response is not completed when timeout is disabled dynamically

core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContext.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
Motivation:
- `RequestContext` is not propagate when users use `CompletableFuture` asynchronously.
Modifications:
- Add `RequestContext#makeContextAware` for `CompletableFuture`.
Result:
- Fixes #365
=> Add makeContextAware for CompletableFuture

retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactory.java, retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaRetrofit.java, retrofit2/src/test/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactoryTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaRetrofitTest.java
Motivations:
- Currently, a response of armeria-retrofit returns wrong uri like `"http://127.0.0.1/"` and it can make a user confusion
Modifications:
- Fix to use armeria client's uri instead of dummy uri for Retrofit's base URL
- Use AbstractServerTest at ArmeriaCallFactoryTest
- Fix to use try-with resource for Buffer due to Buffer is AutoCloseable
Results:
- Fixes #376
=> Fix to use armeria client's uri for Retrofit's base URL

core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistry.java, core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistryTest.java, retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaRetrofit.java, retrofit2/src/test/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactoryTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallSubscriberTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaRetrofitTest.java
Motivation:
An EndpointGroup name is used as a part of URI, often via simple string
concatenation:
uri = "https://group:" + groupName + "/foo/bar";
It would be less error-prone to disallow the characters in EndpoinrGroup
names.
Modifications:
- Add extra rule for EndpointGroup names
- Make EndpointGroup names case-insensitive, because a hostname in a URI
is case-insensitive and thus often lower-cased by other integrating
parties such as OkHttp
- Simplify the configuration of baseUrl in armeria-retrofit2
- Fix inspection warnings in com.linecorp.armeria.client.http.retrofit2
Result:
- EndpointGroup names blend better into URI
=> More strict naming rule for EndpointGroup

core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistry.java, core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistryTest.java
.. which were mistakenly dropped in the previous commit.
=> Allow numeric characters in EndpointGroup names

core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContextAwareCompletableFuture.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
Motivation:
- Current `RequestContext#makeContextAware(CompletableFuture<T> future)`
cannot propagate `RequestContext` to chained futures.
Modifications:
- Add `RequestContextAwareCompletableFuture` for async handlers.
Result:
- Fixes #384
=> Add RequestContextAwareCompletableFuture for async chaining

retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactory.java, retrofit2/src/test/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactoryTest.java
When a client request does not contain the 'content-type' information,
NullPointerException would be raised.
=> Fix NPE in ArmeriaCallFactory

core/src/main/java/com/linecorp/armeria/server/http/dynamic/Deserializers.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunction.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctionEntry.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctionImpl.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctions.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpService.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpServiceBuilder.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicPath.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/MappedDynamicFunction.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/Methods.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServiceTest.java
With this change, automatic execution of methods in the blocking executor is moved into a feature of reflection-based methods, where the only arguments are the Java types. Methods defined directly as implementations of DynamicHttpFunction (dunno if anyone will ever do this...) should take care of using the executor themselves as appropriate (simple since ServiceInvocationContext is provided).
Methods are run in the blocking executor if their return type is not CompletionStage (future) or HttpResponse (published stream). 
Also applied some cleanups while going through the code, let me know if you'd like to move any or all from this behavior-changing PR.
- Replace map dispatch with if/else since almost same amount of code but should be a bit faster/simpler
- Use immutable lists / sets for …
=> Make DynamicHttpService asynchronous.

site/src/sphinx/server-basics.rst
Add missing `.join()` call so that startup failure is not swallowed up
=> Fix armeria server bootstrapping example

core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistry.java, core/src/main/java/com/linecorp/armeria/client/http/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/common/Scheme.java, core/src/main/java/com/linecorp/armeria/common/http/HttpHeaderNames.java, core/src/main/java/com/linecorp/armeria/server/VirtualHost.java, core/src/main/java/com/linecorp/armeria/server/http/auth/OAuth1aToken.java, core/src/main/java/com/linecorp/armeria/server/http/cors/CorsService.java, core/src/main/java/com/linecorp/armeria/server/http/cors/CorsServiceBuilder.java, core/src/main/java/com/linecorp/armeria/server/http/file/MimeTypeUtil.java, zipkin/src/main/java/com/linecorp/armeria/internal/tracing/BraveHttpHeaderNames.java
Motivation:
There are many places in Armeria that performs case conversion and
case-insensitive comparisons on an ASCII string. We were using
String.toLower/UpperCase(Locale.ENGLISH) and String.equalsIgnoreCase(),
but Guava provides much better alternatives in its utility class:
com.google.common.base.Ascii.
Modifications:
- Use Ascii.toLower/UpperCase() wherever possible
- Use Ascii.equalsIgnoreCase() wherever possible
Result:
- Faster and simpler case conversion and case-insensitive comparison
- Fixes #399
=> Prefer Ascii.toLower/UpperCase() and equalsIgnoreCase()

core/src/main/java/com/linecorp/armeria/common/http/HttpHeaders.java, core/src/main/java/com/linecorp/armeria/common/http/HttpHeadersJsonDeserializer.java, core/src/main/java/com/linecorp/armeria/common/http/HttpHeadersJsonSerializer.java, core/src/main/java/com/linecorp/armeria/server/docs/DocService.java, core/src/main/java/com/linecorp/armeria/server/docs/ServiceInfo.java, core/src/main/java/com/linecorp/armeria/server/docs/ServiceSpecificationGenerator.java, core/src/main/resources/com/linecorp/armeria/server/docs/assets/js/armeria.js, core/src/test/java/com/linecorp/armeria/common/http/HttpHeadersJsonDeserializerTest.java, core/src/test/java/com/linecorp/armeria/common/http/HttpHeadersJsonSerializerTest.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceSpecificationGenerator.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServiceTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceSpecificationGeneratorTest.java
Motivation:
Since the separation of armeria-thrift from the core, a user was not
able to specify example HTTP headers. We should implement it again.
Modifications:
- Add a new DocService constructor that accepts a Multimap of
HttpHeaders whose key is the type of the relevant service
- Unlike the old implementation, it is possible to specify more than
one example HTTP headers.
- Replace sampleHttpHeaders which is a Map of Strings with
exampleHttpHeaders which is a List of HttpHeaders
- Add Jackson (de)serializer implementation for HttpHeaders
- Change the signature or ServiceSpecificationGenerator.generate() to
support the example HTTP headers
- Update the frontend-side implementation to handle the example HTTP
headers properly
- Add HttpHeaders.of() convenience method
- …
=> Revive the 'example HTTP headers' support for DocService

core/src/main/java/com/linecorp/armeria/client/Endpoint.java, core/src/main/java/com/linecorp/armeria/client/http/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/client/http/HttpSessionHandler.java, core/src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java, core/src/test/java/com/linecorp/armeria/server/http/file/HttpFileServiceTest.java, dependencies.yml, grpc/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java, jetty/src/main/java/com/linecorp/armeria/server/http/jetty/JettyService.java, settings/logback/logback-test.xml, zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java
Updated dependencies:
- Logback 1.1.7 -> 1.2.1
- Jackson 2.8.4 -> 2.8.7
- Netty 4.1.6 -> 4.1.8
- Brave 3.14.1 -> 4.0.6
- fastutil 7.0.13 -> 7.1.0
- json-unit 1.16.0 -> 1.19.0
- HBase shaded client -> 1.2.3 -> 1.2.4
- Apache HTTP client -> 4.5.2 -> 4.5.3
- Kafka -> 0.10.0.1 -> 0.10.1.1
- ZooKeeper -> 3.4.7 -> 3.4.9
- AssertJ -> 3.5.2 -> 3.6.2
- Jetty -> 9.3.14 -> 9.4.1
- Javassist -> 3.20 -> 3.21
- Jetty ALPN agent -> 2.0.5 -> 2.0.6
- SLF4J -> 1.7.21 -> 1.7.23
Modifications:
- Replace the use of the deprecated API with the new one
- Fix the client-side HTTP/2 upgrade which got broken due to Netty upgrade
- Do not log SslCloseCompletionEvent
- Fix the bugs where HttpServerTest.testStrings_*() do not close the
requests they sent
- Add the logger names related with traffic logging to …
=> Update the dependencies

core/src/main/java/com/linecorp/armeria/server/docs/DocService.java, core/src/main/java/com/linecorp/armeria/server/docs/ServiceSpecificationGenerator.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceSpecificationGenerator.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServiceTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceSpecificationGeneratorTest.java
Not all RPC protocols have the concept of a class (in the end, RPC is just a bunch of methods) so this is more widely appliable.
Hmm - I was hoping to find a better "full service name" for a thrift service than the class canonical name. Any suggestion or does it look ok?
=> Switch example headers from keying on Class to keying on String.

build.gradle
It's common to run :test locally to confirm the build wouldn't be broken when opening a new PR, so it should also run :checkstyle which is part of the build.
=> Run checkstyle when running tests.

core/src/main/java/com/linecorp/armeria/server/docs/ClassInfo.java, core/src/main/java/com/linecorp/armeria/server/docs/UnresolvedClassInfo.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceSpecificationGenerator.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceSpecificationGeneratorTest.java, thrift/src/test/thrift/main.thrift
Motivation:
The FieldValueMetaData of a typedef'd field does not provide enough
information to infer its effective type. Translate typedef'd field into
a new type called UnresolvedClassInfo so that
ThriftServiceSpecificationGenerator does not fail at least.
Modifications:
- Add UnresolvedClassInfo
- Modify ThriftServiceSpecificationGenerator so that it does not fail on
a typedef'd field
- Revise @imasahiro's test case to reflect the modification of
ThriftServiceSpecificationGenerator
Result:
- DocService does not fail to start when typedef is used in .thrift
files.
- Fixes #413
=> Fix DocService by handling Thrift typedefs as an UnresolvedClassInfo

core/src/test/java-shared/com/linecorp/armeria/test/AbstractServerTest.java, core/src/test/java/com/linecorp/armeria/server/ServerTest.java
On Mac (at least my mac), the ipv6 lookups in ServerTest take a ridiculously long time (several seconds). Tests with a timeout less than that fail all the time. One alternative would be to raise the timeout, but there doesn't seem to be a real reason to use ipv6 so switched to using ipv4 addresses which resolve fast.
Result: Tests work on my mac, and ServerTest runs much faster than before.
Fixes #403
=> Use ipv4 addresses instead of ipv6 anycast in socket tests.

core/src/main/java/com/linecorp/armeria/common/http/DefaultHttpHeaders.java, core/src/main/java/com/linecorp/armeria/internal/http/ArmeriaHttpUtil.java, core/src/test/java/com/linecorp/armeria/common/http/HttpHeadersTest.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java
Motivation:
HTTP/2 header field names are compared in case-insensitive fashion.
Modification:
- Make `HTTP2_HEADER_NAME_HASHER` case-insensitive
- Lowercase header name when adding new header
Result:
- Users do not worry case-sensitivity for header names
=> Make header names case-insensitive

core/src/main/java/com/linecorp/armeria/common/RequestContextAwareEventLoop.java
... to propagate current request context to next event loop
https://github.com/line/armeria/pull/364#discussion_r103172395
> Also, the next() actually loses the context (I guess it may be a bug in RequestContextAwareEventLoop where next() should wrap the result in a ContextAwareEventLoop);
=> Return RequestContextAwareEventLoop itself for next()

site/build.gradle
Motivation:
'./gradlew site:javadoc' fails since JDK 1.8.0_121 because it does not
allow a `<script>` tag in `-bottom` option.
Modifications:
- Add the `--allow-script-in-comments` option if available so that
Javadoc does not fail with the `<script>` tag in the `-bottom` option
- Note that we add this option only for `site:javadoc`. Other modules
will not add it for improved security.
Result:
- Build does not fail with JDK 1.8.0_121
=> Fix Javadoc generation failure

zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java, zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/TestBase.java, zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Fixes #431 
This is an alternative to #432 which removes log spam from non-closed zookeeper clients by making sure to close all clients.
Additional changes:
- Raises the zookeeper startup timeout a little, it was too fast for my Mac
- Creates child node data persistently instead of ephemereally. This was probably intended, and only happened to work because the connection wasn't closed.
- Adds a sync after updating endpoints in zookeeper, the watcher would run too slow without it. I'm not sure if this is idiomatic.
=> Close all zookeeper connections opened in test code.

jetty/src/main/java/com/linecorp/armeria/server/http/jetty/JettyService.java, jetty/src/main/java/com/linecorp/armeria/server/http/jetty/JettyServiceBuilder.java, jetty/src/main/java/com/linecorp/armeria/server/http/jetty/JettyServiceConfig.java
Motivation:
Since Jetty 9.4, DefaultSessionIdManager requires a Jetty Server
instance as a constructor parameter, which means a user cannot create it
until a Server instance is actually created. It is currently impossible
to achieve this with JettyService because JettyServiceBuilder requires
a SessionIdManager instance rather than its factory.
Modifications:
- Add JettyServiceBuilder.sessionIdManagerFactory() so that a user can
create a SessionIdManager lazily
Result:
Better customizability of Jetty Server
=> Allow the lazy instantiation of Jetty SessionIdManager

core/src/main/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounter.java, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounterTest.java
Motivation:
The test coverage of SlidingWindowCounter seems inconsistent because
SlidingWindowCounterTest does not test the case where ticker goes
backward explicitly.
Modifications:
- Add a test that reproduces the case where time ticker goes backward
- Migrate from Hamcrest to AssertJ
Result:
- More consistent test coverage value (CI will complain less.)
=> Make the test coverage of SlidingWindowCounter consistent

core/src/main/java/com/linecorp/armeria/common/MediaTypeSet.java, core/src/main/java/com/linecorp/armeria/common/SerializationFormat.java, core/src/main/java/com/linecorp/armeria/common/SerializationFormatProvider.java, core/src/test/java/com/linecorp/armeria/common/MediaTypeSetTest.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/THttp2Client.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp1Test.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp2Test.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
Motivation:
THttpService fails to handle the 'accept' HTTP header whose value
contains:
- comma-separated media ranges
- a wildcard range
- a range with a qvalue parameter
Modifications:
- Add MediaTypeSet which provides the utility methods for content
negotiation
- Make SerializationFormat.find() accept media ranges
- Change the return type of SerializationFormat.mediaTypes() from Set to
MediaTypeSet
- Fix THttpService to handle the 'accept' HTTP header correctly
Result:
- Fixes #443
=> Add MediaTypeSet and handle 'accept' header properly in THttpService

thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java, thrift/src/test/java/com/linecorp/armeria/client/thrift/THttpClientBadSeqIdTest.java
Motivation:
We should ensure that the seqids of a Thrift call and its reply are
identical, because otherwise the client may end up using the wrong reply
when the server is ill-behaving.
Modifications:
- Raise TApplicationException with BAD_SEQUENCE_ID when seqids do not
match
Result:
- Safety
=> Ensure the seqids of Thrift call and its reply are identical

core/src/main/java/com/linecorp/armeria/client/http/encoding/DeflateStreamDecoderFactory.java, core/src/main/java/com/linecorp/armeria/client/http/encoding/GzipStreamDecoderFactory.java, core/src/main/java/com/linecorp/armeria/client/http/encoding/HttpDecodedResponse.java, core/src/main/java/com/linecorp/armeria/client/http/encoding/HttpDecodingClient.java, core/src/main/java/com/linecorp/armeria/client/http/encoding/StreamDecoder.java, core/src/main/java/com/linecorp/armeria/client/http/encoding/StreamDecoderFactory.java, core/src/main/java/com/linecorp/armeria/client/http/encoding/ZlibStreamDecoder.java, core/src/main/java/com/linecorp/armeria/client/http/encoding/package-info.java, core/src/test/java/com/linecorp/armeria/client/http/HttpClientIntegrationTest.java
Fixes #444 
TBH, I have no idea what an EmbeddedChannel does, but I found it in Netty while looking for a solution for incremental decoding and it seems to work. Let me know if this is a bad idea. If it is, I can't find another way than collecting all the response bytes before decoding, disabling streaming functionality.
Also went ahead and made the compression algorithm extensible, can apply something similar to the server-side at some point.
Extra change: add a missing copyright header.
=> Add an HTTP content decoding client decorator.

core/src/main/java/com/linecorp/armeria/client/NonDecoratingClientFactory.java, core/src/main/java/com/linecorp/armeria/client/SessionOption.java, core/src/main/java/com/linecorp/armeria/client/SessionOptions.java, core/src/main/java/com/linecorp/armeria/client/http/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/http/HttpSessionChannelFactory.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/internal/http/Http1ObjectEncoder.java, core/src/test/java/com/linecorp/armeria/client/http/HttpClientPipeliningTest.java
Motivation:
Some users want to disable HTTP/1 pipelining which is enabled by
default.
Modifications:
- Add SessionOption.USE_HTTP1_PIPELINING which enables or disables
HTTP/1 pipelining (default: enabled)
- Update HttpClientDelegate so that it respects USE_HTTP1_PIPELINING
- Add HttpClientPipeliningTest that tests both pipelined and
non-pipelined requests
- Fix various bugs uncovered by the test
- Fix a bug where NonDecoratingClientFactory chooses wrong Channel
types without respecting the EVENT_LOOP_GROUP option
- Fix a bug where DefaultStreamMessage.closeFuture() is sometimes
not completed at all when its subscription is cancelled
- Fix a potential bug where HttpClientDelegate may not return a
Channel back to its pool
- Fix a bug where Http1ObjectEncoder does not write LastHttpContent …
=> Add an option to enable/disable HTTP/1 pipelining and fix related bugs

core/src/main/java/com/linecorp/armeria/server/http/HttpResponseSubscriber.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java
Motivation:
HttpResponseSubscriber.failAndResponse does not set RequestLog.statusCode
when failing a request, resulting in '-1' status code.
Modifications:
- Set RequestLog.statusCode in failAndResponse()
Result:
- RequestLog.statusCode is set to 404, 500 or 503 when the request is
failed by HttpResponseSubscriber
=> Set RequestLog.statusCode when failing a response

thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftService.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
Motivation:
When a Thrift client sends a request with content type
'application/thrift' without a 'protocol' parameter, THttpService
currently can choose a non-default SerializationFormat.
Modifications:
- Choose the default Thrift SerializationFormat when a Thrift client
sends a request with content type 'application/thrift'.
- Add a test case written by @imasahiro
Result:
- Fixes #458
=> Choose correct SerializationFormat when content-type is 'application/thrift'

core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java, core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java, zipkin/src/main/java/com/linecorp/armeria/server/tracing/AbstractTracingService.java, zipkin/src/test/java/com/linecorp/armeria/server/tracing/TracingServiceTest.java
Motivation:
- There's currently no way for a user to add a callback to the context
that is not created and pushed yet. A user may want such a callback
mechanism so that he or she can implement attribute inheritance when
contexts are nested. e.g. Sending a request while serving a request
- RequestContext.onEnter/Exit() uses a Runnable as a callback. This
removes the chance of optimization when a user has a callback that
accesses the current context. e.g.
// A new Runnable is always created.
ctx.onEnter(() -> ctx.attr(...));
// One Consumer instance could be reused if:
ctx.onEnter(myCtx -> myCtx.attr(...));
Modifications:
- Add RequestContext.onChild(BiConsumer) which allows a user to add a
callback to the context that's not created yet
- Add onEnter(Consumer) and onExit(Consumer)
- …
=> Add RequestContext.onChild() and more onEnter/Exit() variants

core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java, core/src/main/java/com/linecorp/armeria/client/ClientDecorationBuilder.java, core/src/main/java/com/linecorp/armeria/client/DecoratingClient.java, core/src/main/java/com/linecorp/armeria/client/DecoratingClientFunction.java, core/src/main/java/com/linecorp/armeria/client/FunctionalDecoratingClient.java, core/src/main/java/com/linecorp/armeria/client/SimpleDecoratingClient.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java, core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java, core/src/main/java/com/linecorp/armeria/client/logging/DropwizardMetricCollectingClient.java, core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/main/java/com/linecorp/armeria/server/DecoratingService.java, core/src/main/java/com/linecorp/armeria/server/DecoratingServiceFunction.java, core/src/main/java/com/linecorp/armeria/server/FunctionalDecoratingService.java, core/src/main/java/com/linecorp/armeria/server/SimpleDecoratingService.java, core/src/main/java/com/linecorp/armeria/server/http/auth/HttpAuthService.java, core/src/main/java/com/linecorp/armeria/server/http/encoding/HttpEncodingService.java, core/src/main/java/com/linecorp/armeria/server/logging/DropwizardMetricCollectingService.java, core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java, core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLoggingService.java, core/src/test/java/com/linecorp/armeria/server/ServerTest.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java, thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, thrift/src/test/java/com/linecorp/armeria/it/metrics/DropwizardMetricsIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java, zipkin/src/main/java/com/linecorp/armeria/client/tracing/AbstractTracingClient.java, zipkin/src/main/java/com/linecorp/armeria/server/tracing/AbstractTracingService.java
Motivation:
Decoration of Clients and Services is not simple enough yet.
Modifications:
- Add SimpleDecoratingService/Client which requires only two type
parameters
- Add DecoratingClientFunction which is similar to DecoratingServiceFunction
- Add Client(Decoration)Builder.decorator() that accepts DecoratingClientFunction
- Use SimpleDecoratingService/Client or DecoratingClient/ServiceFunction
wherever possible
Result:
Tad bit easier to write a decorator
=> Simplify client and service decoration

core/src/main/java/com/linecorp/armeria/common/MediaTypeSet.java, thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftSerializationFormatProvider.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
Motivation:
Some clients seem to append the 'charset=utf-8' parameter to the media
types/ranges specified in the 'content-type' and 'accept' headers of a
Thrift request. This leads the THttpService to respond with '415
Unsupported Media Type' which may be confusing to a user.
Modifications:
- Add the media types with the 'charset=utf-8' parameter to
ThriftSerializationFormatProvider
- Clean up MediaTypeSet.containsAllParameters for clarity
Result:
- Fixes #473
- THttpService now accepts the media types with the 'charset=utf-8'
parameter.
=> Allow 'charset=utf-8' parameter in 'content-type' and 'accept' headers of Thrift requests

zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
I get this failure a lot so propose disabling for now. Maybe we can remove it too - does armeria do anything special for connection recovery vs the standard zookeeper client?
=> Ignore flaky zookeeper test for now.

build.gradle, shaded-test/build.gradle
Motivation:
The tests in the 'shaded-test' module uses one big merged classpath for
all test tasks. It works in most cases but it cannot test the backward
compatibility projects like 'thrift0.9' and 'tomcat8.0'.
Modifications:
- Create a dedicated configuration for each project so that the projects
with conflicting dependencies (e.g. 'thrift' and 'thrift0.9') can
coexist
- Make 'shaded-test' run the tests for 'backwardCompatProjects' as well
- Add 'tomcat8.0' to 'backwardCompatProject', which is going to be added
in the near future
Result:
- The backward-compat projects are also tested properly.
- './gradlew shaded-test:dependencies' shows the dependency graphs for
all shaded projects
=> More fine-grained classpath generation for shaded-test

tomcat/src/test/java/com/linecorp/armeria/server/http/tomcat/UnmanagedTomcatServiceTest.java
- Use TomcatUtil.engine(Service) to make UnmanagedTomcatServiceTest work
for different Tomcat versions
=> Fix NoSuchMethodError in UnmanagedTomcatServiceTest.createTomcat()

core/src/main/java/com/linecorp/armeria/common/logging/RequestLogAvailabilitySet.java, core/src/test/java/com/linecorp/armeria/common/logging/RequestLogAvailabilitySetTest.java
Motivation:
RequestLogAvailabilitySet.of(int) returns a wrong RequestLogAvailibilitySet
or null because of a bug in its instance prepopulation logic.
Modifications:
- Fix the broken logic and add a test case
Result:
RequestLogListener is notified correctly.
=> Fix RequestLogAvailabilitySet.of(int)

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/EndpointHealthStateGaugeSet.java, core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Apply this change will fix healthy count not correct problem. Method
reference & lambda version have different bytecode. check
https://gist.github.com/kojilin/c09062812c1f76699f5567bdcd984cac#file-bytecode1-L105-L113
and
https://gist.github.com/kojilin/c09062812c1f76699f5567bdcd984cac#file-bytecode2-L98-L106
=> Fix health check metrics not correctly represent the state.

thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftDocServicePlugin.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServicePluginTest.java
Motivation:
Thrift compiler seems to have a bug that generates a weird field value
metadata such as:
new FieldValueMetadata(TType.STRUCT)
.. which doesn't make much sense because the metadata of a struct should
be represented as StructMetadata and should have a name.
Because we can't change this behavior, we need to implement a workaround
for this problem.
Modifications:
- Handle the case mentioned in the 'motivation' section
- An offending metadata is translated into
TypeSignature.ofUnresolved("unknown")
Result:
Robustness
=> Fix AssertionError in ThriftDocServicePlugin.toTypeSignature()

core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClient.java, core/src/main/java/com/linecorp/armeria/common/DefaultRpcResponse.java, core/src/main/java/com/linecorp/armeria/common/RpcResponse.java, core/src/main/java/com/linecorp/armeria/common/http/DeferredHttpResponse.java, core/src/main/java/com/linecorp/armeria/common/http/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java, core/src/main/java/com/linecorp/armeria/server/http/auth/HttpAuthService.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/MappedDynamicFunction.java, core/src/test/java/com/linecorp/armeria/common/RpcResponseTest.java, core/src/test/java/com/linecorp/armeria/server/http/auth/HttpAuthServiceTest.java
Motivation:
A user often ends up with quite verbose code when he or she wants to
defer the construction of a RpcResponse or an HttpResponse. For example:
// RpcResponse
DefaultRpcResponse res = new DefaultRpcResponse();
CompletableFuture<Object> future = doAsync();
future.whenComplete((value, cause) -> {
if (cause != null) {
res.completeExceptionally(cause);
} else {
res.complete(value);
}
});
return res;
// HttpResponse
DeferredHttpResponse res = new DeferredHttpResponse();
CompletableFuture<HttpResponse> future = doAsync();
future.whenComplete((actualRes, cause) -> {
if (cause != null) {
res.close(cause);
} else {
res.delegate(actualRes);
}
});
return res;
This pull request simplifies the code above into:
// RpcResponse
return RpcResponse.from(doAsync());
// HttpResponse
return …
=> More convenient deferred construction of RpcResponse and HttpResponse

core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java, core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java, core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java, core/src/main/java/com/linecorp/armeria/common/util/AbstractListenable.java, core/src/main/java/com/linecorp/armeria/common/util/Listenable.java, core/src/test/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroupTest.java
Motivations:
- A EndpointGroup that has delegated Endpoint (for example, OrElseEndpointGroup) does not notify endpoint list
change to listners (#498)
Modifications:
- All subclass of EndpointGroup extends DynamicEndpointGroup
- Merge DynamicEndpointGroup to EndpointGroup
Results:
- Endpoint list changes are notified to listers correctly
=> Notify all Endpoint list change to listners correctly

core/src/main/java/com/linecorp/armeria/client/retry/AbstractBackoff.java, core/src/main/java/com/linecorp/armeria/client/retry/AttemptLimitingBackoff.java, core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java, core/src/main/java/com/linecorp/armeria/client/retry/ExponentialBackoff.java, core/src/main/java/com/linecorp/armeria/client/retry/FixedBackoff.java, core/src/main/java/com/linecorp/armeria/client/retry/JitterAddingBackoff.java, core/src/main/java/com/linecorp/armeria/client/retry/RandomBackoff.java, core/src/test/java/com/linecorp/armeria/client/retry/BackoffTest.java, core/src/test/java/com/linecorp/armeria/client/retry/ExponentialBackoffTest.java, core/src/test/java/com/linecorp/armeria/client/retry/RandomBackoffTest.java
Related: #513 #514
Motivation:
- There's off-by-one validation error in RandomBackoff
- RandomBackoff uses Random.longs() which is expensive to create
- Backoff.withJitter() doesn't accept negative jitters
Modifications:
- Add AbstractBackoff that performs validation on numAttemptsSoFar
- Do not make JitterAddingBackoff delegate to RandomBackoff
- Fix the validation error in RandomBackoff
- Make RandomBackoff not create a LongSupplier every time when
generating a random number
Result:
- Fixes #513
- Fixes #514
- Efficiency
=> Improve randomized backoff

core/src/main/java/com/linecorp/armeria/common/http/HttpSessionProtocols.java
Change the comment on H2C from "over TLS" to "cleartext".
=> Fix a typo in a comment

grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormatProvider.java, grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormats.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormatsTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java
Browsers cannot use normal grpc because they don't support trailers, so a grpc-web spec exists that is basically the same as grpc but encodes trailers into the response body. It also talks about decoupling the protocol from HTTP/2, but armeria already does that :D
Spec:
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md
No reference implementation, but closest is at:
https://github.com/improbable-eng/grpc-web
Verified interop with the example in that repo.
=> Add support for grpc-web draft spec.

build.gradle, core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java
Motivation:
- './gradlew -Pleak test' does not work due to OutOfMemoryError.
- Test tasks do not output the leak error messages when Netty logs it.
Modifications:
- Adjust the heap usage of HttpServerTest when leak detection level is
'paranoid' so that OOME is not raised
- Print the output when the output contains 'LEAK:'
Result:
A developer can easily check if Armeria has any buffer leak.
=> Make leak test work

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframerTest.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshallerTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Some real leaks, some test-specific leaks. There are still a couple of leaks reported in tests after this in error cases which will take a bit more refactoring, so want to get these out first.
- Make sure to release buffer when there is an exception before transfering ownership
- Cancel client's response reading stream if there is a client-side error like timeout
- Close deframer when stream is cancelled
- Close framer / deframer in UnframedGrpcService
- Release intermediary bytebufs and those capture by mocks in unit tests
- Close deframer in ArmeriaServerCallTest by canceling the stream for tests where the stream is ignored. I don't like ArmeriaServerCallTest much since the flow for these streaming calls is too hard to understand (and results in this somewhat hacky code). I will replace …
=> Cleanup most GRPC test bytebuf leaks.

core/src/main/java/com/linecorp/armeria/client/NonDecoratingClientFactory.java, dependencies.yml
Motivation:
A bug in Netty's UnixResolverDnsServerAddressStreamProvider causes
domain name resolution fails with a NullPointerException.
Modifications:
- Avoid using UnixResolverDnsServerAddressStreamProvider
- Use DefaultDnsServerAddressStreamProvider instead
- Update Netty to 4.1.11
Result:
- NPE is gone.
=> Fix NPE when resolving a hostname

dependencies.yml, grpc/build.gradle, grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormatProvider.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java, grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
ArmeriaServerCallTest are very hard to maintain and reason about since they require running many different callbacks in precise order. While the speed of unit tests is nice, these aren't very useful, so we migrate them to normal client/server tests.
Also defines a separate stub interface for fine-grained unit testing. The copy of the upstream one will still be used for interopability tests, but this should be easier to maintain for unit tests. I don't like how in the upstream ones, many different cases are handled by request parameters which are somewhat opaque.
Also follows AbstractThriftOverHttpTest pattern by using the upstream client to test server behavior and interopability in one go. Uses grpc-okhttp instead of grpc-netty to prevent netty version conflicts so this should be …
=> Migrate main tests from ArmeriaServerCall to server tests.

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcStatus.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/TransportStatusListener.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/HttpStreamReaderTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
While examining error handling, I realized that GRPC server does not actually send an error response to the client in cases of transport errors (request too large / invalid, deadline) - it just resets the stream with HTTP/2 CANCEL. Note, this doesn't mean I don't need #521 as I would still like to be able to notify the server's business logic of cancellation and clear up stream resources.
This PR makes sure that non-business-logic exceptions are not returned to the client, but just result in a reset. It also renames to transportStatus and closeListener to match the naming of upstream grpc-java to make comparing the implementations simpler. 
Also:
- Use same translation of netty error codes to status as grpc
- Remove unused method
- Adds DisableOnDebug to test timeout. My previous attempt …
=> Rearrange callbacks for server error case to match GRPC semantics.

grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormats.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
I want to add fast JSON too for allowing REST services to be migrated to GRPC (hint, hint ;) ), but in the meantime slow JSON is useful to enable the debug form in a following PR.
=> Add support for slow JSON GRPC marshalling.

core/build.gradle, core/src/main/java/com/linecorp/armeria/client/metric/DropwizardMetricCollectingClient.java, core/src/main/java/com/linecorp/armeria/client/metric/PrometheusMetricCollectionClient.java, core/src/main/java/com/linecorp/armeria/client/metric/package-info.java, core/src/main/java/com/linecorp/armeria/common/metric/MetricLabel.java, core/src/main/java/com/linecorp/armeria/common/metric/PrometheusRegistry.java, core/src/main/java/com/linecorp/armeria/common/metric/package-info.java, core/src/main/java/com/linecorp/armeria/internal/metric/DropwizardMetricCollector.java, core/src/main/java/com/linecorp/armeria/internal/metric/DropwizardRequestMetrics.java, core/src/main/java/com/linecorp/armeria/internal/metric/PrometheusMetricRequestDecorator.java, core/src/main/java/com/linecorp/armeria/internal/metric/package-info.java, core/src/main/java/com/linecorp/armeria/server/http/metric/PrometheusExporterHttpService.java, core/src/main/java/com/linecorp/armeria/server/http/metric/package-info.java, core/src/main/java/com/linecorp/armeria/server/metric/DropwizardMetricCollectingService.java, core/src/main/java/com/linecorp/armeria/server/metric/PrometheusMetricCollectionService.java, core/src/main/java/com/linecorp/armeria/server/metric/package-info.java, core/src/test/java/com/linecorp/armeria/common/metric/PrometheusRegistryTest.java, core/src/test/java/com/linecorp/armeria/internal/metric/DropwizardMetricCollectorTest.java, dependencies.yml, grpc/src/test/java/com/linecorp/armeria/it/grpc/DropwizardMetricsIntegrationTest.java, spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java, spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java, thrift/src/test/java/com/linecorp/armeria/it/metrics/DropwizardMetricsIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/metrics/PrometheusMetricsIntegrationTest.java
Motivation:
We would like Armeria to record and export Prometheus metrics.
Modifications:
- Add Prometheus dependencies
- Add service and client decorator (combined)
- Add wrapper for registry for concurrent access
- Add Prometheus HTTP exporter
=> Add Prometheus request metrics to armeria-core

core/src/main/java/com/linecorp/armeria/common/http/PathParamExtractor.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctionEntry.java, core/src/test/java/com/linecorp/armeria/common/http/PathParamExtractorTest.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServiceTest.java
Related #553 
Motivation:
- The current `DynamicHttpService` doesn't handle the path which doesn't include a path variable. However some API might get data from the request's body instead of its path, e.g, content type of `application/x-www-form-urlencoded`.
- This might be fixed via #553 in another way. But I need to use this fix before #553 merged.
Modifications:
- `PathParamExtractor.extract` would return `null` instead of an empty map when there's no matched path.
- `DynamicHttpFunctionEntry` might return `MappedDynamicFunction` with empty arguments map.
=> Change the behavior of DynamicHttpFunctionEntry.bind() to allow no-variable path

dependencies.yml, grpc/build.gradle, grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java, grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientFactory.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcJsonUtil.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshallerTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Also adds support for JSON to armeria grpc client. It's unlikely this would be used in practice, but is useful for unit tests. Switches the JSON test to use the armeria client.
=> Switch to protobuf-jackson for json marshalling.

core/src/main/java/com/linecorp/armeria/server/CatchAllPathMapping.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServiceTest.java
Without this, doc service does not handle endpoints for services mounted `serviceUnder("/"`, common for gRPC. It was actually almost implemented already...
=> Allow catch-all mapping to expose prefix for DocService.

core/src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java, core/src/test/java/com/linecorp/armeria/internal/ConnectionLimitingHandlerIntegrationTest.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java, thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
Motivation:
HttpServerTest.testTimeout() sometimes fails with the following
assertion failure:
com.linecorp.armeria.server.http.HttpServerTest > testTimeout[1: h1] FAILED
Expected: is <503>
but: was <200>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.linecorp.armeria.server.http.HttpServerTest.testTimeout(HttpServerTest.java:407)
which means the server sent the '503 Service Unavailable' response
correctly, but the RequestLog in the queue contains '200 OK'.
We clean the queue of RequestLogs before starting each test, but it is
possible that the RequestLog of the previous test is added *after* the
next test is started. i.e. '200 OK' ResponseLog may not be for the
current test. …
=> Potential fix for flaky HttpServerTest.testTimeout()

build.gradle, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java, core/src/test/java/com/linecorp/armeria/server/ServerTest.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServiceTest.java, core/src/test/java/com/linecorp/armeria/server/http/auth/HttpAuthServiceTest.java, shaded-test/build.gradle, testing/src/main/java/com/linecorp/armeria/testing/common/AnticipatedException.java, testing/src/main/java/com/linecorp/armeria/testing/common/package-info.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
Motivation:
- The dot (.) progress display interferes with the progress output of
Gradle 3.5, resulting in ugly terminal.
- Some test outputs printed are not very interesting because they
contain only expected exceptions
- The tasks created by 'shaded-test' look ugly when a project name
contains a hyphen (-). e.g. testSpring-boot should be testSpringBoot.
Modifications:
- Do not print the progress dots
- Add a new exception called 'ExpectedException' and use it for expected
exceptions
- Do not print the test output if it contains only ExpectedExceptions
- Do not print the test output if it contains a false positive
- Fix task name generation in 'shaded-test'
Result:
- Cleaner build output
=> Cleaner build output

core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctionImpl.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctions.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/Methods.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/ParameterEntry.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServiceTest.java, core/src/test/java/com/linecorp/armeria/server/http/TestConverters.java, core/src/test/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpServiceBuilderTest.java
Motivation:
AggregatedHttpMessage is useful for the most cases of restful API.
So it is better to aggregate stream messages automatically and inject the aggregated message into a DynamicHttpFunction method.
Modifications:
- Inject AggregatedHttpMessage into a DynamicHttpFunction method automatically.
- Support AggregatedHttpMessage as a return type.
Result:
Fixes #562.
=> Inject AggregatedHttpMessage into a DynamicHttpFunction method automatically

core/src/main/java/com/linecorp/armeria/common/http/HttpMessageAggregator.java, core/src/main/java/com/linecorp/armeria/common/http/HttpRequest.java, core/src/main/java/com/linecorp/armeria/common/http/HttpRequestAggregator.java, core/src/main/java/com/linecorp/armeria/common/http/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/http/HttpResponseAggregator.java, core/src/test/java/com/linecorp/armeria/common/http/DefaultHttpRequestTest.java, core/src/test/java/com/linecorp/armeria/common/http/DefaultHttpResponseTest.java
Motivation:
HttpMessageAggregator and its subtypes were relying on
Subscriber.onError() and onComplete() to get notified when an HTTP
message stream is closed. However, they are not invoked when the message
is aborted or cancelled due to timeout, leaving the future returned by
aggregate() never fulfilled.
Modifications:
- Use StreamMessage.closeFuture() to always get notified when a stream
being aggregated is closed
- Overall clean-up
- Move the common code up from HttpRequest/ResponseAggregator to
HttpMessageAggregator
- Make most methods in HttpMessageAggregator final
- Add test cases
Result:
- Fixes #571
=> Notify HTTP message aggregation future even on abortion

retrofit2/src/main/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactory.java, retrofit2/src/test/java/com/linecorp/armeria/client/http/retrofit2/ArmeriaCallFactoryTest.java
Apply this change will use okhttp3.HttpUrl's getEncodedQuery and getEncodedPath api to build the armeria's url path & query. These API will follow @Path and @Query's encoded param.
=> Fix query and path not encoded as expected.

core/src/main/java/com/linecorp/armeria/client/http/DefaultHttpClient.java, core/src/main/java/com/linecorp/armeria/client/http/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/common/http/HttpResponse.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/MappedDynamicFunction.java
Motivation:
HttpResponse has ofFailed() while RpcResponse has ofFailure(). We need
consistency here.
Modifications:
- Rename HttpResponse.ofFailed() to ofFailure()
- Add back HttpResponse.ofFailed() and deprecate it
Result:
Consistency
=> Rename HttpResponse.ofFailed() to ofFailure()

core/src/main/java/com/linecorp/armeria/client/http/DefaultHttpClient.java, core/src/main/java/com/linecorp/armeria/common/http/AggregatedHttpMessage.java, core/src/main/java/com/linecorp/armeria/common/http/HttpRequest.java, core/src/main/java/com/linecorp/armeria/server/http/dynamic/DynamicHttpFunctions.java, core/src/test/java/com/linecorp/armeria/common/http/DefaultAggregatedHttpMessageTest.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
.. so that a user can write more concise code:
// Before:
AggregatedHttpMessage aReq = ...;
DefaultHttpRequest req = new DefaultHttpRequest(aReq.headers());
req.write(aReq.content());
req.close();
AggregatedHttpResponse aRes = ...;
DefaultHttpResponse res = new DefaultHttpResponse();
res.respond(aRes);
// After:
AggregatedHttpMessage aReq = ...;
HttpRequest req = aReq.toHttpRequest();
AggregatedHttpResponse aRes = ...;
HttpResponse res = aRes.toHttpResponse();
This commit also makes the following additional changes:
- Add more variants of AggregatedHttpMessages.of() for convenience
- Use AggregatedHttpMessage.toHttpRequest/Response() where possible
Result:
- Fixes #575
=> Add AggregatedHttpMessage.toHttpRequest/Response()

spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java, spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceRegistrationBean.java, spring-boot/autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
Motivation:
Example headers make debugging more useful.
Modification:
- getter/setter for example headers in `ThriftServiceRergistrationBean`
Result:
- Users can utilize predefined headers in DocService debugging form.
=> Enable example headers in ThriftServiceRegistrationBean

core/src/main/java/com/linecorp/armeria/server/DefaultPathMapping.java, core/src/test/java/com/linecorp/armeria/server/DefaultPathMappingTest.java
Motivation:
For example, the following will fail:
PathMapping.of("/{0}");
.. because we use the path parameter name a user specified in verbatim
when building a regular expression. We don't really need to use named
capturing groups in the generated regular expression. We can simply keep
an array which contains the path parameter names in the order of
appearance and then map the capturing group number into a path parameter
name at O(1) time.
Modifications:
- Use numbered capturing groups for the regular expression generated by
DefaultPathMapping
Result:
- Fixes #586
=> Support path parameter names that start with a digit

core/src/main/java/com/linecorp/armeria/server/PathMappings.java, testing/src/main/java/com/linecorp/armeria/testing/server/webapp/WebAppContainerTest.java
Motivation:
There's a bug in PathMappings.apply() where it reuses the cached
PathMappingResult even when query strings are different from the current
request.
Modifications:
- Do not cache PathMappingResult when a request contains a query string
Result:
A query string is not polluted by the PathMappingResult cache.
=> Do not cache PathMappingResult when query string exists

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java, core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java, core/src/test/java/com/linecorp/armeria/server/GlobPathMappingTest.java, core/src/test/java/com/linecorp/armeria/server/PathMappingTest.java
Motivation:
There's currently no simple way to get the value of '*' or '**' in a
glob path pattern.
Modifications:
- Make GlobPathMapping produce an integer-indexed path parameter map
- Modify AnnotatedHttpServices.pathMapping() so that the path parameters
of a glob path pattern is handled correctly when an annotated service is
bound with a prefix
Result:
- Fixes #569
=> Add path parameter support to glob path patterns

core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContext.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
Failing all callbacks when a context is timed out can prevent cleanup logic, etc from being run. It is better to leave it up to the user which callbacks are safe to cancel or not.
=> Remove exception throwing when a context is timed out.

grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocStringExtractor.java
It's quite normal for the same key to be present in multiple files when both APIs import the same dependency (common with google standard dependencies like Timestamp).
=> Allow duplicate docstring keys in grpc docstring extractor.

core/src/main/java/com/linecorp/armeria/common/http/HttpMessageAggregator.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java, core/src/main/java/com/linecorp/armeria/internal/http/ByteBufHttpData.java, core/src/main/java/com/linecorp/armeria/internal/http/Http1ObjectEncoder.java, core/src/main/java/com/linecorp/armeria/internal/http/Http2ObjectEncoder.java, core/src/main/java/com/linecorp/armeria/internal/http/HttpObjectEncoder.java, core/src/test/java/com/linecorp/armeria/client/http/HttpClientIntegrationTest.java, core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java
Motivation:
- There's a buffer leak in DefaultStreamMessage.write() where a
ByteBufHttpData is not released when it's written after the stream is
closed.
- It is currently somewhat unclear how withPooledObjects works in the
documentation.
Modification:
- Clearly state that StreamMessage accepts a ReferenceCounted only when
it's a ByteBuf or a ByteBufHolder.
- Clearly state that the object will be released when it's attempted for
publication on a closed stream.
- Fix a leak in DefaultStreamMessage.write()
- Add more validation in DefaultStreamMessage.write()
- Make ByteBufHttpData implement ByteBufHolder and make
DefaultStreamMessage handle ByteBufHolder and ByteBuf correctly
Result:
- Safety
- Less leaks
=> Fix a leak in DefaultStreamMessage / Improve the life cycle contract of reference-counted objects in StreamMessage

core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/server/http/HttpResponseSubscriber.java, core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
Motivation:
DefaultStreamMessage does not release all pending objects when:
- the stream is closed by the publisher and
- the subscriber cancels its subscription when its demand is 0.
Modifications:
- Make sure cleanup() is invoked when the subscriber cancels its
subscription when the stream is closed so that all the pending objects
are released even if the subscriber's demand is 0.
- Make HttpResponseSubscriber.onNext() release HttpObjects received
after its state became DONE.
Result:
- Less leaks
=> Ensure DefaultStreamMessage cleans up the objects even when demand is 0

core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java, core/src/main/java/com/linecorp/armeria/client/Client.java, core/src/main/java/com/linecorp/armeria/client/ClientDecoration.java, core/src/main/java/com/linecorp/armeria/client/ClientDecorationBuilder.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java, core/src/main/java/com/linecorp/armeria/client/http/encoding/HttpDecodingClient.java, core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClient.java, core/src/main/java/com/linecorp/armeria/client/metric/DropwizardMetricCollectingClient.java, core/src/main/java/com/linecorp/armeria/client/metric/PrometheusMetricCollectingClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java, core/src/main/java/com/linecorp/armeria/common/Request.java, core/src/main/java/com/linecorp/armeria/common/Response.java, core/src/main/java/com/linecorp/armeria/server/Service.java, core/src/main/java/com/linecorp/armeria/server/http/auth/HttpAuthService.java, core/src/main/java/com/linecorp/armeria/server/http/auth/HttpAuthServiceBuilder.java, core/src/main/java/com/linecorp/armeria/server/http/auth/HttpAuthServiceImpl.java, core/src/main/java/com/linecorp/armeria/server/http/cors/CorsService.java, core/src/main/java/com/linecorp/armeria/server/http/cors/CorsServiceBuilder.java, core/src/main/java/com/linecorp/armeria/server/metric/DropwizardMetricCollectingService.java, core/src/main/java/com/linecorp/armeria/server/metric/PrometheusMetricCollectingService.java, core/src/test/java/com/linecorp/armeria/client/ClientDecorationBuilderTest.java, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java, kafka/src/main/java/com/linecorp/armeria/server/logging/structured/kafka/KafkaStructuredLoggingService.java, zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java, zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java
.. by assuming the type parameters of a Client or a Service are only one
of the following:
- HttpRequest and HttpResponse
- RpcRequest and RpcResponse
We give up the ability to use a subtype of these types as a type
parameter and take the simplicity of the decorator declarations.
For example:
public class MyService<I extends HttpRequest, O extneds HttpResponse> { ... }
myService = new MyService<HttpRequest, HttpResponse>();
// This works.
myService.decorate(HttpAuthService.newDecorator(...));
mySpecialService = new MyService<SpecialHttpRequest, SpecialHttpResponse>();
// This fails.
mySpecialService.decorate(HttpAuthService.newDecorator(...));
=> Simplify type parameters of Clients and Services

core/src/main/java/com/linecorp/armeria/common/http/AggregatedHttpMessage.java, core/src/main/java/com/linecorp/armeria/common/http/HttpRequest.java, core/src/main/java/com/linecorp/armeria/common/http/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/http/HttpResponseWriter.java, core/src/main/java/com/linecorp/armeria/internal/http/ArmeriaHttpUtil.java, core/src/main/java/com/linecorp/armeria/server/http/healthcheck/HttpHealthCheckService.java, core/src/test/java/com/linecorp/armeria/common/http/DefaultAggregatedHttpMessageTest.java, core/src/test/java/com/linecorp/armeria/server/http/healthcheck/HttpHealthCheckServiceTest.java, zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java, zipkin/src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceTest.java
- Add HTTP request and response construction methods to
AggregatedHttpMessage
- Add HTTP request construction methods to HttpRequest
- Ensure HttpResponse, HttpResponseWriter and AggregatedHttpMessage have
the same set of convenience methods
- The AggregatedHttpMessage created by AggregatedHttpMessage.of(status)
now has content
- Add missing 'mediaType' parameter to the construction methods who
require content
=> Add more convenience methods for constructing HTTP requests and responses

core/src/main/java/com/linecorp/armeria/common/http/DefaultHttpParameters.java, core/src/main/java/com/linecorp/armeria/common/http/HttpParameters.java, core/src/main/java/com/linecorp/armeria/common/http/ImmutableHttpHeaders.java, core/src/main/java/com/linecorp/armeria/common/http/ImmutableHttpParameters.java, core/src/main/java/com/linecorp/armeria/internal/DefaultValues.java, core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Converter.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Converters.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Delete.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Get.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Head.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Optional.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Options.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Param.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Patch.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Path.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Post.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Put.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/ResponseConverter.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/Trace.java, core/src/main/java/com/linecorp/armeria/server/http/annotation/package-info.java, core/src/test/java/com/linecorp/armeria/common/http/HttpParametersTest.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceBuilderTest.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java, core/src/test/java/com/linecorp/armeria/server/TestConverters.java, site/src/sphinx/server-basics.rst
Related to #580 
Motivation:
The other framework, such as Spring framework, provides query string parameter injection basically.
So it is better to support the feature on Armeria so that a user writes less codes.
We are going to support parameter injection for a query string of HTTP GET requests and URL-encoded form data of HTTP POST requests.
Modifications:
- Add `@Param` annotation for parameter injection.
- Add `HttpParameters` interface to inject every parameters.
- Replace `@PathParam` with `@Param` annotation. `@PathParam` is removed.
- Respond `400 Bad Request` if the request has not sufficient arguments or has an invalid argument. (was: `500 Internal Server Error`)
- Allow path pattern as a value of HTTP method annotations. e.g, `@Get("/path")`
- Add `@Optional` annotation to …
=> Inject a query string parameter as an annotated method argument

core/src/main/java/com/linecorp/armeria/common/http/HttpRequestDuplicator.java, core/src/main/java/com/linecorp/armeria/common/http/HttpResponseDuplicator.java, core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java, core/src/test/java/com/linecorp/armeria/common/http/HttpRequestDuplicatorTest.java, core/src/test/java/com/linecorp/armeria/common/http/HttpResponseDuplicatorTest.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
Motivation:
If a stream message is, once published to a subscriber, next subscriber cannot subscribe
the data again. A user may want to see just the head of data and decide to request other
subscriber to do more action according to the data of the head.
In that case, another subscriber cannot see the data consumed already.
We needed to provide the way that a publisher can be subscribed by multiple
subscribers, so a user can use the elements in different places.
Modifications:
- Add StreamMessageDuplicator that wraps a StreamMessage and spawns
Children stream messages can be subscribed one by one
- Add HttpResponseDuplicator and HttpRequestDuplicator
Result:
- A user can subscribe a publisher with multiple subscribers.
To-do:
- Limit the size of the buffered data in the factory
=> Add StreamMessageDuplicator

core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/PathMapping.java, core/src/main/java/com/linecorp/armeria/server/PrefixPathMapping.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java, core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java, core/src/main/java/com/linecorp/armeria/server/http/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/http/file/HttpFileService.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java, core/src/test/java/com/linecorp/armeria/server/PrefixPathMappingTest.java, core/src/test/java/com/linecorp/armeria/server/composition/CompositeServiceTest.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcRequestUtil.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java, jetty/src/main/java/com/linecorp/armeria/server/http/jetty/JettyService.java, logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java, tomcat/src/main/java/com/linecorp/armeria/server/http/tomcat/TomcatService.java
Currently, the way to get a stripped prefix path is `pathWithoutPrefix`, but we support internal redirects / arbitrary mapping with `PathMappingResult.path`, which is returned by `path`. This makes it mostly impossible to have a service respect both types of mapping.
This PR restores the behavior of prefix mapping stripping the input and allowing services to use the `mappedPath` which has been undeprecated.
We're basically back to before the HTTP-only PR, with `mappedPath` returning `PathMappingResult.path`.
Also removes `pathWithoutPrefix` since it's not needed with this change, and is very short lived so probably not worth deprecating.
=> Restore prefix mapping stripping to allow it to work together with arbitrarily mapped PathMappingResult

core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java, core/src/main/java/com/linecorp/armeria/client/retry/BackoffWrapper.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java, core/src/test/java/com/linecorp/armeria/client/retry/BackoffTest.java
Motivation:
If a client does not invoke `withMaxAttempts` on `Backoff` when it use `RetryingClient`, it can retry infinitely in certain circumstance.
That will consume bandwidth of network and overload the server side as well.
We need a safety mechanism that prevents that situation.
Modifications:
- Add `as` method to Backoff and BackoffWrapper
- Add com.linecorp.armeria.defaultBackoffMaxAttempts system property
- Add AttemptLimitingBackoff to the Backoff who doesn’t have it
Result:
- Close # 546
=> Provide a default value that limits the number of request try attempt

core/src/main/java/com/linecorp/armeria/client/ResponseTimeoutException.java, core/src/main/java/com/linecorp/armeria/client/SessionOptions.java, core/src/main/java/com/linecorp/armeria/client/WriteTimeoutException.java, core/src/main/java/com/linecorp/armeria/client/http/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/main/java/com/linecorp/armeria/common/ClosedSessionException.java, core/src/main/java/com/linecorp/armeria/common/ContentTooLargeException.java, core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/common/ProtocolViolationException.java, core/src/main/java/com/linecorp/armeria/common/stream/CancelledSubscriptionException.java, core/src/main/java/com/linecorp/armeria/common/stream/ClosedPublisherException.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java, core/src/main/java/com/linecorp/armeria/common/util/NativeLibraries.java, core/src/main/java/com/linecorp/armeria/internal/TransportType.java, core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, core/src/main/java/com/linecorp/armeria/server/RequestTimeoutException.java, core/src/main/java/com/linecorp/armeria/server/ResourceNotFoundException.java, core/src/main/java/com/linecorp/armeria/server/ServiceUnavailableException.java
Motivation:
It would be good to have a single central place to get the values of all
available JVM system properties that affect the runtime behavior of
Armeria.
Modifications:
- Add Flags and move System.getProperty() there
- Deprecate the methods that accesses the System properties in favor or
Flags
Result:
A user can find out what JVM system property options he or she can
specify to change the behavior of Armeria.
=> Move the JVM system property flags to Flags

core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
Motivation:
The default blockingTaskExecutor uses 0 core threads and an unbounded
task queue. This will make blockingTaskExecutor single-threaded because
ThreadPoolExecutor will spawn a new thread only when a task queue
rejects a task, which will never happen with an unbounded task queue.
Modifications:
- Set the number of the core threads to the maximum and allow the core
threads to be timed out instead.
Result:
The default blockingTaskExecutor is not single-threaded anymore.
=> Make the default blockingTaskExecutor utilize more than one thread

core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
Motivation:
DeferredStreamMessage.subscribeToDelegate() can subscribe to the
delegate twice when one thread calls subscribe() and the other one calls
delegate().
Modifications:
- Make sure subscribeToDelegate() call StreamMessage.subscribe() only
once by using CAS
Result:
- Fixes #623
=> Fix a race condition in DeferredStreamMessage.subscribeToDelegate()

spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java, spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java, spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/HttpServiceRegistrationBean.java, spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceRegistrationBean.java, spring-boot/autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
Motivation:
We forgot to add a registration bean for an annotated service object.
Modifications:
- Add AnnotatedServiceRegistrationBean
Result:
A user can add an annotated service object to a Server without using the
configurator.
=> Add the registration bean for an annotated service object

thrift/src/test/java/com/linecorp/armeria/client/thrift/THttpClientBadSeqIdTest.java, thrift/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
Motivation:
Flaky tests are annoying.
Modifications:
- Increase the timing tolerance of GracefulShutdownIntegrationTest to
reduce the chance of test failures on a ill-powered machine.
- Improve THttpClientBadSeqIdTest so that the cause of failure is better
known.
Result:
- Fixes #625
- Will get more clues about #624
=> Fix flaky tests

core/src/main/java/com/linecorp/armeria/client/http/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/http/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/http/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/client/http/HttpResponseDecoder.java, core/src/test/java/com/linecorp/armeria/client/http/HttpClientTimeoutTest.java
Motivation:
A client-side response can be closed unexpectedly due to various
reasons, most notably due to a ResponseTimeoutException. When it
happens, an HTTP/1 connection has to be closed and an HTTP/2 stream has
to be reset with CANCEL error code. We don't do anything.
Modifications:
- Close the connection when a response of an HTTP/1 connection is closed
unexpectedly.
- Reset the stream with CANCEL error code when a response of an HTTP/2
connection is closed unexpectedly.
Result:
Memory leak is fixed.
=> Fix memory leak which occurs when a client-side response stream is closed unexpectedly

core/src/main/java/com/linecorp/armeria/client/http/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/http/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/http/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/client/http/HttpResponseDecoder.java, core/src/test/java/com/linecorp/armeria/client/http/HttpClientTimeoutTest.java
Motivation:
A client-side response can be closed unexpectedly due to various
reasons, most notably due to a ResponseTimeoutException. When it
happens, an HTTP/1 connection has to be closed and an HTTP/2 stream has
to be reset with CANCEL error code. We don't do anything.
Modifications:
- Close the connection when a response of an HTTP/1 connection is closed
unexpectedly.
- Reset the stream with CANCEL error code when a response of an HTTP/2
connection is closed unexpectedly.
Result:
Memory leak is fixed.
=> Fix memory leak which occurs when a client-side response stream is closed unexpectedly (#632)

build.gradle
Motivation:
We currently do not print the log messages of failed tests, which is
sometimes a problem when a test failed in shaded-test but not in a
non-shaded one.
Modifications:
- Print the log message of failed tests for shaded-test as well
Result:
More build visibility
=> Print the log messages of failed tests for shaded-test

core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
Keep-alive is a very common term when referring to idle timeout, and having the term next to the setting makes it easier for users to find the appropriate setting when searching.
=> Add keep-alive term next to idle timeout to improve grepability.

core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java
Motivations:
When DocStringExtractor scans the docstring directory using Reflections,
the following messages can be logged:
06:16:52.582 [Test worker] DEBUG c.l.a.i.s.reflections.Reflections - could not scan file META-INF/armeria/grpc/armeria-test.dsc in url file:/C:/projects/armeria/shaded-test/build/classes/test-grpc/ with scanner SubTypesScanner
com.linecorp.armeria.internal.shaded.reflections.ReflectionsException: could not create class object from file META-INF/armeria/grpc/armeria-test.dsc
Although harmless, it can pollute the log file.
Modifications:
- Use only the necessary Scanners (ResourcesScanner only) when scanning
with Reflections in DocStringExtractor
Result:
- Less noise in a log file
=> Use only the necessary Scanners when scanning with Reflections

core/src/test/java/com/linecorp/armeria/client/retry/BackoffTest.java
The test case will pass even when no jitter is added, so revert it back to use a seeded Random and fixed assertions.
=> Revert the test case for Backoff.withJitter()

core/src/main/java/com/linecorp/armeria/client/ClientFactory.java, core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java, core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java, core/src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java, core/src/main/java/com/linecorp/armeria/common/CommonPools.java, core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java, core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java, core/src/main/java/com/linecorp/armeria/internal/ChannelUtil.java, core/src/main/java/com/linecorp/armeria/internal/ConnectionLimitingHandler.java, core/src/main/java/com/linecorp/armeria/server/Server.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, core/src/test/java/com/linecorp/armeria/client/HttpClientPipeliningTest.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java, core/src/test/java/com/linecorp/armeria/internal/ConnectionLimitingHandlerIntegrationTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java, core/src/test/java/com/linecorp/armeria/server/ServerTest.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java, thrift/src/main/java/com/linecorp/armeria/internal/thrift/ThriftFieldAccess.java, thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftStructuredLoggingTest.java
Motivation:
A simple application would use the default settings usually, and it will
make each ClientFactory and Server has its own EventLoopGroups, which
may create too many event loop threads.
Modifications:
- Add CommonPools that provides the common EventLoopGroups and blocking
task Executor which are used when a user did not override the default
- Make a user specify whether to shutdown the EventLoopGroups when
specifying them
- ClientFactory and Server do not create a new EventLoopGroup by
themselves anymore
- Add EventLoopGroups.newEventLoopGroup() utility method so that a
user can create a compatible EventLoopGroup easily instead
- Fix flakiness of ServerTest
- Fix flakiness of ThriftStructuredLoggingTest
- Clean up GrpcClientTest
Result:
- Saner default behavior
- …
=> Add common EventLoopGroups and blocking task Executor

core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
Also:
- Sort the header names alphabetically
- Fix incorrect use of `@deprecated` Javadoc tag
Related:
- https://github.com/netty/netty/pull/6904
=> Add 'content-security-policy' and 'x-frame-options' to HttpHeaderNames

core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java, core/src/main/java/com/linecorp/armeria/server/DefaultPathMapping.java, core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java, core/src/main/java/com/linecorp/armeria/server/RegexPathMapping.java, core/src/test/java/com/linecorp/armeria/server/CatchAllPathMappingTest.java, core/src/test/java/com/linecorp/armeria/server/DefaultPathMappingTest.java, core/src/test/java/com/linecorp/armeria/server/ExactPathMappingTest.java, core/src/test/java/com/linecorp/armeria/server/GlobPathMappingTest.java, core/src/test/java/com/linecorp/armeria/server/PrefixAddingPathMappingTest.java, core/src/test/java/com/linecorp/armeria/server/PrefixPathMappingTest.java, core/src/test/java/com/linecorp/armeria/server/RegexPathMappingTest.java
Motivation:
- For some cases, a user may get `__UNKNOWN__` as `loggerName` and/or `__UNKNOWN_PATH__` as `metricName`.
Modifications:
- Set `loggerName` and `metricName` when instantiating `PrefixAddingPathMapping` and `DefaultPathMapping` class.
- A glob pattern not starting with '/' will be treated as `/**/..pattern..` for `loggerName` and `metricName`.
- Make `metricName` of `RegexPathMapping` as `/regex:...` instead of `regex:...`.
Result:
- Fixes #651
=> Fix PathMapping implementations to produce their loggerName and metricName correctly

core/src/main/java/com/linecorp/armeria/client/http/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/http/HttpClientFactory.java, core/src/test/java/com/linecorp/armeria/server/http/HttpServerTest.java
Motivation:
HttpClientDelegate.pool() lazily creates a KeyedChannelPool which pools
TCP/IP connections. When a new pool is created, as a defensive measure,
pool() adds a listener to the terminationFuture() of EventLoop which
closes the all connections in the pool and removes itself from the map
of pools.
However, this can lead to a leak when a lot of HttpClientDelegates are
created because the listeners added to EventLoop.terminationFuture()
will linger until the EventLoop shuts down, which usually never happens
until the application shuts down.
It is also notable that it's not a good idea to close connections in
terminationFuture()'s listeners, because it's impossible to perform I/O
in a terminated EventLoop in Netty.
Modifications:
- Keep the number of HttpClientDelegates per …
=> Fix EventLoop.terminationFuture() listener leak

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/retry/HttpStatusBasedRetryStrategy.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java, core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java, core/src/main/java/com/linecorp/armeria/internal/HttpHeaderSubscriber.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
Motivation:
Currently, response timeout is applied to an individual retry made by RetryingClient.
However, the timeout needs to happen when the time passed timout milliseconds from the first attempt.
Modification:
- Add timestamp and reset the responseTimeoutMillis whenever retries is made
Result:
Close #627
=> Enable response timeout is enforced across the retries by RetryingClient

core/src/main/java/com/linecorp/armeria/client/ClientFactory.java, core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java, core/src/main/java/com/linecorp/armeria/client/Endpoint.java, core/src/main/java/com/linecorp/armeria/client/EventLoopScheduler.java, core/src/main/java/com/linecorp/armeria/client/NonDecoratingClientFactory.java, core/src/main/java/com/linecorp/armeria/client/UserClient.java, core/src/main/java/com/linecorp/armeria/client/http/DefaultHttpClient.java, core/src/main/java/com/linecorp/armeria/client/http/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/http/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/http/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/http/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/http/HttpSessionChannelFactory.java, core/src/main/java/com/linecorp/armeria/client/pool/PoolKey.java, core/src/main/java/com/linecorp/armeria/common/util/ReleasableHolder.java, core/src/test/java/com/linecorp/armeria/client/EventLoopSchedulerTest.java, grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java, zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java
Motivations:
Armeria currently keeps a client connection pool for each EventLoop. It
means, when a user sends a client request from N different EventLoops,
N new connections will be created. It is not a problem for light usage
but it can consume large amount of resources when the number of
EventLoops and the kinds of Endpoints get bigger.
Modifications:
- Add ClientFactory.acquireEventLoop(Endpoint) which enables a client
implementation to choose the EventLoop which is more likely to have an
idle Channel connected to the desired Endpoint.
- Add EventLoopScheduler which provides the implementation of
acquireEventLoop(Endpoint)
- Use ClientFactory.acquireEventLoop(Endpoint) wherever possible
- UserClient
- ArmeriaChannel (gRPC)
- Add ReleasableHolder
- Fix …
=> Increase the chance of reusing idle client connections

core/src/main/java/com/linecorp/armeria/client/http/HttpClientFactory.java, core/src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java
Motivation:
DefaultKeyedChannelPool uses Deque in FIFO manner to manage available
channels. This has the following issues:
- An older channel gets higher chance of acquisition. This increases
overall lifespan of an idle channel unnecessarily.
- We do not clean up the connections which were closed while they are in
the Deque. They will eventually be cleaned up, but it may take longer
time than expected, combined with the first issue.
Modifications:
- Use LIFO so that a recently used channel get higher chance of
acquisition.
- Clean up the both ends of the Deque so that the closed channels are
cleaned up more aggressively, combined with the first modification.
- Use synchronous health checks instead of the asynchronous one because
we do not need it for HTTP.
Result:
- Reduced memory …
=> Clean up the closed channels from DefaultKeyedChannelPool

build.gradle, core/src/test/java/com/linecorp/armeria/server/ServerTest.java, dependencies.yml, zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java, zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/TestBase.java, zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
- Fixes #639
- Fixes #477
- Do not use fixed port numbers
- Use Awaitility where necessary
- Give more tolerance to state transition tests
- Exclude unnecessary transitive dependencies pulled in by ZooKeeper
- Fix flaky ServerTest.testIdleTimeoutByNoContentSent() as well
=> Fix flaky tests in zookeeper module

core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java, core/src/main/java/com/linecorp/armeria/client/retry/BackoffSpec.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClientBuilder.java, core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/test/java/com/linecorp/armeria/client/retry/BackoffSpecTest.java
Motivation:
It would be very userful to define a string expression for a Backoff.
Modification:
- Add BackoffSpec that takes a backoff string expression as an argument and builds Backoff using it
- Add defaultBackoffSpec to Flags so that a user can specify it using system property
Result:
- A user can create default backoff using either Backoff.of() or defaultBackOffSpec system.property
- Close #628
=> Provide a way to specify a Backoff using a string expression

build.gradle, core/build.gradle, core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/common/stream/AbortedStreamException.java, core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/NeverInvokedSubscriber.java, core/src/main/java/com/linecorp/armeria/common/stream/NoopSubscription.java, core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java, core/src/test/java/com/linecorp/armeria/common/DefaultHttpRequestTest.java, core/src/test/java/com/linecorp/armeria/common/DefaultHttpResponseTest.java, core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageVerification.java, core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageVerification.java, core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageVerification.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorVerification.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java, dependencies.yml, settings.gradle
Motivations:
- Our StreamMessage implementations do not pass Reactive Streams TCK.
- The contract of StreamMessage.abort() is not clear enough. It is
undistinguishable for a Subscriber from a cancellation.
Modifications:
- Update Reactive Streams to 1.0.1-RC1
- Add Reactive Streams TCK 1.0.1-RC1 to the dependencies
- Add core:testNg task because TCK uses TestNG rather than JUnit
- Make sure core:testNg is included into test coverage
- Redefine the behavior of StreamMessage.abort()
- Add AbortStreamException
- Subscriber is notified with onError(AbortedStreamException)
- Add StreamMessageVerification which adds the tests on top of the TCK
- Make DefaultStreamMessage pass the TCK
- Make DeferrtedStreamMessage pass the TCK
- Make PublisherBasedStreamMessage pass the TCK
- Make …
=> Make StreamMessage implementations pass Reactive Streams TCK

core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java, core/src/main/java/com/linecorp/armeria/client/Clients.java, core/src/main/java/com/linecorp/armeria/client/HttpClient.java, core/src/main/java/com/linecorp/armeria/client/HttpClientBuilder.java, core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java, core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java, core/src/test/java/com/linecorp/armeria/client/HttpClientPipeliningTest.java, core/src/test/java/com/linecorp/armeria/client/HttpClientSniTest.java, core/src/test/java/com/linecorp/armeria/client/HttpClientTimeoutTest.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java, core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java, site/src/sphinx/client-http.rst, spring-boot/autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java, testing/src/main/java/com/linecorp/armeria/testing/server/webapp/WebAppContainerTest.java, thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
Motivation:
When a user creates an HttpClient, he/she needs to specify type parameters such as HttpClient.class for construction and HttpRequest.class, HttpResponse.class for the decorator which is painful.
We needed to simplify that.
Modifications:
- Add HttpClientBuilder whilch doesn't need to specify type parameters
- Add of(...) factory methods to HttpClient
- Replace old `HttpClient client = Clients.newClient()` to `HttpClient.of()` in test cases
- Modify RetryingHttpClientTest parameter a little bit and make client use different eventLoop from server's
Result:
- Simplified HttpClient creation
- Less flaky tests
=> Add HttpClientBuilder and factory methods to HttpClient

core/src/main/java/com/linecorp/armeria/common/CommonPools.java, core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java, core/src/main/java/com/linecorp/armeria/server/Server.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
Motivation:
Unless a user specified, Armeria uses the common boss and worker group
when building a Server. This can be a problem because all threads in the
common groups are daemon. If the user's main thread exits and there are
only the common group threads in the JVM, the JVM will choose to
terminate itself because all the remaining threads are daemon.
Modifications:
- Server now creates a dedicated single-thread boss EventLoopGroup for
each ServerPort, and the thread is non-daemon.
- Remove CommonPools.bossGroup
- Remove ServerConfig.bossGroup and shutdownBossGroupOnStop
- Server sets the thread name of boss groups dynamically to show which
thread is handling which server port.
- Server terminates the boss groups lastly so that the JVM does not
terminate itself until the graceful …
=> Prevent premature shutdown of JVM when running a Server

core/src/main/java/com/linecorp/armeria/server/ArmeriaHttpException.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/ResourceNotFoundException.java, core/src/main/java/com/linecorp/armeria/server/ServiceUnavailableException.java, core/src/test/java/com/linecorp/armeria/server/HttpResponseExceptionTest.java
Motivations:
- The error behavior of HttpResponseSubscriber#onError is hard-coded and cannot customize error code.
Modifications:
- Add ArmeriaHttpException which makes more customizable error handling
Results:
- A user can customize error code through ArmeriaHttpException
- Fixes #543
=> Customize http status for error response

core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java
Modifications:
- Remove ‘abstract’ keyword.
- Add a constructor which creates a new instance with HTTP status code.
=> Improve the usability of HttpResponseException

.travis.yml, appveyor.yml
.. from 768m to 1024m to fix the problem where ProGuard takes too much time or fails due to GC overhead
Will merge once the build passes. /cc @hyangtack @minwoox
=> Increase the heap size for Gradle

core/src/main/java/com/linecorp/armeria/client/retry/ExponentialBackoff.java, core/src/main/java/com/linecorp/armeria/client/retry/HttpStatusBasedRetryStrategy.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClientBuilder.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClientBuilder.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClientBuilder.java, core/src/test/java/com/linecorp/armeria/client/retry/BackoffTest.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java, thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Motivation:
A `RetryingClient` may want to have different `Backoff` by the responses.
For example, the client wants to retry using exponential backoff when it gets `SERVICE_UNAVAILABLE`.
On the other hand, it wants to keep retrying without delay when it gets revision conflicts.
Modifications:
- Make all of the implementations of `Backoff` stateless
- Change the `shouldRetry` method returng `Optional<Backoff>`
Result:
- Close #655
- Users can choose `Backoff` accroding to the response
=> Modify RetryStrategy to return backoff according to the response

build.gradle, core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java, core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java, core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/internal/FlushConsolidationHandler.java, core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, core/src/test/java/com/linecorp/armeria/client/Http2ClientSettingsTest.java
Motivation:
A client cannot specify initial HTTP/2 settings, just have to use the default values.
Also, we cannot test Armeria server if it's working correctly with non-default HTTP/2 settings.
Modifications:
- Provide a way to configure initial HTTP/2 settings for client. Configurable settings are:
- Initial connection window size
- SETTINGS_INITIAL_WINDOW_SIZE (for stream-level)
- SETTINGS_MAX_FRAME_SIZE
Result:
- Clients are able to specify non-default HTTP/2 settings
- We can be sure that Armeria server is working well with non-default HTTP/2 settings
Miscellaneous:
- Fix typos in comments
=> Add session-level options for client-side initial HTTP/2 settings

core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
.. because ServerBuilder and AbstractVirtualHostBuilder should have the
same set of service-adding methods
/cc @demongaorui
=> Add service(ServiceWithPathMapping,...) to AbstractVirtualHostBuilder

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java, core/src/main/java/com/linecorp/armeria/common/metric/NoopMeterRegistry.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/test/java/com/linecorp/armeria/client/DefaultHttpClientTest.java, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java, logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java, zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java
Motivation:
Using SimpleMeterRegistry by default doesn't make much sense because a
user will always want to switch to a better MeterRegistry implementation
such as DropwizardMeterRegistry or PrometheusMeterRegistry.
Modifications:
- Add NoopMeterRegistry and use it by default
Result:
- Less overhead unless a user explicitly requested metric recording
=> Use NoopMeterRegistry by default

core/build.gradle, core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java, core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/MediaType.java, core/src/main/java/com/linecorp/armeria/common/RequestContext.java, core/src/main/java/com/linecorp/armeria/common/SerializationFormat.java, core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java, core/src/main/java/com/linecorp/armeria/common/util/NativeLibraries.java, core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/VirtualHost.java, core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeServiceBuilder.java, core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java, dependencies.yml, grpc/build.gradle, grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/StatusMessageEscaper.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/TimeoutHeaderUtil.java, tomcat8.0/build.gradle
- Update dependencies
- Brave 4.5.1 -> 4.5.2
- Caffeine 2.5.3 -> 2.5.5
- Checkstyle 8.0 -> 8.1
- Dropwizard Metrics 3.2.3 -> 3.2.4
- gRPC 1.4.0 -> 1.5.0
- Guava 22.0 -> 23.0
- JSON-unit 1.24.0 -> 1.25.0
- Kafka 0.10.2.1 -> 0.11.0.0
- Netty 4.1.13 -> 4.1.14
- Reactive Streams 1.0.1-RC1 -> 1.0.1
- Spring Boot 1.5.4 -> 1.5.6
- Tomcat 8.5.16 -> 8.5.20 / 8.0.45 -> 8.0.46
- Fix new checkstyle violations reported by 8.1
=> Update dependencies and fix checkstyle violations

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
.. because it seems like a better default than `NoopMeterRegistry`.
Note that we keep `NoopMeterRegistry` because it's still useful for
testing.
=> Use `Metrics.globalRegistry` as the default `MeterRegistry`

core/build.gradle, shaded-test/build.gradle
We did not include non-published Java projects from shaded tests, but
there's no reason that keeps us from doing so. With this change, ':it'
is also shade-tested.
=> Do shaded tests on all Java modules

core/src/main/java/com/linecorp/armeria/internal/metric/CaffeineMetricSupport.java, core/src/test/java/com/linecorp/armeria/internal/metric/CaffeineMetricSupportTest.java
Motivation:
Currently, CaffeineMetricsSupport raises an IllegalStateException when a
user tries to call setup() with different Cache instances at the same
metric ID. This can result in the failure of Server startup when a user
reuses a registry or uses a Metrics.globalRegistry.
Modifications:
- Improve CaffeineMetricsSupport so that it aggregates the stats of all
Cache instances instead of rejection
Result:
Less surprise to users
=> Make CaffineMetricSupport more tolerant to double registration

core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java, spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java, thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
.. because exporter and exposition are different things, as documented
in:
- https://prometheus.io/docs/instrumenting/writing_exporters/
- https://prometheus.io/docs/instrumenting/exposition_formats/
=> Rename PrometheusExporterHttpService to PrometheusExpositionService

build.gradle
.. so that a person who runs the release process is not confused why
.asc files are not uploaded.
=> Reject the publication of release JARs if signatory is missing

dependencies.yml, spring-boot/autoconfigure/build.gradle
Apply this change will remove spring-boot-actuator, spring-web and spring-webmvc.
e.g. Below code will be failed when we don't exclude dependencies.  
```
Caused by:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mappingJackson2HttpMessageConverter' defined in class path resource [org/springframework/boot/autoconfigure/web/JacksonHttpMessageConvertersConfiguration$MappingJackson2HttpMessageConverterConfiguration.class]: Unsatisfied dependency expressed through method 'mappingJackson2HttpMessageConverter' parameter 0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.fasterxml.jackson.databind.ObjectMapper' available: expected single matching bean but found 2: …
```
=> Remove unnecessary dependencies from micrometer-spring-legacy

core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
Related: https://github.com/micrometer-metrics/micrometer/issues/139
Motivation:
Specifying '1.0' as a monitored quantile makes WindowSketchQuantiles.get()
throw an IndexOutOfBoundsException.
Modifications:
- Exclude '1.0' from the monitored quantiles as a workaround
Result:
- No IIOBE
=> Work around IndexOutOfBoundsException in WindowSketchQuantiles.get()

build.gradle
We were setting target=_blank for internal links.
=> Set target=_blank only for external links in Javadoc

core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
* Return status code 400 when annotated http service throwing IllegalArgumentException.
Currently only param check by armeria will be treat as 400 error. But user may want to do some param check with throwing IllegalArgumentException.
* Return correct status code when user code throws HttpResponseException.
=> Enhance Annotated http service exception handling

core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java, thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
See: https://github.com/line/armeria/issues/780
=> Client side Thrift callback not notified correctly for a void method with RetryingRpcClient (#780)

thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
Because there is no way to notify server-side exception to client on
one-way thrift API, thrift service does not need to return exception
response.
Results
- Thrift service handles exception throwned one-way method correctly
- Fixes #782
=> Handle as success even if one way thrift function throw exception

core/src/main/java/com/linecorp/armeria/common/metric/MeterIdFunction.java, core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java, thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
- Do not use Strings.join() for single string in AbstractCompositeService
- Add missing 'hostnamePattern' tag to the default MeterIdFunction
=> Fix incorrect meter tags

core/src/main/java/com/linecorp/armeria/common/HttpMethod.java, core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java, core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Motivation:
Armeria's HttpMethod is an enum, and thus HttpMethod.valueOf() will
raise an exception when the given method name does not match any enum
values.
In contrast, Netty's HttpMethod is not an enum and thus supports
arbitrary method names.
As a result, when a user sends a request whose method is not supported
by Armeria's HttpMethod, the server will fail the request with an
unexpected IllegalArgumentException rather than sending '405 Method
Not Allowed' response.
Modifications:
- Add HttpMethod.isSupported(String)
- Add the validation of request method for HTTP/1 and 2
Result:
- Fixes #754
- Armeria responds with '405 Method Not Allowed' when a client sends a
request with unsupported method.
=> Do not throw exception on unsupported HTTP method

NOTICE.txt, build.gradle, core/build.gradle, core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java, core/src/main/java/com/linecorp/armeria/common/metric/RollingHdrQuantiles.java, core/src/main/java/com/linecorp/armeria/internal/metric/MicrometerUtil.java, core/src/test/java/com/linecorp/armeria/common/metric/MoreMetersTest.java, core/src/test/java/com/linecorp/armeria/common/metric/RollingHdrQuantilesTest.java, dependencies.yml, licenses/LICENSE.hdrhistogram.cc0.txt, licenses/LICENSE.rolling-metrics.al20.txt, thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
Motivation:
The Quantiles implementations provided by Micrometer are not
thread-safe, causing various races.
Modifications:
- Replace CKMSQuantiles with RollingHdrQuantiles, which is a forked
version of Rolling Metrics ResetByChunksAccumulator
- https://github.com/vladimir-bukhtoyarov/rolling-metrics/blob/2.0.3/src/main/java/com/github/rollingmetrics/histogram/accumulator/ResetByChunksAccumulator.java
- Rolling Metrics supports only long integer values so I had to fork
it to support double values.
- Add the metrics for HdrHistograms used by RollingHdrQuantiles
- Add MicrometerUtil.registerLater()
Result:
- Fixes #793
=> Use HdrHistogram as the default Quantiles implementation

dependencies.yml, zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java, zipkin/src/test/java/com/linecorp/armeria/common/tracing/SpanCollectingReporter.java, zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java, zipkin/src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceTest.java
Fixes #791
This is a breaking change, users of the old `Span` API will either have to
- Update the official zipkin collector to a version that supports v2 API
- https://github.com/openzipkin/brave/tree/master/brave#zipkin-v1-setup
- Reimplement the reporter if using some non-official API (like a custom Thrift API)
=> Migrate to Brave 4.9.0

build.gradle, core/build.gradle, dependencies.yml, grpc/build.gradle, thrift/build.gradle
- Apply JMH plugin for all Java projects
- Add JMH annotation processor to the dependencies so that a developer
can launch a benchmark from his or her IDE
- Add 'jmh.*' properties for tuning JMH plugin configuration
- Rename grpcJmh.upstream to jmh.grpcUpstream
=> Improve JMH integration

core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
Used to express a typed relationship with another resource, where the relation type is defined by RFC 5988
=> Add link header to HttpHeaderNames

zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanContextUtil.java, zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java, zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java
Apply this change will fix concurrent problem of SpanScope.
It's possible that RequestContext.push be called concurrently. So context's attr may be overwrite.
Change to use thread local to make scope bind on thread, then we can retrieve it back.
Fix issue https://github.com/line/armeria/issues/811
=> Fix zipkin span not correctly closed problem

core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java, core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java, core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
My service needs a special route rule which like user-id based sticky balancing, and it's finally possible thanks to https://github.com/line/armeria/pull/797 
@imasahiro and @anuraaga may interested in
=> Add StickyStrategy  endpoint selector

grpc/build.gradle, grpc/src/jmh/java/com/linecorp/armeria/grpc/downstream/DownstreamSimpleBenchmark.java, grpc/src/jmh/java/com/linecorp/armeria/grpc/shared/ClientType.java, grpc/src/jmh/java/com/linecorp/armeria/grpc/shared/SimpleBenchmarkBase.java, grpc/src/jmh/java/com/linecorp/armeria/grpc/upstream/UpstreamSimpleBenchmark.java, settings/checkstyle/checkstyle-suppressions.xml
Also refactors more common logic into a base class.
~~While the asynchronous version of the upstream benchmark seemed to be showing awesome performance (2-4x downstream), it doesn't complete since there seems to be a memory leak...~~
After modifying the benchmark to wait for pending requests before moving on, it works. Guess the QPS was high enough to overload the server through multiple iterations.
For #799
=> Add okhttp client and non-blocking gRPC benchmarks.

core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java, core/src/main/java/com/linecorp/armeria/server/annotation/Decorate.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceDecorationTest.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
Motivation:
Currently there is no way to decorate a single annotated service method when an annotated service object is added by ServerBuilder#annotatedService method.
Modifications:
- Add `@Decorate` annotation to specify decorators for an annotated service method
- Use DecoratingServiceFunction and FunctionalDecoratingService to decorate the method
Result:
A user can use a decorator easily by specifying annotations over annotated service method implementations.
=> Add a decorator for annotated service methods

core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/main/java/com/linecorp/armeria/server/annotation/Header.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
Motivation:
There's no way to get the value of the specific HTTP request header using annotated services.
Modifications:
- Add the `Header` annotation to represent a HTTP request header in annotated services.
Result:
- Can close #708
- Can implement the watcher in Central Dogma!!!
=> Provide a way to inject HTTP request headers to annotated services

zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java, zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java
User can decide to add custom service name or using RequestLog#host. Setting remote endpoint make ui looks better(It will show remote name rather than local service name if exists)
--
Should we just using Tracing.current rather than pass in Tracing? I think usually 1 vm should have only 1 Tracing. Because some library like brave.mysql using Tracing#current, so if we use multiple tracing, the service name will be weird.
=> Make tracing client has remote endpoint information.

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageVerification.java
I have split this off of #836 to focus on the re-entrancy problem. Even without trying to optimize event loop access of the stream message, we should be handling it correctly for the non-executor stream case.
https://github.com/reactive-streams/reactive-streams-jvm#2-subscriber-code - 2.7
The test fails without the logic change and passes after it. Unfortunately, I'm trying to wrap my head around failures with the `testNg`. Let me know if you have any ideas what could be up.
```
PublisherBasedStreamMessageVerification.required_spec317_mustNotSignalOnErrorWhenPendingAboveLongMaxValue: FAILURE
Gradle suite > Gradle test > com.linecorp.armeria.common.stream.PublisherBasedStreamMessageVerification.required_spec317_mustNotSignalOnErrorWhenPendingAboveLongMaxValue FAILED …
```
=> Prevent reentrant synchronous callback execution.

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
Motivation:
Currently, `isEmpty()` and `isOpen()` in the `streamMessge` from a `duplicator` using different layer to check their return value.
This is the problem because, for example, if the `streamMessage` has 3 signals and the streamMessage’s `close()` is called, it’s status will be closed and not empty.
However, a `ChildStreamMessage`’s status will be closed(upstream’s status) and empty(downstream’s status) because `subscription.request(long)` is not called.
There are two options to solve this problems. First one is using downstream’s(or processor in the `duplicator`) status.
If we using this, the child stream will be open until it receives `onComplete()` or `onError()` even thought the upstream is closed already.
Second one is using upstream’s status with dealing the situation when …
=> Change isEmpty() in ChildStreamMessage

core/src/main/java/com/linecorp/armeria/client/Endpoint.java, core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistry.java, core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointSelector.java, core/src/main/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategy.java, core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java, core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java, core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java, core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java, core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
This reverts commit 429b658cf057be454691b2489270cc4ca4f55fb6.
Because we realized that it does not provide any merits for now, make endpoint selection synchronous again.
=> Revert "Make endpoint selection asynchronous (#819)"

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java, core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java, core/src/main/java/com/linecorp/armeria/client/retry/HttpStatusBasedRetryStrategy.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java, core/src/main/java/com/linecorp/armeria/common/HttpRequest.java, core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/Response.java, core/src/main/java/com/linecorp/armeria/common/RpcResponse.java, core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java, core/src/main/java/com/linecorp/armeria/common/stream/CancelledSubscriptionException.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClientTest.java, core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
Motivation:
StreamMessage.closeFuture() has a confusing name because it conflicts
with the semantic of isOpen(). It is obviously possible that isOpen() is
false when closeFuture() is not complete.
Modifications:
- Add StreamMessage.completionFuture()
- Add StreamMessage.isComplete()
- Deprecate StreamMessage.closeFuture()
- Update the Javadoc of StreamMessage
Result:
- Less confusing API
/cc @anuraaga
=> Rename StreamMessage.closeFuture() to completionFuture() and revise Javadoc

benchmarks/src/jmh/java/com/linecorp/armeria/benchmarks/core/StreamMessageBenchmark.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
Motivation:
Commit 4f0cee147101db3911b36c6c1a8525be69199cfe introduced a regression
where Subscriber.onSubscribe() can be invoked after onComplete().
Modifications:
- Reschedule the notification when onSubscribe() is not invoked yet.
Result:
- Correct event order
=> Ensure Subscriber.onSubscribe() is invoked before other methods

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java, core/src/test/java/com/linecorp/armeria/server/TestConverters.java
Motivation:
When an annotated method wants to return null, now it should return an empty object instead because returning null would make NPE.
Modifications:
- Find a converter which handles Object.class for the return value of null.
- Avoid NPE.
=> Allow null value as a return value of annotated http service methods

NOTICE.txt, build.gradle, core/src/main/java/com/linecorp/armeria/client/DecodedHttpResponse.java, core/src/main/java/com/linecorp/armeria/common/HttpRequest.java, core/src/main/java/com/linecorp/armeria/common/HttpRequestDuplicator.java, core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/HttpResponseAggregator.java, core/src/main/java/com/linecorp/armeria/common/HttpResponseDuplicator.java, core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/EventLoopStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java, core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java, core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClientTest.java, core/src/test/java/com/linecorp/armeria/common/DefaultHttpRequestTest.java, core/src/test/java/com/linecorp/armeria/common/DefaultHttpResponseTest.java, core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java, dependencies.yml, licenses/LICENSE.jctools.al20.txt
Motivation:
In the current API, subscribing to a StreamMessage without specifying an
Executor will leave no guarantee on which thread will invoke Subscriber.
This introduces various complication such as thread-safety issues.
Modifications:
- Choose the EventLoop of the current RequestContext or one of
CommonPools.workerGroup() EventLoops when subscribing without
specifing an Executor.
- Use EventExecutor instead of Executor so that we have fair confidence
that the signals will be handled in a single thread.
- Fix a race condition in AbstrctStreamMessageDuplicator.requestDemand(),
which passes a non-positive demand to Subscription.request()
- Skip the multi-subscriber tests in Reactive Streams TCK
Result:
- Thread-safety
- Less error-prone
- Fixes #853
=> Enforce single-threaded Subscriber in StreamMessage

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/EventLoopStreamMessage.java
- Change the return type of SubscriptionImpl.executor() to EventExecutor
- Make DefaultStreamMessage.demand non-volatile
- Make sure 'inOnNext' is reset to false even if Subscriber.onNext()
raises an exception
- Simplify doRequest()
- No noticeable performance regression or improvement
=> Miscellaneous StreamMessage improvements

core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java, core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
In `GrpcService`, I call `responseContent` but not `endResponse`, and as a result `LoggingService` never sees any exception. While I could call `endResponse` as well, it was very unintuitive to me that setting a failure response wasn't enough to log the error, and feels repetitive to have to call twice with the same exception. WDYT?
=> Treat RpcResponse.cause as log's cause if not explicitly set.

core/src/main/java/com/linecorp/armeria/client/encoding/ZlibStreamDecoder.java, core/src/main/java/com/linecorp/armeria/common/FilteredHttpResponse.java, core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java, core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java, core/src/main/java/com/linecorp/armeria/internal/PooledObjects.java, core/src/test/java/com/linecorp/armeria/client/encoding/AbstractStreamDecoderTest.java, core/src/test/java/com/linecorp/armeria/client/encoding/ZlibStreamDecoderTest.java, core/src/test/java/com/linecorp/armeria/server/encoding/HttpEncodedResponseTest.java
Motivation:
FilteredStreamMessage currently passes pooled objects such as
ByteBufHttpData, ByteBufHolder and ByteBuf as they are, causing buffer
leaks when a user publishes them.
Modifications:
- Add a constructor parameter 'withPooledObjects' to
FilteredStreamMessage and FilteredHttpResponse
- Extract the common code that converts a pooled object into an unpooled
one into a new utility class 'PooledObjects'
- Add test cases for HttpEncodedResponse and ZlibStreamDecoder to verify
the change
Result:
- Less leaks
=> Make FilteredStreamMessage and FilteredHttpResponse understand buffer pooling

core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageTest.java
Since `isOpen` is usually updated immediately, it's not a sufficient guard for item processing, so add await to the refcnt assertions too.
=> Wait for refcnt assertions.

core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
Motivation:
When HttpResponseWrapper is closed, it also aborts the corresponding request and the response is finally closed with a cause by HttpRequestSubscriber#failAndRespond via HttpRequestSubscriber#onError.
However, we should normally close it without a cause if the response has been completed. So we should give a chance to the HttpResponseWrapper to close the response normally before aborting the request.
Modifications:
- Call `request.abort()` after `delegate.close()` in HttpResponseDecoder.
- Close a request instead of aborting if the request is only handled by HttpServerHandler.
Result:
Closes #630
=> Close completed response before trying to abort its corresponding request

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
It's a bit weird that reactive-streams 2.08 only mentions onNext, but I guess it applies equally to onComplete and onError.
Also makes sure response reader is always cancelled before aborting the request stream and share code with the unlikely `httpClient.execute` exception case for closing.
Not sure if it'll affect #822 but let's try.
=> Keep track of cancellation in stream reader because it is not guaranteed there will be no more notifications.

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframer.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
With the recent subscription changes, it's more important than ever to set the executor. And while our `*Decoder` don't currently write pooled objects, it will be nice to change them to do so and let the streams do the unpooling.
=> Set event loop when subscribing from gRPC and allow pooled objects.

core/src/main/java/com/linecorp/armeria/server/docs/DocService.java, core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpVfs.java, core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpVfs.java, core/src/main/java/com/linecorp/armeria/server/file/FileSystemHttpVfs.java, core/src/main/java/com/linecorp/armeria/server/file/HttpFileService.java, core/src/main/java/com/linecorp/armeria/server/file/HttpVfs.java
Motivation:
Using toString() as a way to get the specific information is not a good
idea in general since toString() always has the default implementation.
Modifications:
- Add HttpVfs.meterTag()
- HttpVfs is not a functional interface anymore.
- Add AbstractHttpVfs which overrides toString()
- Rename the 'rootDir' tag to 'vfs'
Result:
- Fixes #893
- HttpVfs is not a functional interface anymore due to the addition of
meterTag()
- Tag name has been changed from 'rootDir' to 'vfs'.
=> Replace HttpVfs.toString() with HttpVfs.meterTag()

core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java, core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java, core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java, core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContext.java, core/src/main/java/com/linecorp/armeria/internal/DefaultAttributeMap.java, core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java, core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java, core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java, core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
Motivation:
A user may want to create a new context whose properties and attribute map are derived from an existing context.
Modification:
- Add a `newDerivedContext()` to `RequestContext` and implement it in `DefaultClientRequestContext`, `DefaultServiceRequestContext` and `CompositeServiceRequestContext`
Result:
- Close #870
=> Provide a way to create a derived RequestContext

core/src/main/java/com/linecorp/armeria/common/Flags.java
Most http clients including modern http browser does not enable
http1 pipelining by default because many http servers are still
do not works well with it. For this reason, disabling http1 pipelining
by default.
Related to #897
=> Disables http1 pipelining by default

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java, core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/NoopRequestLogBuilder.java, core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithLoggingTest.java, core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
Motivation:
`RetryingClient` could not record the logs properly.
Modifications:
- Add `addChild` to `RequestLogBuilder` to propagate the logs from child
Result:
- Close #869
=> Add addChild method to RequestLogBuilder

core/src/main/java/com/linecorp/armeria/common/MediaType.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java, core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunction.java, core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java, core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverter.java, core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunction.java, core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverters.java, core/src/main/java/com/linecorp/armeria/server/annotation/RequestObject.java, core/src/main/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunction.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceRequestConverterTest.java, core/src/test/java/com/linecorp/armeria/server/TestConverters.java
Motivation:
When we are handling HTTP POST request, we usually convert its body to a Java object by some converting logic like JSON message converter. It is a general use-case for handling a request because a Java object is more convenient than a raw HTTP request itself. So it would be better if we have a request object mapping feature like Spring message converter.
Modifications:
- Add `@RequestConverter` annotation to specify a request converter of a method or a class. It is also repeatable.
- Add RequestConverterFunction interface to implement a request converter class.
- Add `@RequestObject` annotation to specify which parameter should be converted by a request converter.
=> Add request converter to annotated http service

core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java, core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageVerification.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
Currently request timeout doesn't work correctly with deferred responses - the timeout is set after `onSubscribe` is called, which only happens after `delegate` at some point possibly well in the future. And in general, stream lifecycle events should happen before `delegate` has been called. This means it's not enough for a `DefferedStreamMessage` to simply forward all stream events to the delegate - it needs to handle them and only start forwarding after `delegate` has been called.
This change adds keeping track of demand and cancellation to `DeferredStreamMessage` - even before `delegate` has been called, `onSubscribe` is called on the subscriber to make sure logic that should run as soon as subscription (e.g., setting a request timeout) can happen, and since this will immediately …
=> Have DeferredStreamMessage manage the stream instead of just forwarding.

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
Currently, the subscription is cancelled as soon as the response subscriber receives an end-of-stream object, before it is actually written. This makes sense from a reactive streams perspective, but we also have the concept of a completion future which is tied into the stream's lifecycle. When the subscription is canceled, the completion future is set to a cancelled state as well - depending on the stream's implementation, this could be synchronous, meaning the completion future is notified before the last write can even happen. If someone is listening for the completion future to do a cleanup type of thing, it might happen even though things were successful. This is the result of a slightly confusing correlation between the stream lifecycle and completion future.
This PR changes the …
=> Cancel subscription after writing the object is complete for better completion signaling

core/src/main/java/com/linecorp/armeria/internal/metric/CaffeineMetricSupport.java, core/src/test/java/com/linecorp/armeria/internal/metric/CaffeineMetricSupportTest.java
Motivation:
The offending test case keeps the MockLoadingCache in a WeakReference
from its beginning of life. As a result, CaffeineMetricSupport.setup()
sometimes throws a NullPointerException because `WeakReference<MockLoadingCache>.get()`
can return null even before our System.gc() call.
Modifications:
- Keep the strong reference until System.gc()
- More friendly NPE message
Result:
=> Fix flaky test: CaffeineMetricSupportTest.aggregationAfterGC()

core/src/main/java/com/linecorp/armeria/common/MediaType.java, core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceRequestConverterTest.java
Motivation:
Not only `application/json` has JSON content, but also many variants whose subtype
contains `+json` has JSON contents. It is reasonable that `JacksonRequestConveterFunction`
supports converting the requests who have those headers.
I found a similar issue: https://github.com/NativeScript/NativeScript/issues/2593
Modifications:
- make `JacksonRequestConverterFunction` convert requests who have `+json` header
- Add `json-patch+json` media type
Result:
- Robust `JacksonRequestConveterFunction`
=> Make JacksonRequestConverterFunction support +json media type as well

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/internal/TrafficLoggingHandler.java, core/src/main/java/com/linecorp/armeria/internal/logging/LoggingUtil.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java, core/src/main/java/com/linecorp/armeria/server/logging/AccessLogFormats.java, core/src/main/java/com/linecorp/armeria/server/logging/AccessLogType.java, core/src/main/java/com/linecorp/armeria/server/logging/AccessLogWriters.java, core/src/main/java/com/linecorp/armeria/server/logging/AccessLogger.java, core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java, core/src/test/java/com/linecorp/armeria/server/logging/AccessLoggerTest.java, site/src/sphinx/server-access-log.rst, site/src/sphinx/server.rst
Motivation:
Currently we cannot exactly write an access log for a server because our logging mechanism is based on a decorator and the decorator is only applied when a request is mapped to a service.
So it would be better to provide some access logging mechanism by a server itself, not a based on a decorator.
Modifications:
- Define log format types. Also provide a default log format such as NCSA common log format and NCSA combined log format.
- Add an interface to `ServerBuilder` to specify a log format and a log writer.
- Try to write an access log after a response has been sent.
- Add a site document.
Result:
Closes #817
=> Add access logging feature to Server

core/src/main/java/com/linecorp/armeria/common/DefaultHttpRequest.java, core/src/main/java/com/linecorp/armeria/common/FixedHttpRequest.java, core/src/main/java/com/linecorp/armeria/common/HttpRequest.java, core/src/main/java/com/linecorp/armeria/common/HttpRequestDuplicator.java, core/src/main/java/com/linecorp/armeria/common/HttpRequestWriter.java, core/src/main/java/com/linecorp/armeria/common/PublisherBasedHttpRequest.java, core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java, core/src/test/java/com/linecorp/armeria/internal/DefaultHttpRequestTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Motivation:
HttpRequest.isKeepAlive() was originally meant to be server-side only
transport-level detail, which means:
- It has no use on the client side. Creating a request with the false
keepAlive property has no effect at all.
- There's no notion of keep-alive in HTTP/2.
Modification:
- Move HttpRequest.keepAlive down to DecodedHttpRequest so that it's
kept only for the server-side decoder-level
- Remove HttpRequest.streaming() which creates an invalid request.
Result:
- Less noise in the public API
- A user does not have a way anymore to know if the current request will
keep the connection alive or not. It was transport-layer detail anyway.
=> Remove HttpRequest.isKeepAlive()

dependencies.yml, zipkin/build.gradle
Added an explicit dependency on zipkin-java as the transitive dependency seems to have been removed. 
=> Update to Brave 4.13.1

core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java, core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceRequestConverterTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java, thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java, thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientInvocationHandler.java, thrift/src/test/java/com/linecorp/armeria/client/thrift/THttpClientBadSeqIdTest.java
Motivation:
If the client request with invalid JSON, `JacksonRequestConvertFunction` currently, throw
a converting excpeiton and there's no place to catch the exception. Therefore, the client
get `500` error which is not right.
Modification:
- Catch the exception and throw new `IllegalArgumentException` so that `DefaultExceptinHandler` handles it
Result:
- Respond with proper status to clients
=> Catch the Exception while converting RequestObject using JacksonRequestConverterFunction

zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
Motivation:
ZooKeeperUpdatingListener attempts to access `Server.activePort()` in
`serverStarting()`. `Server.activePort()` is supposed to be available in
`serverStarted()`.
Modifications:
Use `serverStarted()` rather than `serverStarting()`.
Result:
- Fixes #933
=> Fix NoSuchElementException in ZooKeeperUpdatingListener

core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java, core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java, core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContext.java, core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java, core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java, core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java, core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java, core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java, core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
So, a user can derive a context with the specified `Request`.
Also, I changed to store the `request` field as `Request` instead of `Object`
inside `NonWrappingRequestContext`.
=> Add newDerivedContext(Request) to RequestContext

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceHandlersOrderTest.java
Motivation:
Currently, if there are method-level `RequestConverter`s, `ResponseConveter`s or
`ExceptionHandler`s in `AnnotatedHttpService`, the class-level `Annotation`s are not applied.
We want to make sure all of the `Annotation`s are applied, so that the order will be
parameter-level -> method-level -> class-level -> service-level.
Modification:
- Add class-level `Annotation`s no matter what, to the `annotationValues`
Result:
- A user does not surprise
=> Change to apply service-level annotation after method-level annotation

site/src/sphinx/client-grpc.rst
- Anonymous class requires an explicit type parameter.
=> Add missing type parameter in gRPC client example

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunction.java, core/src/main/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunction.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceHandlersOrderTest.java
Motivation:
We are using Class.isAssignableFrom() incorrectly in some places. For
example:
expectedReturnType.isAssignableFrom(SomeType.class)
will return true even if 'expectedReturnType' is Object.class. We
obviously do not want our RequestConverterFunction implementations to
inject an Object parameter, but only when the parameter type matches in
a more meaningful way.
Similarly, I find this code:
parameterInfo.type().isAssignableFrom(Optional.class)
which will match even when parameterInfo.type() is Object.class.
Modifictions:
- Use Class.isAssignableFrom() only when necessary
Result:
- More sensible type matching
=> Do not use Class.isAssignableFrom() if not applicable

dependencies.yml, grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
- Update Micrometer to 1.0.0-rc.7
- Increase metrics integration test timeout to 30 seconds so that the
build doesn't fail on slow CI machines
=> Micrometer 1.0.0-rc.7 / Increase metrics integration test timeout

grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageFramer.java
Long time no see. I found this when I was analyzing `UnframedGrpcService`. 😃
=> [Trivial] ArmeriaMessageFramer#writeUncompressed does not throw IOException anymore

core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
I think I had originally written it this way, but thought I could simplify the logic. I realized though, that the response cause pretty much always ends up being `AbortedStreamException` since we call `req.abort()` when finishing a request in `HttpServerHandler`. I guess if an RPC failure has been specified, it will always be more relevant than an `endResponse` exception, so it makes sense to prioritize it, but let me know what you think.
=> Prioritize rpc response error over end response error.

zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java, zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Found while I was working on `ZooKeeperUpdatingListener`.
=> [TRIVIAL] ZooKeeperRegistrationTest#{startServers, stopServers} does not throw Exception anymore

site/src/sphinx/advanced-structured-logging.rst, zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
1. Fix Typo: extenda -> extends.
2. Fix spacing: `ZooKeeperUpdatingListener`.
=> [TRIVIAL] Fix Typos

settings/checkstyle/checkstyle.xml
Motivation:
Many static initialization blocks are directly tied to a field. Removing
the empty line between the field declaration and its static
initialization block makes the association clearer:
private static final String X;
static {
X = ...;
}
Modifications:
- Remove STATIC_INIT token from the EmptyLineSeparator checkstyle rule
Result:
- Fixes #700
=> Remove STATIC_INIT token from EmptyLineSeparator checkstyle rule

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
Motivation:
Users may want to use enumeration type for requesting parameter
Modifications:
- Add converting logic from the enumeration type to string in ‘AnnotatedHttpServiceMethod'
- Add unit test for supporting enumeration type
Results:
- Users are now able to use requesting parameter
=> Support enum as a type of @Param annotated parameter(#935)

core/src/main/java/com/linecorp/armeria/server/RedirectService.java, core/src/test/java/com/linecorp/armeria/server/RedirectServiceTest.java
Motivation:
- Add a new `RedirectService` to forward/redirect requests to other services
Modification:
- Add new `server.RedirectService` class
- implement all pattern population and checking in `RedirectService` itself
- Implement new tests for RedirectService 
Result:
- New RedirectService
@trustin please have a look
- Design choices
- have moved the previous `PathMappingUtil` functions to `RedirectService` instead of adding an inner class
- Limitations
- the `VALID_DEFAULT_URI_PATTERN` is not completely robust, should we check for valid host names etc?
- I will continue with #914 changes in a separate PR
=> Implement RedirectService (#774)

core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java, core/src/main/java/com/linecorp/armeria/server/DecoratingService.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/Service.java, core/src/main/java/com/linecorp/armeria/server/file/HttpFileService.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java, core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Currently, prefix mappings used with an infinite number of URLs (common for a frontend proxy) will cause cache-thrashing. While it can be disabled for these situations, defaulting to exact paths + our common services should be good for most cases either way.
Fixes #967
=> Only cache non-exact path mappings when opted-in by the service.

gradle/scripts/lib/common-release.gradle
Motivation:
`release` task did not handle an SSH remote URL whose path starts with a
colon (:) correctly, e.g. github.com:line/armeria.git
Modifications:
- Match host and path correctly for both forms:
- `scheme://host/path`
- `user@host:path`
Result:
- We can release.
=> Fix the release task

gradle/scripts/.gitrepo
`git-subrepo` is an alternative of git submodules and git subtree. See:
- https://github.com/ingydotnet/git-subrepo 
- https://github.com/ingydotnet/git-subrepo/wiki/Basics
for more information.
=> Use git-subrepo for gradle/scripts

core/src/main/java/com/linecorp/armeria/client/Endpoint.java, core/src/main/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroup.java, core/src/test/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroupTest.java
Motivation:
A user does not always want to specify the default port number when
building a PropertiesEndpointGroup, especially for HTTP and HTTPS
endpoints that run on their default ports.
Modifications:
- Add two overloaded factory methods that do not require 'defaultPort'
- Fix off-by-one validation bug with 'defaultPort'
- Overall clean-up on Javadoc and exception messages
Result:
- A user can build PropertiesEndpointGroup without defaultPort
- Specifying 0 as defaultPort will trigger an exception at earlier point
=> Allow specifying no default port when building PropertiesEndpointGroup

thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftDocServicePlugin.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServiceTest.java
Motivation:
Although it's strongly recommended to use exact path mapping when a user
binds a THttpService, a user may want to or mistakenly bind his or her
service with a prefix path mapping.
When a THttpService is bound with a prefix path mapping, a user cannot
use a debug form because ThriftDocServicePlugin expects an exact path
mapping.
Modifications:
- Make ThriftDocServicePlugin also accept a prefix path mapping.
Result:
- Less surprising
=> Expose prefix-mapped THttpServices in DocService

core/src/main/java/com/linecorp/armeria/common/RequestContext.java
Not using kotlin, but IntelliJ still provides good warnings now that we have the package annotation :)
=> Add Nullable to RequestContext.mapCurrent

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
I had originally done this for responses, but not for requests, probably assuming that requests tend to be small compared to responses. Now I'm writing an object storage client where requests are orders of magnitude larger than responses...
=> Subscribe to pooled objects for client requests.

core/src/main/java/com/linecorp/armeria/client/ClientOptions.java, core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
Motivation:
Some L7 reverse proxies such as Linkerd requires a user to send a
different ':authority' header than the actual host name.
Modification:
- Do not blacklist ':authority' header from ClientOptions.HTTP_HEADERS.
Result:
- Partial fix for #1014
/cc @daveconde
=> Allow overriding ':authority' header

retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallSubscriber.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallSubscriberTest.java
Motivation:
Some HTTP/2 implementations can send additional headers after sending a
non-informational HEADERS frame.
ArmeriaCallSubscriber will fail with NPE because it assumes HttpHeaders
always have a `:status` header, but it's not the case of split headers.
Modifications:
- Append the HTTP headers received after the first non-informational
HTTP headers
- Defer the call to `Response.Builder.body()` so that we can handle
`content-type` or `content-length` header even if it is not in the
first HEADERS frame.
Result:
- Fixes #1014 
/cc @daveconde
=> Handle split headers in ArmeriaCallSubscriber

core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java, core/src/main/java/com/linecorp/armeria/common/HttpRequestAggregator.java, core/src/main/java/com/linecorp/armeria/common/HttpResponseAggregator.java, core/src/test/java/com/linecorp/armeria/internal/DefaultHttpRequestTest.java, core/src/test/java/com/linecorp/armeria/internal/DefaultHttpResponseTest.java
Motivation:
Some HTTP/2 implementations can send additional headers after sending a
non-informational HEADERS frame.
HttpRequest.aggregate() and HttpResponse.aggregate() will not merge the
split headers correctly, making AggregatedHttpMessage.informationals()
contain split headers and headers() and trailingHeaders() omit some
headers.
Modifications:
- Merge the split HTTP headers correctly.
Result:
- Fixes #1014 for HttpRequest.aggregate() and HttpResponse.aggregate()
=> Handle split headers in Http(Request|Response).aggregate()

zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java
I found these [while working on #1007](https://github.com/dongjinleekr/armeria/tree/feature/issue-1007).
=> [TRIVIAL] EndpointGroupTest#[disconnectZk, setNodeChild] does not throw Throwable anymore

core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
=> [TRIVIAL] Remove unused 'throws Exception's from DeferredStreamMessageTest

grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java, grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServicePluginTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java, grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
This seems a bit hacky, but couldn't think of a cleaner approach.
Fixes #1000
=> Make sure RPC information is set to metrics for unframed requests.

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
While the queue releases references fine, it doesn't retain the first one, so it will not be able to do signal the object a second time as it has likely already been released. The unit test forgot about the reference the test itself holds to the buffers.
=> Better document / test reference counting of stream duplication.

core/src/main/java/com/linecorp/armeria/client/DecodedHttpResponse.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriter.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java, core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java, core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriterTest.java, core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageVerification.java, core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/stream/EventLoopStreamMessageVerification.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java, core/src/test/java/com/linecorp/armeria/server/healthcheck/ManagedHttpHealthCheckServiceTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java, grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto, jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java, tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
This ended up being more complicated than I expected. Please check that my understanding makes sense :)
Currently, there is no notification to response streams if the client disconnects. If the client disconnects before finishing a request, server logic will be notified in the request stream, but if it disconnects after finshing a request but before finishing a response, the server logic has no way of knowing to abort processing.
- Now, any in-progress response streams are aborted when channel is closed
- Default behavior of `StreamMessage.write` changed to throw an exception when stream is closed, which is more natural. `tryWrite` can be used when this is not desired.
- Also fix that a client close on HTTP/1 request did not notify the request stream of closure
- Fixes a test which kept a …
=> Close in-progress responses when channel is closed.

grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java, grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto, testing/src/main/java/com/linecorp/armeria/testing/server/ServerRule.java
Currently, a server would know the client cancelled when they attempt to write to the closed stream. Now, they can listen for the cancellation itself.
=> Cancel gRPC stream when client cancels.

site/src/sphinx/server-access-log.rst
In the `logback.xml` example, `SizeAndTimeBasedRollingPolicy` must be used because:
- `maxFileSize` element is specified.
- `%i` is used in the `fileNamePattern`.
=> Fix typo in `logback.xml` example

site/src/sphinx/client-thrift.rst
.. because otherwise the callback might not be executed at all due to
JVM termination.
=> Client Thrift example should wait until a call is finished

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcTestUtil.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java, grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
Currently, methods called from gRPC stub code do not enforce event loop safety as they should. This has a reasonable chance of causing issues for the client in particular since it's common for stubs to be called from a server event loop, and especially true for unit tests.
Now, business logic is always run on the event loop. The few methods that are only for setting up state via experimental APIs before issuing any calls use synchronized instead to force a memory fence.
A test was removed which relied on the previous broken behavior of a write error being synchronously reported to the caller even when on a different thread.
=> Make sure stub code handlers run on the event loop.

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcFlowControlTest.java, grpc/src/test/proto/com/linecorp/armeria/grpc/testing/flow.proto
Currently, reads from the stream are correctly handled by propagating `request` through the stub, but writes are not since `isReady` is not properly implemented. When I first implemented the streams, I didn't understand `StreamWriter` properly, but now I do and realize we can use `onDemand` for this :)
With the change, the stream is only considered ready for writes when there is a request for them. I sort of want to optimize the non-backpressure case by only doing this if `isReady` is called, as that's a heuristic that should generally show the caller is implementing backpressure, but it's a bit weird and for unary calls the one call to `onDemand` doesn't seem like a big deal.
Fixes #1037
=> Implement flow control of gRPC stream writes.

site/src/sphinx/server-basics.rst
Related: #1042
Motivation:
A user who is not used to asynchronous nature of our API may be confused
when a server fails to start up, because the failure is only notified
via the returned CompletableFuture.
Modifications:
Update all examples that calls Server.start() also call join() against
the returned future.
Result:
- Hopefully less confusing
/cc @kishida
=> Always call .join() on Server start futures in examples

core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java, jetty/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java, jetty/src/test/java/com/linecorp/armeria/server/jetty/UnmanagedJettyServiceTest.java, testing-internal/src/main/java/com/linecorp/armeria/testing/internal/webapp/WebAppContainerTest.java, thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp1Test.java, tomcat/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceTest.java
Motivation:
It is a common pattern to create a self-signed certificate to test a
server and we could simplify that.
Modifications:
- Add ServerBuilder.tlsSelfSigned() which generates a self-signed
certificate automatically.
- Remove some code that uses `SelfSignedCertificateGenerator` directly.
Result:
- Brevity
=> Add ServerBuilder.tlsSelfSigned()

core/src/main/java/com/linecorp/armeria/client/Endpoint.java, core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java, core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java, core/src/main/java/com/linecorp/armeria/client/pool/PoolKey.java, core/src/test/java/com/linecorp/armeria/client/EndpointTest.java, core/src/test/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroupTest.java, core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java, core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java, core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java, core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroupTest.java, thrift/src/test/java/com/linecorp/armeria/it/client/endpoint/StaticEndpointGroupIntegrationTest.java, zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/DefaultNodeValueCodec.java, zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java, zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/TestBase.java, zookeeper/src/test/java/com/linecorp/armeria/common/zookeeper/NodeValueCodecTest.java
Motivation:
Currently, `Endpoint.host()` is used as a hostname or an IP address of
an endpoint. This does not work well for the `Endpoint`s whose IP
addresses are known already. For example, let's say we want to use
`DnsServiceEndpointGroup` with the following SRV records:
_https._tcp.foo.com. 3600 IN SRV 10 100 443 one.foo.com.
_https._tcp.foo.com. 3600 IN SRV 10 100 443 two.foo.com.
_https._tcp.foo.com. 3600 IN SRV 10 100 443 three.foo.com.
Because the client will have to create a TLS connection with proper SNI
settings, the `Endpoint` should provide `foo.com` as the host name and
provide `<the IP address of {one,two,three}.foo.com>` as the IP address
of `foo.com`, which is not possible with our current API.
Modifications:
- Add a new property `ipAddr` to `Endpoint`
- Add …
=> Add Endpoint.ipAddr

core/src/main/java/com/linecorp/armeria/common/metric/MoreNamingConventions.java, core/src/test/java/com/linecorp/armeria/common/metric/MoreNamingConventionsTest.java
Motivation:
It would be useful to provide a utility method that configure an
existing MeterRegistry with our NamingConvention implementations in
MoreNamingConventions.
Modifications:
- Add MoreNamingConventions.configure() and its tests.
Result:
- Less boilerplates in a user application
=> Add MoreNamingConventions.configure()

core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/HttpResponseWriter.java, core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java, core/src/main/java/com/linecorp/armeria/unsafe/ByteBufHttpData.java, core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriterTest.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshallerTest.java
Motivation:
We have many places where drops an empty HttpData silently. This can
lead to the leak of empty ByteBufHttpData.
Modifications:
- Use Unpooled.EMPTY_BUFFER for an empty buffer when creating a new
ByteBufHttpData
- Release ByteBufHttpData explicitly when we drop it even if it's not
empty
- Fix the incorrect reference count tests in AbstractStreamMessageAndWriterTest
- Update the Javadoc of StreamWriter about the life cycle of
reference-counted objects
Result:
- Less buffer leak
=> Fix potential buffer leaks due to empty ByteBufHttpData

grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcFlowControlTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Motivation:
:grpc:test sometimes fails due to OutOfMemoryError.
Modifications:
- Dereference multi-megabyte strings when the relevant tests are
finished
Result:
- Less chance of OOME in an environment with memory constraint
=> Reduce the amount of static memory required for testing :grpc

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java, core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
=> Fix a bug where resources are not cleaned up after calling duplicator.close()

core/src/main/java/com/linecorp/armeria/common/Flags.java
Motivation:
Now that HTTP/2 is fairly well-adopted, all sane HTTP/1 and 2
implementations should now handle the HTTP/2 preface string correctly.
Modification:
- Use HTTP/2 preface upgrade by default, in lieu of HTTP/2 upgrade
request, which is inferior in terms of efficiency.
Result:
- Efficiency
- Better compatibility with HTTP/2-first implementations that do not
support upgrade requests.
=> Use HTTP/2 preface upgrade by default

core/src/main/java/com/linecorp/armeria/server/Server.java
Motivation:
`numConnections` violates the Prometheus naming convention
Modifications:
- Rename 'armeria.server.numConnections` to `armeria.server.connections`
Result:
Consistency
=> Rename 'armeria.server.numConnections` to `armeria.server.connections`

core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java, core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriterTest.java
Motivation:
StreamWriter.write() throws IllegalStateException. However, we have a
dedicated exception for that - ClosedPublisherException.
Modifications:
- Throw ClosedPublisherException instead of IllegalStateException
Result:
- Easier to catch
=> Throw ClosedPublisherException when StreamWriter.write() fails

core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java, tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java, tomcat/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceTest.java
Motivation:
A successfully sent response can be logged with AbortedStreamException
or ClosedChannelException due to race conditions.
Modifications:
- Make HttpResponseSubscriber handle AbortedStreamException and
ClosedChannelException better so that they are not logged
unnecessarily
- Make HttpServerHandler clean up unfinished HTTP/1 responses a little
bit later so that they are not aborted too early.
- Fix a bug in DeferredStreamMessage where NeverInvokedSubscriber is
invoked, which happens when a DeferredStreamMessage is delegated to
another DeferredStreamMessage.
Result:
- Much less chance of redundant AbortedStreamException or
ClosedChannelException
=> Improve the cleanup of streaming responses

core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java, core/src/main/java/com/linecorp/armeria/common/HttpRequest.java, core/src/main/java/com/linecorp/armeria/common/HttpRequestAggregator.java, core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/HttpResponseAggregator.java, core/src/test/java/com/linecorp/armeria/internal/DefaultHttpRequestTest.java, core/src/test/java/com/linecorp/armeria/internal/DefaultHttpResponseTest.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
For advanced use cases, including inside armeria itself, it is nice to have the option to aggregate without copying into heap buffers. 
Also removed the thread-local thrift protocol factories since it seemed like saving a couple of objects isn't worth the thread-local overhead of the read and very complex code - let me know if you'd like me to restore it though.
=> Allow aggregating pooled objects.

core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeaders.java, core/src/test/java/com/linecorp/armeria/common/HttpHeadersTest.java
Motivation:
If a user set a `contentType` once, and then set it again using `setObject(...)`,
the `contentType()` returns the previous one.
Modification:
- Check the contentType again when `contentType()` is called`
Result:
- No surprise
=> Fix a bug where contentType is not reset

core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/test/java/com/linecorp/armeria/common/HttpResponseTest.java, site/src/sphinx/server-basics.rst
Motivations
- There are many boiler plate code in the document.
- Make it more simple and friendly.
- Light code will be more light.
- It will make more user. I hope.
Changes
- Introduce `of(String)` and `of(String, Object...)` for `HttpResponse` with `HttpStatus.OK` and `MediaType.PLAIN_TEXT_UTF_8` as a default.
=> Add more concise variants of HttpResponse.of()

core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
Motivation:
Currently, the access log writer gets components of `RequestLog` regardless of `RequestLogAvailability`.
So it sometimes might raise `RequestLogAvailabilityException` when the component is not ready.
Modifications:
- Add access log writer as a listener of `RequestLog`
=> Add access log writer as a listener of RequestLog

site/src/sphinx/advanced.rst, site/src/sphinx/client-circuit-breaker.rst, site/src/sphinx/client-retry.rst, site/src/sphinx/client.rst, site/src/sphinx/setup-common.rst
.. because it gives more visibility to the features. A user will see all
client-side features just by clicking 'Writing a client.'
Also:
- Updated setup-common.rst to add Bouncy Castle to the list
=> Move 'automatic retry' and 'circuit breaker' to 'client' section

site/build.gradle, site/src/sphinx/_extensions/api.py, site/src/sphinx/_static/overrides.css, site/src/sphinx/advanced-logging.rst, site/src/sphinx/advanced-structured-logging-kafka.rst, site/src/sphinx/advanced-structured-logging.rst, site/src/sphinx/advanced-zipkin.rst, site/src/sphinx/advanced-zookeeper.rst, site/src/sphinx/client-circuit-breaker.rst, site/src/sphinx/client-decorator.rst, site/src/sphinx/client-grpc.rst, site/src/sphinx/client-retrofit.rst, site/src/sphinx/client-retry.rst, site/src/sphinx/client-thrift.rst, site/src/sphinx/conf.py, site/src/sphinx/index.rst, site/src/sphinx/server-access-log.rst, site/src/sphinx/server-annotated-service.rst, site/src/sphinx/server-basics.rst, site/src/sphinx/server-decorator.rst, site/src/sphinx/server-docservice.rst, site/src/sphinx/server-grpc.rst, site/src/sphinx/server-http-file.rst, site/src/sphinx/server-servlet.rst, site/src/sphinx/server-thrift.rst
Motivation:
A documentation writer has to use a very long URI to a Javadoc entry
whenever he or she refers to a class or a package.
Modifications:
- Add a Sphinx extension that provides a role called `api` which greatly
simplifies adding an Armeria Javadoc link
- Replace all hard-coded Armeria Javadoc links with the `api` role
Result:
- Simplicity
=> Add a Sphinx extension that simplifies Javadoc linking

grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframer.java
Currently, we use a `CompositeByteBuf` to collect incoming frames, and we read required bytes into another `CompositeByteBuf` as data is available. This causes a lot of overhead for the common case where the message fits in one frame. There also doesn't seem to be a good reason to read into a `nextFrame` as we get bytes, instead of when we have enough bytes (I had copied the pattern in this code pretty much verbatim from upstream without thinking too much about it).
Now, a `CompositeByteBuf` for incoming frames is only created on the second one. If the stream is finished with a single frame, no composites will ever be allocated. Also, incoming bytes are only read when we have enough bytes to deliver a message - this means we don't need to allocate a composite to keep track of read bytes …
=> Only create composite bytebufs if there is more than one incoming gRPC frame.

core/src/main/java/com/linecorp/armeria/internal/AnnotatedHttpServiceParamUtil.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java, core/src/main/java/com/linecorp/armeria/server/annotation/BeanRequestConverterFunction.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceBuilderTest.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
Motivation:
Several HTTP headers can be sent with the same name. We missed that kind of situation before. Need to enhance annotated HTTP service to support it.
Modifications:
- Support `List<String>` type for `@Header` annotation.
=> Support `List<String>` type for `@Header` annotation

site/src/sphinx/_extensions/api.py, site/src/sphinx/_static/overrides.css, site/src/sphinx/advanced-zookeeper.rst
Motivation:
While documenting, it is often necessary to refer to a type in plural
form:
This class retrieves the list of :api:`Endpoint`\s from ZooKeeper.
Although `\` does its job here, the rendered output isn't very pretty,
mainly because:
- There's spacing between `Endpoint` and `s`. The spacing between them
should be moved after the plural suffix `s`.
- There's gray background at `Endpoint` but not at `s`. Both `Endpoint`
and `s` should have the same background color.
Modifications:
- Introduce a new directive `apiplural` which pluralizes a type
reference automatically
Result:
- Aesthetics and convenience
Before:
After:
=> Add 'apiplural' directive for referring to a type in plural form

core/src/main/java/com/linecorp/armeria/common/metric/PrometheusMeterRegistries.java
Motivation:
Like most Micrometer users use Metrics.globalRegistry, most Prometheus
users use CollectorRegistry.defaultRegistry. To create a
PrometheusMeterRegistry with CollectorRegistry.defaultRegistry, a user
has to do the following:
PrometheusMeterRegistries.newRegistry(CollectorRegistry.defaultRegistry)
.. which is too verbose.
Modifications:
- Add PrometheusMeterRegistries.defaultRegistry
Result:
- Fixes #1171
=> Add PrometheusMeterRegistries.defaultRegistry

spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java, spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceUtils.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ThriftServiceUtilsTest.java
Motivations:
- armeria-thrift-* dependencies are removed from armeria-spring-boot*-autoconfigure to choose thrift
implementations by a user but it causes NoClassDefFoundError if armeria-thrift-* dependency is not
populated in dependency list.
Changes:
- Add a reflection based implementation to retrieve names of thrift service
- Fixes https://github.com/line/armeria/issues/650
=> Fetches thrift service names using reflection not to access armeria-thrift package

core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java, core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
> Despite the RFC permitting multi-value response headers
to appear as individual header fields instead of a
single header field with a comma delimitted value,
Internet Explorer does not deal well with this and hence,
this commit ensures that multi-value CORS response
headers are serialized as a single header field with
a comma delimitted value.
https://github.com/elastic/elasticsearch/commit/4566378cd58415f84bde2252b6b95f6b24e96dff
Got compatible issues when using CorsService, IE don't handle multi-value response headers for CORS OPTIONS response, so try to combine multi-value to a comma delimited value.
=> Make CorsService response headers compatible with IE

core/src/main/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistries.java, core/src/test/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistriesTest.java
Related: https://github.com/micrometer-metrics/micrometer/blob/v1.0.0/micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardMeterRegistry.java#L77
Motivation:
Since 1.0.0, Micrometer registers additional gauges for percentile and
histogram values of Timers and DistributionSummarys for some monitoring
systems such as Dropwizard and Statsd.
I think it's not a sensible default to export additional gauges to
Dropwizard Timers and DistributionSummarys because Dropwizard already
provides its own percentile values via Timers and Histograms. Also,
because Dropwizard does not provide any aggregatation, such additional
gauges with tags will make things worse.
Modifications:
- Make the DropwizardMeterRegistry created by DropwizardMeterRegistries
filter out the extra gauges …
=> Do not export '*.percentile' and '*.histogram' gauges to Dropwizard MetricRegistry

core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/Service.java, core/src/main/java/com/linecorp/armeria/server/TransientService.java, core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
Motivations:
- Armeria server counts the number of pending requests including healthcheck requests.
- If a server has many healthcheck clients and these healthcheck clients send a request
frequently, it makes difficult for a server to shutdown on time because graceful
shutdown depends on the number of pending requests.
Modifications:
- Adds methods to track start/finish of processing requests to Server
- Stop to count a pending healthcheck request
=> Skip pending request counting at health check service

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java, grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Going to be writing a Pub/Sub *client* that deals with large payloads :) This PR allows streaming clients to handle large payloads more efficiently at the expensive of unsafe, manual memory management.
Also fixed a typo on the server side.
=> Add unsafe gRPC buffer wrap option to client.

settings.gradle
Motivations:
- Because some Tomcat API were removed from Tomcat 9, ABI compatibility is broken up (for example, [`Context#addServletMapping(String pattern, String name)`](https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/Context.html#addServletMapping(java.lang.String,%20java.lang.String)) is used in TomcatEmbeddedServletContainerFactory(spring-boot-1.5.x) was removed from Tomcat 9). For this, if Tomcat 9 dependency comes first, fails to startup spring-boot application with NoSuchMethodException.
Modifications:
- Publish armeria-tomcat8.5
=> Publish Tomcat8.5 project

core/src/main/java/com/linecorp/armeria/common/HttpData.java, core/src/test/java/com/linecorp/armeria/common/HttpDataTest.java
Motivation:
It would be useful to have stream-related methods in `HttpData`.
Modifications:
- Add `HttpData.toInputStream()`
- Add `HttpData.toReader()`
- Add `HttpData.toReaderUtf8()`
- Add `HttpData.toReaderAscii()`
Result:
- Fixes #1188
=> Add more convenience methods to HttpData

dependencies.yml, zipkin/build.gradle, zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java, zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java
Brave v5 is the same as v4 except no old deps. Notably, there is no
current constant file, so that's why literals are used in this change.
See https://github.com/openzipkin/brave/issues/699
=> Removes old dependencies via Brave 5

core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java, core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java, grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
=> Rename the `status` tag to `httpStatus` in `MeterIdPrefixFunction.ofDefault()`

core/src/main/java/com/linecorp/armeria/server/AnnotatedValueResolver.java, core/src/main/java/com/linecorp/armeria/server/annotation/Cookies.java, core/src/main/java/com/linecorp/armeria/server/annotation/DefaultCookies.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedValueResolverTest.java, site/src/sphinx/server-annotated-service.rst
Motivation:
It would be better to inject `Cookie` header value into a parameter automatically when a user uses an annotated HTTP service.
Modifications:
- Add `Cookies` class to let Armeria know where `Cookie` header is injected into.
Result:
- Closes #1026
=> Inject `Cookie` header automatically

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java, core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, site/src/sphinx/advanced-production-checklist.rst, site/src/sphinx/advanced.rst, site/src/sphinx/client-circuit-breaker.rst
Motivation:
A simple checklist before putting an Armeria application into production
would be very useful for our users.
Modifications:
- Added `advanced-production-checklist.rst` which is based on the recent
Slack thread with @jwills, @anuraaga and @huydx
- Added how to use the `CircuitBreaker` API with non-Armeria clients
- Deprecate ClientFactoryBuilder.socketOption() with channelOption() for
consistency
- Use Object2ObjectArrayMap for storing channel options
Result:
- Better UX
- A little bit of efficiency
/cc @jwills
=> Add documentation - production checklist / Deprecate ClientFactoryBuilder.socketOption() over channelOption()

core/src/main/java/com/linecorp/armeria/client/Endpoint.java, core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMapping.java, core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java, core/src/test/java/com/linecorp/armeria/client/HttpClientDelegateTest.java, core/src/test/java/com/linecorp/armeria/client/HttpClientSniTest.java, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMappingTest.java, core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Motivation:
Endpoint can have an IP address with its host name, which is called
'resolved Endpoint'. This is useful when you signify a specific host out
of many that have the same host name but different IP addresses, which
is often found when using a DnsEndpointGroup.
However, there are a few places in Armeria that the resolved Endpoints
with the same host name and different IP addresses are not handled
properly:
- KeyedCircuitBreakerMapping.KeySelector.HOST does not include an IP
address in the return value. This can make a CircuitBreaker enter the
OPEN state for all endpoints in a DnsEndpointGroup even if only one of
them is faulty.
- HttpHealthCheckedEndpointGroup does not use an IP address when sending
a health check request. This can make the health checker send a health
check …
=> Fix bugs where a resolved Endpoint is not handled correctly

core/src/main/java/com/linecorp/armeria/client/Endpoint.java, core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMapping.java, core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java, core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
Motivation:
Endpoint internally knows:
- whether it is hostname-only endpoint or IP-address-only endpoint
- whether its IP address is IPv4 or IPv6
However, we do not provide any getters for such information.
Modifications:
- Add Endpoint.hasIpAddr()
- Add Endpoint.isIpAddrOnly()
- Add Endpoint.ipFamily()
- .. and use the new methods where applicable
Result:
- Efficiency
=> Add more methods related with accessing IP addresses to Endpoint

core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/test/java/com/linecorp/armeria/client/HttpClientDelegateTest.java
Motivation:
HttpClientDelegate.extractHost() currently always falls back to
`Endpoint.host()` when `ctx.additionalRequestHeaders().authority()` is
not valid. Instead, we could try to extract a host name from
`req.authority()` before falling back to `Endpoint.host()`.
Modifications:
- Try to extract a host name from `req.authority()` rather than falling
back immediately to `Endpoint.host()` when `ctx.additionalRequestHeaders()`
contains an invalid authority.
Result:
- Robustness
=> More robust host name extraction in HttpClientDelegate

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeaders.java, core/src/main/java/com/linecorp/armeria/common/HttpHeaders.java, core/src/main/java/com/linecorp/armeria/common/HttpMethod.java, core/src/main/java/com/linecorp/armeria/common/HttpStatus.java, core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/NoopRequestLogBuilder.java, core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java, core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java, core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java, core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java, core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java, core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java, logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporter.java, logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java, zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java, zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java, zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java, zipkin/src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceTest.java
Motivation:
It is currently possible that `RequestLog.requestHeaders()` and
`responseHeaders()` return an empty `HttpHeaders`, which can trigger
various issues because we often assume they have at least essential
HTTP headers such as `:scheme`, `:authority`, `:method`, `:path` and
`:status`.
Modifications:
- Send a `400 Bad Request` response if a request does not have the
`:method` header.
- Do not fail with an exception if a client sent a weird method name
which is not recognized by `HttpMethod.valueOf()`.
- Add `HttpMethod.UNKNOWN` to represent an 'unknown' method
- Add `HttpStatus.UNKNOWN` to represent an 'unknown' status
- Auto-fill `:scheme` header if missing.
- Return a dummy `HttpHeaders` with the essential headers are filled
instead of returning an empty `HttpHeaders`.
- Deprecate …
=> Fill all necessary pseudo headers in RequestLog headers / Deprecate RequestLog.host() in favor of authority()

core/src/main/java/com/linecorp/armeria/client/ClosedClientFactoryException.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java, thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Motivation:
`Client` has to stop when the `ClientFacotry` is closed.
Modifications:
- Store the `ScheduledFuture` and add a lister which stops retrying
Result:
- Fixed another bug
=> Fix a bug where RetryingClient does not stop when ClientFactory is closed

build.gradle
Currently, verbose exceptions are enabled for all Java executions. This even applies to manual execution with the Gradle runner in IntelliJ, and when doing profiling, it causes the profiles to have extra noise. Now only test have verbose exceptions enabled, which is probably where they are useful.
Also fix `leak` property should be read from `rootProject` as with all gradle properties AFAIU. I recall us not getting leak traces at some point maybe related to this.
=> Only enable verbose exceptions for tests.

benchmarks/build.gradle, benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/downstream/DownstreamSimpleBenchmark.java, benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkBase.java, benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkClient.java, benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/upstream/UpstreamSimpleBenchmark.java
For #1185 - it's good to have some benchmarks to establish a baseline. This first one doesn't intend to be representative of all use cases, but has minimal business logic to try to stress the integration itself as much as possible. Indeed seeing about a 10% improvement in performance using upstream okhttp, similar to the report.
Edit: Was stupidly creating new client every benchmark iteration, ignore emails.
```
Benchmark                                            Mode  Cnt     Score     Error  Units
c.l.a.r.downstream.DownstreamSimpleBenchmark.empty  thrpt   20  3406.076 ▒ 105.094  ops/s
c.l.a.r.upstream.UpstreamSimpleBenchmark.empty      thrpt   20  3785.867 ▒ 130.965  ops/s
```
By the way, to not feel too down, here are the results with 20 JMH threads - as expected our throughput is …
=> Add a simple benchmark to check retrofit performance.

core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java, core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java, core/src/main/java/com/linecorp/armeria/internal/logging/LoggingDecorators.java, core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java, core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Currently, we allow setting different log levels for successful and failed responses. This is to allow the common case where successful requests / responses don't need to be logged (would be noise) but unsuccessful ones should for debugging. Unfortunately, the request is not logged for the latter right now, making it quite hard to debug. I think the default behavior should be to log the request in addition to the response when the response failed.
This change checks if request logging is enabled, and if not, logs request anyways if the response was unsuccessful. It admittedly feels a little weird, but I think it's less surprising for users. Open to any suggestions though.
=> Log request when response is failed and request wasn't logged.

grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormatProvider.java
I have found in the wild (Stackdriver Trace API) that some gRPC servers will not accept `application/grpc+proto` content type. Of course, this isn't compliant with the spec, but I guess reproducing the default behavior of upstream gRPC clients is better than not, so now gRPC client will send `application/grpc` as the proto content-type, matching the behavior of upstream grpc-java.
=> Use non-suffixed content-type for default gRPC proto encoding.

grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java, grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
The advertised encodings of a server or client are constant throughout multiple calls, so we don't need to do slightly expensive computation of the header string every time.
Just a micro-optimization
After (only 1 fork isn't enough for a reliable measurement)
```
Benchmark                                           (clientType)   Mode  Cnt      Score     Error  Units
c.l.a.g.downstream.DownstreamSimpleBenchmark.empty        OKHTTP  thrpt   20  17927.598 ± 670.447  ops/s
c.l.a.g.upstream.UpstreamSimpleBenchmark.empty            OKHTTP  thrpt   20  22614.173 ± 705.504  ops/s
```
Before
```
Benchmark                                           (clientType)   Mode  Cnt      Score      Error  Units
c.l.a.g.downstream.DownstreamSimpleBenchmark.empty        OKHTTP  thrpt   20  17344.866 ±  568.339 …
```
=> Only compute advertised encodings header once since it doesn't change.

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactory.java, core/src/main/java/com/linecorp/armeria/server/CatchAllPathMapping.java, core/src/main/java/com/linecorp/armeria/server/Routers.java, core/src/test/java/com/linecorp/armeria/server/RouterTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
Motivation:
When a user binds more than one service at the same path mapping,
`ServerBuilder` should reject such a configuration.
Modifications:
- Add duplicate mapping detection to `Routers.routers()`
- Weaken `PathMapping` types in `AnnotatedHttpServiceFactory`
Result:
- Almost fixes #529
- Note that this changeset does not detect all possible cases. For
example, it does not consider the relationship between media types.
It will detect most silly mistakes though, which should be enough.
=> Reject most duplicate path mappings

core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java, core/src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java, core/src/main/java/com/linecorp/armeria/client/pool/PoolKey.java, core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
Motivation:
When a user specifies both:
- an Endpoint without an IP address and
- a custom authority
the expected behavior is to use the custom authority as a host name (so
that it sends the correct server name on a TLS connection) and to
connect to the IP address of the host specified by the Endpoint.
However, currently, HttpClientDelegate always uses the IP address of the
host name in the custom authority. As a result, HttpClient ends up with
connecting to a wrong host.
Modifications:
- Made sure that HttpClientDelegate resolves the IP address of the
Endpoint.
- PoolKey.ipAddr is now non-null.
- HttpSessionChannelFactory now assumes PoolKey always has an IP address.
- Added test cases
- Removed small code duplication in HttpClientDelegate
Result:
- HttpClient does not …
=> Fix a bug where HttpClient connects to a wrong host when custom authority is used

benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java, core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java, core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java, thrift/src/test/java/com/linecorp/armeria/it/client/endpoint/StaticEndpointGroupIntegrationTest.java
Motivation:
Client using EndpointGroup with current WeightedRoundRobinStrategy is slow. 
* Current algorithm complexity for selectEndpoint operation is O(N * MaxWeight) where N is number of endpoints. Arbitrary weight value (>1000 for example) cause it slow. 
Modifications:
- Sort endpoints by weight, then by host and port.
- Find the correct endpoint faster by binary search on accumulated sum of weight.
- The complexity is O(log(N)) and not depend on weight value.
Algorithm details:
- In comment code block
Result:
* Faster selectEndpoint operation.
Benchmarks:
Before
```
Result "com.linecorp.armeria.core.client.endpoint.WeightedRoundRobinStrategyBenchmark.randomMainly1Max30":
392327.218 ±(99.9%) 9226.013 ops/s [Average]
Result "com.linecorp.armeria.core.client.endpoint.WeightedRoundRobinS …
```
=> Optimize complexity of client endpoint WeightedRoundRobinStrategy

.appveyor.yml, .travis.yml, build.gradle, core/build.gradle, core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java, it/spring/boot-tomcat/src/test/java/com/linecorp/armeria/spring/tomcat/demo/SpringTomcatApplicationItTest.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaMeterBindersConfigurationTest.java
Motivation:
We currently allow only 128 MiB of heap for tests, which is because we
do not want the streaming tests in `HttpServerTest` take too long
streaming `2 * maxMemory` bytes.
We don't really need to restrict the heap size for other tests. Small
heap size increases the test time for some complex tests that demands
more memory.
Modifications:
- Extract the streaming tests in `HttpServerTest` into
`HttpServerStreamingTest`
- Exclude `HttpServerStreamingTest` from the `test` task
- Add `testStreaming` task which runs `HttpServerStreamingTest` only
- Allow only 64 MiB to `testStreaming` while allowing 512 MiB to other
tests
Result:
- Streaming tests end sooner.
- Reduced memory pressure while running non-streaming tests
=> Allow more memory to tests, except streaming tests

core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java, core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java, core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java
Motivation:
`MeterIdFunction.apply()` is currently used for generating both 1)
active request gauges and 2) other meters. This can make the active
request gauges have unexpected tags such as `httpStatus`, which does not
make sense for 'active' requests.
Modifications:
- Add `MeterIdFunction.activeRequestsPrefix()`
- Modify `MeterIdFunction.andThen()` so that the given `BiFunction` is
applied to both `apply()` and `activeRequestsPrefix()`
- Modify `RequestMetricSupport` to use `activeRequestsPrefix()` for
active request gauges
Result:
- Active request gauges does not happen to have a weird `httpStatus` tag.
- Fixes #1258
=> Add a dedicated factory method for active request gauges to MeterIdPrefixFunction

it/spring/boot-tomcat/src/main/resources/config/application.yml, it/spring/boot-tomcat/src/test/java/com/linecorp/armeria/spring/tomcat/demo/SpringTomcatApplicationItTest.java
* application.yml armeria.ports.port=0.
* SpringTomcatApplication cleanup to use @Autowired, for consistency.
* SpringTomcatApplicationItTest added test that validated that only one connector is present.
Tomcat starts on random port.
=> Reproduce Tomcat 9.0 Issue w/o predefined ports.

it/spring/boot-tomcat/build.gradle, it/spring/boot-tomcat8.5/build.gradle, spring/boot1-autoconfigure/build.gradle, thrift0.9/build.gradle, tomcat8.0/build.gradle, tomcat8.5/build.gradle
Motivation:
IntelliJ IDEA generates an error event like the following when a source
directory has more than one output directory:
java.lang.Throwable: Module 'boot-tomcat_main' and module 'boot-tomcat8.5_main' have the same content root: file:///home/trustin/Workspaces/armeria/it/spring/boot-tomcat/src/main/java
Modifications:
- Do not use the `sourceSets` directive for a derived project.
- Reorder the directives in `:it:spring:boot-tomcat8.5` so that build
plugin part comes first
- Remove an unused dependency
Result:
- IDE devs are happy.
=> Do not confuse an IDE by having a source directory with two output directories

core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/internal/Http2ObjectEncoder.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Motivation:
When a client-side subscriber of a response stream closes the response
stream even before any HEADERS frame is sent to the stream, Armeria
tries to send a RST frame to that stream, which is a violation of
HTTP/2.
Modifications:
- Do not send a RST frame if the stream does not exist yet.
- Do not fail a client-side HTTP/2 connection even if
Http2ResponseDecoder failed to write a received HttpObject to a
response stream.
- Remove the test skip code in GrpcClientTest
Result:
- GrpcClientTest is not flaky anymore.
- HTTP/2 connections are not closed unexpectedly.
=> Fix a bug where a RST frame for a non-existent stream can be sent

core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
Motivation:
When a user sets up his or her server like the following:
new ServerBuilder()
.tls(...)
.service(...)
.build();
The server will listen at two ephemeral ports, one for HTTP and the
other for HTTPS.
This is a surprising behavior - a user would expect the server to listen
at an HTTPS port only.
Modifications:
- Do not add HTTP port but only HTTPS port if TLS was enabled and no
port was specified.
Result:
- Fixes #1279
=> Do not add HTTP port if TLS was enabled and no port was specified

core/src/main/java/com/linecorp/armeria/server/AnnotatedElementNameUtil.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedValueResolver.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceBuilderTest.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedValueResolverTest.java
Motivation:
Armeria currently raises an exception when a user creates an annotated
service with redundant use of Optional and Default:
// No need to use Optional because 'value' is always present.
@Get("/foo/:value")
public String foo(@Param Optional<String> value) {}
// No need to use @Default because 'value' is always present.
@Get("/bar/:value")
public String bar(@Param @Default("defVal") String value) {}
// Optional and @Default were used together. 'value' will always be present.
@Get("/baz")
public String baz(@Param @Default("defVal") Optional<String> value) {}
We could relax a little bit and just warn so that the server starts up
anyway because it wouldn't harm and it would give a user less surprise.
Modifications:
- Log a warning message instead of raising an exception when a …
=> Do not fail but warn when Optional and Default are used redundantly

dependencies.yml
Netty 4.1.27 has been released to fix some regressions showed up in 4.1.26.
=> Update Netty from 4.1.26 to 4.1.27

core/src/main/java/com/linecorp/armeria/server/Server.java
Motivation:
When a user attempts to stop a server that's currently starting up or to
start a server that's currently shutting down, `Server` re-attempts to
stop/start the server after the current job (start/stop) is finished.
In a rare case, such a follow-up re-attempt is invoked even before the
state machine of the server gets a chance to enter `STOPPED` or `STARTED`
state, leading to infinite recursion.
Modifications:
- Use `handleAsync` rather than `handle` for potentially recursive
operations, so that the state machine is given a chance to enter a new
state.
Result:
`StackOverflowError` is gone.
=> Fix a StackOverflowError when stopping a starting server or starting a stopping server

site/src/sphinx/_extensions/api.py, site/src/sphinx/client-grpc.rst, site/src/sphinx/client-thrift.rst, site/src/sphinx/server-access-log.rst
Motivation:
Since Java 9, Javadoc defaults to non-framed version. We should be
consistent across our web site for hyperlinks to Javadoc.
Modifications:
- Use hyperlinks to non-framed versions of Javadoc
Result:
Consistency
=> Do not use framed version of Javadoc

.post-release-msg
So that a user(me) never forget to checkout gh-pages before publishes the site.
=> Add the git checkout action to post-release-msg

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java, core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Motivations:
- A user sometimes want to register duplicated entries to EndpointGroup
to implement `virtual node` to balance requests. But if duplicated
entries are added to an `EndpointGroups`, it stops to update EndpointGroup
refresh.
Modifications:
- Apply merging function not to throw exception when duplicated entries
are found in endpoint group list.
=> Allow to register duplicated endpoints under HealthCheckedEndpointGroup

.travis.yml
Motivation:
Oracle keeps removing the old JDK download URLs whenever they release a
new version.
Modifications:
- Use `openjdk10` instead of `oraclejdk10`
- Pass `-Djavax.net.ssl.trustStore` to use the system certificates
- Add `~/.cache/install-jdk` to the build cache
Result:
Build stability
=> Use OpenJDK 10 instead of Oracle JDK 10 for build stability

core/src/main/java/com/linecorp/armeria/client/Endpoint.java, core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
Motivation:
Endpoint.toString() should include the IP address of an endpoint if
necessary. It currently does not include it at all.
Modifications:
- Fix incorrect `if` statement.
- Update the test case.
Result:
- The string representation of an `Endpoint` now includes its IP
address.
=> Fix a bug where Endpoint.toString() does not include IP address

core/src/main/java/com/linecorp/armeria/server/RejectedPathMappingHandler.java, core/src/main/java/com/linecorp/armeria/server/Routers.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/VirtualHost.java, core/src/test/java/com/linecorp/armeria/server/RouterTest.java
Motivation:
When Armeria is used as a part of another framework/library, the
framework/library may want to have control over how duplicate path
mappings are handled, rather than just throwing an exception.
Modifications:
- Add `RejectedPathMappingHandler` which provides a callback method for
rejected duplicate path mappings
- Change the default behavior from 'throw an exception' to 'log a warning'
- Add `ServerBuilder.rejectedPathMappingHandler()`
Result:
- Fixes #1283 
- More control over duplicate path mappings
=> Add RejectedPathMappingHandler

core/src/main/java/com/linecorp/armeria/internal/ChannelUtil.java, core/src/main/java/com/linecorp/armeria/internal/TransportType.java, core/src/test/java/com/linecorp/armeria/client/HttpClientPipeliningTest.java, core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClientTest.java, core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java, core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriterTest.java, core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/server/auth/AuthorizerTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, testing/src/main/java/com/linecorp/armeria/testing/common/AbstractEventLoopGroupRule.java, testing/src/main/java/com/linecorp/armeria/testing/common/EventLoopGroupRule.java, testing/src/main/java/com/linecorp/armeria/testing/common/EventLoopRule.java, testing/src/main/java/com/linecorp/armeria/testing/common/package-info.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Motivation:
It would be useful to have JUnit `TestRule`s for Netty `EventLoop` and
`EventLoopGroup`.
Modifications:
- Add `EventLoopRule` and `EventLoopGroupRule`
- Update our tests to leverate the rule.
- Fix a bug where `TransportType` rejects `EpollEventLoop`
Result:
- Easier to prepare an event loop in a test case
=> Add EventLoopRule and EventLoopGroupRule

core/src/main/java/com/linecorp/armeria/common/RequestContext.java
It is extremely common to use the `RequestContext`-aware eventloop as just an `Executor` for callbacks (e.g., `thenApplyAsync`). Unfortunately, when writing unit tests for such code, it can be cumbersome to mock `RequestContext` because there is no direct executing event loop (an event loop with an immediate executor usually deadlocks since callbacks get blocked by the previously running item in the loop). It slows down tests to create threads and is cumbersome to shut them down.
This exposes the exact same event loop as an `Executor`. It is purely to allow easier writing of tests where it them becomes possible to just do `when(ctx.contextAwareExecutor()).thenReturn(MoreExecutors.directExecutor())` for many cases where direct execution doesn't deadlock, allowing for faster, simpler tests.
=> Expose context-aware Executor for easier tests

core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
Inspried by https://line-armeria.slack.com/archives/C1NGPBUH2/p1527204753000180 and @chokoswitch 's idea in https://github.com/curioswitch/curiostack/issues/144#issuecomment-392628889 , try to add numMaxConnections Flag. 
And set the default value as 10000 according to https://stackoverflow.com/a/25765451 
> The defaults are maxConnections=10,000 and maxThreads=200.
=> add numMaxConnections Flag

core/src/main/java/com/linecorp/armeria/common/CommonPools.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/BlockingCallSubscriber.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/PipeBuffer.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriber.java, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/SubscriberFactory.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryLargeStreamTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/BlockingCallSubscriberTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriberTest.java
Current implementation will buffer all data and call callback when complete.
So it's not suitable for downloading large files.
This PR will make subscriber requests data one by one from response.　And
because `SourceBuffer#read` and `Subscriber#onNext` are using same thread, we need to
using CommonPools to run `SourceBuffer#read` to avoiding deadlock.
=> Make Armeria Retrofit subscriber not buffer response

core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/internal/ChannelUtil.java, core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
Motivation:
JDK's default X509TrustManager implementation skips host name
verification entirely when SSLParameters.endpointIdentificationAlgorithm
is null or empty, which is our current default.
This can be a security threat because an IP address HTTPS request like
`https://10.0.1.2/` will never fail as long as the server gives a valid
certificate.
Modifications:
- Always set 'HTTPS' to SSLParameters.endpointIdentificationAlgorithm
Result:
- Not insecure anymore
=> Ensure SSLParameters.endpointIdentificationAlgorithm is 'HTTPS'

docs-client/src/containers/MethodPage/index.tsx
Please consider this PR as a feature request.
I added two buttons above the response section of the method page. They are the same level as Debug title, so should not comsume additional space.
Copies whole response text to the clipboard.
While using Armeria docs-client I often deal with big responses and it is often difficult to select and copy the whole response. This is where `Copy` button will be useful.
Clears the response text.
Sometimes when I make the same request the second time it is hard to understand if I still see result of the last one or it is new one but the response is the same. In this case I reload the page to make the second request.
[execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) on the temp textarea is used to put text to the …
=> Add Copy and Clear buttons to docs client

build.gradle, core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java, core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandler.java, core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java, core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java, core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java, grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
Motivation:
Exposing the server-side stack trace in a response can be a security
concern depending on server configuration.
Modifications:
- Add a new system property called `com.linecorp.armeria.verboseResponses`
so that a user can go back to the previous behavior.
- Do not include stack traces in `THttpService` responses by default.
- Include stack traces in `GrpcService` responses if the flag is set.
- Un-deprecate `Exceptions.traceText()` and make it always use `\n` as a line delimiter
- Replace `Throwables.getStackTraceAsString()` and `System.lineSeparator()` with
`Exceptions.traceText()` and `\n`
Result:
- A little bit more out-of-the-box security
- gRPC response stack traces are sent if enabled.
- Platform independent stack trace responses
@anuraaga Anything to …
=> Add a new flag: 'com.linecorp.armeria.verboseResponses'

core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java, core/src/test/java/com/linecorp/armeria/internal/PathAndQueryTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
Motivation:
- A user can send a request to an invalid URL using HttpClient:
```java
HttpClient.newClient(...).get("/a\nb");
```
- A server accepts a path that contains control characters.
- A server does not filter out the paths with double dots when they are
encoded, e.g. `/%2e%2e/%2e%2e/secret.txt`
Modifications:
- Reject control characters
- Decode percent-encoded characters before complex validation
- Encode a raw Unicode string to UTF-8
- Various optimizations
- Slash deduplication while decoding
- Percent encoding validation while decoding
- Add test cases
Result:
- Fixes #1323
- A user cannot send an invalid request with Armeria.
- Armeria filters out more potentially malicious requests.
=> More strict path validation

site/src/sphinx/server-basics.rst
=> Fix broken link

spring/boot-autoconfigure/build.gradle, spring/boot1-autoconfigure/build.gradle
If metadata is generated, we can use code completion and code jump feature in IntelliJ.
I think that is helpful.
---
Unfortunately, the `ports` property defined with List doesn't seem to be complemented.
---
Official documentation of Spring Boot:
- [Spring 1.5.x](https://docs.spring.io/spring-boot/docs/1.5.15.RELEASE/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor)
- [Spring 2.0.x](https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor)
=> Generate config metadata for Spring

dependencies.yml, zipkin/src/main/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContext.java, zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java, zipkin/src/test/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContextTest.java, zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java, zipkin/src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceTest.java
This allows us to do things now that we are using a custom thread local.
See https://github.com/openzipkin/brave/pull/683
=> Allows trace scope decoration such as Log4J trace ID correlation

core/build.gradle, core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java, core/src/main/java/com/linecorp/armeria/server/Server.java, core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java, core/src/test/java/com/linecorp/armeria/common/util/StartStopSupportTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
Motivation:
It would be useful to provide a general construct that helps a user
implement asynchronous startup/shutdown life cycle, just like we do for
`Server.start()` and `stop()`.
Modifications:
- Add `StartStopSupport`
- Use `StartStopSupport` in `Server`
- Do not run streaming tests in `:code:shadedTest`
- Fix a bug where `DocStringExtractor` uses a wrong `ClassLoader`
Result:
- Reusability
- Slightly reduced build time
- Fixes build failures due to the test failures in `GrpcDocStringExtractorTest`
=> Add StartStopSupport

docs-client/src/containers/App/index.tsx
This PR is to add the collapse feature to side menu which will be useful for developers when having a large list of `services` `enums` `structs` `exceptions`.
There are mainly three changes:
- Collapse feature for `services` `enums` `structs` `exceptions` sidemenu.
- Add `dense` to each `ListItem` which changed `padding-top` and `padding-down` from `12px` to `8px`
- All ListItems expand
- Click first Item
=> Apply collapse to side menu

core/src/main/java/com/linecorp/armeria/server/Server.java, core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Motivations:
- When a server starts multiple times, it fails to start later one but
start/stopFuture for later one will be stuck since there is no chance to
complete the future.
Modifications:
- Completes a stopFuture immediately if Server does not start server serverChannels yet
- Shutdown server correctly even if fails to startup
=> Completes stopFuture immediately if Server does not start server serverChannels yet

site/src/sphinx/advanced-logging.rst
custom attribute use `some_value` is most place.
=> Fix advanced logging document not consistent

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java, core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java, core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/test/java/com/linecorp/armeria/server/HttpServerAbortingInfiniteStreamTest.java, testing/src/main/java/com/linecorp/armeria/testing/server/ServerRule.java
Motivation:
When the server responds infinite streaming data, the client can aborts the stream at any time. If it does, the stream should be aborted immediately for the both side of the server and the client, but for now the stream does not be aborted until the request timeout is occurred.
Modifications:
- Client-side:
- Call HttpResponseWrapper#onSubscriptionCancelled instead of #close when the subscription is cancelled. Calling #close with CancelledSubscriptionException raises IllegalArgumentException which is unexpected for while cancelling subscription.
- Server-side:
- Http2RequestDecoder aborts the response stream when a RST_STREAM frame is received from the client. Before that, it closed the request with an Http2Exception, but the exception did not be propagated into the response …
=> Abort a response stream immediately when a client aborts the stream

core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java, core/src/test/java/com/linecorp/armeria/internal/PathAndQueryTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
Motivation:
The following query string:
a=1%26a=2
should be interpreted as a single query entry whose key is `a` and value
is `1&a=2`. However, `PathAndQuery` currently handles it as two query
entries: `a=1` and `a=2`.
It is because `PathAndQuery` decodes `%26` into `&` internally, making `%26`
indistinguishable from `&`.
Also, `%3D` in a query string should be similarly due to the case where
a query string key contains `=`: `a%3Db=1`
Modifications:
- Decode `%26` and `%3D` into a special marker character so that it is encoded
back into `%26` and `%3D` in `PathAndQuery`
- Update test cases
- ArmeriaCallFactory has been updated by @kojilin.
Result:
- A query parameter that contains an ampersand or an equal sign is interpreted correctly.
=> Handle `%26` and `%3D` in a query string correctly

zipkin/src/main/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContext.java, zipkin/src/test/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContextTest.java, zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java
While the `RequestContext` can be treated as the only thread-local for the request thread, this isn't the case for other threads, i.e., when making callbacks run in a threadpool context-aware. For such callbacks, we need to use a separate thread-local to prevent the multiple threads from clashing the context.
=> Use thread local when creating scopes off of the request context thread.

thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientInvocationHandler.java, thrift/src/main/java/com/linecorp/armeria/common/thrift/AsyncMethodCallbacks.java, thrift/src/test/java/com/linecorp/armeria/common/thrift/AsyncMethodCallbacksTest.java
Motivation:
The following is a very common idiom when implementing an asynchronous
Thrift service:
public void myThriftServiceMethod(AsyncMethodCallback<String> cb) {
CompletableFuture<String> f = someAsyncOp();
f.whenComplete((res, cause) -> {
if (cause != null) {
if (cause instanceof Exception) {
cb.onError(cause);
} else {
cb.onError(new CompletionException(cause));
}
} else {
cb.onComplete(res);
}
});
}
We could provide some utility for this:
public void myThriftServiceMethod(AsyncMethodCallback<String> cb) {
AsyncMethodCallbacks.transfer(someAsyncOp(), cb);
}
Modifications:
- Add `AsyncMethodCallbacks.transfer()` and `transferAsync()`
- Add `AsyncMethodCallbacks.invokeOnError()` for deduplication with
`THttpClientInvocationHandler`.
Result:
- Fixes #508
- Slightly better Thrift …
=> Add AsyncMethodCallbacks which bridges the gap between CompletionStage and AsyncMethodCallback

core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java, core/src/test/java/com/linecorp/armeria/internal/PathAndQueryTest.java
Motivation:
The validation logic in `PathAndQuery` is still too restrictive. It
should allow `%09`, `%0A` and `%0D` (TAB, LF and CR) which can be
included in a query string part, e.g. a user can enter a multi-line
text in a form.
Modifications:
- Allow TAB, CR and LF in a query string.
- They are still unallowed in a path part.
Result:
- Innocent web form submissions are not rejected.
=> Allow TAB, CR and LF in a query string

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java, core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupBuilder.java
Motivations:
- Currently, we use default `ClientOptions` for healthcheck `HttpClient` (15 seconds). And it causes that `HttpHealthCheckedEndpointGroup` exposes unhealthy endpoint if a target endpoint stucks.
Changes:
- Provide a `ClientOptions` customizer for healthcheck `HttpClient`
=> Customize client options of HttpClient used in HttpHealthCheckedEndpointGroup

retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
The test should check if the content type is `null`, but it checks query.
=> Fix wrong assert condition in AremriaCallFactoryTest

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java, core/src/main/java/com/linecorp/armeria/internal/Http2ObjectEncoder.java, core/src/main/java/com/linecorp/armeria/internal/HttpObjectEncoder.java, core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
Motivation:
`HttpRequestSubscriber` retrieves the last `ChannelHandlerContext` in a
`ChannelPipeline` using `ChannelPipeline.lastContext()`. However,
`lastContext()` may return `null` when called on a closed `Channel`.
Modifications:
- Do not use `ChannelPipeline.lastContext()`.
- Make `HttpObjectEncoder` implementations keep the non-null reference
to `Channel` or `ChannelHandlerContext` for 1) no change of NPE and 2)
simpler method signatures.
Result:
- NPE is gone.
- Slightly simpler encoder code.
=> Fix NPE in HttpRequestSubscriber.onSubscribe()

build.gradle, grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
- Closes #1370
- Make sure a request is always closed in `ArmeriaClientCall`
- Make sure an `HttpStreamReader` is always cleaned up when a request it
is reading is closed.
- Fixed an incomplete test case `GrpcClientTest.largeUnary_unsafe()`
- Fixed a leak in `ArmeriaServerCallTest`
=> Fix ByteBuf leaks in gRPC client and server

examples/annotated-http-service/src/main/java/example/armeria/server/annotated/MessageConverterService.java, saml/src/main/java/com/linecorp/armeria/server/saml/HttpPostBindingUtil.java, saml/src/main/java/com/linecorp/armeria/server/saml/HttpRedirectBindingUtil.java, saml/src/main/java/com/linecorp/armeria/server/saml/KeyStoreCredentialResolverBuilder.java
Motivation:
The `Basic` type base64 decoder rejects data that contains characters outside the base64 alphabet.
However, some identity provider produces base64 with line feed character, so we need to use
`MIME` type base64 decoder instead of the `Basic` type.
Modifications:
- Get base64 decoder by calling Base64.getMimeDecoder() instread of Base64.getDecoder().
- Improve KeyStoreCredentialResolverBuilder:
- Able to read a keystore file from file system.
- Able to specify keystore type.
=> Use MIME type base64 decoder for SAML messages

core/src/main/java/com/linecorp/armeria/server/Server.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Motivation:
A user may not prefer using `GlobalEventExecutor` to invoke `Server`
start/stop callbacks.
- The user may want the context `ClassLoader` to be preserved.
- The user may want to use a different `Executor` for many other reasons such as
organizational policy, personal preferences, and more.
Modifications:
- Add `ServerBuilder.startStopExecutor()`
Result:
- Fixes #1378
=> Allow specifying the `Executor` used for invoking `Server` start/stop callbacks

core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactory.java, core/src/main/java/com/linecorp/armeria/server/annotation/DefaultExceptionHandler.java, core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionHandlerFunction.java, core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionLoggingMode.java, core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionVerbosity.java
Motivation:
A user may want to know why his or her annotated service returns 400 or 500 status code from the log files.
Modifications:
- Add a flag `com.linecorp.armeria.annotatedServiceExceptionVerbosity`
- Add `ExceptionVerbosity` enum to control logging
Result:
A user can get every exception when adding `com.linecorp.armeria.annotatedServiceExceptionVerbosity=all` to the system properties.
=> Add a flag `com.linecorp.armeria.annotatedServiceExceptionVerbosity`

core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/Server.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, core/src/main/java/com/linecorp/armeria/server/logging/AccessLogWriter.java, core/src/main/java/com/linecorp/armeria/server/logging/AccessLogWriters.java, core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLog.java, core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLogBuilder.java, core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLoggingService.java, kafka/src/main/java/com/linecorp/armeria/server/logging/kafka/KafkaAccessLogWriter.java, kafka/src/main/java/com/linecorp/armeria/server/logging/kafka/package-info.java, kafka/src/main/java/com/linecorp/armeria/server/logging/structured/kafka/KafkaStructuredLoggingService.java, kafka/src/main/java/com/linecorp/armeria/server/logging/structured/kafka/StructuredLogJsonKafkaSerializer.java, kafka/src/test/java/com/linecorp/armeria/server/logging/kafka/KafkaAccessLogWriterTest.java
Motivation:
- `StructuredLoggingService` is not capable of logging unmapped or broken
requests.
- `StructuredLog` is of dubious value. Nobody uses it or people can just
build his/her own.
Modifications:
- Add `AccessLogWriter` interface
- Deprecate `AccessLogWriters` and add the same factory methods to
`AccessLogWriter`
- Replace the usage of `Consumer<RequestLog>` with `AccessLogWriter`
- Add `ServerConfig.shutdownAccessLogWriterOnStop`
- Add `KafkaAccessLogWriter`
- Deprecate `KafkaStructuredLoggingService`
- Deprecate `StructuredLogJsonKafkaSerializer`
- Use https://github.com/daniel-shuy/kafka-jackson-serializer instead.
- Deprecate all classes under `server.logging.structured`
Result:
- Leaner API
- Can send Kafka records for unmapped or broken requests
=> Add `AccessLogWriter` and deprecate StructuredLog and its related classes

benchmarks/build.gradle
Was curious about the impact of Epoll and BoringSSl. Found that on Java 11,
- Epoll does seem to offer some performance
- OpenSSL and JDK SSL are very similar
- With many benchmark threads, upstream gRPC beats us quite a lot...
```
./gradlew :benchmarks:jmh '-Pjmh.include=grpc.*empty$' -Pjmh.params=clientType=OKHTTP -Pjmh.jvmargs='-Dcom.linecorp.armeria.useEpoll=true' -Pjmh.threads=32
Benchmark                                           (clientType)   Mode  Cnt      Score      Error  Units
c.l.a.g.downstream.DownstreamSimpleBenchmark.empty        OKHTTP  thrpt    5  38571.146 ± 1453.260  ops/s
c.l.a.g.upstream.UpstreamSimpleBenchmark.empty            OKHTTP  thrpt    5  94110.982 ± 3330.314  ops/s
./gradlew :benchmarks:jmh '-Pjmh.include=grpc.*empty$' -Pjmh.params=clientType=OKHTTP …
```
=> Allow setting JMH jvm args with command line param.

core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
I didn't find any real difference in my usual benchmark, but doesn't hurt to have knobs. The defaults change though
- Initial window size is 1MB instead of HTTP/2 default of 64K
- Max header size is 8K, just like our default HTTP/1 max
I just followed gRPC upstream but it'd be fine to change these defaults too.
Fixes #1241
=> Allow configuring HTTP2 SETTINGS frame.

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java, core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java, core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, core/src/test/java/com/linecorp/armeria/client/Http2ClientSettingsTest.java, core/src/test/java/com/linecorp/armeria/client/Http2GoAwayTest.java
- Made sure both client and server have the following HTTP/2 settings
- Connection-level initial window size
- Stream-level initial window size
- Max frame size
- Max header list size
- Reordered the fields and methods related with HTTP settings so that
HTTP/2 settings come right before HTTP/1 settings.
- (breaking) Made the protocol-related property names consistent so that
they all start with protocol name first, e.g.
- `maxHttp1ChunkSize` -> `http1MaxChunkSize`
- `initialHttp2ConnectionWindowSize` -> `http2InitialConnectionWindowSize`
- Renamed `ServerBuilder.http2InitialWindowSize` to `http2InitialStreamWindowSize`
- Added `ServerBuilder.http2InitialConnectionWindowSize` and implemented
connection-level initial window size update in `HttpServerHandler`.
- Improve/fix validation of …
=> Make more HTTP/2 settings configurable and make them consistent

core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java, core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandler.java, core/src/main/java/com/linecorp/armeria/internal/Http2GoAwayHandler.java, core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java, core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java, testing-internal/src/main/resources/logback-test.xml
Motivation:
- We currently add 2 `Http2Connection.Listener`s, `Http2GoAwayListener`
and `Http2(Request|Response)Decoder`. We could add only a single
listener so that Netty does not waste time to notify the events which
is uninteresting to `Http2GoAwayListener`.
- We handle GOAWAY frames in more than one place, which is not great for
readability.
- Netty invokes `onGoAwaySent()` callback even if the connection has
been closed already and thus a GOAWAY frame is never sent. This makes
`Http2GoAwayListener` log a false-positive message at WARN level.
Modifications
- Renamed `Http2GoAwayListener` to `Http2GoAwayHandler`.
- `Http2GoAwayHandler` is not an `Http2ConnectionAdapter` anymore.
- Moved all GOAWAY-related code to `Http2GoAwayHandler`.
- Clean-up
- Reordered some constructor parameters …
=> Overall cleanup of HTTP/2 handlers / Do not send GOAWAY to a closed connection

core/src/main/java/com/linecorp/armeria/server/docs/DocService.java, core/src/main/java/com/linecorp/armeria/server/docs/DocServiceBuilder.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServiceTest.java
It can be useful to be able to inject a per-request script into the docs page (e.g., a randomly generated token for bypassing auth checks).
=> Allow specifying injected docs scripts per request.

benchmarks/README.md, benchmarks/build.gradle, dependencies.yml
Motivation:
- We have various non-standard properties that allows a user to specify
JMH options, but they are barely documented.
- @ktoso wrote `sbt-jmh-extras` which provides JMH profiler
implementations based on async-profiler and JFR.
- https://github.com/ktoso/sbt-jmh
- https://github.com/jvm-profiling-tools/async-profiler
Modifications:
- Add `README.md`
- Add `sbt-jmh-extras` to the JMH class path
- Reorganize the build script a little bit
Result:
- A user can run and customize the benchmarks easilyy.
- A user can generate a flame graph using async-profiler.
=> Add README for benchmarks / Add async-profiler support

core/src/main/java/com/linecorp/armeria/client/DefaultHttpClient.java, core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/UserClient.java, core/src/test/java/com/linecorp/armeria/client/HttpClientWithRequestLogTest.java, thrift/src/main/java/com/linecorp/armeria/client/thrift/DefaultTHttpClient.java
Motivation:
The `RequestLog` should be complete because the active request count of an `EventLoop`
is decreased when the `ReqeustLog` is complete.
However, if an exception is raised even before sending an `HttpRequest` by specifying
invalid URI, failing to resolve URI, etc, the `RequestLog` is not complete.
Modifications:
- Fix to complete `RequestLog`
- Fix to abort the `HttpRuest`
Result:
- Less bugs
=> Fix a bug where RequestLog is not complete under certain circumstances

core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java, core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
Users may have a specific reason to use special escaping in a client request (it may be the contract of the server such as [here](https://cloud.google.com/storage/docs/json_api/#encoding)). While the client should make sure request paths are valid, it should not overwrite whatever escaping the user may have used.
A side effect is double slashes are sent as is instead of rewriting them to single slashes. It's conceivable that a server requires double slashes for whatever reason and the client should support it (grudgingly).
Fixes #1416
=> Don't rewrite the user's path if it is valid since it may be escaped.

core/build.gradle, gradle.properties, settings.gradle
Motivation:
- A developer should be able to build Armeria on Java 11.
Modifications:
- Disable ProGuard if Java version is 11+.
- Release still must be done on Java 10 to trim the shaded JAR.
- Disable TLSv1.3 so that handshake failures do not occur when
retrieving package-list files.
Result:
- Armeria builds fine on Java 11.
=> Make Armeria builds on Java 11

core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
Motivation:
- We always specify the current event loop when subscribing to a
user-provided `HttpRequest` or `HttpResponse`. Therefore, we do not
really need to use `EventLoop.execute()` anywhere in
`Http(Request|Response)Subscriber`.
- We forgot to specify the event loop when subscribing to the response
of the HTTP/1-to-2 upgrade request. As a result, we subscribe using
`CommonPools.workerGroup()` which is not optimal.
Modifications:
- Do not use `EventLoop.execute()` in `Http(Request|Response)Subscriber`.
- This change triggered an issue where `412 Request Entity Too Large`
response is not sent due to a slight change in event ordering.
- Specify corrent `EventLoop` when subscribing to HTTP/1-to-2 upgrade
responses in `HttpClientPipelineConfigurator`.
Result:
This pull request improves …
=> Reduce unnecessary event loop task queueing

core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframer.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageFramer.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframerTest.java
Motivation:
We perform unnecessary memory copies while handling a gRPC request.
Modifications:
- Use `ByteBufHttpData` instead of `HttpData.of()` in
`Http2ResponseDecoder`
- Use a queue of `ByteBuf`s instead of `CompositeByteBuf` for deframing
in `ArmeriaMessageDeframer`, because the buffers we get from
`CompositeByteBuf` is often copied or wrapped with indirection.
- Use `CompositeByteBuf` to prepend a frame header if the frame is
larger than 128 bytes
Result:
Higher performance.
Before:
Benchmark                     (wrapBuffer)   Mode  Cnt   Score   Error  Units
LargePayloadBenchmark.normal         false  thrpt  100  35.266 ± 0.191  ops/s
LargePayloadBenchmark.normal          true  thrpt  100  40.839 ± 0.228  ops/s
After:
Benchmark                     (wrapBuffer)   Mode  Cnt    Score …
=> Reduce memory copies in `Http2ResponseDecoder` and gRPC

dependencies.yml, docs-client/build.gradle
Motivation:
Yarn 1.12.1 creates a broken symlink:
- https://github.com/yarnpkg/yarn/issues/6585
- https://github.com/yarnpkg/yarn/issues/6615
Gradle fails the build on Windows when it encounters a broken symlimnk:
- https://github.com/gradle/gradle/issues/1365
Modifications:
- Delete broken symlinks after running `:docs-client:yarn`
Result:
- Gradle is happy. Build is green.
=> Fix a build error on Windows

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java, core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupBuilder.java, core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
As we discussed internally @trustin. 
The use case is when we wrap HttpHealthCheckEndpoint by DnsEndpoint and use different port by DnsEndpoint (for example,  UDP).
=> Make HttpHealthcheckEndpointGroup port customizable

core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientAuthorityHeaderTest.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java, thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Motivation
When an `HttpClient` sends an `HttpRequest`, the authority header is set automatically in `HttpRequestSubscriber`.
If we retry to the same host every time, we do not have to reset the authority header, but the reality is not.
So we should remove the authority header when it wasn't set by a user so that the request is sent with proper authority header.
Modifications:
- Remove the authority header in `RetryingHttpClient` when the authority header is not set by a user
- Fix flaky test
Result:
- less bugs
- less flaky
=> Fix a bug where authority header is not set properly when RetryingClient is used

zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
Empty service name will cause an exception to be thrown by `Span.remoteServiceName`
=> Check for empty remote service name which isn't allowed.

core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
Motivation:
`DefaultClientRequestContext.alloc()` returns
`UnpooledByteBufAllocator.DEFAULT` when the current `Channel` is not
determined yet. This can lead to poor performance when a `Client` tries
to get the allocator early.
Modifications:
- Return `PooledByteBufAllocator.DEFAULT` when `Channel` is not
determined yet.
Result:
- Better client-side gRPC performance (apx. 5% improvement)
master:
Benchmark                        (clientType)   Mode  Cnt      Score     Error  Units
DownstreamSimpleBenchmark.empty        NORMAL  thrpt  100  75881.642 ± 178.229  ops/s
This PR:
Benchmark                        (clientType)   Mode  Cnt      Score     Error  Units
DownstreamSimpleBenchmark.empty        NORMAL  thrpt  100  78863.742 ± 179.395  ops/s
=> Do not use UnpooledByteBufAllocator

core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java, core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java, core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java, core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java, core/src/main/java/com/linecorp/armeria/common/HttpRequest.java, core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/HttpStreamReaderTest.java, jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java, thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Related: #1426
Motivation:
`CompletableFuture` always creates a new `CompletionException` after it
calls the callback registered with `whenCompleteAsync()`, even if there
are no dependants and the `CompletionException` will never be used.
See https://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.base/share/classes/java/util/concurrent/CompletableFuture.java#l870
for more information.
Modifications:
- Use `CompletableFuture.handleAsync()` instead of `whenCompleteAsync()`.
- Avoid using `voidFunction()` which increases the level of indirection
Result:
- Fixes #1426
- Better performance
master:
Benchmark                        (clientType)   Mode  Cnt      Score     Error  Units
DownstreamSimpleBenchmark.empty        NORMAL  thrpt  100  52167.567 ± 274.358  ops/s …
=> Avoid using CompletableFuture.whenCompleteAsync()

core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
Fix NPE in AbstractStreamMessageDuplicator
Motivation:
`StreamMessageDuplicator` feed null to its `Subscriber`. (related with #1446)
Modifications:
- Assign the `elements` to a local variable in the method `get(index)` in `SignalQueue` so that the reference is not changed during the get operation
- Add some `assert` statements which produce useful information for debugging purpose
Result:
- Fewer bugs
=> Fix NPE in AbstractStreamMessageDuplicator

core/build.gradle
Motivation:
Our test coverage has decreased since a79badce5f28e1e804b06fb5d1fec65075bb7974
because `:common:testNg` and `:common:testStreaming` task did not run
with shaded classes and thus JaCoCo ignored the data collected from them
due to mismatching byte code offsets.
Modifications:
- Run TestNG and streaming tests with shaded classes
Result:
Test coverage is up again.
=> Run TestNG and streaming tests with shaded classes

grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Completely forgot to call the `unescape` method anywhere outside of unit tests.
Fixes #1460
=> Unescape grpc message description in client.

core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
Motivation
---
We get a wrong response time after upgrading 0.76.X.
Response time present 1970-01-...
```
2018-11-28 11:05:12.542|DEBUG|armeria-common-worker-nio-7-4||RequestContextAwareLogger.java:148|[id: 0x3e355099, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:63853][h1c://al01370165.local:8080/api/v1#POST] Response: {startTime=1970-01-18T20:42:50.712Z(1543370712), length=2497B, duration=292µs(292431ns), headers=[:status=200, content-type=application/x-thrift; protocol=TTEXT, content-length=2497], content=DefaultRpcResponse{Reactions(reactions:{1150267870113044227=Reaction(like:LikeResults(type:null, count:1, likeList:[Like(parentId:1150267870113044227, mid:ufe3b776fbc1d451aeb7611a6f8af473c, serialNumber:1, type:1001, createdDate:1541413760652, updatedDate:0)], hasMore:false, …
```
=> Fix the wrong unit of response time

site/src/sphinx/server-grpc.rst
I tried to set up my server to accept gRPC unframed requests by following the instructions of the page "Running a gRPC service", but it didn't work.
The description of "Unframed requests" in the page seems to need the following two corrections.
*  In the example code, `GrpcSerializationFormats.JSON` must be given to `GrpcServiceBuilder.supportedSerializationFormats()`, because [the default formats are only `PROTO` and `PROTO_WEB`](https://github.com/line/armeria/blob/master/grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java#L53-L54).
* Content-Type must be `application/json; charset=utf-8`, not simply `application/json`, since [`UnframedGrpcService` requires `MediaType.JSON_UTF_8`](https://github.com/line/armeria/blob/master/grpc/src/main/java/com/linecorp/armeria/ …
=> Correct documentation on GrpcService's Protobuf-JSON support

core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java, core/src/main/java/com/linecorp/armeria/internal/TransportType.java, core/src/main/java/com/linecorp/armeria/server/Server.java
Motivation:
`EventLoopGroup.serverChannelClass()` should be renamed to
`serverChannelType()` for consistency with other methods.
Modifications:
- Added `EventLoopGroup.serverChannelType()` and deprecate
`serverChannelClass()`.
- Renamed `TransportType.serverChannelClass()` to `serverChannelType()`.
- Reordered the methods in `TransportType`.
- Renamed field names in `TransportType` for consistency with its
getter method names.
Result:
- Consistency
=> Rename `EventLoopGroups.serverChannelClass()` to `serverChannelType()`

core/src/main/java/com/linecorp/armeria/client/ClientFactory.java, core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
See: #1082
Motivation:
A Spring user who uses `ClientFactory.DEFAULT` may observe the problem
where the default `ClientFactory` is closed before his/her Spring
application is fully destroyed.
Modifications:
- Added `ClientFactory.disableShutdownHook()`
Result:
- A user have full control over when the default `ClientFactory` can be
closed.
=> Allow disabling default ClientFactory shutdown hook

core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupMetrics.java, core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Sometime we may have some endpoint groups using ip, some not. But
MeterRegistry doesn't allow us to create label with different tags. So
we need to set blank to ip tag if there is no ip addr.
=> Fix endpoint group health check metrics register different tag problem.

dependencies.yml, retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java
* Timeout.deadlineNanoTime is similar to ClientRequestContext.responseTimeoutMillis, but client-side timeout is not runtime-adjustable in Armeria, unlike Timeout API does.
* There's nothing in Armeria that matches the contract of Timeout.timeoutNanos.
Until we can support them, perhaps we could use Timeout.NONE
=> Make armeria support retrofit 2.5

docs-client/package.json, docs-client/src/containers/MethodPage/index.tsx, docs-client/src/lib/specification.tsx, docs-client/yarn.lock, licenses/web-licenses.txt
Motivation:
At the debug page in the documentation service, only service level `exampleHttpHeaders` are shown.
Modification:
- Fix to add method level and entire level `exampleHttpHeaders` to the debug page
Result:
- Better debug page
=> Fix to add exampleHttpHeaders to the DocService debug page

core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java, core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactory.java, core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceExceptionHandlerTest.java
Motivation:
In annotated HTTP service, a user may use both a decorator and an exception handler together for his or her service.
In this case, it would be more useful to let the exception handler handle an exception raised from the decorator.
Modifications:
- Add `ExceptionFilteredHttpResponseDecorator` to the first of a decorator chain when the chain is not empty.
- It wraps an `HttpResponse` with `ExceptionFilteredHttpResponse` if the response is not an instance of `ExceptionFilteredHttpResponse`, in order to handle an exception raised from a decorator.
- Avoid converting `HttpResponseException` to a response, because `HttpResponseException` holds an `HttpResponse` inside.
Result:
- A user can handle exceptions in a generalized way even if any exception is raised from a decorator.
- …
=> Exception handlers handle an exception raised from a decorator

benchmarks/build.gradle, benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/downstream/DownstreamSimpleBenchmark.java, benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/upstream/UpstreamSimpleBenchmark.java, dependencies.yml, retrofit2/build.gradle, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryLargeStreamTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java, site/src/sphinx/client-retrofit.rst
Motivation:
Since Retrofit 2.5, there is no need to use `Java8CallAdapterFactory`
because it's now built-in.
Modifications:
- Remove the references to `Java8CallAdapterFactory`.
- Remove `adapter-java8` from the dependencies.
Result:
- Less cruft
=> Remove the usage of Retrofit `Java8CallAdapterFactory`

core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java, core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpSession.java, core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java, core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
Related: #1206
Motivation:
Armeria HTTP client does not respect `MAX_CONCURRENT_STREAMS` HTTP/2
setting. As a result, it is possible for a user to create more streams
than allowed accidentally, which results it protocol violation.
Modifications:
- Do not reuse an existing HTTP/2 connection but create a new one when
the connection already has many concurrent streams.
- Clean up acquisition logic in `HttpChannelPool`.
Result:
- Fixes #1206
- No more protocol violation
=> Respect MAX_CONCURRENT_STREAMS on the client side

core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java, core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java, core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
It can be useful for RPC implementations, especially gRPC, to be able to specify additional trailers using `ServiceRequestContext`. 
This also updates `additionalResponseHeaders` manipulation to be thread-safe, which I don't think it was before. Compared to the previous implementation, `removeAdditional` always forces creation of headers but I think this is fine given usual usage of the method and makes sure it's thread-safe vs other add operations.
Fixes #1468
=> Allow users to set additional trailers using ServiceRequestContext.

core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java, core/src/main/java/com/linecorp/armeria/client/ClientDecorationBuilder.java, core/src/main/java/com/linecorp/armeria/client/Clients.java, core/src/main/java/com/linecorp/armeria/client/HttpClientBuilder.java, core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClient.java, core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingClient.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java, grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java, retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java, site/src/sphinx/client-custom-http-headers.rst, site/src/sphinx/client-decorator.rst, site/src/sphinx/client-grpc.rst, site/src/sphinx/client-retry.rst, site/src/sphinx/client-thrift.rst, thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java, thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java, thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java, thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpHeaderTest.java, zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java
Motivation:
Practically, there are only 2 ways of adding a client decorator:
- `builder.decorator(HttpRequest.class, HttpResposne.class, ...);`
- `builder.decorator(RpcRequest.class, RpcResponse.class, ...);`
Instead of requiring a user to specify req/res types, we could just
provide two builder methods dedicated to each case.
Modifications:
- Deprecated the old `decorator()` builder methods.
- Added `decorator(Function)` and `decorator(ClientDecoratorFunction)`
which add an HTTP-level decorator.
- Added `rpcDecorator(Function)` and `rpcDecorator(ClientDecoratorFunction)`
which add an RPC-level decorator.
- Removed `HttpClient.decorator()` methods which became unnecessary due
to the new `decorator()` methods in `AbstractClientOptionsBuilder`.
Result:
- Fixes #1482
- Simpler builder API
- …
=> Simplify decorator builder methods

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java, core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpSession.java, core/src/main/java/com/linecorp/armeria/internal/ChannelUtil.java, core/src/main/java/com/linecorp/armeria/internal/InboundTrafficController.java, core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java, core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
Motivation:
`InboundTrafficController` uses a hard-coded water mark value of 128KiB,
which is much smaller than our current initial connection window size
(1MiB).
Modifications:
- Use the water mark values that matches the initial HTTP/2 connection
window size.
- HTTP/1 connections' water mark values stay same.
- Disable Netty `Channel` write buffer water mark to reduce unnecessary
emission of `channelWritabilityChanged` events.
Result:
- Less frequent network read suspension which was unnecessary.
- Less frequent `channelWritabilityChanged` events.
=> Respect HTTP/2 connection window size

core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactory.java, examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/HelloAnnotatedService.java, examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/HelloConfiguration.java, examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/ValidationExceptionHandler.java, examples/spring-boot-webflux/src/test/java/example/springframework/boot/webflux/HelloApplicationIntegrationTest.java
Motivation:
If a user uses Spring and Armeria together, he or she may want to apply Java Bean Validation framework to Armeria annotated HTTP service.
Modifications:
- Use `org.reflections.ReflectionUtils` when getting methods or constructors from a class.
- Check all super classes when getting annotations from a class.
- `ReflectionUtils.getAllAnnotations()` returns a `HashSet` of `Annotations` which does not preserve their specified order.
- Add `HelloAnnotatedService` and related classes to `examples/spring-boo-webflux` in order to show how to use an annotated HTTP service with Spring framework.
Result:
- Closes #1473
=> Support Spring validation on annotated HTTP services

site/src/sphinx/advanced-spring-webflux-integration.rst
Just a simple fix.
Replace
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html/
-> 404
with
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html
=> Fix an inaccessible link on doc

dependencies.yml, tomcat/src/main/java/com/linecorp/armeria/server/tomcat/ConfigFileLoaderInitializer.java, tomcat/src/main/java/com/linecorp/armeria/server/tomcat/ManagedTomcatService.java, tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat90ProtocolHandler.java, tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java, tomcat8.0/build.gradle, tomcat8.5/build.gradle
- Updated Tomcat from 9.0.13 to 9.0.14
- Added `ConfigFileLoaderInitializer` which sets
`ConfigFileLoader.source` property for Tomcat 9+
- Added the methods required to support Tomcat 9.0.14 to `Tomcat90ProtocolHandler`
=> Support Tomcat 9.0.14

core/src/main/java/com/linecorp/armeria/server/misc/Inet4AddressBlock.java, core/src/main/java/com/linecorp/armeria/server/misc/Inet6AddressBlock.java, core/src/main/java/com/linecorp/armeria/server/misc/InetAddressPredicates.java, core/src/main/java/com/linecorp/armeria/server/misc/package-info.java, core/src/test/java/com/linecorp/armeria/server/misc/InetAddressPredicatesTest.java
Motivation:
Once #1467 is merged, we could add a utility class that provides static factory methods that creates `Predicate<InetAddress>` from a CIDR notation, such as `192.168.0.0/24`.
Modifications:
- Add `InetAddressPredicates` which provides static factory methods that return `Predicate<InetAddress>`.
Result:
- Closes #1490
=> Add CIDR based Predicate<InetAddress>

core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java, core/src/test/java/com/linecorp/armeria/client/Http1EmptyRequestTest.java
Motivation:
Although not a protocol violation, Armeria does not send a
`content-length` header when a client sends an empty PUT/POST/PATCH
request, which may confuse some server implementations or users.
Modifications:
- Make sure that an empty PUT/POST/PATCH request always has the
`content-length: 0` header.
Result:
- Fixes #1476
=> Send 'content-length' header for an empty PUT/POST/PATCH request

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceElement.java, core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java, core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtilTest.java
Motivation:
It was unnecessary because we are comparing the original service instance with decorators-applied service instance when deciding to add an exception handling decorator.
Modifications:
- Revert `null` to `Function.identity()` in `AbstractVirtualHostBuilder`.
- Add a test case for `ArmeriaConfigurationUtil#configureAnnotatedHttpServices`. (related to #1497)
=> Revert 'null' to 'Function.identity()' which was fixed by #1478

site/src/sphinx/client-circuit-breaker.rst
`CircuitBreakerStrategy` is not a generic interface anymore
- PR #1418 Changed `CircuitBreakerStrategy` to a non-generic interface.
- But the related document was still using generic
- See: https://github.com/line/armeria/pull/1418/files#diff-d248cc525f658e2c7a7dc11aad417ca3R49
=> Update the outdated site document

core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandler.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Motivation:
`verboseResponse` flag could be controlled programmatically when
creating a `Server` because a user may not want to rely on a system
property.
Modifications:
- Added `verboseResponses` property to `ServerBuilder` and `ServerConfig`
- Removed the stack trace from the `debugData` field of a `GOAWAY` frame
and logged the connection error exceptions explicitly instead for
easier protocol violation diagnosis.
- As a result, `GOAWAY` frame logging does not rely on `verboseResponses`
anymore.
Result:
- Closes #1507
=> Add ServerConfig.verboseResponses()

docs-client/build.gradle, docs-client/package.json, docs-client/src/containers/App/index.tsx, docs-client/src/containers/MethodPage/index.tsx, docs-client/yarn.lock, licenses/web-licenses.txt
Motivation:
When there are many services to show in `DocService`, it's not easy to see the
main content page because when the scroll goes down the main content does not follow.
So if we can collapse the services, it will me much easier to look at the main content.
Modifications:
- Make services collapsible
- Make the `AppDrawer` scrollable
Result:
- Better UI
=> Make services in DocService collapsible

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java, core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpSession.java, core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java, core/src/main/java/com/linecorp/armeria/internal/Http2GoAwayHandler.java, core/src/test/java/com/linecorp/armeria/client/Http1ConnectionCloseHeaderTest.java, core/src/test/java/com/linecorp/armeria/client/Http1EmptyRequestTest.java, core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
Motivation:
It is currently possible to return a connection to the pool even if it's
scheduled for disconnection, e.g. a connection which received a response
with a `connection: close` header or a `GOAWAY` frame.
As a result, it is possible to acquire a connection which will be closed
very soon, causing an unexpected request failure.
Modifications:
- Renamed `HttpSession.isActive()` to `canSendRequest()` to make its
meaning clearer.
- `HttpSession.canSendRequest()` will return `false` if disconnection
has been scheduled, e.g. received a `connection: close` header or
sent/received a `GOAWAY` frame.
- Renamed `HttpResponseDecoder.needsToDisconnect()` to `needsToDisconnectNow()`
for clarity.
- Added `HttpResponseDecoder.needsToDisconnectWhenFinished()`, which is
used to tell if the …
=> Do not return a connection to the pool if it's scheduled for disconnection

CONTRIBUTING.md, README.md
When I tried to build Armeria for the first time, I failed it because I used Java 8. 
As far as I know, It requires Java 10 or later to build, so I added additional description in `README.md`
so that A user doesn't have to be confused. ( Let me know if I am wrong )
I also think that the description for IDE settings for IntelliJ is not enough. so I added it too.
=> Additional description in README.md and CONTRIBUTING.md

core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListenerAdapter.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerListener.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerListenerAdapter.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/MetricCollectingCircuitBreakerListener.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java, core/src/main/java/com/linecorp/armeria/server/ServerListenerAdapter.java, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientTest.java, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/MetricCollectingCircuitBreakerListenerTest.java
Motivation:
The methods in `CircuitBreakerListener` are invoked with the `CircuitBreaker` instance. In our default implementation of `CircuitBreaker` which is `NonBlockingCircuitBreaker`, `canRequest()` calls `CircuitBreakerListener.onRequestRejected()` internally. So if `canRequest()` is called inside `onRequestRejected()`, it makes cycle, so we should prevent it.
Modifications:
- Make all methods in `CircuitBreakerListener` deprecated, and add methods which take the circuit breaker name as an argument.
- Fix flaky test in CircuitBreakerHttpClientTest
- Add CircuitBreakerListenerAdapter
Result:
- Less cycle
- Less flaky
- Fix #1443
=> Prevent cyclic call in CircuitBreakerListener

core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java, core/src/main/java/com/linecorp/armeria/internal/Http2GoAwayHandler.java, core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java, core/src/test/java/com/linecorp/armeria/internal/Http2GoAwayHandlerTest.java
Motivation:
1)
`Exceptions.isExpected(Throwable)` should always return `false` when
`verboseExceptions` flag is set. However, it currently always returns
`true` by coding mistake.
2)
I found a few more exception messages which do not really need to be
logged at high level:
SSLException: SSLEngine closed already
Sent a GOAWAY frame: lastStreamId=..., errorCode=INTERNAL_ERROR(2), debugData="Error flushing"
Both errors can happen when a socket connection has been closed by a
remote peer, which should be treated in a similar manner with
'connection reset by peer' errors.
Modifications:
- Update `Exceptions.isExpected()` to always return `false` when
`verboseExceptions` flag is set.
- Update `Exceptions.isExpected()` to return `true` for
`SSLException: SSLEngine closed already`.
- Update …
=> Less verbose error logging / Fix incorrect behavior when 'verboseExceptions' is set.

core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java, core/src/main/java/com/linecorp/armeria/common/HttpRequest.java, core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java, core/src/main/java/com/linecorp/armeria/server/docs/DocService.java, core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFile.java, core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFileBuilder.java, core/src/main/java/com/linecorp/armeria/server/file/AggregatedHttpFile.java, core/src/main/java/com/linecorp/armeria/server/file/CachingHttpFile.java, core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpFile.java, core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpVfs.java, core/src/main/java/com/linecorp/armeria/server/file/DefaultEntityTagFunction.java, core/src/main/java/com/linecorp/armeria/server/file/FileSystemHttpFile.java, core/src/main/java/com/linecorp/armeria/server/file/FileSystemHttpVfs.java, core/src/main/java/com/linecorp/armeria/server/file/HttpDataFile.java, core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java, core/src/main/java/com/linecorp/armeria/server/file/HttpFileAttributes.java, core/src/main/java/com/linecorp/armeria/server/file/HttpFileBuilder.java, core/src/main/java/com/linecorp/armeria/server/file/HttpFileService.java, core/src/main/java/com/linecorp/armeria/server/file/HttpVfs.java, core/src/main/java/com/linecorp/armeria/server/file/MimeTypeUtil.java, core/src/main/java/com/linecorp/armeria/server/file/NonExistentHttpFile.java, core/src/main/java/com/linecorp/armeria/server/file/StreamingHttpFile.java, core/src/test/java/com/linecorp/armeria/server/file/CachingHttpFileTest.java, core/src/test/java/com/linecorp/armeria/server/file/DefaultEntityTagFunctionTest.java, core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java, core/src/test/java/com/linecorp/armeria/server/file/MimeTypeUtilTest.java, site/src/sphinx/server-annotated-service.rst, site/src/sphinx/server-http-file.rst
Related: #1397
Motivation:
We have `HttpFileService` but its usage is limited to serving static
files under a specific path. A user may want to serve an arbitrary
static file whose path is not necessarily mapped to request URI, e.g.
'Serve `index.html` for all requests under `/my_react_app/`.'
Modifications:
- Added `HttpFile`, `AggregatedHttpFile`, `HttpFileBuilder` and their
related subtypes.
- (Breaking change) Changed the signature of `HttpVfs.get()`.
- (Breaking change) Replaced the usage of `HttpVfs.Entry` with `HttpFile`.
- Moved most logic of `HttpFileService` to `HttpFile` implementations.
- `if-none-match` header is now supported.
- Updated `HttpFileServiceTest` to test both cached and uncached
scenarious completely.
- Updated the web page about static file serving.
- …
=> Provide a way to stream an individual file

core/src/main/java/com/linecorp/armeria/client/ClosedClientFactoryException.java, core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java, core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java, thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Motivation:
Previously at #1236, we added `ClosedClientFactoryException` which is
raised when a request in progress by `RetryingClient` is cancelled due
to the termination of `ClientFactory`. I see two issues here:
- Defining a new exception type for such an exceptional cause has
dubious value. It is hard to expect for a user to catch
`ClosedClientFactoryException` and handle it.
- Due to inevitable race conditions, we are already raising
`IllegalStateException` in some places, such as the connection pool.
Indeed, `IllegalStateException` with a message is a better choice
here.
Modifications:
- Deprecated `ClosedClientFactoryException` and used `IllegalStateException`.
- Made `ClosedClientFactoryException` extend `IllegalStateException`.
- Updates the test cases.
Result:
- Less flakiness
- …
=> Deprecate `ClosedClientFactoryException` and use `IllegalStateException`

core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerListener.java, core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java, core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
Motivation
I made the methods in `CircuitBreakerListener` deprecated and add methods whose first parameter
is the `circuitBreakerName` to prevent another breaking change.
But it was not a good idea because I had to add new methods in `CircuitBreakerListener` so I cannot
avoid making breaking change anyway.
Modification
- Remove the deprecated methods
Result
- Neat APIs
=> Remove deprecated methods in CircuitBreakerListener

spring/boot-autoconfigure/build.gradle, spring/boot-webflux-autoconfigure/build.gradle, spring/boot1-autoconfigure/build.gradle
Currently, users either need to provide `hibernate-validator` or exclude `javax.validation` when using `armeria-spring` because spring boot checks for the presence of the latter on the classpath and then requires something like the former. I think most users will have the dependencies if they want validation automatically without armeria enforcing it as a required dependency. Of course, exclusion is always an option too so maybe it's not a big deal. Thoughts?
Came up in https://github.com/openzipkin/zipkin/pull/2348
=> Make javax.validation compileOnly

grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
Bytecode generation can take a while during initialization and is pointless if it won't be needed. Client already had this check.
Fixes #1556
=> Only initialize json marshaller when needed.

NOTICE.txt, core/build.gradle, core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java, core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java, core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceAnnotationAliasTest.java, core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java, core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotationUtilTest.java, dependencies.yml, licenses/LICENSE.cglib.al20.txt
Motivation:
A user may want to define his or her annotations as a custom annotation in order to apply the custom annotation to his or her annotated HTTP services. e.g:
```
// Define a custom annotation:
@ProducesJson
@LoggingDecorator
@interface MyApiSpecification {}
// Apply it to the annotated HTTP service:
@Get("/api")
@MyApiSpecification
public Something getSomething() {}
```
Modifications:
- Add `AnnotationUtil` for finding a specific annotation or getting all annotations from an `AnnotatedElement`.
- Use `AnnotationUtil` instead of `ReflectionUtils.getAllAnnotations()`. The old one does not respect the order of the annotations because its return type is a `Set<Annotation>` (more specifically it's `HashSet`).
Result:
- Won't depend on the `ReflectionUtils`'s implementation when …
=> Support an alias for a bunch of annotations

core/src/main/java/com/linecorp/armeria/common/AggregatedHttpMessage.java, core/src/main/java/com/linecorp/armeria/common/HttpResponse.java, core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java, core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java, core/src/main/java/com/linecorp/armeria/internal/Http2ObjectEncoder.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java, core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpMessageTest.java, core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java, core/src/test/java/com/linecorp/armeria/internal/DefaultHttpResponseTest.java, core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java, core/src/test/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunctionTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java
Motivations:
Some of the client implementations such as `curl` ignores trailing headers if the `Content-length` header is present.
We should not set `Content-length` header when trailing headers exists so that those clients can receive the trailing headers.
Modification:
- Do not set `Content-length` header when trailing headers exists
- Make a backlist which must not be included in trailing headers
- https://tools.ietf.org/html/rfc7230#section-4.1.2
- Allow `Trailer` headers in response headers which was not before
- Set `Content-length` to `0` when the `HttpResponse` contains only a status so that the response is not transfer encoding
Result:
- Closes #1554
=> Do not set Content-length header when trailing headers exists

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedBeanFactory.java, core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedBeanFactoryRegistry.java, core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServicePlugin.java, core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedValueResolver.java, core/src/main/java/com/linecorp/armeria/server/docs/DocService.java, core/src/main/java/com/linecorp/armeria/server/docs/EndpointInfoBuilder.java, core/src/main/java/com/linecorp/armeria/server/docs/FieldInfo.java, core/src/main/java/com/linecorp/armeria/server/docs/FieldInfoBuilder.java, core/src/main/java/com/linecorp/armeria/server/docs/FieldLocation.java, core/src/main/java/com/linecorp/armeria/server/docs/FieldRequirement.java, core/src/main/java/com/linecorp/armeria/server/docs/TypeSignature.java, core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedBeanFactoryRegistryTest.java, core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServicePluginTest.java, core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServiceTest.java, docs-client/src/components/VariableList/index.tsx, docs-client/src/containers/MethodPage/index.tsx, docs-client/src/lib/specification.tsx, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocServicePlugin.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServicePluginTest.java, thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftDocServicePlugin.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServicePluginTest.java
Motivation:
Currently, `RequestObject`s are not shown in `DocService`.
Modifications:
- Rename `AnnotatedBeanFactory` to `AnnotatedBeanFactoryRegistry`
- Add `AnnotatedBeanFactory` which has information about the bean factory
- Add `EndpointInfoBuilder` to make it `EndpointInfo` easily
- Add `FieldLocation` enum
Result:
- Better developer experience
=> Support RequestObject in DocService

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java, core/src/main/java/com/linecorp/armeria/server/annotation/Order.java, core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverters.java, core/src/main/java/com/linecorp/armeria/server/annotation/StatusCode.java, core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceAnnotationAliasTest.java, core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotationUtilTest.java
Motivation:
Follow-up work after #1560.
Modifications:
- `AnnotationUtil` will lookup meta-annotations of a meta-annotation to support the following case:
```
@ProducesJson
@Produces("text/plain")
@interface MyPostServiceSpecifications {}
```
- `@ProducesJson` will also be found with this PR, which wasn't found before.
- Add `ElementType.ANNOTATION_TYPE` to `Target` annotation for `@Order` and `@StatusCode` so that a user can use them as a meta-annotation for his or her custom annotation.
=> Improve AnnotationUtil

dependencies.yml, spring/boot-autoconfigure/build.gradle, spring/boot-webflux-autoconfigure/build.gradle
Motivations:
- Sometimes spring-boot-actuator pulls unrelated metrics to MeterRegistry. For example, if a user add `armeria-spring-boot-starter` dependency to an application, because it also pulls spring-boot-actuator dependency, [KafkaMetricsAutoConfiguration](https://docs.spring.io/spring-boot/docs/2.2.0.BUILD-SNAPSHOT/api/org/springframework/boot/actuate/autoconfigure/metrics/KafkaMetricsAutoConfiguration.html) is enabled if kafka client bean is existed. And it causes unintentional conflicts with user metrics configurations. 
Changes:
- Remove spring-boot-starter-actuator dependency from spring-boot modules
Result:
- Less surprise
=> Remove spring-boot-starter-actuator dependency from spring-boot modules

core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java, spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpHandlerAdapter.java, tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Motivation:
It is sometimes hard for a client to know why a request is bad.
Modifications:
- Added short error messages to 400 Bad Request responses
- Used `ProtocolViolationException` instead of `IllegalArgumentException` for bad requests.
- Removed unnecessary validation of HTTP method in `HttpServerHandler`.
- Cleaned up response generation in `HttpServerHandler`.
Result:
- User friendliness.
=> Tell why a request is bad for a 400 Bad Request response

core/src/main/java/com/linecorp/armeria/common/Flags.java, core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java, core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java
Motivation:
Since we fixed the behavior of `verboseExceptions` flag with respect to
`Exceptions.isExpected()`, we received the report of increased
exceptions logged. However, most of them were harmless socket-related
ones such as `connection reset by peer`, where we do not have control
over, because network disconnection can always happen.
Modifications:
- Added a new flag `verboseSocketException` which defaults to `false`.
- Modified `Exceptions.isExpected()` to use `verboseSocketException`
instead of `verboseException`.
Result:
- Less noisy log messages
=> Add `verboseSocketExceptions` flag

dependencies.yml, settings.gradle, spring/boot-actuator-autoconfigure/build.gradle, spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java, spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationHttpService.java, spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/package-info.java, spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java, spring/boot-actuator-autoconfigure/src/test/resources/application-autoConfTest.yml, spring/boot-actuator-starter/build.gradle
Ever since spring-boot 2.0, actuator is abstracted on top of generic web operations and can be implemented directly in armeria, so servers can serve actuator without needing Tomcat, etc.
Much of this code is taken from https://github.com/openzipkin/zipkin/pull/2348/files#diff-9b461e029eeefaccd44534eb0d550ae2R124
Still need to add more tests and possibly handle some corner cases (trying to understand what `TolerantPathMapping` in that zipkin PR is for). But sending out for now.
=> Implement spring-boot actuator with armeria.

core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java, core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java, core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java, core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java, core/src/main/java/com/linecorp/armeria/internal/logging/LoggingDecorators.java, core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java, core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java, core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Motivation:
A user wants to sanitize the stack trace of `RequestLog.responseCause()`
or avoid logging the stack trace completely.
Modifications:
- Added LoggingDecoratorBuilder.responseCauseSanitizer()` and applied
the specified `Function` to the response cause.
- Widened the type parameters of sanitizer functions.
- Fixed a bug where a response content sanitizer is applied on request
content on a certain case.
- Added `contentSanitizer()` and `headersSanitizer()` shortcut methods.
- Javadoc clean-up
Result:
- A user can sanitize/drop the stack trace of `RequestLog.responseCause()`.
- Request content is always sanitized with an intended sanitizer.
- More shortcut methods in `LoggingClientBuilder` and `LoggingServiceBuilder`.
=> Add `responseCauseSanitizer` to `LoggingDecoratorBuilder`

spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpClientResponseSubscriber.java, spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Motivation:
As we discovered in #1440, `whenComplete()` is harmful for performance.
Modifications:
- Use `handle()` instead of `whenComplete()`
Result:
- Potentially less unnecessary instantiation of `CompletionException`.
=> Avoid using `whenComplete()`; use `handle()`

settings/checkstyle/checkstyle.xml
Motivation:
IntelliJ inserts unnecessary space between semicolons in `for (;;)`
making the `for` sentence look weird when reformatting or re-indenting:
for (; ;) { ... }
.. and I'm tired of adding comments for this kind of aesthetical issue.
Modifications:
- Add a Checkstyle rule that prohibits spaces in `for (;;)`
Result:
- Automation
=> Add a Checkstyle rule that prohibits spaces in `for (;;)`

grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframer.java, grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframerTest.java, grpc/src/test/java/com/linecorp/armeria/internal/grpc/HttpStreamReaderTest.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Fixes #1524 hopefully doesn't break other things though ><
I was expecting this to just be running callbacks in order, but it turned out also needing to rework many aspects of deframing to allow the deframing and business logic to happen on separate threads. It seems like upstream also has added similar logic after our fork of the class, though the context seems to be moving deframing off the transport thread which confuses me since I would expect the ordering issue to happen when it is _on_ the transport thread. Oh well, didn't dig deeper on that.
https://github.com/grpc/grpc-java/pull/3145
Now, when the HTTP reader is finished, the business logic listener is not notified right away, but only if all messages have first been delivered. Previously, the ordering worked out that this was …
=> Execute blocking gRPC callbacks in order

core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
Motivation:
Server might leave a log message like the following when a client
disconnects prematurely during TLS handshake:
TLS handshake failed:
java.nio.channels.ClosedChannelException: null
at io.netty.handler.ssl.SslHandler.channelInactive(...)
.. which pollutes the server log file.
Modifications:
- Guarded the TLS handshake failure logging code with
`!Exceptions.isExpected()`.
Result:
- Less noise
=> Less noisy TLS handshake error logging

site/src/sphinx/client-custom-http-headers.rst, site/src/sphinx/client-timeouts.rst, site/src/sphinx/client.rst
Slightly related to #723, this PR describes how the default client timeouts can be overridden.
(This wasn't obvious to me at first, so adding this in the hope that it helps others. Note that the `ClientBuilder` class can also be used to tweak this; it's not 100% clear to me when to use that one and when to go with the `Clients.newClient` method.)
=> [docs] Add info about client timeouts

dependencies.yml, grpc/build.gradle, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java, grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java, site/src/sphinx/server-grpc.rst
I was originally thinking of forking `ProtoReflectionService` from upstream, but realized it's not hard to just use it as is. This implementation is quite similar to upstream which essentially runs custom logic based on an `instanceof` check.
https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java#L111
Fixes #1621
=> Add support for ProtoReflectionService.

site/src/sphinx/client-grpc.rst, site/src/sphinx/client-timeouts.rst, site/src/sphinx/client.rst
- Reordered the existing sections so that the example that uses
`ClientBuilder` comes first, because its used more commonly.
- Added a section about the system properties
- Added a section about adjusting idle connection timeout
programmatically
=> Add more information about client timeouts

core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java, core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/test/java/com/linecorp/armeria/server/DecodedHttpRequestTest.java, core/src/test/java/com/linecorp/armeria/server/HttpResponseSubscriberTest.java
Motivation:
The HTTP response content is released after writing the socket in `ChannelOutboundBuffer`.
If we want to log the content, we should do it before we write it to the socket.
Modifications:
- Call `increase(Response|Request)Length` before writing to channel.
Result:
- Fewer bugs.
=> Fix a bug where ByteBuf is released before storing it for content preview

site/src/sphinx/server-access-log.rst, site/src/sphinx/server-basics.rst
Modifications:
- Add a link to `Getting an IP address of a client who initiated a request` section in `server-basic.rst`.
=> Explain how to get the address corresponding to '%a' token of access log

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java, core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotationUtilTest.java
Motivation:
There is no cyclic reference detection implemented in `AnnotationUtil`,
which means an annotation like the following can trigger a
`StackOverflowError`:
@Cyclic
@Retention(RUNTIME)
@interface Cyclic {}
This was not a problem before because we blacklisted well known JDK
classes that has cyclic references, but it does not work for other
classes.
Modifications:
- Added cyclic dependency detection in the traversal logic.
- Added a thread-local blacklist of the annotation types with cyclic
dependencies.
Result:
- Annotation scanning is faster.
- Annotation scanning does not trigger a `StackOverflowException`.
- Fixes #1632
- Fixes #1633
/cc @iEAmi @tobias-
=> Reduce the search space of AnnotationUtil.getAnnotations() and find()

examples/spring-boot-minimal/build.gradle, examples/spring-boot-tomcat/build.gradle, examples/spring-boot-webflux/build.gradle, spring/boot-actuator-autoconfigure/build.gradle, spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java, spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationHttpService.java, spring/boot-actuator-autoconfigure/src/main/resources/META-INF/spring.factories, spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java, spring/boot-actuator-starter/build.gradle
Motivation:
Spring Actuator responses are not always JSON. It can be a plaintext or
even an octet stream.
Modifications:
- Respect the negotiated media type.
- Added support for a plaintext response represented as a `CharSequence`.
- Added support for a binary response represented as a `Resource`.
- `msg` -> `req` or `res`
- Added `final` wherever applicable.
- Added missing `spring.factories` to `armeria-spring-boot-actuator-autoconfigure`.
- Made all Spring Boot examples use our actuator implementation.
- Fixed a packaging issue which made more than one `Server` 
instantiated. (The fix originally written by @hyangtack)
Result:
- Fixes #1637
- A user can also retrieve the heap dump via the Actuator service.
- A user does not need to import …
=> Support non-JSON Spring Actuator responses

site/src/sphinx/_templates/layout.html, site/src/sphinx/advanced-saml.rst, site/src/sphinx/advanced-spring-webflux-integration.rst, site/src/sphinx/server-annotated-service.rst, site/src/sphinx/server-grpc.rst, site/src/sphinx/setup.rst
.. because `thrift`, `gradle`, `protobuf` are not included in the common
languages.
=> Add more languages to Highlight.js

core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerBuilder.java, site/src/sphinx/client-circuit-breaker.rst
Motivation:
The default failure rate threshold of a circuit breaker is written
inconsistently between documentation (0.2) and implementation (0.8).
Modifications:
- Use consistent default value - 0.5.
Result:
- Fixes documentation error.
- (Breaking) Uses more widely adopted default failure rate threshold.
=> Set 0.5 to the default failure rate threshold of a circuit breaker

core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, core/src/main/java/com/linecorp/armeria/common/util/SystemInfo.java, core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java, core/src/test/java/com/linecorp/armeria/common/util/SystemInfoTest.java
Motivation:
It'd be nice for Armeria to provide a reliable way to retrieve the
system information that requires some hack depending on OS and Java
version, such as:
- Java version
- local hostname
- current PID
- microsecond-precision time
Modifications:
- Added `SystemInfo` which provides the information mentioned in the
'Motivation' section.
Result:
- Convenience.
=> Add `SystemInfo` utility class which provides the system information

core/src/main/java/com/linecorp/armeria/client/ClientOptions.java, core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java, core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java, core/src/main/java/com/linecorp/armeria/common/HttpMethod.java, core/src/main/java/com/linecorp/armeria/common/HttpStatusClass.java, core/src/main/java/com/linecorp/armeria/common/MediaType.java, core/src/main/java/com/linecorp/armeria/common/StringValueConverter.java, core/src/main/java/com/linecorp/armeria/common/util/Version.java, core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java, core/src/main/java/com/linecorp/armeria/internal/DefaultAttributeMap.java, core/src/main/java/com/linecorp/armeria/internal/Http1ClientCodec.java, core/src/main/java/com/linecorp/armeria/internal/logging/CountingSampler.java, core/src/main/java/com/linecorp/armeria/internal/logging/Sampler.java, core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java, core/src/test/java/com/linecorp/armeria/common/MediaTypeTest.java, core/src/test/java/com/linecorp/armeria/internal/DefaultAttributeMapTest.java, dependencies.yml, spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/DefaultSslInfo.java
- Dependencies
- java-jwt 3.7.0 -> 3.8.0
- Guava 27.0.1 -> 27.1
- Netty 4.1.33 -> 4.1.34
- Netty TCNative BoringSSL 2.0.20 -> 2.0.22
- Brave 5.6.1 -> 5.6.3
- Build:
- json-unit 2.4.0 -> 2.5.0
- AssertJ 3.12.1 -> 3.12.2
- Mockito 2.25.0 -> 2.25.1
- Forks:
- Updated `MediaType`
- Updated `DefaultSslInfo`
- Updated `StringValueConverter`
- Updated `Sampler` and `CountingSampler`
- `HttpHeaderNames` now forks from Guava's `HttpHeaders` instead of
Netty's `HttpHeaderNames` because it has more recent HTTP headers
which may be useful to service authors.
- (Breaking) Some header names were removed, although it is very
unlikely to be used by users:
- `Keep-Alive`
- `Proxy-Connection`
- `Content-Transfer-Encoding`
- `ClientOptions` now prohibits `HTTP2-Settings` header as well.
=> Update dependencies and forks

core/src/main/java/com/linecorp/armeria/server/file/HttpFileBuilder.java, core/src/test/java/com/linecorp/armeria/server/file/HttpFileTest.java
Motivation:
Unlike `ClassPathHttpVfs.get()`, `HttpFile.ofResource()` does not strip
a leading slash in a given path.
Modifications:
- Strip a leading slash in `HttpFileBuilder.ofResource()`
Result:
- Fixes #1650.
=> Strip a leading slash in an `HttpFile` resource path

spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java, spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java, spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ByteBufLeakTest.java
Motivation:
`ArmeriaServerHttpResponse`, especially its super class, `AbstractServerHttpResponse`, uses `ChannelSendOperator#WriteBarrier` when writing a response.
The `WriteBarrier` internally caches the first published object, but it does nothing when the cached object is discarded, which might cause `ByteBuf` leak.
Modifications:
- Do not inherit `AbstractServerHttpResponse` anymore, which causes mis-ordering of invoking `onNext` of `PublisherBasedHttpResponse`.
- Add `HttpResponseProcessor` between `PublisherBasedHttpResponse` and the content publisher.
- It always requests one element to the publisher when subscribing, and then caches the first published object.
- When a Spring controller returns `Mono`, it always received `request(unbounded)` signal internally, so we need to have a …
=> Fix ByteBuf leak from Spring WebFlux integration

benchmarks/src/jmh/java/com/linecorp/armeria/shared/EventLoopJmhExecutor.java, core/src/main/java/com/linecorp/armeria/common/CommonPools.java, core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java, core/src/main/java/com/linecorp/armeria/common/util/EventLoopThread.java, core/src/main/java/com/linecorp/armeria/common/util/EventLoopThreadFactory.java, core/src/main/java/reactor/core/scheduler/NonBlocking.java, core/src/main/java/reactor/core/scheduler/package-info.java, core/src/test/java/com/linecorp/armeria/server/GracefulShutdownSupportTest.java, core/src/test/java/com/linecorp/armeria/server/ServerTest.java, site/build.gradle
Motivation:
Project Reactor determines whether a thread is non-blocking or not by
checking if the thread implements a special tag interface `NonBlocking`.
Because our event loop threads do not implement it, Project Reactor's
`Schedulers.isInNonBlockingThread()` will return `false`.
Modification:
- Added `reactor.core.scheduler.NonBlocking` interface to `armeria-core`.
- Added `EventLoopThreadFactory` that creates an `EventLoopThread`.
- Added `EventLoopThread` which implements `NonBlocking`.
- Updated the existing code to use `EventLoopThreadFactory` instead of
`DefaultThreadFactory` wherever possible.
Result:
- Project Reactor and its users are happy.
- We are a little bit unhappy due to ugliness of the fix.
=> Create event-loop threads that make Project Reactor happy.

core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
Motivation:
We removed `HttpHeaderNames.PREFER` by mistake at
35c8b7914ee2335b6400b178dcab5a33203ef0d9.
Modification:
- Add `HttpHeaderNames.PREFER` back.
Result:
- A past mistake is undone.
- Fixes #1664
=> Add HttpHeaderNames.PREFER back

site/src/sphinx/client-grpc.rst, site/src/sphinx/server-grpc.rst
Motivation:
We missed the links when adding a gRPC example.
=> Add a link to armeria-examples repository in gRPC documents

build.gradle, site/build.gradle
Motivations:
I mistakenly added `reactor.core.scheduler` to the Javadoc blacklist. It
has to be added to the exclusion list.
Modifications:
- Remove `reactor.core.scheduler` from the Javadoc blacklist and add it
to the exclusion list.
=> Fix incorrect Javadoc exclusion and blacklisting

core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java, core/src/main/java/com/linecorp/armeria/server/Server.java, core/src/test/java/com/linecorp/armeria/common/util/StartStopSupportTest.java
Motivation:
A user sometimes wants to pass an argument when starting or stopping
something.
Modifications:
- Added two more type parameters to `StartStopSupport`.
- Added `StartStopSupport.start(arg, failIfStarted)`
- Added `StartStopSupport.stop(arg)`
- Modified the parameters of `StartStop.doStart()`, `doStop()` and
listener notification methods.
Result:
- A user can pass a startup/shutdown argument when using
`StartStopSupport`.
- `StartStopSupport` has breaking changes.
=> Add start/stop parameters to StartStopSupport

NOTICE.txt, spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java, spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java, spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/Ssl.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaMeterBindersConfigurationTest.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaOkServiceConfiguration.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSslConfigurationTest.java, spring/boot-autoconfigure/src/test/resources/config/application-sslTest.yml, spring/boot-webflux-autoconfigure/build.gradle, spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Changes:
- Fork Spring's Ssl to support both spring-boot1, spring-boot2.
- Move TLS configuration setup to boot-autoconfigure to allow to setup TLS at non-reactive servers
Results:
- Cloeses #1659 
TODO:
=> Add TLS configuration support to spring-autoconfigure

core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java, core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java, core/src/test/java/com/linecorp/armeria/client/HttpResponseDecoderTest.java
Motivation:
There's chance to close `HttpResponseWrapper` on an event loop which is different from the channel event loop.
It is definitely not intended action, and it can cause `IllegalReferenceCountException` due to double-free if a user configured a content previewer.
Modifications:
- Used channel event loop when closing the `HttpResponseWrapper`.
Result:
- No more `IllegalReferenceCountException`.
=> Ensure to close HttpResponseWrapper on the channel event loop

core/src/main/java/com/linecorp/armeria/client/InvalidResponseException.java, core/src/main/java/com/linecorp/armeria/client/InvalidResponseHeadersException.java, thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java, thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
Motivation:
When a Thrift client throws an `InvalidResponseException`, a user need
to know the details about the response, such as HTTP status code.
Modifications:
- Added `InvalidResponseHeadersException` which extends
`InvalidResponseException`
- Throw `InvalidResponseHeadersException` instead of
`InvalidResponseException` where possible.
Result:
A user have enough information to determine the status of a Thrift
endpoint.
=> Add InvalidResponseHeadersException

core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java, core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java, core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsQuestionWithoutTrailingDot.java, core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java, core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroup.java
Motivation:
When using `Dns*EndpointGroup` in a system with search domains in
`/etc/resolv.conf`, the resolver should try all search domains until the
host name is resolved.
However, it treats the specified host name as a full domain name by
appending a dot (.) to the specified host name.
Modifications:
- Introduce a new `DnsQuestion` implementation called
`DnsQuestionWithoutTrailingDot` which does not append a dot at the end
of the host name.
Result:
- `Dns*EndpointGroup` respects the search domains in `/etc/resolv.conf`.
- Fixes #1694
=> Fix a bug where `DnsEndpointGroup` does not respect search domains

core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java, core/src/main/java/com/linecorp/armeria/server/CatchAllPathMapping.java, core/src/main/java/com/linecorp/armeria/server/DefaultPathMapping.java, core/src/main/java/com/linecorp/armeria/server/ExactPathMapping.java, core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java, core/src/main/java/com/linecorp/armeria/server/HttpHeaderPathMapping.java, core/src/main/java/com/linecorp/armeria/server/PathMapping.java, core/src/main/java/com/linecorp/armeria/server/PrefixPathMapping.java, core/src/main/java/com/linecorp/armeria/server/RegexPathMapping.java, core/src/main/java/com/linecorp/armeria/server/annotation/decorator/CorsDecorator.java, core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java, core/src/main/java/com/linecorp/armeria/server/cors/ChainedCorsPolicyBuilder.java, core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java, core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java, core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java, core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java, core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java, site/src/sphinx/server-cors.rst
Motivation:
Currently, there is no way to apply a CORS policy to the specific paths. So it is hard for a user to configure different policies for different paths when the `Origin` domains are the same.
`@CorsDecorator` can handle this kind of situation because it can be specified on each methods in an annotated service, but using the annotation will be worked only if a user knows what origins are allowed at the compile time, which means that it's not suitable for configuring the origins dynamically. Also, it's only for the annotated services.
If the `CorsPolicy` has a `PathMapping` property, `CorsService` will be able to find a policy by using an `Origin` header value and the request path. Therefore, a user can apply CORS policies for different paths more convenient way.
Modifications:
- …
=> Make CORS policy to be applied to the specific paths

zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java, zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java
In most cases, address can not be used in place of service name.
The namespace of service name is polluted.
If `remoteEndpoint.serviceName` is not set, it should not be set to span.
Related PR: #835 #1235
=> Don't use address for service name

core/src/main/java/com/linecorp/armeria/client/ClientConnectionTimings.java, core/src/main/java/com/linecorp/armeria/client/ClientConnectionTimingsBuilder.java, core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java, core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java, core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java, core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java, core/src/main/java/com/linecorp/armeria/common/util/TextFormatter.java, core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java, core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLog.java, core/src/test/java/com/linecorp/armeria/client/ClientConnectionTimingsTest.java, core/src/test/java/com/linecorp/armeria/client/HttpClientWithRequestLogTest.java, core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java, core/src/test/java/com/linecorp/armeria/common/util/TextFormatterTest.java, core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java, logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java, site/src/sphinx/advanced-custom-attributes.rst, site/src/sphinx/advanced-logging.rst, site/src/sphinx/advanced-structured-logging.rst, site/src/sphinx/advanced-unit-testing.rst, site/src/sphinx/advanced.rst, site/src/sphinx/client-decorator.rst, site/src/sphinx/server-decorator.rst, thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftStructuredLog.java
Motivation:
Currently, there's no way to get the duration for getting a connection. If you use HTTP/2,
getting the duration might be useless because, most of the time, you will share just one connection which was established beforehand. (So the duration is very short.) If you use HTTP/1.1, however,
you might need the value due to the nature of HTTP/1.1 which sends just one request at a time. (You need as many connections as you send requests concurrently.)
Modifications:
- Make `RequestLog` extends `AttributeMap` so that you can easily get the attributes from the log.
- Add `ClientConnectionTimings` and it's builder which has the timing information about a connection attempt. The timings are the start time and duration of:
- `connectionAcquisition`
- `dnsResolution`
- `socketConnect`
- …
=> Provide a way to get the duration that was taken to get a connection

spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java, spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaCompressionConfigurationTest.java, spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSslConfigurationTest.java, spring/boot-autoconfigure/src/test/resources/config/application-compressionTest.yml, spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Motivation:
Currently, Spring framework provides `server.compression` property to configure HTTP content encoding,
but `ArmeriaSettings` doesn't provide it. So a user cannot configure it without fixing their code.
Modifications:
- Added `Compression` class to `ArmeriaSettings`, which is similar to the Spring's one.
- We could not reuse the Spring's class because we need to support Spring Boot 1.x and 2.x.
- Moved `ArmeriaReactiveWebServerFactory#contentEncodingDecorator` to `ArmeriaConfigurationUtil` for sharing the method with `spring-boot-autoconfigure`.
Result:
- A user can configure HTTP content encoding with a Spring property file.
=> Add HTTP content encoding property to ArmeriaSettings

core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java, core/src/main/java/com/linecorp/armeria/server/healthcheck/SettableHealthChecker.java, core/src/test/java/com/linecorp/armeria/server/healthcheck/SettableHealthCheckerTest.java
Currently, it can sometimes be inconvenient that a `SettableHealthChecker` can't have `setHealthy` called fluently. This is mainly because the default is `false` though - it might be good to consider whether the default should be `true`, in which case this change becomes less useful.
=> Allow SettableHealthChecker to have chained invocation.

core/src/main/java/com/linecorp/armeria/server/RedirectService.java, core/src/test/java/com/linecorp/armeria/server/RedirectServiceTest.java
Motivation:
When redirecting, a user would want to preserve the query string in the
original request URI, by appending it to the end of the new location.
Modifications:
- Make `RedirectService` preserve the query string by default.
- Note: the query string is not appended if the new location already
contains a query string.
- Add `preserveQueryString` parameter to the constructors of
`RedirectService` so that a user can go back to the old behavior.
- Update the class documentation of `RedirectService`.
Result:
- Fixes #1725
- Less surprising behavior.
=> Make `RedirectService` preserve the query string by default

thrift/src/main/java/com/linecorp/armeria/internal/thrift/ThriftFunction.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
fixes https://github.com/line/armeria/issues/1728 ?
Was able to test this locally and confirm that it works.
=> Use `Class.getDeclaredField()` instead of `getField()` when fetching Thrift metadata.

core/src/main/java/com/linecorp/armeria/server/InterminableExecutorService.java, core/src/main/java/com/linecorp/armeria/server/Server.java, core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java, core/src/main/java/com/linecorp/armeria/server/ServerConfig.java, core/src/test/java/com/linecorp/armeria/server/ServerTest.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Hi :)
I added `ServerBuilder.blockingTaskExecutor(Executor, boolean[shutdownOnStop])`, but I don't know how to using `shutdownOnStop`.
Modifications:
- Deprecate `ServerBuilder.blockingTaskExecutor(Executor)`
- Add `ServerBuilder.blockingTaskExecutor(Executor, boolean[shutdownOnStop])`
Result:
- Fix #1685
\- This is my first PR at Armenia that might be insufficient, Please advise the insufficient part.
=> Add `boolean shutdownOnStop` parameter to `ServerBuilder.blockingTaskExecutor()`

core/src/main/java/com/linecorp/armeria/internal/Types.java, thrift/src/main/java/com/linecorp/armeria/internal/thrift/ThriftServiceMetadata.java, thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java, thrift/src/test/thrift/RpcDebugTest.thrift, thrift0.11/src/test/thrift/RpcDebugTest.thrift, thrift0.9/src/test/thrift/RpcDebugTest.thrift
Motivation:
When a Thrift service inherits from another service, armeria incorrectly sees the inherited methods as duplicated.
Modifications:
* Accept multiple declarations of the same method, making sure to always take the most specific declaration
Example error:
```
Exception in thread "main" java.lang.IllegalArgumentException: duplicate Thrift method name: cancel
at com.linecorp.armeria.internal.thrift.ThriftServiceMetadata.checkDuplicateMethodName(ThriftServiceMetadata.java:196)
at com.linecorp.armeria.internal.thrift.ThriftServiceMetadata.registerFunction(ThriftServiceMetadata.java:177)
at com.linecorp.armeria.internal.thrift.ThriftServiceMetadata.lambda$init$1(ThriftServiceMetadata.java:94)
at java.util.HashMap.forEach(HashMap.java:1289)
at …
```
=> allow for repeated method declarations

core/src/main/java/com/linecorp/armeria/server/cors/CorsDecoratorFactoryFunction.java, core/src/main/java/com/linecorp/armeria/server/cors/CorsDecoratorsFactoryFunction.java, core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java, core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
Motivation:
Currently, the decorator function returned by
`CorsServiceBuilder.newDecorator()` does not perform any decoration at
all when a given `Service` is decorated with a `CorsService` already.
This is a confusing behavior which throws user's configuration
unexpectedly.
Modifications:
- Make `CorsServiceBuilder.build()` reject double decoration.
- Move the logic that ignores the CORS policy at a higher level to
`CorsDecorator(s)FactoryFunction`.
Result:
- Less surprising behavior.
=> Prevent double `CorsService` decoration

core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java, core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java
Motivation:
- #1735 made `DefaultPathMapping` generate a correct path pattern with a trailing slash,
but the `RoutingTrie` hasn't still handled the trailing slash correctly.
Modifications:
- Made `RoutingTrie` handle the trailing slash correctly.
Result:
- A service can be correctly mapped to the path with a trailing slash.
=> `RoutingTrie` can now handle a trailing slash correctly

dependencies.yml, site/src/sphinx/_static/add_badges.js, site/src/sphinx/_static/center_page.js, site/src/sphinx/_static/overrides.css, site/src/sphinx/_templates/layout.html, site/src/sphinx/conf.py, site/src/sphinx/index.rst, site/src/sphinx/setup.rst
Motivation:
It's always better looking nicer.
Modifications:
- Typography
- Increased the overall font size and line height a little bit for
readability.
- Changed the heading font from Source Sans Pro to Merriweather
because it is more distinguished from body text.
- Changed the body font from Source Sans Pro to Lato because Source
Sans Pro is relatively smaller and denser than other sans-serif
fonts, making the CSS customization harder.
- Lato is the default font used by the Sphinx theme we are using,
which means one less thing to worry.
- Changed the monospace font from Inconsolata to Hack because:
- Inconsolata looks thin when paired with Lato.
- Hack is my favorite font. :-)
- Layout
- Increased the width of the content pane from 800px to 960px.
- Made the content pane resizable by …
=> Improve the overall look of the web site

grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaStatusException.java, grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java, grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClientTest.java
Fixes #1703 
This is the client version of #1727. Advanced users can use `UnaryGrpcClient` to issue gRPC-framed requests to a gRPC server given they handle serialization / deserialization of messages themselves, either by depending on protobuf (without needing to depend on grpc) or reimplementing the logic themselves.
As this is an advanced API, I think it's good to keep it small since it won't be as well tested as normal APIs. I've only exposed the most flexible APIs without providing any extra helpers as a result.
/cc @adriancole This should finish the ungrpc'ing of zipkin
=> Add UnaryGrpcClient.

core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
Motivation:
There's not really a need to set the `SO_KEEPALIVE` socket option in a
modern socket programming, because the keepalive interval is way longer
than what users usually want and it is often difficult to configure the
interval.
Modifications:
- Remove the code that sets `SO_KEEPALIVE` channel option on the client
side.
Result:
We don't waste time setting an additional channel option.
=> Do not set SO_KEEPALIVE socket option by default

logback/src/main/java/com/linecorp/armeria/common/logback/BuiltInProperty.java, logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporterBuilder.java, logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExporterBuilderTest.java, site/src/sphinx/advanced-logging.rst
For #489
I applied a wildcard `*` pattern about builtin properties. We can also adopt a wildcard about `headers` or `attrs`. But it can be caused some overhead to by logging.
I also specified to document that the wildcard applies only to the `builtin` property.
=> Allow using wildcards with RequestContextExportingAppender

README.md, site/src/sphinx/index.rst
.. because it just looks better.
=> Link to https://go.java/ instead of https://java.oracle.com/

core/src/main/java/com/linecorp/armeria/common/SessionProtocol.java, core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java, zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java, zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java, zipkin/src/test/java/com/linecorp/armeria/internal/tracing/SpanTagsTest.java, zipkin/src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceTest.java
Motivation:
The Zipkin span tag `http.url` has to be a valid addressable URL that
starts with `http://` or `https://`. We currently use `Scheme.uriText()`
which may be surprising to users.
Modifications:
- Make sure `http.url` starts with `http://` or `https://` for HTTP(S)
endpoints.
- Add `http.protocol` and `http.serfmt`.
Result:
Less surprising behavior.
=> Fix `http.url` Zipkin span tag and add `http.protocol` and `http.serfmt`

core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunction.java, core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java, core/src/main/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunction.java, core/src/test/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunctionTest.java, core/src/test/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunctionTest.java, core/src/test/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunctionTest.java, site/src/sphinx/server-annotated-service.rst
**Related-Issue:** https://github.com/line/armeria/issues/1584
**Motivation:**
Currently, it is possible to convert the request body to `byte[]`, `HttpData`, `String`, `CharSequence` only for a specific `content-type`.
If the converters can convert the body to `byte[]`, `HttpData`, `String`, `CharSequence` regardless of `content-type`, a user can easily convert the request body to specific result type what they want.
**Modification:**
- In `JacksonRequestConverterFunction`, pass the request to the next `RequestConverterFunction` if it failed to deserialize its content.
- In `ByteArrayRequestConverterFunction` and `StringRequestConverterFunction`, the request body can be converted to `expectedResultType` regardless of `content-type`.
**Result:**
A user can convert the request body to …
=> Enable to convert request body to expected result type regardless of content-type

docs-client/src/containers/MethodPage/DebugPage.tsx, docs-client/src/lib/transports/annotated-http.ts, docs-client/src/lib/transports/grpc-unframed.ts, docs-client/src/lib/transports/thrift.ts, docs-client/src/lib/transports/transport.ts
Motivation:
- Rarely, I want to copy a debug request to a curl command to put
additional headers to the request. Even if I can copy it from the dev
tools provided by browsers, opening them is annoying.
Modifications:
- Introduced a 'Copy as a curl command' button
- It copies the converted command to the clipboard, but not intuitive...
- Added some methods to support curl export in `Transport` class
- Each three transports has its own MIME type and body format to make
a request in text
Result:
- Close #196
For your reference,
<kbd><img src="https://cl.ly/35f9d965b508/2019-04-28_20-57-08.png"></kbd>
<kbd><img src="https://cl.ly/d655bfd6042d/2019-04-28_20-58-26.png"></kbd>
<kbd><img src="https://cl.ly/387928a10807/2019-04-28_20-59-14.png"></kbd>
=> Introduce 'Copy as a curl command' button to a debug request window

grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/AbstractUnaryGrpcService.java, grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
Users like zipkin can use access to unsafe buffers to maximize performance, and it's not so hard to support it so may as well.
=> Add AbstractUnsafeUnaryGrpcService for really advanced and unsafe users.

core/src/main/java/com/linecorp/armeria/common/Flags.java
Currently it is very difficult to know what ciphers are supported by a given armeria-based server that uses OpenSSL (JDK users can look at JDK's documentation) because OpenSSL may be boring, or system, depending on configuration, and the version always changes. This PR adds a flag to dump information about ciphers so users can see the exact ciphers that would be used in their environment.
I tried also using `getEnabledProtocols` to see what protocols are enabled by default, but it always seems to return SSLV2 and TLS1, 1.1, even though when I use `testssl.sh`, it always only shows TLS1.2, so for now I haven't tried logging that since I don't know how to get the right value.
`-Dcom.linecorp.armeria.dumpOpenSslInfo=true`
For #1711
=> Add a flag that can dump available ciphers on startup.

core/src/main/java/com/linecorp/armeria/common/HttpRequest.java, core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java, core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java, core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java, core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java, core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java, core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java, core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java, core/src/test/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilderTest.java, site/src/sphinx/advanced-structured-logging.rst, site/src/sphinx/server-access-log.rst, site/src/sphinx/server-basics.rst, tomcat/src/test/java/com/linecorp/armeria/server/tomcat/UnmanagedTomcatServiceTest.java
Motivation:
We fill the `:scheme` and `:authority` header in `HttpServerHander`.
However, the `HttpHeaders` is immutable now, it's better to fill the headers when we build it.
Modification:
- Fii the `:scheme` and `:authority` header in `Http1RequestDecoder` and `Http2RequestDecoder`
Result:
- Fix #1773
=> Fill scheme and authority pseudo headers in the request decoder

core/src/main/java/com/linecorp/armeria/client/encoding/DeflateStreamDecoderFactory.java, core/src/main/java/com/linecorp/armeria/client/encoding/GzipStreamDecoderFactory.java, core/src/main/java/com/linecorp/armeria/client/encoding/HttpDecodedResponse.java, core/src/main/java/com/linecorp/armeria/client/encoding/HttpDecodingClient.java, core/src/main/java/com/linecorp/armeria/client/encoding/StreamDecoderFactory.java, core/src/main/java/com/linecorp/armeria/client/encoding/ZlibStreamDecoder.java, core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java, core/src/test/java/com/linecorp/armeria/client/encoding/AbstractStreamDecoderTest.java, core/src/test/java/com/linecorp/armeria/client/encoding/HttpDecodedResponseTest.java, core/src/test/java/com/linecorp/armeria/client/encoding/ZlibStreamDecoderTest.java
Currently, HTTP decoding always returns unpooled data, even if a user requested pooled objects. This allows HTTP decoding to return pooled objects if any of the inputs were pooled, which indicates the user requested pooled objects.
Also added a minor optimization for the common case where calls to get the decoded output only return one buffer.
Came up in https://github.com/apache/incubator-zipkin/pull/2595
=> Return pooled buffers from HTTP decoded responses when requested.

grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientFactory.java, grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Motivation:
- Current gRPC client that built without path makes a request without
root path(slash).
For example, when gRPC client call "hello()" method, the request path
will be "{scheme}://{authority}hello".
Root path(slash) need to be located at the next of "{authority}".
Modification:
- When URI does not have any path value, URI having root path(slash)
will be passed for DefaultClientBuilderParams
Result:
- gRPC client built without path can send request correctly.
=> Make gRPC client built without path work correctly

core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java, core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java, grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java, grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
Currently, trailers are not added when the response is trailers-only. This means a user's call to `addAdditionalResponseTrailer` may be ignored based on whether the response has a stream of objects or only the trailers, which can be hard for gRPC users where both situations occur.
Also added a unit test demonstrating adding a protobuf to response trailers and using a server interceptor to replace exceptions.
=> Fix additional trailers are not added for trailers-only responses and add some advanced gRPC unit tests.
